// Glossary for PHYS — SC 11th-grade Physics.
// Terms expected for a standard high school Physics course.

export interface GlossaryEntry {
  term: string;
  definition: string;
}

export const glossary: GlossaryEntry[] = [
  // ── Kinematics ────────────────────────────────────────────────
  { term: 'Displacement',        definition: 'The vector change in position from start to finish — a straight-line measurement with direction. Differs from distance, which is the total path length. A round trip has distance = total path but displacement = 0.' },
  { term: 'Velocity',            definition: 'The rate of change of displacement with time (Δx/Δt). A vector quantity — it has both magnitude (speed) and direction. Average velocity = total displacement / total time; instantaneous velocity is the velocity at a single moment.' },
  { term: 'Acceleration',        definition: 'The rate of change of velocity with time (Δv/Δt). A vector measured in m/s². Positive: speeding up in the positive direction (or slowing down in the negative direction). An object can have zero velocity and non-zero acceleration (e.g., a ball at the top of its arc).' },
  { term: 'Free fall',           definition: 'Motion under the influence of gravity alone, with no air resistance. All objects near Earth\'s surface fall with the same acceleration g = 9.8 m/s² downward, regardless of mass. Galileo demonstrated this by dropping objects from the Leaning Tower of Pisa.' },
  { term: 'Projectile motion',   definition: 'Two-dimensional motion under gravity where horizontal velocity is constant (no horizontal force) and vertical velocity changes at g = 9.8 m/s² downward. The horizontal and vertical motions are completely independent and are solved separately using kinematic equations.' },
  { term: 'Kinematics',          definition: 'The branch of physics describing HOW objects move (position, velocity, acceleration, time) without asking WHY they move. The SUVAT equations (v = u + at, s = ut + ½at², v² = u² + 2as) are the core tools. Kinematics does not involve forces.' },

  // ── Energy & Momentum ─────────────────────────────────────────
  { term: 'Kinetic energy',      definition: 'The energy an object has due to its motion. KE = ½mv². Always non-negative. Doubled velocity means 4× the kinetic energy (squared relationship). Unit: Joule (J). A 2 kg ball at 3 m/s has KE = ½(2)(9) = 9 J.' },
  { term: 'Potential energy',    definition: 'Stored energy due to position or configuration. Gravitational PE = mgh (depends on height). Elastic PE = ½kx² (stored in a compressed/stretched spring). Both can convert to kinetic energy. The choice of reference height for GPE is arbitrary — only changes in PE matter.' },
  { term: 'Conservation of energy', definition: 'In an isolated system with only conservative forces, total mechanical energy (KE + PE) is constant. Energy can transform between forms (KE ↔ PE ↔ elastic PE) but the total never changes. Friction converts mechanical energy to thermal energy (heat), removing it from the mechanical system.' },
  { term: 'Work',                definition: 'The transfer of energy by a force acting over a distance: W = Fd cos θ, where θ is the angle between force and displacement. Unit: Joule (J). A force perpendicular to motion does zero work (cos 90° = 0). Negative work slows objects down; positive work speeds them up.' },
  { term: 'Momentum',            definition: 'The product of an object\'s mass and velocity: p = mv. A vector with units kg·m/s. Momentum is conserved in any isolated system (no external net force). The more momentum an object has, the harder it is to stop — both mass and velocity matter.' },
  { term: 'Impulse',             definition: 'The change in momentum of an object: J = FΔt = Δp. A force applied over a time interval changes an object\'s momentum. Extending collision time reduces the force for the same momentum change — the physics behind airbags, padded dashboards, and catching a ball with a relaxed hand.' },
  { term: 'Elastic collision',   definition: 'A collision in which both momentum AND kinetic energy are conserved. Objects bounce off each other without permanent deformation. Ideal billiard ball collisions approximate elastic collisions. In perfectly elastic collisions between equal masses, the moving object stops and the stationary one moves at the original speed.' },
  { term: 'Inelastic collision', definition: 'A collision in which momentum is conserved but kinetic energy is NOT. Some KE is converted to heat, sound, or deformation. In a perfectly inelastic collision, objects stick together — maximum kinetic energy is lost. All real collisions are at least slightly inelastic.' },

  // ── Waves & Sound ─────────────────────────────────────────────
  { term: 'Wavelength',          definition: 'The distance between two successive identical points on a wave (e.g., crest to crest, or compression to compression). Symbol: λ (lambda). Units: meters. Related to frequency by v = fλ. Longer wavelength → lower frequency (at constant speed).' },
  { term: 'Frequency',           definition: 'The number of complete wave cycles passing a point per second. Symbol: f. Unit: Hertz (Hz = cycles/s). Determines pitch for sound and color for light. Related to period by f = 1/T. The frequency of a wave is determined by the source and does not change when the wave enters a new medium.' },
  { term: 'Amplitude',           definition: 'The maximum displacement of a wave from its equilibrium (rest) position. Determines the intensity/energy of the wave: intensity ∝ amplitude². Larger amplitude = louder sound or brighter light. Amplitude does NOT affect wave speed in a given medium.' },
  { term: 'Transverse wave',     definition: 'A wave in which particle oscillation is PERPENDICULAR to the direction of wave travel. Examples: light (electromagnetic), waves on a string, seismic S-waves. Transverse waves can be polarized — their oscillation can be restricted to one plane. Sound is NOT transverse.' },
  { term: 'Longitudinal wave',   definition: 'A wave in which particle oscillation is PARALLEL to the direction of wave travel, creating alternating compressions (high pressure) and rarefactions (low pressure). Sound is the primary example. Longitudinal waves require a medium and cannot be polarized.' },
  { term: 'Standing wave',       definition: 'A wave pattern that appears stationary, formed when two identical waves traveling in opposite directions interfere. Has fixed nodes (zero displacement) and antinodes (maximum displacement). Occurs in guitar strings, organ pipes, and any resonant cavity. The frequencies at which standing waves form are called harmonics.' },
  { term: 'Doppler Effect',      definition: 'The apparent change in frequency (and pitch/color) of a wave due to relative motion between source and observer. Source approaching → compressed waves → higher frequency (higher pitch). Source receding → stretched waves → lower frequency (lower pitch). Applies to sound and light; light Doppler shifting is called redshift (receding) or blueshift (approaching).' },

  // ── Light & Optics ────────────────────────────────────────────
  { term: 'Refraction',          definition: 'The bending of a wave (usually light) as it passes from one medium to another with a different speed. Described by Snell\'s Law: n₁sinθ₁ = n₂sinθ₂. Light bends toward the normal when entering a denser medium (slowing down) and away when entering a less dense medium (speeding up).' },
  { term: 'Total internal reflection', definition: 'Complete reflection of light back into a denser medium when the angle of incidence exceeds the critical angle and light is traveling from a denser to a less dense medium. No light refracts out — 100% reflects. The basis of fiber optic communication cables.' },
  { term: 'Index of refraction', definition: 'A dimensionless number n = c/v describing how much a medium slows light compared to a vacuum. Higher n = slower light = more bending at interfaces. Vacuum: n = 1 (exactly). Air: n ≈ 1.00. Water: n ≈ 1.33. Glass: n ≈ 1.5. Diamond: n ≈ 2.42.' },
  { term: 'Electromagnetic spectrum', definition: 'The complete range of electromagnetic radiation ordered by frequency (or wavelength): Radio → Microwave → Infrared → Visible → Ultraviolet → X-ray → Gamma ray. All travel at c = 3×10⁸ m/s in a vacuum. Higher frequency = shorter wavelength = more energy per photon. Visible light is a tiny portion of the full spectrum.' },
  { term: 'Snell\'s Law',         definition: 'The quantitative law of refraction: n₁ sinθ₁ = n₂ sinθ₂. Angles are measured from the NORMAL to the surface. When a ray passes into a higher-n medium, the angle decreases (bends toward normal). When passing into a lower-n medium, the angle increases (bends away).' },

  // ── Electricity & Circuits ────────────────────────────────────
  { term: 'Ohm\'s Law',          definition: 'V = IR. Voltage (V) equals current (I) times resistance (R). More voltage drives more current; more resistance reduces current. Applies to many (but not all) materials — resistors that follow Ohm\'s Law are called "ohmic." Units: V = Volts, I = Amperes, R = Ohms (Ω).' },
  { term: 'Electric current',    definition: 'The rate of flow of electric charge: I = Q/t. Measured in Amperes (A = C/s). Conventional current flows from positive to negative terminal (opposite to electron flow). In series circuits, the same current flows through all components. In parallel circuits, current divides among branches.' },
  { term: 'Electric resistance',  definition: 'Opposition to the flow of electric current. Measured in Ohms (Ω). Resistance depends on material (resistivity), length, and cross-sectional area. Longer wire = more resistance; thicker wire = less resistance. Resistors in series add directly; in parallel, total resistance decreases.' },
  { term: 'Electric power',       definition: 'The rate of energy transfer in an electrical circuit. P = IV = I²R = V²/R. Measured in Watts (W). Energy E = Pt (in Joules). Power dissipated as heat in a resistor is "wasted" energy. Your electricity bill is based on kilowatt-hours (kWh) = 3.6 × 10⁶ J.' },
  { term: 'Kirchhoff\'s Laws',    definition: 'Two rules for analyzing circuits: (1) Junction Rule (KCL): sum of currents entering a junction equals sum leaving — conservation of charge. (2) Loop Rule (KVL): sum of all voltage drops around any closed loop equals zero — conservation of energy. Together they allow analysis of any circuit.' },

  // ── Magnetism ─────────────────────────────────────────────────
  { term: 'Magnetic field',      definition: 'A vector field (symbol B) created by moving charges or permanent magnets that exerts forces on other moving charges or magnets. Measured in Tesla (T). Field lines run from North to South outside a magnet. Denser lines = stronger field. A stationary charge creates no magnetic field.' },
  { term: 'Electromagnetic induction', definition: 'The production of an EMF (and thus current) in a conductor due to a changing magnetic flux. Described by Faraday\'s Law: EMF = −NΔΦ/Δt. The basis for all electrical generators and transformers. Discovered by Michael Faraday in 1831.' },
  { term: 'Faraday\'s Law',      definition: 'The induced EMF in a coil equals the negative rate of change of magnetic flux: EMF = −NΔΦ/Δt. N = number of turns, Φ = magnetic flux = BAcosθ. Flux can change by varying B, area, or angle. The negative sign encodes Lenz\'s Law.' },
  { term: 'Lenz\'s Law',         definition: 'The induced current flows in the direction that OPPOSES the change in magnetic flux that caused it. A consequence of conservation of energy — if induced current reinforced the change, runaway energy amplification would occur. The induced current creates a B field opposing the original change.' },
  { term: 'Transformer',         definition: 'A device that uses electromagnetic induction to change AC voltage levels. Equation: V₁/V₂ = N₁/N₂. Step-up: more secondary turns → higher voltage, lower current. Step-down: fewer secondary turns → lower voltage, higher current. Power is conserved (V₁I₁ = V₂I₂). Used in power transmission and phone chargers.' },
];
