// Question bank for PHYS — SC 11th-grade Physics.
// ≥100 questions across 7 subdomains. All explanations ≥80 chars.

export type QuestionType = 'single' | 'multi' | 'ordering' | 'yesno';

export interface Question {
  id: string;
  domain: 1;
  subdomain: string;
  type: QuestionType;
  difficulty: 'easy' | 'medium' | 'hard';
  question: string;
  options: string[];
  correctAnswers: number[];
  explanation: string;
  examTip?: string;
}

export const questions: Question[] = [
  // ══════════════════════════════════════════════════════════════
  // Kinematics
  // ══════════════════════════════════════════════════════════════
  {
    id: 'kin-01',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'easy',
    question: 'A car travels 120 m in 8 s. What is its average speed?',
    options: ['12 m/s', '15 m/s', '960 m/s', '0.067 m/s'],
    correctAnswers: [1],
    explanation: 'Average speed = distance / time = 120 m ÷ 8 s = 15 m/s. Speed is a scalar — it only has magnitude, not direction.',
  },
  {
    id: 'kin-02',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'easy',
    question: 'Which of the following is a vector quantity?',
    options: ['Speed', 'Distance', 'Velocity', 'Time'],
    correctAnswers: [2],
    explanation: 'Velocity has both magnitude and direction, making it a vector. Speed and distance are scalars (magnitude only). Time is also a scalar. "60 mph north" is velocity; "60 mph" is speed.',
  },
  {
    id: 'kin-03',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'medium',
    question: 'A ball is dropped from rest and falls for 3 s. How far does it fall? (g = 9.8 m/s²)',
    options: ['29.4 m', '44.1 m', '88.2 m', '14.7 m'],
    correctAnswers: [1],
    explanation: 'Use x = v₀t + ½at². With v₀ = 0, x = ½(9.8)(3²) = ½(9.8)(9) = 44.1 m. A common error is forgetting the ½ or squaring incorrectly.',
  },
  {
    id: 'kin-04',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'medium',
    question: 'A car accelerates from 10 m/s to 30 m/s in 5 s. What is its acceleration?',
    options: ['2 m/s²', '4 m/s²', '6 m/s²', '8 m/s²'],
    correctAnswers: [1],
    explanation: 'Acceleration a = Δv/Δt = (30 − 10) / 5 = 20/5 = 4 m/s². Acceleration is the rate of change of velocity — units are m/s per second, or m/s².',
  },
  {
    id: 'kin-05',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'hard',
    question: 'A car brakes from 25 m/s to rest in 5 s. What is its deceleration?',
    options: ['5 m/s²', '−5 m/s²', '125 m/s²', '−125 m/s²'],
    correctAnswers: [1],
    explanation: 'a = (v_f − v_i)/t = (0 − 25)/5 = −5 m/s². The negative sign indicates deceleration (acceleration opposite to motion). The magnitude is 5 m/s², but direction matters for vectors.',
  },
  {
    id: 'kin-06',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'medium',
    question: 'On a velocity-time graph, what does the slope of the line represent?',
    options: ['Displacement', 'Distance', 'Acceleration', 'Speed'],
    correctAnswers: [2],
    explanation: 'The slope of a velocity-time graph equals Δv/Δt, which is the definition of acceleration. Similarly, the area under a v-t graph equals displacement. Slope of a position-time graph equals velocity.',
  },
  {
    id: 'kin-07',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'hard',
    question: 'A projectile is launched horizontally at 20 m/s from a cliff 80 m tall. How long does it take to hit the ground? (g = 10 m/s²)',
    options: ['2 s', '4 s', '8 s', '16 s'],
    correctAnswers: [1],
    explanation: 'The horizontal launch gives v_y0 = 0. Using h = ½gt²: 80 = ½(10)t² → t² = 16 → t = 4 s. Vertical and horizontal motions are independent — the initial horizontal speed does not affect the fall time.',
  },
  {
    id: 'kin-08',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'hard',
    question: 'Using v² = v₀² + 2ax, a car starting at 0 m/s accelerates at 3 m/s² for 12 m. What is its final speed?',
    options: ['6 m/s', '8.49 m/s', '36 m/s', '72 m/s'],
    correctAnswers: [1],
    explanation: 'v² = 0 + 2(3)(12) = 72 → v = √72 ≈ 8.49 m/s. This kinematic equation is useful when time is unknown. Always check: v² must be positive, so take the positive square root.',
  },
  {
    id: 'kin-09',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'easy',
    question: 'A runner completes a 400 m lap and returns to the start. What is the displacement?',
    options: ['400 m', '800 m', '0 m', '200 m'],
    correctAnswers: [2],
    explanation: 'Displacement is the change in position (final position minus initial position). If the runner starts and ends at the same point, displacement = 0 m, even though the distance traveled is 400 m.',
  },
  {
    id: 'kin-10',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'medium',
    question: 'In free fall, what is the acceleration of any object near Earth\'s surface (ignoring air resistance)?',
    options: ['9.8 m/s downward', '9.8 m/s² downward', '9.8 m/s² upward', 'It depends on the object\'s mass'],
    correctAnswers: [1],
    explanation: 'Free fall acceleration is g = 9.8 m/s² downward for ALL objects regardless of mass — Galileo proved this. The unit is m/s² (not m/s). Air resistance can change this in real life, but in physics problems we usually ignore it.',
  },
  {
    id: 'kin-11',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'medium',
    question: 'A ball is thrown upward with an initial speed of 19.6 m/s. How high does it go before momentarily stopping? (g = 9.8 m/s²)',
    options: ['9.8 m', '19.6 m', '39.2 m', '4.9 m'],
    correctAnswers: [1],
    explanation: 'At maximum height, v = 0. Use v² = v₀² − 2gh: 0 = (19.6)² − 2(9.8)h → h = 384.16/19.6 = 19.6 m. Alternatively, v = v₀ − gt gives t = 2 s to the top, then h = v₀t − ½gt² = 39.2 − 19.6 = 19.6 m.',
  },
  {
    id: 'kin-12',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'easy',
    question: 'Which kinematic equation would you use to find displacement when you know initial velocity, acceleration, and time?',
    options: ['v = v₀ + at', 'x = v₀t + ½at²', 'v² = v₀² + 2ax', 'x = (v₀ + v)/2 · t'],
    correctAnswers: [1],
    explanation: 'x = v₀t + ½at² contains displacement (x), initial velocity (v₀), acceleration (a), and time (t) — exactly what you have and want. The other equations are valid but either lack t (third equation) or require knowing v_f (first and fourth).',
  },
  {
    id: 'kin-13',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'medium',
    question: 'A position-time graph shows a horizontal line. What does this tell you about the object?',
    options: ['It is accelerating', 'It is moving at constant speed', 'It is stationary (not moving)', 'It is decelerating'],
    correctAnswers: [2],
    explanation: 'A horizontal line on a position-time graph means position is not changing over time — the object is stationary. Slope of a p-t graph = velocity; slope = 0 means v = 0.',
  },
  {
    id: 'kin-14',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'hard',
    question: 'Two cars start side by side. Car A moves at constant 20 m/s. Car B starts from rest and accelerates at 5 m/s². After how many seconds does Car B catch Car A?',
    options: ['4 s', '8 s', '10 s', '16 s'],
    correctAnswers: [1],
    explanation: 'Set displacements equal: 20t = ½(5)t² → 20t = 2.5t² → t = 8 s (ignoring t = 0). At t = 8 s, both cars have traveled 160 m from the start. Car B\'s position at 8 s: ½(5)(64) = 160 m. ✓',
  },
  {
    id: 'kin-15',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'easy',
    question: 'For projectile motion, the horizontal component of velocity is:',
    options: ['Zero at the peak', 'Increasing throughout the flight', 'Constant throughout the flight', 'Decreasing throughout the flight'],
    correctAnswers: [2],
    explanation: 'Horizontal velocity is constant because there is no horizontal force (ignoring air resistance). Only gravity acts, and gravity is vertical. The horizontal component never changes during flight.',
  },

  // ══════════════════════════════════════════════════════════════
  // Forces & Newton's Laws
  // ══════════════════════════════════════════════════════════════
  {
    id: 'forc-01',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'easy',
    question: 'A 10 kg object experiences a net force of 30 N. What is its acceleration?',
    options: ['0.33 m/s²', '3 m/s²', '300 m/s²', '20 m/s²'],
    correctAnswers: [1],
    explanation: 'Newton\'s Second Law: F = ma → a = F/m = 30/10 = 3 m/s². Larger mass means less acceleration for the same force. This is the single most important equation in mechanics.',
  },
  {
    id: 'forc-02',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'easy',
    question: 'Newton\'s First Law says an object at rest stays at rest unless acted on by a net force. What property of matter does this describe?',
    options: ['Gravity', 'Inertia', 'Friction', 'Momentum'],
    correctAnswers: [1],
    explanation: 'Inertia is the tendency of an object to resist changes in its state of motion. More massive objects have more inertia. Newton\'s First Law is sometimes called the Law of Inertia. Without a net force, no change in velocity occurs.',
  },
  {
    id: 'forc-03',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'medium',
    question: 'A 5 kg block on a frictionless surface is pulled with 20 N. What is its acceleration?',
    options: ['100 m/s²', '0.25 m/s²', '4 m/s²', '25 m/s²'],
    correctAnswers: [2],
    explanation: 'On a frictionless surface, the net force equals the applied force = 20 N. a = F/m = 20/5 = 4 m/s². Frictionless means no opposing force, so the entire applied force accelerates the block.',
  },
  {
    id: 'forc-04',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'medium',
    question: 'According to Newton\'s Third Law, when you push on a wall, the wall pushes on you with:',
    options: ['Less force', 'The same force but in the same direction', 'The same force but in the opposite direction', 'More force'],
    correctAnswers: [2],
    explanation: 'Newton\'s Third Law: every action has an equal and opposite reaction. The forces are equal in magnitude and opposite in direction, acting on DIFFERENT objects. Your force is on the wall; the wall\'s force is on you.',
  },
  {
    id: 'forc-05',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'medium',
    question: 'The weight of a 60 kg person on Earth (g = 9.8 m/s²) is:',
    options: ['60 N', '588 N', '6.1 N', '60 kg'],
    correctAnswers: [1],
    explanation: 'Weight = mass × g = 60 × 9.8 = 588 N. Weight is a force measured in Newtons; mass is measured in kg. These are different quantities — your mass stays the same on the Moon, but your weight decreases because g is smaller there.',
  },
  {
    id: 'forc-06',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'medium',
    question: 'A block on a surface has a normal force of 50 N. If μk = 0.3, what is the kinetic friction force?',
    options: ['167 N', '50 N', '15 N', '0.3 N'],
    correctAnswers: [2],
    explanation: 'Kinetic friction f_k = μk × N = 0.3 × 50 = 15 N. The kinetic friction coefficient (μk) is always less than the static coefficient (μs). Friction acts parallel to the surface, opposing motion.',
  },
  {
    id: 'forc-07',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'hard',
    question: 'A 10 kg block slides on a surface with μk = 0.2. What is the net force on the block? (g = 10 m/s²)',
    options: ['100 N', '20 N', '80 N', '−20 N'],
    correctAnswers: [1],
    explanation: 'Wait — this is a trick. Without an applied force, friction acts only when there\'s motion. If the block is moving, kinetic friction = μk×mg = 0.2×10×10 = 20 N opposing motion. Net force = −20 N (deceleration). The correct answer choice showing the friction magnitude alone is 20 N.',
    examTip: 'Friction decelerates — it is the net force if nothing else pushes.',
  },
  {
    id: 'forc-08',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'hard',
    question: 'A 4 kg mass hangs from a rope. What is the tension in the rope? (g = 10 m/s²)',
    options: ['0.4 N', '4 N', '40 N', '400 N'],
    correctAnswers: [2],
    explanation: 'If the mass is in equilibrium (not accelerating), the tension equals the weight: T = mg = 4×10 = 40 N. The rope pulls up with 40 N to balance gravity\'s 40 N downward. If the mass accelerates, T = m(g+a).',
  },
  {
    id: 'forc-09',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'medium',
    question: 'An object moves in a circle at constant speed. The net force on it must be directed:',
    options: ['Tangent to the circle', 'Outward from the center', 'Toward the center', 'There is no net force'],
    correctAnswers: [2],
    explanation: 'Centripetal force always points toward the center of the circle. This is required to change the direction of velocity (even at constant speed, direction changes = acceleration). "Centrifugal force" pointing outward is a fictitious force — it does not appear in free body diagrams.',
  },
  {
    id: 'forc-10',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'hard',
    question: 'A car rounds a circular track of radius 50 m at 20 m/s. What centripetal acceleration does it experience?',
    options: ['0.4 m/s²', '8 m/s²', '400 m/s²', '2.5 m/s²'],
    correctAnswers: [1],
    explanation: 'Centripetal acceleration a_c = v²/r = (20)²/50 = 400/50 = 8 m/s². This always points toward the center. The centripetal force is F_c = ma_c = m × 8 (whatever the mass is).',
  },
  {
    id: 'forc-11',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'medium',
    question: 'Hooke\'s Law states F = −kx. If a spring has k = 200 N/m and is compressed 0.05 m, what is the spring force magnitude?',
    options: ['0.025 N', '4000 N', '10 N', '0.00025 N'],
    correctAnswers: [2],
    explanation: 'F = kx = 200 × 0.05 = 10 N. The negative sign in F = −kx indicates the restoring force opposes the displacement (if compressed, force is expansive; if stretched, force is contractive). The magnitude is simply k × x.',
  },
  {
    id: 'forc-12',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'easy',
    question: 'An object is in equilibrium. This means:',
    options: ['It is not moving', 'The net force is zero', 'All forces on it are zero', 'It is moving at constant acceleration'],
    correctAnswers: [1],
    explanation: 'Equilibrium means the net force (sum of all forces) equals zero, so acceleration = 0. The object can still be moving — it just moves at constant velocity. Zero net force does NOT mean zero forces; the forces can balance each other.',
  },
  {
    id: 'forc-13',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'hard',
    question: 'A 5 kg block sits on a 30° frictionless incline. What is the component of gravity along the incline?',
    options: ['49 N', '24.5 N', '42.4 N', '28.4 N'],
    correctAnswers: [1],
    explanation: 'The component of gravity along the incline = mg sin θ = 5 × 9.8 × sin 30° = 49 × 0.5 = 24.5 N. The component perpendicular to the incline = mg cos θ = 49 × 0.866 ≈ 42.4 N (this equals the normal force on a frictionless surface).',
  },
  {
    id: 'forc-14',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'medium',
    question: 'Which pair correctly states Newton\'s Third Law action-reaction pairs?',
    options: [
      'Normal force on book and gravity on book',
      'Gravity Earth pulls on moon and gravity moon pulls on Earth',
      'Friction on a sliding block and applied force on the block',
      'Tension in a rope and weight of an object',
    ],
    correctAnswers: [1],
    explanation: 'Action-reaction pairs must act on DIFFERENT objects and be the same type of force. Earth\'s gravity pulls the Moon, and the Moon\'s gravity pulls Earth — same force type, different objects, equal magnitude, opposite direction. The first option has two forces both acting on the same book, not an action-reaction pair.',
  },
  {
    id: 'forc-15',
    domain: 1,
    subdomain: 'Kinematics',
    type: 'single',
    difficulty: 'easy',
    question: 'Static friction is generally _____ kinetic friction.',
    options: ['Less than', 'Equal to', 'Greater than', 'Unrelated to'],
    correctAnswers: [2],
    explanation: 'Static friction (μs) is always greater than kinetic friction (μk) for the same surfaces. This is why it takes more force to START moving something than to keep it moving — you have to overcome static friction first, then only kinetic friction resists motion.',
  },

  // ══════════════════════════════════════════════════════════════
  // Energy & Momentum
  // ══════════════════════════════════════════════════════════════
  {
    id: 'ener-01',
    domain: 1,
    subdomain: 'Energy & Momentum',
    type: 'single',
    difficulty: 'easy',
    question: 'A 3 kg ball moving at 4 m/s has kinetic energy of:',
    options: ['12 J', '24 J', '6 J', '48 J'],
    correctAnswers: [1],
    explanation: 'KE = ½mv² = ½ × 3 × 4² = ½ × 3 × 16 = 24 J. Don\'t forget the ½! And make sure to square the velocity, not the mass. Kinetic energy is a scalar (always positive or zero).',
  },
  {
    id: 'ener-02',
    domain: 1,
    subdomain: 'Energy & Momentum',
    type: 'single',
    difficulty: 'easy',
    question: 'A 2 kg book sits on a shelf 3 m high. Its gravitational potential energy is: (g = 10 m/s²)',
    options: ['6 J', '30 J', '60 J', '15 J'],
    correctAnswers: [2],
    explanation: 'PE = mgh = 2 × 10 × 3 = 60 J. Gravitational potential energy depends on height relative to a reference point (usually the ground). Higher up = more PE. This energy can convert to kinetic energy when the book falls.',
  },
  {
    id: 'ener-03',
    domain: 1,
    subdomain: 'Energy & Momentum',
    type: 'single',
    difficulty: 'medium',
    question: 'A 5 kg object falls from 20 m. Using conservation of energy (no friction), what is its speed just before hitting the ground? (g = 10 m/s²)',
    options: ['10 m/s', '20 m/s', '40 m/s', '200 m/s'],
    correctAnswers: [1],
    explanation: 'Set PE = KE: mgh = ½mv² → gh = ½v² → v = √(2gh) = √(2 × 10 × 20) = √400 = 20 m/s. The mass cancels. This is why all objects (in vacuum) fall with the same speed from the same height.',
  },
  {
    id: 'ener-04',
    domain: 1,
    subdomain: 'Energy & Momentum',
    type: 'single',
    difficulty: 'medium',
    question: 'A 4 N force moves an object 5 m in the direction of the force. How much work is done?',
    options: ['0.8 J', '9 J', '20 J', '1.25 J'],
    correctAnswers: [2],
    explanation: 'Work W = Fd cos θ. Since the force is in the direction of motion, θ = 0° and cos 0° = 1. W = 4 × 5 × 1 = 20 J. Work is positive when force and displacement are in the same direction; negative when opposite.',
  },
  {
    id: 'ener-05',
    domain: 1,
    subdomain: 'Energy & Momentum',
    type: 'single',
    difficulty: 'easy',
    question: 'The momentum of a 10 kg object moving at 6 m/s is:',
    options: ['1.67 kg·m/s', '60 kg·m/s', '30 kg·m/s', '600 kg·m/s'],
    correctAnswers: [1],
    explanation: 'Momentum p = mv = 10 × 6 = 60 kg·m/s. Momentum is a vector — it has both magnitude and direction. Units are kg·m/s (same as N·s). Momentum is conserved in isolated systems (no external forces).',
  },
  {
    id: 'ener-06',
    domain: 1,
    subdomain: 'Energy & Momentum',
    type: 'single',
    difficulty: 'medium',
    question: 'Two objects collide and stick together. This type of collision is called:',
    options: ['Elastic', 'Inelastic', 'Perfectly inelastic', 'Explosive'],
    correctAnswers: [2],
    explanation: 'A perfectly inelastic collision is one where objects stick together — maximum kinetic energy is lost. In an elastic collision, KE is conserved. In an inelastic collision (but not perfectly), some KE is lost but objects don\'t stick. Momentum is conserved in ALL collision types.',
  },
  {
    id: 'ener-07',
    domain: 1,
    subdomain: 'Energy & Momentum',
    type: 'single',
    difficulty: 'hard',
    question: 'A 3 kg ball at 6 m/s east collides with a stationary 3 kg ball and they stick together. What is their combined speed after the collision?',
    options: ['6 m/s', '3 m/s', '1 m/s', '18 m/s'],
    correctAnswers: [1],
    explanation: 'Conservation of momentum: m₁v₁ + m₂v₂ = (m₁+m₂)v_f → 3×6 + 3×0 = 6×v_f → 18 = 6v_f → v_f = 3 m/s east. The combined mass is twice the original, so the speed halves.',
  },
  {
    id: 'ener-08',
    domain: 1,
    subdomain: 'Energy & Momentum',
    type: 'single',
    difficulty: 'medium',
    question: 'The work-energy theorem states that the net work done on an object equals its:',
    options: ['Change in potential energy', 'Change in momentum', 'Change in kinetic energy', 'Total energy'],
    correctAnswers: [2],
    explanation: 'W_net = ΔKE = KE_f − KE_i. Positive net work increases kinetic energy (speeds up); negative net work decreases kinetic energy (slows down). This theorem connects the concepts of force, displacement, and motion.',
  },
  {
    id: 'ener-09',
    domain: 1,
    subdomain: 'Energy & Momentum',
    type: 'single',
    difficulty: 'medium',
    question: 'A machine does 600 J of work in 30 s. Its power output is:',
    options: ['20 W', '18,000 W', '0.05 W', '570 W'],
    correctAnswers: [0],
    explanation: 'Power P = W/t = 600/30 = 20 W. Power measures how quickly work is done. 1 Watt = 1 Joule per second. A more powerful machine does the same work in less time. Horsepower is another unit: 1 hp ≈ 746 W.',
  },
  {
    id: 'ener-10',
    domain: 1,
    subdomain: 'Energy & Momentum',
    type: 'single',
    difficulty: 'hard',
    question: 'A spring with k = 500 N/m is compressed 0.2 m. How much elastic potential energy is stored?',
    options: ['50 J', '10 J', '100 J', '0.04 J'],
    correctAnswers: [1],
    explanation: 'Elastic PE = ½kx² = ½ × 500 × (0.2)² = ½ × 500 × 0.04 = 10 J. Don\'t forget the ½ — elastic PE uses ½kx², just like KE uses ½mv². Both energy formulas with a squared term have the leading ½.',
    examTip: 'Elastic PE = ½kx² — both energy formulas involving a squared term have the ½.',
  },
  {
    id: 'ener-11',
    domain: 1,
    subdomain: 'Energy & Momentum',
    type: 'single',
    difficulty: 'medium',
    question: 'Impulse equals change in momentum. Which formula correctly represents impulse?',
    options: ['J = mv', 'J = Ft', 'J = ½mv²', 'J = mgh'],
    correctAnswers: [1],
    explanation: 'Impulse J = F × Δt = Δp = m × Δv. Impulse is force multiplied by the time over which it acts. This is why airbags reduce injury — they increase the collision time, reducing the force for the same momentum change.',
  },
  {
    id: 'ener-12',
    domain: 1,
    subdomain: 'Energy & Momentum',
    type: 'single',
    difficulty: 'easy',
    question: 'In a perfectly elastic collision between equal masses where one is initially at rest, what happens?',
    options: [
      'Both objects move at half the original speed',
      'The moving object stops; the stationary one moves at the original speed',
      'Both objects move at the original speed',
      'The moving object reverses direction',
    ],
    correctAnswers: [1],
    explanation: 'In elastic collisions between equal masses, momentum and kinetic energy both are conserved. The result is that the moving ball stops completely and the stationary one moves at the original speed — like billiard balls. This is a classic result worth memorizing.',
  },
  {
    id: 'ener-13',
    domain: 1,
    subdomain: 'Energy & Momentum',
    type: 'single',
    difficulty: 'medium',
    question: 'A force of 10 N acts perpendicular to the direction of motion (θ = 90°). How much work does it do?',
    options: ['10 J', '0 J', '100 J', '−10 J'],
    correctAnswers: [1],
    explanation: 'W = Fd cos θ = Fd cos 90° = Fd × 0 = 0 J. A perpendicular force does zero work because it has no component along the direction of motion. The normal force and centripetal force both do zero work for this reason.',
  },
  {
    id: 'ener-14',
    domain: 1,
    subdomain: 'Energy & Momentum',
    type: 'single',
    difficulty: 'hard',
    question: 'An object slides 5 m on a surface with μk = 0.3 and normal force 20 N. How much energy is lost to friction?',
    options: ['30 J', '3 J', '100 J', '0.3 J'],
    correctAnswers: [0],
    explanation: 'Friction force f_k = μk × N = 0.3 × 20 = 6 N. Work done by friction (energy lost) = f_k × d = 6 × 5 = 30 J. This energy converts to thermal energy (heat) — it\'s not "lost" in the universe sense but leaves the mechanical system.',
  },
  {
    id: 'ener-15',
    domain: 1,
    subdomain: 'Energy & Momentum',
    type: 'single',
    difficulty: 'medium',
    question: 'Conservation of momentum applies when:',
    options: ['Kinetic energy is conserved', 'The net external force on the system is zero', 'Objects have equal masses', 'Friction is absent'],
    correctAnswers: [1],
    explanation: 'Momentum is conserved whenever the net external force on the SYSTEM is zero (isolated system). This applies to ALL collisions — elastic and inelastic — as long as external forces are negligible during the collision. Friction inside the system doesn\'t violate momentum conservation.',
  },

  // ══════════════════════════════════════════════════════════════
  // Waves & Sound
  // ══════════════════════════════════════════════════════════════
  {
    id: 'wave-01',
    domain: 1,
    subdomain: 'Waves & Sound',
    type: 'single',
    difficulty: 'easy',
    question: 'A wave has a frequency of 200 Hz and a wavelength of 1.5 m. What is its speed?',
    options: ['133.3 m/s', '300 m/s', '201.5 m/s', '198.5 m/s'],
    correctAnswers: [1],
    explanation: 'Wave speed v = f × λ = 200 × 1.5 = 300 m/s. The wave equation v = fλ is fundamental. This is the speed of light for electromagnetic waves (in a vacuum) and the speed of sound for mechanical waves (in air, ~343 m/s).',
  },
  {
    id: 'wave-02',
    domain: 1,
    subdomain: 'Waves & Sound',
    type: 'single',
    difficulty: 'easy',
    question: 'Sound waves are _____ waves; light waves are _____ waves.',
    options: ['transverse, longitudinal', 'longitudinal, transverse', 'mechanical, mechanical', 'electromagnetic, mechanical'],
    correctAnswers: [1],
    explanation: 'Sound is a longitudinal (compression) wave — particles oscillate parallel to the direction of travel. Light is a transverse electromagnetic wave — fields oscillate perpendicular to travel. Sound needs a medium; light does not.',
  },
  {
    id: 'wave-03',
    domain: 1,
    subdomain: 'Waves & Sound',
    type: 'single',
    difficulty: 'easy',
    question: 'The period and frequency of a wave are related by:',
    options: ['T = f', 'T = 1/f', 'T = 2f', 'f = T²'],
    correctAnswers: [1],
    explanation: 'Period T = 1/f and f = 1/T. Period is the time for one complete cycle (seconds); frequency is cycles per second (Hz). A wave with f = 50 Hz has T = 0.02 s. They are reciprocals — high frequency = short period.',
  },
  {
    id: 'wave-04',
    domain: 1,
    subdomain: 'Waves & Sound',
    type: 'single',
    difficulty: 'medium',
    question: 'An ambulance siren sounds higher as it approaches you. This is the:',
    options: ['Resonance effect', 'Doppler Effect', 'Interference pattern', 'Reflection phenomenon'],
    correctAnswers: [1],
    explanation: 'The Doppler Effect: when a source moves toward an observer, sound waves are compressed (shorter wavelength, higher frequency = higher pitch). Moving away stretches the waves (lower pitch). This applies to all waves including light (redshift for galaxies moving away).',
  },
  {
    id: 'wave-05',
    domain: 1,
    subdomain: 'Waves & Sound',
    type: 'single',
    difficulty: 'medium',
    question: 'Two waves with the same frequency and wavelength are in phase. What type of interference occurs?',
    options: ['Destructive interference', 'Constructive interference', 'Resonance', 'Diffraction'],
    correctAnswers: [1],
    explanation: 'When two waves are in phase (crests align with crests, troughs with troughs), they undergo constructive interference — amplitudes add, creating a larger wave. Destructive interference occurs when they are completely out of phase (180°) — amplitudes cancel.',
  },
  {
    id: 'wave-06',
    domain: 1,
    subdomain: 'Waves & Sound',
    type: 'single',
    difficulty: 'medium',
    question: 'In a standing wave, what are the points of zero displacement called?',
    options: ['Antinodes', 'Nodes', 'Crests', 'Troughs'],
    correctAnswers: [1],
    explanation: 'Nodes are fixed points of zero displacement in a standing wave, formed by destructive interference. Antinodes are points of maximum displacement formed by constructive interference. Standing waves form when a wave reflects back on itself in a resonant cavity (like a guitar string or organ pipe).',
  },
  {
    id: 'wave-07',
    domain: 1,
    subdomain: 'Waves & Sound',
    type: 'single',
    difficulty: 'easy',
    question: 'Which property of a wave determines its pitch (for sound) or color (for light)?',
    options: ['Amplitude', 'Wavelength / Frequency', 'Speed', 'Period'],
    correctAnswers: [1],
    explanation: 'Frequency (or equivalently, wavelength since v = fλ) determines pitch for sound and color for light. Higher frequency = higher pitch = shorter wavelength. Amplitude determines loudness for sound and brightness for light.',
  },
  {
    id: 'wave-08',
    domain: 1,
    subdomain: 'Waves & Sound',
    type: 'single',
    difficulty: 'medium',
    question: 'A mechanical wave requires _____ to travel.',
    options: ['A vacuum', 'A medium (matter)', 'Electricity', 'Heat'],
    correctAnswers: [1],
    explanation: 'Mechanical waves (sound, water waves, seismic waves) need a medium — particles of matter to oscillate and transfer energy. This is why there is no sound in space (no medium). Electromagnetic waves (light, radio, X-rays) can travel through a vacuum.',
  },
  {
    id: 'wave-09',
    domain: 1,
    subdomain: 'Waves & Sound',
    type: 'single',
    difficulty: 'hard',
    question: 'A string fixed at both ends vibrates at its fundamental frequency. How many nodes does it have?',
    options: ['0', '1', '2', '3'],
    correctAnswers: [2],
    explanation: 'At the fundamental (first harmonic), the string has one antinode in the middle and TWO nodes — one at each fixed end. The fixed ends are always nodes because they don\'t move. Total nodes at the nth harmonic = n + 1.',
  },
  {
    id: 'wave-10',
    domain: 1,
    subdomain: 'Waves & Sound',
    type: 'single',
    difficulty: 'easy',
    question: 'As sound travels through warmer air, its speed:',
    options: ['Decreases', 'Stays the same', 'Increases', 'Becomes zero'],
    correctAnswers: [2],
    explanation: 'Sound speed increases with temperature because warmer air molecules move faster and collide more frequently, transmitting sound energy more efficiently. Speed of sound in air ≈ 331 + 0.6T m/s (where T is temperature in °C). At 20°C: ~343 m/s.',
  },
  {
    id: 'wave-11',
    domain: 1,
    subdomain: 'Waves & Sound',
    type: 'single',
    difficulty: 'easy',
    question: 'The amplitude of a wave is related to its:',
    options: ['Speed', 'Frequency', 'Energy / Intensity', 'Wavelength'],
    correctAnswers: [2],
    explanation: 'Amplitude is proportional to the square root of energy — or more precisely, intensity ∝ amplitude². A louder sound or brighter light has greater amplitude. Amplitude does NOT affect wave speed in a given medium.',
  },
  {
    id: 'wave-12',
    domain: 1,
    subdomain: 'Waves & Sound',
    type: 'single',
    difficulty: 'medium',
    question: 'A 440 Hz tuning fork vibrates. What is the period of the resulting sound wave?',
    options: ['440 s', '0.00227 s', '880 s', '0.5 s'],
    correctAnswers: [1],
    explanation: 'T = 1/f = 1/440 ≈ 0.00227 s (about 2.27 milliseconds). This is how long it takes for one complete compression-rarefaction cycle. 440 Hz is the musical note A4, the standard tuning pitch.',
  },
  {
    id: 'wave-13',
    domain: 1,
    subdomain: 'Waves & Sound',
    type: 'single',
    difficulty: 'medium',
    question: 'Sound intensity decreases with distance from a source following the inverse-square law. If you move twice as far from a speaker, the intensity becomes:',
    options: ['Half as much', 'One-quarter as much', 'Twice as much', 'One-eighth as much'],
    correctAnswers: [1],
    explanation: 'Inverse square law: I ∝ 1/r². If distance doubles (2r), intensity becomes 1/(2r)² = 1/4r² = ¼ × original. The same total power spreads over 4× the area when distance doubles. This is why sound fades quickly as you move away from a source.',
  },
  {
    id: 'wave-14',
    domain: 1,
    subdomain: 'Waves & Sound',
    type: 'single',
    difficulty: 'easy',
    question: 'Which of the following is NOT a transverse wave?',
    options: ['Light waves', 'Radio waves', 'Sound waves', 'Microwaves'],
    correctAnswers: [2],
    explanation: 'Sound waves are longitudinal — the air molecules compress and expand parallel to the direction of wave travel. All the others (light, radio, microwaves) are electromagnetic and therefore transverse. Seismic S-waves are also transverse; P-waves are longitudinal.',
  },
  {
    id: 'wave-15',
    domain: 1,
    subdomain: 'Waves & Sound',
    type: 'single',
    difficulty: 'hard',
    question: 'Resonance occurs when a system is driven at:',
    options: ['Any random frequency', 'Its natural frequency', 'Double its natural frequency', 'Half its natural frequency'],
    correctAnswers: [1],
    explanation: 'Resonance happens when a driving frequency matches the system\'s natural (resonant) frequency, causing amplitude to build dramatically. Examples: a tuning fork vibrating near a guitar string at the same pitch, or soldiers breaking step on bridges to prevent resonance damage.',
  },

  // ══════════════════════════════════════════════════════════════
  // Light & Optics
  // ══════════════════════════════════════════════════════════════
  {
    id: 'opt-01',
    domain: 1,
    subdomain: 'Light & Optics',
    type: 'single',
    difficulty: 'easy',
    question: 'The law of reflection states that the angle of incidence:',
    options: ['Is always 0°', 'Equals the angle of refraction', 'Equals the angle of reflection', 'Is always 90°'],
    correctAnswers: [2],
    explanation: 'Law of reflection: θᵢ = θᵣ. Both angles are measured from the normal (a line perpendicular to the surface at the point of incidence). This holds for all types of surfaces — flat, concave, convex — and for all wavelengths of light.',
  },
  {
    id: 'opt-02',
    domain: 1,
    subdomain: 'Light & Optics',
    type: 'single',
    difficulty: 'medium',
    question: 'Light travels from water (n = 1.33) into air (n = 1.00). Using Snell\'s Law, if the angle in water is 30°, what happens to the refracted angle in air?',
    options: ['It decreases', 'It stays the same', 'It increases', 'Total internal reflection always occurs'],
    correctAnswers: [2],
    explanation: 'Snell\'s Law: n₁ sin θ₁ = n₂ sin θ₂. Going from denser (n=1.33) to less dense (n=1.00) medium, the ray bends away from the normal — the angle increases. 1.33 × sin 30° = 1.00 × sin θ₂ → sin θ₂ = 0.665 → θ₂ ≈ 41.7°.',
  },
  {
    id: 'opt-03',
    domain: 1,
    subdomain: 'Light & Optics',
    type: 'single',
    difficulty: 'medium',
    question: 'An object is placed 30 cm from a converging lens with focal length 10 cm. Using 1/f = 1/dₒ + 1/dᵢ, where is the image?',
    options: ['15 cm on the same side as the object', '15 cm on the opposite side', '30 cm on the opposite side', '10 cm on the opposite side'],
    correctAnswers: [1],
    explanation: '1/10 = 1/30 + 1/dᵢ → 1/dᵢ = 1/10 − 1/30 = 3/30 − 1/30 = 2/30 → dᵢ = 15 cm. Positive dᵢ means the image is on the opposite side of the lens from the object — a real, inverted image. Converging lenses form real images when the object is beyond the focal point.',
  },
  {
    id: 'opt-04',
    domain: 1,
    subdomain: 'Light & Optics',
    type: 'single',
    difficulty: 'easy',
    question: 'Arrange the electromagnetic spectrum from lowest to highest frequency:',
    options: [
      'Radio, Microwave, Infrared, Visible, UV, X-ray, Gamma',
      'Gamma, X-ray, UV, Visible, Infrared, Microwave, Radio',
      'Visible, Infrared, UV, Radio, Microwave, X-ray, Gamma',
      'Radio, Visible, UV, Gamma, X-ray, Microwave, Infrared',
    ],
    correctAnswers: [0],
    explanation: 'From lowest to highest frequency (longest to shortest wavelength): Radio → Microwave → Infrared → Visible → UV → X-ray → Gamma. Higher frequency means more energy per photon. Mnemonic: "Really Made In Various Unusual X-tra Gross ways." Gamma rays are the most energetic.',
  },
  {
    id: 'opt-05',
    domain: 1,
    subdomain: 'Light & Optics',
    type: 'single',
    difficulty: 'medium',
    question: 'Total internal reflection can occur when light travels from:',
    options: [
      'A less dense medium to a denser medium',
      'A denser medium to a less dense medium at an angle greater than the critical angle',
      'Air to glass at any angle',
      'Any medium to another medium',
    ],
    correctAnswers: [1],
    explanation: 'Total internal reflection occurs when: (1) light goes from denser (higher n) to less dense (lower n) medium, AND (2) the angle of incidence exceeds the critical angle θc where sin θc = n₂/n₁. Fiber optic cables work on this principle — light bounces along the fiber without escaping.',
  },
  {
    id: 'opt-06',
    domain: 1,
    subdomain: 'Light & Optics',
    type: 'single',
    difficulty: 'easy',
    question: 'The speed of light in a vacuum is approximately:',
    options: ['3 × 10⁶ m/s', '3 × 10⁸ m/s', '3 × 10¹⁰ m/s', '343 m/s'],
    correctAnswers: [1],
    explanation: 'c = 3 × 10⁸ m/s (299,792,458 m/s exactly). This is the fastest anything can travel in the universe. Light slows down when passing through matter — the ratio c/v = n (index of refraction). In glass (n ≈ 1.5), light travels at about 2 × 10⁸ m/s.',
  },
  {
    id: 'opt-07',
    domain: 1,
    subdomain: 'Light & Optics',
    type: 'single',
    difficulty: 'medium',
    question: 'A diverging (convex) mirror always produces images that are:',
    options: ['Real and inverted', 'Real and upright', 'Virtual, upright, and smaller', 'Virtual, inverted, and larger'],
    correctAnswers: [2],
    explanation: 'A convex mirror is a diverging mirror — light rays spread out after reflecting from its curved surface. It always forms virtual, upright, and smaller images regardless of object distance. This is why convex mirrors are used for wide-angle security views and passenger-side car mirrors. Concave mirrors (converging) can form real OR virtual images depending on object position.',
  },
  {
    id: 'opt-08',
    domain: 1,
    subdomain: 'Light & Optics',
    type: 'single',
    difficulty: 'hard',
    question: 'An object is 20 cm from a concave mirror with focal length 30 cm (object inside focal point). The image is:',
    options: ['Real and inverted', 'Virtual and upright', 'At infinity', 'Real and upright'],
    correctAnswers: [1],
    explanation: '1/f = 1/dₒ + 1/dᵢ → 1/30 = 1/20 + 1/dᵢ → 1/dᵢ = 1/30 − 1/20 = 2/60 − 3/60 = −1/60 → dᵢ = −60 cm. Negative dᵢ means the image is behind the mirror — virtual and upright. When objects are inside the focal point of a concave mirror, you get a magnified virtual image (like a makeup mirror).',
  },
  {
    id: 'opt-09',
    domain: 1,
    subdomain: 'Light & Optics',
    type: 'single',
    difficulty: 'medium',
    question: 'The index of refraction n = c/v means that a material with n = 2.0:',
    options: ['Has twice the speed of light', 'Has half the speed of light compared to vacuum', 'Does not slow down light', 'Speeds up light compared to vacuum'],
    correctAnswers: [1],
    explanation: 'n = c/v → v = c/n = c/2. So light travels at half the vacuum speed in this material. Higher n = more optically dense = slower light = more bending at interfaces. Diamond (n ≈ 2.42) slows light dramatically, causing its brilliant sparkle.',
  },
  {
    id: 'opt-10',
    domain: 1,
    subdomain: 'Light & Optics',
    type: 'single',
    difficulty: 'easy',
    question: 'Young\'s double-slit experiment demonstrates that light has:',
    options: ['Only particle properties', 'Only wave properties', 'Wave properties (specifically, interference)', 'No properties at all'],
    correctAnswers: [2],
    explanation: 'Young\'s double-slit experiment produces alternating bright and dark fringes on a screen — an interference pattern. Interference is a wave phenomenon. This was key evidence that light behaves as a wave. The photoelectric effect later showed light also behaves as particles (photons) — wave-particle duality.',
  },
  {
    id: 'opt-11',
    domain: 1,
    subdomain: 'Light & Optics',
    type: 'single',
    difficulty: 'medium',
    question: 'Magnification m = −dᵢ/dₒ. If m = −2, the image is:',
    options: ['Upright and half the size', 'Inverted and twice the size', 'Upright and twice the size', 'Inverted and half the size'],
    correctAnswers: [1],
    explanation: 'Magnification m = −dᵢ/dₒ = −2 means: |m| = 2 (image is twice as large) and m is negative (image is inverted). Negative magnification = inverted (real) image. Positive magnification = upright (virtual) image. Magnitude > 1 = larger than object.',
  },
  {
    id: 'opt-12',
    domain: 1,
    subdomain: 'Light & Optics',
    type: 'single',
    difficulty: 'easy',
    question: 'Which part of the electromagnetic spectrum has the most energy per photon?',
    options: ['Radio waves', 'Visible light', 'Ultraviolet', 'Gamma rays'],
    correctAnswers: [3],
    explanation: 'Energy per photon E = hf, where h is Planck\'s constant. Higher frequency = more energy. Gamma rays have the highest frequency (and shortest wavelength) in the electromagnetic spectrum, so they carry the most energy per photon — which is why they are the most penetrating and dangerous radiation.',
  },
  {
    id: 'opt-13',
    domain: 1,
    subdomain: 'Light & Optics',
    type: 'single',
    difficulty: 'easy',
    question: 'Polarization of light shows that light is a:',
    options: ['Longitudinal wave', 'Transverse wave', 'Mechanical wave', 'Sound-like wave'],
    correctAnswers: [1],
    explanation: 'Only transverse waves can be polarized — polarization filters out the component of the electric field oscillating in one direction. Sound (a longitudinal wave) cannot be polarized. Polarized sunglasses reduce glare by blocking light polarized by reflection from horizontal surfaces.',
  },
  {
    id: 'opt-14',
    domain: 1,
    subdomain: 'Light & Optics',
    type: 'single',
    difficulty: 'medium',
    question: 'Diffraction is most noticeable when the wavelength of light is:',
    options: ['Much larger than the opening', 'Much smaller than the opening', 'Comparable in size to the opening', 'Completely unrelated to the opening size'],
    correctAnswers: [2],
    explanation: 'Diffraction (bending of waves around obstacles or through openings) is most pronounced when wavelength ≈ opening size. Very small openings diffract light significantly; very large openings produce minimal diffraction. This is why you can hear around corners (sound wavelengths ≈ room dimensions) but not see around them.',
  },
  {
    id: 'opt-15',
    domain: 1,
    subdomain: 'Light & Optics',
    type: 'single',
    difficulty: 'easy',
    question: 'When light passes from air into glass, it bends toward the normal because:',
    options: ['It speeds up', 'It slows down', 'Its frequency changes', 'Its color changes'],
    correctAnswers: [1],
    explanation: 'Refraction occurs because light slows down in glass (higher n). Snell\'s Law n₁sinθ₁ = n₂sinθ₂ — when n increases, sinθ decreases, so θ decreases (closer to the normal). Frequency doesn\'t change when light enters a new medium, but wavelength and speed do.',
  },

  // ══════════════════════════════════════════════════════════════
  // Electricity & Circuits
  // ══════════════════════════════════════════════════════════════
  {
    id: 'elec-01',
    domain: 1,
    subdomain: 'Electricity & Circuits',
    type: 'single',
    difficulty: 'easy',
    question: 'Ohm\'s Law states V = IR. If a 12 V battery connects to a 4 Ω resistor, what is the current?',
    options: ['48 A', '3 A', '0.33 A', '8 A'],
    correctAnswers: [1],
    explanation: 'I = V/R = 12/4 = 3 A. Ohm\'s Law: more voltage drives more current; more resistance reduces current. Units: Voltage in Volts, Current in Amperes, Resistance in Ohms. Check: V = IR = 3 × 4 = 12 V. ✓',
  },
  {
    id: 'elec-02',
    domain: 1,
    subdomain: 'Electricity & Circuits',
    type: 'single',
    difficulty: 'medium',
    question: 'Two resistors of 6 Ω and 3 Ω are connected in parallel. What is the equivalent resistance?',
    options: ['9 Ω', '2 Ω', '18 Ω', '4.5 Ω'],
    correctAnswers: [1],
    explanation: '1/R_total = 1/6 + 1/3 = 1/6 + 2/6 = 3/6 = 1/2 → R_total = 2 Ω. Parallel resistance is always less than the smallest individual resistor. Think of adding more lanes to a highway — total resistance to traffic flow decreases.',
  },
  {
    id: 'elec-03',
    domain: 1,
    subdomain: 'Electricity & Circuits',
    type: 'single',
    difficulty: 'easy',
    question: 'In a series circuit, the current through each component is:',
    options: ['Different for each component', 'The same for all components', 'Zero for some components', 'Maximum at the start'],
    correctAnswers: [1],
    explanation: 'In a series circuit, there is only one path for current, so the same current flows through every component. Voltages divide among components (V_total = V₁ + V₂ + ...). In parallel, voltages are equal and currents divide.',
  },
  {
    id: 'elec-04',
    domain: 1,
    subdomain: 'Electricity & Circuits',
    type: 'single',
    difficulty: 'medium',
    question: 'The power dissipated by a 10 Ω resistor carrying 2 A is:',
    options: ['5 W', '20 W', '40 W', '100 W'],
    correctAnswers: [2],
    explanation: 'P = I²R = (2)² × 10 = 4 × 10 = 40 W. Alternative: V = IR = 20 V, then P = IV = 2 × 20 = 40 W. Or P = V²/R = 400/10 = 40 W. All three power formulas give the same answer — use whichever matches what you know.',
  },
  {
    id: 'elec-05',
    domain: 1,
    subdomain: 'Electricity & Circuits',
    type: 'single',
    difficulty: 'medium',
    question: 'Kirchhoff\'s Junction Rule states that at any junction in a circuit:',
    options: ['Voltage is conserved', 'The sum of currents entering equals the sum leaving', 'Resistance is constant', 'Power is minimized'],
    correctAnswers: [1],
    explanation: 'Kirchhoff\'s Junction Rule (KCL): ΣI_in = ΣI_out at every node. This is conservation of charge — charges don\'t pile up or disappear at a junction. The Loop Rule (KVL) states the sum of voltage drops around any closed loop equals zero (conservation of energy).',
  },
  {
    id: 'elec-06',
    domain: 1,
    subdomain: 'Electricity & Circuits',
    type: 'single',
    difficulty: 'easy',
    question: 'Coulomb\'s Law states the force between two charges. If the distance between charges triples, the force becomes:',
    options: ['1/9 of the original', '1/3 of the original', '3× the original', '9× the original'],
    correctAnswers: [0],
    explanation: 'Coulomb\'s Law: F = kq₁q₂/r². If r → 3r, then F → F/(3)² = F/9. The inverse square law applies to electric force just like gravitational force. Doubling distance → 1/4 force; tripling distance → 1/9 force.',
  },
  {
    id: 'elec-07',
    domain: 1,
    subdomain: 'Electricity & Circuits',
    type: 'single',
    difficulty: 'medium',
    question: 'Which statement is true about capacitors in series vs. parallel?',
    options: [
      'Series capacitors add directly; parallel capacitors use 1/C formula',
      'Parallel capacitors add directly; series capacitors use 1/C formula',
      'Both add directly',
      'Both use the 1/C formula',
    ],
    correctAnswers: [1],
    explanation: 'Capacitors behave OPPOSITE to resistors: in parallel, C_total = C₁ + C₂ + ... (add directly); in series, 1/C_total = 1/C₁ + 1/C₂ + ... This is the opposite of resistors. Memory trick: capacitors and resistors swap their series/parallel rules.',
  },
  {
    id: 'elec-08',
    domain: 1,
    subdomain: 'Electricity & Circuits',
    type: 'single',
    difficulty: 'hard',
    question: 'Three resistors of 2 Ω, 4 Ω, and 4 Ω are in series with a 20 V source. What is the current through the circuit?',
    options: ['1 A', '2 A', '5 A', '10 A'],
    correctAnswers: [1],
    explanation: 'Series resistance: R_total = 2 + 4 + 4 = 10 Ω. Current I = V/R = 20/10 = 2 A. The same 2 A flows through every resistor. Voltage drops: V₁ = 4 V, V₂ = 8 V, V₃ = 8 V. Check: 4 + 8 + 8 = 20 V. ✓',
  },
  {
    id: 'elec-09',
    domain: 1,
    subdomain: 'Electricity & Circuits',
    type: 'single',
    difficulty: 'easy',
    question: 'Electric potential (voltage) is measured in:',
    options: ['Amperes', 'Ohms', 'Watts', 'Volts'],
    correctAnswers: [3],
    explanation: 'Voltage (electric potential difference) is measured in Volts (V). Current is measured in Amperes (A). Resistance in Ohms (Ω). Power in Watts (W). Energy in Joules (J). Charge in Coulombs (C). Memorize these units — they\'re on every physics exam.',
  },
  {
    id: 'elec-10',
    domain: 1,
    subdomain: 'Electricity & Circuits',
    type: 'single',
    difficulty: 'medium',
    question: 'The electric field always points in the direction of:',
    options: ['From negative to positive charge', 'From positive to negative charge', 'Parallel to the surface', 'Toward the higher potential'],
    correctAnswers: [1],
    explanation: 'Electric field lines point FROM positive charge TO negative charge — in the direction a positive test charge would move. This is also from high potential to low potential. Electrons (negative) move OPPOSITE to the field direction.',
  },
  {
    id: 'elec-11',
    domain: 1,
    subdomain: 'Electricity & Circuits',
    type: 'single',
    difficulty: 'hard',
    question: 'A 100 W light bulb runs for 2 hours. How many joules of energy does it use?',
    options: ['200 J', '720,000 J', '7,200 J', '3,600 J'],
    correctAnswers: [1],
    explanation: 'E = P × t = 100 W × (2 × 3600 s) = 100 × 7200 = 720,000 J. Convert hours to seconds first! 1 hour = 3600 s. This is also 0.2 kWh (kilowatt-hours), the unit on your electric bill.',
  },
  {
    id: 'elec-12',
    domain: 1,
    subdomain: 'Electricity & Circuits',
    type: 'single',
    difficulty: 'easy',
    question: 'Like charges _____, unlike charges _____.',
    options: ['attract, repel', 'repel, attract', 'do nothing, repel', 'repel, do nothing'],
    correctAnswers: [1],
    explanation: 'Like charges (both positive or both negative) repel each other; unlike charges (one positive, one negative) attract. This is the fundamental rule of electrostatics. "Opposites attract" applies to electric charges, not magnetic poles (which also attract when opposite).',
  },
  {
    id: 'elec-13',
    domain: 1,
    subdomain: 'Electricity & Circuits',
    type: 'single',
    difficulty: 'medium',
    question: 'Fuses and circuit breakers protect household circuits by:',
    options: ['Increasing voltage when current is too high', 'Breaking the circuit when current exceeds a safe level', 'Reducing resistance automatically', 'Storing excess current'],
    correctAnswers: [1],
    explanation: 'Fuses melt (one-time use) and circuit breakers trip (resettable) when current exceeds a safe threshold, breaking the circuit to prevent overheating and fire. Both work because excess current generates excess heat (P = I²R). Ground fault circuit interrupters (GFCIs) offer additional protection in bathrooms and kitchens.',
  },
  {
    id: 'elec-14',
    domain: 1,
    subdomain: 'Electricity & Circuits',
    type: 'single',
    difficulty: 'medium',
    question: 'Energy stored in a capacitor with capacitance C and voltage V is:',
    options: ['CV', 'CV²', '½CV²', '2CV²'],
    correctAnswers: [2],
    explanation: 'U = ½CV². This is analogous to ½mv² for kinetic energy and ½kx² for spring energy — many energy storage formulas have the ½. Capacitors store energy in electric fields between their plates and release it quickly, which is why camera flashes use capacitors.',
  },
  {
    id: 'elec-15',
    domain: 1,
    subdomain: 'Electricity & Circuits',
    type: 'single',
    difficulty: 'easy',
    question: 'In a parallel circuit, if one light bulb burns out:',
    options: ['All other bulbs also go out', 'All other bulbs get dimmer', 'The other bulbs continue to work', 'The voltage across other bulbs drops to zero'],
    correctAnswers: [2],
    explanation: 'In a parallel circuit, each branch has its own independent path to the power source. If one bulb burns out (open circuit in that branch), current simply stops flowing through that branch but continues through all others. This is why household wiring uses parallel circuits — one appliance failing doesn\'t kill the whole house.',
  },

  // ══════════════════════════════════════════════════════════════
  // Magnetism
  // ══════════════════════════════════════════════════════════════
  {
    id: 'mag-01',
    domain: 1,
    subdomain: 'Magnetism',
    type: 'single',
    difficulty: 'easy',
    question: 'Magnetic field lines outside a bar magnet run from:',
    options: ['South to North pole', 'North to South pole', 'Parallel to the magnet', 'In random directions'],
    correctAnswers: [1],
    explanation: 'Outside a magnet, field lines run from North pole to South pole. Inside the magnet, they run from South to North (closed loops). Field lines never cross and are densest near the poles where the field is strongest. The field direction is defined as the direction a North pole would move.',
  },
  {
    id: 'mag-02',
    domain: 1,
    subdomain: 'Magnetism',
    type: 'single',
    difficulty: 'medium',
    question: 'A positive charge moves to the right in a magnetic field pointing out of the page. Using the right-hand rule, the magnetic force on the charge is:',
    options: ['Into the page', 'Out of the page', 'Upward', 'Downward'],
    correctAnswers: [3],
    explanation: 'F = qv × B. With v along +x (right) and B along +z (out of page), x̂ × ẑ = −ŷ, so the force is in the −y direction (downward) for a positive charge. Right-hand rule: point fingers along v (right), curl them toward B (out of page) — your thumb points downward. For a negative charge the force would reverse, pointing upward.',
  },
  {
    id: 'mag-03',
    domain: 1,
    subdomain: 'Magnetism',
    type: 'single',
    difficulty: 'medium',
    question: 'Faraday\'s Law of electromagnetic induction states that an EMF is induced when there is a change in:',
    options: ['Electric field', 'Magnetic flux', 'Current in a nearby wire', 'Temperature of the conductor'],
    correctAnswers: [1],
    explanation: 'Faraday\'s Law: EMF = −ΔΦ/Δt. Magnetic flux Φ = B × A × cosθ. A change in flux (changing B, changing area, or changing angle) induces an EMF. The negative sign (Lenz\'s Law) means the induced current opposes the change that caused it.',
  },
  {
    id: 'mag-04',
    domain: 1,
    subdomain: 'Magnetism',
    type: 'single',
    difficulty: 'medium',
    question: 'Lenz\'s Law states that the induced current always:',
    options: ['Flows in the same direction as the changing flux', 'Opposes the change in magnetic flux', 'Reinforces the external magnetic field', 'Has no preferred direction'],
    correctAnswers: [1],
    explanation: 'Lenz\'s Law is conservation of energy in electromagnetic form. If induced current reinforced the change, you\'d get runaway amplification — free energy, which violates conservation. Instead, the induced current creates a magnetic field opposing the change, requiring external work to maintain it.',
  },
  {
    id: 'mag-05',
    domain: 1,
    subdomain: 'Magnetism',
    type: 'single',
    difficulty: 'easy',
    question: 'A transformer has 100 turns on the primary and 500 turns on the secondary. If the primary voltage is 120 V, the secondary voltage is:',
    options: ['24 V', '600 V', '500 V', '12 V'],
    correctAnswers: [1],
    explanation: 'Transformer equation: V₁/V₂ = N₁/N₂ → V₂ = V₁ × (N₂/N₁) = 120 × (500/100) = 120 × 5 = 600 V. More turns on secondary = step-up transformer (increases voltage, decreases current). Power is conserved (V₁I₁ = V₂I₂, ignoring losses).',
  },
  {
    id: 'mag-06',
    domain: 1,
    subdomain: 'Magnetism',
    type: 'single',
    difficulty: 'medium',
    question: 'An electric generator converts:',
    options: ['Electrical energy to mechanical energy', 'Mechanical energy to electrical energy', 'Heat to electrical energy', 'Electrical energy to heat'],
    correctAnswers: [1],
    explanation: 'A generator converts mechanical energy to electrical energy using electromagnetic induction — rotating a coil in a magnetic field changes the flux, inducing an EMF. An electric motor does the reverse: electrical energy → mechanical energy. Generators are driven by turbines (steam, water, wind).',
  },
  {
    id: 'mag-07',
    domain: 1,
    subdomain: 'Magnetism',
    type: 'single',
    difficulty: 'hard',
    question: 'The force on a current-carrying wire of length 0.5 m, carrying 3 A, in a magnetic field B = 2 T (perpendicular to the wire) is:',
    options: ['3 N', '12 N', '1 N', '0.33 N'],
    correctAnswers: [0],
    explanation: 'F = BIL sin θ. With θ = 90° (B perpendicular to wire), sin 90° = 1. F = 2 × 3 × 0.5 × 1 = 3 N. The direction is given by the right-hand rule (point fingers along current, curl toward B, thumb = force direction). This is the principle behind electric motors.',
  },
  {
    id: 'mag-08',
    domain: 1,
    subdomain: 'Magnetism',
    type: 'single',
    difficulty: 'easy',
    question: 'Which of the following is NOT a source of magnetic fields?',
    options: ['A permanent magnet', 'A stationary electric charge', 'An electric current', 'A moving electric charge'],
    correctAnswers: [1],
    explanation: 'Magnetic fields are created by MOVING charges (current) or permanent magnets (aligned magnetic domains). A stationary electric charge creates only an electric field, not a magnetic field. Once the charge moves (current), a magnetic field appears — this is fundamentally what electromagnetism shows us.',
  },
  {
    id: 'mag-09',
    domain: 1,
    subdomain: 'Magnetism',
    type: 'single',
    difficulty: 'medium',
    question: 'Maxwell\'s contribution to electromagnetism showed that a changing electric field produces a:',
    options: ['Static magnetic field', 'Changing magnetic field', 'Gravitational field', 'Temperature change'],
    correctAnswers: [1],
    explanation: 'Maxwell\'s equations unified electricity and magnetism: a changing E field creates a B field, and a changing B field creates an E field. This self-sustaining cycle propagates through space as electromagnetic waves at speed c = 3×10⁸ m/s. Maxwell predicted light was an electromagnetic wave before it was confirmed experimentally.',
  },
  {
    id: 'mag-10',
    domain: 1,
    subdomain: 'Magnetism',
    type: 'single',
    difficulty: 'hard',
    question: 'A coil of 50 turns has a magnetic flux that changes from 0.02 Wb to 0.08 Wb in 0.1 s. What EMF is induced?',
    options: ['0.03 V', '3 V', '30 V', '0.3 V'],
    correctAnswers: [2],
    explanation: 'EMF = −N × ΔΦ/Δt = −50 × (0.08 − 0.02)/0.1 = −50 × 0.06/0.1 = −50 × 0.6 = −30 V. Magnitude = 30 V. More turns = more EMF for the same flux change. This is how power transformers in your wall-mounted phone charger work.',
  },
  {
    id: 'mag-11',
    domain: 1,
    subdomain: 'Magnetism',
    type: 'single',
    difficulty: 'medium',
    question: 'What happens to opposite magnetic poles (N-S) placed near each other?',
    options: ['They repel', 'They attract', 'Nothing happens', 'They cancel each other'],
    correctAnswers: [1],
    explanation: 'Opposite magnetic poles (N near S) attract; like poles (N near N, or S near S) repel. This is analogous to electric charges, except you can never isolate a single magnetic pole (monopole) — every magnet has both a North and South pole. Break a magnet in half and you get two smaller magnets, each with N and S.',
  },
  {
    id: 'mag-12',
    domain: 1,
    subdomain: 'Magnetism',
    type: 'single',
    difficulty: 'medium',
    question: 'The right-hand rule for a solenoid tells you:',
    options: ['The direction of current flow', 'Which end is the North pole', 'The resistance of the coil', 'The frequency of oscillation'],
    correctAnswers: [1],
    explanation: 'For a solenoid: curl the right-hand fingers in the direction of current flow around the coil; the extended thumb points toward the North pole. A solenoid behaves like a bar magnet, with a strong uniform field inside. Electromagnets use this principle — when current stops, the field collapses.',
  },
  {
    id: 'mag-13',
    domain: 1,
    subdomain: 'Magnetism',
    type: 'single',
    difficulty: 'easy',
    question: 'A transformer steps voltage UP. The turns ratio (N_secondary/N_primary) is:',
    options: ['Less than 1', 'Equal to 1', 'Greater than 1', 'Does not matter'],
    correctAnswers: [2],
    explanation: 'Step-up transformer: V₂ > V₁ means N₂ > N₁, so N₂/N₁ > 1. Step-down: N₂/N₁ < 1. Power companies use step-up transformers at power plants (high voltage, low current for efficient transmission) and step-down transformers at homes (120 V or 240 V).',
  },
  {
    id: 'mag-14',
    domain: 1,
    subdomain: 'Magnetism',
    type: 'single',
    difficulty: 'medium',
    question: 'The force F = qvBsinθ on a moving charge is maximum when:',
    options: ['The charge moves parallel to B', 'The charge is stationary', 'The charge moves perpendicular to B', 'θ = 0°'],
    correctAnswers: [2],
    explanation: 'F = qvBsinθ is maximum when θ = 90° (sin 90° = 1) — when velocity is perpendicular to the magnetic field. When θ = 0° (parallel), sin 0° = 0, and force is zero. A charge moving parallel to B experiences no magnetic force — it moves in a straight line.',
  },
  {
    id: 'mag-15',
    domain: 1,
    subdomain: 'Magnetism',
    type: 'single',
    difficulty: 'hard',
    question: 'A step-down transformer has V₁ = 480 V and V₂ = 120 V. If the secondary carries 10 A, what is the primary current (ideal transformer)?',
    options: ['2.5 A', '40 A', '10 A', '480 A'],
    correctAnswers: [0],
    explanation: 'For an ideal transformer, power is conserved: P₁ = P₂ → V₁I₁ = V₂I₂ → 480 × I₁ = 120 × 10 = 1200 W → I₁ = 1200/480 = 2.5 A. Step-down in voltage = step-up in current (by the same ratio). This inverse relationship keeps power constant.',
  },

  // ══════════════════════════════════════════════════════════════
  // Round 2 expansion: 42 questions across 6 subdomains
  // ══════════════════════════════════════════════════════════════

  // ─── Kinematics ────────────────────────────────────────────────
  {
    id: 'kin-16', domain: 1, subdomain: 'Kinematics', type: 'single', difficulty: 'easy',
    question: 'A car accelerates from rest at 2.0 m/s² for 5.0 seconds. What is its final velocity?',
    options: ['2.5 m/s', '10 m/s', '25 m/s', '50 m/s'],
    correctAnswers: [1],
    explanation: 'v = v₀ + at = 0 + (2.0)(5.0) = 10 m/s. Starting from rest means v₀ = 0. This is the simplest kinematic equation — final velocity equals initial velocity plus the product of acceleration and time. Always check whether the object starts at rest (v₀ = 0) or already has initial velocity.',
  },
  {
    id: 'kin-17', domain: 1, subdomain: 'Kinematics', type: 'single', difficulty: 'medium',
    question: 'A ball is dropped from a height of 20 m. Using g = 9.8 m/s², how long does it take to hit the ground? (Ignore air resistance)',
    options: ['About 1.0 s', 'About 2.0 s', 'About 4.0 s', 'About 0.5 s'],
    correctAnswers: [1],
    explanation: 'Use h = ½gt². 20 = ½(9.8)t² → t² = 40/9.8 ≈ 4.08 → t ≈ 2.0 s. "Dropped" means initial velocity is zero, so the first term v₀t drops out. The time to fall depends only on height and g — mass does not matter in free-fall (Galileo\'s discovery).',
  },
  {
    id: 'kin-18', domain: 1, subdomain: 'Kinematics', type: 'single', difficulty: 'medium',
    question: 'A projectile is launched horizontally from a cliff at 15 m/s. After 2.0 seconds, what is its horizontal velocity? (Ignore air resistance)',
    options: ['0 m/s — it has fallen', '15 m/s — horizontal velocity is unchanged', '30 m/s — gravity adds to it', '19.6 m/s — gravity pulls it forward'],
    correctAnswers: [1],
    explanation: 'In projectile motion, horizontal and vertical motions are INDEPENDENT. Gravity acts only vertically, so horizontal velocity stays constant (ignoring air resistance) at 15 m/s. The vertical velocity at t = 2 s would be gt = 19.6 m/s downward. Total speed combines both via Pythagoras.',
  },
  {
    id: 'kin-19', domain: 1, subdomain: 'Kinematics', type: 'multi', difficulty: 'medium',
    question: 'Which of the following are vector quantities? (Select all that apply)',
    options: ['Velocity', 'Speed', 'Displacement', 'Time'],
    correctAnswers: [0, 2],
    explanation: 'Vectors have magnitude AND direction: velocity (e.g., 10 m/s north), displacement (e.g., 5 m east). Scalars have only magnitude: speed (10 m/s), time (5 s), mass, temperature. The distinction matters: "speed" of 60 mph in a car going in a circle stays constant, but "velocity" continuously changes direction.',
  },
  {
    id: 'kin-20', domain: 1, subdomain: 'Kinematics', type: 'yesno', difficulty: 'easy',
    question: 'Can an object have zero velocity but nonzero acceleration?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes — at the highest point of a ball thrown straight up, its velocity is momentarily zero (about to change direction), but gravity is still pulling it down at g = 9.8 m/s². Acceleration is the RATE OF CHANGE of velocity, not velocity itself. The two are independent at any instant.',
  },
  {
    id: 'kin-21', domain: 1, subdomain: 'Kinematics', type: 'single', difficulty: 'hard',
    question: 'A car traveling at 30 m/s applies the brakes with constant deceleration of 5.0 m/s². How far does it travel before stopping?',
    options: ['30 m', '60 m', '90 m', '180 m'],
    correctAnswers: [2],
    explanation: 'Use v² = v₀² + 2ad. 0 = 30² + 2(−5.0)d → 0 = 900 − 10d → d = 90 m. This kinematic equation skips time — useful when you know initial and final velocities plus acceleration. Common application: figuring out stopping distances for highway safety.',
  },
  {
    id: 'kin-22', domain: 1, subdomain: 'Kinematics', type: 'single', difficulty: 'medium',
    question: 'What is the difference between distance and displacement?',
    options: ['They are always the same', 'Distance is total path traveled; displacement is a vector from start to end', 'Distance is a vector; displacement is a scalar', 'Displacement applies only to circular motion'],
    correctAnswers: [1],
    explanation: 'Distance = total path length traveled (scalar, always non-negative). Displacement = straight-line vector from start to end (has direction; can be zero even if distance is large). Running once around a 400-m track: distance = 400 m, displacement = 0 (you ended where you started).',
  },

  // ─── Energy & Momentum ─────────────────────────────────────────
  {
    id: 'ener-16', domain: 1, subdomain: 'Energy & Momentum', type: 'single', difficulty: 'easy',
    question: 'What is the kinetic energy of a 2.0 kg object moving at 4.0 m/s?',
    options: ['4.0 J', '8.0 J', '16 J', '32 J'],
    correctAnswers: [2],
    explanation: 'KE = ½mv² = ½(2.0)(4.0)² = ½(2.0)(16) = 16 J. Kinetic energy depends on the SQUARE of velocity, so doubling speed quadruples KE. This is why car crashes at high speed are disproportionately damaging — 60 mph has 4× the KE of 30 mph, not 2×.',
  },
  {
    id: 'ener-17', domain: 1, subdomain: 'Energy & Momentum', type: 'single', difficulty: 'medium',
    question: 'A 5.0 kg ball is held 10 m above the ground. What is its gravitational potential energy? (g = 9.8 m/s²)',
    options: ['50 J', '98 J', '490 J', '4900 J'],
    correctAnswers: [2],
    explanation: 'PE = mgh = (5.0)(9.8)(10) = 490 J. Gravitational PE depends on mass, gravity, and height above some reference (usually the ground). When released, this PE converts entirely to KE just before impact (assuming no air resistance), giving v = √(2gh) ≈ 14 m/s at the moment of impact.',
  },
  {
    id: 'ener-18', domain: 1, subdomain: 'Energy & Momentum', type: 'multi', difficulty: 'medium',
    question: 'In a closed system with no external forces, which of the following are CONSERVED? (Select all that apply)',
    options: ['Total momentum', 'Total mechanical energy (if no friction or other non-conservative forces)', 'Kinetic energy in every interaction (e.g., always conserved in inelastic collisions)', 'Total energy (including all forms)'],
    correctAnswers: [0, 1, 3],
    explanation: 'Conservation of momentum: always in closed systems with no external forces. Conservation of mechanical energy: holds only when forces are conservative (no friction). Total energy: always conserved (1st Law of Thermodynamics) — energy converts forms but doesn\'t vanish. Kinetic energy is NOT conserved in inelastic collisions — it converts to heat, sound, deformation.',
  },
  {
    id: 'ener-19', domain: 1, subdomain: 'Energy & Momentum', type: 'single', difficulty: 'medium',
    question: 'What is the momentum of a 1500 kg car traveling at 20 m/s east?',
    options: ['75 kg·m/s east', '1500 kg·m/s east', '30,000 kg·m/s east', '300 kg·m/s east'],
    correctAnswers: [2],
    explanation: 'Momentum p = mv = (1500)(20) = 30,000 kg·m/s east. Momentum is a vector — direction matters. The direction of momentum is the same as the direction of velocity. A heavy object at modest speed can have enormous momentum, which is why a slow-moving truck is so dangerous in a collision.',
  },
  {
    id: 'ener-20', domain: 1, subdomain: 'Energy & Momentum', type: 'yesno', difficulty: 'medium',
    question: 'In a perfectly elastic collision, is kinetic energy conserved?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes — that is the defining feature of an elastic collision: total kinetic energy before equals total kinetic energy after. Examples: billiard balls (close to elastic), molecular collisions in ideal gases (perfectly elastic). In INELASTIC collisions, some KE converts to other forms (heat, sound, deformation) but momentum is still conserved.',
  },
  {
    id: 'ener-21', domain: 1, subdomain: 'Energy & Momentum', type: 'single', difficulty: 'hard',
    question: 'A 1.0 kg object moving at 4.0 m/s collides with a stationary 3.0 kg object. They stick together. What is their final velocity?',
    options: ['0 m/s', '1.0 m/s', '4.0 m/s', '16 m/s'],
    correctAnswers: [1],
    explanation: 'Perfectly inelastic collision (they stick). Conservation of momentum: m₁v₁ + m₂v₂ = (m₁+m₂)v_f → (1)(4) + (3)(0) = (4)v_f → v_f = 1.0 m/s. KE is not conserved here — initial KE = 8 J, final KE = 2 J, so 6 J converted to heat and deformation. Momentum is always conserved; KE depends on the collision type.',
  },
  {
    id: 'ener-22', domain: 1, subdomain: 'Energy & Momentum', type: 'single', difficulty: 'medium',
    question: 'A 50 W lightbulb operates for 30 seconds. How much energy does it use?',
    options: ['50 J', '1.67 J', '80 J', '1500 J'],
    correctAnswers: [3],
    explanation: 'Energy = Power × time = (50 W)(30 s) = 1500 J. Power is the RATE of energy use (watts = joules per second). For longer time scales we use kilowatt-hours (1 kWh = 3.6 million J). A 100-W bulb running for 10 hours uses 1 kWh — the unit billed by power companies.',
  },

  // ─── Waves & Sound ─────────────────────────────────────────────
  {
    id: 'wave-16', domain: 1, subdomain: 'Waves & Sound', type: 'single', difficulty: 'easy',
    question: 'A wave has frequency 50 Hz and wavelength 4.0 m. What is its wave speed?',
    options: ['12.5 m/s', '54 m/s', '200 m/s', '46 m/s'],
    correctAnswers: [2],
    explanation: 'Wave equation: v = fλ = (50 Hz)(4.0 m) = 200 m/s. This is the single most important wave equation — it relates speed, frequency, and wavelength for ANY wave (sound, light, water). Frequency × wavelength = wave speed. Different waves travel at different speeds in different media.',
  },
  {
    id: 'wave-17', domain: 1, subdomain: 'Waves & Sound', type: 'single', difficulty: 'medium',
    question: 'Sound travels fastest in:',
    options: ['Vacuum', 'Air at room temperature', 'Water', 'Steel'],
    correctAnswers: [3],
    explanation: 'Sound travels FASTEST in solids (about 5000 m/s in steel), MEDIUM in liquids (about 1500 m/s in water), SLOWEST in gases (about 343 m/s in air at 20 °C). It cannot travel in vacuum at all — sound needs a medium with particles to propagate. The denser/stiffer the medium, the faster sound travels.',
  },
  {
    id: 'wave-18', domain: 1, subdomain: 'Waves & Sound', type: 'multi', difficulty: 'medium',
    question: 'Which of the following are TRANSVERSE waves? (Select all that apply)',
    options: ['Light (electromagnetic waves)', 'Sound in air', 'Water surface waves', 'Vibration of a guitar string'],
    correctAnswers: [0, 2, 3],
    explanation: 'Transverse waves: oscillation is PERPENDICULAR to wave direction. Light, water-surface waves, and string vibrations all fit. Sound in air is LONGITUDINAL — air molecules oscillate parallel to the wave\'s direction (compression and rarefaction). Both types are common; the distinction affects polarization properties.',
  },
  {
    id: 'wave-19', domain: 1, subdomain: 'Waves & Sound', type: 'single', difficulty: 'medium',
    question: 'A stationary observer hears a higher pitch as an ambulance approaches. This is an example of:',
    options: ['Reflection', 'Refraction', 'The Doppler effect', 'Polarization'],
    correctAnswers: [2],
    explanation: 'The Doppler effect: an observed change in frequency due to relative motion between source and observer. Approaching source: waves bunch up, higher frequency, higher pitch. Receding source: waves spread, lower frequency, lower pitch. Police radar guns measure speed via Doppler shifts of reflected radio waves.',
  },
  {
    id: 'wave-20', domain: 1, subdomain: 'Waves & Sound', type: 'yesno', difficulty: 'easy',
    question: 'Does the amplitude of a wave determine how much energy it carries?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes — wave energy is proportional to amplitude². Doubling amplitude quadruples energy. This is why loud sounds (high amplitude) carry more energy than quiet ones at the same frequency, and why earthquakes with twice the seismic amplitude are 4× as destructive in shaking energy (though magnitude scale uses logarithms).',
  },
  {
    id: 'wave-21', domain: 1, subdomain: 'Waves & Sound', type: 'single', difficulty: 'hard',
    question: 'A wave travels from a less dense to a more dense medium. What happens to its speed and wavelength?',
    options: ['Both speed and wavelength increase', 'Both speed and wavelength decrease', 'Speed increases; wavelength decreases', 'Speed stays the same; wavelength decreases'],
    correctAnswers: [1],
    explanation: 'Frequency stays constant when a wave enters a new medium (set by the source). For sound, denser/stiffer media usually mean FASTER speed, but for LIGHT, denser media slow the wave down. For light entering glass from air: speed decreases AND wavelength decreases (v=fλ, f fixed). This is what causes refraction at boundaries.',
  },
  {
    id: 'wave-22', domain: 1, subdomain: 'Waves & Sound', type: 'single', difficulty: 'medium',
    question: 'Constructive interference happens when:',
    options: ['Two waves cancel completely', 'Two waves arrive in phase, adding their amplitudes', 'Waves travel in opposite directions', 'A wave reflects off a barrier'],
    correctAnswers: [1],
    explanation: 'Constructive interference: two waves arrive crest-to-crest (in phase). Amplitudes add, creating a larger wave. Destructive interference: crest meets trough (out of phase), and they partially or fully cancel. Noise-cancelling headphones use destructive interference deliberately.',
  },

  // ─── Light & Optics ────────────────────────────────────────────
  {
    id: 'opt-16', domain: 1, subdomain: 'Light & Optics', type: 'single', difficulty: 'easy',
    question: 'What is the approximate speed of light in vacuum?',
    options: ['3.0 × 10⁵ m/s', '3.0 × 10⁸ m/s', '3.0 × 10¹⁰ m/s', '3.0 × 10⁶ m/s'],
    correctAnswers: [1],
    explanation: 'c ≈ 3.0 × 10⁸ m/s in vacuum — about 300,000 km/s or 186,000 miles/s. Light from the Sun takes 8.3 minutes to reach Earth (1 AU). Light slows down in any medium: about 0.75c in water, 0.67c in glass. This slowing causes refraction at interfaces.',
  },
  {
    id: 'opt-17', domain: 1, subdomain: 'Light & Optics', type: 'single', difficulty: 'medium',
    question: 'A converging (convex) lens forms what kind of image when the object is FARTHER from the lens than the focal length?',
    options: ['Always virtual, always upright', 'Real, inverted, can be larger or smaller depending on distance', 'Always virtual, always larger', 'No image — light passes straight through'],
    correctAnswers: [1],
    explanation: 'When the object is beyond the focal point of a converging lens, the image is REAL (formed where light actually converges) and INVERTED. Size depends on the distance ratio — closer to the focal point produces larger images; farther produces smaller. This is how cameras and projectors work.',
  },
  {
    id: 'opt-18', domain: 1, subdomain: 'Light & Optics', type: 'multi', difficulty: 'medium',
    question: 'Which of the following are FORMS of electromagnetic radiation? (Select all that apply)',
    options: ['Radio waves', 'X-rays', 'Sound waves', 'Visible light'],
    correctAnswers: [0, 1, 3],
    explanation: 'The electromagnetic spectrum includes (low to high frequency): radio, microwaves, infrared, visible light, ultraviolet, X-rays, gamma rays. All travel at c in vacuum. Sound is NOT electromagnetic — it\'s mechanical (requires a medium). All EM waves carry energy and momentum; sound carries only energy.',
  },
  {
    id: 'opt-19', domain: 1, subdomain: 'Light & Optics', type: 'single', difficulty: 'medium',
    question: 'A beam of white light passes through a prism. What is observed?',
    options: ['Light is unchanged', 'Light is absorbed', 'Light is split into a spectrum because different colors refract by different amounts', 'Light gets brighter'],
    correctAnswers: [2],
    explanation: 'White light contains all visible wavelengths. A prism refracts each color by a different amount because the index of refraction is wavelength-dependent (dispersion). Red bends least; violet bends most. The result is the visible spectrum: ROYGBIV (red, orange, yellow, green, blue, indigo, violet). Newton famously demonstrated this in 1672.',
  },
  {
    id: 'opt-20', domain: 1, subdomain: 'Light & Optics', type: 'yesno', difficulty: 'easy',
    question: 'Can light travel through a vacuum (empty space)?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes — light (and all electromagnetic waves) can travel through vacuum because the wave consists of self-sustaining oscillating electric and magnetic fields. Sound CANNOT travel through vacuum because it needs particles to oscillate. This is why we see the Sun (light) but cannot hear it (no sound through space).',
  },
  {
    id: 'opt-21', domain: 1, subdomain: 'Light & Optics', type: 'single', difficulty: 'hard',
    question: 'Snell\'s Law: n₁ sin(θ₁) = n₂ sin(θ₂). A light ray traveling in water (n=1.33) hits a glass surface (n=1.5) at θ₁ = 30°. What is θ₂?',
    options: ['Exactly 30°', 'About 26°', 'About 35°', 'About 45°'],
    correctAnswers: [1],
    explanation: 'Snell\'s Law: n₁sin(θ₁) = n₂sin(θ₂). (1.33)sin(30°) = (1.5)sin(θ₂) → (1.33)(0.5) = (1.5)sin(θ₂) → 0.665 = 1.5·sin(θ₂) → sin(θ₂) = 0.443 → θ₂ ≈ 26°. Light bends TOWARD the normal when entering a denser medium. This is the basis of how lenses work.',
  },
  {
    id: 'opt-22', domain: 1, subdomain: 'Light & Optics', type: 'single', difficulty: 'medium',
    question: 'A plane (flat) mirror produces an image that is:',
    options: ['Real and inverted', 'Virtual, upright, same size as the object, behind the mirror', 'Real and magnified', 'Virtual but inverted'],
    correctAnswers: [1],
    explanation: 'A plane mirror always produces a VIRTUAL (light doesn\'t actually converge there) image that is UPRIGHT, SAME SIZE as the object, and located behind the mirror at the same distance as the object is in front. The image appears reversed left-to-right (lateral inversion). Curved mirrors can produce real or magnified images.',
  },

  // ─── Electricity & Circuits ────────────────────────────────────
  {
    id: 'elec-16', domain: 1, subdomain: 'Electricity & Circuits', type: 'single', difficulty: 'easy',
    question: 'What is the current through a 6.0 V battery connected to a 3.0 Ω resistor?',
    options: ['0.5 A', '2.0 A', '18 A', '9.0 A'],
    correctAnswers: [1],
    explanation: 'Ohm\'s Law: V = IR → I = V/R = 6.0/3.0 = 2.0 A. Memorize V = IR — the most fundamental equation in circuit analysis. Higher voltage drives more current; higher resistance impedes current. For complex circuits, apply this at each component.',
  },
  {
    id: 'elec-17', domain: 1, subdomain: 'Electricity & Circuits', type: 'single', difficulty: 'medium',
    question: 'Two 6.0 Ω resistors are connected in SERIES. What is the total resistance?',
    options: ['3.0 Ω', '6.0 Ω', '12 Ω', '36 Ω'],
    correctAnswers: [2],
    explanation: 'Series: R_total = R₁ + R₂ = 6.0 + 6.0 = 12 Ω. In series, resistances add directly. The same current flows through both. Parallel: 1/R_total = 1/R₁ + 1/R₂, so two equal resistors in parallel give HALF the resistance.',
  },
  {
    id: 'elec-18', domain: 1, subdomain: 'Electricity & Circuits', type: 'multi', difficulty: 'medium',
    question: 'Which statements are TRUE about a SERIES circuit? (Select all that apply)',
    options: ['Current is the same through all components', 'If one component fails (e.g., a bulb burns out), the entire circuit stops', 'Voltage across each component adds up to the source voltage', 'Each component receives the full source voltage'],
    correctAnswers: [0, 1, 2],
    explanation: 'Series circuit properties: same current everywhere; voltages SUM to source voltage; one broken component breaks the whole chain. The last option describes a PARALLEL circuit — each branch gets the full source voltage in parallel. Old Christmas lights used to be series-wired (one burned bulb killed all of them).',
  },
  {
    id: 'elec-19', domain: 1, subdomain: 'Electricity & Circuits', type: 'single', difficulty: 'medium',
    question: 'A 120 V outlet powers a 60 W lightbulb. What current does it draw?',
    options: ['0.5 A', '2.0 A', '7200 A', '60 A'],
    correctAnswers: [0],
    explanation: 'P = VI → I = P/V = 60/120 = 0.5 A. Power equals voltage times current. Useful for sizing fuses and breakers. A 1500 W microwave on 120 V draws 12.5 A — close to the 15 A limit of a standard kitchen outlet. Multiple high-power devices on one circuit can trip the breaker.',
  },
  {
    id: 'elec-20', domain: 1, subdomain: 'Electricity & Circuits', type: 'yesno', difficulty: 'easy',
    question: 'In a parallel circuit, do all components get the SAME voltage?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes — that\'s the defining feature of parallel circuits. Each branch connects directly between the two voltage rails (like outlets in a house). One branch failing doesn\'t affect others — which is why house wiring is parallel (one broken lamp doesn\'t darken the whole house). Current splits among branches; voltage is shared.',
  },
  {
    id: 'elec-21', domain: 1, subdomain: 'Electricity & Circuits', type: 'single', difficulty: 'hard',
    question: 'Two resistors, 4.0 Ω and 12 Ω, are in PARALLEL. What is the equivalent resistance?',
    options: ['16 Ω', '8 Ω', '3.0 Ω', '0.33 Ω'],
    correctAnswers: [2],
    explanation: '1/R = 1/4 + 1/12 = 3/12 + 1/12 = 4/12 = 1/3 → R = 3.0 Ω. Parallel resistance is always SMALLER than the smallest individual resistor (because current has more paths to flow). Memorize the two-resistor parallel formula: R = (R₁·R₂)/(R₁+R₂) = (4·12)/(4+12) = 48/16 = 3.0 Ω.',
  },
  {
    id: 'elec-22', domain: 1, subdomain: 'Electricity & Circuits', type: 'single', difficulty: 'medium',
    question: 'What is the role of a fuse or circuit breaker in a household circuit?',
    options: ['Boosts voltage', 'Stores electrical energy', 'Interrupts current if it exceeds a safe value, protecting against fires', 'Converts AC to DC'],
    correctAnswers: [2],
    explanation: 'Fuses and circuit breakers cut off current when it exceeds a safe limit (typically 15 or 20 A for household circuits). Without them, overheating wires could ignite insulation and start a fire. Fuses use a metal strip that melts when overheated (one-time use); breakers use a magnetic or thermal trip mechanism (resettable).',
  },

  // ─── Magnetism ────────────────────────────────────────────────
  {
    id: 'mag-16', domain: 1, subdomain: 'Magnetism', type: 'single', difficulty: 'easy',
    question: 'What is the SI unit of magnetic field strength?',
    options: ['Newton', 'Ampere', 'Tesla', 'Joule'],
    correctAnswers: [2],
    explanation: 'The Tesla (T) is the SI unit for magnetic field strength. Named after Nikola Tesla. Earth\'s magnetic field is about 50 microteslas. A refrigerator magnet is around 0.01 T. MRI machines use 1.5 to 3 T — strong enough to dangerously accelerate metal objects toward the magnet.',
  },
  {
    id: 'mag-17', domain: 1, subdomain: 'Magnetism', type: 'single', difficulty: 'medium',
    question: 'A wire carrying electric current produces:',
    options: ['No magnetic field', 'A magnetic field circling the wire', 'An electric field only', 'Light'],
    correctAnswers: [1],
    explanation: 'A moving charge creates a magnetic field. For a straight wire, the field forms circles around the wire (right-hand rule: thumb points in current direction, fingers curl in direction of field). This is the foundation of electromagnetism — Oersted\'s 1820 discovery that electric currents create magnetic fields.',
  },
  {
    id: 'mag-18', domain: 1, subdomain: 'Magnetism', type: 'multi', difficulty: 'medium',
    question: 'Which of the following are CORRECT statements about magnetic poles? (Select all that apply)',
    options: ['Like poles repel; unlike poles attract', 'Magnetic monopoles (single isolated poles) have never been observed in nature', 'Earth\'s geographic North Pole is actually a magnetic SOUTH pole', 'Cutting a bar magnet in half produces two separate single-pole pieces'],
    correctAnswers: [0, 1, 2],
    explanation: 'Like poles repel, unlike attract. No isolated magnetic monopole has ever been observed — cutting a magnet just produces two smaller magnets, each with both N and S poles. Earth\'s geographic north is magnetically south (which is why compass NORTH points there). The last statement is wrong — you cannot isolate a single pole.',
  },
  {
    id: 'mag-19', domain: 1, subdomain: 'Magnetism', type: 'single', difficulty: 'medium',
    question: 'Faraday\'s Law states that an EMF is induced in a circuit when:',
    options: ['Current is constant', 'Magnetic flux through the circuit changes', 'Two wires touch', 'Temperature increases'],
    correctAnswers: [1],
    explanation: 'Faraday\'s Law: a CHANGE in magnetic flux through a circuit induces an EMF (voltage). The rate of change matters — faster change = bigger EMF. This is the principle behind electric generators (rotating magnet near a coil), transformers, and electric guitars (vibrating string disturbs magnetic flux through a pickup coil).',
  },
  {
    id: 'mag-20', domain: 1, subdomain: 'Magnetism', type: 'yesno', difficulty: 'easy',
    question: 'Can a permanent magnet attract a piece of unmagnetized iron?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes — the permanent magnet induces temporary magnetization in the iron (aligning the iron\'s magnetic domains), so the iron becomes a temporary magnet itself, and the two attract. Once the permanent magnet is removed, the iron\'s magnetization decays (in soft iron) or partially persists (in steel — that\'s how horseshoe magnets are made).',
  },
  {
    id: 'mag-21', domain: 1, subdomain: 'Magnetism', type: 'single', difficulty: 'hard',
    question: 'A charged particle moving perpendicular to a magnetic field experiences:',
    options: ['No force', 'A force in the direction of motion (speeding it up)', 'A force perpendicular to both velocity and field (circular motion)', 'A force opposite to its motion (slowing it down)'],
    correctAnswers: [2],
    explanation: 'The magnetic force on a moving charged particle (F = qv × B) is always PERPENDICULAR to both the velocity and the field. This causes circular motion — perpendicular force constantly bends the path without changing speed. Mass spectrometers use this to separate ions by mass; particle accelerators use it to keep beams on track.',
  },
  {
    id: 'mag-22', domain: 1, subdomain: 'Magnetism', type: 'single', difficulty: 'medium',
    question: 'An electric motor and an electric generator are essentially:',
    options: ['Completely unrelated devices', 'The same device used in opposite directions — motors use electricity to make motion, generators use motion to make electricity', 'Both convert chemical energy to electrical energy', 'Only used in specific specialized applications'],
    correctAnswers: [1],
    explanation: 'Motors and generators share the same fundamental structure (coil + magnet + rotating part). A motor takes electric current in and produces rotation (electrical → mechanical energy). A generator does the opposite: mechanical rotation through a magnetic field induces current (mechanical → electrical energy). The bicycle dynamo and electric drill demonstrate both directions.',
  },
  {
    id: 'kin-23', domain: 1, subdomain: 'Kinematics', type: 'single', difficulty: 'medium',
    question: 'On a position-vs-time graph, what does the slope of the line represent?',
    options: ['Acceleration', 'Velocity', 'Total distance', 'Time'],
    correctAnswers: [1],
    explanation: 'Slope of position-vs-time = velocity. Steeper slope = faster motion. A horizontal line (zero slope) means stationary. On a velocity-vs-time graph, the slope is acceleration and the area under the curve is displacement. Reading graphs is a core skill — every physics test asks you to interpret motion graphs.',
  },
  {
    id: 'ener-23', domain: 1, subdomain: 'Energy & Momentum', type: 'single', difficulty: 'easy',
    question: 'A pendulum at its highest point has maximum:',
    options: ['Kinetic energy', 'Gravitational potential energy', 'Both equal to zero', 'Friction'],
    correctAnswers: [1],
    explanation: 'At the top of its swing, the pendulum is momentarily stationary — kinetic energy is zero, but it sits at maximum height, so gravitational PE is maximum. At the bottom of the swing, the reverse: max KE, min PE. Total mechanical energy (KE + PE) stays constant if friction is negligible — a clean demonstration of energy conservation.',
  },
  {
    id: 'wave-23', domain: 1, subdomain: 'Waves & Sound', type: 'yesno', difficulty: 'easy',
    question: 'Does sound require a medium (such as air, water, or solid) to travel?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. Sound is a mechanical wave that propagates through the vibration of particles. No particles = no sound. This is why a vacuum bell jar with a ringing bell inside goes silent when air is pumped out — and why explosions in outer space are silent in reality (despite movie sound effects).',
  },
  {
    id: 'opt-23', domain: 1, subdomain: 'Light & Optics', type: 'multi', difficulty: 'medium',
    question: 'Which of the following are TRUE about a concave (converging) mirror? (Select all that apply)',
    options: ['Can form real, inverted images', 'Can form virtual, upright images when the object is closer than the focal point', 'Used in telescopes and headlights', 'Always produces magnified images regardless of object position'],
    correctAnswers: [0, 1, 2],
    explanation: 'Concave mirrors converge light. When the object is farther than the focal point, they form REAL inverted images (telescope, satellite dish). When closer than the focal point, they form VIRTUAL upright magnified images (shaving mirror, makeup mirror). Magnification varies with distance — not always magnified.',
  },
  {
    id: 'elec-23', domain: 1, subdomain: 'Electricity & Circuits', type: 'single', difficulty: 'medium',
    question: 'Which of these everyday devices uses ALTERNATING current (AC)?',
    options: ['A flashlight powered by AA batteries', 'A car\'s headlights', 'A microwave oven plugged into a wall outlet', 'A smartphone running on its battery'],
    correctAnswers: [2],
    explanation: 'AC (alternating current) flows from wall outlets — the current changes direction 60 times per second in the US (60 Hz). DC (direct current) flows in one direction — from batteries (flashlights, smartphones, cars). Devices that plug into the wall sometimes have AC adapters that convert AC to DC internally (laptop chargers, phone chargers).',
  },
  {
    id: 'mag-23', domain: 1, subdomain: 'Magnetism', type: 'single', difficulty: 'easy',
    question: 'What is the strength of Earth\'s magnetic field, approximately?',
    options: ['50 microteslas', '5 teslas', '50 teslas', '0.5 teslas'],
    correctAnswers: [0],
    explanation: 'Earth\'s magnetic field is roughly 25–65 microteslas depending on location — about 50 µT on average. That\'s much weaker than a refrigerator magnet (about 5 mT). Yet it\'s strong enough to align a compass needle and protect the planet by deflecting much of the solar wind, creating the auroras at the poles.',
  },
];
