// Question bank for ENG3 — English Language Arts 3 (11th grade SC).
// Covers all ELA strands: Reading Literary, Reading Informational,
// Literary Devices & Craft, Argument & Rhetoric, Language & Conventions,
// Research Writing, and Speaking & Listening.

export type QuestionType = 'single' | 'multi' | 'ordering' | 'yesno';

export interface Question {
  id: string;
  domain: 1;
  subdomain: string;
  type: QuestionType;
  difficulty: 'easy' | 'medium' | 'hard';
  question: string;
  options: string[];
  correctAnswers: number[];
  explanation: string;
  examTip?: string;
  codeSnippet?: string;
}

export const questions: Question[] = [

  // ══════════════════════════════════════════════════════════════════
  // Reading Literature
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'rl-01',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'easy',
    question: 'A story told from the perspective of a narrator who knows the thoughts and feelings of all characters is written in which point of view?',
    options: ['First-person limited', 'Third-person limited', 'Third-person omniscient', 'Second-person'],
    correctAnswers: [2],
    explanation: 'Third-person omniscient narrators have unlimited access to the inner lives of all characters. "Omniscient" means all-knowing. First-person is told by a character using "I." Third-person limited stays inside one character\'s head only. Second-person uses "you" and is rare.',
  },
  {
    id: 'rl-02',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'easy',
    question: 'In Freytag\'s pyramid, which stage immediately follows the climax?',
    options: ['Exposition', 'Rising action', 'Falling action', 'Resolution'],
    correctAnswers: [2],
    explanation: 'Freytag\'s pyramid flows: Exposition → Rising Action → Climax → Falling Action → Resolution (denouement). After the climax — the moment of highest tension — the falling action winds down the consequences before the story reaches its resolution.',
  },
  {
    id: 'rl-03',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'A poem\'s speaker addresses a dead friend directly using "you." The speaker is different from the poet. Which term describes the speaker\'s direct address to someone not present?',
    options: ['Apostrophe', 'Allusion', 'Anaphora', 'Assonance'],
    correctAnswers: [0],
    explanation: 'Apostrophe is the rhetorical device of addressing someone absent or dead, or even an abstract idea, as if present. It is distinct from the poet\'s voice — the speaker is the persona in the poem. Allusion refers to another text, anaphora is repetition at line starts, and assonance is vowel repetition.',
  },
  {
    id: 'rl-04',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'The rhyme scheme ABAB CDCD EFEF GG is characteristic of which poetic form?',
    options: ['Petrarchan sonnet', 'Shakespearean sonnet', 'Villanelle', 'Ode'],
    correctAnswers: [1],
    explanation: 'The Shakespearean (English) sonnet has three quatrains (ABAB CDCD EFEF) and a final couplet (GG). The Petrarchan sonnet is ABBAABBA CDECDE (or similar). A villanelle uses two repeating refrains in a 19-line structure. An ode is a longer praise poem with no fixed rhyme scheme requirement.',
  },
  {
    id: 'rl-05',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'yesno',
    difficulty: 'easy',
    question: 'True or False: Tone refers to the emotional atmosphere a text creates in the reader, while mood refers to the author\'s attitude toward the subject.',
    options: ['True', 'False'],
    correctAnswers: [1],
    explanation: 'This is reversed. Tone is the author\'s attitude toward the subject (e.g., sarcastic, reverent, melancholic). Mood is the emotional atmosphere the reader experiences. A horror story\'s tone might be detached and clinical while the mood it creates is one of dread.',
  },
  {
    id: 'rl-06',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are characteristics of an epistolary novel? Select ALL that apply.',
    options: [
      'The story is told through letters, diary entries, or other documents',
      'The narrative uses an unreliable narrator because documents are written by characters with limited knowledge',
      'The author directly addresses the reader in italicized asides',
      'Readers must infer events between documents',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'An epistolary novel (from Latin "epistola," letter) is told through documents written by characters, who naturally have limited perspectives — making them inherently unreliable narrators. Readers must piece together what happens between entries. The author directly addressing the reader is a metafictional device, not a characteristic of the epistolary form.',
  },
  {
    id: 'rl-07',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'hard',
    question: 'In a poem, the moment of shift in thought or emotion — often signaled by "but," "yet," or "however" — is called the:',
    options: ['Enjambment', 'Volta', 'Caesura', 'Couplet'],
    correctAnswers: [1],
    explanation: 'The volta (Italian for "turn") is the pivot point in a poem where the speaker\'s thinking shifts — a classic move in sonnets where the sestet responds to or complicates the octave. Enjambment is when a line continues without punctuation into the next. Caesura is a mid-line pause. A couplet is two consecutive rhyming lines.',
  },
  {
    id: 'rl-08',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'A character\'s most important trait does not change from beginning to end of the story. This character is best described as:',
    options: ['Dynamic', 'Static', 'Foil', 'Protagonist'],
    correctAnswers: [1],
    explanation: 'A static character does not undergo significant internal change. A dynamic character changes meaningfully through the story\'s events. A foil is a character who contrasts with and highlights the protagonist\'s traits. Protagonist simply means the central character, who may be either static or dynamic.',
  },
  {
    id: 'rl-09',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'Iambic pentameter means each line of a poem has:',
    options: [
      'Ten syllables in a pattern of stressed-unstressed feet',
      'Five iambs, each consisting of one unstressed syllable followed by one stressed syllable',
      'Five syllables alternating between stressed and unstressed',
      'Ten iambic feet with equal stress on each',
    ],
    correctAnswers: [1],
    explanation: 'An iamb is an unstressed syllable followed by a stressed syllable (da-DUM). Pentameter means five feet per line. Iambic pentameter = 5 iambs = 10 syllables per line, following the pattern da-DUM da-DUM da-DUM da-DUM da-DUM. It is the most common meter in English poetry and Shakespeare\'s plays.',
  },
  {
    id: 'rl-10',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'ordering',
    difficulty: 'easy',
    question: 'Arrange the stages of Freytag\'s Pyramid in the correct narrative order, from first to last.',
    options: ['Climax', 'Exposition', 'Falling Action', 'Rising Action', 'Resolution'],
    correctAnswers: [1, 3, 0, 2, 4],
    explanation: 'Freytag\'s Pyramid runs: Exposition (background and setting) → Rising Action (conflict builds) → Climax (peak tension) → Falling Action (consequences unfold) → Resolution/Denouement (loose ends tied). Every story, regardless of genre, can be mapped onto this structure.',
  },
  {
    id: 'rl-11',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'When a line of poetry continues without grammatical pause into the next line, this technique is called:',
    options: ['Caesura', 'End-stopping', 'Enjambment', 'Elision'],
    correctAnswers: [2],
    explanation: 'Enjambment (from French "enjamber," to straddle) is when a sentence or phrase runs from one line into the next without punctuation. It creates forward momentum and can build suspense. End-stopping is the opposite — a line that concludes with a period or comma. Caesura is a pause within a line.',
  },
  {
    id: 'rl-12',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'hard',
    question: 'A story that begins in the middle of the action, then uses flashbacks to fill in the backstory, is said to begin:',
    options: ['In medias res', 'With a frame narrative', 'With a nonlinear prologue', 'In flagrante delicto'],
    correctAnswers: [0],
    explanation: '"In medias res" is Latin for "in the middle of things." It is a narrative technique that drops the reader into the action, creating immediate engagement. Details and backstory are delivered later through flashbacks or exposition. Many epics (Homer\'s Iliad) and modern novels use this technique.',
  },
  {
    id: 'rl-13',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'yesno',
    difficulty: 'easy',
    question: 'True or False: The theme of a story is the same as its subject.',
    options: ['True', 'False'],
    correctAnswers: [1],
    explanation: 'Theme and subject are distinct. Subject is the topic (e.g., "war," "friendship"). Theme is the insight or statement the story makes about that topic (e.g., "War destroys the humanity of those who wage it"). Themes are full ideas, not just nouns. A story can have multiple themes.',
  },
  {
    id: 'rl-14',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are ways an author\'s choice of narrative structure can affect meaning? Select ALL that apply.',
    options: [
      'A nonlinear structure can create suspense by withholding information',
      'A frame narrative distances the inner story, affecting its reliability',
      'Linear structure guarantees an unreliable narrator',
      'An epistolary structure limits the narrator\'s perspective to what each character knows',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'Nonlinear structure withholds chronological information, creating suspense. Frame narratives (a story within a story) affect reliability because the framing narrator has an agenda. Epistolary structure limits perspective to documents written by fallible characters. Linear structure alone says nothing about narrator reliability — that depends on characterization.',
  },
  {
    id: 'rl-15',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'hard',
    question: 'A character in a novel exists primarily to highlight the protagonist\'s qualities by contrast. This character is called a:',
    options: ['Antagonist', 'Foil', 'Static character', 'Round character'],
    correctAnswers: [1],
    explanation: 'A foil character is designed to contrast with the protagonist, making the protagonist\'s traits more apparent by comparison. For example, Laertes serves as a foil to Hamlet — both lose fathers but respond differently. A foil may be an antagonist, but not necessarily. "Round" and "flat" describe character depth, not function.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Reading Informational Text
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'ri-01',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'easy',
    question: 'An author writes an article explaining why the school lunch period should be extended. The primary purpose of this text is to:',
    options: ['Inform', 'Persuade', 'Entertain', 'Describe'],
    correctAnswers: [1],
    explanation: 'When an author makes an argument for why something should change, the primary purpose is to persuade — to convince the reader to adopt the author\'s position. Informational texts primarily inform (present facts without taking sides). Entertainment focuses on engaging readers emotionally. Description depicts something without necessarily arguing a point.',
  },
  {
    id: 'ri-02',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'medium',
    question: 'What is the difference between a central idea and a main idea in informational text?',
    options: [
      'They are synonyms — both refer to the author\'s primary argument',
      'Central idea is the overarching claim of the whole text; main idea is the primary point of a single paragraph or section',
      'Central idea applies only to fiction; main idea applies only to nonfiction',
      'Main idea is what the reader thinks; central idea is what the author intended',
    ],
    correctAnswers: [1],
    explanation: 'Central idea is the overall unifying claim or message of an entire text — what the whole piece is "about" at its highest level. Main idea refers to the primary point of a specific paragraph or section that supports the central idea. Both terms appear in literary analysis, both apply to nonfiction, and both refer to authorial intent.',
  },
  {
    id: 'ri-03',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'medium',
    question: 'An article uses the structure "problem → solution." A reader encounters this structure when the author:',
    options: [
      'Presents events in the order they happened',
      'Groups ideas by similarities and differences',
      'Identifies a difficulty and then proposes ways to address it',
      'Explains why an event happened and what resulted from it',
    ],
    correctAnswers: [2],
    explanation: 'Problem-solution structure presents a challenge or issue, then argues for one or more ways to address it. Chronological order presents events in time sequence. Compare-contrast groups by similarities/differences. Cause-effect explains why something happened and what resulted from it — different from problem-solution, which is prescriptive.',
  },
  {
    id: 'ri-04',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'multi',
    difficulty: 'medium',
    question: 'When evaluating a source\'s credibility, which of the following are relevant factors? Select ALL that apply.',
    options: [
      'Whether the author has relevant expertise or credentials',
      'Whether the source has been peer-reviewed or editorially reviewed',
      'Whether the source presents a point of view different from your own',
      'Whether the publication date is recent enough to be relevant',
      'Whether the source cites other reputable sources',
    ],
    correctAnswers: [0, 1, 3, 4],
    explanation: 'Credibility factors include author expertise, editorial or peer-review process, currency (date), and use of credible citations. A source presenting a different viewpoint is NOT automatically less credible — bias is separate from credibility. A source can be credible even if you disagree with its conclusions, as long as it uses reliable evidence and methodology.',
  },
  {
    id: 'ri-05',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'easy',
    question: 'A primary source is best described as:',
    options: [
      'A document created by scholars who studied historical events',
      'A text that gives a first-hand or direct account of an event or experience',
      'Any source that is cited in a peer-reviewed journal',
      'The most reliable type of source in any research context',
    ],
    correctAnswers: [1],
    explanation: 'Primary sources are original, first-hand accounts: a soldier\'s diary, a photograph, a speech, census data, or an interview. Secondary sources analyze or interpret primary sources — like a textbook or historical analysis. Primary sources are valuable for their directness, but they also contain bias and must be evaluated critically.',
  },
  {
    id: 'ri-06',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'yesno',
    difficulty: 'medium',
    question: 'True or False: Distinguishing between fact and opinion requires looking at whether a statement can be verified with evidence, not whether you agree with it.',
    options: ['True', 'False'],
    correctAnswers: [0],
    explanation: 'A fact is a statement verifiable through objective evidence ("The Earth orbits the Sun"). An opinion is a judgment or interpretation ("The Earth is the most beautiful planet"). Your agreement has nothing to do with classification. A statement you strongly disagree with can still be a verifiable fact, and a statement you believe deeply can still be an opinion.',
  },
  {
    id: 'ri-07',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'hard',
    question: 'When synthesizing two texts on the same topic, a writer should:',
    options: [
      'Present the texts separately and avoid mixing their ideas',
      'Choose the more credible source and dismiss the other',
      'Identify agreements, disagreements, and gaps, then draw a conclusion that accounts for both',
      'Always side with the more recent text since newer information supersedes older',
    ],
    correctAnswers: [2],
    explanation: 'Synthesis means integrating multiple sources — not just summarizing them side by side. A skilled synthesizer finds where texts agree, disagree, or complement each other, then draws a conclusion that accounts for the full picture. More recent does not automatically mean more accurate, and dismissing a source rather than evaluating it is poor scholarly practice.',
  },
  {
    id: 'ri-08',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'medium',
    question: 'An author includes a bar graph showing rising global temperatures alongside a written argument about climate change. The graph primarily serves to:',
    options: [
      'Make the article look more professional',
      'Provide quantitative evidence that supports the author\'s central claim',
      'Contradict the written text with a different form of data',
      'Replace the need for written evidence in the paragraphs',
    ],
    correctAnswers: [1],
    explanation: 'Quantitative graphics — charts, graphs, tables — provide data-based evidence that supports or complicates textual claims. In a well-constructed informational text, visuals are integrated with the writing, not replacements for it. Readers should connect the graphic\'s data to the specific claims in the paragraphs around it.',
  },
  {
    id: 'ri-09',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'medium',
    question: 'Bias in a source means:',
    options: [
      'The source contains factual errors',
      'The source was written for a specific audience',
      'The source presents information in a way that reflects a particular perspective, potentially omitting contrary evidence',
      'The source is not credible and should not be used',
    ],
    correctAnswers: [2],
    explanation: 'All sources have some degree of bias — a perspective or angle from which the author approaches the topic. Bias means one-sided presentation that may omit, underweight, or frame contrary evidence unfavorably. Bias is different from error (factual mistakes) and different from audience (intended readers). Biased sources can still be cited; you just need to acknowledge and account for the bias.',
  },
  {
    id: 'ri-10',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'multi',
    difficulty: 'hard',
    question: 'Which of the following organizational structures present information in a cause → effect relationship? Select ALL that apply.',
    options: [
      'A text explaining why the Roman Empire fell and what changed afterward',
      'A text listing the pros and cons of solar energy',
      'A text showing how poverty leads to poor health outcomes',
      'A text describing the steps to apply for college in chronological order',
    ],
    correctAnswers: [0, 2],
    explanation: 'Cause-effect structure explains why something happened and what resulted. The Roman Empire\'s fall and its consequences is classic cause-effect. Poverty → poor health outcomes is also causal. Pros and cons is compare-contrast. A chronological sequence of steps is a process/procedural structure, not cause-effect — steps happen in sequence but step 1 doesn\'t necessarily cause step 2.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Literary Devices & Author's Craft
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'ld-01',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'easy',
    question: '"Life is a journey" is an example of which literary device?',
    options: ['Simile', 'Metaphor', 'Personification', 'Hyperbole'],
    correctAnswers: [1],
    explanation: 'A metaphor directly states that one thing IS another. "Life is a journey" declares equivalence without using "like" or "as." A simile would say "Life is LIKE a journey." Personification gives human qualities to non-human things. Hyperbole is extreme exaggeration for effect.',
  },
  {
    id: 'ld-02',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'easy',
    question: '"The wind whispered through the trees" uses which literary device?',
    options: ['Alliteration', 'Personification', 'Hyperbole', 'Oxymoron'],
    correctAnswers: [1],
    explanation: 'Personification gives human characteristics to non-human things. Wind cannot literally whisper (only humans whisper), so attributing this human action to wind is personification. Alliteration is repeated initial consonant sounds. Hyperbole is gross exaggeration. Oxymoron combines contradictory terms.',
  },
  {
    id: 'ld-03',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'Which of these is an example of verbal irony?',
    options: [
      'A fire station burns down',
      'A character says "Oh, wonderful" when something terrible happens',
      'A character discovers the person trying to help them is actually the villain',
      'A character learns their fate after the audience already knows it',
    ],
    correctAnswers: [1],
    explanation: 'Verbal irony occurs when someone says the opposite of what they mean — essentially sarcasm. Saying "Oh, wonderful" during a disaster is verbal irony. A fire station burning down is situational irony (an ironic situation). A character discovering someone is the villain is dramatic or situational irony. Audience knowing a character\'s fate before the character does is dramatic irony.',
  },
  {
    id: 'ld-04',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'Anaphora is a rhetorical device in which:',
    options: [
      'The last word of each clause is repeated at the start of the next',
      'The same word or phrase is repeated at the beginning of successive clauses',
      'Two opposite ideas are placed side by side for contrast',
      'A word imitates the sound it describes',
    ],
    correctAnswers: [1],
    explanation: 'Anaphora is the repetition of a word or phrase at the beginning of successive clauses or sentences. "We shall fight on the beaches, we shall fight on the landing grounds, we shall fight in the fields" — each clause starts with "we shall fight." This creates rhythm and emphasis. Option A describes anadiplosis. Option C is antithesis. Option D is onomatopoeia.',
  },
  {
    id: 'ld-05',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'hard',
    question: '"Ask not what your country can do for you — ask what you can do for your country" uses which device?',
    options: ['Anaphora', 'Chiasmus', 'Epistrophe', 'Parallel structure'],
    correctAnswers: [1],
    explanation: 'Chiasmus reverses the grammatical structure of phrases — "A B | B A." Here: "what your country can do for you" is flipped to "what you can do for your country." The two halves mirror each other in reversed order. Anaphora repeats at the beginning. Epistrophe repeats at the end. Parallel structure uses the same grammatical form but doesn\'t reverse.',
  },
  {
    id: 'ld-06',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are examples of sound devices? Select ALL that apply.',
    options: ['Alliteration', 'Assonance', 'Onomatopoeia', 'Hyperbole', 'Consonance'],
    correctAnswers: [0, 1, 2, 4],
    explanation: 'Sound devices manipulate the sounds of words: alliteration (repeated initial consonants), assonance (repeated vowel sounds), onomatopoeia (words that sound like what they describe — buzz, crack), and consonance (repeated consonant sounds within or at the end of words). Hyperbole is a figure of speech based on exaggeration, not sound.',
  },
  {
    id: 'ld-07',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'An author uses a reference to the story of Icarus when describing a character who overreaches and fails. This is an example of:',
    options: ['Allusion', 'Allegory', 'Metaphor', 'Symbol'],
    correctAnswers: [0],
    explanation: 'An allusion is an indirect reference to a well-known person, event, text, or myth, relying on shared knowledge. The Icarus myth (flying too close to the sun) is a classic allusion for hubris and self-destruction. Allegory is an extended narrative that represents abstract ideas throughout. A symbol is a concrete object representing an abstract concept. Metaphor directly equates two things.',
  },
  {
    id: 'ld-08',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'yesno',
    difficulty: 'medium',
    question: 'True or False: The effect of a literary device on a text is just as important as correctly naming the device.',
    options: ['True', 'False'],
    correctAnswers: [0],
    explanation: 'Identifying a device by name is only the first step. The key question is always WHY the author chose it — what emotional, thematic, or structural effect does it create? An essay that just says "the author uses personification" without explaining its purpose earns partial credit at best. Analysis means connecting the device to its effect on meaning or tone.',
  },
  {
    id: 'ld-09',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'easy',
    question: 'Which device involves giving a part the name of the whole, or a whole the name of a part? For example, "all hands on deck."',
    options: ['Metonymy', 'Synecdoche', 'Allusion', 'Allegory'],
    correctAnswers: [1],
    explanation: '"All hands on deck" uses "hands" (a part of a person) to stand for the whole person. This is synecdoche — part for the whole or whole for the part. Metonymy substitutes a related concept ("the Crown" for the monarchy — Crown is associated with but not a part of royalty). Both are figures of speech but use different relationships.',
  },
  {
    id: 'ld-10',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'hard',
    question: 'Dramatic irony occurs when:',
    options: [
      'The author makes a sarcastic remark directed at the characters',
      'The audience or reader knows something that a character does not',
      'A character says one thing but means the opposite',
      'Two characters misunderstand each other in a comical way',
    ],
    correctAnswers: [1],
    explanation: 'Dramatic irony is the gap between what the audience knows and what a character knows. In Romeo and Juliet, the audience knows Juliet is asleep (not dead) while Romeo does not — a textbook example. This creates tension, suspense, or tragedy. Saying one thing but meaning the opposite is verbal irony. The author being sarcastic is not a defined literary term in this context.',
  },
  {
    id: 'ld-11',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'An extended metaphor that runs throughout an entire work, in which characters, events, and settings represent abstract ideas, is called:',
    options: ['Allegory', 'Symbol', 'Allusion', 'Motif'],
    correctAnswers: [0],
    explanation: 'Allegory is a sustained, narrative-length comparison where the entire story operates on two levels — literal and symbolic. Animal Farm is an allegory: the farm is literally a farm but represents Soviet Russia; each animal represents a political figure or class. A symbol is a single object with meaning. An allusion is a reference. A motif is a recurring element that contributes to theme.',
  },
  {
    id: 'ld-12',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'easy',
    question: '"I\'ve told you a million times" is an example of:',
    options: ['Metaphor', 'Understatement', 'Hyperbole', 'Oxymoron'],
    correctAnswers: [2],
    explanation: 'Hyperbole is deliberate, dramatic exaggeration used for emphasis or humor — not meant to be taken literally. No one has actually said something a million times. Understatement is the opposite of hyperbole (minimizing something). A metaphor directly compares two unlike things. An oxymoron combines two contradictory terms ("deafening silence").',
  },
  {
    id: 'ld-13',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'multi',
    difficulty: 'hard',
    question: 'Which of the following are structural devices an author can use to shape meaning? Select ALL that apply.',
    options: ['Parallel structure', 'Anaphora', 'Flashback', 'Foreshadowing', 'Assonance'],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'Parallel structure (grammatically equivalent sentence parts), anaphora (repeated phrase at clause beginnings), flashback (returning to past events), and foreshadowing (hinting at future events) are all structural devices that shape how a story or argument is organized and how it unfolds. Assonance is a sound device, not a structural one — it affects texture at the word level.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Argument & Rhetoric
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'ar-01',
    domain: 1,
    subdomain: 'Argument & Rhetoric',
    type: 'single',
    difficulty: 'easy',
    question: 'An author builds credibility by citing their professional experience and academic credentials. This is an appeal to:',
    options: ['Pathos', 'Logos', 'Ethos', 'Kairos'],
    correctAnswers: [2],
    explanation: 'Ethos is the appeal to credibility, authority, or character — convincing the audience that the speaker is trustworthy and qualified. Citing credentials is a classic ethos move. Pathos appeals to emotion. Logos appeals to logic and evidence. Kairos refers to the timeliness or opportune moment of an argument — not one of the original three Aristotelian appeals.',
  },
  {
    id: 'ar-02',
    domain: 1,
    subdomain: 'Argument & Rhetoric',
    type: 'single',
    difficulty: 'easy',
    question: 'An argument that uses statistical data and scientific studies to support its claim is primarily using:',
    options: ['Ethos', 'Pathos', 'Logos', 'Anaphora'],
    correctAnswers: [2],
    explanation: 'Logos is the appeal to logic, reason, and evidence — statistics, studies, expert findings, and logical reasoning. Data-driven arguments are logos-heavy. Anaphora is a structural/rhetorical device (repeated phrase at line starts), not an appeal.',
  },
  {
    id: 'ar-03',
    domain: 1,
    subdomain: 'Argument & Rhetoric',
    type: 'single',
    difficulty: 'medium',
    question: 'An author describes a starving child in vivid detail to convince readers to donate to a charity. This is an appeal to:',
    options: ['Logos', 'Ethos', 'Pathos', 'Deduction'],
    correctAnswers: [2],
    explanation: 'Pathos is the appeal to emotion — using vivid imagery, personal stories, or emotional language to move the audience. Describing a suffering child to trigger compassion and generosity is a clear pathos appeal. This isn\'t inherently manipulative, but it should be paired with factual evidence (logos) for a strong argument.',
  },
  {
    id: 'ar-04',
    domain: 1,
    subdomain: 'Argument & Rhetoric',
    type: 'single',
    difficulty: 'medium',
    question: 'Which logical fallacy occurs when an argument attacks the character of the person making an argument rather than addressing the argument itself?',
    options: ['Straw man', 'Ad hominem', 'Appeal to authority', 'False dichotomy'],
    correctAnswers: [1],
    explanation: 'Ad hominem (Latin: "to the person") attacks the person rather than their argument. "You can\'t trust her argument about taxes — she filed for bankruptcy once" is ad hominem. Straw man misrepresents an opponent\'s position. Appeal to authority uses an expert\'s opinion without adequate evidence. False dichotomy presents only two options when more exist.',
  },
  {
    id: 'ar-05',
    domain: 1,
    subdomain: 'Argument & Rhetoric',
    type: 'single',
    difficulty: 'medium',
    question: 'Which fallacy presents only two options when in reality more options exist?',
    options: ['Slippery slope', 'Hasty generalization', 'False dichotomy', 'Circular reasoning'],
    correctAnswers: [2],
    explanation: 'False dichotomy (also called either/or fallacy) artificially limits options to two: "Either you support this policy or you hate this country." Real issues usually have multiple positions. Slippery slope claims one event will inevitably lead to extreme consequences. Hasty generalization draws a broad conclusion from insufficient evidence. Circular reasoning uses the conclusion as a premise.',
  },
  {
    id: 'ar-06',
    domain: 1,
    subdomain: 'Argument & Rhetoric',
    type: 'single',
    difficulty: 'hard',
    question: 'In the Toulmin model, the _____ is the specific case the arguer is making based on the evidence.',
    options: ['Warrant', 'Claim', 'Backing', 'Qualifier'],
    correctAnswers: [1],
    explanation: 'In the Toulmin model: Claim = the position being argued. Data = the evidence. Warrant = the assumption connecting data to claim. Backing = support for the warrant. Qualifier = limits on the claim\'s certainty (e.g., "usually," "in most cases"). Rebuttal = acknowledgment of counterarguments. The claim is the thesis-equivalent — what the arguer is trying to prove.',
  },
  {
    id: 'ar-07',
    domain: 1,
    subdomain: 'Argument & Rhetoric',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are examples of logical fallacies? Select ALL that apply.',
    options: [
      'Drawing a conclusion from a sample of only 3 people and applying it to all teenagers',
      'Arguing that banning one type of gun will eventually lead to a total firearms ban',
      'Citing a study with 10,000 participants to support a health claim',
      '"Since you can\'t prove ghosts don\'t exist, they must exist"',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'Drawing a conclusion from 3 people and generalizing to all teenagers is a hasty generalization. Arguing gun bans lead inevitably to total bans is a slippery slope. "You can\'t disprove it therefore it\'s true" is an appeal to ignorance. Citing a large, well-designed study is a legitimate logos appeal — not a fallacy.',
  },
  {
    id: 'ar-08',
    domain: 1,
    subdomain: 'Argument & Rhetoric',
    type: 'yesno',
    difficulty: 'medium',
    question: 'True or False: A strong counterargument in an essay weakens the writer\'s overall argument.',
    options: ['True', 'False'],
    correctAnswers: [1],
    explanation: 'Acknowledging and refuting a strong counterargument actually strengthens an essay. It demonstrates that the writer has considered other perspectives and can respond to them — a sign of intellectual honesty and argumentative sophistication. Ignoring obvious counterarguments makes an essay look one-sided and weaker. The key is to acknowledge the counterargument AND rebut it.',
  },
  {
    id: 'ar-09',
    domain: 1,
    subdomain: 'Argument & Rhetoric',
    type: 'single',
    difficulty: 'easy',
    question: 'The claim-evidence-reasoning (CER) structure requires that after presenting evidence, a writer must:',
    options: [
      'Move immediately to the next piece of evidence',
      'Restate the claim word for word',
      'Explain how and why the evidence supports the claim',
      'Acknowledge a counterargument',
    ],
    correctAnswers: [2],
    explanation: 'The reasoning step (the "R" in CER) is where writers explain the connection between their evidence and their claim — WHY does this evidence matter? What does it show? Without reasoning, evidence just sits there. Many student writers skip reasoning, which makes paragraphs feel thin. Restating the claim verbatim adds no value.',
  },
  {
    id: 'ar-10',
    domain: 1,
    subdomain: 'Argument & Rhetoric',
    type: 'single',
    difficulty: 'hard',
    question: 'An arguer says: "If we allow students to use phones in class, next they\'ll be allowed to use them on tests, then they won\'t need to learn anything, and education will collapse." This is an example of:',
    options: ['Ad hominem', 'Slippery slope', 'False dichotomy', 'Bandwagon'],
    correctAnswers: [1],
    explanation: 'Slippery slope fallacy claims that one event will inevitably lead to a series of increasingly extreme consequences, usually without evidence that each step would follow from the previous. The leap from "phones in class" to "education will collapse" involves unproven chains of causation. It\'s a fallacy because each link needs to be argued, not assumed.',
  },
  {
    id: 'ar-11',
    domain: 1,
    subdomain: 'Argument & Rhetoric',
    type: 'single',
    difficulty: 'medium',
    question: 'Which type of evidence is generally considered strongest in an academic argument about health policy?',
    options: [
      'A personal anecdote from the author\'s own experience',
      'A peer-reviewed study published in a medical journal',
      'A celebrity endorsement of the policy',
      'An emotional story about a patient who was affected',
    ],
    correctAnswers: [1],
    explanation: 'Peer-reviewed studies are the gold standard in academic arguments because they have been evaluated by independent experts, use controlled methodology, and represent systematic evidence rather than a single case. Personal anecdotes and emotional stories can be powerful pathos appeals but lack statistical weight. Celebrity endorsements are appeals to authority without relevant expertise.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Language & Conventions
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'lc-01',
    domain: 1,
    subdomain: 'Language & Conventions',
    type: 'single',
    difficulty: 'easy',
    question: 'Which sentence has correct subject-verb agreement?',
    options: [
      'The group of students were arguing loudly.',
      'Neither the teacher nor the students was ready.',
      'Each of the players are required to sign the waiver.',
      'The committee has reached a decision.',
    ],
    correctAnswers: [3],
    explanation: '"The committee has reached a decision" is correct. "Committee" is a collective noun treated as singular when acting as a unit (singular verb: "has"). Option A: "group" is collective-singular, so "was." Option B: with "neither...nor," the verb agrees with the closer subject ("students" → "were"). Option C: "Each" is always singular, so "is required."',
  },
  {
    id: 'lc-02',
    domain: 1,
    subdomain: 'Language & Conventions',
    type: 'single',
    difficulty: 'medium',
    question: 'Identify the sentence with a dangling modifier.',
    options: [
      'Running to the bus, Maria dropped her backpack.',
      'Having finished the exam, the students waited quietly.',
      'Walking through the park, the leaves were beautiful.',
      'After eating dinner, she went to the library.',
    ],
    correctAnswers: [2],
    explanation: 'A dangling modifier occurs when the modifying phrase doesn\'t logically connect to the subject of the main clause. "Walking through the park" implies a person is walking, but the subject of the main clause is "the leaves" — leaves can\'t walk. The intended subject is missing. It should read: "Walking through the park, I thought the leaves were beautiful." Options A, B, and D have clear subjects performing the introductory action.',
  },
  {
    id: 'lc-03',
    domain: 1,
    subdomain: 'Language & Conventions',
    type: 'single',
    difficulty: 'easy',
    question: 'Which sentence correctly uses a semicolon?',
    options: [
      'She studied all night; because she had an exam.',
      'She studied all night; she felt prepared for the exam.',
      'She studied; all night for the exam.',
      'She studied all night; and felt prepared.',
    ],
    correctAnswers: [1],
    explanation: 'A semicolon connects two independent clauses — clauses that can each stand alone as complete sentences. "She studied all night" and "she felt prepared for the exam" are both independent. Option A is wrong: "because she had an exam" is a dependent clause (starts with "because") — dependent clauses cannot follow a semicolon. Options C and D split sentences incorrectly.',
  },
  {
    id: 'lc-04',
    domain: 1,
    subdomain: 'Language & Conventions',
    type: 'single',
    difficulty: 'medium',
    question: 'Choose the correct word: "The new policy will _____ all employees."',
    options: ['effect', 'affect'],
    correctAnswers: [1],
    explanation: '"Affect" is usually a verb meaning to influence or impact. "Effect" is usually a noun meaning a result or outcome. "The policy will affect employees" (verb: to influence). You could also say "The policy will have a positive effect" (noun: result). A memory trick: Affect = Action (both start with A); Effect = End result (E). One exception: "to effect change" uses effect as a verb meaning "to bring about."',
  },
  {
    id: 'lc-05',
    domain: 1,
    subdomain: 'Language & Conventions',
    type: 'single',
    difficulty: 'medium',
    question: 'Which sentence demonstrates parallel structure?',
    options: [
      'She likes hiking, to swim, and to run.',
      'She likes hiking, swimming, and running.',
      'She likes hiking, swims, and to run.',
      'She likes to hike, swimming, and runs.',
    ],
    correctAnswers: [1],
    explanation: 'Parallel structure requires that items in a series use the same grammatical form. "Hiking, swimming, and running" are all gerunds (-ing nouns) — parallel. Options A, C, and D mix gerunds, infinitives, and conjugated verbs, which violates parallelism. Parallel structure makes writing clearer and more rhythmically satisfying.',
  },
  {
    id: 'lc-06',
    domain: 1,
    subdomain: 'Language & Conventions',
    type: 'single',
    difficulty: 'hard',
    question: 'Which sentence uses "who" correctly (as opposed to "whom")?',
    options: [
      'She is the candidate whom everyone believes will win.',
      'Whom do you think will be selected?',
      'Give the award to whoever deserves it most.',
      'The student whom received the scholarship was surprised.',
    ],
    correctAnswers: [2],
    explanation: '"Who/whoever" is the subject form; "whom/whomever" is the object form. In option C, "whoever" is the subject of "deserves" — subject form is correct. In option A, "whom everyone believes will win" — here "who" is the subject of "will win" (try substituting: "everyone believes he will win," not "him will win") — "who" is correct; "whom" is wrong. Option D: "who received" is subject — should be "who," not "whom."',
  },
  {
    id: 'lc-07',
    domain: 1,
    subdomain: 'Language & Conventions',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following sentences use commas correctly? Select ALL that apply.',
    options: [
      'My sister, who lives in Atlanta, is a doctor.',
      'The book that she recommended was excellent.',
      'He bought milk eggs and bread.',
      'Before the meeting began, she reviewed her notes.',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'Option A uses commas correctly around a non-restrictive clause ("who lives in Atlanta" — parenthetical information that can be removed). Option B correctly omits commas because "that she recommended" is a restrictive clause that identifies which book. Option C is missing the serial comma after "eggs" (should be "milk, eggs, and bread"). Option D correctly uses a comma after an introductory adverbial clause.',
  },
  {
    id: 'lc-08',
    domain: 1,
    subdomain: 'Language & Conventions',
    type: 'single',
    difficulty: 'easy',
    question: 'Which sentence uses active voice?',
    options: [
      'The exam was passed by most students.',
      'The novel was written by Toni Morrison.',
      'Most students passed the exam.',
      'The award was given to the winner by the committee.',
    ],
    correctAnswers: [2],
    explanation: 'Active voice: the subject performs the action (Most students PASSED the exam — subject "students" acts). Passive voice: the subject receives the action (The exam WAS PASSED by students). Active voice is generally preferred for clarity and directness. Passive voice is appropriate when the actor is unknown, unimportant, or deliberately omitted.',
  },
  {
    id: 'lc-09',
    domain: 1,
    subdomain: 'Language & Conventions',
    type: 'yesno',
    difficulty: 'easy',
    question: 'True or False: "Its" (without an apostrophe) is always correct when showing possession.',
    options: ['True', 'False'],
    correctAnswers: [0],
    explanation: '"Its" (no apostrophe) is the possessive pronoun — "the dog wagged its tail." "It\'s" (with apostrophe) is the contraction for "it is" or "it has." The apostrophe never indicates possession for pronouns (his, hers, its, theirs, yours, ours). This is a very common error. When in doubt: expand it — if "it is" fits, use "it\'s." If not, use "its."',
  },
  {
    id: 'lc-10',
    domain: 1,
    subdomain: 'Language & Conventions',
    type: 'single',
    difficulty: 'medium',
    question: 'A compound-complex sentence contains:',
    options: [
      'Two or more independent clauses and no dependent clauses',
      'One independent clause and one or more dependent clauses',
      'Two or more independent clauses and at least one dependent clause',
      'Only dependent clauses connected by conjunctions',
    ],
    correctAnswers: [2],
    explanation: 'Compound-complex = compound (two+ independent clauses) + complex (at least one dependent clause). Example: "She studied hard [independent], so she passed the exam [independent], although she was nervous [dependent]." Simple = one independent. Compound = two+ independent. Complex = one independent + one+ dependent. Compound-complex combines both.',
  },
  {
    id: 'lc-11',
    domain: 1,
    subdomain: 'Language & Conventions',
    type: 'single',
    difficulty: 'medium',
    question: 'A misplaced modifier occurs when:',
    options: [
      'A modifier is completely missing from the sentence',
      'A modifier is placed too far from the word it modifies, creating ambiguity',
      'A modifier describes an action rather than a noun',
      'A modifier is attached to a subject that cannot perform the action it describes',
    ],
    correctAnswers: [1],
    explanation: 'A misplaced modifier is positioned far from the word it modifies, making the sentence ambiguous or unintentionally funny. "She served cake to the guests on paper plates" — does "on paper plates" modify the cake or the guests? Correct: "She served cake on paper plates to the guests." A dangling modifier (option D) is when the intended noun is absent from the sentence entirely.',
  },
  {
    id: 'lc-12',
    domain: 1,
    subdomain: 'Language & Conventions',
    type: 'single',
    difficulty: 'easy',
    question: 'Which correctly uses "fewer" vs. "less"?',
    options: [
      'There are less students in the class this year.',
      'She has fewer patience than he does.',
      'There are fewer students in the class this year.',
      'She has less textbooks than he does.',
    ],
    correctAnswers: [2],
    explanation: '"Fewer" is used for countable nouns (students — you can count them). "Less" is used for uncountable nouns or abstract quantities (patience, time, water). "Fewer students, less patience." The classic grocery store sign "10 items or less" is technically incorrect — items are countable, so it should be "10 items or fewer."',
  },

  // ══════════════════════════════════════════════════════════════════
  // Research Writing
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'rw-01',
    domain: 1,
    subdomain: 'Research Writing',
    type: 'single',
    difficulty: 'easy',
    question: 'A strong thesis statement for an argumentative essay should be:',
    options: [
      'A factual statement that everyone agrees with',
      'A question the essay will answer',
      'A specific, arguable claim that can be supported with evidence',
      'A broad topic sentence introducing the subject',
    ],
    correctAnswers: [2],
    explanation: 'A strong thesis is specific (not vague), arguable (someone could disagree), and supportable with evidence. "Pollution is bad" is not a strong thesis — it\'s too vague and unopposed. "Local industries should be required to publish annual pollution reports because transparency reduces violations and holds companies accountable" is specific and arguable. A thesis is a claim, not a question.',
  },
  {
    id: 'rw-02',
    domain: 1,
    subdomain: 'Research Writing',
    type: 'single',
    difficulty: 'medium',
    question: 'What is the difference between paraphrasing and summarizing?',
    options: [
      'Paraphrasing is longer and restates a passage in your own words; summarizing is shorter and captures only the main idea',
      'Paraphrasing uses quotation marks; summarizing does not',
      'They are the same — both require you to use the original author\'s words',
      'Summarizing is always longer than paraphrasing',
    ],
    correctAnswers: [0],
    explanation: 'Paraphrasing restates a specific passage in your own words at approximately the same length — it captures detail and nuance. Summarizing condenses a larger section to its main idea only, leaving out supporting details. Neither uses quotation marks (that\'s direct quoting). Both require citation because you\'re still using someone else\'s ideas, even in your own words.',
  },
  {
    id: 'rw-03',
    domain: 1,
    subdomain: 'Research Writing',
    type: 'yesno',
    difficulty: 'medium',
    question: 'True or False: Paraphrasing someone\'s ideas without citing the source is still considered plagiarism.',
    options: ['True', 'False'],
    correctAnswers: [0],
    explanation: 'Plagiarism is presenting someone else\'s ideas as your own — whether you use their exact words or not. Paraphrasing without attribution is still plagiarism because you are using another person\'s original thinking. Citation tells readers where the idea came from and gives credit to the original author. Word-for-word copying without quotes AND citation is plagiarism.',
  },
  {
    id: 'rw-04',
    domain: 1,
    subdomain: 'Research Writing',
    type: 'single',
    difficulty: 'medium',
    question: 'In MLA format, the in-text citation for a quote from page 45 of a book by Sarah Jones would be:',
    options: [
      '(Jones, 45)',
      '(Jones 45)',
      '"Jones, p. 45"',
      '(Sarah Jones, page 45)',
    ],
    correctAnswers: [1],
    explanation: 'MLA in-text citations use (Author LastName PageNumber) with no comma and no "p." For Jones, page 45: (Jones 45). APA uses (Jones, 2023, p. 45) with a comma, year, and "p." Chicago/Turabian uses footnotes. These style differences matter in formal academic writing — know which style is expected.',
  },
  {
    id: 'rw-05',
    domain: 1,
    subdomain: 'Research Writing',
    type: 'single',
    difficulty: 'hard',
    question: 'Revision differs from editing in that revision:',
    options: [
      'Focuses on fixing spelling and grammar errors',
      'Involves reconsidering and restructuring ideas, argument, and organization',
      'Is done before writing the first draft',
      'Is only concerned with word choice and sentence variety',
    ],
    correctAnswers: [1],
    explanation: 'Revision (re-vision = seeing again) is a higher-order activity: reconsidering the argument, restructuring paragraphs, strengthening evidence, and clarifying ideas. Editing addresses lower-order concerns: grammar, mechanics, spelling, punctuation. Proofreading is the final check for surface errors. Good writers revise first, then edit, then proofread — in that order.',
  },
  {
    id: 'rw-06',
    domain: 1,
    subdomain: 'Research Writing',
    type: 'single',
    difficulty: 'medium',
    question: 'A signal phrase is used when incorporating sources to:',
    options: [
      'Replace in-text citations so quotes don\'t need to be cited',
      'Attribute the quotation or paraphrase to its source and integrate it smoothly',
      'Indicate that the information is common knowledge',
      'Show that the writer agrees with the cited source',
    ],
    correctAnswers: [1],
    explanation: 'A signal phrase introduces a quote or paraphrase by naming the author or source: "According to Smith...", "As the CDC reports...", "Jones argues that..." Signal phrases integrate evidence smoothly and attribute it — but they do NOT replace in-text citations; both are usually required. Signal phrases say nothing about the writer\'s agreement.',
  },
  {
    id: 'rw-07',
    domain: 1,
    subdomain: 'Research Writing',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are steps in the research writing process? Select ALL that apply.',
    options: [
      'Developing a research question',
      'Evaluating source credibility',
      'Deleting all evidence that contradicts your thesis',
      'Drafting an annotated bibliography',
      'Revising for clarity and argument strength',
    ],
    correctAnswers: [0, 1, 3, 4],
    explanation: 'The research writing process includes: developing a question, evaluating sources, annotating sources (annotated bibliography), drafting, revising, and editing. Deleting contradictory evidence is NOT a step — it is cherry-picking or confirmation bias, which produces dishonest arguments. Strong writers engage with counterevidence rather than hiding it.',
  },
  {
    id: 'rw-08',
    domain: 1,
    subdomain: 'Research Writing',
    type: 'ordering',
    difficulty: 'medium',
    question: 'Place these steps of the writing process in the correct order.',
    options: ['Brainstorm and research', 'Draft', 'Edit for grammar and mechanics', 'Proofread final copy', 'Revise structure and argument'],
    correctAnswers: [0, 1, 4, 2, 3],
    explanation: 'The correct writing process order is: Brainstorm/Research → Draft (get ideas on paper) → Revise (fix structure, argument, clarity — big picture) → Edit (grammar, mechanics — sentence level) → Proofread (final surface-level check). Many students skip revision and go straight to editing, missing the most important improvement step.',
  },
  {
    id: 'rw-09',
    domain: 1,
    subdomain: 'Research Writing',
    type: 'single',
    difficulty: 'easy',
    question: 'Which scenario represents academic plagiarism?',
    options: [
      'Using a direct quote with quotation marks and an in-text citation',
      'Paraphrasing a source and including a citation',
      'Copying three paragraphs from a website and pasting them into your essay without attribution',
      'Summarizing a book chapter and citing it in your Works Cited',
    ],
    correctAnswers: [2],
    explanation: 'Copying text without attribution is plagiarism — the most direct form. Options A, B, and D all properly attribute the source, which is what makes them legitimate uses. Citation requirements exist for direct quotes (quotation marks + citation), paraphrases (citation), and summaries (citation). Only common knowledge does not require citation.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Speaking & Listening
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'sl-01',
    domain: 1,
    subdomain: 'Speaking & Listening',
    type: 'single',
    difficulty: 'easy',
    question: 'Which of the following is an example of active listening during a class discussion?',
    options: [
      'Thinking about what you will say next while someone else is talking',
      'Looking at your phone quietly without disrupting',
      'Making eye contact, nodding, and taking notes on key points',
      'Waiting for the speaker to finish so you can disagree',
    ],
    correctAnswers: [2],
    explanation: 'Active listening means fully engaging with the speaker — maintaining eye contact, showing comprehension through body language, and capturing key ideas in notes. Planning your own response while someone speaks is common but counterproductive to actual understanding. Passive listening (waiting to talk, phone use) misses content and signals disrespect.',
  },
  {
    id: 'sl-02',
    domain: 1,
    subdomain: 'Speaking & Listening',
    type: 'single',
    difficulty: 'medium',
    question: 'In a formal presentation, which delivery technique is most important for maintaining audience engagement?',
    options: [
      'Reading directly from notecards word-for-word for accuracy',
      'Maintaining eye contact and varying your pace and volume',
      'Standing perfectly still to appear professional',
      'Using as many slides as possible to cover your topic',
    ],
    correctAnswers: [1],
    explanation: 'Effective speakers vary their pace, volume, and tone to signal importance and maintain interest — a monotone delivery loses audiences quickly. Eye contact creates connection and signals confidence. Reading word-for-word from notecards disengages the audience and signals poor preparation. More slides do not equal better presentations — clarity and focus matter more.',
  },
  {
    id: 'sl-03',
    domain: 1,
    subdomain: 'Speaking & Listening',
    type: 'yesno',
    difficulty: 'easy',
    question: 'True or False: Nonverbal communication — posture, gesture, facial expression — can reinforce or undermine a speaker\'s verbal message.',
    options: ['True', 'False'],
    correctAnswers: [0],
    explanation: 'Nonverbal communication constitutes a significant portion of how messages are received. A speaker saying "I\'m confident about this" while slouching and avoiding eye contact sends a mixed message — the body undermines the words. Strong presenters align their nonverbal signals with their message: upright posture, purposeful gestures, and appropriate facial expressions reinforce credibility.',
  },
  {
    id: 'sl-04',
    domain: 1,
    subdomain: 'Speaking & Listening',
    type: 'single',
    difficulty: 'medium',
    question: 'A Socratic seminar differs from a regular class discussion because it:',
    options: [
      'Has a teacher who provides answers to student questions',
      'Requires students to ask questions and build on each other\'s ideas through open dialogue',
      'Focuses only on facts rather than interpretations',
      'Is a formal debate format with two sides arguing against each other',
    ],
    correctAnswers: [1],
    explanation: 'A Socratic seminar is a student-led discussion based on open-ended questions, where participants build on each other\'s ideas collaboratively rather than competitively. Named after Socrates\' method of questioning, it emphasizes inquiry. The teacher facilitates but does not provide answers. It is not a debate — the goal is shared understanding, not winning.',
  },
  {
    id: 'sl-05',
    domain: 1,
    subdomain: 'Speaking & Listening',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are effective strategies for evaluating a speaker\'s argument during a presentation? Select ALL that apply.',
    options: [
      'Identifying the claim and the evidence used to support it',
      'Evaluating whether the evidence is credible and sufficient',
      'Noting whether the speaker uses emotional appeals that lack factual backing',
      'Judging the argument based primarily on whether you like the speaker',
      'Considering what counterarguments the speaker didn\'t address',
    ],
    correctAnswers: [0, 1, 2, 4],
    explanation: 'Evaluating a speaker\'s argument requires analyzing the claim, evidence quality, rhetorical appeals, and logical gaps. Identifying claims and evidence, checking credibility of sources, spotting emotional manipulation without factual backup, and noting unaddressed counterarguments are all critical evaluation strategies. Judging based on personal liking is an ad hominem bias — irrelevant to argument quality.',
  },
  {
    id: 'sl-06',
    domain: 1,
    subdomain: 'Speaking & Listening',
    type: 'single',
    difficulty: 'easy',
    question: 'A clarifying question in a discussion is designed to:',
    options: [
      'Challenge the speaker\'s viewpoint and propose an alternative',
      'Ensure you have correctly understood the speaker\'s point before responding',
      'Change the subject to something more relevant',
      'Summarize the speaker\'s argument for the rest of the group',
    ],
    correctAnswers: [1],
    explanation: 'A clarifying question ("Did you mean...?", "Can you explain what you meant by...?") seeks to ensure comprehension before engaging further. It\'s a sign of good faith listening. It is distinct from a probing question (pushing deeper into an idea) or a challenging question (questioning the argument\'s validity). Clarifying first prevents responding to a misunderstanding.',
  },
  {
    id: 'sl-07',
    domain: 1,
    subdomain: 'Speaking & Listening',
    type: 'ordering',
    difficulty: 'medium',
    question: 'Place these steps for preparing a formal presentation in the correct logical order.',
    options: [
      'Practice delivery and time the presentation',
      'Identify your central claim and audience',
      'Select and evaluate supporting evidence',
      'Create visual aids (slides)',
      'Organize your points in a logical structure',
    ],
    correctAnswers: [1, 2, 4, 3, 0],
    explanation: 'Effective presentation preparation flows: Identify claim and audience → Select and evaluate evidence → Organize points logically → Create visual aids to support structure → Practice delivery. Visual aids come after structure (they illustrate your argument, not define it), and practice is always last so you can adjust based on how things flow.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Research Writing (continued — rw-10 through rw-14)
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'rw-10',
    domain: 1,
    subdomain: 'Research Writing',
    type: 'single',
    difficulty: 'medium',
    question: 'The CRAAP test is used to evaluate sources. Which of the following does the second "A" in CRAAP stand for?',
    options: ['Accessibility', 'Accuracy', 'Authority', 'Authenticity'],
    correctAnswers: [1],
    explanation: 'CRAAP stands for Currency (how recent), Relevance (does it fit your topic), Authority (who wrote it and what are their credentials), Accuracy (is the information correct and supported by evidence), and Purpose (why was it written — to inform, sell, entertain, persuade?). The second A is Accuracy — checking that claims are verifiable and evidence is cited.',
  },
  {
    id: 'rw-11',
    domain: 1,
    subdomain: 'Research Writing',
    type: 'single',
    difficulty: 'medium',
    question: 'Which of the following best describes a primary source?',
    options: [
      'A textbook chapter that synthesizes multiple studies on a topic',
      'A newspaper editorial commenting on a political event',
      'A soldier\'s diary written during World War II',
      'A documentary film about the Civil Rights Movement',
    ],
    correctAnswers: [2],
    explanation: 'A primary source is a first-hand, original account created at the time of the event or by someone directly involved. A soldier\'s wartime diary is a primary source. Textbooks (secondary), editorials (secondary), and documentaries (secondary) all interpret or analyze original events rather than recording them directly. The distinction matters because primary sources provide raw evidence while secondary sources provide analysis.',
  },
  {
    id: 'rw-12',
    domain: 1,
    subdomain: 'Research Writing',
    type: 'single',
    difficulty: 'hard',
    question: 'In MLA format, how does an in-text citation differ from an APA in-text citation?',
    options: [
      'MLA includes the year of publication; APA does not',
      'MLA uses (Author Page) with no comma; APA uses (Author, Year, p. Page)',
      'MLA uses footnotes; APA uses parenthetical citations',
      'They are identical — both styles use the same in-text format',
    ],
    correctAnswers: [1],
    explanation: 'MLA (used in English/humanities) formats in-text citations as (LastName PageNumber) — no comma, no year, no "p." Example: (Morrison 47). APA (used in social sciences) uses (LastName, Year, p. PageNumber) — with commas and the year. Example: (Morrison, 1987, p. 47). MLA uses footnotes only for content notes, not citations. Knowing the difference matters when your teacher specifies a style.',
  },
  {
    id: 'rw-13',
    domain: 1,
    subdomain: 'Research Writing',
    type: 'yesno',
    difficulty: 'medium',
    question: 'True or False: Synthesis in research writing means presenting sources one at a time in separate paragraphs without connecting them to each other.',
    options: ['True', 'False'],
    correctAnswers: [1],
    explanation: 'Synthesis means weaving multiple sources together around a central idea — not summarizing each source in isolation. A synthesis paragraph integrates what Source A says, how Source B agrees or disagrees, and what the combination reveals. Presenting sources in separate paragraphs without connecting them is a "source dump" — summary, not synthesis. Synthesis requires the writer to do the intellectual work of finding relationships between sources.',
  },
  {
    id: 'rw-14',
    domain: 1,
    subdomain: 'Research Writing',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are effective strategies for avoiding plagiarism? Select ALL that apply.',
    options: [
      'Keeping careful notes about where each idea came from during research',
      'Using quotation marks for any exact words taken from a source',
      'Changing a few words in a passage and not citing it',
      'Citing paraphrased material even though it is in your own words',
      'Using a citation manager to track your sources',
    ],
    correctAnswers: [0, 1, 3, 4],
    explanation: 'Avoiding plagiarism requires tracking sources from the start (notes/citation managers), quoting exactly when using original wording, and citing paraphrases because borrowed ideas require attribution regardless of whose words express them. Changing only a few words in a passage is patchwriting — still plagiarism if uncited, and bad style even when cited. True paraphrase restates the idea completely in your own phrasing AND cites the source.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Language & Conventions (continued — lc-13 through lc-14)
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'lc-13',
    domain: 1,
    subdomain: 'Language & Conventions',
    type: 'single',
    difficulty: 'medium',
    question: 'Which sentence contains a comma splice?',
    options: [
      'She finished the assignment, and she submitted it on time.',
      'She finished the assignment; she submitted it on time.',
      'She finished the assignment, she submitted it on time.',
      'After finishing the assignment, she submitted it on time.',
    ],
    correctAnswers: [2],
    explanation: 'A comma splice joins two independent clauses with only a comma — no coordinating conjunction. "She finished the assignment, she submitted it on time" is a comma splice. Fix it by: (1) adding a coordinating conjunction after the comma (and, but, so), (2) replacing the comma with a semicolon, or (3) making one clause dependent. Options A and B are correctly punctuated; option D converts one clause to a dependent phrase.',
  },
  {
    id: 'lc-14',
    domain: 1,
    subdomain: 'Language & Conventions',
    type: 'single',
    difficulty: 'medium',
    question: 'Which sentence demonstrates faulty parallel structure?',
    options: [
      'The coach advised us to practice daily, to eat well, and to get enough sleep.',
      'She enjoys reading, writing, and hiking on weekends.',
      'He was known for his courage, his honesty, and being generous.',
      'The project required research, drafting, and revision.',
    ],
    correctAnswers: [2],
    explanation: 'Parallel structure requires that items in a series use the same grammatical form. In option C, "his courage" and "his honesty" are noun phrases, but "being generous" is a gerund phrase — the form shifts mid-list. The correct version would be "his courage, his honesty, and his generosity." Options A (infinitive phrases), B (gerunds), and D (nouns) are all internally consistent.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Speaking & Listening (continued — sl-08 through sl-12)
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'sl-08',
    domain: 1,
    subdomain: 'Speaking & Listening',
    type: 'single',
    difficulty: 'easy',
    question: 'During a presentation, a speaker who maintains consistent eye contact with the audience is primarily demonstrating:',
    options: [
      'That they have memorized their script perfectly',
      'Confidence, engagement, and connection with listeners',
      'That they do not need any notes or visual aids',
      'Advanced preparation of their visual slides',
    ],
    correctAnswers: [1],
    explanation: 'Eye contact signals engagement, confidence, and respect for the audience. It creates a connection that reading from a script cannot. Eye contact does not mean the speaker has memorized everything — effective speakers use brief glances at notes while maintaining sustained audience connection. It is a nonverbal communication tool, not evidence of visual aid quality.',
  },
  {
    id: 'sl-09',
    domain: 1,
    subdomain: 'Speaking & Listening',
    type: 'single',
    difficulty: 'medium',
    question: 'Which of the following describes the best use of multimedia (slides, video, audio) in a presentation?',
    options: [
      'Putting all your text on slides so the audience can read along with you',
      'Using multimedia to illustrate and reinforce key points, not to replace your spoken content',
      'Playing a video for most of your presentation time to keep the audience interested',
      'Avoiding multimedia entirely since it distracts from your words',
    ],
    correctAnswers: [1],
    explanation: 'Multimedia is most effective when it supports the spoken word — visual data, images, or brief video clips that reinforce key points. Slides heavy with text compete with the speaker\'s words rather than supporting them (the audience reads instead of listens). Letting video do most of the presenting undermines the speaker\'s role. Multimedia is a tool to strengthen arguments, not replace them.',
  },
  {
    id: 'sl-10',
    domain: 1,
    subdomain: 'Speaking & Listening',
    type: 'single',
    difficulty: 'medium',
    question: 'When giving a peer a verbal critique of their presentation, the most effective approach is to:',
    options: [
      'Focus only on the positives to avoid discouraging them',
      'List every error you noticed so they can correct them all',
      'Identify specific strengths and offer targeted, actionable suggestions for improvement',
      'Compare their presentation to the best one in the class',
    ],
    correctAnswers: [2],
    explanation: 'Effective peer feedback is specific, balanced, and actionable: name what worked and why, then identify a focused area for improvement with a concrete suggestion. "Your eye contact was strong" is more useful than "good job." "Your introduction would be clearer if you stated your main argument in the first 30 seconds" is more useful than "the intro was confusing." Comparing to others is demoralizing and unhelpful.',
  },
  {
    id: 'sl-11',
    domain: 1,
    subdomain: 'Speaking & Listening',
    type: 'yesno',
    difficulty: 'easy',
    question: 'True or False: Speaking at a varied pace — sometimes faster, sometimes slower — is an effective delivery technique for keeping audiences engaged.',
    options: ['True', 'False'],
    correctAnswers: [0],
    explanation: 'Pace variation is one of the most powerful vocal tools a speaker has. Slowing down signals importance and gives the audience time to absorb complex ideas. Speeding up can create energy or urgency. A monotone, consistent pace lulls audiences into inattention. Intentional pauses — especially after key points — are also highly effective: silence draws focus rather than losing it.',
  },
  {
    id: 'sl-12',
    domain: 1,
    subdomain: 'Speaking & Listening',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which behaviors demonstrate good participation in a Socratic seminar? Select ALL that apply.',
    options: [
      'Building on a classmate\'s point by referencing what they said before adding your own idea',
      'Asking an open-ended question that invites further exploration',
      'Dominating the conversation to ensure your ideas are heard',
      'Citing textual evidence when making a claim',
      'Waiting for the teacher to call on you before speaking, even during open discussion',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'Strong Socratic seminar participation is collaborative: building on others\' ideas, posing questions that open rather than close discussion, and grounding claims in evidence are all hallmarks of quality dialogue. Dominating the conversation prevents others from contributing and undermines the collaborative purpose. In Socratic seminars, students are usually expected to self-manage discussion without constantly waiting for teacher prompts — that is part of the format.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Reading Literature (continued — rl-16 through rl-19)
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'rl-16',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'A recurring image, idea, or symbol throughout a literary work that contributes to its themes is called a:',
    options: ['Allegory', 'Motif', 'Archetype', 'Allusion'],
    correctAnswers: [1],
    explanation: 'A motif is a recurring element — image, phrase, situation, or idea — that appears multiple times throughout a work and contributes to its theme. In The Great Gatsby, the green light and eyes of Doctor T. J. Eckleburg are motifs. An archetype is a universal character type or pattern (the hero, the trickster). An allegory is a sustained symbolic narrative. An allusion is a reference to another work.',
  },
  {
    id: 'rl-17',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'hard',
    question: 'Which type of characterization does NOT directly describe a character\'s personality but instead reveals it through behavior, dialogue, or what others say?',
    options: ['Direct characterization', 'Indirect characterization', 'Static characterization', 'Flat characterization'],
    correctAnswers: [1],
    explanation: 'Indirect characterization (STEAL: Speech, Thoughts, Effect on others, Actions, Looks) reveals character through the author\'s craft rather than explicit statements. "She was kind" is direct; showing her return a lost wallet without expecting thanks is indirect. Indirect characterization is generally considered more sophisticated because it invites the reader to draw conclusions. Static/flat describe change and complexity, not the method of characterization.',
  },
  {
    id: 'rl-18',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'Close reading of a literary passage primarily involves:',
    options: [
      'Reading quickly to identify the main idea without stopping at every sentence',
      'Consulting outside sources to learn the historical context of the passage',
      'Analyzing specific word choices, sentence structures, and literary devices to understand meaning',
      'Summarizing the plot events in the passage in order',
    ],
    correctAnswers: [2],
    explanation: 'Close reading is slow, deliberate analysis of a text at the level of word choice, syntax, imagery, and device. The goal is to understand HOW the author creates meaning — not just WHAT happens. It prioritizes the text itself over outside context or summary. Questions in close reading: Why this word and not another? What does this image suggest? How does this sentence structure create emphasis?',
  },
  {
    id: 'rl-19',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are types of figurative language? Select ALL that apply.',
    options: ['Simile', 'Hyperbole', 'Connotation', 'Personification', 'Paradox'],
    correctAnswers: [0, 1, 3, 4],
    explanation: 'Simile (comparison using "like/as"), hyperbole (exaggeration), personification (human traits given to non-human things), and paradox (an apparently contradictory statement that contains a truth) are all types of figurative language — language that means something beyond its literal sense. Connotation is the emotional or cultural association of a word, which is a feature of diction/word choice rather than a figure of speech per se.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Reading Informational Text (continued — ri-11 through ri-15)
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'ri-11',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'easy',
    question: 'An informational text that describes events in the sequence they occurred — first, then, next, finally — uses which text structure?',
    options: ['Cause and effect', 'Chronological order', 'Compare and contrast', 'Problem and solution'],
    correctAnswers: [1],
    explanation: 'Chronological order presents events in time sequence, using signal words like "first," "then," "next," "after," and "finally." It is common in historical accounts, biographies, and how-to articles. Cause-effect explains why something happened and its results. Compare-contrast explores similarities and differences. Problem-solution identifies an issue and argues for remedies.',
  },
  {
    id: 'ri-12',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'medium',
    question: 'When an author of an informational text makes a concession, they are:',
    options: [
      'Dismissing an opposing viewpoint as irrelevant',
      'Acknowledging that the opposing side has a valid point before continuing their own argument',
      'Summarizing the evidence for both sides without taking a position',
      'Ending the essay by restating the thesis',
    ],
    correctAnswers: [1],
    explanation: 'A concession is when the author acknowledges the merit of an opposing argument ("Admittedly, critics are correct that...") before pivoting back to their own position ("however, this does not account for..."). Concessions demonstrate intellectual honesty and actually strengthen an argument by showing the author has considered objections. Dismissing the opposition is not a concession.',
  },
  {
    id: 'ri-13',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'multi',
    difficulty: 'hard',
    question: 'Which of the following are signs of potential bias in an informational source? Select ALL that apply.',
    options: [
      'The source presents only evidence that supports one point of view',
      'The source uses emotionally charged language in a news article',
      'The source was published by a university press',
      'The source omits key facts that would complicate its argument',
      'The source cites peer-reviewed studies',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'Bias indicators include one-sided evidence selection, emotionally charged language in contexts meant to be neutral (like news reporting), and omission of complicating facts. University press publication and citation of peer-reviewed studies are signs of credibility, not bias. Note: all sources have some bias (a perspective), but these specific behaviors signal problematic slanting rather than inevitable subjectivity.',
  },
  {
    id: 'ri-14',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'medium',
    question: 'Which text feature would MOST help a reader quickly locate information about a specific topic within a long informational text?',
    options: ['The bibliography', 'The index', 'The preface', 'The introduction'],
    correctAnswers: [1],
    explanation: 'An index is an alphabetical list at the back of a book that lists topics and the pages where they appear — the fastest way to locate specific information. A bibliography lists sources used but does not point to content within the text. The preface explains the author\'s purpose and background. The introduction sets up the topic broadly. For quick reference to specific content, the index is the correct tool.',
  },
  {
    id: 'ri-15',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'hard',
    question: 'An author\'s tone in an informational text is BEST determined by examining:',
    options: [
      'The length of the paragraphs and how the text is formatted',
      'The author\'s word choice, the evidence selected, and how opposing views are framed',
      'The number of times the author uses first-person pronouns',
      'Whether the text includes charts and photographs',
    ],
    correctAnswers: [1],
    explanation: 'Tone in informational text is revealed through diction (formal vs. informal word choice), selection of evidence (what the author emphasizes), and how opposing views are treated (fairly considered vs. dismissed or caricatured). These choices reflect the author\'s attitude toward the subject and audience. Formatting, pronoun count, and visuals can be clues, but they are surface features compared to the cumulative effect of language choices.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Argument & Rhetoric (continued — ar-12 through ar-15)
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'ar-12',
    domain: 1,
    subdomain: 'Argument & Rhetoric',
    type: 'single',
    difficulty: 'medium',
    question: 'In the rhetorical situation, the "audience" refers to:',
    options: [
      'The general public who might read any piece of writing',
      'The specific group of people the writer is addressing and trying to persuade',
      'Only people who already agree with the writer\'s position',
      'The publisher or editor who approves the text',
    ],
    correctAnswers: [1],
    explanation: 'Audience in rhetoric is the specific group the writer is targeting — their values, beliefs, prior knowledge, and relationship to the topic shape every rhetorical decision. A speech to climate scientists uses different evidence, vocabulary, and appeals than one written for voters who are skeptical of climate policy. Understanding the audience is the foundation of effective rhetoric.',
  },
  {
    id: 'ar-13',
    domain: 1,
    subdomain: 'Argument & Rhetoric',
    type: 'single',
    difficulty: 'hard',
    question: 'A writer argues: "Studies show 95% of scientists agree that humans are driving climate change. If you disagree, you must believe that all these scientists are wrong." This argument is an example of:',
    options: ['Hasty generalization', 'Straw man', 'False dichotomy', 'Appeal to authority'],
    correctAnswers: [2],
    explanation: 'This is a false dichotomy — it presents only two options (you agree, OR you think all scientists are wrong) when nuanced positions exist (you might accept some climate science but dispute specific policy responses, question methodology, or have other views). Presenting a complex debate as a binary choice is a classic false dichotomy. Appeal to authority would use the scientists\' credentials without the false either/or framing.',
  },
  {
    id: 'ar-14',
    domain: 1,
    subdomain: 'Argument & Rhetoric',
    type: 'single',
    difficulty: 'medium',
    question: 'The rhetorical strategy of acknowledging and then refuting an opposing argument is called:',
    options: ['Concession and rebuttal', 'Straw man', 'Circular reasoning', 'Anaphora'],
    correctAnswers: [0],
    explanation: 'Concession and rebuttal is a two-move strategy: first, grant that the opposition has a point ("Admittedly..."), then show why your argument still holds ("Nevertheless..."). This approach demonstrates intellectual honesty and strengthens the overall argument. A straw man misrepresents the opposition\'s argument before attacking it. Circular reasoning restates the conclusion as evidence. Anaphora is a structural sound/rhythm device.',
  },
  {
    id: 'ar-15',
    domain: 1,
    subdomain: 'Argument & Rhetoric',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are components of the rhetorical triangle (Aristotelian appeals)? Select ALL that apply.',
    options: ['Ethos', 'Logos', 'Kairos', 'Pathos', 'Thesis'],
    correctAnswers: [0, 1, 3],
    explanation: 'The three Aristotelian appeals forming the rhetorical triangle are Ethos (credibility/character), Logos (logic/evidence), and Pathos (emotion). These three must work together: all ethos and no logos is authority without substance; all logos and no pathos may fail to move the audience; all pathos and no logos is manipulation. Kairos (timeliness) and Thesis are important rhetorical concepts but are not part of the three-appeal triangle.',
  },

  // ── Additional Reading Literature ──────────────────────────────────
  {
    id: 'rl-20',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'In a story, a character\'s internal monologue reveals that she fears abandonment but outwardly acts aloof and dismissive. This gap between interior thought and exterior behavior is best described as:',
    options: ['Situational irony', 'Dramatic irony', 'Character foil', 'Psychological realism'],
    correctAnswers: [3],
    explanation: 'Psychological realism depicts the inner life of characters — their fears, contradictions, desires, and rationalizations — so that external behavior flows logically from internal psychology. The gap between the character\'s inner fear and outer aloofness is precisely what psychological realism explores. Situational irony is a gap between expectation and outcome. Dramatic irony occurs when the audience knows something characters don\'t. A foil is a contrasting character.',
  },
  {
    id: 'rl-21',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'hard',
    question: 'A short story opens with: "The morning light crept through the blinds like fingers searching for something lost." This description establishes:',
    options: ['A tone of optimism about the new day', 'A mood of unease and searching through personification and simile', 'A theme of nature vs. technology', 'A flashback to the narrator\'s childhood'],
    correctAnswers: [1],
    explanation: 'The image combines a simile ("like fingers") with personification (light that "crept" and was "searching for something lost") to create an unsettled, searching mood. The verb "crept" suggests stealth and unease; "something lost" introduces a note of absence and longing before the story has even begun. This is a deliberate mood-setting opener. There is no established optimism, nature-vs.-technology theme, or flashback here.',
  },
  {
    id: 'rl-22',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'A character who exists primarily to highlight the qualities of the protagonist by contrast is called a:',
    options: ['Narrator', 'Foil', 'Antagonist', 'Stock character'],
    correctAnswers: [1],
    explanation: 'A foil is a character whose contrasting traits emphasize or illuminate the protagonist\'s qualities. Laertes in Hamlet is a classic foil — his impulsive decisiveness contrasts with Hamlet\'s deliberate hesitation, throwing each trait into sharper relief. An antagonist opposes the protagonist but need not be a foil. A narrator tells the story. A stock character is a type or cliché (the bumbling sidekick, the wise old mentor) rather than a deliberate contrast.',
  },
  {
    id: 'rl-23',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'hard',
    question: 'The author of a short story places a gun on the mantelpiece in Chapter 1. By the end of the story, the gun has not been used. This violates the principle known as:',
    options: ['In medias res', 'Chekhov\'s Gun', 'Rising action', 'The unreliable narrator convention'],
    correctAnswers: [1],
    explanation: 'Chekhov\'s Gun is the narrative principle — named after Anton Chekhov — that every element introduced in a story should be relevant; if a gun appears in Act 1, it must be fired before the story ends. Including a gun that never fires violates this economy-of-narrative principle because it creates an expectation in the reader that goes unfulfilled. In medias res is starting a story in the middle of action. Rising action is the buildup of tension toward the climax.',
  },
  {
    id: 'rl-24',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are elements of an extended metaphor? Select ALL that apply.',
    options: ['It continues the same comparison across multiple lines, stanzas, or paragraphs', 'It uses "like" or "as" to signal the comparison', 'It develops the comparison with increasing detail and complexity', 'It can appear in both poetry and prose'],
    correctAnswers: [0, 2, 3],
    explanation: 'An extended metaphor sustains and develops a single comparison throughout a longer passage or work, adding layers of meaning with each new detail. It appears in both poetry and prose. However, an extended metaphor does NOT use "like" or "as" — that would make it a simile (or extended simile). A metaphor states the identification directly ("Life is a journey") rather than comparing with explicit comparison words.',
  },

  // ── Additional Language & Conventions ────────────────────────────
  {
    id: 'lc-15',
    domain: 1,
    subdomain: 'Language & Conventions',
    type: 'single',
    difficulty: 'medium',
    question: 'Which sentence uses the subjunctive mood correctly?',
    options: [
      'If I was president, I would change the law.',
      'If I were president, I would change the law.',
      'If I am president, I would change the law.',
      'If I be president, I would change the law.',
    ],
    correctAnswers: [1],
    explanation: 'The subjunctive mood is used for hypothetical, contrary-to-fact, or wishful conditions. In these constructions, use "were" (not "was") for all subjects — "If I were," "If she were," "If he were." The construction "If I was" uses indicative mood and is incorrect in formal contexts when the condition is contrary to fact. "If I am" is indicative and suggests a real possibility, not a hypothetical. "If I be" is an archaic subjunctive form not used in modern standard English.',
  },
  {
    id: 'lc-16',
    domain: 1,
    subdomain: 'Language & Conventions',
    type: 'single',
    difficulty: 'medium',
    question: 'Identify the error in the following sentence: "Between you and I, the project is already behind schedule."',
    options: [
      'No error — "between you and I" is standard formal English',
      '"Between you and I" should be "between you and me" — "I" is a subject pronoun, not an object pronoun',
      '"behind schedule" should be hyphenated: "behind-schedule"',
      'The sentence should use "among" rather than "between" for more than two things',
    ],
    correctAnswers: [1],
    explanation: '"Between you and I" is a hypercorrection — many speakers use "I" because it sounds formal, but it is grammatically wrong. The preposition "between" governs its objects and requires object pronouns: "me," not "I." The correct form is "between you and me." A test: remove the other person — "between I" sounds immediately wrong; "between me" sounds right. This error is called hypercorrection because it overcorrects in the wrong direction.',
  },
  {
    id: 'lc-17',
    domain: 1,
    subdomain: 'Language & Conventions',
    type: 'single',
    difficulty: 'hard',
    question: 'A student writes: "The committee have reached their decision." A teacher marks it wrong. Which explanation best defends the student\'s original sentence?',
    options: [
      'The student is wrong; "committee" is always singular in English',
      'In British English, collective nouns like "committee" can take plural verbs when the members are acting as individuals; the student may be applying British convention',
      'The student is wrong; the correct pronoun after "committee" is always "its," not "their"',
      'Collective nouns never take plural verbs under any circumstances',
    ],
    correctAnswers: [1],
    explanation: 'Collective nouns (committee, team, jury, faculty) are handled differently in American and British English. In American English, collective nouns are treated as singular: "The committee has reached its decision." In British English, collective nouns can be plural when members act individually: "The committee have reached their decision." The student\'s sentence follows British convention. The teacher\'s correction reflects American usage. Neither is inherently "wrong" — they represent different dialect conventions.',
  },
  {
    id: 'lc-18',
    domain: 1,
    subdomain: 'Language & Conventions',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following sentences contain a dangling modifier? Select ALL that apply.',
    options: [
      'Running through the rain, my shoes got soaked.',
      'Running through the rain, I soaked my shoes.',
      'After reviewing the data, the report was finalized.',
      'After reviewing the data, the team finalized the report.',
    ],
    correctAnswers: [0, 2],
    explanation: 'A dangling modifier occurs when the implied subject of the modifying phrase does not match the grammatical subject of the main clause. In option A, "Running through the rain" implies a person running, but the main clause subject is "my shoes" — shoes cannot run. In option C, "After reviewing the data" implies a person reviewing, but "the report" cannot review data. Options B and D are correct: "I" (who ran) and "the team" (who reviewed) are the logical actors of the modifying phrases.',
  },

  // ── Additional Research Writing ───────────────────────────────────
  {
    id: 'rw-15',
    domain: 1,
    subdomain: 'Research Writing',
    type: 'single',
    difficulty: 'medium',
    question: 'A student uses three sentences from a source article, reorganizes them into new sentences, and presents the content without a citation. This is an example of:',
    options: ['Effective paraphrasing', 'Plagiarism — the content and ideas are not the student\'s own even though words changed', 'Correct summarizing — changing words removes the need to cite', 'Academic dishonesty only if the original words are kept'],
    correctAnswers: [1],
    explanation: 'Plagiarism includes presenting someone else\'s IDEAS without attribution, not just their exact words. Reorganizing sentences while keeping the original ideas, structure, and content without citation is still plagiarism. The standard is: if the idea, argument, data, or unique phrasing came from a source, cite it — regardless of how thoroughly you changed the surface wording. Proper paraphrasing changes the structure AND gives credit to the original.',
  },
  {
    id: 'rw-16',
    domain: 1,
    subdomain: 'Research Writing',
    type: 'single',
    difficulty: 'hard',
    question: 'Which of the following is the MOST reliable source for a research paper on the effectiveness of a new medication?',
    options: [
      'A blog post by a doctor sharing personal opinions about the medication',
      'A peer-reviewed article in a medical journal reporting results of a controlled clinical trial',
      'A pharmaceutical company\'s website promoting the medication',
      'A news article summarizing the medication\'s recent FDA approval',
    ],
    correctAnswers: [1],
    explanation: 'A peer-reviewed article in a medical journal is the gold standard. Peer review means other qualified scientists reviewed and scrutinized the methodology before publication. A controlled clinical trial provides empirical data with measurable outcomes. A doctor\'s blog is opinion without peer accountability. A pharmaceutical company\'s website has a financial conflict of interest. A news article summarizing the approval provides secondary information filtered through non-specialist journalists and lacks methodological detail.',
  },
];

