// Question bank for USHC — U.S. History and the Constitution. Targets the
// SC End-of-Course Examination Program (EOCEP) for 11th-grade U.S. History.

export type QuestionType = 'single' | 'multi' | 'ordering' | 'yesno' | 'match' | 'hot-area' | 'case-study';

export interface Question {
  id: string;
  domain: 1;            // single domain — the EOCEP is one combined exam
  subdomain: string;
  type: QuestionType;
  difficulty: 'easy' | 'medium' | 'hard';
  question: string;
  options: string[];
  correctAnswers: number[];
  explanation: string;
  codeSnippet?: string;
  examTip?: string;
  match?: { leftItems: string[]; rightItems: string[]; correctPairs: [number, number][] };
  hotArea?: { svg: string; targets: { id: string; label: string }[]; correctTargetIds: string[]; selectAll?: boolean };
  caseStudy?: { scenario: string; subQuestions: { question: string; options: string[]; type: 'single' | 'multi'; correctAnswers: number[] }[] };
}

export const questions: Question[] = [
  // ══════════════════════════════════════════════════════════════════
  // Foundations & Constitution
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'found-01',
    domain: 1,
    subdomain: 'Foundations & Constitution',
    type: 'single',
    difficulty: 'easy',
    question: 'Which weakness of the Articles of Confederation was most directly exposed by Shays\' Rebellion (1786–87)?',
    options: [
      'The federal government could not raise an army or enforce order across state lines',
      'States were forbidden to issue their own currencies',
      'The president had veto power that Congress could not override',
      'Trade with Britain was completely prohibited',
    ],
    correctAnswers: [0],
    explanation: 'Under the Articles, the federal government had no standing army and no power to compel state militias. Massachusetts had to put down Shays\' Rebellion entirely on its own — a vivid demonstration that a stronger central government was needed. This crisis was a direct trigger for the Constitutional Convention in 1787.',
  },
  {
    id: 'found-02',
    domain: 1,
    subdomain: 'Foundations & Constitution',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are checks the legislative branch holds over the executive?',
    options: [
      'Override a presidential veto with a two-thirds vote',
      'Confirm or reject presidential appointments to the Supreme Court',
      'Declare laws unconstitutional',
      'Ratify or reject treaties',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'Congress can override vetoes (2/3 of both houses), the Senate confirms appointments and ratifies treaties — all checks on the executive. Declaring laws unconstitutional is judicial review, exercised by the Supreme Court, not Congress. This is the kind of distinction the EOCEP loves to test.',
  },
  {
    id: 'found-03',
    domain: 1,
    subdomain: 'Foundations & Constitution',
    type: 'single',
    difficulty: 'medium',
    question: 'In Marbury v. Madison (1803), Chief Justice John Marshall established which power for the Supreme Court?',
    options: [
      'The power to impeach a sitting president',
      'The power of judicial review — to declare federal laws unconstitutional',
      'The power to write laws',
      'The power to ratify constitutional amendments',
    ],
    correctAnswers: [1],
    explanation: 'Marbury v. Madison is the foundational case establishing judicial review. Marshall ruled that a section of the Judiciary Act of 1789 was unconstitutional, asserting the Court\'s authority to strike down acts of Congress. This is the source of the Court\'s modern constitutional power.',
  },
  {
    id: 'found-04',
    domain: 1,
    subdomain: 'Foundations & Constitution',
    type: 'single',
    difficulty: 'hard',
    question: 'The Three-Fifths Compromise primarily affected which aspect of the early federal government?',
    options: [
      'The conduct of foreign policy',
      'Representation in the House of Representatives and direct taxation',
      'Eligibility for the Supreme Court',
      'Voting rights for free Black men',
    ],
    correctAnswers: [1],
    explanation: 'The Three-Fifths Compromise counted enslaved persons as 3/5 of a person for both apportionment of House seats and direct taxes. This inflated Southern representation in Congress and the Electoral College until the 13th Amendment ended slavery in 1865.',
  },
  {
    id: 'found-05',
    domain: 1,
    subdomain: 'Foundations & Constitution',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Does the Bill of Rights apply only to the federal government as originally written?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Originally yes — the Bill of Rights (1791) restricted only the federal government. Only after the 14th Amendment (1868) and a long series of Supreme Court "incorporation" cases through the 20th century did its protections apply to state and local governments.',
  },
  {
    id: 'found-06',
    domain: 1,
    subdomain: 'Foundations & Constitution',
    type: 'ordering',
    difficulty: 'medium',
    question: 'Arrange the following founding documents in chronological order from earliest to latest.',
    options: [
      'Declaration of Independence',
      'Articles of Confederation (ratified)',
      'U.S. Constitution (ratified)',
      'Bill of Rights (ratified)',
    ],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'Declaration of Independence (1776) → Articles of Confederation ratified (1781) → Constitution ratified (1788) → Bill of Rights ratified (1791). The Constitution replaced the Articles after their weaknesses became undeniable; the Bill of Rights was added to satisfy anti-Federalist concerns about federal overreach.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Reconstruction
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'recon-01',
    domain: 1,
    subdomain: 'Reconstruction',
    type: 'single',
    difficulty: 'easy',
    question: 'Which amendment formally abolished slavery in the United States?',
    options: ['12th Amendment', '13th Amendment', '14th Amendment', '15th Amendment'],
    correctAnswers: [1],
    explanation: 'The 13th Amendment (ratified December 1865) abolished slavery and involuntary servitude, except as punishment for a crime. It was the first of the three Reconstruction Amendments (13/14/15) that fundamentally reshaped federal law on race and citizenship.',
  },
  {
    id: 'recon-02',
    domain: 1,
    subdomain: 'Reconstruction',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following did the 14th Amendment establish?',
    options: [
      'Birthright citizenship for anyone born in the United States',
      'Equal protection of the laws',
      'The right to vote regardless of race',
      'Due process protections against state governments',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'The 14th Amendment (1868) established birthright citizenship, equal protection, and due process AGAINST STATE actions (a huge expansion). The right to vote regardless of race is the 15th Amendment (1870). The Equal Protection Clause is the most-litigated phrase in the entire Constitution.',
  },
  {
    id: 'recon-03',
    domain: 1,
    subdomain: 'Reconstruction',
    type: 'single',
    difficulty: 'medium',
    question: 'What was the practical effect of the Compromise of 1877?',
    options: [
      'It restored slavery in the South',
      'It ended Reconstruction and withdrew federal troops from the South',
      'It expanded the Freedmen\'s Bureau nationwide',
      'It guaranteed Black voting rights for the next century',
    ],
    correctAnswers: [1],
    explanation: 'In exchange for Rutherford B. Hayes winning the disputed 1876 election, Republicans agreed to withdraw federal troops from the South. Without federal enforcement, Southern states quickly began constructing the Jim Crow legal system that would persist for nearly a century.',
  },
  {
    id: 'recon-04',
    domain: 1,
    subdomain: 'Reconstruction',
    type: 'single',
    difficulty: 'medium',
    question: 'The Supreme Court ruling in Plessy v. Ferguson (1896) established which doctrine?',
    options: [
      'One person, one vote',
      '"Separate but equal" — segregation is constitutional if facilities are notionally equal',
      'Judicial review',
      'States cannot secede from the Union',
    ],
    correctAnswers: [1],
    explanation: 'Plessy v. Ferguson upheld a Louisiana law segregating railroad cars and articulated the "separate but equal" doctrine that justified Jim Crow for 58 years. It was overturned by Brown v. Board of Education in 1954.',
  },
  {
    id: 'recon-05',
    domain: 1,
    subdomain: 'Reconstruction',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Did the 15th Amendment grant women the right to vote?',
    options: ['Yes', 'No'],
    correctAnswers: [1],
    explanation: 'No — the 15th Amendment (1870) banned voting discrimination based on "race, color, or previous condition of servitude" but explicitly left out sex. Women would not get the vote nationally until the 19th Amendment in 1920, a full 50 years later.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Industrialization & Gilded Age
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'ind-01',
    domain: 1,
    subdomain: 'Industrialization & Gilded Age',
    type: 'single',
    difficulty: 'easy',
    question: 'Which industrialist built Standard Oil into a near-monopoly through horizontal integration?',
    options: ['Andrew Carnegie', 'John D. Rockefeller', 'Cornelius Vanderbilt', 'J.P. Morgan'],
    correctAnswers: [1],
    explanation: 'John D. Rockefeller built Standard Oil into a horizontal monopoly — buying or crushing competitors at the same level of production (refining). At its peak Standard Oil controlled about 90% of U.S. oil refining. Theodore Roosevelt later used the Sherman Antitrust Act to break it up.',
  },
  {
    id: 'ind-02',
    domain: 1,
    subdomain: 'Industrialization & Gilded Age',
    type: 'single',
    difficulty: 'medium',
    question: 'Andrew Carnegie\'s Steel empire used "vertical integration." What does that mean?',
    options: [
      'Buying up competitors making the same product',
      'Controlling every stage of production from raw material to finished good and distribution',
      'Vertical price-fixing across distributors',
      'Producing goods at multiple altitudes',
    ],
    correctAnswers: [1],
    explanation: 'Vertical integration means controlling every step of a supply chain: Carnegie owned the iron mines, the coal mines, the railroads carrying the ore, the steel mills, and the ships carrying the finished steel. Each stage protected the others from middleman markups.',
  },
  {
    id: 'ind-03',
    domain: 1,
    subdomain: 'Industrialization & Gilded Age',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following were major labor union actions during the Gilded Age?',
    options: [
      'The Haymarket Affair (1886)',
      'The Pullman Strike (1894)',
      'The Triangle Shirtwaist Factory fire response (1911)',
      'The Stamp Act protests',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Haymarket, the Pullman Strike, and the Triangle Shirtwaist fire response were all key labor and reform moments. The Stamp Act protests were from the 1760s — colonial era, not Gilded Age. The Gilded Age and Progressive Era are the formative period for U.S. labor law.',
  },
  {
    id: 'ind-04',
    domain: 1,
    subdomain: 'Industrialization & Gilded Age',
    type: 'single',
    difficulty: 'hard',
    question: 'The Sherman Antitrust Act (1890) was ironically used most aggressively against which group in its first decade?',
    options: [
      'Standard Oil',
      'The transcontinental railroads',
      'Labor unions',
      'Tobacco trusts',
    ],
    correctAnswers: [2],
    explanation: 'Despite being aimed at trusts, the Sherman Act was initially used to prosecute labor unions (whose strikes were ruled an illegal "restraint of trade"). Only with Theodore Roosevelt\'s trust-busting in the early 1900s did it begin to be wielded against actual monopolies.',
  },
  {
    id: 'ind-05',
    domain: 1,
    subdomain: 'Industrialization & Gilded Age',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Did the transcontinental railroad rely on Chinese immigrant labor for much of its construction?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. The Central Pacific Railroad (building eastward from Sacramento) hired thousands of Chinese workers for the dangerous Sierra Nevada section. By 1869, when the railroad was completed at Promontory, Utah, roughly 90% of CP\'s workforce was Chinese.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Progressive Era
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'prog-01',
    domain: 1,
    subdomain: 'Progressive Era',
    type: 'single',
    difficulty: 'easy',
    question: 'Upton Sinclair\'s novel The Jungle (1906) most directly led to which federal legislation?',
    options: [
      'The Sherman Antitrust Act',
      'The Pure Food and Drug Act and the Meat Inspection Act',
      'The Federal Reserve Act',
      'The Clayton Antitrust Act',
    ],
    correctAnswers: [1],
    explanation: 'The Jungle exposed sickening conditions in Chicago meatpacking plants. Public outrage drove Theodore Roosevelt to push through both the Pure Food and Drug Act and the Meat Inspection Act in 1906 — landmarks in federal consumer protection.',
  },
  {
    id: 'prog-02',
    domain: 1,
    subdomain: 'Progressive Era',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of these constitutional amendments were ratified during the Progressive Era (roughly 1900–1920)?',
    options: [
      '16th Amendment (federal income tax)',
      '17th Amendment (direct election of senators)',
      '18th Amendment (Prohibition)',
      '19th Amendment (women\'s suffrage)',
    ],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'All four — 16th and 17th in 1913, 18th in 1919, 19th in 1920 — are Progressive Era amendments. Together they represent the most concentrated burst of constitutional reform between Reconstruction and the Civil Rights era.',
  },
  {
    id: 'prog-03',
    domain: 1,
    subdomain: 'Progressive Era',
    type: 'single',
    difficulty: 'medium',
    question: 'Which progressive era amendment was later repealed?',
    options: [
      '16th — federal income tax',
      '17th — direct election of senators',
      '18th — Prohibition',
      '19th — women\'s suffrage',
    ],
    correctAnswers: [2],
    explanation: 'The 18th Amendment (Prohibition, 1919) is the only amendment ever repealed — undone by the 21st Amendment in 1933. Prohibition failed in practice, fueling organized crime and proving unenforceable. The 16th, 17th, and 19th all remain in force.',
  },
  {
    id: 'prog-04',
    domain: 1,
    subdomain: 'Progressive Era',
    type: 'single',
    difficulty: 'easy',
    question: 'Which president is most associated with "trust-busting" and the Square Deal?',
    options: ['William McKinley', 'Theodore Roosevelt', 'William Howard Taft', 'Woodrow Wilson'],
    correctAnswers: [1],
    explanation: 'Theodore Roosevelt (president 1901–1909) made trust-busting and the "Square Deal" his signature domestic agenda. He successfully broke up the Northern Securities Company and pursued Standard Oil. Taft actually busted MORE trusts but never matched TR\'s public identity with the issue.',
  },
  {
    id: 'prog-05',
    domain: 1,
    subdomain: 'Progressive Era',
    type: 'yesno',
    difficulty: 'medium',
    question: 'Did the 17th Amendment change how U.S. senators are chosen?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. Before 1913, senators were chosen by state legislatures (per Article I of the original Constitution). The 17th Amendment moved that to direct popular election. It was a Progressive response to widespread corruption in state legislative selection of senators.',
  },

  // ══════════════════════════════════════════════════════════════════
  // World War I & 1920s
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'wwi-01',
    domain: 1,
    subdomain: 'World War I & 1920s',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which events directly contributed to U.S. entry into World War I in 1917?',
    options: [
      'German unrestricted submarine warfare',
      'The sinking of the Lusitania',
      'The Zimmermann Telegram',
      'The Japanese attack on Pearl Harbor',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Submarine warfare, the Lusitania (1915, 128 Americans killed), and the Zimmermann Telegram (Germany offered Mexico the U.S. Southwest if it joined the Central Powers) drove the U.S. to declare war in April 1917. Pearl Harbor was December 1941 — that\'s WWII.',
  },
  {
    id: 'wwi-02',
    domain: 1,
    subdomain: 'World War I & 1920s',
    type: 'single',
    difficulty: 'medium',
    question: 'Why did the United States not join the League of Nations after WWI?',
    options: [
      'Wilson refused to sign the Treaty of Versailles',
      'The U.S. Senate rejected the Treaty of Versailles',
      'France vetoed U.S. membership',
      'The League dissolved before the U.S. could join',
    ],
    correctAnswers: [1],
    explanation: 'The Senate, led by Henry Cabot Lodge, rejected the Treaty of Versailles — and with it, U.S. membership in the League of Nations. Senators feared the League would commit the U.S. to European conflicts. Without American participation, the League proved unable to prevent WWII.',
  },
  {
    id: '20s-01',
    domain: 1,
    subdomain: 'World War I & 1920s',
    type: 'single',
    difficulty: 'easy',
    question: 'The Harlem Renaissance of the 1920s is best described as:',
    options: [
      'A real estate boom in New York',
      'A flowering of Black art, literature, and music centered in Harlem',
      'The construction of Harlem\'s subway system',
      'A series of race riots in northern cities',
    ],
    correctAnswers: [1],
    explanation: 'The Harlem Renaissance was the explosion of African American art, writing, music, and intellectual life in Harlem during the 1920s. Key figures include Langston Hughes, Zora Neale Hurston, Duke Ellington, and Louis Armstrong. It was the first time Black culture reached mainstream American audiences in such depth.',
  },
  {
    id: '20s-02',
    domain: 1,
    subdomain: 'World War I & 1920s',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Was the Red Scare of 1919–20 driven mostly by fears of communist/anarchist revolution?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. The Bolshevik Revolution in Russia (1917) and a wave of anarchist bombings in the U.S. fueled the First Red Scare. Attorney General A. Mitchell Palmer led raids that deported hundreds of suspected radicals. The pattern repeated more famously during the McCarthy era in the 1950s.',
  },
  {
    id: '20s-03',
    domain: 1,
    subdomain: 'World War I & 1920s',
    type: 'single',
    difficulty: 'medium',
    question: 'The Scopes "Monkey" Trial (1925) centered on which question?',
    options: [
      'Whether public schools could ban evolution in their biology curriculum',
      'Whether women could serve on juries',
      'Whether Black students could attend white schools',
      'Whether labor unions could legally strike',
    ],
    correctAnswers: [0],
    explanation: 'Tennessee teacher John Scopes was tried for violating a state law against teaching evolution. The trial became a national symbol of the urban/rural and modernist/fundamentalist culture clashes of the 1920s. Scopes lost technically but the law later quietly faded.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Great Depression & New Deal
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'dep-01',
    domain: 1,
    subdomain: 'Great Depression & New Deal',
    type: 'single',
    difficulty: 'easy',
    question: 'What event in October 1929 is generally identified as the start of the Great Depression?',
    options: [
      'The Stock Market Crash (Black Tuesday)',
      'Pearl Harbor',
      'The Dust Bowl beginning',
      'FDR\'s inauguration',
    ],
    correctAnswers: [0],
    explanation: 'Black Tuesday (October 29, 1929) saw the Dow Jones lose 12% in a single day. The crash itself didn\'t cause the Depression — underlying weaknesses in banking, agriculture, and overproduction did — but it triggered the cascade of bank failures and unemployment that followed.',
  },
  {
    id: 'dep-02',
    domain: 1,
    subdomain: 'Great Depression & New Deal',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are New Deal programs? (Select all that apply)',
    options: [
      'Civilian Conservation Corps (CCC)',
      'Works Progress Administration (WPA)',
      'Social Security Administration',
      'The G.I. Bill',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'CCC (1933), WPA (1935), and Social Security (1935) are all New Deal programs. The G.I. Bill (1944) came LATER, under FDR but during WWII — it\'s a wartime/postwar program, not a Depression-era one. Distinguishing these timelines is a common EOCEP trap.',
  },
  {
    id: 'dep-03',
    domain: 1,
    subdomain: 'Great Depression & New Deal',
    type: 'single',
    difficulty: 'medium',
    question: 'Which New Deal agency still operates today and is generally considered the most enduring legacy of the era?',
    options: [
      'The Civilian Conservation Corps',
      'The National Recovery Administration',
      'The Social Security Administration',
      'The Works Progress Administration',
    ],
    correctAnswers: [2],
    explanation: 'Social Security (1935) remains a foundational federal program — retirement pensions and unemployment insurance funded by payroll taxes. The CCC and WPA ended during WWII; the NRA was struck down by the Supreme Court in 1935. Social Security endures because it created a politically untouchable constituency: every retired worker.',
  },
  {
    id: 'dep-04',
    domain: 1,
    subdomain: 'Great Depression & New Deal',
    type: 'single',
    difficulty: 'hard',
    question: 'FDR\'s "court-packing" plan of 1937 was a response to which problem?',
    options: [
      'Republicans winning back the Senate',
      'The Supreme Court striking down major New Deal programs as unconstitutional',
      'A budget shortfall in Social Security',
      'Pressure to enter World War II',
    ],
    correctAnswers: [1],
    explanation: 'A conservative Supreme Court struck down key New Deal programs (NRA, AAA) in 1935–36. FDR proposed adding up to 6 new justices, claiming the Court was overworked. The plan failed politically — but the Court began ruling more favorably anyway (the "switch in time that saved nine").',
  },
  {
    id: 'dep-05',
    domain: 1,
    subdomain: 'Great Depression & New Deal',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Did the Dust Bowl of the 1930s drive large numbers of farmers from the Great Plains to California?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. Severe drought and decades of poor tilling practices stripped topsoil from Oklahoma, Texas, Kansas, and surrounding states. Hundreds of thousands of "Okies" migrated west, especially to California — a movement captured in Steinbeck\'s The Grapes of Wrath.',
  },
  {
    id: 'dep-06',
    domain: 1,
    subdomain: 'Great Depression & New Deal',
    type: 'ordering',
    difficulty: 'medium',
    question: 'Place these events of the Depression/New Deal era in chronological order.',
    options: [
      'Stock Market Crash (Black Tuesday)',
      'FDR\'s first inauguration',
      'Social Security Act passed',
      'FDR\'s court-packing plan',
    ],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'Stock Market Crash (October 1929) → FDR\'s inauguration (March 1933) → Social Security Act (August 1935) → court-packing plan (February 1937). The years 1929–1937 cover the descent into Depression and the most aggressive phase of New Deal reform.',
  },

  // ══════════════════════════════════════════════════════════════════
  // World War II
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'wwii-01',
    domain: 1,
    subdomain: 'World War II',
    type: 'single',
    difficulty: 'easy',
    question: 'What event directly brought the United States into WWII?',
    options: [
      'The German invasion of Poland',
      'The Japanese attack on Pearl Harbor',
      'The Battle of Britain',
      'The Lend-Lease Act',
    ],
    correctAnswers: [1],
    explanation: 'The Japanese attack on Pearl Harbor (December 7, 1941) killed 2,403 Americans and sank or damaged eight battleships. The U.S. declared war on Japan the next day. Germany and Italy declared war on the U.S. three days later, drawing America into both Pacific and European theaters.',
  },
  {
    id: 'wwii-02',
    domain: 1,
    subdomain: 'World War II',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following were home-front developments in the U.S. during WWII?',
    options: [
      'Women entering factory work in record numbers ("Rosie the Riveter")',
      'Forced internment of Japanese Americans',
      'Rationing of food and gasoline',
      'The repeal of Prohibition',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Women in factories, Japanese internment (Executive Order 9066), and rationing were all WWII home-front realities. Prohibition was repealed in 1933 — a decade earlier — by the 21st Amendment. Watch for chronology traps where era-mixing is the wrong answer.',
  },
  {
    id: 'wwii-03',
    domain: 1,
    subdomain: 'World War II',
    type: 'single',
    difficulty: 'medium',
    question: 'D-Day (June 6, 1944) was significant because it:',
    options: [
      'Ended the war in the Pacific',
      'Opened the Western Front against Nazi Germany via amphibious invasion of Normandy',
      'Was the first use of atomic weapons',
      'Brought the U.S. into the war',
    ],
    correctAnswers: [1],
    explanation: 'D-Day was the Allied amphibious invasion of Nazi-occupied France at Normandy — the largest seaborne assault in history. It opened the Western Front and began the rollback that ended in Germany\'s surrender 11 months later. Pacific war ended in August 1945.',
  },
  {
    id: 'wwii-04',
    domain: 1,
    subdomain: 'World War II',
    type: 'single',
    difficulty: 'hard',
    question: 'The Manhattan Project produced what?',
    options: [
      'Radar capable of detecting German U-boats',
      'The first atomic bomb',
      'A new generation of long-range bombers',
      'The Enigma machine for decrypting Japanese codes',
    ],
    correctAnswers: [1],
    explanation: 'The Manhattan Project (1942–45), led by physicist Robert Oppenheimer at Los Alamos, developed the first atomic bombs. Bombs were dropped on Hiroshima (August 6, 1945) and Nagasaki (August 9). Japan surrendered on September 2, ending WWII.',
  },
  {
    id: 'wwii-05',
    domain: 1,
    subdomain: 'World War II',
    type: 'yesno',
    difficulty: 'medium',
    question: 'Did the Korematsu v. United States (1944) decision uphold the constitutionality of Japanese-American internment?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. The Supreme Court ruled 6–3 that internment was a legitimate wartime security measure. Korematsu is now widely considered one of the worst Supreme Court decisions ever and was effectively repudiated in Trump v. Hawaii (2018). Civil liberties under wartime pressure is a recurring EOCEP theme.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Cold War & Containment
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'cw-01',
    domain: 1,
    subdomain: 'Cold War & Containment',
    type: 'single',
    difficulty: 'easy',
    question: 'The Truman Doctrine (1947) committed the U.S. to what policy?',
    options: [
      'Disarming after WWII',
      'Containing the spread of communism by supporting nations resisting Soviet pressure',
      'Joining the United Nations',
      'Returning to isolationism',
    ],
    correctAnswers: [1],
    explanation: 'The Truman Doctrine made containment of communism the central organizing principle of U.S. foreign policy for the next four decades. First applied to Greece and Turkey, it justified involvement in Korea, Vietnam, and dozens of smaller conflicts.',
  },
  {
    id: 'cw-02',
    domain: 1,
    subdomain: 'Cold War & Containment',
    type: 'single',
    difficulty: 'medium',
    question: 'The Marshall Plan provided primarily what?',
    options: [
      'Military equipment for NATO',
      'Economic aid to rebuild Western Europe after WWII',
      'A nuclear umbrella for Asia',
      'Food aid to the Soviet Union',
    ],
    correctAnswers: [1],
    explanation: 'The Marshall Plan (1948–52) sent about $13 billion in aid to rebuild Western Europe. The strategy combined humanitarian goals with containment: stable democracies were less vulnerable to communist movements. It worked — Western Europe boomed.',
  },
  {
    id: 'cw-03',
    domain: 1,
    subdomain: 'Cold War & Containment',
    type: 'single',
    difficulty: 'medium',
    question: 'The Cuban Missile Crisis (October 1962) is widely considered:',
    options: [
      'The end of the Cold War',
      'The closest the world has come to nuclear war',
      'The beginning of the Vietnam War',
      'A successful U.S. invasion of Cuba',
    ],
    correctAnswers: [1],
    explanation: 'During 13 tense days in October 1962, the U.S. blockaded Cuba after discovering Soviet nuclear missiles there. Kennedy and Khrushchev resolved it: the USSR removed missiles in exchange for U.S. removal of missiles from Turkey. Closest the Cold War came to going hot.',
  },
  {
    id: 'cw-04',
    domain: 1,
    subdomain: 'Cold War & Containment',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following were direct Cold War proxy conflicts involving U.S. forces?',
    options: [
      'The Korean War (1950–53)',
      'The Vietnam War (1955–75)',
      'The Bay of Pigs invasion (1961)',
      'The Revolutionary War',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Korea, Vietnam, and Bay of Pigs were all Cold War conflicts where the U.S. fought communist or Soviet-aligned forces. The Revolutionary War was 1775–83 — colonial era, no relation to the Cold War.',
  },
  {
    id: 'cw-05',
    domain: 1,
    subdomain: 'Cold War & Containment',
    type: 'single',
    difficulty: 'hard',
    question: 'Senator Joseph McCarthy is best remembered for what?',
    options: [
      'Leading the integration of Little Rock schools',
      'Sensationalist accusations of communist infiltration of the U.S. government in the early 1950s',
      'Negotiating the Cuban Missile Crisis',
      'Drafting the Civil Rights Act of 1964',
    ],
    correctAnswers: [1],
    explanation: 'Wisconsin senator Joseph McCarthy held high-profile hearings (1950–54) claiming widespread communist infiltration of the State Department, the army, and Hollywood. He destroyed many careers with little evidence; the Senate censured him in December 1954. "McCarthyism" entered the language as a synonym for unfounded accusation.',
  },
  {
    id: 'cw-06',
    domain: 1,
    subdomain: 'Cold War & Containment',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Was the U.S. response to Sputnik (1957) a major increase in math and science education funding?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. The Soviet launch of Sputnik (the first artificial satellite) panicked U.S. policymakers. Congress responded with the National Defense Education Act (1958), pouring federal money into science, math, and engineering education to close what was perceived as a "missile gap."',
  },

  // ══════════════════════════════════════════════════════════════════
  // Civil Rights Movement
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'cr-01',
    domain: 1,
    subdomain: 'Civil Rights Movement',
    type: 'single',
    difficulty: 'easy',
    question: 'Brown v. Board of Education (1954) overturned which earlier Supreme Court decision?',
    options: [
      'Marbury v. Madison',
      'Dred Scott v. Sandford',
      'Plessy v. Ferguson',
      'Korematsu v. United States',
    ],
    correctAnswers: [2],
    explanation: 'Brown overturned Plessy v. Ferguson\'s "separate but equal" doctrine. The unanimous Warren Court ruling declared segregated public schools "inherently unequal" and unconstitutional under the 14th Amendment. It launched the modern Civil Rights era.',
  },
  {
    id: 'cr-02',
    domain: 1,
    subdomain: 'Civil Rights Movement',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are key Civil Rights Movement events from the 1950s–60s?',
    options: [
      'Montgomery Bus Boycott (1955–56)',
      'March on Washington (1963)',
      'Selma to Montgomery marches (1965)',
      'The Stonewall riots (1969)',
    ],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'All four were transformative civil rights moments. Montgomery, the March on Washington, and Selma were core African American civil rights events; Stonewall in 1969 marked the start of the modern LGBTQ rights movement. Movements often inspire and learn from each other.',
  },
  {
    id: 'cr-03',
    domain: 1,
    subdomain: 'Civil Rights Movement',
    type: 'single',
    difficulty: 'medium',
    question: 'The Civil Rights Act of 1964 banned discrimination in:',
    options: [
      'Only federal employment',
      'Employment, public accommodations, and federally-funded programs',
      'Voting only',
      'Religious institutions only',
    ],
    correctAnswers: [1],
    explanation: 'The 1964 Act was unusually broad: it banned discrimination based on race, color, religion, sex, or national origin in EMPLOYMENT, PUBLIC ACCOMMODATIONS (hotels, restaurants, theaters), and ANY federally-funded program. Title VII (employment) and Title II (public accommodations) are the most-litigated sections.',
  },
  {
    id: 'cr-04',
    domain: 1,
    subdomain: 'Civil Rights Movement',
    type: 'single',
    difficulty: 'medium',
    question: 'Why was the Voting Rights Act of 1965 needed if the 15th Amendment had been ratified in 1870?',
    options: [
      'The 15th Amendment had been repealed',
      'Southern states had used literacy tests, poll taxes, and intimidation to disenfranchise Black voters for decades',
      'New states were joining the Union and needed new rules',
      'The 15th Amendment never actually mentioned voting',
    ],
    correctAnswers: [1],
    explanation: 'After Reconstruction ended in 1877, Southern states erected a maze of barriers — literacy tests, poll taxes, "grandfather clauses," white primaries, and outright violence — to disenfranchise Black voters. The 1965 Act banned these practices and authorized federal election oversight in jurisdictions with histories of discrimination.',
  },
  {
    id: 'cr-05',
    domain: 1,
    subdomain: 'Civil Rights Movement',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Did the Montgomery Bus Boycott use economic pressure rather than legal action as its primary strategy?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. After Rosa Parks\' arrest, Black residents (about 75% of bus riders) refused to ride for 381 days, devastating the transit system financially. A parallel federal lawsuit (Browder v. Gayle) eventually outlawed bus segregation, but the economic boycott was the visible engine of the movement.',
  },
  {
    id: 'cr-06',
    domain: 1,
    subdomain: 'Civil Rights Movement',
    type: 'ordering',
    difficulty: 'hard',
    question: 'Order these Civil Rights events from earliest to latest.',
    options: [
      'Brown v. Board of Education decision',
      'Montgomery Bus Boycott begins',
      'March on Washington',
      'Voting Rights Act signed',
    ],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'Brown v. Board (May 1954) → Montgomery Bus Boycott (Dec 1955) → March on Washington (Aug 1963) → Voting Rights Act (Aug 1965). The arc spans 11 years from the landmark ruling to the legislative culmination of the movement\'s nonviolent-direct-action phase.',
  },

  // ══════════════════════════════════════════════════════════════════
  // EXPANSION — 60+ additional questions to reach EOCEP-track depth.
  // Same nine subdomains; questions vary by difficulty and type.
  // ══════════════════════════════════════════════════════════════════

  // ─── Foundations & Constitution ──────────────────────────────────
  {
    id: 'found-07',
    domain: 1,
    subdomain: 'Foundations & Constitution',
    type: 'single',
    difficulty: 'easy',
    question: 'Which document begins with "We the People"?',
    options: ['The Declaration of Independence', 'The U.S. Constitution', 'The Magna Carta', 'The Articles of Confederation'],
    correctAnswers: [1],
    explanation: 'The Preamble to the U.S. Constitution opens with "We the People of the United States…" — a deliberate framing that locates governmental authority in the citizens themselves, not in a king or in the states. The Declaration of Independence (1776) begins "When in the Course of human events…"',
  },
  {
    id: 'found-08',
    domain: 1,
    subdomain: 'Foundations & Constitution',
    type: 'single',
    difficulty: 'medium',
    question: 'Which clause in Article I gives Congress broad power to pass laws beyond those specifically enumerated?',
    options: ['The Establishment Clause', 'The Necessary and Proper Clause', 'The Supremacy Clause', 'The Equal Protection Clause'],
    correctAnswers: [1],
    explanation: 'The Necessary and Proper Clause (Article I, Section 8) — also called the Elastic Clause — lets Congress pass any law "necessary and proper" to execute its enumerated powers. McCulloch v. Maryland (1819) used it to uphold the national bank. It is the main constitutional basis for the modern federal government\'s scope.',
  },
  {
    id: 'found-09',
    domain: 1,
    subdomain: 'Foundations & Constitution',
    type: 'single',
    difficulty: 'medium',
    question: 'The Supremacy Clause establishes that:',
    options: [
      'The President is supreme over Congress',
      'Federal law (when constitutional) overrides conflicting state law',
      'The Supreme Court is supreme over both Congress and the President',
      'States have supremacy over the federal government in domestic matters',
    ],
    correctAnswers: [1],
    explanation: 'Article VI\'s Supremacy Clause makes the Constitution, federal laws, and federal treaties the "supreme Law of the Land." When state law conflicts with valid federal law, the federal law wins. The clause was crucial in McCulloch v. Maryland (1819) and Cooper v. Aaron (1958, school desegregation).',
  },
  {
    id: 'found-10',
    domain: 1,
    subdomain: 'Foundations & Constitution',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are reserved (not delegated) powers belonging to the states under the 10th Amendment?',
    options: [
      'Regulating intrastate commerce within their own borders',
      'Conducting elections (including federal elections)',
      'Declaring war on foreign countries',
      'Establishing public schools and licensing professionals',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'Reserved powers stay with the states because the Constitution did not delegate them to the federal government. Intrastate commerce, election administration, education, and professional licensing are all classic state functions. Declaring war is exclusively a federal power (Article I, Section 8), so it is NOT reserved.',
  },
  {
    id: 'found-11',
    domain: 1,
    subdomain: 'Foundations & Constitution',
    type: 'single',
    difficulty: 'medium',
    question: 'The Federalist Papers were written primarily to:',
    options: [
      'Oppose ratification of the Constitution',
      'Persuade New York and other states to ratify the Constitution',
      'Replace the Articles of Confederation with a king',
      'Argue against the Bill of Rights',
    ],
    correctAnswers: [1],
    explanation: 'Alexander Hamilton, James Madison, and John Jay wrote the 85 Federalist essays (1787–88) under the pen name "Publius" to persuade New York voters to ratify the Constitution. They remain foundational sources for original-intent constitutional interpretation. Federalist 10 (Madison) on factions and Federalist 51 (Madison) on checks and balances are the most cited.',
  },
  {
    id: 'found-12',
    domain: 1,
    subdomain: 'Foundations & Constitution',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Does the U.S. Constitution explicitly require the Supreme Court to have nine justices?',
    options: ['Yes', 'No'],
    correctAnswers: [1],
    explanation: 'No — the Constitution leaves the size of the Court to Congress. The number has changed several times (6 initially in 1789, peaked at 10 in 1863, fixed at 9 by the Judiciary Act of 1869). FDR\'s 1937 court-packing plan would have added up to 6 more — politically defeated, but constitutionally permissible.',
  },

  // ─── Reconstruction ──────────────────────────────────────────────
  {
    id: 'recon-06',
    domain: 1,
    subdomain: 'Reconstruction',
    type: 'single',
    difficulty: 'easy',
    question: 'Which president was impeached during Reconstruction?',
    options: ['Abraham Lincoln', 'Andrew Johnson', 'Ulysses S. Grant', 'Rutherford B. Hayes'],
    correctAnswers: [1],
    explanation: 'Andrew Johnson, Lincoln\'s vice president who became president after Lincoln\'s assassination, was impeached by the House in 1868 for violating the Tenure of Office Act by firing Secretary of War Edwin Stanton. He survived removal in the Senate by ONE vote. The clash was really about Johnson\'s lenient approach to Reconstruction.',
  },
  {
    id: 'recon-07',
    domain: 1,
    subdomain: 'Reconstruction',
    type: 'single',
    difficulty: 'medium',
    question: 'The Civil Rights Act of 1866 was significant primarily because it:',
    options: [
      'Banned segregation in public accommodations nationwide',
      'Declared all persons born in the U.S. (except untaxed Native Americans) to be citizens, regardless of race',
      'Created the Bureau of Indian Affairs',
      'Established the modern income tax',
    ],
    correctAnswers: [1],
    explanation: 'The Civil Rights Act of 1866 was the first federal law to define citizenship and affirm equal rights regardless of race. Johnson vetoed it; Congress overrode the veto — the first time Congress ever overrode a presidential veto on major legislation. Its principles were soon constitutionalized in the 14th Amendment to put them beyond future legislative repeal.',
  },
  {
    id: 'recon-08',
    domain: 1,
    subdomain: 'Reconstruction',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following methods were used by Southern states to disenfranchise Black voters after Reconstruction?',
    options: [
      'Literacy tests with subjectively-graded answers',
      'Poll taxes that poor freedmen could not afford',
      'Grandfather clauses exempting whites whose ancestors had voted before the Civil War',
      'White-only primary elections',
    ],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'All four were used. Southern states constructed an interlocking system: literacy tests (graded harshly for Black applicants, leniently for whites), poll taxes (effectively disenfranchising poor freedmen), grandfather clauses (a workaround to keep poor whites enfranchised while filtering out Black voters), and white-only primaries (Democratic primary was the only meaningful election in much of the one-party South). The 1965 Voting Rights Act finally dismantled the system.',
  },
  {
    id: 'recon-09',
    domain: 1,
    subdomain: 'Reconstruction',
    type: 'single',
    difficulty: 'medium',
    question: 'What was sharecropping?',
    options: [
      'A federal program providing 40 acres and a mule to freedmen',
      'A labor system in which freedmen and poor whites farmed landowners\' land in exchange for a share of the crop — often trapping them in cycles of debt',
      'A union of agricultural workers founded by Booker T. Washington',
      'A type of cooperative banking in the post-war South',
    ],
    correctAnswers: [1],
    explanation: 'Sharecropping replaced slavery as the dominant Southern labor system after the Civil War. Tenants farmed a landowner\'s land in exchange for a portion of the harvest, but they had to buy seeds, tools, and supplies on credit from the landowner\'s store at inflated prices. Most ended each year in deeper debt than they started — a system designed to keep freedmen tied to the land in conditions resembling the slavery they had just left.',
  },
  {
    id: 'recon-10',
    domain: 1,
    subdomain: 'Reconstruction',
    type: 'ordering',
    difficulty: 'medium',
    question: 'Put these events in chronological order from earliest to latest.',
    options: [
      'Lincoln assassinated; Andrew Johnson becomes president',
      '14th Amendment ratified',
      '15th Amendment ratified',
      'Compromise of 1877 ends Reconstruction',
    ],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'Lincoln assassinated April 14, 1865 → 14th Amendment ratified July 1868 → 15th Amendment ratified February 1870 → Compromise of 1877 (March 1877). The roughly 12 years from Lincoln\'s death to the end of Reconstruction set the trajectory of American race relations for nearly a century.',
  },
  {
    id: 'recon-11',
    domain: 1,
    subdomain: 'Reconstruction',
    type: 'yesno',
    difficulty: 'medium',
    question: 'Did formerly enslaved men actually vote and hold office during Reconstruction?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes — during Reconstruction (especially 1867–77), Black men voted in large numbers and held offices at every level. 14 Black men served in the U.S. House and 2 in the Senate (Hiram Revels and Blanche Bruce of Mississippi). Black officials served as state legislators, lieutenant governors, and local sheriffs. After the Compromise of 1877 ended federal enforcement, these gains were systematically reversed.',
  },

  // ─── Industrialization & Gilded Age ──────────────────────────────
  {
    id: 'ind-06',
    domain: 1,
    subdomain: 'Industrialization & Gilded Age',
    type: 'single',
    difficulty: 'medium',
    question: 'The Bessemer process revolutionized which industry?',
    options: ['Oil refining', 'Steel production', 'Railroad construction', 'Telegraph communication'],
    correctAnswers: [1],
    explanation: 'The Bessemer process (1850s) blew air through molten pig iron to burn off impurities, producing steel cheaply and at scale. Andrew Carnegie adopted it in his Pittsburgh mills. Cheap steel transformed railroads (steel rails replaced iron), construction (steel-frame skyscrapers), and shipbuilding. Steel production became the single best indicator of industrial power.',
  },
  {
    id: 'ind-07',
    domain: 1,
    subdomain: 'Industrialization & Gilded Age',
    type: 'single',
    difficulty: 'medium',
    question: 'The "Gospel of Wealth," published in 1889 by Andrew Carnegie, argued that:',
    options: [
      'Wealth should be redistributed through progressive taxation',
      'The wealthy have a moral obligation to use their fortunes for the public good (philanthropy)',
      'Wealth is a sign of religious salvation',
      'Wealthy industrialists should never be regulated',
    ],
    correctAnswers: [1],
    explanation: 'Carnegie\'s "Gospel of Wealth" argued that the rich are stewards who should distribute their wealth for the public benefit during their lifetimes, not pass it to heirs. Carnegie lived this — he funded 2,500+ public libraries, Carnegie Hall, the Carnegie Institute, and gave away over $350 million (~$11 billion today) before his death. The essay defined modern philanthropy.',
  },
  {
    id: 'ind-08',
    domain: 1,
    subdomain: 'Industrialization & Gilded Age',
    type: 'single',
    difficulty: 'easy',
    question: 'Ellis Island and Angel Island were major immigrant entry points for which two coasts respectively?',
    options: [
      'Both East Coast',
      'East Coast (Ellis) and West Coast (Angel)',
      'West Coast (Ellis) and East Coast (Angel)',
      'Gulf Coast (Ellis) and West Coast (Angel)',
    ],
    correctAnswers: [1],
    explanation: 'Ellis Island in New York Harbor (1892–1954) processed about 12 million immigrants — overwhelmingly Europeans (Italians, Eastern Europeans, Jews fleeing pogroms). Angel Island in San Francisco Bay (1910–40) processed about 1 million, mostly Asian immigrants. The two islands\' experiences diverged sharply — Ellis emphasized rapid processing, while Angel Island detained Chinese immigrants for weeks or months under the Chinese Exclusion Act (1882, the first federal law restricting immigration by nationality).',
  },
  {
    id: 'ind-09',
    domain: 1,
    subdomain: 'Industrialization & Gilded Age',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following were Gilded Age labor unions?',
    options: [
      'Knights of Labor',
      'American Federation of Labor (AFL)',
      'Industrial Workers of the World (IWW)',
      'United Farm Workers',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Knights of Labor (peaked ~1886, declined after Haymarket), AFL (founded 1886 by Samuel Gompers, focused on skilled workers and bread-and-butter wage issues), and IWW ("Wobblies," 1905, radical and inclusive) were all major Gilded Age / Progressive Era unions. The United Farm Workers was founded much later (1962, Cesar Chavez and Dolores Huerta) — a 20th-century civil rights / labor movement.',
  },
  {
    id: 'ind-10',
    domain: 1,
    subdomain: 'Industrialization & Gilded Age',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Did the federal government regulate working hours, wages, or workplace safety during most of the Gilded Age (1870–1900)?',
    options: ['Yes', 'No'],
    correctAnswers: [1],
    explanation: 'No — federal regulation of labor was almost nonexistent in the Gilded Age. Courts struck down state efforts to limit work hours (Lochner v. New York, 1905, invalidated a 10-hour bakery law). Federal labor regulation did not arrive in serious form until the Progressive Era (e.g., the 1916 Adamson Act for railroad workers) and especially the New Deal (Fair Labor Standards Act, 1938 — minimum wage, 40-hour week, child labor restrictions).',
  },
  {
    id: 'ind-11',
    domain: 1,
    subdomain: 'Industrialization & Gilded Age',
    type: 'single',
    difficulty: 'hard',
    question: 'The Interstate Commerce Act (1887) was significant because it:',
    options: [
      'Banned interstate commerce entirely',
      'Created the first federal regulatory agency, the Interstate Commerce Commission (ICC), to oversee railroads',
      'Established the federal income tax',
      'Created the Federal Reserve System',
    ],
    correctAnswers: [1],
    explanation: 'The Interstate Commerce Act created the ICC to regulate railroad rates and prevent monopolistic abuses (rebates to favored shippers, price discrimination). It was the first federal regulatory agency — the prototype for the alphabet soup of later agencies (FDA, FTC, SEC, FCC). Initially weak, the ICC was strengthened by later laws (Hepburn Act 1906 under Theodore Roosevelt).',
  },

  // ─── Progressive Era ─────────────────────────────────────────────
  {
    id: 'prog-06',
    domain: 1,
    subdomain: 'Progressive Era',
    type: 'single',
    difficulty: 'easy',
    question: 'Jane Addams is best known for:',
    options: [
      'Leading the women\'s suffrage movement',
      'Founding Hull House, a Chicago settlement house for immigrants',
      'Inventing the assembly line',
      'Discovering radium',
    ],
    correctAnswers: [1],
    explanation: 'Jane Addams co-founded Hull House in Chicago in 1889 — a "settlement house" providing services (childcare, English classes, healthcare, cultural programs) to working-class immigrants. The settlement house movement helped professionalize social work. Addams won the Nobel Peace Prize in 1931, the first American woman to do so.',
  },
  {
    id: 'prog-07',
    domain: 1,
    subdomain: 'Progressive Era',
    type: 'single',
    difficulty: 'medium',
    question: 'Theodore Roosevelt\'s "Big Stick" diplomacy is summarized by his quote:',
    options: [
      '"Ask not what your country can do for you…"',
      '"Speak softly, and carry a big stick; you will go far."',
      '"The buck stops here."',
      '"Tear down this wall!"',
    ],
    correctAnswers: [1],
    explanation: 'TR\'s "Speak softly, and carry a big stick" captured his foreign-policy approach: project credible military power (the Great White Fleet, expanded Navy) while preferring negotiation. Examples include the Roosevelt Corollary to the Monroe Doctrine, the Panama Canal project (1903–14), and mediating the Russo-Japanese War (1905, winning him a Nobel Peace Prize).',
  },
  {
    id: 'prog-08',
    domain: 1,
    subdomain: 'Progressive Era',
    type: 'single',
    difficulty: 'medium',
    question: 'The Triangle Shirtwaist Factory fire (1911) led primarily to:',
    options: [
      'A constitutional amendment banning child labor',
      'A wave of workplace safety regulations and labor reforms in New York and beyond',
      'The closure of all garment factories nationwide',
      'The election of Woodrow Wilson',
    ],
    correctAnswers: [1],
    explanation: '146 garment workers — mostly young immigrant women — died at the Triangle Shirtwaist Factory in Manhattan when a fire broke out and locked exits prevented escape. The tragedy provoked enormous public outrage. New York passed dozens of workplace safety laws, and the disaster became a touchstone for the labor movement. Frances Perkins, who witnessed the fire, later became FDR\'s Secretary of Labor — the first woman in a cabinet.',
  },
  {
    id: 'prog-09',
    domain: 1,
    subdomain: 'Progressive Era',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following were goals of the Progressive movement?',
    options: [
      'Curbing the power of trusts and monopolies',
      'Expanding democratic participation (direct election of senators, initiative and referendum)',
      'Eliminating the federal government entirely',
      'Improving working conditions and food safety',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'Progressives wanted to restrain corporate power (trust-busting), expand democracy (17th Amendment, women\'s suffrage, primary elections), and protect workers and consumers (food/drug laws, workplace safety, child labor restrictions). They wanted to REFORM the federal government, not eliminate it — in fact, Progressives substantially EXPANDED federal regulatory power.',
  },
  {
    id: 'prog-10',
    domain: 1,
    subdomain: 'Progressive Era',
    type: 'single',
    difficulty: 'hard',
    question: 'The 1912 election was significant because it featured:',
    options: [
      'The first female presidential candidate',
      'Four major candidates including former president Theodore Roosevelt running on the Progressive (Bull Moose) Party ticket, splitting the Republican vote',
      'The first president to be impeached',
      'A tie in the Electoral College that the House had to decide',
    ],
    correctAnswers: [1],
    explanation: 'In 1912, Theodore Roosevelt broke from the Republican Party (after losing the nomination to incumbent William Howard Taft) and ran on the Progressive Party ticket. The four-way race included Wilson (Democrat), Taft (Republican), Roosevelt (Progressive), and Eugene V. Debs (Socialist, who won ~6% of the vote — the highest percentage ever for a socialist candidate). Wilson won with 42% of the popular vote because Taft and Roosevelt split the Republican vote.',
  },
  {
    id: 'prog-11',
    domain: 1,
    subdomain: 'Progressive Era',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Did the Progressive Era include both Republican and Democratic presidents?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes — Progressivism was a bipartisan reform movement. Theodore Roosevelt (Republican, 1901–09) and William Howard Taft (Republican, 1909–13) led trust-busting and conservation. Woodrow Wilson (Democrat, 1913–21) pushed the Federal Reserve, Clayton Antitrust Act, FTC, and constitutional amendments. The shared goal — taming Gilded Age excesses — cut across party lines.',
  },

  // ─── World War I & 1920s ─────────────────────────────────────────
  {
    id: 'wwi-03',
    domain: 1,
    subdomain: 'World War I & 1920s',
    type: 'single',
    difficulty: 'medium',
    question: 'The Selective Service Act of 1917 did what?',
    options: [
      'Established the U.S. Air Force',
      'Created the draft to raise an army for WWI',
      'Granted citizenship to immigrants who served in the military',
      'Allowed women to vote in federal elections',
    ],
    correctAnswers: [1],
    explanation: 'The Selective Service Act (May 1917) required men aged 21–30 (later 18–45) to register for the draft. About 2.8 million men were drafted during WWI, joining the 2 million volunteers. The system has been reused (with modifications) for WWII, Korea, and Vietnam. The draft was suspended in 1973; men 18–25 still register today but no one has been drafted since.',
  },
  {
    id: 'wwi-04',
    domain: 1,
    subdomain: 'World War I & 1920s',
    type: 'single',
    difficulty: 'medium',
    question: 'The Espionage Act (1917) and Sedition Act (1918) were used to:',
    options: [
      'Convict German spies operating in the U.S.',
      'Suppress anti-war speech, including prosecuting socialist Eugene V. Debs for an anti-war speech',
      'Establish modern intelligence agencies',
      'Permit unlimited campaign donations',
    ],
    correctAnswers: [1],
    explanation: 'The Espionage and Sedition Acts criminalized speech and writing that interfered with the war effort. They were used most famously against anti-war socialist Eugene Debs (sentenced to 10 years for a 1918 speech criticizing the draft — he ran for president from prison in 1920 and got 919,000 votes). Schenck v. United States (1919) upheld convictions, with Justice Holmes coining the "clear and present danger" test.',
  },
  {
    id: 'wwi-05',
    domain: 1,
    subdomain: 'World War I & 1920s',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following changes happened during the Great Migration (roughly 1916–1970)?',
    options: [
      'Six million African Americans moved from the rural South to Northern, Midwestern, and Western cities',
      'Black communities in Chicago, Detroit, Harlem, and other Northern cities grew dramatically',
      'African Americans gained access to industrial wartime jobs in the North',
      'Federal law forced the migration',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'The Great Migration was a voluntary movement of about 6 million Black Americans escaping Jim Crow, rural poverty, and racial violence. They were pulled by industrial jobs in Chicago, Detroit, Cleveland, Pittsburgh, and New York — especially during WWI and WWII when European immigration was cut off and labor demand spiked. It was not federally compelled — it was a grassroots demographic shift that reshaped American politics, music, and culture.',
  },
  {
    id: 'wwi-06',
    domain: 1,
    subdomain: 'World War I & 1920s',
    type: 'single',
    difficulty: 'hard',
    question: 'The "return to normalcy" was the slogan of which 1920 presidential winner?',
    options: ['Calvin Coolidge', 'Warren G. Harding', 'Herbert Hoover', 'Charles Evans Hughes'],
    correctAnswers: [1],
    explanation: 'Warren G. Harding\'s 1920 campaign slogan "Return to Normalcy" promised relief from war, progressive reform, and international entanglements. He won in a landslide. His administration was marred by scandal (Teapot Dome — Secretary of the Interior Albert Fall convicted of bribery for leasing federal oil reserves to private companies). Harding died in office in 1923; Coolidge succeeded him.',
  },
  {
    id: '20s-04',
    domain: 1,
    subdomain: 'World War I & 1920s',
    type: 'yesno',
    difficulty: 'medium',
    question: 'Did the 1920s see a dramatic rise in immigration restrictions through national-origin quotas?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes — the Immigration Act of 1924 (National Origins Act) imposed strict quotas based on the 1890 census, heavily favoring Northern and Western European immigrants while severely restricting Southern Europeans (Italians), Eastern Europeans (Jews, Poles), and ALMOST ALL ASIANS (the act effectively excluded Japanese immigration after the Gentlemen\'s Agreement era). The quota system stayed largely intact until the Immigration and Nationality Act of 1965 finally replaced it with a system favoring family reunification and skilled labor.',
  },
  {
    id: '20s-05',
    domain: 1,
    subdomain: 'World War I & 1920s',
    type: 'single',
    difficulty: 'medium',
    question: 'The KKK\'s second peak (membership around 4–5 million) in the 1920s targeted:',
    options: [
      'Only African Americans',
      'African Americans, Catholics, Jews, immigrants, and labor unions',
      'Native Americans exclusively',
      'Only members of organized crime',
    ],
    correctAnswers: [1],
    explanation: 'The 1920s Klan, revived by William J. Simmons in 1915 and inspired by the film "The Birth of a Nation," was more broadly nativist than the original Reconstruction-era KKK. It targeted Black Americans, Catholics, Jews, immigrants from "non-Anglo-Saxon" countries, and what it considered "modern" influences (jazz, alcohol, urban culture). It had millions of members in the North as well as the South and substantial political influence in Indiana, Oregon, and Colorado.',
  },

  // ─── Great Depression & New Deal ─────────────────────────────────
  {
    id: 'dep-07',
    domain: 1,
    subdomain: 'Great Depression & New Deal',
    type: 'single',
    difficulty: 'easy',
    question: 'Who was President when the stock market crashed in October 1929?',
    options: ['Calvin Coolidge', 'Herbert Hoover', 'Franklin D. Roosevelt', 'Woodrow Wilson'],
    correctAnswers: [1],
    explanation: 'Herbert Hoover (Republican, 1929–33) had just been inaugurated in March 1929. His federal response was widely seen as too slow and too small. By 1932, unemployment was 25%, banks were failing, and "Hoovervilles" (shantytowns) dotted the country. Hoover lost the 1932 election to FDR in a landslide. His name became a byword for failed Depression policy.',
  },
  {
    id: 'dep-08',
    domain: 1,
    subdomain: 'Great Depression & New Deal',
    type: 'single',
    difficulty: 'medium',
    question: 'The Tennessee Valley Authority (TVA) was created to:',
    options: [
      'Subsidize the Tennessee tobacco industry',
      'Build dams to provide flood control, electricity, and economic development in the impoverished Tennessee River Valley',
      'Manage U.S. relations with Tennessee under federal occupation',
      'Conduct nuclear research in Oak Ridge',
    ],
    correctAnswers: [1],
    explanation: 'The TVA (1933) was an ambitious federal experiment in regional economic development — building dams along the Tennessee River for hydroelectricity, flood control, and improved navigation in a region of widespread poverty. It electrified rural areas and modernized the Valley\'s economy. Despite ideological objections (it competed directly with private utilities), it survived and still operates today. Oak Ridge would later become part of the Manhattan Project — a separate program leveraging TVA-supplied electricity.',
  },
  {
    id: 'dep-09',
    domain: 1,
    subdomain: 'Great Depression & New Deal',
    type: 'single',
    difficulty: 'medium',
    question: 'Which of the following best describes the Civilian Conservation Corps (CCC)?',
    options: [
      'A federal jobs program that put young unmarried men to work on conservation projects (planting trees, building park infrastructure, fighting fires)',
      'A program that paid farmers to leave fields fallow',
      'A regulator of the New York Stock Exchange',
      'A relief program providing cash payments to senior citizens',
    ],
    correctAnswers: [0],
    explanation: 'The CCC (1933–42) employed about 3 million young men ages 17–25 in conservation work in national forests and parks. CCC workers planted 3 billion trees, built park infrastructure still visible today, and fought wildfires. Workers earned $30/month — most of which they had to send home. The CCC ended in 1942 as WWII absorbed available manpower into military service.',
  },
  {
    id: 'dep-10',
    domain: 1,
    subdomain: 'Great Depression & New Deal',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are TRUE about the Social Security Act of 1935?',
    options: [
      'It created old-age pensions funded by payroll taxes',
      'It established federal unemployment insurance (in partnership with states)',
      'It provided Aid to Dependent Children',
      'It originally excluded agricultural workers and domestic workers, who were disproportionately African American',
    ],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'All four are correct. SSA originally excluded agricultural and domestic workers — a concession to Southern Democrats — which excluded roughly two-thirds of Black workers in the South from the program for its first decades. Coverage expanded gradually, particularly in 1950, 1954, and 1956 amendments. The Act fundamentally restructured American social policy by establishing the federal government as a guarantor of economic security.',
  },
  {
    id: 'dep-11',
    domain: 1,
    subdomain: 'Great Depression & New Deal',
    type: 'single',
    difficulty: 'hard',
    question: 'Which agency, created by the Glass-Steagall Act of 1933, still exists and protects bank depositors today?',
    options: [
      'The Securities and Exchange Commission (SEC)',
      'The Federal Deposit Insurance Corporation (FDIC)',
      'The Federal Reserve',
      'The National Recovery Administration (NRA)',
    ],
    correctAnswers: [1],
    explanation: 'The FDIC insures bank deposits (currently up to $250,000 per depositor per insured bank) — a New Deal innovation that ended the bank-run cycle that had devastated the early Depression. The SEC was also created in the New Deal (1934) but to regulate stock markets. The Federal Reserve existed earlier (1913). The NRA was struck down by the Supreme Court in 1935.',
  },
  {
    id: 'dep-12',
    domain: 1,
    subdomain: 'Great Depression & New Deal',
    type: 'yesno',
    difficulty: 'medium',
    question: 'Did the New Deal end the Great Depression?',
    options: ['Yes', 'No'],
    correctAnswers: [1],
    explanation: 'No — the New Deal substantially relieved suffering and reformed the financial system, but unemployment stayed high (14% as late as 1940). The Depression ended only when WWII mobilization (1941–45) finally absorbed the surplus labor. By 1944, unemployment was below 2%. Historians debate why the New Deal didn\'t fully recover the economy — too cautious in early years, the 1937 "Roosevelt Recession" from premature tightening — but the consensus is wartime spending finished what New Deal spending began.',
  },

  // ─── World War II ────────────────────────────────────────────────
  {
    id: 'wwii-06',
    domain: 1,
    subdomain: 'World War II',
    type: 'single',
    difficulty: 'easy',
    question: 'Which two countries did the U.S. fight in the Pacific theater of WWII?',
    options: [
      'Japan and the Soviet Union',
      'Japan, primarily, with some action against minor Axis-aligned states',
      'China and North Korea',
      'Germany and Italy',
    ],
    correctAnswers: [1],
    explanation: 'The Pacific Theater was primarily a U.S.-Japan war (with British, Australian, Chinese, and Dutch Allied forces also engaged). Japan attacked Pearl Harbor and seized vast Pacific territory; the U.S. responded with an island-hopping campaign across the Pacific, culminating in the atomic bombs. The Soviet Union joined the war against Japan only at the very end (August 8, 1945 — between Hiroshima and Nagasaki).',
  },
  {
    id: 'wwii-07',
    domain: 1,
    subdomain: 'World War II',
    type: 'single',
    difficulty: 'medium',
    question: 'Operation Overlord, the largest amphibious assault in history, refers to:',
    options: [
      'The Battle of Midway',
      'The D-Day invasion of Normandy on June 6, 1944',
      'The bombing of Pearl Harbor',
      'The atomic bombing of Hiroshima',
    ],
    correctAnswers: [1],
    explanation: 'Operation Overlord was the Allied invasion of Nazi-occupied France. About 156,000 Allied troops landed on five Normandy beaches (codenamed Utah, Omaha, Gold, Juno, and Sword) on June 6, 1944, supported by 7,000 ships and 11,000 aircraft. About 4,400 Allied troops died on D-Day itself. The invasion opened the Western Front and began the rollback of the Third Reich.',
  },
  {
    id: 'wwii-08',
    domain: 1,
    subdomain: 'World War II',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following describe American home-front mobilization in WWII?',
    options: [
      'Women entered factory work in unprecedented numbers (about 6 million during the war)',
      'War Production Board oversight redirected industrial output to military goods',
      'Rationing of food, gasoline, rubber, and metals',
      'Universal opposition to the war among the public',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'The home front was deeply mobilized. "Rosie the Riveter" entered the workforce in record numbers (though most were pushed out after the war). The War Production Board converted civilian factories to military production (Ford built bombers, GM built tanks). Rationing managed scarce resources. Public support for WWII was unusually high — unlike WWI\'s mixed reception or Vietnam\'s later opposition, WWII enjoyed broad consensus after Pearl Harbor.',
  },
  {
    id: 'wwii-09',
    domain: 1,
    subdomain: 'World War II',
    type: 'single',
    difficulty: 'medium',
    question: 'The Holocaust killed approximately how many Jewish people?',
    options: ['~1 million', '~3 million', '~6 million', '~12 million'],
    correctAnswers: [2],
    explanation: 'About 6 million Jewish people were systematically murdered by Nazi Germany — roughly two-thirds of European Jewry. The Nazis also killed millions of other targeted groups: Roma, disabled people, Soviet POWs, Polish civilians, political dissidents, gay people, Jehovah\'s Witnesses. The total non-Jewish victims of Nazi genocide policies approached 5–6 million additional deaths. The Holocaust shaped postwar international law (the Genocide Convention, 1948; Nuremberg principles) and Jewish history (founding of Israel, 1948).',
  },
  {
    id: 'wwii-10',
    domain: 1,
    subdomain: 'World War II',
    type: 'ordering',
    difficulty: 'medium',
    question: 'Place these WWII events in chronological order from earliest to latest.',
    options: [
      'Germany invades Poland',
      'Pearl Harbor attacked',
      'D-Day invasion of Normandy',
      'Atomic bombs dropped on Japan',
    ],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'Germany invades Poland (Sept 1, 1939) → Pearl Harbor (Dec 7, 1941) → D-Day (June 6, 1944) → atomic bombs (Aug 6 and 9, 1945). The war in Europe began nearly six years before the atomic bombings ended it in the Pacific. The U.S. was officially in the war for only three years and eight months — December 1941 to September 1945.',
  },
  {
    id: 'wwii-11',
    domain: 1,
    subdomain: 'World War II',
    type: 'yesno',
    difficulty: 'medium',
    question: 'Was the G.I. Bill (1944) a major program affecting millions of returning WWII veterans?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes — the Servicemen\'s Readjustment Act (G.I. Bill) provided returning WWII veterans with tuition for college, low-interest home loans, unemployment compensation, and other benefits. About 8 million veterans used educational benefits; millions bought homes with G.I. loans. The program is credited with fueling the postwar middle-class boom and suburban expansion. (Black veterans received reduced benefits in practice due to discrimination by Northern colleges and Southern home lenders.)',
  },

  // ─── Cold War & Containment ──────────────────────────────────────
  {
    id: 'cw-07',
    domain: 1,
    subdomain: 'Cold War & Containment',
    type: 'single',
    difficulty: 'medium',
    question: 'The Berlin Airlift (1948–49) was the U.S./Allied response to:',
    options: [
      'A Nazi resurgence in West Berlin',
      'A Soviet ground blockade of West Berlin meant to force the Allies out',
      'A natural disaster in Germany',
      'A request from the West German government',
    ],
    correctAnswers: [1],
    explanation: 'The Soviet Union blockaded all ground access to West Berlin in June 1948, hoping to starve the Allies out. The U.S. and Britain responded with an extraordinary 11-month airlift — 277,000 flights delivered 2.3 million tons of food, coal, and supplies. The Soviets lifted the blockade in May 1949. The crisis directly accelerated NATO\'s formation (April 1949).',
  },
  {
    id: 'cw-08',
    domain: 1,
    subdomain: 'Cold War & Containment',
    type: 'single',
    difficulty: 'medium',
    question: 'The Korean War (1950–53) is often described as:',
    options: [
      'A complete U.S. victory',
      'A Soviet victory',
      'A stalemate that ended with an armistice (not a peace treaty) at roughly the original 38th parallel',
      'A war the U.S. avoided entirely',
    ],
    correctAnswers: [2],
    explanation: 'The Korean War ended in stalemate. North Korea invaded the South in June 1950; the U.N. (mostly U.S.) forces under MacArthur pushed the North Koreans nearly to the Chinese border; China entered the war and pushed the U.N. back. Three years of fighting left the boundary roughly where it started. The 1953 Armistice (not a formal peace treaty — North and South Korea are technically still at war) established the DMZ that persists today.',
  },
  {
    id: 'cw-09',
    domain: 1,
    subdomain: 'Cold War & Containment',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following were major proxy wars or interventions during the Cold War?',
    options: [
      'The Korean War (1950–53)',
      'The Vietnam War (1955–75)',
      'The Soviet invasion of Afghanistan (1979–89)',
      'The Iraq War of 2003–11',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Korea, Vietnam, and Afghanistan were major Cold War proxy or superpower interventions where the U.S. and USSR backed opposite sides. The 2003 Iraq War came after the Cold War ended in 1991 — it was a post-9/11 intervention with different geopolitical framing (counterterrorism / regime change), not Cold War containment.',
  },
  {
    id: 'cw-10',
    domain: 1,
    subdomain: 'Cold War & Containment',
    type: 'single',
    difficulty: 'medium',
    question: 'The Cuban Missile Crisis was resolved when:',
    options: [
      'The U.S. invaded Cuba',
      'The USSR agreed to remove its missiles from Cuba in exchange for a U.S. promise not to invade Cuba and secret removal of U.S. missiles from Turkey',
      'NATO intervened militarily',
      'Cuba declared its independence from both superpowers',
    ],
    correctAnswers: [1],
    explanation: 'The October 1962 crisis ended via backchannel negotiation between Kennedy and Khrushchev. The publicly-announced deal: USSR removes Cuba missiles, U.S. agrees not to invade Cuba. The secret deal (declassified decades later): U.S. quietly removed Jupiter missiles from Turkey a few months later. Both sides got what they needed; both could claim victory at home. The crisis prompted the Moscow-Washington "hot line" and the Limited Test Ban Treaty (1963).',
  },
  {
    id: 'cw-11',
    domain: 1,
    subdomain: 'Cold War & Containment',
    type: 'single',
    difficulty: 'hard',
    question: 'Which event is generally identified as the symbolic end of the Cold War?',
    options: [
      'The Cuban Missile Crisis',
      'The fall of the Berlin Wall on November 9, 1989',
      'The Korean Armistice',
      'The Marshall Plan ending',
    ],
    correctAnswers: [1],
    explanation: 'The fall of the Berlin Wall on November 9, 1989, is the iconic symbolic moment. Eastern European communist regimes collapsed in rapid succession that year (Poland, Hungary, East Germany, Czechoslovakia, Romania). The Soviet Union itself dissolved on December 26, 1991. Reagan\'s 1987 "Tear down this wall" speech at the Brandenburg Gate gained retrospective resonance.',
  },
  {
    id: 'cw-12',
    domain: 1,
    subdomain: 'Cold War & Containment',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Was the United States a member of the United Nations from its founding in 1945?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. After the Senate\'s rejection of the League of Nations Treaty in 1919, the U.S. learned its lesson. The Senate ratified the U.N. Charter in 1945 (89–2), and the U.N.\'s headquarters was built in New York City on land donated by John D. Rockefeller Jr. The U.S. has been one of the five permanent Security Council members (with veto power) since the U.N.\'s founding.',
  },

  // ─── Civil Rights Movement ──────────────────────────────────────
  {
    id: 'cr-07',
    domain: 1,
    subdomain: 'Civil Rights Movement',
    type: 'single',
    difficulty: 'easy',
    question: 'Who delivered the "I Have a Dream" speech?',
    options: ['Malcolm X', 'Martin Luther King Jr.', 'John F. Kennedy', 'Lyndon B. Johnson'],
    correctAnswers: [1],
    explanation: 'Martin Luther King Jr. delivered the "I Have a Dream" speech on August 28, 1963, at the March on Washington for Jobs and Freedom — to a crowd of about 250,000 people in front of the Lincoln Memorial. The speech is widely considered one of the greatest American speeches of all time. The march was a turning point in building public support for the Civil Rights Act of 1964.',
  },
  {
    id: 'cr-08',
    domain: 1,
    subdomain: 'Civil Rights Movement',
    type: 'single',
    difficulty: 'medium',
    question: 'The Little Rock Nine (1957) refers to:',
    options: [
      'Nine civil rights leaders arrested in Arkansas',
      'Nine Black students who integrated Little Rock Central High School under federal protection',
      'The first nine Black students at Harvard',
      'Nine Supreme Court justices who ruled on Brown v. Board',
    ],
    correctAnswers: [1],
    explanation: 'In September 1957, nine Black students attempted to integrate Little Rock Central High School in Arkansas, three years after Brown v. Board. Arkansas Governor Orval Faubus deployed the state National Guard to BLOCK their entry. President Eisenhower federalized the National Guard and sent the 101st Airborne Division to escort the students. The students endured harassment all year. The incident demonstrated that federal enforcement would back up Brown.',
  },
  {
    id: 'cr-09',
    domain: 1,
    subdomain: 'Civil Rights Movement',
    type: 'single',
    difficulty: 'medium',
    question: 'Which Supreme Court case extended the right to counsel to defendants in state criminal cases who could not afford an attorney?',
    options: [
      'Brown v. Board of Education (1954)',
      'Miranda v. Arizona (1966)',
      'Gideon v. Wainwright (1963)',
      'Tinker v. Des Moines (1969)',
    ],
    correctAnswers: [2],
    explanation: 'Gideon v. Wainwright (1963) — a unanimous Warren Court ruling — held that the Sixth Amendment\'s right to counsel applies to state felony defendants who cannot afford lawyers, requiring states to provide public defenders. Clarence Earl Gideon had been convicted of a Florida burglary without a lawyer; he hand-wrote his Supreme Court appeal from prison. The case is one of the great "due process revolution" cases of the Warren Court.',
  },
  {
    id: 'cr-10',
    domain: 1,
    subdomain: 'Civil Rights Movement',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are TRUE about the Voting Rights Act of 1965?',
    options: [
      'It banned literacy tests as a voting requirement',
      'It authorized federal observers and federal preclearance review of voting law changes in jurisdictions with histories of discrimination',
      'It enfranchised women',
      'It dramatically increased Black voter registration in the South',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'VRA banned literacy tests, authorized federal observers, and required preclearance (covered states had to get DOJ or court approval before changing voting rules). Black voter registration in the Deep South surged — Mississippi went from ~7% Black registration in 1965 to ~67% by 1969. Women were enfranchised by the 19th Amendment in 1920, NOT the VRA. The Supreme Court\'s Shelby County v. Holder (2013) gutted the preclearance formula.',
  },
  {
    id: 'cr-11',
    domain: 1,
    subdomain: 'Civil Rights Movement',
    type: 'single',
    difficulty: 'hard',
    question: 'The Black Panther Party (founded 1966) is best described as:',
    options: [
      'A nonviolent civil rights organization aligned with MLK',
      'A revolutionary Black nationalist organization that combined armed self-defense, community programs (free breakfast for children, health clinics), and Marxist analysis',
      'A formal political party that ran candidates for president',
      'A traditional civil rights group focused on litigation',
    ],
    correctAnswers: [1],
    explanation: 'The Black Panther Party for Self-Defense, founded by Huey Newton and Bobby Seale in Oakland in October 1966, was a Black nationalist and socialist organization that surveyed police interactions to deter brutality, ran free breakfast programs for thousands of children, operated health clinics, and articulated a 10-Point Program of demands. The FBI targeted it as a major domestic threat through COINTELPRO. Internal conflict, FBI infiltration, and the killing of Fred Hampton (Chicago, 1969) eroded the party by the mid-1970s.',
  },
  {
    id: 'cr-12',
    domain: 1,
    subdomain: 'Civil Rights Movement',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Was Martin Luther King Jr. ever arrested for civil rights activities?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes — Martin Luther King Jr. was arrested 29 times for civil rights activities. His most famous arrest produced the "Letter from Birmingham Jail" (April 1963), written in response to white clergy who urged him to slow down. The letter articulates the moral case for civil disobedience and the urgency of justice and is now widely studied as a foundational piece of American moral philosophy.',
  },

  // ─── Additional spread for content volume + difficulty mix ────────
  {
    id: 'found-13',
    domain: 1,
    subdomain: 'Foundations & Constitution',
    type: 'single',
    difficulty: 'medium',
    question: 'How can the U.S. Constitution be amended?',
    options: [
      'The President can amend it unilaterally',
      'A two-thirds vote in both houses of Congress plus ratification by three-fourths of the states',
      'A simple majority vote in Congress',
      'A national referendum every ten years',
    ],
    correctAnswers: [1],
    explanation: 'Article V lays out the standard amendment process: proposed by 2/3 of both House and Senate, then ratified by 3/4 of state legislatures (or state conventions). An alternative — never used — is a national convention called by 2/3 of states. The deliberately high thresholds explain why only 27 amendments have been ratified in 235+ years. The Bill of Rights (10 amendments) was added in 1791 right after ratification.',
  },
  {
    id: 'found-14',
    domain: 1,
    subdomain: 'Foundations & Constitution',
    type: 'single',
    difficulty: 'hard',
    question: 'Which Supreme Court case (1819) established that Congress has powers beyond those literally enumerated (the "implied powers" doctrine) and that states cannot tax federal institutions?',
    options: [
      'Marbury v. Madison',
      'McCulloch v. Maryland',
      'Gibbons v. Ogden',
      'Dred Scott v. Sandford',
    ],
    correctAnswers: [1],
    explanation: 'McCulloch v. Maryland (1819, John Marshall) confirmed Congress\'s power to charter the Second Bank of the United States (an implied power flowing from explicit fiscal powers via the Necessary and Proper Clause), and ruled that "the power to tax involves the power to destroy," so Maryland could not tax the federal bank. The case cemented broad federal authority and the supremacy of federal institutions over conflicting state actions.',
  },
  {
    id: 'recon-12',
    domain: 1,
    subdomain: 'Reconstruction',
    type: 'single',
    difficulty: 'hard',
    question: 'The Slaughter-House Cases (1873) are significant because they:',
    options: [
      'Expanded the 14th Amendment\'s protection of individual rights against states',
      'Narrowly interpreted the 14th Amendment\'s Privileges or Immunities Clause, effectively gutting it for nearly 150 years',
      'Established marriage equality',
      'Banned the death penalty',
    ],
    correctAnswers: [1],
    explanation: 'The Slaughter-House Cases (1873) — the first major Supreme Court interpretation of the 14th Amendment — read the Privileges or Immunities Clause so narrowly that it became nearly useless as a protector of individual rights against state action. The Court later relied on the Due Process and Equal Protection Clauses instead. This narrow reading helped slow Reconstruction\'s civil-rights project and is widely considered one of the Court\'s worst-reasoned decisions.',
  },
  {
    id: 'ind-12',
    domain: 1,
    subdomain: 'Industrialization & Gilded Age',
    type: 'single',
    difficulty: 'medium',
    question: 'The transcontinental railroad was completed in:',
    options: [
      'Promontory Summit, Utah, in May 1869',
      'Salt Lake City, Utah, in 1867',
      'San Francisco, California, in 1872',
      'Council Bluffs, Iowa, in 1865',
    ],
    correctAnswers: [0],
    explanation: 'The Union Pacific (building west from Omaha) and Central Pacific (building east from Sacramento) met at Promontory Summit, Utah, on May 10, 1869. Leland Stanford drove the ceremonial "Golden Spike." The transcontinental railroad slashed cross-country travel from months to about a week, opened the West to settlement, and unified national markets — but also displaced Native nations and devastated bison herds.',
  },
  {
    id: 'prog-12',
    domain: 1,
    subdomain: 'Progressive Era',
    type: 'single',
    difficulty: 'medium',
    question: 'The Federal Reserve, created in 1913, was designed primarily to:',
    options: [
      'Replace the dollar with a gold-backed alternative',
      'Provide a flexible central banking system that could respond to financial panics and regulate money supply',
      'Eliminate private banks',
      'Print currency for the executive branch on demand',
    ],
    correctAnswers: [1],
    explanation: 'The Panic of 1907 — averted only because J.P. Morgan personally organized a private bailout — convinced Congress the U.S. needed a real central bank. The Federal Reserve Act (1913) created 12 regional Federal Reserve Banks coordinated by a Board of Governors. The Fed acts as a "lender of last resort," manages monetary policy, and supervises member banks. Its powers have grown dramatically — especially after the 2008 financial crisis and during the COVID-19 response.',
  },
  {
    id: 'wwi-07',
    domain: 1,
    subdomain: 'World War I & 1920s',
    type: 'single',
    difficulty: 'medium',
    question: 'The League of Nations, established by the Treaty of Versailles, ultimately failed because:',
    options: [
      'It was too aggressive in punishing aggressor nations',
      'It lacked enforcement power and never included the United States, weakening its credibility',
      'It was disbanded by Hitler',
      'It refused to admit France or Britain',
    ],
    correctAnswers: [1],
    explanation: 'Wilson\'s League of Nations was supposed to be a forum for collective security and dispute resolution, but the U.S. Senate rejected the Versailles Treaty and the U.S. never joined. Without American participation, the League could not enforce its decisions. It failed to prevent Japanese aggression in Manchuria (1931), Italy\'s invasion of Ethiopia (1935), or German rearmament. After WWII, the U.N. inherited similar functions with more practical enforcement structure (Security Council, peacekeeping forces).',
  },
  {
    id: '20s-06',
    domain: 1,
    subdomain: 'World War I & 1920s',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are characteristic of the 1920s economy?',
    options: [
      'Rapid expansion of consumer credit (buying on installment)',
      'Stock market speculation, often using borrowed money (margin)',
      'Surging unemployment throughout the decade',
      'Rising automobile ownership (driven by Ford\'s assembly line)',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'The 1920s economy boomed on consumer credit, stock speculation, and mass-produced consumer goods. Auto ownership tripled. Radios and washing machines became commonplace. But the boom was unevenly distributed — farmers and Black Americans largely missed out, and the high-flying stock market was built on margin debt that would collapse spectacularly in October 1929. Unemployment was generally LOW in the 1920s; it surged AFTER the 1929 crash.',
  },
  {
    id: 'dep-13',
    domain: 1,
    subdomain: 'Great Depression & New Deal',
    type: 'single',
    difficulty: 'medium',
    question: 'Frances Perkins, FDR\'s Secretary of Labor (1933–45), is best known for:',
    options: [
      'Leading the U.S. delegation at Yalta',
      'Being the first female cabinet member and the principal architect of the Social Security Act',
      'Negotiating the Marshall Plan',
      'Founding the United Auto Workers',
    ],
    correctAnswers: [1],
    explanation: 'Frances Perkins was the first woman to serve in a U.S. presidential cabinet (1933) and stayed throughout FDR\'s entire 12-year presidency. She was instrumental in crafting the Social Security Act, the Fair Labor Standards Act (minimum wage, 40-hour week, banning child labor), and unemployment insurance. Her experience witnessing the Triangle Shirtwaist Fire as a young social worker is often cited as formative for her career.',
  },
  {
    id: 'dep-14',
    domain: 1,
    subdomain: 'Great Depression & New Deal',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Did the Supreme Court strike down some of FDR\'s New Deal programs as unconstitutional?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. The Court (conservative-majority during FDR\'s first term) struck down the National Industrial Recovery Act (NIRA, in Schechter Poultry Corp. v. United States, 1935) and the Agricultural Adjustment Act (AAA, in United States v. Butler, 1936). These setbacks prompted FDR\'s 1937 court-packing plan, which failed in Congress but coincided with the Court\'s "switch in time that saved nine" — after which the Court began upholding New Deal programs.',
  },
  {
    id: 'wwii-12',
    domain: 1,
    subdomain: 'World War II',
    type: 'single',
    difficulty: 'medium',
    question: 'The Battle of Midway (June 1942) is considered the turning point of the Pacific War because:',
    options: [
      'It was the largest amphibious assault in the Pacific',
      'The U.S. Navy sank four Japanese fleet aircraft carriers in three days, crippling Japan\'s offensive capability',
      'It led directly to Japan\'s surrender',
      'It ended Japan\'s involvement in WWII',
    ],
    correctAnswers: [1],
    explanation: 'At Midway, the U.S. Navy (under Admiral Nimitz, exploiting broken Japanese code) sank four of Japan\'s six fleet aircraft carriers (Akagi, Kaga, Soryu, Hiryu) and one heavy cruiser in three days. The U.S. lost one carrier (Yorktown). After Midway, Japan could no longer mount large-scale offensive operations — the strategic initiative shifted permanently to the U.S. The war continued for three more brutal years, but Japan was on the defensive.',
  },
  {
    id: 'cw-13',
    domain: 1,
    subdomain: 'Cold War & Containment',
    type: 'single',
    difficulty: 'medium',
    question: 'The Vietnam War became deeply unpopular in the U.S. partly because:',
    options: [
      'No American troops were sent — only money',
      'Television news brought combat footage, casualty counts, and events like the My Lai massacre into American homes nightly — known as the "living-room war"',
      'The economy benefited too much from war spending',
      'It was over within a few months',
    ],
    correctAnswers: [1],
    explanation: 'Vietnam was the first "television war." Walter Cronkite, Morley Safer, and other journalists reported on combat conditions and civilian casualties from the field. The 1968 Tet Offensive — a tactical defeat for the North but a strategic shock that contradicted official optimistic statements — shifted U.S. public opinion against the war. The Pentagon Papers (1971) exposed government deception. The combined effect transformed Vietnam into a deeply divisive event that shaped a generation\'s skepticism of government.',
  },
  {
    id: 'cw-14',
    domain: 1,
    subdomain: 'Cold War & Containment',
    type: 'single',
    difficulty: 'hard',
    question: 'The Eisenhower Doctrine (1957) extended containment to:',
    options: [
      'The Indian subcontinent',
      'The Middle East, pledging aid to countries threatened by communist aggression',
      'Latin America',
      'Sub-Saharan Africa',
    ],
    correctAnswers: [1],
    explanation: 'The Eisenhower Doctrine (1957) extended Truman-style containment to the Middle East, pledging economic and military aid to nations resisting "international communism." Issued in the wake of the 1956 Suez Crisis, it reflected growing U.S. interest in Middle Eastern stability and oil — and the perception that British and French influence in the region was fading. The doctrine was invoked most notably in Lebanon (1958), when U.S. Marines briefly landed in Beirut.',
  },
  {
    id: 'cr-13',
    domain: 1,
    subdomain: 'Civil Rights Movement',
    type: 'single',
    difficulty: 'medium',
    question: 'Loving v. Virginia (1967) struck down:',
    options: [
      'State laws banning same-sex marriage',
      'State laws banning interracial marriage',
      'School segregation in Virginia',
      'Poll taxes in federal elections',
    ],
    correctAnswers: [1],
    explanation: 'Loving v. Virginia (1967) was a unanimous Warren Court decision striking down all state laws prohibiting interracial marriage. Richard and Mildred Loving — a white man and a Black/Native American woman — had been convicted under Virginia\'s "Racial Integrity Act" of 1924. The Court held that such laws violated both the Equal Protection and Due Process Clauses of the 14th Amendment. Sixteen states still had such laws at the time of the ruling.',
  },
  {
    id: 'cr-14',
    domain: 1,
    subdomain: 'Civil Rights Movement',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following describe Title IX of the Education Amendments of 1972?',
    options: [
      'It bans sex discrimination in any education program receiving federal funding',
      'It dramatically expanded female participation in school athletics',
      'It applies only to elementary schools',
      'It has been used to address sexual harassment and assault in educational settings',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'Title IX (1972) is a 37-word law that has had enormous impact: it bans sex discrimination in any educational program receiving federal funds. The most visible result is the explosion of female participation in school athletics — in 1971, ~294,000 high school girls played sports; by 2020, about 3.4 million. Title IX also requires schools to address sexual harassment and assault. It applies to ALL levels of education, not just elementary schools.',
  },
  {
    id: 'found-15',
    domain: 1,
    subdomain: 'Foundations & Constitution',
    type: 'single',
    difficulty: 'medium',
    question: 'What is "stare decisis"?',
    options: [
      'A Latin phrase meaning "let the buyer beware"',
      'The doctrine that courts should follow precedent — earlier rulings should generally be respected in similar cases',
      'A constitutional right to a speedy trial',
      'The process of selecting a jury',
    ],
    correctAnswers: [1],
    explanation: 'Stare decisis (Latin: "to stand by things decided") is the doctrine that judges should follow precedents established in earlier cases. It provides stability and predictability in the law. The Supreme Court can overturn precedent (e.g., Brown overturning Plessy in 1954) but the threshold for doing so is high. Stare decisis explains why most lower-court rulings are tightly bound by earlier appellate decisions — but it does not bind the Supreme Court to its own prior rulings.',
  },
];
