import type { ExamImageKey } from './signs/catalog';

export interface Flashcard {
  id: string;
  front: string;
  back: string;
  category: 'road-signs' | 'traffic-rules' | 'numbers' | 'safety';
  difficulty: 'easy' | 'medium' | 'hard';
  /** Optional visual reference shown on the back of the card after flipping. Keeps the front a clue-only prompt. */
  imageBack?: ExamImageKey;
}

export const flashcardDeck: Flashcard[] = [
  // Road signs
  {
    id: 'scpermit-fc-001',
    front: 'Octagon (8 sides)',
    back: 'STOP — always come to a complete stop and check before moving.',
    category: 'road-signs',
    difficulty: 'easy',
    imageBack: 'sign:stop',
  },
  {
    id: 'scpermit-fc-002',
    front: 'Triangle pointing down',
    back: 'YIELD — slow down and let other traffic or people go first.',
    category: 'road-signs',
    difficulty: 'easy',
    imageBack: 'sign:yield',
  },
  {
    id: 'scpermit-fc-003',
    front: 'Diamond shape, yellow',
    back: 'WARNING — something ahead needs your attention, like a curve or merging traffic.',
    category: 'road-signs',
    difficulty: 'easy',
    imageBack: 'sign:warning-blank',
  },
  {
    id: 'scpermit-fc-004',
    front: 'Red circle with a line through it',
    back: 'NO — whatever is shown is not allowed.',
    category: 'road-signs',
    difficulty: 'easy',
  },
  {
    id: 'scpermit-fc-005',
    front: 'Rectangle sign, usually white',
    back: 'REGULATION — this is a rule you must follow, like speed limit or no parking.',
    category: 'road-signs',
    difficulty: 'easy',
    imageBack: 'sign:regulatory-blank',
  },
  {
    id: 'scpermit-fc-006',
    front: 'Pentagon shape, yellow',
    back: 'SCHOOL ZONE or SCHOOL CROSSING — kids may be nearby, so slow down.',
    category: 'road-signs',
    difficulty: 'medium',
    imageBack: 'sign:school-zone',
  },
  {
    id: 'scpermit-fc-007',
    front: 'Round sign, yellow with black X',
    back: 'RAILROAD CROSSING ahead — slow down, look, and listen for trains.',
    category: 'road-signs',
    difficulty: 'medium',
    imageBack: 'sign:railroad-crossing-circular',
  },
  {
    id: 'scpermit-fc-008',
    front: 'Pennant-shaped sign on the left side of the road',
    back: 'NO PASSING ZONE — stay in your lane and do not pass.',
    category: 'road-signs',
    difficulty: 'hard',
    imageBack: 'sign:no-passing-zone',
  },
  {
    id: 'scpermit-fc-009',
    front: 'Orange sign',
    back: 'WORK ZONE — road crews or lane changes may be ahead.',
    category: 'road-signs',
    difficulty: 'easy',
    imageBack: 'sign:work-zone',
  },
  {
    id: 'scpermit-fc-010',
    front: 'Blue sign',
    back: 'SERVICE sign — points to gas, food, lodging, hospital, or other helpful stops.',
    category: 'road-signs',
    difficulty: 'easy',
    imageBack: 'sign:guide-service',
  },
  {
    id: 'scpermit-fc-011',
    front: 'Green sign',
    back: 'GUIDE sign — gives directions, routes, exits, or distances.',
    category: 'road-signs',
    difficulty: 'easy',
    imageBack: 'sign:guide-green',
  },
  {
    id: 'scpermit-fc-012',
    front: 'Brown sign',
    back: 'RECREATION or historic sign — helps you find parks, beaches, or landmarks.',
    category: 'road-signs',
    difficulty: 'medium',
    imageBack: 'sign:guide-recreation',
  },
  {
    id: 'scpermit-fc-013',
    front: 'Red and white sign',
    back: 'Important rule or prohibition — pay attention because it usually means do not enter or stop/yield.',
    category: 'road-signs',
    difficulty: 'medium',
    imageBack: 'sign:do-not-enter',
  },
  {
    id: 'scpermit-fc-014',
    front: 'Do Not Enter sign',
    back: 'Do not go into that road or ramp from this direction.',
    category: 'road-signs',
    difficulty: 'easy',
    imageBack: 'sign:do-not-enter',
  },
  {
    id: 'scpermit-fc-015',
    front: 'Wrong Way sign',
    back: 'You are headed the wrong direction. Pull over safely and turn around when safe.',
    category: 'road-signs',
    difficulty: 'easy',
    imageBack: 'sign:wrong-way',
  },
  {
    id: 'scpermit-fc-016',
    front: 'Lane Ends sign',
    back: 'One lane is about to end, so merge safely.',
    category: 'road-signs',
    difficulty: 'medium',
    imageBack: 'sign:lane-ends',
  },
  {
    id: 'scpermit-fc-017',
    front: 'Merge sign',
    back: 'Traffic is joining your lane — be ready to adjust speed and spacing.',
    category: 'road-signs',
    difficulty: 'medium',
    imageBack: 'sign:merge',
  },
  {
    id: 'scpermit-fc-018',
    front: 'Slippery When Wet sign',
    back: 'Road may get slick in rain — slow down and avoid sudden moves.',
    category: 'road-signs',
    difficulty: 'easy',
    imageBack: 'sign:slippery-when-wet',
  },
  {
    id: 'scpermit-fc-019',
    front: 'Two-Way Traffic sign',
    back: 'Traffic will be coming from both directions, so stay alert and stay right.',
    category: 'road-signs',
    difficulty: 'easy',
    imageBack: 'sign:two-way-traffic',
  },
  {
    id: 'scpermit-fc-020',
    front: 'School Bus Stop Ahead sign',
    back: 'Be ready for kids, flashing bus lights, and sudden stops.',
    category: 'road-signs',
    difficulty: 'medium',
    imageBack: 'sign:school-bus-stop-ahead',
  },

  // Traffic rules
  {
    id: 'scpermit-fc-021',
    front: 'Flashing red light',
    back: 'Treat it like a stop sign — stop fully, then go when it is safe.',
    category: 'traffic-rules',
    difficulty: 'easy',
    imageBack: 'signal:flashing-red',
  },
  {
    id: 'scpermit-fc-022',
    front: 'Flashing yellow light',
    back: 'Slow down and be extra careful before moving through.',
    category: 'traffic-rules',
    difficulty: 'easy',
    imageBack: 'signal:flashing-yellow',
  },
  {
    id: 'scpermit-fc-023',
    front: 'Solid yellow line on your side',
    back: 'Do not cross it to pass.',
    category: 'traffic-rules',
    difficulty: 'easy',
    imageBack: 'lane:solid-yellow-your-side',
  },
  {
    id: 'scpermit-fc-024',
    front: 'Broken yellow line on your side',
    back: 'Passing is allowed if the road is clear and it is safe.',
    category: 'traffic-rules',
    difficulty: 'easy',
    imageBack: 'lane:dashed-yellow',
  },
  {
    id: 'scpermit-fc-025',
    front: 'Double solid yellow lines',
    back: 'No passing in either direction.',
    category: 'traffic-rules',
    difficulty: 'easy',
    imageBack: 'lane:double-yellow',
  },
  {
    id: 'scpermit-fc-026',
    front: 'Solid white line',
    back: 'Stay in your lane unless you need to change lanes and it is allowed.',
    category: 'traffic-rules',
    difficulty: 'medium',
    imageBack: 'lane:solid-white',
  },
  {
    id: 'scpermit-fc-027',
    front: 'Broken white line',
    back: 'Lane changes are allowed when safe.',
    category: 'traffic-rules',
    difficulty: 'easy',
    imageBack: 'lane:dashed-white',
  },
  {
    id: 'scpermit-fc-028',
    front: 'Right turn on red',
    back: 'Usually allowed after a full stop unless a sign says no. Yield first.',
    category: 'traffic-rules',
    difficulty: 'medium',
  },
  {
    id: 'scpermit-fc-029',
    front: 'At a 4-way stop',
    back: 'First car to stop goes first. If tied, the driver on the right goes first.',
    category: 'traffic-rules',
    difficulty: 'medium',
  },
  {
    id: 'scpermit-fc-030',
    front: 'Pedestrians in a crosswalk',
    back: 'They go first. Stop and let them cross safely.',
    category: 'traffic-rules',
    difficulty: 'easy',
  },
  {
    id: 'scpermit-fc-031',
    front: 'Emergency vehicle with siren/lights',
    back: 'Pull to the right and stop until it passes unless police direct otherwise.',
    category: 'traffic-rules',
    difficulty: 'easy',
  },
  {
    id: 'scpermit-fc-032',
    front: 'School bus with flashing red lights',
    back: 'Stop and stay stopped until the lights stop flashing or the bus moves again.',
    category: 'traffic-rules',
    difficulty: 'medium',
    imageBack: 'sign:school-bus-stop-ahead',
  },
  {
    id: 'scpermit-fc-033',
    front: 'Entering a highway',
    back: 'Use the ramp to speed up, signal, and merge when there is a safe gap.',
    category: 'traffic-rules',
    difficulty: 'medium',
  },
  {
    id: 'scpermit-fc-034',
    front: 'Leaving a highway',
    back: 'Signal early and move into the exit lane before slowing down a lot.',
    category: 'traffic-rules',
    difficulty: 'medium',
  },
  {
    id: 'scpermit-fc-035',
    front: 'When another driver is passing you',
    back: 'Stay in your lane and do not speed up.',
    category: 'traffic-rules',
    difficulty: 'easy',
  },
  {
    id: 'scpermit-fc-036',
    front: 'When you want to pass',
    back: 'Only pass when it is legal, the road is clear, and you can return safely.',
    category: 'traffic-rules',
    difficulty: 'medium',
  },
  {
    id: 'scpermit-fc-037',
    front: 'At a railroad crossing',
    back: 'Slow down, look both ways, listen, and never drive around lowered gates.',
    category: 'traffic-rules',
    difficulty: 'medium',
    imageBack: 'sign:railroad-crossing-circular',
  },
  {
    id: 'scpermit-fc-038',
    front: 'Turning left',
    back: 'Yield to oncoming traffic, signal, and turn into the correct lane.',
    category: 'traffic-rules',
    difficulty: 'medium',
  },
  {
    id: 'scpermit-fc-039',
    front: 'Backing up',
    back: 'Look over your right shoulder, go super slow, and only back when it is safe.',
    category: 'traffic-rules',
    difficulty: 'easy',
  },
  {
    id: 'scpermit-fc-040',
    front: 'At a yellow light',
    back: 'Slow down and stop if you can do it safely. Do not speed up to beat it.',
    category: 'traffic-rules',
    difficulty: 'easy',
    imageBack: 'signal:yellow',
  },

  // Numbers
  {
    id: 'scpermit-fc-041',
    front: 'Distance from a fire hydrant to park',
    back: '15 feet',
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'scpermit-fc-042',
    front: 'Distance from a crosswalk to park',
    back: '20 feet',
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'scpermit-fc-043',
    front: 'Distance from a stop sign to park',
    back: '30 feet',
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'scpermit-fc-044',
    front: 'Distance from a traffic signal to park',
    back: '30 feet',
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'scpermit-fc-045',
    front: 'Distance from a railroad crossing to park',
    back: '50 feet',
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'scpermit-fc-046',
    front: 'Speed limit in cities and towns',
    back: '30 mph unless a sign says something else.',
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'scpermit-fc-047',
    front: 'School zone speed limit',
    back: '25 mph unless posted otherwise.',
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'scpermit-fc-048',
    front: 'Maximum interstate speed in South Carolina',
    back: '70 mph unless posted lower.',
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'scpermit-fc-049',
    front: 'Typical rural road speed limit',
    back: '55 mph unless posted otherwise.',
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'scpermit-fc-050',
    front: 'Following distance rule',
    back: 'At least 2 seconds in good conditions — more in rain, fog, or traffic.',
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'scpermit-fc-051',
    front: 'When to use your turn signal before turning',
    back: 'At least 100 feet before the turn.',
    category: 'numbers',
    difficulty: 'easy',
  },
  {
    id: 'scpermit-fc-052',
    front: 'When to dim high beams for oncoming traffic',
    back: 'Within 500 feet of an oncoming vehicle.',
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'scpermit-fc-053',
    front: 'When to dim high beams when following another car',
    back: 'Within 200 feet behind that vehicle.',
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'scpermit-fc-054',
    front: 'When to use headlights',
    back: 'When you cannot clearly see 500 feet ahead.',
    category: 'numbers',
    difficulty: 'medium',
  },
  {
    id: 'scpermit-fc-055',
    front: 'BAC limit for DUI',
    back: '0.08% for adults, and basically zero tolerance for drivers under 21.',
    category: 'numbers',
    difficulty: 'hard',
  },

  // Safety
  {
    id: 'scpermit-fc-056',
    front: 'What to do if your brakes fail',
    back: 'Pump the brake pedal, use the parking brake gently, downshift if possible, and steer to a safe spot.',
    category: 'safety',
    difficulty: 'hard',
  },
  {
    id: 'scpermit-fc-057',
    front: 'Hydroplaning',
    back: 'Your tires ride on water and lose grip. Ease off the gas and do not slam the brakes.',
    category: 'safety',
    difficulty: 'medium',
  },
  {
    id: 'scpermit-fc-058',
    front: 'If a tire blows out',
    back: 'Hold the wheel tight, ease off the gas, and steer smoothly to a safe place.',
    category: 'safety',
    difficulty: 'medium',
  },
  {
    id: 'scpermit-fc-059',
    front: 'If your car starts skidding',
    back: 'Look where you want to go and steer gently in that direction. Do not overcorrect.',
    category: 'safety',
    difficulty: 'hard',
  },
  {
    id: 'scpermit-fc-060',
    front: 'Safe night driving',
    back: 'Slow down, increase following distance, and keep your eyes moving.',
    category: 'safety',
    difficulty: 'easy',
  },
  {
    id: 'scpermit-fc-061',
    front: 'Seat belt rule',
    back: 'Buckle up every trip, every seat, every time. No excuses.',
    category: 'safety',
    difficulty: 'easy',
  },
  {
    id: 'scpermit-fc-062',
    front: 'Sharing the road with motorcycles',
    back: 'Give them a full lane and extra space. They are smaller, not invincible.',
    category: 'safety',
    difficulty: 'medium',
  },
  {
    id: 'scpermit-fc-063',
    front: 'Sharing the road with trucks',
    back: 'Stay out of their blind spots and do not cut in too close.',
    category: 'safety',
    difficulty: 'medium',
  },
  {
    id: 'scpermit-fc-064',
    front: 'What to do when you feel road rage building',
    back: 'Take a breath, back off, and do not make the situation worse. Getting home matters more than being right.',
    category: 'safety',
    difficulty: 'easy',
  },
  {
    id: 'scpermit-fc-065',
    front: 'Most important safe-driving mindset',
    back: 'Stay calm, stay focused, and expect other drivers to do random stuff.',
    category: 'safety',
    difficulty: 'easy',
  },
];
