export interface Flashcard {
  id: string;
  front: string;
  back: string;
  category: 'vocabulary' | 'math-formula' | 'grammar-rule' | 'strategy';
  difficulty: 'easy' | 'medium' | 'hard';
}

export const flashcardDeck: Flashcard[] = [
  // Vocabulary
  {
    id: 'sat-fc-001',
    front: 'abate',
    back: `to become less intense or widespread. Example: After the storm began to abate, the hikers continued down the trail.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-002',
    front: 'aberration',
    back: `a departure from what is normal or expected. Example: The scientist treated the unusual result as an aberration and repeated the experiment.`,
    category: 'vocabulary',
    difficulty: 'hard',
  },
  {
    id: 'sat-fc-003',
    front: 'advocate',
    back: `to support publicly; also a person who supports a cause. Example: The mayor continued to advocate for expanded public transportation.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-004',
    front: 'ambiguous',
    back: `unclear or open to more than one interpretation. Example: Because the instructions were ambiguous, several students completed the lab differently.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-005',
    front: 'arbitrary',
    back: `based on random choice rather than reason or system. Example: The committee avoided making an arbitrary decision by reviewing the evidence carefully.`,
    category: 'vocabulary',
    difficulty: 'hard',
  },
  {
    id: 'sat-fc-006',
    front: 'bolster',
    back: `to support, strengthen, or reinforce. Example: The new data helped bolster the author's argument about climate trends.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-007',
    front: 'candid',
    back: `honest and straightforward. Example: In a candid interview, the athlete admitted that the season had been difficult.`,
    category: 'vocabulary',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-008',
    front: 'concise',
    back: `brief but clear and complete. Example: Her concise summary captured the article's main claim in two sentences.`,
    category: 'vocabulary',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-009',
    front: 'corroborate',
    back: `to confirm or support with evidence. Example: The diary entries corroborate the historian's account of the expedition.`,
    category: 'vocabulary',
    difficulty: 'hard',
  },
  {
    id: 'sat-fc-010',
    front: 'deferential',
    back: `showing respectful submission to another's judgment. Example: The intern remained deferential when offering suggestions to the director.`,
    category: 'vocabulary',
    difficulty: 'hard',
  },
  {
    id: 'sat-fc-011',
    front: 'diligent',
    back: `careful and persistent in effort. Example: Through diligent practice, the pianist mastered the most difficult passage.`,
    category: 'vocabulary',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-012',
    front: 'eloquent',
    back: `fluent, persuasive, and expressive in speaking or writing. Example: Her eloquent speech moved the audience to applause.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-013',
    front: 'empathy',
    back: `the ability to understand and share another person's feelings. Example: The novel encourages empathy by showing the conflict from multiple perspectives.`,
    category: 'vocabulary',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-014',
    front: 'feasible',
    back: `possible to do easily or realistically. Example: After reviewing the budget, the team concluded that the proposal was feasible.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-015',
    front: 'frugal',
    back: `careful about spending money or resources. Example: Because the researchers were frugal, they stretched the grant across two years.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-016',
    front: 'galvanize',
    back: `to spur into action. Example: The principal's announcement galvanized students into organizing a tutoring program.`,
    category: 'vocabulary',
    difficulty: 'hard',
  },
  {
    id: 'sat-fc-017',
    front: 'impartial',
    back: `fair and not favoring one side over another. Example: A good judge must remain impartial during the entire trial.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-018',
    front: 'inevitable',
    back: `certain to happen; unavoidable. Example: Given the traffic, a delay seemed inevitable.`,
    category: 'vocabulary',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-019',
    front: 'justify',
    back: `to show or prove to be reasonable. Example: The data did not justify the researcher's bold conclusion.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-020',
    front: 'meticulous',
    back: `extremely careful and precise. Example: The editor's meticulous review caught even the smallest formatting errors.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-021',
    front: 'obscure',
    back: `not well known; difficult to understand. Example: The article explained an obscure scientific concept in simple language.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-022',
    front: 'pragmatic',
    back: `practical and focused on results. Example: Rather than argue about theory, the engineer proposed a pragmatic solution.`,
    category: 'vocabulary',
    difficulty: 'hard',
  },
  {
    id: 'sat-fc-023',
    front: 'profound',
    back: `very deep, intense, or insightful. Example: The philosopher's question had a profound effect on the class discussion.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-024',
    front: 'resilient',
    back: `able to recover quickly from difficulty. Example: The resilient community rebuilt after the flood.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-025',
    front: 'scrutinize',
    back: `to examine very closely. Example: Before accepting the claim, readers should scrutinize the source of the evidence.`,
    category: 'vocabulary',
    difficulty: 'hard',
  },
  {
    id: 'sat-fc-026',
    front: 'substantiate',
    back: `to support with facts or evidence. Example: The speaker used charts and studies to substantiate her argument.`,
    category: 'vocabulary',
    difficulty: 'hard',
  },
  {
    id: 'sat-fc-027',
    front: 'tentative',
    back: `not fully certain or fixed; hesitant. Example: Because the evidence was limited, the scientist offered only a tentative conclusion.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-028',
    front: 'undermine',
    back: `to weaken or damage gradually. Example: Repeated factual errors can undermine an author's credibility.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-029',
    front: 'valid',
    back: `logically sound or well founded. Example: Her criticism was valid because it was based on evidence from the report.`,
    category: 'vocabulary',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-030',
    front: 'wary',
    back: `cautious or watchful. Example: Investors grew wary after the company released an unclear statement.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-031',
    front: 'yield',
    back: `to produce, provide, or give way. Example: The revised experiment may yield more reliable results.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-032',
    front: 'austere',
    back: `plain, severe, or lacking luxury. Example: The author's austere style avoided unnecessary ornament.`,
    category: 'vocabulary',
    difficulty: 'hard',
  },
  {
    id: 'sat-fc-033',
    front: 'benevolent',
    back: `kind and generous. Example: The benevolent donor funded scholarships for first-generation students.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-034',
    front: 'coherent',
    back: `logical, clear, and consistent. Example: A coherent essay connects every paragraph to the thesis.`,
    category: 'vocabulary',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-035',
    front: 'disdain',
    back: `a feeling of scorn or lack of respect. Example: The critic regarded the flashy advertisement with open disdain.`,
    category: 'vocabulary',
    difficulty: 'hard',
  },
  {
    id: 'sat-fc-036',
    front: 'ephemeral',
    back: `lasting for a very short time. Example: The fame created by the viral video proved ephemeral.`,
    category: 'vocabulary',
    difficulty: 'hard',
  },
  {
    id: 'sat-fc-037',
    front: 'fortify',
    back: `to strengthen or secure. Example: The additional evidence helped fortify the historian's interpretation.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-038',
    front: 'novel',
    back: `new, original, or unusual. Example: The researcher proposed a novel method for storing solar energy.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-039',
    front: 'reconcile',
    back: `to bring into agreement or make compatible. Example: The committee tried to reconcile the two conflicting reports.`,
    category: 'vocabulary',
    difficulty: 'hard',
  },
  {
    id: 'sat-fc-040',
    front: 'viable',
    back: `capable of working successfully; practical. Example: After testing the prototype, the team knew the design was viable.`,
    category: 'vocabulary',
    difficulty: 'medium',
  },

  // Math formulas and concepts
  {
    id: 'sat-fc-041',
    front: 'Linear Equation Slope-Intercept Form',
    back: `y = mx + b. Use this form to identify slope (m) and y-intercept (b) quickly from a line's equation.`,
    category: 'math-formula',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-042',
    front: 'Point-Slope Form',
    back: `y - y₁ = m(x - x₁). Use when you know the slope and one point on a line.`,
    category: 'math-formula',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-043',
    front: 'Standard Form of a Line',
    back: `Ax + By = C. Use standard form when working with intercepts or solving systems efficiently.`,
    category: 'math-formula',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-044',
    front: 'Slope Formula',
    back: `m = (y₂ - y₁) / (x₂ - x₁). Use to find the slope of a line through two points.`,
    category: 'math-formula',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-045',
    front: 'Parallel and Perpendicular Slopes',
    back: `Parallel lines have equal slopes; perpendicular slopes are negative reciprocals. Use to compare line relationships.`,
    category: 'math-formula',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-046',
    front: 'System of Equations: Substitution',
    back: `Solve one equation for a variable, then substitute into the other equation. Use when one variable is already isolated or easy to isolate.`,
    category: 'math-formula',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-047',
    front: 'System of Equations: Elimination',
    back: `Add or subtract equations to cancel a variable. Use when coefficients can be matched easily.`,
    category: 'math-formula',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-048',
    front: 'Exponent Product and Quotient Rules',
    back: `a^m · a^n = a^(m+n) and a^m / a^n = a^(m-n). Use when multiplying or dividing like bases.`,
    category: 'math-formula',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-049',
    front: 'Power Rules for Exponents',
    back: `(a^m)^n = a^(mn) and (ab)^n = a^n b^n. Use when raising powers or products to a power.`,
    category: 'math-formula',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-050',
    front: 'Greatest Common Factor Factoring',
    back: `ax + ay = a(x + y). Use first when factoring polynomials to simplify expressions.`,
    category: 'math-formula',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-051',
    front: 'Difference of Squares',
    back: `a² - b² = (a - b)(a + b). Use when a binomial has two square terms with subtraction.`,
    category: 'math-formula',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-052',
    front: 'Quadratic Formula',
    back: `x = [-b ± √(b² - 4ac)] / (2a). Use to solve ax² + bx + c = 0 when factoring is difficult.`,
    category: 'math-formula',
    difficulty: 'hard',
  },
  {
    id: 'sat-fc-053',
    front: 'Vertex Form of a Quadratic',
    back: `y = a(x - h)² + k. Use to identify the vertex quickly as (h, k).`,
    category: 'math-formula',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-054',
    front: 'Axis of Symmetry',
    back: `x = -b / (2a) for y = ax² + bx + c. Use to find the x-value through the middle of a parabola.`,
    category: 'math-formula',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-055',
    front: 'Discriminant',
    back: `b² - 4ac. Use to determine the number of real solutions of a quadratic: positive = 2, zero = 1, negative = 0 real solutions.`,
    category: 'math-formula',
    difficulty: 'hard',
  },
  {
    id: 'sat-fc-056',
    front: 'Percent Change',
    back: `percent change = (change / original) × 100%. Use for percent increase or decrease problems.`,
    category: 'math-formula',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-057',
    front: 'Simple Interest',
    back: `I = Prt. Use when interest grows only on the original principal.`,
    category: 'math-formula',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-058',
    front: 'Exponential Growth and Decay',
    back: `y = a(1 ± r)^t. Use for repeated percent growth or reduction over equal time intervals.`,
    category: 'math-formula',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-059',
    front: 'Distance Formula',
    back: `d = √[(x₂ - x₁)² + (y₂ - y₁)²]. Use to find the distance between two points on the coordinate plane.`,
    category: 'math-formula',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-060',
    front: 'Midpoint Formula',
    back: `midpoint = ((x₁ + x₂)/2, (y₁ + y₂)/2). Use to find the point halfway between two endpoints.`,
    category: 'math-formula',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-061',
    front: 'Area of a Circle',
    back: `A = πr². Use when asked for the space inside a circle.`,
    category: 'math-formula',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-062',
    front: 'Circumference of a Circle',
    back: `C = 2πr or C = πd. Use when asked for the distance around a circle.`,
    category: 'math-formula',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-063',
    front: 'Pythagorean Theorem',
    back: `a² + b² = c². Use in right triangles to relate the legs and hypotenuse.`,
    category: 'math-formula',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-064',
    front: '45-45-90 Triangle Ratios',
    back: `side ratio = x : x : x√2. Use for isosceles right triangles to find missing sides quickly.`,
    category: 'math-formula',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-065',
    front: '30-60-90 Triangle Ratios',
    back: `side ratio = x : x√3 : 2x. Use for special right triangles with 30°, 60°, and 90° angles.`,
    category: 'math-formula',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-066',
    front: 'SOHCAHTOA',
    back: `sin = opposite/hypotenuse, cos = adjacent/hypotenuse, tan = opposite/adjacent. Use basic trig to find sides or angles in right triangles.`,
    category: 'math-formula',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-067',
    front: 'Mean',
    back: `mean = sum of values / number of values. Use to find the arithmetic average.`,
    category: 'math-formula',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-068',
    front: 'Median',
    back: `The median is the middle value in an ordered list, or the average of the two middle values when there is an even number of terms. Use for the center of ordered data.`,
    category: 'math-formula',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-069',
    front: 'Standard Deviation',
    back: `Standard deviation measures how spread out data are from the mean. Use it to compare variability in data sets.`,
    category: 'math-formula',
    difficulty: 'hard',
  },
  {
    id: 'sat-fc-070',
    front: 'Probability',
    back: `probability = favorable outcomes / total possible outcomes. Use when all outcomes are equally likely.`,
    category: 'math-formula',
    difficulty: 'easy',
  },

  // Grammar rules
  {
    id: 'sat-fc-071',
    front: 'Comma with FANBOYS',
    back: `Use a comma before for, and, nor, but, or, yet, so when joining two independent clauses. Correct: The data were limited, but the conclusion was careful. Incorrect: The data were limited but the conclusion was careful.`,
    category: 'grammar-rule',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-072',
    front: 'Semicolon Usage',
    back: `Use a semicolon to join two closely related independent clauses. Correct: Maya revised the draft; her partner checked the citations. Incorrect: Maya revised the draft; because her partner checked the citations.`,
    category: 'grammar-rule',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-073',
    front: 'Colon Usage',
    back: `Use a colon after a complete sentence to introduce a list, explanation, or example. Correct: The committee reached one conclusion: the plan needed more funding. Incorrect: The committee reached: one conclusion that the plan needed more funding.`,
    category: 'grammar-rule',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-074',
    front: 'Dash Usage',
    back: `Use em dashes to set off nonessential information for emphasis. Correct: The final speaker—who had studied the issue for years—answered every question. Incorrect: The final speaker—who had studied the issue for years answered every question.`,
    category: 'grammar-rule',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-075',
    front: 'Introductory Comma',
    back: `Use a comma after an introductory phrase or clause. Correct: After reviewing the graph, Lena changed her answer. Incorrect: After reviewing the graph Lena changed her answer.`,
    category: 'grammar-rule',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-076',
    front: 'Nonessential Clause Commas',
    back: `Set off nonessential information with commas. Correct: The mural, which was painted in 1932, attracts thousands of visitors. Incorrect: The mural which was painted in 1932 attracts thousands of visitors.`,
    category: 'grammar-rule',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-077',
    front: 'Apostrophes',
    back: `Use apostrophes for possession and contractions, not for plurals. Correct: The artist's sketches were on display. Incorrect: The artists sketches were on display.`,
    category: 'grammar-rule',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-078',
    front: 'Subject-Verb Agreement',
    back: `A singular subject takes a singular verb; a plural subject takes a plural verb. Correct: The list of winners is on the table. Incorrect: The list of winners are on the table.`,
    category: 'grammar-rule',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-079',
    front: 'Pronoun-Antecedent Agreement',
    back: `A pronoun must agree in number with the noun it replaces. Correct: Every student submitted his or her form on time. Incorrect: Every student submitted their form on time.`,
    category: 'grammar-rule',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-080',
    front: 'Verb Tense Consistency',
    back: `Keep verb tense consistent unless the time frame changes. Correct: The scientist recorded the data and wrote a summary. Incorrect: The scientist recorded the data and writes a summary.`,
    category: 'grammar-rule',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-081',
    front: 'Parallel Structure',
    back: `Items in a list or comparison should match grammatically. Correct: The job requires planning, writing, and revising. Incorrect: The job requires planning, writing, and to revise.`,
    category: 'grammar-rule',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-082',
    front: 'Sentence Fragment',
    back: `A fragment lacks a complete thought, subject, or verb. Correct: Because the roads were flooded, school was canceled. Incorrect: Because the roads were flooded.`,
    category: 'grammar-rule',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-083',
    front: 'Run-On Sentence',
    back: `Two independent clauses cannot be joined with no punctuation or only a comma. Correct: The lecture ended, and the students asked questions. Incorrect: The lecture ended the students asked questions.`,
    category: 'grammar-rule',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-084',
    front: 'Misplaced Modifier',
    back: `Place descriptive phrases next to what they modify. Correct: Walking through the museum, Ana admired the sculptures. Incorrect: Walking through the museum, the sculptures impressed Ana.`,
    category: 'grammar-rule',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-085',
    front: 'Who vs. Whom',
    back: `Use who for subjects and whom for objects. Correct: The scientist whom the reporter interviewed won an award. Incorrect: The scientist who the reporter interviewed won an award.`,
    category: 'grammar-rule',
    difficulty: 'hard',
  },
  {
    id: 'sat-fc-086',
    front: `Its vs. It's`,
    back: `It's means it is; its is possessive. Correct: The company changed its policy because it's expanding. Incorrect: The company changed it's policy because its expanding.`,
    category: 'grammar-rule',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-087',
    front: 'Affect vs. Effect',
    back: `Affect is usually a verb; effect is usually a noun. Correct: The weather may affect attendance. Incorrect: The weather may effect attendance.`,
    category: 'grammar-rule',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-088',
    front: 'Less vs. Fewer',
    back: `Use fewer for countable items and less for uncountable amounts. Correct: Fewer students missed class this week. Incorrect: Less students missed class this week.`,
    category: 'grammar-rule',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-089',
    front: 'Then vs. Than',
    back: `Then relates to time; than introduces comparison. Correct: Maya finished earlier than Luis and then left for practice. Incorrect: Maya finished earlier then Luis and than left for practice.`,
    category: 'grammar-rule',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-090',
    front: 'Pronoun Case',
    back: `Use subject pronouns for subjects and object pronouns for objects. Correct: Jordan and I presented the project. Incorrect: Jordan and me presented the project.`,
    category: 'grammar-rule',
    difficulty: 'medium',
  },

  // Reading and test strategies
  {
    id: 'sat-fc-091',
    front: 'Read the Question Stem First',
    back: `Before diving into the passage, note what the question asks so you know whether to hunt for a main idea, detail, inference, or grammar issue.`,
    category: 'strategy',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-092',
    front: 'Predict Before Looking at Choices',
    back: `Pause and form your own answer first. This makes trap choices easier to spot and keeps you focused on evidence.`,
    category: 'strategy',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-093',
    front: 'Use Evidence for Inferences',
    back: `On inference questions, choose the answer that must be true based on the text—not one that sounds plausible from outside knowledge.`,
    category: 'strategy',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-094',
    front: 'Plug In Vocabulary Choices',
    back: `For words-in-context questions, replace the tested word with each choice and pick the one that best preserves the sentence's meaning and tone.`,
    category: 'strategy',
    difficulty: 'easy',
  },
  {
    id: 'sat-fc-095',
    front: 'Eliminate Extreme Answers',
    back: `Choices with words like always, never, or completely are often wrong unless the passage clearly supports that level of certainty.`,
    category: 'strategy',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-096',
    front: 'Track Logical Relationships',
    back: `In revision and transition questions, identify whether the sentence needs contrast, cause/effect, addition, or example before choosing an answer.`,
    category: 'strategy',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-097',
    front: 'Use Desmos Strategically',
    back: `On Digital SAT math, graph equations, test intersections, and visualize transformations in Desmos—but only when it saves time over algebra.`,
    category: 'strategy',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-098',
    front: 'Backsolve or Plug In Numbers',
    back: `When answer choices are numeric or variables represent general values, substitute smart numbers or test choices from the options to work backward efficiently.`,
    category: 'strategy',
    difficulty: 'medium',
  },
  {
    id: 'sat-fc-099',
    front: 'Pace by Module',
    back: `Keep moving. Since Module 2 adapts from Module 1 performance, protecting accuracy early matters—but never spend so long on one item that you miss easy points later.`,
    category: 'strategy',
    difficulty: 'hard',
  },
  {
    id: 'sat-fc-100',
    front: 'Guess on Every Question',
    back: `The SAT has no penalty for wrong answers, so eliminate what you can and make a guess rather than leaving anything blank.`,
    category: 'strategy',
    difficulty: 'easy',
  },
];
