// Question bank for ALG2 — Algebra 2 (SC 11th-grade standard-pace math).
// No EOCEP. Covers 7 content subdomains across ≥100 questions.

export type QuestionType = 'single' | 'multi' | 'ordering' | 'yesno';

export interface Question {
  id: string;
  domain: 1;
  subdomain: string;
  type: QuestionType;
  difficulty: 'easy' | 'medium' | 'hard';
  question: string;
  options: string[];
  correctAnswers: number[];
  explanation: string;
  codeSnippet?: string;
  examTip?: string;
}

export const questions: Question[] = [
  // ══════════════════════════════════════════════════════════════════
  // Polynomial & Rational Functions
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'poly-01',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'What is the degree of the polynomial 4x⁵ − 7x³ + 2x − 9?',
    options: ['3', '4', '5', '9'],
    correctAnswers: [2],
    explanation: 'The degree of a polynomial is the highest exponent on the variable. The term 4x⁵ has the highest exponent, so the degree is 5. Don\'t be fooled by the constant −9 (degree 0) or the coefficient 4.',
  },
  {
    id: 'poly-02',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'Describe the end behavior of f(x) = −3x⁴ + 7x² − 1.',
    options: [
      'Both ends go up (↑ … ↑)',
      'Both ends go down (↓ … ↓)',
      'Left end goes down, right end goes up (↓ … ↑)',
      'Left end goes up, right end goes down (↑ … ↓)',
    ],
    correctAnswers: [1],
    explanation: 'For end behavior, check the leading term: −3x⁴. Even degree (4) means both arms go the same direction; negative leading coefficient means both go DOWN. So f(x) → −∞ as x → ±∞, giving ↓ … ↓.',
  },
  {
    id: 'poly-03',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'If x = 2 is a zero of multiplicity 2 for a polynomial, how does the graph behave at x = 2?',
    options: [
      'Crosses the x-axis sharply',
      'Touches the x-axis and bounces back (does not cross)',
      'Has a vertical asymptote',
      'Crosses and continues in the same direction',
    ],
    correctAnswers: [1],
    explanation: 'Even multiplicity → the graph touches the x-axis and turns around (bounces). Odd multiplicity → the graph crosses through. Since multiplicity 2 is even, the curve kisses the axis at x = 2 and returns without crossing.',
  },
  {
    id: 'poly-04',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'Divide (x³ − 3x² + 4) by (x − 2) using synthetic division. What is the remainder?',
    options: ['−4', '0', '4', '2'],
    correctAnswers: [1],
    explanation: 'Set up synthetic division with root 2 and coefficients 1, −3, 0, 4 (note the 0 for the missing x term). Bring down 1; 1×2=2, −3+2=−1; −1×2=−2, 0+(−2)=−2; −2×2=−4, 4+(−4)=0. Remainder is 0, meaning (x−2) is a factor.',
  },
  {
    id: 'poly-05',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'The Rational Zeros Theorem says the possible rational zeros of 2x³ − 5x² + x − 6 are ±(factors of 6)/(factors of 2). Which list is complete?',
    options: [
      '±1, ±2, ±3, ±6',
      '±1/2, ±3/2, ±1, ±2, ±3, ±6',
      '±1, ±2, ±3, ±6, ±1/2, ±3/2',
      '±2, ±3, ±1/2',
    ],
    correctAnswers: [2],
    explanation: 'Factors of the constant 6: 1,2,3,6. Factors of the leading coefficient 2: 1,2. Possible rational zeros = p/q = ±1/1, ±2/1, ±3/1, ±6/1, ±1/2, ±3/2. Both options C and B list these — option C (matching ±1,±2,±3,±6,±1/2,±3/2) is the standard complete list.',
  },
  {
    id: 'poly-06',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'What is the vertical asymptote of the rational function f(x) = (x+3)/(x−5)?',
    options: ['x = −3', 'x = 3', 'x = 5', 'x = −5'],
    correctAnswers: [2],
    explanation: 'Vertical asymptotes occur where the denominator equals zero (and the zero doesn\'t cancel with the numerator). Set x − 5 = 0, giving x = 5. There is no common factor to cancel, so x = 5 is a vertical asymptote, not a hole.',
  },
  {
    id: 'poly-07',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'For f(x) = (3x²)/(x² + 1), what is the horizontal asymptote?',
    options: ['y = 0', 'y = 1', 'y = 3', 'No horizontal asymptote'],
    correctAnswers: [2],
    explanation: 'When the degrees of numerator and denominator are equal, the horizontal asymptote is y = (leading coeff numerator)/(leading coeff denominator) = 3/1 = 3. If deg(num) < deg(den), y = 0. If deg(num) > deg(den), no horizontal asymptote (possible slant).',
  },
  {
    id: 'poly-08',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'Which function has a "hole" (removable discontinuity) rather than a vertical asymptote at x = 2?',
    options: [
      'f(x) = (x−2)/(x²−9)',
      'f(x) = (x²−4)/(x−2)',
      'f(x) = (x+2)/(x−2)',
      'f(x) = 1/(x−2)',
    ],
    correctAnswers: [1],
    explanation: 'A hole occurs when a factor cancels. x²−4 = (x−2)(x+2), so (x²−4)/(x−2) = (x+2) for x≠2. The (x−2) cancels, leaving a hole at x=2 (the point (2,4) is missing). The other options don\'t have (x−2) in the numerator to cancel.',
  },
  {
    id: 'poly-09',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'By the Fundamental Theorem of Algebra, how many complex zeros does f(x) = x³ − 5x + 6 have (counting multiplicity)?',
    options: ['1', '2', '3', 'Cannot be determined'],
    correctAnswers: [2],
    explanation: 'The Fundamental Theorem of Algebra states that every polynomial of degree n has exactly n complex zeros (counted with multiplicity). Since the degree is 3, there are exactly 3 complex zeros, though some may be real and some may come in conjugate pairs.',
  },
  {
    id: 'poly-10',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'f(x) = (2x²−3x+1)/(x−2). When you do polynomial long division, what is the slant asymptote?',
    options: ['y = 2x + 1', 'y = 2x − 7', 'y = 2x + 7', 'y = x − 2'],
    correctAnswers: [0],
    explanation: 'Divide 2x²−3x+1 by x−2. First term: 2x²÷x = 2x. Multiply: 2x(x−2) = 2x²−4x. Subtract: (−3x+4x)+1 = x+1. Next term: x÷x = 1. Multiply: 1(x−2) = x−2. Subtract: 1−(−2) = 3. Result: 2x+1 remainder 3. Slant asymptote is y = 2x+1.',
  },
  {
    id: 'poly-11',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'What does the Factor Theorem say about a polynomial p(x)?',
    options: [
      '(x − a) is a factor of p(x) if and only if p(a) = 0',
      '(x + a) is always a factor of p(x)',
      'p(x) has no real factors if its degree is odd',
      'p(a) = 0 means a is not a factor',
    ],
    correctAnswers: [0],
    explanation: 'The Factor Theorem: (x − a) is a factor of p(x) if and only if p(a) = 0. This is a two-way street — if you find a zero, you\'ve found a factor, and vice versa. The Remainder Theorem says p(a) = remainder when dividing by (x−a), so zero remainder ↔ factor.',
  },
  {
    id: 'poly-12',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following can be determined from the leading term of a polynomial? Select ALL that apply.',
    options: [
      'End behavior',
      'Number of real zeros',
      'Whether degree is even or odd',
      'The sign of the function for large |x|',
    ],
    correctAnswers: [0, 2, 3],
    explanation: 'The leading term tells you: (1) end behavior — arms go up or down based on sign and degree; (2) whether the degree is even or odd — same or opposite arms; (3) the sign for large |x|. It does NOT tell you the number of real zeros — that requires more analysis.',
  },
  {
    id: 'poly-13',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'The domain of f(x) = (x + 1)/((x − 3)(x + 2)) excludes which x-values?',
    options: ['x = −1 only', 'x = 3 only', 'x = 3 and x = −2', 'x = 3, x = −2, and x = −1'],
    correctAnswers: [2],
    explanation: 'The domain of a rational function excludes values where the denominator is zero. Set (x−3)(x+2) = 0: x = 3 or x = −2. The numerator x+1 doesn\'t affect the domain. Check whether any factor cancels — since (x+1) is only in the numerator, no cancellation occurs.',
  },
  {
    id: 'poly-14',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'A polynomial of degree 5 with a positive leading coefficient: describe its end behavior.',
    options: [
      'Both ends up',
      'Both ends down',
      'Left down, right up',
      'Left up, right down',
    ],
    correctAnswers: [2],
    explanation: 'Odd degree with positive leading coefficient: left end goes DOWN (−∞ as x → −∞) and right end goes UP (+∞ as x → +∞). Think of y = x³ as the template. Flipping the leading sign swaps both arms.',
  },
  {
    id: 'poly-15',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'Which polynomial could have zeros at x = −1 (multiplicity 1), x = 2 (multiplicity 2), and a positive leading coefficient?',
    options: [
      'f(x) = (x+1)(x−2)²',
      'f(x) = −(x+1)(x−2)²',
      'f(x) = (x−1)(x+2)²',
      'f(x) = (x+1)²(x−2)',
    ],
    correctAnswers: [0],
    explanation: 'Zeros at x = −1 → factor (x+1); x = 2 with mult 2 → factor (x−2)². So f(x) = (x+1)(x−2)². The leading term comes from x · x² = x³ with coefficient 1 (positive). Option B has a negative leading coefficient. Option D has the wrong multiplicities.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Complex Numbers
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'cx-01',
    domain: 1,
    subdomain: 'Complex Numbers',
    type: 'single',
    difficulty: 'easy',
    question: 'What is i² equal to?',
    options: ['1', '−1', 'i', '0'],
    correctAnswers: [1],
    explanation: 'By definition, i = √(−1), so i² = (√(−1))² = −1. This is the foundational fact for all complex number arithmetic. Every simplification involving powers of i eventually reduces to this fact.',
  },
  {
    id: 'cx-02',
    domain: 1,
    subdomain: 'Complex Numbers',
    type: 'single',
    difficulty: 'easy',
    question: 'Simplify: (3 + 2i) + (5 − 4i)',
    options: ['8 + 2i', '8 − 2i', '2 + 6i', '8 − 6i'],
    correctAnswers: [1],
    explanation: 'Add real parts and imaginary parts separately: (3 + 5) + (2i − 4i) = 8 + (−2)i = 8 − 2i. Complex addition is like combining like terms: treat the real part and imaginary part as completely separate quantities.',
  },
  {
    id: 'cx-03',
    domain: 1,
    subdomain: 'Complex Numbers',
    type: 'single',
    difficulty: 'medium',
    question: 'Multiply: (2 + 3i)(1 − 4i)',
    options: ['2 − 12i²', '14 − 5i', '2 − 5i − 12i²', '2 + 3i − 8i − 12i²'],
    correctAnswers: [1],
    explanation: 'FOIL: (2)(1) + (2)(−4i) + (3i)(1) + (3i)(−4i) = 2 − 8i + 3i − 12i². Substitute i² = −1: 2 − 8i + 3i − 12(−1) = 2 + 12 + (−8+3)i = 14 − 5i. Always replace i² = −1 at the end.',
  },
  {
    id: 'cx-04',
    domain: 1,
    subdomain: 'Complex Numbers',
    type: 'single',
    difficulty: 'medium',
    question: 'Simplify: (3 + i)/(2 − i). (Divide by multiplying by the conjugate.)',
    options: ['(5 + 5i)/5', '1 + i', '(7 + 5i)/5', '(5 + 5i)/3'],
    correctAnswers: [1],
    explanation: 'Multiply numerator and denominator by the conjugate of the denominator, (2+i): numerator = (3+i)(2+i) = 6+3i+2i+i² = 6+5i−1 = 5+5i; denominator = (2−i)(2+i) = 4−i² = 4+1 = 5. Result: (5+5i)/5 = 1+i.',
  },
  {
    id: 'cx-05',
    domain: 1,
    subdomain: 'Complex Numbers',
    type: 'single',
    difficulty: 'easy',
    question: 'What is the complex conjugate of 4 − 7i?',
    options: ['−4 + 7i', '4 + 7i', '7 − 4i', '−4 − 7i'],
    correctAnswers: [1],
    explanation: 'The complex conjugate of a + bi is a − bi (flip the sign of the imaginary part only). So the conjugate of 4 − 7i is 4 + 7i. Multiplying a complex number by its conjugate always gives a real number: (4−7i)(4+7i) = 16 + 49 = 65.',
  },
  {
    id: 'cx-06',
    domain: 1,
    subdomain: 'Complex Numbers',
    type: 'single',
    difficulty: 'medium',
    question: 'Find the modulus (absolute value) of 3 + 4i.',
    options: ['7', '5', '25', '√7'],
    correctAnswers: [1],
    explanation: 'The modulus of a + bi is |a + bi| = √(a² + b²). For 3 + 4i: √(3² + 4²) = √(9 + 16) = √25 = 5. This is exactly a 3-4-5 right triangle — the complex number lives at the point (3, 4) in the complex plane, and 5 is the distance from the origin.',
  },
  {
    id: 'cx-07',
    domain: 1,
    subdomain: 'Complex Numbers',
    type: 'single',
    difficulty: 'medium',
    question: 'Solve x² + 9 = 0 over the complex numbers.',
    options: ['x = ±3', 'x = ±3i', 'x = ±√3i', 'No solution'],
    correctAnswers: [1],
    explanation: 'x² = −9, so x = ±√(−9) = ±√9·√(−1) = ±3i. The solutions are ±3i, a complex conjugate pair. Whenever the discriminant b²−4ac is negative, the quadratic has two non-real complex conjugate roots.',
  },
  {
    id: 'cx-08',
    domain: 1,
    subdomain: 'Complex Numbers',
    type: 'single',
    difficulty: 'hard',
    question: 'If a quadratic has real coefficients and one root is 2 + 5i, what is the other root?',
    options: ['2 + 5i', '2 − 5i', '−2 + 5i', '5 + 2i'],
    correctAnswers: [1],
    explanation: 'Complex roots of polynomials with real coefficients always come in conjugate pairs. If 2 + 5i is a root, then 2 − 5i (its conjugate) must also be a root. This is the Complex Conjugate Root Theorem — you get one root "for free" whenever you find one complex root.',
  },
  {
    id: 'cx-09',
    domain: 1,
    subdomain: 'Complex Numbers',
    type: 'single',
    difficulty: 'easy',
    question: 'Simplify i⁷.',
    options: ['1', '−1', 'i', '−i'],
    correctAnswers: [3],
    explanation: 'Powers of i cycle with period 4: i¹=i, i²=−1, i³=−i, i⁴=1, i⁵=i, … Divide the exponent by 4: 7 ÷ 4 = 1 remainder 3. So i⁷ = i³ = −i. To find any power of i, just find the remainder when dividing the exponent by 4.',
  },
  {
    id: 'cx-10',
    domain: 1,
    subdomain: 'Complex Numbers',
    type: 'single',
    difficulty: 'medium',
    question: 'Which quadratic has roots 1 + 2i and 1 − 2i?',
    options: ['x² − 2x − 5', 'x² − 2x + 5', 'x² + 2x + 5', 'x² + 5'],
    correctAnswers: [1],
    explanation: 'Sum of roots = (1+2i)+(1−2i) = 2 → coefficient of x is −2 (sum = −b/a). Product of roots = (1+2i)(1−2i) = 1−4i² = 1+4 = 5 → constant term is 5 (product = c/a). Quadratic: x² − 2x + 5. Alternatively, use conjugate pair shortcut: x² − (sum)x + (product).',
  },

  // ══════════════════════════════════════════════════════════════════
  // Exponential & Logarithmic Functions
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'el-01',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'Rewrite log₃(81) = 4 in exponential form.',
    options: ['3⁴ = 81', '81⁴ = 3', '4³ = 81', '3⁸¹ = 4'],
    correctAnswers: [0],
    explanation: 'Logarithm and exponential are inverse operations: logₐ(x) = y ↔ aʸ = x. So log₃(81) = 4 means 3⁴ = 81. Check: 3⁴ = 3×3×3×3 = 81. ✓ Practice converting between the two forms until it\'s automatic.',
  },
  {
    id: 'el-02',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'Evaluate log₂(32).',
    options: ['4', '5', '16', '6'],
    correctAnswers: [1],
    explanation: 'Ask: "2 to what power equals 32?" 2¹=2, 2²=4, 2³=8, 2⁴=16, 2⁵=32. So log₂(32) = 5. You can also write 32 = 2⁵ and read the exponent directly.',
  },
  {
    id: 'el-03',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'Expand: log(x²y/z³) using log rules.',
    options: [
      '2log x + log y − 3log z',
      '2log x − log y + 3log z',
      'log x + log y + log z',
      '2log(x) · log(y) / 3log(z)',
    ],
    correctAnswers: [0],
    explanation: 'Apply log rules: log(AB) = logA + logB; log(A/B) = logA − logB; log(Aⁿ) = n·logA. So log(x²y/z³) = log(x²) + log(y) − log(z³) = 2log x + log y − 3log z. Never multiply or divide the log expressions themselves.',
  },
  {
    id: 'el-04',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'Solve for x: 2^(x+1) = 16.',
    options: ['x = 3', 'x = 4', 'x = 5', 'x = 2'],
    correctAnswers: [0],
    explanation: 'Rewrite 16 as a power of 2: 16 = 2⁴. Then 2^(x+1) = 2⁴, so x+1 = 4, giving x = 3. When both sides can be written with the same base, just set the exponents equal. Check: 2^(3+1) = 2⁴ = 16 ✓.',
  },
  {
    id: 'el-05',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'Solve for x: log(x + 5) = 2. (Assume base 10.)',
    options: ['x = 95', 'x = 7', 'x = 20', 'x = 100'],
    correctAnswers: [0],
    explanation: 'Rewrite in exponential form: 10² = x + 5, so 100 = x + 5, giving x = 95. Always check: log(95+5) = log(100) = 2 ✓. Caution: make sure x + 5 > 0 (it is, since 95+5 = 100 > 0).',
  },
  {
    id: 'el-06',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'Solve: 3^(2x) = 7. Which answer uses change of base correctly?',
    options: [
      'x = log 7 / log 3',
      'x = log 7 / (2 · log 3)',
      'x = (log 7 · log 3) / 2',
      'x = log 21 / 2',
    ],
    correctAnswers: [1],
    explanation: 'Take log of both sides: log(3^(2x)) = log 7, so 2x · log 3 = log 7. Solve: x = log 7 / (2 · log 3). You can use natural log or log base 10 — as long as you use the same base on numerator and denominator, it simplifies correctly.',
  },
  {
    id: 'el-07',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'What is the natural logarithm (ln) — what base does it use?',
    options: ['Base 2', 'Base 10', 'Base e (≈ 2.718)', 'Base π'],
    correctAnswers: [2],
    explanation: 'The natural logarithm ln(x) uses base e, where e ≈ 2.71828… is Euler\'s number. It arises naturally in calculus, compound interest, and many growth/decay problems. ln(e) = 1, ln(1) = 0, and e^(ln x) = x for x > 0.',
  },
  {
    id: 'el-08',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'A substance decays according to A(t) = 100 · e^(−0.05t). What is the half-life?',
    options: ['About 13.9 years', 'About 20 years', 'About 5 years', 'About 50 years'],
    correctAnswers: [0],
    explanation: 'Set A(t) = 50 (half of 100): 50 = 100e^(−0.05t) → 0.5 = e^(−0.05t) → ln(0.5) = −0.05t → t = −ln(0.5)/0.05 = ln(2)/0.05 ≈ 0.6931/0.05 ≈ 13.9 years. The half-life formula is also t₁/₂ = ln2/k where k is the decay rate.',
  },
  {
    id: 'el-09',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'Which is the inverse function of f(x) = 2^x?',
    options: ['f⁻¹(x) = x/2', 'f⁻¹(x) = log₂(x)', 'f⁻¹(x) = 2/x', 'f⁻¹(x) = x²'],
    correctAnswers: [1],
    explanation: 'Exponential and logarithm are inverses of each other. If f(x) = 2^x, then f⁻¹(x) = log₂(x). You can verify: f(f⁻¹(x)) = 2^(log₂ x) = x ✓. The domain of f is all reals; the domain of f⁻¹ is x > 0.',
  },
  {
    id: 'el-10',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'Condense into a single log: 3ln(x) + ln(y) − 2ln(z).',
    options: [
      'ln(x³yz²)',
      'ln(x³y/z²)',
      'ln(3xy/2z)',
      '3ln(xy/z²)',
    ],
    correctAnswers: [1],
    explanation: 'Apply log rules in reverse: 3ln(x) = ln(x³), 2ln(z) = ln(z²). Then ln(x³) + ln(y) − ln(z²) = ln(x³y) − ln(z²) = ln(x³y/z²). The power rule, product rule, and quotient rule all run in both directions.',
  },
  {
    id: 'el-11',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'The pH scale uses pH = −log[H⁺]. If [H⁺] = 10^(−4), what is the pH?',
    options: ['−4', '0.0001', '4', '40'],
    correctAnswers: [2],
    explanation: 'pH = −log(10^(−4)) = −(−4) · log(10) = −(−4)(1) = 4. The negative sign in the pH formula means a more acidic solution (higher [H⁺]) gives a lower pH number. pH = 4 is acidic (below 7).',
  },
  {
    id: 'el-12',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are valid log rules? Select ALL that apply.',
    options: [
      'log(AB) = log A + log B',
      'log(A + B) = log A + log B',
      'log(Aⁿ) = n · log A',
      'log(A/B) = log A − log B',
    ],
    correctAnswers: [0, 2, 3],
    explanation: 'The three log rules are: product (log AB = log A + log B), power (log Aⁿ = n log A), and quotient (log A/B = log A − log B). There is NO log rule for log(A+B) — it cannot be simplified further. This is one of the most common algebra errors.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Systems & Matrices
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'mat-01',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'easy',
    question: 'What are the dimensions of a matrix with 3 rows and 4 columns?',
    options: ['4 × 3', '3 × 4', '12 × 1', '7 × 1'],
    correctAnswers: [1],
    explanation: 'Matrix dimensions are always stated as rows × columns (R × C — remember "RC Cola"). A matrix with 3 rows and 4 columns is 3 × 4. The 3 × 4 matrix has 12 entries total.',
  },
  {
    id: 'mat-02',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'easy',
    question: 'Can you add a 2×3 matrix to a 3×2 matrix?',
    options: [
      'Yes, by adding corresponding entries',
      'No — matrices must have the same dimensions to add',
      'Yes, but only if both have integer entries',
      'Yes, and the result is a 5×5 matrix',
    ],
    correctAnswers: [1],
    explanation: 'Matrix addition (and subtraction) requires the matrices to have identical dimensions — same number of rows AND columns. A 2×3 and a 3×2 both have 6 entries, but they\'re arranged differently and cannot be added. Only same-size matrices can be added.',
  },
  {
    id: 'mat-03',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'medium',
    question: 'Compute: [2  1] × [3], where [2  1] is 1×2 and [3] / [4] is 2×1.',
    options: ['[6  4]', '[10]', '[6/4]', '[8]'],
    correctAnswers: [1],
    explanation: 'A 1×2 times a 2×1 gives a 1×1 result: [2 1] × [3; 4] = 2·3 + 1·4 = 6 + 4 = 10. Matrix multiplication is rows of the left times columns of the right — "dot product" of each row with each column.',
  },
  {
    id: 'mat-04',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'medium',
    question: 'The determinant of [[2, 3], [1, 4]] is:',
    options: ['11', '5', '−5', '8'],
    correctAnswers: [1],
    explanation: 'For a 2×2 matrix [[a,b],[c,d]], det = ad − bc. Here: 2·4 − 3·1 = 8 − 3 = 5. The determinant tells you whether the matrix has an inverse (det ≠ 0 → invertible; det = 0 → singular/not invertible).',
  },
  {
    id: 'mat-05',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'medium',
    question: 'If a system of 3 equations in 3 unknowns has infinitely many solutions, what does that mean geometrically?',
    options: [
      'The three planes intersect at exactly one point',
      'The three planes have no common point',
      'At least two planes are parallel',
      'The three planes share a common line or plane (they overlap)',
    ],
    correctAnswers: [3],
    explanation: 'Infinitely many solutions means the system is dependent — the planes overlap along a line or coincide completely. "Exactly one solution" means three planes meet at a point. "No solution" means no common point (inconsistent). "At least two parallel" is usually no solution, not infinite.',
  },
  {
    id: 'mat-06',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'easy',
    question: 'What is the 2×2 identity matrix?',
    options: [
      '[[0,0],[0,0]]',
      '[[1,0],[0,1]]',
      '[[1,1],[1,1]]',
      '[[0,1],[1,0]]',
    ],
    correctAnswers: [1],
    explanation: 'The identity matrix I has 1s on the main diagonal and 0s elsewhere. For any matrix A of compatible size, AI = IA = A (it\'s the multiplicative identity for matrices). The 2×2 identity is [[1,0],[0,1]] — the analog of the number 1 for matrix multiplication.',
  },
  {
    id: 'mat-07',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'hard',
    question: 'Is matrix multiplication commutative? (Does AB always equal BA?)',
    options: [
      'Yes, always',
      'No — AB and BA are generally not equal',
      'Yes, if both matrices are square',
      'Yes, if both matrices are identity matrices',
    ],
    correctAnswers: [1],
    explanation: 'Matrix multiplication is NOT commutative in general — AB ≠ BA for most matrices. This is one of the major ways matrices differ from regular numbers. Even if both products are defined, they can give different results. Exception: a matrix times its inverse, or a matrix times I.',
  },
  {
    id: 'mat-08',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'medium',
    question: 'When solving the system x + y + z = 6, 2x − y + z = 3, x + 2y − z = 2, what method puts the augmented matrix into row echelon form?',
    options: ['Cramer\'s Rule', 'Gaussian Elimination', 'The Quadratic Formula', 'Synthetic Division'],
    correctAnswers: [1],
    explanation: 'Gaussian elimination uses elementary row operations (swap rows, multiply a row by a constant, add a multiple of one row to another) to convert an augmented matrix [A|b] into row echelon form (upper-triangular), then back-substitutes to find the solution.',
  },
  {
    id: 'mat-09',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'medium',
    question: 'The system Ax = b has a unique solution when:',
    options: [
      'det(A) = 0',
      'det(A) ≠ 0',
      'A is a rectangular matrix',
      'b is the zero vector',
    ],
    correctAnswers: [1],
    explanation: 'A square matrix A is invertible (and Ax = b has a unique solution) if and only if det(A) ≠ 0. When det(A) = 0, the matrix is singular — the system either has no solution or infinitely many. Non-zero determinant ↔ invertible ↔ unique solution.',
  },
  {
    id: 'mat-10',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'hard',
    question: 'Solve the system by substitution: y = 3x − 1 and 2x + y = 14. Find x.',
    options: ['x = 2', 'x = 3', 'x = 4', 'x = 1'],
    correctAnswers: [1],
    explanation: 'Substitute y = 3x − 1 into 2x + y = 14: 2x + (3x − 1) = 14 → 5x − 1 = 14 → 5x = 15 → x = 3. Check: y = 3(3) − 1 = 8, and 2(3) + 8 = 14 ✓. Substitution works best when one equation is already solved for a variable (here, y) — just plug it into the other equation and solve the resulting one-variable equation.',
  },
  {
    id: 'mat-11',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'medium',
    question: 'Multiply scalar 3 times matrix [[1, −2], [0, 4]].',
    options: ['[[3, −6], [0, 12]]', '[[3, −2], [0, 4]]', '[[4, 1], [3, 7]]', '[[1/3, −2/3], [0, 4/3]]'],
    correctAnswers: [0],
    explanation: 'Scalar multiplication: multiply every entry in the matrix by the scalar. 3 × [[1, −2], [0, 4]] = [[3·1, 3·(−2)], [3·0, 3·4]] = [[3, −6], [0, 12]]. This is straightforward — just distribute the scalar to each element.',
  },
  {
    id: 'mat-12',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'easy',
    question: 'If matrix A is 2×3 and matrix B is 3×4, what are the dimensions of AB?',
    options: ['3×3', '2×4', '3×4', '6×12'],
    correctAnswers: [1],
    explanation: 'For AB to be defined, the inner dimensions must match: A is (2×3) and B is (3×4) — the inner 3s match. The result has dimensions equal to the outer dimensions: 2×4. Memory trick: (rows of A) × (columns of B) = dimensions of AB.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Conic Sections
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'con-01',
    domain: 1,
    subdomain: 'Conic Sections',
    type: 'single',
    difficulty: 'easy',
    question: 'Which equation represents a circle centered at (3, −2) with radius 5?',
    options: [
      '(x+3)² + (y−2)² = 5',
      '(x−3)² + (y+2)² = 25',
      '(x−3)² + (y−2)² = 5',
      '(x+3)² + (y+2)² = 25',
    ],
    correctAnswers: [1],
    explanation: 'Standard circle: (x−h)² + (y−k)² = r². Center (h,k) = (3, −2), r = 5 so r² = 25. Plug in: (x−3)² + (y−(−2))² = 25, which is (x−3)² + (y+2)² = 25. Note: the signs inside the parentheses are opposite to the center coordinates.',
  },
  {
    id: 'con-02',
    domain: 1,
    subdomain: 'Conic Sections',
    type: 'single',
    difficulty: 'easy',
    question: 'What shape does the equation (x−1)²/9 + (y+2)²/4 = 1 represent?',
    options: ['Circle', 'Parabola', 'Ellipse', 'Hyperbola'],
    correctAnswers: [2],
    explanation: 'Standard ellipse form: (x−h)²/a² + (y−k)²/b² = 1, with PLUS between the fractions. This is an ellipse centered at (1, −2) with a² = 9 (a = 3) and b² = 4 (b = 2). A circle is a special ellipse where a = b. A hyperbola has a MINUS sign.',
  },
  {
    id: 'con-03',
    domain: 1,
    subdomain: 'Conic Sections',
    type: 'single',
    difficulty: 'medium',
    question: 'For the hyperbola (x−2)²/16 − (y+1)²/9 = 1, what are the asymptote equations?',
    options: [
      'y + 1 = ±(3/4)(x − 2)',
      'y + 1 = ±(4/3)(x − 2)',
      'y − 2 = ±(3/4)(x + 1)',
      'y = ±(3/4)x',
    ],
    correctAnswers: [0],
    explanation: 'Hyperbola (x−h)²/a² − (y−k)²/b² = 1 has asymptotes y − k = ±(b/a)(x − h). Here h=2, k=−1, a=4, b=3. Asymptotes: y − (−1) = ±(3/4)(x − 2), i.e., y + 1 = ±(3/4)(x − 2). Note b/a (not a/b) because b goes with y and a goes with x.',
  },
  {
    id: 'con-04',
    domain: 1,
    subdomain: 'Conic Sections',
    type: 'single',
    difficulty: 'medium',
    question: 'For the parabola y = 2(x − 1)² + 3, what is the vertex?',
    options: ['(1, 3)', '(−1, 3)', '(1, −3)', '(2, 3)'],
    correctAnswers: [0],
    explanation: 'Vertex form of a parabola is y = a(x − h)² + k, where (h, k) is the vertex. Here a = 2, h = 1, k = 3, so the vertex is (1, 3). Since a = 2 > 0, the parabola opens upward and the vertex is a minimum.',
  },
  {
    id: 'con-05',
    domain: 1,
    subdomain: 'Conic Sections',
    type: 'single',
    difficulty: 'hard',
    question: 'Rewrite x² + 6x + y² − 4y = 12 in standard form by completing the square.',
    options: [
      '(x+3)² + (y−2)² = 25',
      '(x+3)² + (y−2)² = 1',
      '(x−3)² + (y+2)² = 25',
      '(x+3)² + (y+2)² = 25',
    ],
    correctAnswers: [0],
    explanation: 'Complete the square for x: x²+6x → (x+3)²−9. For y: y²−4y → (y−2)²−4. So (x+3)²−9 + (y−2)²−4 = 12 → (x+3)² + (y−2)² = 12+9+4 = 25. This is a circle centered at (−3, 2) with radius 5.',
  },
  {
    id: 'con-06',
    domain: 1,
    subdomain: 'Conic Sections',
    type: 'single',
    difficulty: 'medium',
    question: 'For an ellipse with a² = 25 and b² = 16 (a > b), the relationship c² = a² − b² gives c² = ?',
    options: ['41', '9', '400', '3'],
    correctAnswers: [1],
    explanation: 'For an ellipse, c² = a² − b² = 25 − 16 = 9, so c = 3. The foci are located c units from the center along the major axis. The key relationship to remember: a² = b² + c² for an ellipse (a is largest). Compare to a hyperbola where c² = a² + b².',
  },
  {
    id: 'con-07',
    domain: 1,
    subdomain: 'Conic Sections',
    type: 'single',
    difficulty: 'easy',
    question: 'A satellite dish is shaped like a paraboloid. The receiver should be placed at the:',
    options: ['Vertex', 'Directrix', 'Focus', 'Center of the circle'],
    correctAnswers: [2],
    explanation: 'The key reflective property of a parabola: parallel rays hitting the parabola all reflect to the focus. Satellite dishes are parabolic so all incoming signals (which are essentially parallel rays from space) converge at the focus — where the receiver is placed.',
  },
  {
    id: 'con-08',
    domain: 1,
    subdomain: 'Conic Sections',
    type: 'single',
    difficulty: 'hard',
    question: 'Which equation represents a hyperbola that opens left and right (horizontal transverse axis)?',
    options: [
      'x²/4 + y²/9 = 1',
      'y²/4 − x²/9 = 1',
      'x²/4 − y²/9 = 1',
      '(x−1)²/4 + (y+2)²/9 = 1',
    ],
    correctAnswers: [2],
    explanation: 'A hyperbola opening left and right has x² first with a MINUS sign: x²/a² − y²/b² = 1. This is because the x-intercepts (vertices) are the only real intercepts, and the hyperbola opens toward them. If y² is first with the minus, the hyperbola opens up and down.',
  },
  {
    id: 'con-09',
    domain: 1,
    subdomain: 'Conic Sections',
    type: 'single',
    difficulty: 'medium',
    question: 'For a downward-opening parabola, which vertex form is correct if the vertex is at (0, 5)?',
    options: [
      'y = (x − 0)² + 5',
      'y = −(x − 0)² + 5',
      'x = −(y − 5)² + 0',
      'y = (x − 5)² + 0',
    ],
    correctAnswers: [1],
    explanation: 'A downward-opening parabola has a negative "a" value in y = a(x − h)² + k. With vertex (0, 5) and a < 0, the equation is y = −(x − 0)² + 5 = −x² + 5. The negative coefficient flips the parabola downward from the vertex.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Sequences & Series
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'seq-01',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'easy',
    question: 'In the arithmetic sequence 3, 7, 11, 15, …, what is the common difference?',
    options: ['3', '4', '7', '11'],
    correctAnswers: [1],
    explanation: 'The common difference d in an arithmetic sequence is found by subtracting any term from the next: 7 − 3 = 4, 11 − 7 = 4, 15 − 11 = 4. The common difference is constant — that\'s what makes it arithmetic.',
  },
  {
    id: 'seq-02',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'easy',
    question: 'Find the 10th term of the arithmetic sequence with a₁ = 5 and d = 3.',
    options: ['27', '30', '32', '35'],
    correctAnswers: [2],
    explanation: 'Arithmetic nth term formula: aₙ = a₁ + (n−1)d. For n=10: a₁₀ = 5 + (10−1)(3) = 5 + 27 = 32. The formula adds (n−1) copies of d because you start at a₁ and step forward n−1 times.',
  },
  {
    id: 'seq-03',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'medium',
    question: 'Find the sum of the first 20 terms of the arithmetic sequence 2, 5, 8, 11, …',
    options: ['590', '610', '620', '640'],
    correctAnswers: [1],
    explanation: 'First find a₂₀: a₂₀ = 2 + (19)(3) = 2 + 57 = 59. Then Sₙ = n(a₁ + aₙ)/2 = 20(2 + 59)/2 = 20(61)/2 = 10(61) = 610. Arithmetic series sum is always (number of terms) × (average of first and last term). For long sequences this beats adding term by term.',
  },
  {
    id: 'seq-04',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'easy',
    question: 'What is the common ratio of the geometric sequence 2, 6, 18, 54, …?',
    options: ['2', '3', '4', '6'],
    correctAnswers: [1],
    explanation: 'In a geometric sequence, the common ratio r = any term ÷ the previous term. Here: 6/2 = 3, 18/6 = 3, 54/18 = 3. The ratio is constant at r = 3. Each term is 3 times the previous one.',
  },
  {
    id: 'seq-05',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'medium',
    question: 'Find the 6th term of the geometric sequence with a₁ = 3 and r = 2.',
    options: ['48', '96', '192', '32'],
    correctAnswers: [1],
    explanation: 'Geometric nth term formula: aₙ = a₁ · rⁿ⁻¹. For n=6: a₆ = 3 · 2^(6−1) = 3 · 2⁵ = 3 · 32 = 96.',
  },
  {
    id: 'seq-06',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'hard',
    question: 'An infinite geometric series has a₁ = 12 and r = 1/3. What is its sum?',
    options: ['36', '18', '24', 'The series diverges'],
    correctAnswers: [1],
    explanation: 'Infinite geometric series sum: S = a₁/(1−r) when |r| < 1. Here |1/3| < 1, so the series converges: S = 12/(1 − 1/3) = 12/(2/3) = 12 · (3/2) = 18. If |r| ≥ 1, the series diverges (grows without bound).',
  },
  {
    id: 'seq-07',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'medium',
    question: 'What is the 4th term in the expansion of (x + 2)⁵ using the Binomial Theorem?',
    options: ['80x²', '40x³', '80x³', '80x²·2'],
    correctAnswers: [0],
    explanation: 'Binomial Theorem: (a+b)ⁿ = Σ C(n,k)·aⁿ⁻ᵏ·bᵏ. The kth term (starting k=0) is C(5,k)x^(5−k)·2^k. The 4th term uses k=3: C(5,3)·x^(5−3)·2³ = 10·x²·8 = 80x². (C(5,3) = 10.)',
  },
  {
    id: 'seq-08',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'medium',
    question: 'Write using sigma notation: 3 + 6 + 9 + 12 + 15.',
    options: [
      'Σ(k=1 to 5) 3k',
      'Σ(k=1 to 5) k + 3',
      'Σ(k=0 to 4) 3k',
      'Σ(k=1 to 15) k',
    ],
    correctAnswers: [0],
    explanation: 'The terms 3, 6, 9, 12, 15 are multiples of 3: 3(1), 3(2), 3(3), 3(4), 3(5). So the sum is Σ(k=1 to 5) 3k. Check: when k=1, 3(1)=3; k=5, 3(5)=15 ✓. Sigma notation compresses repetitive sums elegantly.',
  },
  {
    id: 'seq-09',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'hard',
    question: 'For the geometric series 1 + r + r² + r³ + … to converge to a finite sum, what must be true?',
    options: ['r > 1', 'r = 1', '|r| < 1', 'r > 0'],
    correctAnswers: [2],
    explanation: 'The infinite geometric series Σrⁿ converges if and only if |r| < 1 (the absolute value of the common ratio is strictly less than 1). When |r| ≥ 1, successive terms don\'t shrink, so the sum grows without bound (diverges). When |r| < 1, sum = a₁/(1−r).',
  },
  {
    id: 'seq-10',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'medium',
    question: 'Evaluate Σ(k=1 to 5) (2k − 1).',
    options: ['15', '20', '25', '30'],
    correctAnswers: [2],
    explanation: 'Substitute k = 1, 2, 3, 4, 5: (2·1−1)+(2·2−1)+(2·3−1)+(2·4−1)+(2·5−1) = 1+3+5+7+9 = 25. These are the first 5 odd numbers, and their sum = 5² = 25 (a useful pattern: sum of first n odd numbers = n²).',
  },

  // ══════════════════════════════════════════════════════════════════
  // Statistics & Probability
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'sp-01',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'easy',
    question: 'In a normal distribution, approximately what percent of data falls within 1 standard deviation of the mean?',
    options: ['50%', '68%', '95%', '99.7%'],
    correctAnswers: [1],
    explanation: 'The empirical rule (68-95-99.7 rule): within 1 SD of the mean ≈ 68%, within 2 SDs ≈ 95%, within 3 SDs ≈ 99.7%. These percentages describe the normal (bell) curve and apply approximately to any data that is approximately normally distributed.',
  },
  {
    id: 'sp-02',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'easy',
    question: 'A z-score of −2.0 means the data value is:',
    options: [
      '2 units above the mean',
      '2 units below the mean',
      '2 standard deviations above the mean',
      '2 standard deviations below the mean',
    ],
    correctAnswers: [3],
    explanation: 'Z-score = (x − μ)/σ measures how many standard deviations from the mean a value is. Negative z-score → below the mean. z = −2.0 means the value is exactly 2 standard deviations below the mean. The unit is "standard deviations," not "units."',
  },
  {
    id: 'sp-03',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'medium',
    question: 'How many ways can you arrange 4 books on a shelf from a collection of 7? (Order matters.)',
    options: ['28', '35', '840', '5040'],
    correctAnswers: [2],
    explanation: '₇P₄ = 7!/(7−4)! = 7!/3! = 7×6×5×4 = 840. Permutation because ORDER MATTERS (different arrangements count as different). If order didn\'t matter (combination), it would be ₇C₄ = 35. Memory trick: Permutation has "P" for position — where you put things matters.',
  },
  {
    id: 'sp-04',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'medium',
    question: 'A committee of 3 is chosen from 8 people. How many ways can this be done? (Order does NOT matter.)',
    options: ['24', '56', '336', '512'],
    correctAnswers: [1],
    explanation: '₈C₃ = 8!/(3!·5!) = (8×7×6)/(3×2×1) = 336/6 = 56. Combination because ORDER DOESN\'T MATTER — {Alice, Bob, Carol} is the same committee as {Carol, Alice, Bob}. C always gives a smaller number than P for the same n and r.',
  },
  {
    id: 'sp-05',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'medium',
    question: 'P(A|B) = 0.4 and P(B) = 0.5. Find P(A and B).',
    options: ['0.2', '0.8', '0.9', '0.1'],
    correctAnswers: [0],
    explanation: 'Conditional probability formula: P(A|B) = P(A∩B)/P(B). Rearrange: P(A∩B) = P(A|B)·P(B) = 0.4 × 0.5 = 0.2. The intersection (both A and B) is found by multiplying the conditional probability by the conditioning event\'s probability.',
  },
  {
    id: 'sp-06',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'medium',
    question: 'Events A and B are independent if and only if:',
    options: [
      'P(A ∩ B) = P(A) + P(B)',
      'P(A|B) = P(B)',
      'P(A ∩ B) = P(A)·P(B)',
      'P(A ∪ B) = 1',
    ],
    correctAnswers: [2],
    explanation: 'Two events are independent when knowing one occurred doesn\'t change the probability of the other: P(A|B) = P(A), which is equivalent to P(A∩B) = P(A)·P(B). This multiplication rule is the standard test for independence. Mutually exclusive events (can\'t both occur) are generally NOT independent.',
  },
  {
    id: 'sp-07',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'medium',
    question: 'A fair coin is flipped 5 times. What is the probability of getting exactly 3 heads?',
    options: ['1/8', '5/16', '3/16', '3/32'],
    correctAnswers: [1],
    explanation: 'Binomial probability: P(X=k) = C(n,k)pᵏ(1−p)ⁿ⁻ᵏ. Here n=5, k=3, p=1/2. P(X=3) = C(5,3)(1/2)³(1/2)² = 10·(1/8)·(1/4) = 10/32 = 5/16.',
  },
  {
    id: 'sp-08',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'hard',
    question: 'Which scatter plot description indicates a strong positive linear correlation?',
    options: [
      'r = −0.95',
      'r = 0.12',
      'r = 0.89',
      'r = −0.05',
    ],
    correctAnswers: [2],
    explanation: 'The correlation coefficient r ranges from −1 to +1. Positive → positive slope. |r| close to 1 → strong linear relationship. r = 0.89 is positive and close to 1, indicating a strong positive linear correlation. r = −0.95 is strong but NEGATIVE. r near 0 means weak or no linear correlation.',
  },
  {
    id: 'sp-09',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'easy',
    question: 'The expected value E(X) of a discrete random variable is:',
    options: [
      'The value that occurs most often',
      'The middle value when sorted',
      'The sum of each outcome times its probability: Σ x·P(x)',
      'The maximum possible value',
    ],
    correctAnswers: [2],
    explanation: 'Expected value E(X) = Σ x·P(x) — each outcome multiplied by its probability, all added up. It\'s a "probability-weighted average." If X = {1, 2, 3} with equal probabilities 1/3 each, E(X) = 1(1/3)+2(1/3)+3(1/3) = 2. Expected value may not be a possible outcome.',
  },
  {
    id: 'sp-10',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'medium',
    question: 'The z-score for a value of 80 in a distribution with mean 70 and standard deviation 5 is:',
    options: ['1', '2', '10', '0.5'],
    correctAnswers: [1],
    explanation: 'z = (x − μ)/σ = (80 − 70)/5 = 10/5 = 2. A z-score of 2 means 80 is exactly 2 standard deviations above the mean. By the empirical rule, only about 2.5% of data falls above z = 2 in a normal distribution.',
  },
  {
    id: 'sp-11',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'hard',
    question: 'A binomial experiment with n = 10 and p = 0.3. What is the mean and standard deviation?',
    options: [
      'μ = 3, σ = √2.1',
      'μ = 3, σ = 2.1',
      'μ = 0.3, σ = √3',
      'μ = 7, σ = √2.1',
    ],
    correctAnswers: [0],
    explanation: 'Binomial distribution: μ = np = 10(0.3) = 3. σ = √(np(1−p)) = √(10·0.3·0.7) = √2.1 ≈ 1.449. The mean is the expected number of successes; the standard deviation measures how much variation to expect around that mean.',
  },
  {
    id: 'sp-12',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are properties of the normal distribution? Select ALL that apply.',
    options: [
      'Symmetric about the mean',
      'Mean, median, and mode are equal',
      'The tails touch the x-axis at ±3σ',
      'Total area under the curve equals 1',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'Normal distribution properties: (1) symmetric about the mean — left half mirrors right half; (2) mean = median = mode (all at the center); (3) total area = 1 (all probabilities sum to 100%); (4) the tails are ASYMPTOTIC — they approach but never touch the x-axis. So option C is false.',
  },
  {
    id: 'sp-13',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'easy',
    question: 'How many different 3-digit codes can be formed using digits 0–9 if repetition is allowed?',
    options: ['27', '720', '1000', '30'],
    correctAnswers: [2],
    explanation: 'By the Fundamental Counting Principle: 10 choices for each digit × 10 × 10 = 1000. From 000 to 999, there are exactly 1000 different codes. When repetition is allowed, use the counting principle. When not allowed, use permutations.',
  },
  {
    id: 'sp-14',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'hard',
    question: 'P(A) = 0.5, P(B) = 0.4, and A and B are mutually exclusive. Find P(A ∪ B).',
    options: ['0.7', '0.9', '0.2', '1.0'],
    correctAnswers: [1],
    explanation: 'For mutually exclusive events, P(A ∩ B) = 0, so the addition rule simplifies: P(A ∪ B) = P(A) + P(B) = 0.5 + 0.4 = 0.9. Mutually exclusive means they cannot both occur. If they could overlap, we\'d need P(A ∪ B) = P(A) + P(B) − P(A ∩ B).',
  },
  {
    id: 'sp-15',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'medium',
    question: 'The correlation coefficient r = 0 indicates:',
    options: [
      'A perfect positive linear relationship',
      'No relationship of any kind',
      'No linear relationship (but there could be a non-linear one)',
      'A perfect negative linear relationship',
    ],
    correctAnswers: [2],
    explanation: 'r = 0 means there is no LINEAR relationship between the variables. However, a strong non-linear relationship (like a perfect U-shape or circle) can still exist with r = 0. Always look at a scatter plot in addition to calculating r — correlation only captures linear patterns.',
  },

  // ── Additional Polynomial & Rational Functions ────────────────────
  {
    id: 'poly-16',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'A polynomial p(x) has p(3) = 0. Which of the following must be true?',
    options: ['3 is the leading coefficient', '(x − 3) is a factor of p(x)', 'x = −3 is also a zero', 'The degree of p(x) is 3'],
    correctAnswers: [1],
    explanation: 'By the Factor Theorem, if p(a) = 0 then (x − a) is a factor. So p(3) = 0 means (x − 3) is a factor of p(x). The other statements are not necessarily true — complex conjugate root theorem requires real coefficients and a complex root, and the degree is independent of any specific zero.',
  },
  {
    id: 'poly-17',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'The rational function f(x) = (x² − 9) / (x² − 3x) in simplified form has:',
    options: [
      'A vertical asymptote at x = 0 and a hole at x = 3',
      'A vertical asymptote at x = 3 and a hole at x = 0',
      'Vertical asymptotes at x = 0 and x = 3, no holes',
      'A hole at x = 0 and a hole at x = 3',
    ],
    correctAnswers: [0],
    explanation: 'Factor: numerator = (x−3)(x+3); denominator = x(x−3). The (x−3) cancels → HOLE at x = 3. The remaining denominator factor x gives a vertical asymptote at x = 0. Always factor and cancel before identifying holes vs asymptotes.',
  },
  {
    id: 'poly-18',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'yesno',
    difficulty: 'easy',
    question: 'A polynomial of degree 4 with a positive leading coefficient has end behavior: both ends go up (y → +∞ as x → ±∞). True or False?',
    options: ['True', 'False'],
    correctAnswers: [0],
    explanation: 'Even degree (4) with positive leading coefficient: both arms point upward. Think of y = x⁴ as the model — as x → +∞ or x → −∞, x⁴ → +∞. If the leading coefficient were negative, both arms would go down.',
  },

  // ── Additional Complex Numbers ────────────────────────────────────
  {
    id: 'cx-11',
    domain: 1,
    subdomain: 'Complex Numbers',
    type: 'single',
    difficulty: 'medium',
    question: 'What is (3 + 2i)(3 − 2i)?',
    options: ['5', '9 − 4i²', '13', '1 + 12i'],
    correctAnswers: [2],
    explanation: '(3 + 2i)(3 − 2i) = 9 − 6i + 6i − 4i² = 9 − 4(−1) = 9 + 4 = 13. The product of a complex number and its conjugate is always real: (a+bi)(a−bi) = a² + b². Here 3² + 2² = 9 + 4 = 13.',
  },
  {
    id: 'cx-12',
    domain: 1,
    subdomain: 'Complex Numbers',
    type: 'single',
    difficulty: 'hard',
    question: 'A degree-4 polynomial with real coefficients has roots 2 and 1 + 3i. How many total roots does it have, and what is another guaranteed root?',
    options: [
      '3 roots total; −2 is a root',
      '4 roots total; 1 − 3i is a root',
      '4 roots total; −1 + 3i is a root',
      '2 roots total; the polynomial is fully factored',
    ],
    correctAnswers: [1],
    explanation: 'A degree-4 polynomial has exactly 4 roots (counting multiplicity) by the Fundamental Theorem of Algebra. By the Complex Conjugate Root Theorem, if 1 + 3i is a root of a real-coefficient polynomial, then its conjugate 1 − 3i must also be a root. The four roots are 2, some fourth root, 1 + 3i, and 1 − 3i.',
  },

  // ── Additional Exponential & Logarithmic Functions ────────────────
  {
    id: 'el-13',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'Solve for x: log₂(x) + log₂(x − 2) = 3',
    options: ['x = 4', 'x = −1 or x = 3', 'x = 4 only (x = −1 is extraneous)', 'x = 8'],
    correctAnswers: [2],
    explanation: 'Combine logs: log₂[x(x−2)] = 3 → x(x−2) = 2³ = 8 → x² − 2x − 8 = 0 → (x−4)(x+2) = 0 → x = 4 or x = −2. Check: log₂(−2) is undefined, so x = −2 is extraneous. Only x = 4 is valid. Always check for extraneous solutions in log equations.',
  },
  {
    id: 'el-14',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'Which property of logarithms states that log_b(M/N) = log_b(M) − log_b(N)?',
    options: ['Product rule', 'Quotient rule', 'Power rule', 'Change of base rule'],
    correctAnswers: [1],
    explanation: 'The quotient rule: log_b(M/N) = log_b(M) − log_b(N). It mirrors exponent rules — dividing means subtracting exponents, so logs of quotients subtract. The product rule adds logs, and the power rule moves exponents to coefficients.',
  },
  {
    id: 'el-15',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'yesno',
    difficulty: 'medium',
    question: 'Is the function f(x) = (1/3)ˣ an example of exponential decay?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes — when the base b satisfies 0 < b < 1 (here b = 1/3), the exponential function decreases as x increases. As x → +∞, (1/3)ˣ → 0. As x → −∞, (1/3)ˣ → +∞. The graph falls from left to right: exponential decay.',
  },

  // ── Additional Systems & Matrices ─────────────────────────────────
  {
    id: 'sm-13',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'medium',
    question: 'A 2×2 matrix A has det(A) = 0. What does this tell you about the system Ax = b?',
    options: [
      'The system has exactly one solution',
      'The system has no solution',
      'The system has either no solution or infinitely many solutions (no unique solution)',
      'The system always has infinitely many solutions',
    ],
    correctAnswers: [2],
    explanation: 'det(A) = 0 means A is singular — it has no inverse. A singular matrix means the rows are linearly dependent (parallel or identical lines in 2D). The system either has no solution (parallel lines that never intersect) or infinitely many (the same line twice). You need to examine the augmented matrix to determine which.',
  },
  {
    id: 'sm-14',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'easy',
    question: 'To multiply two matrices A and B (AB), what condition on their dimensions must be satisfied?',
    options: [
      'A and B must both be square matrices',
      'The number of columns in A must equal the number of rows in B',
      'A and B must have the same dimensions',
      'The number of rows in A must equal the number of columns in B',
    ],
    correctAnswers: [1],
    explanation: 'For matrix multiplication AB, if A is m×n and B is p×q, then n must equal p. The result is m×q. Remember: inner dimensions must match, outer dimensions give the result size. An easy check: (3×2)(2×5) → inner 2s match → result is 3×5.',
  },
  {
    id: 'sm-15',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'hard',
    question: 'Using Cramer\'s Rule for the system: x + 2y = 5 and 3x + y = 7, what is x?',
    options: ['x = 1', 'x = 9/5', 'x = 3', 'x = 7/5'],
    correctAnswers: [1],
    explanation: 'det(A) = (1)(1) − (2)(3) = 1 − 6 = −5. For x: det(Aₓ) = (5)(1) − (2)(7) = 5 − 14 = −9. x = det(Aₓ)/det(A) = −9/−5 = 9/5. (Check: y = det(Aᵧ)/det(A) = [(1)(7)−(5)(3)]/(−5) = (7−15)/(−5) = 8/5.)',
  },

  // ── Additional Conic Sections ─────────────────────────────────────
  {
    id: 'con-10',
    domain: 1,
    subdomain: 'Conic Sections',
    type: 'single',
    difficulty: 'easy',
    question: 'The equation x²/25 + y²/9 = 1 describes which conic section?',
    options: ['Circle', 'Ellipse', 'Parabola', 'Hyperbola'],
    correctAnswers: [1],
    explanation: 'This is the standard form of an ellipse: x²/a² + y²/b² = 1 with a = 5 (semi-major along x) and b = 3 (semi-minor along y). A circle would require equal denominators (a² = b²). A hyperbola would have subtraction. A parabola has only one squared variable.',
  },
  {
    id: 'con-11',
    domain: 1,
    subdomain: 'Conic Sections',
    type: 'single',
    difficulty: 'medium',
    question: 'The parabola y² = 8x opens in which direction, and what is its focus?',
    options: [
      'Opens right; focus at (2, 0)',
      'Opens left; focus at (−2, 0)',
      'Opens up; focus at (0, 2)',
      'Opens right; focus at (8, 0)',
    ],
    correctAnswers: [0],
    explanation: 'y² = 4px with p > 0 opens to the right. Here 4p = 8, so p = 2. The focus is at (p, 0) = (2, 0). The directrix is x = −2. Think of p as the distance from the vertex (origin) to the focus. Since p > 0 and the y-variable is squared, it opens right.',
  },
  {
    id: 'con-12',
    domain: 1,
    subdomain: 'Conic Sections',
    type: 'yesno',
    difficulty: 'medium',
    question: 'The equation x² − y² = 16 represents a hyperbola. True or False?',
    options: ['True', 'False'],
    correctAnswers: [0],
    explanation: 'True. Rewrite as x²/16 − y²/16 = 1, which is the standard form of a hyperbola with a² = b² = 16. The defining feature of a hyperbola is the subtraction of the two squared terms. The two vertices are at (±4, 0) and the transverse axis lies along the x-axis.',
  },

  // ── Additional Sequences & Series ─────────────────────────────────
  {
    id: 'seq-11',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'easy',
    question: 'Find the sum of the first 10 terms of the arithmetic sequence: 3, 7, 11, 15, …',
    options: ['210', '220', '195', '103'],
    correctAnswers: [0],
    explanation: 'a₁ = 3, d = 4, n = 10. Sum = n/2 · (2a₁ + (n−1)d) = 10/2 · (6 + 36) = 5 · 42 = 210. Alternatively, Sₙ = n(a₁+aₙ)/2: a₁₀ = 3 + 9·4 = 39, so S₁₀ = 10(3+39)/2 = 10·21 = 210.',
  },
  {
    id: 'seq-12',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'medium',
    question: 'Does the infinite geometric series 5 + 5/2 + 5/4 + 5/8 + … converge? If so, what is its sum?',
    options: [
      'Diverges because the series grows',
      'Converges to 10',
      'Converges to 5',
      'Converges to 7.5',
    ],
    correctAnswers: [1],
    explanation: 'The common ratio r = (5/2)/5 = 1/2. Since |r| = 0.5 < 1, the series converges. Sum = a₁/(1−r) = 5/(1−1/2) = 5/(1/2) = 10. The infinite sum converges because each term is half the previous one, so the total approaches but never exceeds 10.',
  },
  {
    id: 'seq-13',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'hard',
    question: 'Expand (2x − 3)⁴ using the Binomial Theorem. What is the coefficient of the x² term?',
    options: ['54', '216', '−216', '216x²'],
    correctAnswers: [1],
    explanation: 'The x² term comes from k = 2: C(4,2)·(2x)²·(−3)² = 6 · 4x² · 9 = 216x². So the coefficient is 216. In the Binomial Theorem, (a+b)ⁿ = Σ C(n,k)·aⁿ⁻ᵏ·bᵏ. Here a=2x, b=−3, n=4, and the k=2 term gives the x² coefficient.',
  },

  // ── Additional Polynomial & Rational Functions ─────────────────────
  {
    id: 'prf-19',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'The polynomial p(x) = x³ − 6x² + 11x − 6 has zeros at x = 1, x = 2, and x = 3. What is the factored form of p(x)?',
    options: ['(x−1)(x−2)(x−3)', '(x+1)(x+2)(x+3)', '(x−1)(x−2)(x+3)', 'x(x−2)(x−3)'],
    correctAnswers: [0],
    explanation: 'If r is a zero of a polynomial, then (x − r) is a factor (Factor Theorem). Zeros at x = 1, 2, and 3 give factors (x−1), (x−2), and (x−3). Multiplying: (x−1)(x−2) = x²−3x+2; then (x²−3x+2)(x−3) = x³−6x²+11x−6 ✓. The leading coefficient of the original polynomial is 1, so no additional scalar factor is needed to produce the correct polynomial.',
  },
  {
    id: 'prf-20',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'What is the horizontal asymptote of f(x) = (3x³ − 2x + 5) / (x³ + 4x²)?',
    options: ['y = 0', 'y = 3', 'y = 5/4', 'No horizontal asymptote'],
    correctAnswers: [1],
    explanation: 'When the degrees of numerator and denominator are equal (both degree 3 here), the horizontal asymptote is y = (leading coefficient of numerator) / (leading coefficient of denominator) = 3/1 = 3. The lower-degree terms become negligible as x → ±∞ compared to the leading x³ terms. So f(x) → 3x³/x³ = 3 as x → ±∞. If deg(num) < deg(den): HA is y=0. If deg(num) = deg(den): HA is ratio of leading coefficients. If deg(num) > deg(den): no HA (oblique or polynomial asymptote instead).',
  },
  {
    id: 'prf-21',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'When p(x) is divided by (x + 2), the remainder is −5. What is p(−2)?',
    options: ['5', '−5', '2', 'Cannot be determined'],
    correctAnswers: [1],
    explanation: 'The Remainder Theorem states: when p(x) is divided by (x − a), the remainder equals p(a). Dividing by (x + 2) = (x − (−2)) means a = −2. Therefore the remainder = p(−2) = −5. This theorem lets you evaluate polynomials at a specific value using synthetic division — just divide and read the remainder — rather than substituting directly. No additional information about p(x) is needed; the remainder is completely determined.',
  },
  {
    id: 'prf-22',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'yesno',
    difficulty: 'easy',
    question: 'True or False: A polynomial of degree 5 with real coefficients can have exactly 3 real zeros and 2 complex zeros.',
    options: ['True', 'False'],
    correctAnswers: [0],
    explanation: 'True. The Fundamental Theorem of Algebra guarantees exactly 5 zeros in the complex numbers (counting multiplicity). Complex zeros of polynomials with real coefficients come in conjugate pairs. So a degree-5 polynomial can have 5, 3, or 1 real zeros (the remaining 0, 2, or 4 are complex conjugate pairs). Having 3 real zeros and 1 conjugate pair of complex zeros (= 2 complex zeros) is valid: 3 + 2 = 5 ✓. You cannot have 4 real and 1 complex without a paired conjugate.',
  },

  // ── Additional Exponential & Logarithmic Functions ────────────────
  {
    id: 'elf-16',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'Solve: log₃(x − 1) + log₃(x − 3) = 1',
    options: ['x = 4', 'x = 0', 'x = 4 and x = 0', 'No solution'],
    correctAnswers: [0],
    explanation: 'Product rule: log₃((x−1)(x−3)) = 1 → (x−1)(x−3) = 3¹ = 3 → x²−4x+3 = 3 → x²−4x = 0 → x(x−4) = 0 → x = 0 or x = 4. Check: x = 0 gives log₃(−1) — undefined (negative argument). x = 4 gives log₃(3) + log₃(1) = 1 + 0 = 1 ✓. So x = 4 is the only valid solution. Always check logarithmic equation solutions by substituting back into the ORIGINAL equation to identify extraneous solutions.',
  },
  {
    id: 'elf-17',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'An investment doubles in value every 12 years. What is the approximate annual growth rate?',
    options: ['About 5.8%', 'About 8.3%', 'About 6.7%', 'About 12%'],
    correctAnswers: [0],
    explanation: 'Using the doubling time formula: T₂ = ln(2)/k, so k = ln(2)/T₂ = 0.693/12 ≈ 0.0578 ≈ 5.78% per year. The Rule of 72 gives an approximation: 72/12 = 6% (close but approximate). The exact answer uses continuous compounding: if A = A₀e^(kt) doubles in 12 years, then 2 = e^(12k), so 12k = ln(2), giving k = ln(2)/12 ≈ 5.8% per year. The Rule of 72 works because ln(2) ≈ 0.693 and 0.72 is a convenient approximation.',
  },
  {
    id: 'elf-18',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'Which of the following correctly simplifies ln(e^(3x) / e^(x−1))?',
    options: ['2x − 1', '2x + 1', '3x(x−1)', '3x/(x−1)'],
    correctAnswers: [1],
    explanation: 'ln(e^(3x) / e^(x−1)) = ln(e^(3x)) − ln(e^(x−1)) = 3x − (x−1) = 3x − x + 1 = 2x + 1. Key identities: ln(A/B) = ln A − ln B (quotient rule), and ln(eⁿ) = n (inverse function property). Note: −(x−1) = −x+1, NOT −x−1. Distributing the negative sign carefully is the key step — the result is 2x+1, not 2x−1.',
  },

  // ── Additional Complex Numbers ─────────────────────────────────────
  {
    id: 'cn-13',
    domain: 1,
    subdomain: 'Complex Numbers',
    type: 'single',
    difficulty: 'medium',
    question: 'Simplify (3 + 2i)(1 − i).',
    options: ['3 − 2i²', '5 − i', '1 − i', '3 + 2i'],
    correctAnswers: [1],
    explanation: '(3+2i)(1−i) using FOIL: = 3(1) + 3(−i) + 2i(1) + 2i(−i) = 3 − 3i + 2i − 2i². Since i² = −1: −2i² = −2(−1) = +2. So: 3 − 3i + 2i + 2 = 5 − i. The key is replacing i² with −1, which converts the imaginary squared term into a real number. FOIL works exactly like multiplying binomials — just remember the extra substitution at the end.',
  },
  {
    id: 'cn-14',
    domain: 1,
    subdomain: 'Complex Numbers',
    type: 'single',
    difficulty: 'hard',
    question: 'What is the modulus (absolute value) of the complex number 5 − 12i?',
    options: ['7', '13', '17', '√7'],
    correctAnswers: [1],
    explanation: 'The modulus of a + bi is |a + bi| = √(a² + b²). Here: |5 − 12i| = √(5² + (−12)²) = √(25 + 144) = √169 = 13. The modulus represents the distance from the origin to the point (a, b) in the complex plane. Recognizing this as the 5-12-13 Pythagorean triple makes the calculation immediate. The negative sign on 12i does not affect the modulus since (−12)² = 144 = 12².',
  },
  {
    id: 'cn-15',
    domain: 1,
    subdomain: 'Complex Numbers',
    type: 'single',
    difficulty: 'medium',
    question: 'Simplify i^47.',
    options: ['i', '−i', '1', '−1'],
    correctAnswers: [1],
    explanation: 'Powers of i cycle with period 4: i¹=i, i²=−1, i³=−i, i⁴=1, then repeats. To find i^47: divide 47 by 4 → 47 = 4×11 + 3. Remainder is 3, so i^47 = i³ = −i. The pattern by remainder: 1→i, 2→−1, 3→−i, 0→1. Memorize this four-step cycle and you can evaluate any power of i in seconds. This rule works because i⁴ = (i²)² = (−1)² = 1, so every 4th power resets to 1.',
  },

  // ── Additional Conic Sections ──────────────────────────────────────
  {
    id: 'conics-13',
    domain: 1,
    subdomain: 'Conic Sections',
    type: 'single',
    difficulty: 'medium',
    question: 'Which conic section does the equation x² − 4y² = 16 describe?',
    options: ['Circle', 'Ellipse', 'Hyperbola', 'Parabola'],
    correctAnswers: [2],
    explanation: 'Rewrite: x²/16 − y²/4 = 1. This matches the standard form of a hyperbola: x²/a² − y²/b² = 1 (opening left-right). The defining pattern: when one squared term is subtracted from another, equal to a constant, it\'s a hyperbola. Circle: x²+y²=r² (equal positive coefficients). Ellipse: x²/a²+y²/b²=1 (both positive, unequal). Parabola: only one variable squared. Hyperbola: one positive squared term MINUS one positive squared term = constant.',
  },
  {
    id: 'conics-14',
    domain: 1,
    subdomain: 'Conic Sections',
    type: 'single',
    difficulty: 'hard',
    question: 'An ellipse has the equation (x−2)²/25 + (y+1)²/9 = 1. What are the center and lengths of the semi-major and semi-minor axes?',
    options: [
      'Center (2, −1); a = 5 (horizontal semi-major), b = 3 (vertical semi-minor)',
      'Center (−2, 1); a = 25, b = 9',
      'Center (2, −1); a = 25, b = 9',
      'Center (2, 1); a = 5, b = 3',
    ],
    correctAnswers: [0],
    explanation: 'Standard ellipse (x−h)²/a² + (y−k)²/b² = 1 has center (h,k). Here h=2, k=−1, center=(2,−1). Denominators give a²=25→a=5 and b²=9→b=3. Since a>b and a² is under the x-term, the major axis is horizontal with semi-major axis a=5 (total major axis length 10). Semi-minor axis b=3 (vertical, length 6). Foci on horizontal axis: c²=a²−b²=25−9=16, c=4, foci at (2±4,−1)=(−2,−1) and (6,−1).',
  },

  // ── Additional Systems & Matrices ──────────────────────────────────
  {
    id: 'sm-16',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'medium',
    question: 'If det(A) = 0 for a square matrix A, which of the following is true about the system Ax = b?',
    options: [
      'The system always has exactly one solution',
      'The system has no solution or infinitely many solutions — but NOT a unique solution',
      'The system has a unique solution only when b = 0',
      'The matrix A must equal the zero matrix',
    ],
    correctAnswers: [1],
    explanation: 'If det(A) = 0, the matrix is singular (non-invertible). For a 2×2 system, this means the two equations are either parallel lines (no intersection → no solution) or the same line (infinitely many intersections → infinite solutions). A unique solution requires det(A) ≠ 0 so that A⁻¹ exists and x = A⁻¹b can be computed. This is why Cramer\'s Rule requires det(A) ≠ 0 and why row reduction resulting in a row of all zeros signals either no solution or infinite solutions.',
  },
  {
    id: 'sm-17',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'hard',
    question: 'Matrix A = [[2, 1], [5, 3]]. What is A⁻¹?',
    options: [
      '[[3, −1], [−5, 2]]',
      '[[1/2, 1], [5, 1/3]]',
      '[[3, 1], [5, 2]]',
      '[[2, 5], [1, 3]]',
    ],
    correctAnswers: [0],
    explanation: 'For a 2×2 matrix [[a,b],[c,d]], the inverse is (1/det)·[[d,−b],[−c,a]]. Here det(A) = (2)(3)−(1)(5) = 6−5 = 1. Since det=1, A⁻¹ = 1·[[3,−1],[−5,2]] = [[3,−1],[−5,2]]. Verification: A·A⁻¹ = [[2(3)+1(−5), 2(−1)+1(2)],[5(3)+3(−5), 5(−1)+3(2)]] = [[6−5,−2+2],[15−15,−5+6]] = [[1,0],[0,1]] ✓. The formula for a 2×2 inverse is: swap the diagonal, negate the off-diagonal, divide by the determinant.',
  },

  // ── Additional Sequences & Series ─────────────────────────────────
  {
    id: 'ss-14',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'medium',
    question: 'Find the sum of the infinite geometric series: 8 + 4 + 2 + 1 + ...',
    options: ['16', '8', 'Diverges — no sum', '12'],
    correctAnswers: [0],
    explanation: 'This is a geometric series with a₁ = 8 and common ratio r = 4/8 = 1/2. Since |r| = 1/2 < 1, the series converges. S∞ = a₁/(1−r) = 8/(1−1/2) = 8/(1/2) = 16. The partial sums approach 16: 8+4=12, +2=14, +1=15, +0.5=15.5, ... → 16. Intuitively, dividing an interval in half repeatedly approaches zero, so the sum approaches a finite limit. Whenever |r| < 1, the infinite geometric series converges to a₁/(1−r).',
  },
  {
    id: 'ss-15',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'hard',
    question: 'An arithmetic sequence has a₁ = 7 and a₁₅ = 63. What is the common difference?',
    options: ['4', '5', '6', '56'],
    correctAnswers: [0],
    explanation: 'Using aₙ = a₁ + (n−1)d: 63 = 7 + (15−1)d → 56 = 14d → d = 4. The common difference is 4. Alternatively: d = (aₙ − a₁)/(n−1) = (63−7)/(15−1) = 56/14 = 4. Verify: a₁₅ = 7 + 14(4) = 7 + 56 = 63 ✓. This formula works because the nth term equals the first term plus (n−1) steps of size d, so the change from first to nth term is exactly (n−1)d.',
  },

  // ── Additional Statistics & Probability ───────────────────────────
  {
    id: 'sp-16',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'medium',
    question: 'A bag contains 5 red marbles and 3 blue marbles. Two marbles are drawn WITHOUT replacement. What is the probability that both are red?',
    options: ['25/64', '5/14', '10/56', '15/28'],
    correctAnswers: [1],
    explanation: 'P(both red without replacement) = P(1st red) × P(2nd red | 1st was red) = (5/8) × (4/7) = 20/56 = 5/14. With "without replacement," the second draw is conditional on the first result — after drawing one red marble, there are 4 red and 3 blue (7 total). Compare to "with replacement": (5/8)×(5/8) = 25/64. Without replacement uses the multiplication rule for dependent events: P(A and B) = P(A) × P(B|A).',
  },
  {
    id: 'sp-17',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'hard',
    question: 'In a normal distribution, approximately what percentage of data falls within 2 standard deviations of the mean?',
    options: ['68%', '95%', '99.7%', '75%'],
    correctAnswers: [1],
    explanation: 'The Empirical Rule (68-95-99.7 rule) for normal distributions: ≈68% within 1σ; ≈95% within 2σ; ≈99.7% within 3σ. So 95% of data falls within μ ± 2σ. This means only 5% of normally distributed data lies more than 2 standard deviations from the mean — about 2.5% on each tail. This threshold is the basis for the common statistical significance level of p < 0.05 (approximately 2σ away from the expected value under the null hypothesis).',
  },
  {
    id: 'sp-18',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'medium',
    question: 'In how many ways can 5 students be arranged in a line?',
    options: ['5', '10', '120', '25'],
    correctAnswers: [2],
    explanation: '5 students arranged in a line is a permutation of all 5: P(5,5) = 5! = 5×4×3×2×1 = 120. The first position can be filled 5 ways; second 4 ways (one student already placed); third 3 ways; etc. The counting principle multiplies these choices: 5×4×3×2×1 = 120. This is different from "choose 5 from a group" — here we\'re arranging all 5, so every factorial 5! = 120 unique orderings exist.',
  },

  // ── Second wave — broader question coverage ────────────────────────
  {
    id: 'prf-23',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'The graph of a polynomial function crosses the x-axis at x = 2 (multiplicity 1) and touches but does not cross at x = −1 (multiplicity 2). Which description of the graph near those zeros is correct?',
    options: [
      'Crosses at x=2, bounces at x=−1',
      'Bounces at x=2, crosses at x=−1',
      'Crosses at both x=2 and x=−1',
      'Bounces at both zeros',
    ],
    correctAnswers: [0],
    explanation: 'The graph\'s behavior at each zero depends on multiplicity. Odd multiplicity → the graph crosses through the x-axis (changes sign). Even multiplicity → the graph bounces (touches the axis and returns, does not change sign). At x=2 (multiplicity 1, odd): the graph crosses. At x=−1 (multiplicity 2, even): the graph bounces. This rule is one of the most tested aspects of polynomial graphing — examine each zero\'s multiplicity individually.',
  },
  {
    id: 'prf-24',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'What are the vertical asymptotes, if any, of g(x) = (x² − 9) / (x² − x − 6)?',
    options: [
      'x = 3 and x = −2',
      'x = −2 only (x = 3 is a hole)',
      'x = 3 only (x = −2 is a hole)',
      'No vertical asymptotes — both cancel',
    ],
    correctAnswers: [1],
    explanation: 'Factor: numerator = (x−3)(x+3); denominator = (x−3)(x+2). The factor (x−3) appears in both — it cancels, creating a HOLE at x = 3 (not an asymptote). The remaining denominator factor (x+2) does not cancel, so x = −2 is a vertical asymptote. The function simplifies to (x+3)/(x+2) with a hole at x=3. At x=3 on the simplified form: y = (3+3)/(3+2) = 6/5. So the hole is at (3, 6/5) and the only vertical asymptote is x = −2.',
  },
  {
    id: 'prf-25',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are possible rational zeros of p(x) = 6x³ − 7x² + 2x − 5 according to the Rational Zeros Theorem? Select ALL that apply.',
    options: ['±1/2', '±5/6', '±5/2', '±7/3'],
    correctAnswers: [0, 1, 2],
    explanation: 'The Rational Zeros Theorem: any rational zero has the form p/q where p divides the constant term (5) and q divides the leading coefficient (6). Factors of 5: ±1, ±5. Factors of 6: ±1, ±2, ±3, ±6. Possible rational zeros: ±1, ±5, ±1/2, ±5/2, ±1/3, ±5/3, ±1/6, ±5/6. So ±1/2, ±5/6, and ±5/2 are all valid candidates. ±7/3 is NOT valid because 7 is not a factor of the constant term 5.',
  },
  {
    id: 'elf-19',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'hard',
    question: '$2,000 is invested at 6% annual interest compounded monthly. Which expression gives the amount after 10 years?',
    options: [
      '2000(1.06)^10',
      '2000(1 + 0.06/12)^(12×10)',
      '2000·e^(0.06×10)',
      '2000(1.06/12)^(10)',
    ],
    correctAnswers: [1],
    explanation: 'Compound interest formula: A = P(1 + r/n)^(nt). Here P = 2000, r = 0.06 (annual rate), n = 12 (monthly compounding), t = 10. So A = 2000(1 + 0.06/12)^(12×10) = 2000(1.005)^120. Option A uses annual compounding (n=1), not monthly. Option C uses continuous compounding (Peʳᵗ). Option D has the formula incorrectly structured. The key is n represents the number of compounding periods per year, and you must divide the annual rate by n and multiply the exponent by n.',
  },
  {
    id: 'elf-20',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'yesno',
    difficulty: 'medium',
    question: 'True or False: log(5) + log(2) = 1 (where log means log base 10).',
    options: ['True', 'False'],
    correctAnswers: [0],
    explanation: 'True. Using the product rule: log(5) + log(2) = log(5×2) = log(10) = 1. This works because 5 × 2 = 10 and log₁₀(10) = 1 by definition (since 10¹ = 10). This is a frequently tested application of the product rule — recognizing that log(5)+log(2) is the same as log(10). If you memorize that log(2) ≈ 0.301 and log(5) ≈ 0.699, you can also verify: 0.301 + 0.699 = 1.000.',
  },
  {
    id: 'cn-16',
    domain: 1,
    subdomain: 'Complex Numbers',
    type: 'single',
    difficulty: 'medium',
    question: 'Write the complex number (2 + 3i) / (1 − i) in standard form a + bi.',
    options: ['−1/2 + 5i/2', '−1 + 5i/2', '5/2 + i/2', '5/2 − i/2'],
    correctAnswers: [0],
    explanation: 'Multiply numerator and denominator by the conjugate of the denominator (1+i): [(2+3i)(1+i)] / [(1−i)(1+i)]. Denominator: (1−i)(1+i) = 1 − i² = 1 + 1 = 2. Numerator: (2+3i)(1+i) = 2 + 2i + 3i + 3i² = 2 + 5i − 3 = −1 + 5i. Result: (−1 + 5i) / 2 = −1/2 + 5i/2. Always rationalize complex denominators by multiplying by the conjugate.',
  },
  {
    id: 'sm-18',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'medium',
    question: 'Solve the system: 2x + y = 7 and x − y = 2 using elimination.',
    options: ['x = 3, y = 1', 'x = 1, y = 5', 'x = 9/3, y = 0', 'x = 5, y = −3'],
    correctAnswers: [0],
    explanation: 'Add the two equations to eliminate y: (2x+y) + (x−y) = 7+2 → 3x = 9 → x = 3. Substitute back: 2(3)+y = 7 → 6+y = 7 → y = 1. Check in both equations: 2(3)+1 = 7 ✓ and 3−1 = 2 ✓. Elimination works by adding/subtracting equations to cancel one variable. Here the y terms (+y and −y) cancel directly without any scaling needed.',
  },
  {
    id: 'sm-19',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'hard',
    question: 'Matrix A = [[4, 2], [1, 3]]. What is det(A)?',
    options: ['10', '14', '12', '8'],
    correctAnswers: [0],
    explanation: 'For a 2×2 matrix [[a,b],[c,d]], det = ad − bc. Here: det([[4,2],[1,3]]) = (4)(3) − (2)(1) = 12 − 2 = 10. The determinant tells you whether the matrix is invertible (det ≠ 0) and gives the area scaling factor for linear transformations. If det(A) > 0, orientation is preserved; if det(A) < 0, orientation is reversed; if det(A) = 0, the transformation collapses space onto a lower dimension and the matrix has no inverse.',
  },
  {
    id: 'conics-16',
    domain: 1,
    subdomain: 'Conic Sections',
    type: 'single',
    difficulty: 'medium',
    question: 'Which equation represents a parabola with vertex at (−3, 2) opening downward?',
    options: [
      'y = a(x+3)² + 2, where a < 0',
      'y = a(x−3)² + 2, where a > 0',
      'y = a(x+3)² + 2, where a > 0',
      '(x+3)² + (y−2)² = r²',
    ],
    correctAnswers: [0],
    explanation: 'Vertex form: y = a(x−h)² + k with vertex (h, k). Vertex at (−3, 2): h = −3 (so x−h = x−(−3) = x+3) and k = 2. The equation is y = a(x+3)² + 2. Opening downward requires a < 0 (negative leading coefficient reflects the parabola). Option B has the wrong sign in the parenthesis. Option C has a > 0 (opens upward). Option D is a circle, not a parabola.',
  },
  {
    id: 'ss-16',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'medium',
    question: 'A geometric sequence has a₁ = 81 and a₅ = 1. What is the common ratio r?',
    options: ['1/3', '−1/3', '3', '1/4'],
    correctAnswers: [0],
    explanation: 'Using aₙ = a₁·rⁿ⁻¹: 1 = 81·r^(5−1) → 1 = 81r⁴ → r⁴ = 1/81 → r = (1/81)^(1/4) = 1/3. Verification: a₁=81, a₂=27, a₃=9, a₄=3, a₅=1 ✓ (each term is multiplied by 1/3). Note: r = −1/3 would also give |r|^4 = 1/81 mathematically, but a₅ = 81·(−1/3)⁴ = 81·(1/81) = 1 as well. However, in a standard sequence context where the terms 81, 27, 9, 3, 1 are clearly shown to be decreasing positive values, r = 1/3 is the intended answer.',
  },
  {
    id: 'ss-17',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'hard',
    question: 'Evaluate: Σ(k=1 to 6) (3k − 1)',
    options: ['60', '63', '57', '54'],
    correctAnswers: [2],
    explanation: 'Write out each term: k=1: 3(1)−1=2; k=2: 5; k=3: 8; k=4: 11; k=5: 14; k=6: 17. Sum = 2+5+8+11+14+17 = 57. Or use the linearity of sigma: Σ(3k−1) = 3·Σk − Σ1 = 3·(6·7/2) − 6 = 63 − 6 = 57. Either method gets the same answer.',
  },
  {
    id: 'sp-19',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'hard',
    question: 'A binomial experiment has n = 10 trials and probability of success p = 0.3 per trial. What is the probability of exactly 3 successes?',
    options: ['C(10,3)·(0.3)³·(0.7)⁷', 'C(10,3)·(0.7)³·(0.3)⁷', '(0.3)³·(0.7)⁷', '10·(0.3)³·(0.7)⁷'],
    correctAnswers: [0],
    explanation: 'The binomial probability formula: P(X=k) = C(n,k)·pᵏ·(1−p)^(n−k). Here n=10, k=3, p=0.3, so P(X=3) = C(10,3)·(0.3)³·(0.7)⁷. C(10,3) = 120 accounts for the number of ways to choose WHICH 3 of the 10 trials succeed. Each specific sequence of 3 successes and 7 failures has probability (0.3)³·(0.7)⁷. The combination multiplies by the number of such sequences. Evaluating: 120·(0.027)·(0.082) ≈ 0.267 or about 26.7%.',
  },
  {
    id: 'sp-20',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'medium',
    question: 'A class of 30 students has 18 who play sports (S) and 12 who play music (M). If 6 students play both, how many play neither?',
    options: ['6', '12', '0', '24'],
    correctAnswers: [0],
    explanation: 'Using the inclusion-exclusion principle: |S ∪ M| = |S| + |M| − |S ∩ M| = 18 + 12 − 6 = 24. Students playing at least one activity: 24. Students playing neither: 30 − 24 = 6. The inclusion-exclusion principle corrects for double-counting: when you add |S| and |M|, the students in both groups are counted twice, so you subtract |S ∩ M| once to get the correct total for the union.',
  },
  {
    id: 'sp-21',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'yesno',
    difficulty: 'easy',
    question: 'True or False: The mean of a data set is always one of the data values in the set.',
    options: ['True', 'False'],
    correctAnswers: [1],
    explanation: 'False. The mean (arithmetic average) is the sum of all values divided by the count, and this result may not match any actual value in the set. For example, the mean of {1, 2, 4} is 7/3 ≈ 2.33, which is not in the set. This is unlike the median (the literal middle value when sorted) and mode (the most frequent value), both of which must be actual data values. Averages smoothing across data points frequently land between actual values.',
  },
  {
    id: 'prf-26',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'What is the end behavior of f(x) = −2x⁵ + 3x³ − x as x → +∞?',
    options: ['f(x) → +∞', 'f(x) → −∞', 'f(x) → 0', 'f(x) oscillates'],
    correctAnswers: [1],
    explanation: 'End behavior depends only on the leading term: −2x⁵. As x → +∞, x⁵ → +∞ and −2x⁵ → −∞. Degree 5 is odd and the leading coefficient is negative, giving the pattern: as x → −∞, f → +∞; as x → +∞, f → −∞ (LEFT UP, RIGHT DOWN). The lower-order terms (3x³, −x) become negligible compared to −2x⁵ for large |x|. So f(x) → −∞ as x → +∞.',
  },
  {
    id: 'sm-20',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'medium',
    question: 'A system of equations has no solution. Geometrically, this means:',
    options: [
      'The two lines are the same line (coincident)',
      'The two lines are parallel and never intersect',
      'The two lines intersect at exactly one point',
      'The system is consistent',
    ],
    correctAnswers: [1],
    explanation: 'Three possible outcomes for a 2×2 linear system: (1) One unique solution — two distinct lines intersecting at exactly one point (consistent and independent). (2) No solution — two parallel lines with the same slope but different y-intercepts; they never meet (inconsistent). (3) Infinitely many solutions — same line written two different ways; all points on the line are solutions (consistent and dependent). No solution = parallel lines = inconsistent system.',
  },
  {
    id: 'elf-21',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'A radioactive substance has a half-life of 20 years. What fraction of the original amount remains after 60 years?',
    options: ['1/2', '1/4', '1/6', '1/8'],
    correctAnswers: [3],
    explanation: '60 years / 20 years per half-life = 3 half-lives. After 1 half-life: 1/2 remains. After 2: 1/4. After 3: 1/8. Each half-life multiplies the remaining amount by 1/2, so after n half-lives, the fraction remaining is (1/2)ⁿ = (1/2)³ = 1/8. Using the half-life formula: A = A₀·(1/2)^(t/h) = A₀·(1/2)^(60/20) = A₀·(1/2)³ = A₀/8 ✓.',
  },
  {
    id: 'conics-17',
    domain: 1,
    subdomain: 'Conic Sections',
    type: 'single',
    difficulty: 'hard',
    question: 'The foci of an ellipse are at (±4, 0) and the sum of distances from any point on the ellipse to both foci is 10. What is the equation of the ellipse?',
    options: [
      'x²/25 + y²/9 = 1',
      'x²/16 + y²/9 = 1',
      'x²/9 + y²/25 = 1',
      'x²/100 + y²/84 = 1',
    ],
    correctAnswers: [0],
    explanation: 'For an ellipse: 2a = sum of focal distances = 10, so a = 5, a² = 25. Foci at (±4, 0) give c = 4, c² = 16. Using c² = a² − b²: 16 = 25 − b², so b² = 9. Since the foci are on the x-axis, the major axis is horizontal: x²/a² + y²/b² = 1 → x²/25 + y²/9 = 1. The foci lie on the major axis, so the larger denominator (25) goes under x², and b² = 9 goes under y².',
  },
  {
    id: 'ss-18',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'yesno',
    difficulty: 'medium',
    question: 'True or False: The series Σ(k=1 to ∞) (3/2)ᵏ converges to a finite value.',
    options: ['True', 'False'],
    correctAnswers: [1],
    explanation: 'False. This is a geometric series with ratio r = 3/2. Since |r| = 3/2 > 1, the series DIVERGES — the terms (3/2)¹ = 1.5, (3/2)² = 2.25, (3/2)³ = 3.375, ... grow without bound, so the sum also grows without bound. A geometric series converges to a₁/(1−r) ONLY when |r| < 1. When |r| ≥ 1, the terms do not approach zero, so the series cannot converge to a finite value.',
  },
  {
    id: 'cn-17',
    domain: 1,
    subdomain: 'Complex Numbers',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following statements about complex conjugates are correct? Select ALL that apply.',
    options: [
      'The conjugate of (a + bi) is (a − bi)',
      'A complex number times its conjugate always equals a real number',
      'Complex zeros of polynomials with real coefficients always appear in conjugate pairs',
      'The conjugate of a real number (b=0) is a different number than the original',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'Three statements are correct. (A) By definition, the conjugate of a+bi is a−bi — change the sign of the imaginary part. (B) (a+bi)(a−bi) = a²−(bi)² = a²+b², always a non-negative real number — this is why multiplying by the conjugate "realifies" a complex number. (C) Complex zeros come in conjugate pairs for polynomials with real coefficients — proven by the Conjugate Pairs Theorem. (D) is false: if b=0, the conjugate of a+0i = a is a−0i = a — the same real number, not different.',
  },
  {
    id: 'sp-22',
    domain: 1,
    subdomain: 'Statistics & Probability',
    type: 'single',
    difficulty: 'medium',
    question: 'A spinner has sections labeled 1, 2, 3, 4, 5. The expected value E(X) of one spin is:',
    options: ['3', '2.5', '4', '15'],
    correctAnswers: [0],
    explanation: 'For a fair spinner with equally likely outcomes, E(X) = Σ[x · P(x)] = (1+2+3+4+5)/5 = 15/5 = 3. Alternatively: for integers 1 to n, E(X) = (n+1)/2 = (5+1)/2 = 3. Expected value is the long-run average outcome. If probabilities were unequal, weight each outcome by its probability before summing: E(X) = Σ xᵢ·P(xᵢ).',
  },
  {
    id: 'prf-27',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'The graph of a polynomial has end behavior: as x → −∞, f(x) → +∞ and as x → +∞, f(x) → −∞. Which leading term is consistent with this end behavior?',
    options: ['4x⁶', '−3x⁵', '2x³', '−x⁴'],
    correctAnswers: [1],
    explanation: 'End behavior LEFT UP, RIGHT DOWN matches: odd degree + negative leading coefficient. Check each option: 4x⁶ — degree 6 (even), positive; both ends up — NO. −3x⁵ — degree 5 (odd), negative; left up, right down — YES ✓. 2x³ — degree 3 (odd), positive; left down, right up — NO. −x⁴ — degree 4 (even), negative; both ends down — NO. The pattern: odd degree gives opposite end directions; even degree gives same end directions. Sign of leading coefficient determines whether the right end goes up or down.',
  },
  {
    id: 'sm-21',
    domain: 1,
    subdomain: 'Systems & Matrices',
    type: 'single',
    difficulty: 'hard',
    question: 'Use Cramer\'s Rule to find x for the system: 3x + 2y = 8 and x + 4y = 6.',
    options: ['x = 2', 'x = 20/10', 'x = 1', 'x = 3'],
    correctAnswers: [0],
    explanation: 'Cramer\'s Rule: x = Dₓ/D where D = det([[3,2],[1,4]]) = 3(4)−2(1) = 12−2 = 10, and Dₓ = det([[8,2],[6,4]]) = 8(4)−2(6) = 32−12 = 20. So x = Dₓ/D = 20/10 = 2. Verify: 3(2)+2y=8 → 6+2y=8 → y=1; check 2nd: 2+4(1)=6 ✓. Cramer\'s Rule requires computing the determinant of the coefficient matrix (D≠0) and two modified determinants (Dₓ, Dᵧ) where each replaces the corresponding column with the constants column.',
  },
  {
    id: 'elf-22',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'Which of the following is equivalent to log₅(125)?',
    options: ['3', '5/3', '25', '15'],
    correctAnswers: [0],
    explanation: 'log₅(125) asks: "5 to what power equals 125?" Since 5¹=5, 5²=25, 5³=125, the answer is 3. More formally: log₅(125) = log₅(5³) = 3·log₅(5) = 3·1 = 3. Recognizing that 125 = 5³ is the key step. If you don\'t recognize the power, you can use the change-of-base formula: log₅(125) = log(125)/log(5) = 3·log(5)/log(5) = 3.',
  },
  {
    id: 'conics-18',
    domain: 1,
    subdomain: 'Conic Sections',
    type: 'single',
    difficulty: 'medium',
    question: 'What is the center and radius of the circle x² + y² − 4x + 6y − 3 = 0?',
    options: [
      'Center (2, −3), radius 4',
      'Center (−2, 3), radius 4',
      'Center (2, −3), radius 16',
      'Center (4, −6), radius 3',
    ],
    correctAnswers: [0],
    explanation: 'Complete the square for both x and y. Group: (x²−4x) + (y²+6y) = 3. Complete: (x²−4x+4) + (y²+6y+9) = 3+4+9 = 16 → (x−2)² + (y+3)² = 16. Standard form (x−h)²+(y−k)²=r² gives center (h,k)=(2,−3) and r²=16 so r=4. When completing the square for (x²+bx), add (b/2)² inside the grouping AND to the right side to maintain equality. Here: b=−4→add 4; b=6→add 9.',
  },
  {
    id: 'ss-19',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'yesno',
    difficulty: 'easy',
    question: 'True or False: In a geometric sequence, each term after the first is found by multiplying the previous term by a constant ratio.',
    options: ['True', 'False'],
    correctAnswers: [0],
    explanation: 'True — this is the defining property of a geometric sequence. The constant multiplier is called the common ratio r. To identify whether a sequence is geometric, divide any term by the previous one: if the quotient is always the same, it\'s geometric with ratio r = aₙ/aₙ₋₁. Compare to arithmetic sequences where each term is found by ADDING (not multiplying) the common difference d.',
  },
];
