// Question bank for PRECALC — Pre-Calculus (SC 11th-grade advanced math).

export type QuestionType = 'single' | 'multi' | 'ordering' | 'yesno';

export interface Question {
  id: string;
  domain: 1;
  subdomain: string;
  type: QuestionType;
  difficulty: 'easy' | 'medium' | 'hard';
  question: string;
  options: string[];
  correctAnswers: number[];
  explanation: string;
}

export const questions: Question[] = [
  // ══════════════════════════════════════════════════════════════════
  // Functions & Transformations
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'ft-01',
    domain: 1,
    subdomain: 'Functions & Transformations',
    type: 'single',
    difficulty: 'easy',
    question: 'Which transformation shifts the graph of f(x) three units to the right?',
    options: ['f(x) + 3', 'f(x) − 3', 'f(x − 3)', 'f(x + 3)'],
    correctAnswers: [2],
    explanation: 'A horizontal shift of h units to the RIGHT is achieved by replacing x with (x − h). Here h = 3, so f(x − 3) shifts the graph 3 units right. The counterintuitive "minus sign" inside the function argument is the key rule: inside the function, subtract to go right.',
  },
  {
    id: 'ft-02',
    domain: 1,
    subdomain: 'Functions & Transformations',
    type: 'single',
    difficulty: 'easy',
    question: 'If g(x) = −f(x), the graph of g is a reflection of f over which axis?',
    options: ['y-axis', 'x-axis', 'origin', 'line y = x'],
    correctAnswers: [1],
    explanation: 'Multiplying the entire function by −1, i.e. g(x) = −f(x), flips every y-value to its opposite, which is a reflection over the x-axis. Replacing x with −x (i.e. f(−x)) gives a reflection over the y-axis.',
  },
  {
    id: 'ft-03',
    domain: 1,
    subdomain: 'Functions & Transformations',
    type: 'single',
    difficulty: 'medium',
    question: 'A function is called "even" if f(−x) = f(x) for all x. Which of the following parent functions is even?',
    options: ['f(x) = x (linear)', 'f(x) = x³ (cubic)', 'f(x) = x² (quadratic)', 'f(x) = √x (square root)'],
    correctAnswers: [2],
    explanation: 'An even function satisfies f(−x) = f(x) — it is symmetric about the y-axis. f(x) = x² qualifies: f(−x) = (−x)² = x² = f(x). The cubic f(x) = x³ is odd (f(−x) = −f(x)). The linear f(x) = x is also odd. The square root is neither (its domain is x ≥ 0 only).',
  },
  {
    id: 'ft-04',
    domain: 1,
    subdomain: 'Functions & Transformations',
    type: 'single',
    difficulty: 'medium',
    question: 'Given f(x) = x² and g(x) = 2f(x − 1) + 3, what are the transformations applied to f?',
    options: [
      'Shift right 1, vertical stretch by 2, shift up 3',
      'Shift left 1, vertical compress by 2, shift down 3',
      'Shift right 2, vertical stretch by 1, shift up 3',
      'Shift right 1, vertical compress by 1/2, shift up 3',
    ],
    correctAnswers: [0],
    explanation: 'Breaking apart g(x) = 2f(x − 1) + 3: the (x − 1) inside the function shifts the graph 1 unit to the right; the coefficient 2 in front vertically stretches by a factor of 2; and the +3 outside shifts up 3. The order of operations is: inside changes affect x (horizontal), outside changes affect y (vertical).',
  },
  {
    id: 'ft-05',
    domain: 1,
    subdomain: 'Functions & Transformations',
    type: 'single',
    difficulty: 'medium',
    question: 'Which function would have f(f⁻¹(x)) = x and f⁻¹(f(x)) = x as verification that f⁻¹ is the inverse?',
    options: [
      'Only f(f⁻¹(x)) = x is needed',
      'Both compositions must equal x',
      'Neither — just check the graph symmetry over y = x',
      'Only the horizontal line test is needed',
    ],
    correctAnswers: [1],
    explanation: 'To fully verify that two functions are inverses of each other, you must show BOTH compositions equal x: f(f⁻¹(x)) = x AND f⁻¹(f(x)) = x. The horizontal line test checks whether f has an inverse at all (it must be one-to-one), but you still need the algebraic verification. Graph symmetry over y = x is a visual check, not a proof.',
  },
  {
    id: 'ft-06',
    domain: 1,
    subdomain: 'Functions & Transformations',
    type: 'single',
    difficulty: 'hard',
    question: 'If f(x) = 3x + 2, what is f⁻¹(x)?',
    options: ['(x − 2)/3', '(x + 2)/3', '3x − 2', '1/(3x + 2)'],
    correctAnswers: [0],
    explanation: 'To find the inverse: write y = 3x + 2, swap x and y to get x = 3y + 2, then solve for y: x − 2 = 3y, so y = (x − 2)/3. Therefore f⁻¹(x) = (x − 2)/3. Verification: f(f⁻¹(x)) = 3·((x−2)/3) + 2 = (x − 2) + 2 = x ✓.',
  },
  {
    id: 'ft-07',
    domain: 1,
    subdomain: 'Functions & Transformations',
    type: 'single',
    difficulty: 'medium',
    question: 'Which of these is a piecewise function evaluated correctly at x = −2 for f(x) = {x² if x ≥ 0; 2x + 1 if x < 0}?',
    options: ['f(−2) = 4', 'f(−2) = −3', 'f(−2) = 3', 'f(−2) = −4'],
    correctAnswers: [1],
    explanation: 'Since x = −2 is less than 0, we use the second piece: f(−2) = 2(−2) + 1 = −4 + 1 = −3. A common mistake is using the wrong piece. Always check the domain condition first before evaluating.',
  },
  {
    id: 'ft-08',
    domain: 1,
    subdomain: 'Functions & Transformations',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following represent functions? Select ALL that apply.',
    options: [
      'A vertical line',
      'A horizontal line',
      'y = x²',
      'x² + y² = 9 (a circle)',
      'y = √x',
    ],
    correctAnswers: [1, 2, 4],
    explanation: 'A horizontal line passes the vertical line test (every vertical line crosses it exactly once), so it is a function. y = x² and y = √x both pass the vertical line test. A vertical line fails it (the single x-value maps to infinitely many y-values). A circle fails it (most x-values map to two y-values — one on the top arc and one on the bottom).',
  },
  {
    id: 'ft-09',
    domain: 1,
    subdomain: 'Functions & Transformations',
    type: 'single',
    difficulty: 'hard',
    question: 'Given f(x) = x + 1 and g(x) = x², find (f ∘ g)(3).',
    options: ['10', '16', '7', '9'],
    correctAnswers: [0],
    explanation: '(f ∘ g)(3) = f(g(3)). Evaluate the inner function first: g(3) = 3² = 9. Then apply f: f(9) = 9 + 1 = 10. Notice the order: ∘ reads right-to-left, so g acts first. (g ∘ f)(3) would be g(f(3)) = g(4) = 16 — a different result.',
  },
  {
    id: 'ft-10',
    domain: 1,
    subdomain: 'Functions & Transformations',
    type: 'single',
    difficulty: 'easy',
    question: 'The graph of y = |x| shifted left 4 units and down 2 units is:',
    options: ['y = |x − 4| − 2', 'y = |x + 4| − 2', 'y = |x + 4| + 2', 'y = |x − 4| + 2'],
    correctAnswers: [1],
    explanation: 'Horizontal shifts go inside the absolute value: left 4 means replace x with (x + 4), giving |x + 4|. Vertical shifts go outside: down 2 means subtract 2, giving |x + 4| − 2. Remember: inside the function argument, "plus" moves left, "minus" moves right.',
  },
  {
    id: 'ft-11',
    domain: 1,
    subdomain: 'Functions & Transformations',
    type: 'single',
    difficulty: 'medium',
    question: 'For y = (1/3)f(x), the graph of f is:',
    options: [
      'Vertically stretched by a factor of 3',
      'Vertically compressed by a factor of 3',
      'Horizontally stretched by a factor of 3',
      'Horizontally compressed by a factor of 3',
    ],
    correctAnswers: [1],
    explanation: 'Multiplying f(x) by a constant a gives a vertical stretch if |a| > 1, and a vertical compression if 0 < |a| < 1. Here a = 1/3, which is between 0 and 1, so the graph is vertically compressed (squished toward the x-axis) by a factor of 3. This is not a horizontal transformation.',
  },
  {
    id: 'ft-12',
    domain: 1,
    subdomain: 'Functions & Transformations',
    type: 'single',
    difficulty: 'medium',
    question: 'The domain of f(x) = √(x − 5) is:',
    options: ['x ≤ 5', 'x ≥ 5', 'x > 5', 'all real numbers'],
    correctAnswers: [1],
    explanation: 'The expression under a square root must be non-negative: x − 5 ≥ 0, which gives x ≥ 5. Note that x = 5 is included because √0 = 0 is defined. The domain is [5, ∞).',
  },
  {
    id: 'ft-13',
    domain: 1,
    subdomain: 'Functions & Transformations',
    type: 'single',
    difficulty: 'hard',
    question: 'Which of the following confirms that a function is ODD?',
    options: [
      'Its graph is symmetric about the y-axis',
      'f(−x) = f(x) for all x',
      'f(−x) = −f(x) for all x',
      'It passes the horizontal line test',
    ],
    correctAnswers: [2],
    explanation: 'An odd function satisfies f(−x) = −f(x) — its graph has 180° rotational symmetry about the origin. Even functions satisfy f(−x) = f(x) and have y-axis symmetry. The horizontal line test determines whether a function has an inverse, not whether it is odd or even.',
  },
  {
    id: 'ft-14',
    domain: 1,
    subdomain: 'Functions & Transformations',
    type: 'single',
    difficulty: 'easy',
    question: 'The parent function of y = 1/x is called the:',
    options: ['Square root function', 'Reciprocal function', 'Absolute value function', 'Cubic function'],
    correctAnswers: [1],
    explanation: 'y = 1/x is the reciprocal function (also called the rational parent function). Its graph consists of two hyperbola branches in the first and third quadrants, with vertical asymptote x = 0 and horizontal asymptote y = 0. It is an odd function.',
  },
  {
    id: 'ft-15',
    domain: 1,
    subdomain: 'Functions & Transformations',
    type: 'single',
    difficulty: 'hard',
    question: 'If f(2) = 5 and f is one-to-one, then f⁻¹(5) equals:',
    options: ['1/5', '2', '5', '1/2'],
    correctAnswers: [1],
    explanation: 'If f(2) = 5, the inverse reverses the input-output pair: f⁻¹(5) = 2. Inverse functions swap the x and y coordinates, so the point (2, 5) on the graph of f corresponds to the point (5, 2) on the graph of f⁻¹. No calculation is needed — just read the relationship.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Polynomial & Rational Functions
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'pr-01',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'A polynomial of degree 5 with a positive leading coefficient has what end behavior?',
    options: [
      'Both ends go up',
      'Both ends go down',
      'Left end goes down, right end goes up',
      'Left end goes up, right end goes down',
    ],
    correctAnswers: [2],
    explanation: 'For a polynomial with odd degree and positive leading coefficient: as x → +∞, y → +∞ (right end goes up), and as x → −∞, y → −∞ (left end goes down). The mnemonic: odd degree = opposite ends; positive leading coefficient = right goes up. If the leading coefficient were negative, both directions flip.',
  },
  {
    id: 'pr-02',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'The zero x = 3 has multiplicity 2 in a polynomial. How does the graph behave at x = 3?',
    options: [
      'It crosses through the x-axis',
      'It bounces off the x-axis (touches but does not cross)',
      'It has a vertical asymptote',
      'It becomes undefined',
    ],
    correctAnswers: [1],
    explanation: 'Even multiplicity zeros cause the graph to touch (bounce off) the x-axis without crossing. Odd multiplicity zeros cause the graph to cross through. At x = 3 with multiplicity 2 (even), the graph touches the axis and turns around — like a parabola at its vertex.',
  },
  {
    id: 'pr-03',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'According to the Remainder Theorem, if f(x) is divided by (x − 3), the remainder equals:',
    options: ['f(0)', 'f(3)', 'f(−3)', '3'],
    correctAnswers: [1],
    explanation: 'The Remainder Theorem states that when a polynomial f(x) is divided by (x − a), the remainder is f(a). Here a = 3, so the remainder equals f(3). If f(3) = 0, then (x − 3) is a factor — that is the Factor Theorem.',
  },
  {
    id: 'pr-04',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'The rational function f(x) = (x + 2)/[(x − 1)(x + 3)] has vertical asymptotes at:',
    options: ['x = −2', 'x = 1 and x = −3', 'x = −1 and x = 3', 'x = 1 only'],
    correctAnswers: [1],
    explanation: 'Vertical asymptotes occur at values where the denominator equals zero and the numerator is NOT zero (no cancellation). Setting (x − 1)(x + 3) = 0 gives x = 1 and x = −3. At neither of these does the numerator (x + 2) equal zero, so both are true asymptotes, not holes.',
  },
  {
    id: 'pr-05',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'For f(x) = (3x² + x)/(x² − 4), the horizontal asymptote is:',
    options: ['y = 3', 'y = 0', 'y = 1', 'No horizontal asymptote'],
    correctAnswers: [0],
    explanation: 'When the degree of the numerator equals the degree of the denominator, the horizontal asymptote is the ratio of the leading coefficients. Numerator has degree 2 with leading coefficient 3; denominator has degree 2 with leading coefficient 1. So y = 3/1 = 3.',
  },
  {
    id: 'pr-06',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'The function f(x) = (x² − 4)/(x − 2) has a hole at x = 2. After simplification, what is the y-value of the hole?',
    options: ['0', '2', '4', 'Undefined (no hole)'],
    correctAnswers: [2],
    explanation: 'Factor the numerator: x² − 4 = (x + 2)(x − 2). Cancel the common factor (x − 2): the simplified function is x + 2, with the restriction x ≠ 2. The hole occurs at x = 2, and its y-coordinate is found by evaluating the simplified function: 2 + 2 = 4. The point (2, 4) is a removable discontinuity.',
  },
  {
    id: 'pr-07',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'When dividing 2x³ − x² + 3x − 5 by (x − 2) using synthetic division, the remainder is:',
    options: ['9', '13', '17', '−5'],
    correctAnswers: [1],
    explanation: 'Using synthetic division with divisor x = 2: Coefficients are 2, −1, 3, −5. Bring down 2. Multiply 2×2=4, add to −1 to get 3. Multiply 3×2=6, add to 3 to get 9. Multiply 9×2=18, add to −5 to get 13. The remainder is 13. By the Remainder Theorem, this equals f(2) = 2(8) − 4 + 6 − 5 = 16 − 4 + 6 − 5 = 13 ✓.',
  },
  {
    id: 'pr-08',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'A degree-4 polynomial can have at most how many turning points?',
    options: ['4', '3', '2', '5'],
    correctAnswers: [1],
    explanation: 'A polynomial of degree n can have at most n − 1 turning points (local maxima and minima). For degree 4, that is at most 3 turning points. The actual number may be fewer, but never more than n − 1.',
  },
  {
    id: 'pr-09',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'For f(x) = (x + 1)/(x − 3), which statement about the horizontal asymptote is correct?',
    options: [
      'y = 1, because the leading coefficient ratio is 1/1',
      'y = −1/3, because of the y-intercept',
      'y = 3, because the denominator zero is 3',
      'No horizontal asymptote',
    ],
    correctAnswers: [0],
    explanation: 'Numerator and denominator both have degree 1. The horizontal asymptote is the ratio of leading coefficients: 1/1 = 1. So y = 1. For rational functions, if degrees are equal, HA = leading coeff ratio; if deg(num) < deg(den), HA = 0; if deg(num) > deg(den), there is no HA (instead, oblique or polynomial asymptote).',
  },
  {
    id: 'pr-10',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'A polynomial with zeros at x = −2 (multiplicity 1), x = 0 (multiplicity 2), and x = 3 (multiplicity 1) and a positive leading coefficient has minimum degree:',
    options: ['3', '4', '5', '6'],
    correctAnswers: [1],
    explanation: 'The minimum degree equals the sum of all multiplicities: 1 + 2 + 1 = 4. The polynomial can be written as f(x) = a·x²·(x + 2)·(x − 3) for some positive leading coefficient a. Expanding confirms degree 4.',
  },
  {
    id: 'pr-11',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'For f(x) = 5/(x + 1), as x → +∞, f(x) approaches:',
    options: ['5', '0', '+∞', '1'],
    correctAnswers: [1],
    explanation: 'As x grows without bound, the denominator (x + 1) grows without bound while the numerator stays fixed at 5. So 5/(x + 1) → 0. This is consistent with the horizontal asymptote y = 0 (since degree of numerator 0 < degree of denominator 1).',
  },
  {
    id: 'pr-12',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'If (x − 4) is a factor of p(x), which statement must be true?',
    options: [
      'p(4) = 4',
      'p(4) = 0',
      'p(0) = 4',
      'The graph has a vertical asymptote at x = 4',
    ],
    correctAnswers: [1],
    explanation: 'The Factor Theorem states that (x − a) is a factor of p(x) if and only if p(a) = 0. Here a = 4, so p(4) = 0. This means x = 4 is a zero of the polynomial and the graph crosses (or touches) the x-axis at x = 4.',
  },
  {
    id: 'pr-13',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'Which rational function has an oblique (slant) asymptote?',
    options: [
      'f(x) = x/(x + 2)',
      'f(x) = (x² + 1)/(x − 1)',
      'f(x) = 1/(x² + 1)',
      'f(x) = (x + 3)/(x² − 4)',
    ],
    correctAnswers: [1],
    explanation: 'An oblique asymptote exists when the degree of the numerator is exactly one more than the degree of the denominator. In f(x) = (x² + 1)/(x − 1), the numerator has degree 2 and the denominator has degree 1 — exactly one more. Performing polynomial long division gives the oblique asymptote. The other functions have equal degrees or numerator degree less than denominator degree.',
  },
  {
    id: 'pr-14',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'yesno',
    difficulty: 'easy',
    question: 'True or False: A polynomial can have at most n real zeros, where n is the degree of the polynomial.',
    options: ['True', 'False'],
    correctAnswers: [0],
    explanation: 'True. A polynomial of degree n can have at most n zeros (real or complex). By the Fundamental Theorem of Algebra, it has exactly n zeros when counted with multiplicity (in the complex number system). For real zeros only, the count can be n, n−2, n−4, … down to 0 or 1 depending on degree.',
  },
  {
    id: 'pr-15',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'A polynomial f has degree 3, a negative leading coefficient, and zeros at x = −1, 2, 5. As x → +∞, f(x) approaches:',
    options: ['+∞', '−∞', '0', 'undefined'],
    correctAnswers: [1],
    explanation: 'With odd degree and negative leading coefficient: as x → +∞, y → −∞, and as x → −∞, y → +∞. The zeros tell us where the graph crosses the x-axis but do not change the end behavior. The leading term dominates for large |x|.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Exponential & Logarithmic Functions
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'el-01',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'Which logarithm property states that log(AB) = log A + log B?',
    options: ['Quotient rule', 'Product rule', 'Power rule', 'Change of base'],
    correctAnswers: [1],
    explanation: 'The Product Rule for logarithms states logb(AB) = logb(A) + logb(B). This works because logarithms are exponents, and when you multiply powers with the same base, you add exponents. Similarly, logb(A/B) = logb(A) − logb(B) (Quotient Rule), and logb(Aⁿ) = n·logb(A) (Power Rule).',
  },
  {
    id: 'el-02',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'Solve: 2ˣ = 32',
    options: ['x = 4', 'x = 5', 'x = 6', 'x = 16'],
    correctAnswers: [1],
    explanation: 'Express 32 as a power of 2: 32 = 2⁵. So 2ˣ = 2⁵, which means x = 5. When both sides have the same base, the exponents must be equal. For equations where you cannot match bases, take log of both sides and use the power rule.',
  },
  {
    id: 'el-03',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'log₂(8) equals:',
    options: ['2', '3', '4', '16'],
    correctAnswers: [1],
    explanation: 'log₂(8) asks: "2 to what power equals 8?" Since 2³ = 8, the answer is 3. Always read logb(x) as "the exponent you put on b to get x." This thinking converts every logarithm evaluation into an exponent problem.',
  },
  {
    id: 'el-04',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'The continuously compounded interest formula is A = Peʳᵗ. If $1,000 is invested at 5% annual interest for 10 years, what is A?',
    options: ['$1,648.72', '$1,500.00', '$1,647.00', '$1,628.89'],
    correctAnswers: [0],
    explanation: 'A = Peʳᵗ = 1000 · e^(0.05 × 10) = 1000 · e^0.5 ≈ 1000 · 1.6487 ≈ $1,648.72. This is slightly more than periodic compounding because continuous compounding adds interest infinitely many times per year — the limit of (1 + r/n)^(nt) as n → ∞.',
  },
  {
    id: 'el-05',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'Using change of base, log₅(30) can be written as:',
    options: ['log(5)/log(30)', 'log(30)/log(5)', 'ln(5)/ln(30)', '5/30'],
    correctAnswers: [1],
    explanation: 'The change of base formula: logb(x) = log(x)/log(b) = ln(x)/ln(b). So log₅(30) = log(30)/log(5) ≈ 1.477/0.699 ≈ 2.11. This formula lets you evaluate any logarithm using a calculator\'s log₁₀ or ln keys.',
  },
  {
    id: 'el-06',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'Solve: log₃(x + 1) + log₃(x − 1) = 2',
    options: ['x = √10', 'x = 3', 'x = ±√10', 'x = 10'],
    correctAnswers: [0],
    explanation: 'Use the product rule: log₃((x+1)(x−1)) = 2, so log₃(x²−1) = 2. Rewrite in exponential form: x² − 1 = 3² = 9, so x² = 10, x = ±√10. Check domains: the arguments (x+1) and (x−1) must be positive, requiring x > 1. So x = −√10 ≈ −3.16 is rejected, and x = √10 ≈ 3.16 is valid.',
  },
  {
    id: 'el-07',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'A radioactive substance has a half-life of 20 years. The decay formula A = A₀e^(−kt). What is k?',
    options: ['k = ln(2)/20', 'k = 20/ln(2)', 'k = 20', 'k = 2/20'],
    correctAnswers: [0],
    explanation: 'At t = 20 (one half-life), A = A₀/2. So A₀/2 = A₀e^(−20k), giving 1/2 = e^(−20k). Take ln of both sides: ln(1/2) = −20k, so −ln(2) = −20k, thus k = ln(2)/20 ≈ 0.0347. This k value appears in all exponential decay contexts (carbon-14, drug clearance, etc.).',
  },
  {
    id: 'el-08',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'The logistic growth model P(t) = K/(1 + Ae^(−bt)) approaches what value as t → ∞?',
    options: ['0', 'A', 'K', 'b'],
    correctAnswers: [2],
    explanation: 'As t → ∞, e^(−bt) → 0 (since b > 0), so the denominator approaches 1 + A·0 = 1, and P(t) → K/1 = K. The value K is the carrying capacity — the maximum population the environment can support. The S-shaped logistic curve grows quickly at first, then slows as it approaches K.',
  },
  {
    id: 'el-09',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'Simplify: log(1000) (base 10)',
    options: ['2', '3', '100', '10'],
    correctAnswers: [1],
    explanation: 'log₁₀(1000) = log₁₀(10³) = 3. Always ask: "10 to what power equals 1000?" Since 10³ = 1000, the answer is 3. Key logarithm values to memorize: log(1) = 0, log(10) = 1, log(100) = 2, log(1000) = 3, and log(0.1) = −1.',
  },
  {
    id: 'el-10',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'Solve: 5^(2x−1) = 125',
    options: ['x = 2', 'x = 3', 'x = 1', 'x = 1/2'],
    correctAnswers: [0],
    explanation: '125 = 5³, so 5^(2x−1) = 5³. Since the bases are equal, 2x − 1 = 3, giving 2x = 4, x = 2. Always look to express both sides with the same base before equating exponents. This avoids the need for logarithms entirely.',
  },
  {
    id: 'el-11',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'The inverse function of f(x) = eˣ is:',
    options: ['f⁻¹(x) = 10ˣ', 'f⁻¹(x) = ln(x)', 'f⁻¹(x) = log(x)', 'f⁻¹(x) = e^(−x)'],
    correctAnswers: [1],
    explanation: 'The natural logarithm ln(x) is the inverse of the natural exponential eˣ. This means e^(ln x) = x and ln(eˣ) = x. The graphs of y = eˣ and y = ln(x) are reflections of each other over the line y = x. Note: log(x) is base 10 and is the inverse of 10ˣ, not eˣ.',
  },
  {
    id: 'el-12',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'A population starts at 500 and doubles every 8 years. What is the doubling time formula for the continuous model P = P₀e^(kt)?',
    options: ['k = 8/ln(2)', 'k = ln(2)/8', 'k = 8·ln(2)', 'k = 2/8'],
    correctAnswers: [1],
    explanation: 'Doubling time T satisfies P₀·e^(kT) = 2P₀, so e^(kT) = 2, giving kT = ln(2), thus k = ln(2)/T = ln(2)/8 ≈ 0.0866. This is the analog of the half-life formula. The doubling time itself is T = ln(2)/k — memorize this relationship.',
  },
  {
    id: 'el-13',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'ln(e⁷) equals:',
    options: ['7e', 'e⁷', '7', '1/7'],
    correctAnswers: [2],
    explanation: 'By the inverse property of logarithms, ln(eˣ) = x for all real x. Therefore ln(e⁷) = 7. This is the defining property of the natural log as the inverse of the natural exponential function.',
  },
  {
    id: 'el-14',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'Which of the following correctly expands log₂(8x³/y)?',
    options: [
      'log₂(8) + 3·log₂(x) − log₂(y)',
      '3 + 3·log₂(x) − log₂(y)',
      '3·log₂(8x) − log₂(y)',
      '8 + log₂(x³) − log₂(y)',
    ],
    correctAnswers: [1],
    explanation: 'Apply the quotient rule: log₂(8x³/y) = log₂(8x³) − log₂(y). Then the product rule: log₂(8) + log₂(x³) − log₂(y). Then the power rule: log₂(8) + 3·log₂(x) − log₂(y). Since log₂(8) = log₂(2³) = 3, the final answer is 3 + 3·log₂(x) − log₂(y).',
  },
  {
    id: 'el-15',
    domain: 1,
    subdomain: 'Exponential & Logarithmic Functions',
    type: 'yesno',
    difficulty: 'medium',
    question: 'True or False: The domain of f(x) = log(x) includes negative values of x.',
    options: ['True', 'False'],
    correctAnswers: [1],
    explanation: 'False. The domain of f(x) = log(x) is x > 0. You cannot take the logarithm of a non-positive number in the real number system. There is no real power you can raise 10 to and get a negative result or zero. The range of log(x), however, is all real numbers.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Trigonometric Functions
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'trig-01',
    domain: 1,
    subdomain: 'Trigonometric Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'How many radians are equivalent to 180°?',
    options: ['π/2', 'π', '2π', '3π/2'],
    correctAnswers: [1],
    explanation: '180° = π radians. This is the fundamental conversion. To convert from degrees to radians, multiply by π/180. To convert from radians to degrees, multiply by 180/π. Key benchmarks: 90° = π/2, 180° = π, 270° = 3π/2, 360° = 2π.',
  },
  {
    id: 'trig-02',
    domain: 1,
    subdomain: 'Trigonometric Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'On the unit circle, the coordinates at angle θ = π/3 (60°) are:',
    options: ['(√3/2, 1/2)', '(1/2, √3/2)', '(√2/2, √2/2)', '(1/2, 1/2)'],
    correctAnswers: [1],
    explanation: 'At 60° (π/3) on the unit circle, x = cos(60°) = 1/2 and y = sin(60°) = √3/2. So the coordinates are (1/2, √3/2). Memory trick for the 30-60-90 triangle: the sides opposite 30°, 60°, 90° are in ratio 1 : √3 : 2. On the unit circle, hypotenuse = 1.',
  },
  {
    id: 'trig-03',
    domain: 1,
    subdomain: 'Trigonometric Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'For y = 3sin(2x − π/4) + 1, the amplitude is:',
    options: ['1', '2', '3', '6'],
    correctAnswers: [2],
    explanation: 'In y = A·sin(Bx + C) + D, the amplitude is |A|. Here A = 3, so the amplitude is 3. The amplitude is the "half-height" of the wave — the maximum is 3 + 1 = 4 and the minimum is −3 + 1 = −2. Amplitude is always positive (take the absolute value if A is negative).',
  },
  {
    id: 'trig-04',
    domain: 1,
    subdomain: 'Trigonometric Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'What is the period of y = sin(4x)?',
    options: ['4π', 'π/2', '2π', 'π'],
    correctAnswers: [1],
    explanation: 'The period of y = sin(Bx) is 2π/|B|. Here B = 4, so period = 2π/4 = π/2. A larger B compresses the graph horizontally, resulting in a shorter period. A smaller B (like B = 1/2) stretches the graph, giving a longer period.',
  },
  {
    id: 'trig-05',
    domain: 1,
    subdomain: 'Trigonometric Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'In which quadrant is both sin(θ) and cos(θ) negative?',
    options: ['Quadrant I', 'Quadrant II', 'Quadrant III', 'Quadrant IV'],
    correctAnswers: [2],
    explanation: 'Using ASTC (All Students Take Calculus): All trig functions are positive in Q1; Sine (and cosec) are positive in Q2; Tangent (and cotan) are positive in Q3; Cosine (and secant) are positive in Q4. So in Q3, sine and cosine are BOTH negative, while tangent is positive (negative/negative = positive).',
  },
  {
    id: 'trig-06',
    domain: 1,
    subdomain: 'Trigonometric Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'The reciprocal of sin(θ) is:',
    options: ['cos(θ)', 'tan(θ)', 'csc(θ)', 'sec(θ)'],
    correctAnswers: [2],
    explanation: 'csc(θ) = 1/sin(θ) is the cosecant function. The three reciprocal pairs are: csc = 1/sin, sec = 1/cos, cot = 1/tan. Mnemonic: co-functions are pairs — sin↔csc, cos↔sec, tan↔cot. Be careful not to confuse sec with the inverse of sine (that would be sin⁻¹, which is arcsine, a completely different thing).',
  },
  {
    id: 'trig-07',
    domain: 1,
    subdomain: 'Trigonometric Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'For y = −2cos(x − π/6) + 3, the phase shift is:',
    options: ['π/6 to the right', 'π/6 to the left', '3 to the right', '−π/6 to the right'],
    correctAnswers: [0],
    explanation: 'In y = A·cos(Bx − C) + D, the phase shift is C/B (positive = right). Here the equation is y = −2cos(x − π/6) + 3, so B = 1 and C = π/6. Phase shift = (π/6)/1 = π/6 to the right. The negative sign on A causes a reflection over the midline — it does not affect the phase shift.',
  },
  {
    id: 'trig-08',
    domain: 1,
    subdomain: 'Trigonometric Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'What is sin(π/2)?',
    options: ['0', '1/2', '√2/2', '1'],
    correctAnswers: [3],
    explanation: 'At π/2 (90°), the unit circle point is (0, 1). Since sin(θ) = y-coordinate, sin(π/2) = 1. This is the maximum value of sine. Memorize the key values: sin(0) = 0, sin(π/6) = 1/2, sin(π/4) = √2/2, sin(π/3) = √3/2, sin(π/2) = 1.',
  },
  {
    id: 'trig-09',
    domain: 1,
    subdomain: 'Trigonometric Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'The period of y = tan(x) is:',
    options: ['2π', 'π', 'π/2', '4π'],
    correctAnswers: [1],
    explanation: 'The period of y = tan(x) is π (not 2π like sine and cosine). This is because the tangent function goes through one complete cycle from one vertical asymptote to the next, which is a distance of π. The period of y = tan(Bx) is π/|B|.',
  },
  {
    id: 'trig-10',
    domain: 1,
    subdomain: 'Trigonometric Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'Convert 5π/6 radians to degrees.',
    options: ['120°', '150°', '210°', '300°'],
    correctAnswers: [1],
    explanation: '5π/6 × (180°/π) = 5×180/6 = 900/6 = 150°. This angle is in Quadrant II (between 90° and 180°). Its reference angle is 180° − 150° = 30°. At 150°: sin(150°) = sin(30°) = 1/2, and cos(150°) = −cos(30°) = −√3/2 (negative in Q2).',
  },
  {
    id: 'trig-11',
    domain: 1,
    subdomain: 'Trigonometric Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'What is cos(0)?',
    options: ['0', '1/2', '1', 'undefined'],
    correctAnswers: [2],
    explanation: 'At angle 0 (or 0°), the unit circle point is (1, 0). Since cos(θ) = x-coordinate, cos(0) = 1. This is the starting point of the cosine graph. Key: cos(0) = 1, cos(π/2) = 0, cos(π) = −1, cos(3π/2) = 0, cos(2π) = 1.',
  },
  {
    id: 'trig-12',
    domain: 1,
    subdomain: 'Trigonometric Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'The reference angle for 240° is:',
    options: ['30°', '60°', '120°', '240°'],
    correctAnswers: [1],
    explanation: '240° is in Quadrant III (between 180° and 270°). The reference angle for a Q3 angle is the angle minus 180°: 240° − 180° = 60°. Reference angles are always between 0° and 90°. They allow you to use the 30-60-90 or 45-45-90 triangles to find trig values in any quadrant.',
  },
  {
    id: 'trig-13',
    domain: 1,
    subdomain: 'Trigonometric Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'In y = A·sin(Bx + C) + D, which parameter controls the vertical shift?',
    options: ['A', 'B', 'C', 'D'],
    correctAnswers: [3],
    explanation: 'D is the vertical shift (or vertical translation). It moves the midline of the sinusoidal graph up or down. A is the amplitude, B determines the period (period = 2π/|B|), and C (combined with B) determines the phase shift (−C/B). A complete understanding of all four parameters is essential for graphing sinusoidal functions.',
  },
  {
    id: 'trig-14',
    domain: 1,
    subdomain: 'Trigonometric Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'What is tan(π/4)?',
    options: ['1', '√2', '1/2', '√3'],
    correctAnswers: [0],
    explanation: 'tan(π/4) = sin(π/4)/cos(π/4) = (√2/2)/(√2/2) = 1. At 45°, sine and cosine are equal (both √2/2), so their ratio is 1. Also, the 45-45-90 triangle has equal legs, so opposite/adjacent = 1/1 = 1. tan(π/4) = 1 is one of the most important unit circle values to memorize.',
  },
  {
    id: 'trig-15',
    domain: 1,
    subdomain: 'Trigonometric Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'Which of the following is the midline of y = 4sin(x) − 1?',
    options: ['y = 4', 'y = −1', 'y = 1', 'y = 0'],
    correctAnswers: [1],
    explanation: 'The midline of y = A·sin(Bx + C) + D is y = D. Here D = −1, so the midline is y = −1. The graph oscillates between −1 + 4 = 3 (maximum) and −1 − 4 = −5 (minimum), centered on y = −1. The midline is the horizontal axis of the sinusoidal wave.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Analytic Trigonometry
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'at-01',
    domain: 1,
    subdomain: 'Analytic Trigonometry',
    type: 'single',
    difficulty: 'easy',
    question: 'The Pythagorean identity sin²θ + cos²θ equals:',
    options: ['0', '1', '2', 'tan²θ'],
    correctAnswers: [1],
    explanation: 'sin²θ + cos²θ = 1 is the most fundamental Pythagorean identity. It comes directly from the Pythagorean theorem applied to the unit circle: on the unit circle, x = cosθ, y = sinθ, and x² + y² = 1 (the radius is 1). Dividing both sides by cos²θ gives 1 + tan²θ = sec²θ; dividing by sin²θ gives cot²θ + 1 = csc²θ.',
  },
  {
    id: 'at-02',
    domain: 1,
    subdomain: 'Analytic Trigonometry',
    type: 'single',
    difficulty: 'medium',
    question: 'The sine addition formula sin(A + B) equals:',
    options: ['sin A + sin B', 'sin A·cos B + cos A·sin B', 'sin A·cos B − cos A·sin B', 'cos A·cos B − sin A·sin B'],
    correctAnswers: [1],
    explanation: 'sin(A + B) = sin A·cos B + cos A·sin B. This is one of the most important identities. Memory tip: "sin cos + cos sin" for addition. For subtraction: sin(A − B) = sin A·cos B − cos A·sin B. Compare with cos(A + B) = cos A·cos B − sin A·sin B (the pattern flips and the sign goes negative).',
  },
  {
    id: 'at-03',
    domain: 1,
    subdomain: 'Analytic Trigonometry',
    type: 'single',
    difficulty: 'medium',
    question: 'The double angle formula cos(2A) can be written as (choose any equivalent form):',
    options: ['2cos A', '2cos²A − 1', 'cos²A + sin²A', '2sin A·cos A'],
    correctAnswers: [1],
    explanation: 'cos(2A) has three equivalent forms: cos²A − sin²A, 2cos²A − 1, and 1 − 2sin²A. You get them by replacing sin²A = 1 − cos²A or cos²A = 1 − sin²A in the first form. Choose based on which trig functions appear in your target expression. The double angle for sine is sin(2A) = 2sinA·cosA.',
  },
  {
    id: 'at-04',
    domain: 1,
    subdomain: 'Analytic Trigonometry',
    type: 'single',
    difficulty: 'hard',
    question: 'When proving a trig identity, which approach is correct?',
    options: [
      'Add the same expression to both sides',
      'Multiply both sides by a common denominator',
      'Work one side only until it matches the other',
      'Cross-multiply to create a new equation',
    ],
    correctAnswers: [2],
    explanation: 'When proving a trig identity, work on ONE side only and transform it algebraically until it looks exactly like the other side. You cannot add to both sides, multiply both sides, or cross-multiply — those operations assume the identity is true, which is exactly what you are trying to prove. Treat the other side as the "target" you are navigating toward.',
  },
  {
    id: 'at-05',
    domain: 1,
    subdomain: 'Analytic Trigonometry',
    type: 'single',
    difficulty: 'medium',
    question: 'Solve sin(x) = 1/2 on [0, 2π). Which values are solutions?',
    options: ['x = π/6 only', 'x = π/6 and 5π/6', 'x = π/3 and 2π/3', 'x = π/4 and 3π/4'],
    correctAnswers: [1],
    explanation: 'sin(x) = 1/2 corresponds to a reference angle of π/6 (30°). Sine is positive in Quadrants I and II. In Q1: x = π/6. In Q2: x = π − π/6 = 5π/6. These are the two solutions in [0, 2π). The general solution would be x = π/6 + 2πk and x = 5π/6 + 2πk for any integer k.',
  },
  {
    id: 'at-06',
    domain: 1,
    subdomain: 'Analytic Trigonometry',
    type: 'single',
    difficulty: 'medium',
    question: 'The Law of Sines states that a/sin A equals:',
    options: ['b/sin B', 'sin B/b', 'b·sin B', 'sin A/a'],
    correctAnswers: [0],
    explanation: 'The Law of Sines: a/sin A = b/sin B = c/sin C, where a, b, c are sides and A, B, C are the opposite angles. Use it when you know two angles and a side (AAS or ASA), or two sides and a non-included angle (SSA — but watch for the ambiguous case). The ratio a/sin A is sometimes written as 2R, where R is the circumradius.',
  },
  {
    id: 'at-07',
    domain: 1,
    subdomain: 'Analytic Trigonometry',
    type: 'single',
    difficulty: 'hard',
    question: 'In a triangle where a = 7, b = 10, and A = 30°, how many triangles are possible (ambiguous case)?',
    options: [
      'Exactly 1',
      'Exactly 2',
      'None',
      'Cannot determine without more information',
    ],
    correctAnswers: [1],
    explanation: 'In the SSA ambiguous case with acute angle A = 30°: compare a (7) to b·sin A = 10·sin(30°) = 5. Since a = 7 > 5 = b·sin A and a = 7 < b = 10, two triangles are possible. Summary: if angle A is acute and b·sin A < a < b, two triangles exist; if a ≥ b or a = b·sin A, one triangle; if a < b·sin A, no triangle.',
  },
  {
    id: 'at-08',
    domain: 1,
    subdomain: 'Analytic Trigonometry',
    type: 'single',
    difficulty: 'medium',
    question: 'The Law of Cosines c² = a² + b² − 2ab·cos C is used when:',
    options: [
      'You know all three angles',
      'You know two angles and one side',
      'You know two sides and the included angle (SAS) or all three sides (SSS)',
      'You know two sides and a non-included angle (SSA)',
    ],
    correctAnswers: [2],
    explanation: 'The Law of Cosines is used for SAS (two sides and the included angle) or SSS (all three sides). Notice it reduces to the Pythagorean theorem when C = 90° (cos 90° = 0, so c² = a² + b²). The Law of Sines is typically easier for AAS, ASA, and SSA cases.',
  },
  {
    id: 'at-09',
    domain: 1,
    subdomain: 'Analytic Trigonometry',
    type: 'single',
    difficulty: 'hard',
    question: 'Which of the following is NOT a correct form of the Pythagorean identities?',
    options: ['sin²θ + cos²θ = 1', '1 + tan²θ = sec²θ', 'cot²θ + 1 = csc²θ', 'sin²θ − cos²θ = 1'],
    correctAnswers: [3],
    explanation: 'sin²θ − cos²θ = 1 is NOT a valid Pythagorean identity. The correct one is sin²θ + cos²θ = 1 (addition, not subtraction). The three Pythagorean identities are: (1) sin²θ + cos²θ = 1, (2) 1 + tan²θ = sec²θ, (3) cot²θ + 1 = csc²θ. All three follow from dividing the first identity by cos²θ or sin²θ.',
  },
  {
    id: 'at-10',
    domain: 1,
    subdomain: 'Analytic Trigonometry',
    type: 'single',
    difficulty: 'hard',
    question: 'The restricted domain for y = sin(x) that allows y = sin⁻¹(x) to be defined is:',
    options: ['[0, π]', '[−π/2, π/2]', '[0, 2π)', 'All real numbers'],
    correctAnswers: [1],
    explanation: 'To define the inverse sine (arcsin), we restrict sin(x) to [−π/2, π/2] — the interval where sine is one-to-one. On this interval, sin increases from −1 to 1, so sin⁻¹ has domain [−1, 1] and range [−π/2, π/2]. Similarly, cos⁻¹ uses [0, π] for cosine, and tan⁻¹ uses (−π/2, π/2) for tangent.',
  },
  {
    id: 'at-11',
    domain: 1,
    subdomain: 'Analytic Trigonometry',
    type: 'single',
    difficulty: 'medium',
    question: 'sin(2A) equals:',
    options: ['2sin A', '2sin A·cos A', 'sin²A − cos²A', '2cos A'],
    correctAnswers: [1],
    explanation: 'The double angle formula for sine is sin(2A) = 2sin(A)cos(A). This follows from the addition formula: sin(A + A) = sin A·cos A + cos A·sin A = 2sin A·cos A. The double angle formula for cosine has three forms: cos(2A) = cos²A − sin²A = 2cos²A − 1 = 1 − 2sin²A.',
  },
  {
    id: 'at-12',
    domain: 1,
    subdomain: 'Analytic Trigonometry',
    type: 'single',
    difficulty: 'easy',
    question: 'sin⁻¹(1) equals:',
    options: ['0', 'π/4', 'π/2', 'π'],
    correctAnswers: [2],
    explanation: 'sin⁻¹(1) asks: "what angle in [−π/2, π/2] has a sine of 1?" The answer is π/2, because sin(π/2) = 1. The range of arcsine is [−π/2, π/2], so π would not be in the range even though sin(π) = 0 (not 1). Key values: sin⁻¹(0) = 0, sin⁻¹(1/2) = π/6, sin⁻¹(√2/2) = π/4, sin⁻¹(√3/2) = π/3, sin⁻¹(1) = π/2.',
  },
  {
    id: 'at-13',
    domain: 1,
    subdomain: 'Analytic Trigonometry',
    type: 'single',
    difficulty: 'hard',
    question: 'In a triangle with sides a = 6, b = 8, c = 10, angle C (opposite side c = 10) is:',
    options: ['30°', '45°', '60°', '90°'],
    correctAnswers: [3],
    explanation: 'Using the Law of Cosines: c² = a² + b² − 2ab·cos C → 100 = 36 + 64 − 96·cos C → 100 = 100 − 96·cos C → 0 = −96·cos C → cos C = 0 → C = 90°. This is a 6-8-10 right triangle (a Pythagorean triple scaled from 3-4-5). Recognizing Pythagorean triples saves time.',
  },
  {
    id: 'at-14',
    domain: 1,
    subdomain: 'Analytic Trigonometry',
    type: 'single',
    difficulty: 'medium',
    question: 'cos(A − B) equals:',
    options: [
      'cos A·cos B + sin A·sin B',
      'cos A·cos B − sin A·sin B',
      'cos A − cos B',
      'sin A·cos B − cos A·sin B',
    ],
    correctAnswers: [0],
    explanation: 'cos(A − B) = cos A·cos B + sin A·sin B. Note the positive sign — this is different from cos(A + B) = cos A·cos B − sin A·sin B. The sign difference is a common error. A useful check: cos(A − A) = cos(0) = 1, and cos A·cos A + sin A·sin A = cos²A + sin²A = 1 ✓.',
  },
  {
    id: 'at-15',
    domain: 1,
    subdomain: 'Analytic Trigonometry',
    type: 'single',
    difficulty: 'hard',
    question: 'Solve 2cos²(x) − 1 = 0 on [0, 2π).',
    options: [
      'x = π/4 and 3π/4',
      'x = π/4, 3π/4, 5π/4, 7π/4',
      'x = π/3 and 5π/3',
      'x = π/6 and 5π/6',
    ],
    correctAnswers: [1],
    explanation: '2cos²x − 1 = 0 → cos²x = 1/2 → cos x = ±√(1/2) = ±√2/2. cos x = +√2/2 gives x = π/4 (Q1) and x = 7π/4 (Q4). cos x = −√2/2 gives x = 3π/4 (Q2) and x = 5π/4 (Q3). All four solutions. Note: 2cos²x − 1 = cos(2x) by the double angle identity, so this is equivalent to cos(2x) = 0.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Sequences & Series
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'ss-01',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'easy',
    question: 'The nth term of an arithmetic sequence with first term a₁ = 5 and common difference d = 3 is:',
    options: ['aₙ = 3n + 5', 'aₙ = 5 + 3(n − 1)', 'aₙ = 5n + 3', 'aₙ = 3n'],
    correctAnswers: [1],
    explanation: 'The nth term formula for an arithmetic sequence is aₙ = a₁ + (n − 1)d. With a₁ = 5 and d = 3: aₙ = 5 + (n − 1)·3 = 5 + 3n − 3 = 3n + 2. So option B = 5 + 3(n − 1) is equivalent. Let\'s verify: a₁ = 5 + 3(0) = 5 ✓, a₂ = 5 + 3(1) = 8 ✓, a₃ = 5 + 3(2) = 11 ✓.',
  },
  {
    id: 'ss-02',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'medium',
    question: 'For a geometric sequence with first term 2 and common ratio 3, what is the 5th term?',
    options: ['32', '162', '486', '54'],
    correctAnswers: [1],
    explanation: 'The nth term of a geometric sequence is aₙ = a₁·rⁿ⁻¹. Here a₁ = 2 and r = 3: a₅ = 2·3⁴ = 2·81 = 162. The sequence is 2, 6, 18, 54, 162, … — each term is multiplied by 3. Notice that a₄ = 54 and a₅ = 162 (not 486, which would be a₆).',
  },
  {
    id: 'ss-03',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'medium',
    question: 'The infinite geometric series with a₁ = 6 and r = 1/2 converges to:',
    options: ['12', '6', '3', '∞'],
    correctAnswers: [0],
    explanation: 'An infinite geometric series converges when |r| < 1, and its sum is S = a₁/(1 − r). Here |1/2| < 1, so it converges. S = 6/(1 − 1/2) = 6/(1/2) = 12. The series 6 + 3 + 3/2 + 3/4 + … adds up to exactly 12. If |r| ≥ 1, the series diverges.',
  },
  {
    id: 'ss-04',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'easy',
    question: 'What does lim(x→2) (x² − 4)/(x − 2) equal? (Evaluate the limit, not just substitute.)',
    options: ['0', 'undefined', '4', '2'],
    correctAnswers: [2],
    explanation: 'Direct substitution gives 0/0, an indeterminate form. Factor the numerator: (x² − 4)/(x − 2) = (x + 2)(x − 2)/(x − 2) = x + 2, for x ≠ 2. Now take the limit: lim(x→2) (x + 2) = 4. The limit exists and equals 4, even though the function is undefined at x = 2.',
  },
  {
    id: 'ss-05',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'hard',
    question: 'lim(x→∞) (3x² + 2x)/(x² − 5) equals:',
    options: ['0', '3', '∞', '2'],
    correctAnswers: [1],
    explanation: 'Divide numerator and denominator by x² (the highest power): (3 + 2/x)/(1 − 5/x²). As x → ∞, 2/x → 0 and 5/x² → 0, leaving 3/1 = 3. This technique — dividing by the highest power — always works for rational functions at infinity. The horizontal asymptote of the corresponding rational function is y = 3.',
  },
  {
    id: 'ss-06',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'medium',
    question: 'Which condition guarantees that an infinite geometric series converges?',
    options: ['r > 1', '|r| < 1', 'r = 1', 'r is positive'],
    correctAnswers: [1],
    explanation: 'An infinite geometric series Σ a₁rⁿ converges if and only if |r| < 1. This includes negative r values like r = −1/2. If |r| ≥ 1, the terms do not approach zero, and the series diverges. The convergence condition and sum formula S = a₁/(1 − r) are two things to memorize together.',
  },
  {
    id: 'ss-07',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'medium',
    question: 'The sum of the first n terms of an arithmetic sequence is:',
    options: ['S = n·a₁', 'S = n/2·(a₁ + aₙ)', 'S = a₁·rⁿ⁻¹', 'S = a₁/(1 − r)'],
    correctAnswers: [1],
    explanation: 'The sum of the first n terms of an arithmetic sequence is S = n/2·(a₁ + aₙ) = n/2·(first term + last term). This makes intuitive sense: the average of the first and last terms, times n, gives the total. For example, the sum 1 + 2 + 3 + … + 100 = 100/2·(1 + 100) = 50·101 = 5050.',
  },
  {
    id: 'ss-08',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'hard',
    question: 'The limit lim(x→3⁺) 1/(x − 3) equals:',
    options: ['0', '−∞', '+∞', '1/3'],
    correctAnswers: [2],
    explanation: 'Approaching from the right (x → 3⁺), (x − 3) is small and positive. So 1/(x − 3) becomes a very large positive number: the limit is +∞. Approaching from the left (x → 3⁻), (x − 3) is small and negative, giving −∞. Since left and right limits differ, the two-sided limit does not exist, but the one-sided limit from the right is +∞.',
  },
  {
    id: 'ss-09',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'hard',
    question: 'The derivative, defined as the limit f\'(x) = lim(h→0) [f(x+h) − f(x)]/h, represents geometrically:',
    options: [
      'The area under the curve',
      'The slope of the tangent line at x',
      'The average value of f on an interval',
      'The y-intercept of f',
    ],
    correctAnswers: [1],
    explanation: 'The difference quotient [f(x+h) − f(x)]/h is the slope of the secant line through (x, f(x)) and (x+h, f(x+h)). As h → 0, this secant line approaches the tangent line at x, so the limit is the slope of the tangent line at that point. This is the geometric meaning of the derivative — your first glimpse into calculus.',
  },
  {
    id: 'ss-10',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'medium',
    question: 'A sequence is defined by a₁ = 3, aₙ = aₙ₋₁ + 5. This is:',
    options: ['Geometric with ratio 5', 'Arithmetic with difference 5', 'Neither arithmetic nor geometric', 'Geometric with ratio 3'],
    correctAnswers: [1],
    explanation: 'The recursive formula aₙ = aₙ₋₁ + 5 adds a constant (5) to each term — that is the definition of an arithmetic sequence. The common difference is d = 5. The sequence is 3, 8, 13, 18, … The explicit formula is aₙ = 3 + (n − 1)·5 = 5n − 2.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Vectors & Parametrics
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'vp-01',
    domain: 1,
    subdomain: 'Vectors & Parametrics',
    type: 'single',
    difficulty: 'easy',
    question: 'The magnitude of vector v = ⟨3, 4⟩ is:',
    options: ['7', '5', '12', '25'],
    correctAnswers: [1],
    explanation: 'The magnitude (length) of vector ⟨a, b⟩ is √(a² + b²). Here: √(3² + 4²) = √(9 + 16) = √25 = 5. This is a 3-4-5 Pythagorean triple. Magnitude is always non-negative. Notation: |v| or ‖v‖.',
  },
  {
    id: 'vp-02',
    domain: 1,
    subdomain: 'Vectors & Parametrics',
    type: 'single',
    difficulty: 'medium',
    question: 'The dot product of u = ⟨2, 3⟩ and v = ⟨4, −1⟩ is:',
    options: ['5', '8', '11', '−5'],
    correctAnswers: [0],
    explanation: 'The dot product u·v = u₁v₁ + u₂v₂ = (2)(4) + (3)(−1) = 8 − 3 = 5. The dot product is a scalar (not a vector). It equals |u||v|cos θ, where θ is the angle between u and v. When the dot product is 0, the vectors are perpendicular (orthogonal).',
  },
  {
    id: 'vp-03',
    domain: 1,
    subdomain: 'Vectors & Parametrics',
    type: 'single',
    difficulty: 'medium',
    question: 'Two vectors u and v are orthogonal if their dot product equals:',
    options: ['1', '−1', '0', '|u||v|'],
    correctAnswers: [2],
    explanation: 'Two vectors are orthogonal (perpendicular) if and only if their dot product is 0. This comes from the formula u·v = |u||v|cos θ: if θ = 90°, then cos 90° = 0, so u·v = 0. This is a powerful test — you don\'t need angles, just check if u₁v₁ + u₂v₂ = 0.',
  },
  {
    id: 'vp-04',
    domain: 1,
    subdomain: 'Vectors & Parametrics',
    type: 'single',
    difficulty: 'hard',
    question: 'In polar coordinates, the point (r, θ) = (3, π/6) corresponds to which Cartesian coordinates?',
    options: ['(3√3/2, 3/2)', '(3/2, 3√3/2)', '(3, π/6)', '(√3/2, 1/2)'],
    correctAnswers: [0],
    explanation: 'Polar-to-Cartesian: x = r·cos θ = 3·cos(π/6) = 3·(√3/2) = 3√3/2; y = r·sin θ = 3·sin(π/6) = 3·(1/2) = 3/2. So (x, y) = (3√3/2, 3/2). Option B has x and y swapped — a common error when memorizing the conversion the wrong way around.',
  },
  {
    id: 'vp-05',
    domain: 1,
    subdomain: 'Vectors & Parametrics',
    type: 'single',
    difficulty: 'medium',
    question: 'Parametric equations x = 2t and y = t² − 1. Eliminating the parameter t gives:',
    options: ['y = x² − 1', 'y = x²/4 − 1', 'y = 4x² − 1', 'y = (x/2)² + 1'],
    correctAnswers: [1],
    explanation: 'From x = 2t, solve for t: t = x/2. Substitute into y: y = (x/2)² − 1 = x²/4 − 1. This is an upward-opening parabola shifted down 1 unit. Eliminating the parameter converts parametric form to Cartesian form — the process is always "solve for t in the simpler equation, then substitute."',
  },
  {
    id: 'vp-06',
    domain: 1,
    subdomain: 'Vectors & Parametrics',
    type: 'single',
    difficulty: 'easy',
    question: 'The polar equation r = 3 represents:',
    options: ['A vertical line', 'A horizontal line', 'A circle of radius 3', 'A spiral'],
    correctAnswers: [2],
    explanation: 'In polar coordinates, r = constant is a circle centered at the origin. Here r = 3 is a circle with radius 3. Converting to Cartesian: r = 3 → r² = 9 → x² + y² = 9, which is indeed a circle of radius 3. The angle θ can take any value while r stays fixed at 3.',
  },
  {
    id: 'vp-07',
    domain: 1,
    subdomain: 'Vectors & Parametrics',
    type: 'single',
    difficulty: 'hard',
    question: 'The direction angle of vector v = ⟨−3, 3⟩ (measured from the positive x-axis) is:',
    options: ['45°', '135°', '−45°', '225°'],
    correctAnswers: [1],
    explanation: 'The reference angle is arctan(|3|/|−3|) = arctan(1) = 45°. The vector ⟨−3, 3⟩ is in Quadrant II (negative x, positive y). So the direction angle = 180° − 45° = 135°. Always adjust the arctan result to the correct quadrant by checking the signs of the components.',
  },
  {
    id: 'vp-08',
    domain: 1,
    subdomain: 'Vectors & Parametrics',
    type: 'single',
    difficulty: 'medium',
    question: 'Vector addition: ⟨2, −1⟩ + ⟨−3, 4⟩ equals:',
    options: ['⟨5, −5⟩', '⟨−1, 3⟩', '⟨1, 3⟩', '⟨−1, −5⟩'],
    correctAnswers: [1],
    explanation: 'Add component-by-component: ⟨2 + (−3), −1 + 4⟩ = ⟨−1, 3⟩. Vector addition is commutative and associative. Geometrically, you place the tail of the second vector at the head of the first; the sum is the vector from the tail of the first to the head of the second.',
  },
  {
    id: 'vp-09',
    domain: 1,
    subdomain: 'Vectors & Parametrics',
    type: 'single',
    difficulty: 'medium',
    question: 'Converting the Cartesian point (0, −5) to polar coordinates gives:',
    options: ['(5, 0)', '(5, π/2)', '(5, 3π/2)', '(−5, π)'],
    correctAnswers: [2],
    explanation: 'r = √(0² + (−5)²) = √25 = 5. θ = arctan(y/x) = arctan(−5/0), which is undefined by formula, but the point (0, −5) is directly below the origin on the negative y-axis, at angle θ = 3π/2 (or equivalently 270° or −π/2). So the polar form is (5, 3π/2).',
  },
  {
    id: 'vp-10',
    domain: 1,
    subdomain: 'Vectors & Parametrics',
    type: 'single',
    difficulty: 'hard',
    question: 'The scalar projection of u = ⟨3, 4⟩ onto v = ⟨1, 0⟩ is:',
    options: ['3', '4', '5', '0'],
    correctAnswers: [0],
    explanation: 'The scalar projection of u onto v is (u·v)/|v|. Here u·v = 3(1) + 4(0) = 3 and |v| = √(1² + 0²) = 1. So the scalar projection is 3/1 = 3. Geometrically, projecting ⟨3, 4⟩ onto the x-axis gives the x-component, which is 3. When projecting onto a unit vector, the scalar projection equals the dot product.',
  },

  // ── 6 additional questions to reach ≥100 ─────────────────────────

  {
    id: 'trig-21',
    domain: 1,
    subdomain: 'Trigonometric Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'arcsin(√3/2) equals (give the answer in the principal-value range [−π/2, π/2]):',
    options: ['π/3', '2π/3', 'π/6', '−π/3'],
    correctAnswers: [0],
    explanation: 'arcsin asks "what angle in [−π/2, π/2] has a sine of √3/2?" Since sin(π/3) = √3/2 and π/3 is in [−π/2, π/2], the answer is π/3 (60°). The principal-value range for arcsine is always [−π/2, π/2], so 2π/3 is excluded even though sin(2π/3) = √3/2 as well.',
  },
  {
    id: 'trig-22',
    domain: 1,
    subdomain: 'Trigonometric Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'arctan(−1) equals (principal value):',
    options: ['π/4', '−π/4', '3π/4', '−3π/4'],
    correctAnswers: [1],
    explanation: 'arctan has principal-value range (−π/2, π/2). We need the angle in that range whose tangent is −1. Since tan(−π/4) = −1 and −π/4 is in (−π/2, π/2), the answer is −π/4. Note: tan(3π/4) = −1 too, but 3π/4 is outside the principal-value range for arctan.',
  },
  {
    id: 'pr-16',
    domain: 1,
    subdomain: 'Polynomial & Rational Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'The partial fraction decomposition of (3x + 5)/[(x + 1)(x + 2)] is of the form:',
    options: [
      'A/(x + 1) + B/(x + 2)',
      'A/(x + 1)² + B/(x + 2)',
      '(Ax + B)/(x + 1) + C/(x + 2)',
      'A/[(x + 1)(x + 2)]',
    ],
    correctAnswers: [0],
    explanation: 'When the denominator has distinct linear factors, each factor gets its own constant numerator. So (3x + 5)/[(x+1)(x+2)] = A/(x+1) + B/(x+2). Multiply both sides by (x+1)(x+2), then solve for A and B by substituting convenient values of x: let x = −1 → A = 2; let x = −2 → B = 1.',
  },
  {
    id: 'vp-11',
    domain: 1,
    subdomain: 'Vectors & Parametrics',
    type: 'single',
    difficulty: 'medium',
    question: 'The parametric equations x = 3cos(t), y = 3sin(t) for t ∈ [0, 2π) describe which curve in rectangular form?',
    options: ['y = 3 − x', 'x² + y² = 9', 'x²/9 + y²/9 = 3', 'y = √(9 − x²)'],
    correctAnswers: [1],
    explanation: 'Square both equations: x² = 9cos²t and y² = 9sin²t. Add them: x² + y² = 9cos²t + 9sin²t = 9(cos²t + sin²t) = 9·1 = 9. So the rectangular form is x² + y² = 9, a circle of radius 3 centered at the origin. The parameter t acts like the angle in the unit circle definition.',
  },
  {
    id: 'at-16',
    domain: 1,
    subdomain: 'Analytic Trigonometry',
    type: 'single',
    difficulty: 'hard',
    question: 'Using the sum identity, sin(75°) = sin(45° + 30°) equals:',
    options: [
      '(√6 + √2)/4',
      '(√6 − √2)/4',
      '(√3 + 1)/4',
      '(√2 + 1)/2',
    ],
    correctAnswers: [0],
    explanation: 'sin(A + B) = sinA·cosB + cosA·sinB. With A = 45° and B = 30°: sin(75°) = sin45°·cos30° + cos45°·sin30° = (√2/2)(√3/2) + (√2/2)(1/2) = √6/4 + √2/4 = (√6 + √2)/4 ≈ 0.966. This technique lets you find exact trig values for angles that aren\'t on the standard unit circle.',
  },
  {
    id: 'ss-16',
    domain: 1,
    subdomain: 'Sequences & Series',
    type: 'single',
    difficulty: 'medium',
    question: 'The sequence aₙ = (2n + 1)/n as n → ∞ has limit:',
    options: ['0', '1', '2', '∞'],
    correctAnswers: [2],
    explanation: 'Divide numerator and denominator by n: aₙ = (2 + 1/n)/1. As n → ∞, the term 1/n → 0, so aₙ → (2 + 0)/1 = 2. A sequence converges when its terms approach a finite limit; this sequence converges to 2. If the limit were ∞ or did not exist, the sequence would diverge.',
  },

  // ══════════════════════════════════════════════════════════════
  // Trigonometric Functions — additional questions
  // ══════════════════════════════════════════════════════════════
  {
    id: 'trig-23', domain: 1, subdomain: 'Trigonometric Functions', type: 'single', difficulty: 'medium',
    question: 'The function y = 3sin(2x − π) + 1 has amplitude, period, and vertical shift of:',
    options: [
      'Amplitude 3, period π, vertical shift 1',
      'Amplitude 3, period 2π, vertical shift −1',
      'Amplitude 6, period π, vertical shift 1',
      'Amplitude 1/3, period π, vertical shift −1',
    ],
    correctAnswers: [0],
    explanation: 'For y = A·sin(Bx − C) + D: amplitude = |A| = 3, period = 2π/|B| = 2π/2 = π, phase shift = C/B = π/2 (right), vertical shift = D = 1. The phase shift does not affect amplitude, period, or vertical shift. Identifying these four parameters is the foundation for graphing any sinusoidal function.',
  },
  {
    id: 'trig-24', domain: 1, subdomain: 'Trigonometric Functions', type: 'single', difficulty: 'easy',
    question: 'What is the exact value of cos(π/4)?',
    options: ['1/2', '√2/2', '√3/2', '1'],
    correctAnswers: [1],
    explanation: 'cos(π/4) = cos(45°) = √2/2 ≈ 0.707. In the 45-45-90 special right triangle with legs 1 and hypotenuse √2, the adjacent side over the hypotenuse gives 1/√2 = √2/2. Memorize unit circle values for 0°, 30°, 45°, 60°, and 90° — they appear constantly on exams and must be recalled instantly without a calculator.',
  },
  {
    id: 'trig-25', domain: 1, subdomain: 'Trigonometric Functions', type: 'single', difficulty: 'hard',
    question: 'Which of the following is the range of y = arcsin(x)?',
    options: ['[0, π]', '[−π/2, π/2]', '(−π, π)', 'All real numbers'],
    correctAnswers: [1],
    explanation: 'arcsin(x) has domain [−1, 1] and range [−π/2, π/2]. The range is restricted so arcsin is a proper function (one input → one output). Note: arccos has range [0, π] and arctan has range (−π/2, π/2) open interval — common exam confusions. Always verify the specific inverse trig function for its restricted range.',
  },
  {
    id: 'trig-26', domain: 1, subdomain: 'Trigonometric Functions', type: 'multi', difficulty: 'medium',
    question: 'Which statements about y = tan(x) are true? (Select all that apply.)',
    options: [
      'The period of tan(x) is π',
      'tan(x) has vertical asymptotes at x = π/2 + nπ for integer n',
      'The range of tan(x) is [−1, 1]',
      'tan(x) is an odd function: tan(−x) = −tan(x)',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'tan(x) = sin(x)/cos(x). Period = π (half of sine/cosine). Vertical asymptotes where cos(x) = 0, i.e., x = π/2 + nπ. Odd function because sin(−x) = −sin(x) and cos(−x) = cos(x) so tan(−x) = −tan(x). The range is all real numbers (−∞, ∞), NOT [−1, 1]. Only sin and cos have the bounded [−1, 1] range.',
  },
  {
    id: 'trig-27', domain: 1, subdomain: 'Trigonometric Functions', type: 'single', difficulty: 'hard',
    question: 'A Ferris wheel with radius 20 m has its center 22 m above the ground and completes one revolution every 40 seconds. Which function models height h(t) of a rider starting at the bottom?',
    options: [
      'h(t) = 20cos(2πt/40) + 22',
      'h(t) = −20cos(2πt/40) + 22',
      'h(t) = 20sin(2πt/40) + 22',
      'h(t) = −20sin(2πt/40) + 22',
    ],
    correctAnswers: [1],
    explanation: 'Starting at the bottom: h(0) = 22 − 20 = 2 m. Using −cos: h(0) = −20·cos(0) + 22 = −20 + 22 = 2 ✓. Period: 2π/B = 40 → B = π/20, so B = 2π/40. Amplitude = 20 (radius). Vertical shift = 22 (center height). Using +cos gives h(0) = 42 (top start), so −cos is correct for starting at the bottom.',
  },

  // ══════════════════════════════════════════════════════════════
  // Polynomial & Rational Functions — additional questions
  // ══════════════════════════════════════════════════════════════
  {
    id: 'pr-17', domain: 1, subdomain: 'Polynomial & Rational Functions', type: 'single', difficulty: 'medium',
    question: 'According to the Rational Root Theorem, which of the following could be a rational zero of f(x) = 2x³ − 5x² + 3x − 6?',
    options: ['±7', '±3/2', '±4', '±5/3'],
    correctAnswers: [1],
    explanation: 'Rational Root Theorem: possible rational zeros = ±(factors of constant) / (factors of leading coefficient) = ±{1,2,3,6} / {1,2} = ±1, ±2, ±3, ±6, ±1/2, ±3/2. Only ±3/2 from the options appears on this list. The RRT narrows candidates; you still must test each (by synthetic division or substitution) to confirm actual zeros.',
  },
  {
    id: 'pr-18', domain: 1, subdomain: 'Polynomial & Rational Functions', type: 'single', difficulty: 'medium',
    question: 'What does the end behavior of f(x) = −3x⁴ + 2x² − 1 look like?',
    options: [
      'As x → ±∞, f(x) → +∞',
      'As x → ±∞, f(x) → −∞',
      'As x → +∞, f(x) → +∞ and as x → −∞, f(x) → −∞',
      'As x → +∞, f(x) → −∞ and as x → −∞, f(x) → +∞',
    ],
    correctAnswers: [1],
    explanation: 'End behavior is determined by the leading term −3x⁴. Even degree → both ends go same direction. Negative leading coefficient → both ends go DOWN. So as x → ±∞, f(x) → −∞ (graph falls on both sides). Rule: even degree + positive leading = both up; even degree + negative = both down; odd degree + positive = down-left/up-right; odd + negative = up-left/down-right.',
  },
  {
    id: 'pr-19', domain: 1, subdomain: 'Polynomial & Rational Functions', type: 'single', difficulty: 'hard',
    question: 'The function f(x) = (x² − 4)/(x − 2) has which feature at x = 2?',
    options: [
      'A vertical asymptote',
      'A zero of the function',
      'A removable discontinuity (hole)',
      'The function is defined and continuous at x = 2',
    ],
    correctAnswers: [2],
    explanation: 'Factor: x² − 4 = (x−2)(x+2). So f(x) = (x−2)(x+2)/(x−2) = x+2 for x ≠ 2. The common factor (x−2) cancels — leaving a hole (removable discontinuity) at x = 2, not a vertical asymptote. The hole is at (2, 4). A vertical asymptote requires a denominator zero that does NOT cancel with the numerator.',
  },
  {
    id: 'pr-20', domain: 1, subdomain: 'Polynomial & Rational Functions', type: 'multi', difficulty: 'hard',
    question: 'For f(x) = (2x² + 3x)/(x² − 1), which are true? (Select all that apply.)',
    options: [
      'The horizontal asymptote is y = 2',
      'There are vertical asymptotes at x = 1 and x = −1',
      'There is a zero at x = 0',
      'The degree of the numerator equals the degree of the denominator',
    ],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'All four are true. HA: degrees equal (both 2), so HA = ratio of leading coefficients = 2/1 = 2. VAs: x²−1 = (x−1)(x+1) → zeros at x = ±1; neither cancels with 2x²+3x. Zero: numerator 2x²+3x = x(2x+3) = 0 at x = 0 and x = −3/2, so x = 0 is a zero. Degrees: both numerator and denominator have degree 2.',
  },
  {
    id: 'pr-21', domain: 1, subdomain: 'Polynomial & Rational Functions', type: 'single', difficulty: 'medium',
    question: 'How many turning points can a degree-5 polynomial have at most?',
    options: ['3', '4', '5', '6'],
    correctAnswers: [1],
    explanation: 'A polynomial of degree n can have at most n − 1 turning points. For degree-5: maximum of 4 turning points. The actual number depends on the polynomial — it could have 4, 2, or 0. A turning point is where the function changes from increasing to decreasing (local max) or decreasing to increasing (local min). This rule helps quickly check whether a proposed graph matches a given degree.',
  },

  // ══════════════════════════════════════════════════════════════
  // Analytic Trigonometry — additional questions
  // ══════════════════════════════════════════════════════════════
  {
    id: 'at-17', domain: 1, subdomain: 'Analytic Trigonometry', type: 'single', difficulty: 'medium',
    question: 'Simplify: sin²(x) / (1 − cos(x))',
    options: ['1 + cos(x)', '1 − cos(x)', 'sin(x)', 'cos(x)'],
    correctAnswers: [0],
    explanation: 'Use Pythagorean identity sin²(x) = 1 − cos²(x) = (1−cos x)(1+cos x). Substitute: (1−cos x)(1+cos x)/(1−cos x) = 1 + cos(x), valid when cos x ≠ 1. Recognizing sin²x as a difference of squares via the Pythagorean identity is one of the most common trig simplification strategies on standardized assessments.',
  },
  {
    id: 'at-18', domain: 1, subdomain: 'Analytic Trigonometry', type: 'single', difficulty: 'hard',
    question: 'Solve for x ∈ [0, 2π): 2cos²(x) − cos(x) − 1 = 0',
    options: [
      'x = π/3, 5π/3',
      'x = 0, 2π/3, 4π/3',
      'x = 2π/3, 4π/3',
      'x = π/3, π, 5π/3',
    ],
    correctAnswers: [1],
    explanation: 'Let u = cos(x). Factor: 2u² − u − 1 = (2u + 1)(u − 1) = 0. So u = −1/2 or u = 1. cos(x) = −1/2 → x = 2π/3, 4π/3. cos(x) = 1 → x = 0. Solutions: x = 0, 2π/3, 4π/3. Technique: substitute u = trig(x) to form a quadratic, factor, solve, then map u back to x using the unit circle.',
  },
  {
    id: 'at-19', domain: 1, subdomain: 'Analytic Trigonometry', type: 'single', difficulty: 'medium',
    question: 'Which identity is the double-angle formula for cosine?',
    options: [
      'cos(2x) = sin²(x) − cos²(x)',
      'cos(2x) = cos²(x) − sin²(x)',
      'cos(2x) = 2sin(x)cos(x)',
      'cos(2x) = sin(x) + cos(x)',
    ],
    correctAnswers: [1],
    explanation: 'cos(2x) = cos²(x) − sin²(x), derived from cos(A+B) = cosAcosB − sinAsinB with A=B=x. Two equivalent forms: 2cos²(x)−1 (useful when you want only cosines) or 1−2sin²(x) (only sines). The formula 2sin(x)cos(x) is the double-angle for SINE — a common distractor on exams.',
  },
  {
    id: 'at-20', domain: 1, subdomain: 'Analytic Trigonometry', type: 'single', difficulty: 'hard',
    question: 'In triangle ABC, a = 7, b = 10, and C = 60°. What is the length of side c?',
    options: ['√51', '√79', '√109', '√129'],
    correctAnswers: [1],
    explanation: 'Law of Cosines: c² = a² + b² − 2ab·cos(C) = 49 + 100 − 2(7)(10)·cos(60°) = 149 − 140·(1/2) = 149 − 70 = 79. So c = √79 ≈ 8.89. Use Law of Cosines for SAS (two sides + included angle) or SSS. Law of Sines is easier for AAS and ASA cases.',
  },
  {
    id: 'at-21', domain: 1, subdomain: 'Analytic Trigonometry', type: 'yesno', difficulty: 'medium',
    question: 'Is tan(x + π) = tan(x) true for all x in the domain of tangent?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. The tangent function has period π (unlike sine and cosine whose period is 2π). Therefore tan(x + π) = tan(x) exactly. This means tan(x + 2π) = tan(x) also holds (two periods), but the minimal period is π. This property is used to simplify expressions like tan(7π/4) = tan(7π/4 − π) = tan(3π/4).',
  },

  // ══════════════════════════════════════════════════════════════
  // Functions & Transformations — additional questions
  // ══════════════════════════════════════════════════════════════
  {
    id: 'ft-16', domain: 1, subdomain: 'Functions & Transformations', type: 'single', difficulty: 'easy',
    question: 'If f(x) = x² and g(x) = f(x − 3) + 2, what transformation describes g relative to f?',
    options: [
      'Shift left 3, shift down 2',
      'Shift right 3, shift up 2',
      'Shift left 3, shift up 2',
      'Reflect across x-axis, shift right 3',
    ],
    correctAnswers: [1],
    explanation: 'g(x) = (x−3)² + 2. Replacing x with (x−3) shifts RIGHT by 3 (horizontal shifts are counter-intuitive: x−h shifts right h units). Adding 2 outside shifts UP by 2. Vertex moves from (0,0) to (3,2). Remember the sign rule: (x−3) shifts right; (x+3) shifts left.',
  },
  {
    id: 'ft-17', domain: 1, subdomain: 'Functions & Transformations', type: 'single', difficulty: 'medium',
    question: 'If f(x) is one-to-one, what is the relationship between the graphs of f and f⁻¹?',
    options: [
      'The graph of f⁻¹ is the reflection of f across the x-axis',
      'The graph of f⁻¹ is the reflection of f across the line y = x',
      'The graph of f⁻¹ is a vertical translation of f',
      'The graphs of f and f⁻¹ are identical',
    ],
    correctAnswers: [1],
    explanation: 'The graph of f⁻¹ is the reflection of f across y = x, because if (a, b) is on f, then (b, a) is on f⁻¹ (x and y swap). If f(3) = 7, then f⁻¹(7) = 3. Graphically, reflecting over y = x swaps all (x, y) to (y, x). A function must pass the horizontal line test (be one-to-one) to have an inverse.',
  },
  {
    id: 'ft-18', domain: 1, subdomain: 'Functions & Transformations', type: 'single', difficulty: 'hard',
    question: 'Given f(x) = 2x + 5 and g(x) = x², find (f ∘ g)(3).',
    options: ['11', '23', '121', '13'],
    correctAnswers: [1],
    explanation: '(f ∘ g)(3) = f(g(3)). Step 1: g(3) = 3² = 9. Step 2: f(9) = 2(9) + 5 = 23. Note (g ∘ f)(3) = g(f(3)) = g(11) = 121 ≠ 23 — composition is NOT commutative. Always apply the inner function first. The notation f ∘ g means "f after g."',
  },
  {
    id: 'ft-19', domain: 1, subdomain: 'Functions & Transformations', type: 'multi', difficulty: 'medium',
    question: 'Which transformations change the y-intercept of y = f(x)? (Select all that apply.)',
    options: [
      'Vertical shift: y = f(x) + k for k ≠ 0',
      'Horizontal shift: y = f(x − h) for h ≠ 0',
      'Vertical stretch: y = c·f(x) for c ≠ 1',
      'Reflection across y-axis: y = f(−x)',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'y-intercept occurs at x = 0. Vertical shift changes f(0) + k. Horizontal shift changes f(0−h) = f(−h), which is generally ≠ f(0). Vertical stretch multiplies f(0) by c (changes unless f(0)=0). Reflection across y-axis: f(−0) = f(0) → y-intercept UNCHANGED. Reflections across y-axis preserve the y-intercept because x=0 maps to itself.',
  },
  {
    id: 'ft-20', domain: 1, subdomain: 'Functions & Transformations', type: 'single', difficulty: 'medium',
    question: 'What is the domain of f(x) = √(4 − x²)?',
    options: ['[−2, 2]', '(−∞, −2] ∪ [2, ∞)', '[0, 2]', 'All real numbers'],
    correctAnswers: [0],
    explanation: 'Square root requires radicand ≥ 0: 4 − x² ≥ 0 → x² ≤ 4 → −2 ≤ x ≤ 2. Domain: [−2, 2]. The graph of f(x) = √(4−x²) is the upper half of a circle with radius 2, running from (−2, 0) to (2, 0) with peak at (0, 2). Recognizing geometric shapes helps confirm domain and range quickly.',
  },

  // ══════════════════════════════════════════════════════════════
  // Exponential & Logarithmic Functions — additional questions
  // ══════════════════════════════════════════════════════════════
  {
    id: 'el-16', domain: 1, subdomain: 'Exponential & Logarithmic Functions', type: 'single', difficulty: 'easy',
    question: 'What is log₂(32)?',
    options: ['4', '5', '6', '16'],
    correctAnswers: [1],
    explanation: 'log₂(32) asks: "2 to what power equals 32?" Since 2⁵ = 32, the answer is 5. Rephrase any log as an exponent: log_b(x) = y means b^y = x. Powers of 2: 2¹=2, 2²=4, 2³=8, 2⁴=16, 2⁵=32, 2⁶=64, 2⁷=128, 2⁸=256, 2⁹=512, 2¹⁰=1024 — worth memorizing for quick mental math.',
  },
  {
    id: 'el-17', domain: 1, subdomain: 'Exponential & Logarithmic Functions', type: 'single', difficulty: 'medium',
    question: 'Which property lets you write log(x²y³) as a sum of simpler logs?',
    options: [
      'Product rule: log(AB) = log A + log B and power rule: log(Aⁿ) = n·log A',
      'Quotient rule: log(A/B) = log A − log B',
      'Change of base formula: log_a(x) = ln(x)/ln(a)',
      'Inverse property: a^(log_a x) = x',
    ],
    correctAnswers: [0],
    explanation: 'log(x²y³) = log(x²) + log(y³) [product rule] = 2log(x) + 3log(y) [power rule]. Two rules in sequence: (1) product rule splits a product inside a log into a sum; (2) power rule moves exponents in front as multipliers. These rules reverse too — sums of logs condense into a single logarithm with a product inside.',
  },
  {
    id: 'el-18', domain: 1, subdomain: 'Exponential & Logarithmic Functions', type: 'single', difficulty: 'hard',
    question: 'Solve for x: 5^(2x−1) = 125',
    options: ['x = 1', 'x = 2', 'x = 3', 'x = 4'],
    correctAnswers: [1],
    explanation: 'Write 125 as a power of 5: 125 = 5³. So 5^(2x−1) = 5³. Equal bases → equal exponents: 2x − 1 = 3 → 2x = 4 → x = 2. Verify: 5^(2·2−1) = 5³ = 125 ✓. When both sides can share the same base, equating exponents is faster than taking logarithms. Use logarithms only when bases cannot be matched.',
  },
  {
    id: 'el-19', domain: 1, subdomain: 'Exponential & Logarithmic Functions', type: 'single', difficulty: 'hard',
    question: 'A population doubles every 12 years. Starting at 5,000, when will it first reach 40,000?',
    options: ['After 24 years', 'After 36 years', 'After 40 years', 'After 48 years'],
    correctAnswers: [1],
    explanation: '5000 · 2^(t/12) = 40000 → 2^(t/12) = 8 → 2^(t/12) = 2³ → t/12 = 3 → t = 36 years. So three doublings (from 5,000 → 10,000 → 20,000 → 40,000) take 3 × 12 = 36 years. The continuous-growth form is P = P₀·e^(kt) where k = ln(2) / doubling time = ln(2)/12 ≈ 0.0578.',
  },
  {
    id: 'el-20', domain: 1, subdomain: 'Exponential & Logarithmic Functions', type: 'single', difficulty: 'medium',
    question: 'What is the inverse function of f(x) = log₃(x − 2) + 1?',
    options: [
      'f⁻¹(x) = 3^(x+1) + 2',
      'f⁻¹(x) = 3^(x−1) + 2',
      'f⁻¹(x) = log₃(x + 1) − 2',
      'f⁻¹(x) = 3^x − 1',
    ],
    correctAnswers: [1],
    explanation: 'Swap x and y then solve: x = log₃(y−2)+1 → x−1 = log₃(y−2) → 3^(x−1) = y−2 → y = 3^(x−1)+2. So f⁻¹(x) = 3^(x−1)+2. Domain of f is x > 2 (becomes range of f⁻¹). Range of f is all reals (becomes domain of f⁻¹). Inverse functions swap domain and range — always verify this relationship.',
  },

  // ══════════════════════════════════════════════════════════════
  // Vectors & Parametrics — additional questions
  // ══════════════════════════════════════════════════════════════
  {
    id: 'vp-12', domain: 1, subdomain: 'Vectors & Parametrics', type: 'single', difficulty: 'easy',
    question: 'What is the magnitude of the vector v = ⟨3, −4⟩?',
    options: ['1', '5', '7', '25'],
    correctAnswers: [1],
    explanation: '|v| = √(3² + (−4)²) = √(9 + 16) = √25 = 5. The 3-4-5 right triangle is the most common Pythagorean triple. Geometrically, magnitude is the straight-line distance from the origin to the vector tip. Magnitude is always non-negative. Unit vector in direction of v: v̂ = v/|v| = ⟨3/5, −4/5⟩.',
  },
  {
    id: 'vp-13', domain: 1, subdomain: 'Vectors & Parametrics', type: 'single', difficulty: 'medium',
    question: 'Find the dot product of u = ⟨2, 5⟩ and v = ⟨−3, 1⟩.',
    options: ['−1', '1', '−6', '7'],
    correctAnswers: [0],
    explanation: 'u · v = (2)(−3) + (5)(1) = −6 + 5 = −1. The dot product is a scalar. Key property: u · v = |u||v|cos(θ), so: zero dot product → perpendicular vectors; negative → obtuse angle (>90°) between them; positive → acute angle. Here −1 < 0, so the angle between u and v is obtuse.',
  },
  {
    id: 'vp-14', domain: 1, subdomain: 'Vectors & Parametrics', type: 'single', difficulty: 'hard',
    question: 'A particle moves with x(t) = t² − 2t, y(t) = t³ − 3t. At t = 1, what are the horizontal and vertical velocity components?',
    options: [
      'vₓ = 0, vy = 0',
      'vₓ = 2, vy = 3',
      'vₓ = 0, vy = −3',
      'vₓ = −1, vy = 0',
    ],
    correctAnswers: [0],
    explanation: 'Velocities are derivatives: vₓ = dx/dt = 2t − 2, vy = dy/dt = 3t² − 3. At t = 1: vₓ = 2(1)−2 = 0, vy = 3(1)²−3 = 0. Both velocity components are zero — the particle is instantaneously at rest at t = 1. This is a critical point in the motion; the particle could be reversing direction or at a cusp in its path.',
  },
  {
    id: 'vp-15', domain: 1, subdomain: 'Vectors & Parametrics', type: 'single', difficulty: 'medium',
    question: 'Convert polar coordinates (4, π/6) to rectangular (Cartesian) form.',
    options: [
      '(2, 2√3)',
      '(2√3, 2)',
      '(4√3, 4)',
      '(2, 4)',
    ],
    correctAnswers: [1],
    explanation: 'x = r·cos(θ) = 4·cos(π/6) = 4·(√3/2) = 2√3. y = r·sin(θ) = 4·sin(π/6) = 4·(1/2) = 2. Rectangular form: (2√3, 2) ≈ (3.46, 2). Polar-to-rectangular: x = r cos θ, y = r sin θ. Rectangular-to-polar: r = √(x²+y²), θ = arctan(y/x) with quadrant check.',
  },
  {
    id: 'vp-16', domain: 1, subdomain: 'Vectors & Parametrics', type: 'single', difficulty: 'medium',
    question: 'Eliminate the parameter from x = t + 1, y = 2t − 3 to find the rectangular equation.',
    options: [
      'y = 2x − 5',
      'y = 2x + 5',
      'y = x − 2',
      'y = x/2 − 1',
    ],
    correctAnswers: [0],
    explanation: 'From x = t+1, solve for t: t = x−1. Substitute into y = 2t−3: y = 2(x−1)−3 = 2x−2−3 = 2x−5. The rectangular equation y = 2x−5 is a line. Parametric form adds information (travel direction, speed) that rectangular form loses — critical in physics and calculus. Always verify by substituting a specific t value into both parametric and rectangular forms.',
  },
  {
    id: 'vp-17', domain: 1, subdomain: 'Vectors & Parametrics', type: 'yesno', difficulty: 'medium',
    question: 'Two vectors with the same direction but different magnitudes are considered equal vectors. True or false?',
    options: ['True', 'False'],
    correctAnswers: [1],
    explanation: 'False. Equal vectors must have both the same direction AND the same magnitude. Vectors with the same direction but different magnitude are scalar multiples of each other — parallel but not equal. Example: ⟨2,4⟩ and ⟨1,2⟩ point the same way but have magnitudes 2√5 and √5 respectively, so they are not equal.',
  },

  // ══════════════════════════════════════════════════════════════
  // Sequences & Series — additional questions
  // ══════════════════════════════════════════════════════════════
  {
    id: 'ss-11', domain: 1, subdomain: 'Sequences & Series', type: 'single', difficulty: 'easy',
    question: 'What is the sum of the finite geometric series 1 + 2 + 4 + 8 + 16?',
    options: ['28', '30', '31', '32'],
    correctAnswers: [2],
    explanation: 'Geometric series: a₁=1, r=2, n=5. Formula: Sₙ = a₁(1−rⁿ)/(1−r) = 1·(1−32)/(1−2) = (−31)/(−1) = 31. Pattern: sum of first n terms starting at 1 with ratio 2 = 2ⁿ − 1 = 32 − 1 = 31. The formula Sₙ = a₁(1−rⁿ)/(1−r) applies for any geometric series with r ≠ 1.',
  },
  {
    id: 'ss-12', domain: 1, subdomain: 'Sequences & Series', type: 'single', difficulty: 'medium',
    question: 'What condition guarantees that an infinite geometric series converges?',
    options: [
      'r > 1',
      '|r| < 1',
      'a > 0',
      'n is finite',
    ],
    correctAnswers: [1],
    explanation: 'An infinite geometric series ∑ a·rⁿ converges if and only if |r| < 1. Sum = a/(1−r). When |r| ≥ 1, terms do not approach zero and the series diverges. Example: 1 + 1/2 + 1/4 + ... has r = 1/2, sum = 1/(1−1/2) = 2. But 1 + 2 + 4 + ... has r = 2 and diverges to infinity.',
  },
  {
    id: 'ss-13', domain: 1, subdomain: 'Sequences & Series', type: 'single', difficulty: 'hard',
    question: 'Expand (x + y)⁴. What is the coefficient of the x²y² term?',
    options: ['4', '6', '8', '12'],
    correctAnswers: [1],
    explanation: 'Binomial Theorem: (x+y)⁴ = Σ C(4,k)·x^(4-k)·yᵏ. For x²y², k=2: C(4,2) = 4!/(2!·2!) = 6. Full expansion: x⁴ + 4x³y + 6x²y² + 4xy³ + y⁴. Pascal row 4: 1, 4, 6, 4, 1. The coefficient 6 is the middle term. C(n,k) counts combinations — the number of ways to choose k items from n without order.',
  },
  {
    id: 'ss-14', domain: 1, subdomain: 'Sequences & Series', type: 'single', difficulty: 'medium',
    question: 'An arithmetic sequence has a₁ = 7 and d = 3. What is the 20th term?',
    options: ['64', '67', '70', '73'],
    correctAnswers: [0],
    explanation: 'Arithmetic formula: aₙ = a₁ + (n−1)d. For n = 20: a₂₀ = 7 + (20−1)·3 = 7 + 57 = 64. Note (n−1) not n — the first term requires zero steps. After 19 steps of size 3 from 7: 7 + 57 = 64. Check: a₁=7, a₂=10, a₃=13 ... each term is 3 more than the previous.',
  },
  {
    id: 'ss-15', domain: 1, subdomain: 'Sequences & Series', type: 'single', difficulty: 'hard',
    question: 'To prove P(n) is true for all integers n ≥ 1 by mathematical induction, you must show:',
    options: [
      'P(1) is true, and if P(k) is true then P(k+1) is true',
      'P(1) and P(2) are true',
      'P(n) is true for n = 1, 2, 3, 4, and 5',
      'P(k+1) implies P(k) for all k',
    ],
    correctAnswers: [0],
    explanation: 'Mathematical induction requires exactly two steps: (1) Base case: verify P(1) is true. (2) Inductive step: assume P(k) is true (inductive hypothesis) and prove P(k+1) must also be true. Together these guarantee P(n) for ALL n ≥ 1 — like dominoes: prove the first falls (base case) and each topples the next (inductive step).',
  },
  {
    id: 'ss-17', domain: 1, subdomain: 'Sequences & Series', type: 'single', difficulty: 'medium',
    question: 'A savings account earns 6% annual interest compounded monthly. Which formula gives the balance after t years starting with $1,000?',
    options: [
      'A = 1000(1.06)^t',
      'A = 1000(1 + 0.06/12)^(12t)',
      'A = 1000·e^(0.06t)',
      'A = 1000 + 1000·0.06·t',
    ],
    correctAnswers: [1],
    explanation: 'Compound interest: A = P(1 + r/n)^(nt). Here P = 1000, r = 0.06, n = 12 (monthly), t = years. A = 1000(1.005)^(12t). Option A: annual compounding. Option C: continuous compounding (Pᵉ^(rt)). Option D: simple interest (no compounding). Monthly compounding earns more than annual because interest is credited 12× per year, each earning its own interest afterward.',
  },

  // ══════════════════════════════════════════════════════════════
  // Mixed review — spanning multiple topics
  // ══════════════════════════════════════════════════════════════
  {
    id: 'trig-28', domain: 1, subdomain: 'Trigonometric Functions', type: 'single', difficulty: 'medium',
    question: 'What is the period of y = cos(πx/2)?',
    options: ['π/2', 'π', '2', '4'],
    correctAnswers: [3],
    explanation: 'Period = 2π/|B| where B is the coefficient of x. Here y = cos(πx/2), so B = π/2. Period = 2π/(π/2) = 2π · 2/π = 4. The period of 4 means the graph completes one full wave every 4 units along the x-axis. Larger B → shorter period; smaller B → longer period.',
  },
  {
    id: 'ft-21', domain: 1, subdomain: 'Functions & Transformations', type: 'single', difficulty: 'medium',
    question: 'Which of the following represents an even function?',
    options: [
      'f(x) = x³',
      'f(x) = x² + 3',
      'f(x) = x³ + x',
      'f(x) = sin(x)',
    ],
    correctAnswers: [1],
    explanation: 'A function is even if f(−x) = f(x) for all x (symmetric about the y-axis). Test f(x) = x²+3: f(−x) = (−x)²+3 = x²+3 = f(x) ✓ — even. x³ is odd (f(−x) = −x³ = −f(x)). x³+x is odd (sum of two odd functions). sin(x) is odd. Even functions have y-axis symmetry; odd functions have origin symmetry.',
  },
  {
    id: 'el-21', domain: 1, subdomain: 'Exponential & Logarithmic Functions', type: 'single', difficulty: 'medium',
    question: 'Which is the correct change-of-base formula for log₅(12)?',
    options: [
      'log(5)/log(12)',
      'ln(5)/ln(12)',
      'log(12)/log(5)',
      'log(12−5)',
    ],
    correctAnswers: [2],
    explanation: 'Change-of-base formula: log_b(x) = log(x)/log(b) = ln(x)/ln(b). For log₅(12): log(12)/log(5) ≈ 1.079/0.699 ≈ 1.544. This formula converts any logarithm to base 10 (or natural log) so you can evaluate it on a calculator. Numerator is the argument; denominator is the base — a common order-error on exams.',
  },
  {
    id: 'at-22', domain: 1, subdomain: 'Analytic Trigonometry', type: 'single', difficulty: 'medium',
    question: 'What is the exact value of sin(π/12) using the difference formula?',
    options: [
      '(√6 − √2)/4',
      '(√6 + √2)/4',
      '(√3 − 1)/2',
      '(√2 − √3)/4',
    ],
    correctAnswers: [0],
    explanation: 'π/12 = π/3 − π/4. sin(A−B) = sinA·cosB − cosA·sinB. sin(π/3−π/4) = sin(π/3)cos(π/4) − cos(π/3)sin(π/4) = (√3/2)(√2/2) − (1/2)(√2/2) = √6/4 − √2/4 = (√6−√2)/4 ≈ 0.259. This is the same strategy used for sin(75°) but subtracted: 60°−45°=15°=π/12.',
  },
  {
    id: 'pr-22', domain: 1, subdomain: 'Polynomial & Rational Functions', type: 'single', difficulty: 'hard',
    question: 'If f(x) = x³ − 4x, how many real zeros does f have and what are they?',
    options: [
      'One zero at x = 0',
      'Two zeros at x = ±2',
      'Three zeros at x = 0, 2, −2',
      'Three zeros at x = 0, 4, −4',
    ],
    correctAnswers: [2],
    explanation: 'Factor: f(x) = x³ − 4x = x(x² − 4) = x(x−2)(x+2). Setting each factor = 0: x = 0, x = 2, x = −2. Three distinct real zeros. A degree-3 polynomial can have 1, 2, or 3 real zeros (counting multiplicity). Here all three zeros are simple (multiplicity 1), so the graph crosses the x-axis at all three points.',
  },
  {
    id: 'vp-18', domain: 1, subdomain: 'Vectors & Parametrics', type: 'single', difficulty: 'medium',
    question: 'Which polar equation describes a circle of radius 3 centered at the origin?',
    options: ['r = θ', 'r = 3', 'θ = 3', 'r = 3θ'],
    correctAnswers: [1],
    explanation: 'In polar coordinates, r = k (constant) describes a circle of radius k centered at the origin. Here r = 3 means every point is exactly 3 units from the origin — a circle of radius 3. Compare: r = acos(θ) is a circle shifted along the x-axis; r = a(1−sinθ) is a cardioid; r = aθ is a spiral.',
  },
  {
    id: 'ss-18', domain: 1, subdomain: 'Sequences & Series', type: 'single', difficulty: 'medium',
    question: 'The 5th term of a geometric sequence is 48 and the common ratio is 2. What is the first term?',
    options: ['1', '2', '3', '6'],
    correctAnswers: [2],
    explanation: 'aₙ = a₁·rⁿ⁻¹. For n=5: 48 = a₁·2⁴ = a₁·16. So a₁ = 48/16 = 3. Check: 3, 6, 12, 24, 48 ✓ — each term doubles. The formula aₙ = a₁·rⁿ⁻¹ works both forward (find later terms) and backward (find a₁ given aₙ). When working backward, divide by rⁿ⁻¹ rather than multiply.',
  },
  {
    id: 'trig-29', domain: 1, subdomain: 'Trigonometric Functions', type: 'single', difficulty: 'medium',
    question: 'On the unit circle, which quadrant contains the angle θ = 5π/4?',
    options: ['Quadrant I', 'Quadrant II', 'Quadrant III', 'Quadrant IV'],
    correctAnswers: [2],
    explanation: '5π/4 radians = 225°, which is π + π/4 — 45° past the negative x-axis into Quadrant III. In Quadrant III both sine and cosine are negative. At 225°: sin = −√2/2, cos = −√2/2. Angle position check: 0 to π/2 → Q1; π/2 to π → Q2; π to 3π/2 → Q3; 3π/2 to 2π → Q4. Since 5π/4 is between π and 3π/2, it is in Q3.',
  },
  {
    id: 'pr-23', domain: 1, subdomain: 'Polynomial & Rational Functions', type: 'single', difficulty: 'easy',
    question: 'What is the multiplicity of the zero x = 3 in f(x) = (x − 3)²(x + 1)?',
    options: ['1', '2', '3', '4'],
    correctAnswers: [1],
    explanation: 'The zero x = 3 comes from the factor (x−3)², so it has multiplicity 2. The zero x = −1 has multiplicity 1. Behavior at the zero depends on multiplicity: odd multiplicity → the graph crosses the x-axis; even multiplicity → the graph touches the x-axis and turns back (bounces). At x = 3 (mult 2), the graph touches and bounces; at x = −1 (mult 1), it crosses.',
  },
];
