// Glossary for PFIN — SC Personal Finance (11th grade).
// Terms covering all 7 subdomains of the course.

export interface GlossaryEntry {
  term: string;
  definition: string;
}

export const glossary: GlossaryEntry[] = [
  // ── Earning Income ────────────────────────────────────────────
  { term: 'Gross income',         definition: 'Total earnings before any taxes or deductions are withheld. Includes wages, salary, tips, commissions, and bonuses. Gross income is what you earn; net income is what you keep.' },
  { term: 'Net income',           definition: 'Take-home pay — the amount remaining after all taxes and deductions (federal income tax, FICA, health insurance premiums, retirement contributions) are subtracted from gross income. Always budget with net income.' },
  { term: 'W-2',                  definition: 'Wage and Tax Statement. Issued by employers each January summarizing the employee\'s total wages and taxes withheld for the prior year. Used to file your federal and state income tax return.' },
  { term: 'W-4',                  definition: 'Employee\'s Withholding Certificate. Completed by employees when starting a new job (or when financial circumstances change) to tell the employer how much federal income tax to withhold from each paycheck.' },
  { term: 'Paycheck stub',        definition: 'The document (paper or electronic) that accompanies each paycheck, itemizing gross pay, each category of deduction, net pay, and year-to-date totals for all amounts. Essential for verifying that withholding is correct.' },
  { term: 'FICA',                 definition: 'Federal Insurance Contributions Act. The payroll tax that funds Social Security (6.2% of wages) and Medicare (1.45% of wages). Both employees and employers pay equal shares, totaling 15.3% combined.' },
  { term: 'Human capital',        definition: 'The economic value of a person\'s knowledge, skills, experience, and education. Investing in human capital through education or training typically raises earning potential and broadens career opportunities over a lifetime.' },

  // ── Budgeting & Spending ──────────────────────────────────────
  { term: 'Budget',               definition: 'A plan that allocates expected income to spending categories, savings, and debt repayment over a specific time period (usually monthly). A budget makes intentional use of money rather than wondering where it went.' },
  { term: 'Needs vs. wants',      definition: 'Needs are necessities required for survival or employment — housing, food, utilities, basic transportation, and medication. Wants are discretionary expenses that improve quality of life but are not essential — dining out, streaming services, vacations.' },
  { term: 'Fixed expense',        definition: 'An expense that is the same amount each payment period — rent, car loan payment, or insurance premium. Fixed expenses are easy to budget because they don\'t fluctuate month to month.' },
  { term: 'Variable expense',     definition: 'An expense whose amount changes each period based on usage or behavior — groceries, gasoline, electricity, clothing. Variable expenses can be reduced by changing habits and are the primary target when cutting a budget.' },
  { term: 'Periodic expense',     definition: 'An expense that doesn\'t occur every month but is predictable — annual car registration, holiday gifts, semi-annual insurance premiums. Budget for these by dividing the annual cost by 12 and setting aside that amount each month.' },
  { term: '50/30/20 rule',        definition: 'A popular budgeting guideline: 50% of after-tax income to needs, 30% to wants, and 20% to savings and debt repayment. It provides a simple framework for balancing present needs with future financial security.' },
  { term: 'Opportunity cost',     definition: 'The value of the best alternative given up when making a choice. Spending $500 on a vacation has an opportunity cost of whatever else that money could have done — paying down debt, investing, or building savings.' },

  // ── Saving & Banking ─────────────────────────────────────────
  { term: 'Savings account',      definition: 'A bank or credit union deposit account designed to hold money not needed for immediate spending. Earns interest (typically low at traditional banks, higher at online banks). Insured by FDIC up to $250,000.' },
  { term: 'Checking account',     definition: 'A deposit account designed for frequent transactions — paying bills, debit card purchases, and ATM withdrawals. Generally earns little or no interest. FDIC insured. Essential for managing day-to-day spending.' },
  { term: 'Compound interest',    definition: 'Interest earned on both the original principal AND the accumulated interest from prior periods. Formula: A = P(1 + r)ⁿ. The longer the time horizon and the higher the rate, the more powerful compounding becomes — it is the foundation of long-term saving and investing.' },
  { term: 'APY',                  definition: 'Annual Percentage Yield. The effective annual return on a deposit account, accounting for the frequency of compounding. A higher compounding frequency (daily vs. monthly) produces a higher APY from the same nominal rate. Always compare APYs when choosing accounts.' },
  { term: 'FDIC',                 definition: 'Federal Deposit Insurance Corporation. A government agency that insures deposits at member banks up to $250,000 per depositor, per bank, per ownership category. If an insured bank fails, the FDIC reimburses depositors within days.' },
  { term: 'Liquidity',            definition: 'How quickly and easily an asset can be converted to cash without significant loss of value. Cash is perfectly liquid. Savings accounts are highly liquid. Real estate and CDs are less liquid. Emergency funds must be in highly liquid accounts.' },
  { term: 'Certificate of Deposit (CD)', definition: 'A savings product that pays a fixed interest rate for a fixed term (3 months to 5 years). CDs pay higher rates than regular savings accounts because you commit to leaving the money deposited. Early withdrawal typically incurs a penalty.' },

  // ── Credit & Debt ─────────────────────────────────────────────
  { term: 'Credit score',         definition: 'A numerical rating (typically 300–850 for FICO) that summarizes a person\'s creditworthiness based on their borrowing and repayment history. Lenders use it to decide whether to approve loans and what interest rate to charge.' },
  { term: 'FICO score',           definition: 'The most widely used credit scoring model, developed by Fair Isaac Corporation. Ranges 300–850. Calculated from five factors: payment history (35%), amounts owed (30%), length of credit history (15%), new credit (10%), and credit mix (10%).' },
  { term: 'Credit report',        definition: 'A detailed record of your credit history compiled by the three major bureaus (Equifax, Experian, TransUnion). Includes account information, payment history, balances, and public records. You can get one free report per bureau per year at AnnualCreditReport.com.' },
  { term: 'APR',                  definition: 'Annual Percentage Rate. The yearly cost of borrowing money, expressed as a percentage. For credit cards, APR applies to any balance carried past the due date. For loans, APR includes the interest rate plus certain fees, making it more comprehensive than the stated interest rate alone.' },
  { term: 'Secured loan',         definition: 'A loan backed by collateral — an asset the lender can seize if you default. Examples: mortgage (home as collateral), auto loan (car as collateral). Secured loans typically carry lower interest rates because the lender\'s risk is reduced.' },
  { term: 'Unsecured loan',       definition: 'A loan with no collateral backing it. Examples: credit cards, student loans, personal loans. Because the lender has no asset to reclaim, unsecured loans carry higher interest rates to compensate for the added risk.' },
  { term: 'Credit utilization',   definition: 'The percentage of your available credit currently in use: (balances ÷ credit limits) × 100. Keeping utilization below 30% is recommended to protect your credit score. Utilization is the second most important FICO factor at 30%.' },

  // ── Investing & Markets ───────────────────────────────────────
  { term: 'Stock',                definition: 'A share representing partial ownership (equity) in a corporation. Stockholders may receive dividends and benefit if the stock price rises. Stocks carry higher risk than bonds but have historically produced higher long-term returns.' },
  { term: 'Bond',                 definition: 'A debt security representing a loan from the investor to a company or government. The borrower pays fixed interest (coupon) and returns the principal at maturity. Bonds are generally less risky and earn less than stocks over the long term.' },
  { term: 'Mutual fund',          definition: 'An investment vehicle that pools money from many investors to purchase a diversified portfolio of stocks, bonds, or other securities, managed by a professional. Provides diversification with a single purchase. May be actively managed (higher fees) or passively managed (index funds).' },
  { term: 'ETF',                  definition: 'Exchange-Traded Fund. Like a mutual fund, it holds a basket of securities, but it trades on a stock exchange throughout the day like an individual stock. ETFs typically have very low fees and provide instant diversification. Ideal for beginning long-term investors.' },
  { term: 'Diversification',      definition: 'The strategy of spreading investments across different asset types, sectors, and geographies to reduce risk. When one investment loses value, others may offset the loss. Widely summarized as "don\'t put all your eggs in one basket."' },
  { term: 'Risk tolerance',       definition: 'An investor\'s ability and willingness to endure fluctuations and potential losses in exchange for higher potential returns. Depends on time horizon, financial situation, and personality. Longer time horizons allow greater risk tolerance because there is time to recover from downturns.' },
  { term: '401(k)',               definition: 'An employer-sponsored retirement savings plan. Traditional 401(k): contributions are pre-tax, reducing current taxable income; withdrawals in retirement are taxed. Roth 401(k): contributions are after-tax; qualified withdrawals are tax-free. Many employers match contributions up to a percentage of salary.' },
  { term: 'IRA',                  definition: 'Individual Retirement Account. An account individuals open independently (not through an employer) to save for retirement with tax advantages. Traditional IRA: contributions may be deductible; withdrawals taxed. Roth IRA: after-tax contributions; qualified withdrawals are tax-free.' },

  // ── Insurance & Risk Management ───────────────────────────────
  { term: 'Premium',              definition: 'The regular payment (monthly, quarterly, or annually) made to keep an insurance policy active. Premiums are owed regardless of whether you file a claim. Higher coverage limits and lower deductibles result in higher premiums.' },
  { term: 'Deductible',           definition: 'The amount you must pay out-of-pocket for covered losses before the insurance company begins paying. Example: $500 deductible on auto insurance — you pay the first $500 of repairs, insurer covers the rest. Higher deductibles = lower premiums.' },
  { term: 'Copay',                definition: 'A fixed dollar amount you pay for a specific health care service at the time of service, regardless of the total cost. Example: $25 copay for a doctor visit. Copays do not count toward the deductible in most plans.' },
  { term: 'Liability coverage',   definition: 'Insurance that pays on your behalf when you are legally responsible for causing bodily injury or property damage to someone else. Required for auto insurance in most states. Homeowner\'s and renter\'s policies also include liability coverage.' },
  { term: 'Beneficiary',         definition: 'The person or entity designated to receive the proceeds (death benefit) of a life insurance policy or retirement account when the account holder dies. Beneficiary designations override wills and must be kept updated after major life events.' },

  // ── Taxes & Government Programs ───────────────────────────────
  { term: 'Income tax',           definition: 'A tax levied by federal and most state governments on a person\'s earned and investment income. The federal income tax is progressive — higher income is taxed at higher marginal rates across a series of tax brackets.' },
  { term: 'Marginal tax rate',    definition: 'The tax rate applied to the LAST dollar of income earned — the rate of your highest tax bracket. In the U.S. progressive system, you pay the marginal rate only on income within that bracket, not on all income. Knowing your marginal rate helps evaluate deductions and credits.' },
  { term: 'Standard deduction',   definition: 'A fixed dollar amount subtracted from gross income to arrive at taxable income, available to all taxpayers who don\'t itemize. For 2024: $14,600 (single), $29,200 (married filing jointly). Most taxpayers use the standard deduction rather than itemizing.' },
  { term: 'Medicare',             definition: 'A federal health insurance program primarily for people aged 65 and older, and for certain younger individuals with disabilities. Funded through FICA payroll taxes. Consists of Part A (hospital), Part B (medical), Part C (Medicare Advantage), and Part D (prescription drugs).' },
  { term: 'Social Security',      definition: 'A federal program funded by FICA payroll taxes that provides retirement income, disability benefits, and survivor benefits. Workers earn "credits" through years of work. Retirement benefits can begin at age 62 (reduced) or up to age 70 (maximized).' },
  { term: 'Filing status',        definition: 'A category chosen on your tax return — Single, Married Filing Jointly, Married Filing Separately, Head of Household, or Qualifying Surviving Spouse — that determines your tax bracket thresholds and standard deduction. Choosing the correct status is one of the most impactful tax decisions.' },
];
