// Glossary for BIO1 — Biology 1. Terms a 9th–10th grader is expected to
// recognize on the SC EOCEP. Shown as a Glossary section in the Study Guide
// and indexed by the unified search.

export interface GlossaryEntry {
  term: string;
  definition: string;
}

export const glossary: GlossaryEntry[] = [
  // ── Cell Structure & Function ─────────────────────────────────────
  { term: 'Cell',                 definition: 'The smallest unit of life. Every living organism is made of one or more cells. The cell theory states that all cells come from pre-existing cells.' },
  { term: 'Prokaryote',           definition: 'A simple, single-celled organism with NO membrane-bound nucleus and no membrane-bound organelles. DNA floats freely in the cytoplasm. Bacteria and archaea are prokaryotes.' },
  { term: 'Eukaryote',            definition: 'A cell with a true, membrane-bound nucleus and membrane-bound organelles. Plants, animals, fungi, and protists are eukaryotes. Larger and more complex than prokaryotes.' },
  { term: 'Nucleus',              definition: 'The "control center" of a eukaryotic cell. Houses the DNA and directs protein synthesis. Surrounded by a double membrane called the nuclear envelope.' },
  { term: 'Mitochondria',         definition: 'The "powerhouse" organelles where cellular respiration occurs. Convert glucose and oxygen into ATP. Have their own DNA and a double membrane with folded inner membrane called cristae.' },
  { term: 'Chloroplast',          definition: 'The photosynthesis organelle found in plant cells and algae. Contains chlorophyll, the green pigment that captures light energy to make glucose from CO₂ and H₂O.' },
  { term: 'Ribosome',             definition: 'The protein-building site. Reads mRNA and assembles amino acids into proteins. Found in BOTH prokaryotes and eukaryotes. Can float free or attach to rough endoplasmic reticulum.' },
  { term: 'Endoplasmic reticulum',definition: 'A network of membranes that transports materials through the cell. Rough ER has ribosomes (makes proteins); smooth ER lacks ribosomes (makes lipids and detoxifies).' },
  { term: 'Golgi apparatus',      definition: 'The cell’s "shipping department." Modifies, packages, and ships proteins received from the ER. Outputs vesicles destined for the membrane or other organelles.' },
  { term: 'Lysosome',             definition: 'A "recycling center" filled with digestive enzymes. Breaks down worn-out organelles, food particles, and invading bacteria. Found mostly in animal cells.' },
  { term: 'Vacuole',              definition: 'A storage sac for water, nutrients, or waste. Plant cells have one LARGE central vacuole that helps maintain turgor pressure. Animal cells have small, scattered vacuoles.' },
  { term: 'Cell wall',            definition: 'A rigid outer layer found in plants (cellulose), fungi (chitin), and bacteria (peptidoglycan). Provides shape and structural support. Animal cells do NOT have cell walls.' },
  { term: 'Cell membrane',        definition: 'A flexible phospholipid bilayer that surrounds every cell. Selectively permeable — controls what enters and leaves. Made of two layers of phospholipids with embedded proteins.' },
  { term: 'Cytoplasm',            definition: 'The jelly-like fluid that fills the cell, holding all the organelles in place. Site of many chemical reactions, including glycolysis.' },
  { term: 'Organelle',            definition: 'A specialized structure inside a cell that performs a specific function — the cellular equivalent of an organ. Examples: nucleus, mitochondria, chloroplast, ribosome.' },
  { term: 'Diffusion',            definition: 'The passive movement of particles from high concentration to low concentration. Requires NO energy. Spreads molecules until they are evenly distributed.' },
  { term: 'Osmosis',              definition: 'The diffusion of WATER across a selectively permeable membrane, from a region of high water concentration (low solute) to low water concentration (high solute). No energy required.' },
  { term: 'Active transport',     definition: 'Movement of particles AGAINST their concentration gradient (low to high). REQUIRES energy in the form of ATP. Uses transport proteins (pumps) in the membrane.' },
  { term: 'Hypotonic solution',   definition: 'A solution with LOWER solute concentration than the cell. Water rushes INTO the cell, causing it to swell or burst. "Hypo" = low (outside).' },
  { term: 'Hypertonic solution',  definition: 'A solution with HIGHER solute concentration than the cell. Water leaves the cell, causing it to shrivel. "Hyper" = high (outside).' },
  { term: 'Isotonic solution',    definition: 'A solution with EQUAL solute concentration to the cell. Water moves in and out at the same rate. The cell maintains its shape — the ideal environment.' },

  // ── Cell Energy ───────────────────────────────────────────────────
  { term: 'Photosynthesis',       definition: 'The process plants use to make glucose from CO₂ and H₂O using light energy. Equation: 6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂. Happens in the chloroplast.' },
  { term: 'Cellular respiration', definition: 'The process of breaking down glucose to make ATP. Equation: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP. Happens in three stages: glycolysis, Krebs cycle, electron transport chain.' },
  { term: 'ATP',                  definition: 'Adenosine triphosphate — the energy currency of the cell. Releases energy when its third phosphate bond is broken (becoming ADP). Used to power nearly every cellular process.' },
  { term: 'Chlorophyll',          definition: 'The green pigment in chloroplasts that absorbs red and blue light (reflecting green, which is why plants look green). Captures light energy to start photosynthesis.' },
  { term: 'Glucose',              definition: 'A six-carbon sugar (C₆H₁₂O₆) made by photosynthesis and broken down by cellular respiration. The main fuel for most living cells.' },
  { term: 'Glycolysis',           definition: 'The first stage of cellular respiration. Happens in the CYTOPLASM. Splits one glucose into two pyruvate molecules, producing a net 2 ATP. Does NOT require oxygen.' },
  { term: 'Krebs cycle',          definition: 'The second stage of cellular respiration, also called the citric acid cycle. Happens in the mitochondrial matrix. Produces CO₂, ATP, and electron carriers (NADH, FADH₂).' },
  { term: 'Electron transport chain', definition: 'The third stage of cellular respiration. Happens in the inner mitochondrial membrane. Uses electrons from NADH/FADH₂ to make most of the ATP (~34). Requires oxygen as the final electron acceptor.' },
  { term: 'Aerobic respiration',  definition: 'Cellular respiration that REQUIRES oxygen. Produces ~36–38 ATP per glucose. The complete pathway: glycolysis + Krebs + ETC.' },
  { term: 'Anaerobic respiration / Fermentation', definition: 'Cellular respiration without oxygen. Glycolysis followed by fermentation. Produces only 2 ATP per glucose. Yeast makes alcohol; muscle cells make lactic acid.' },
  { term: 'Autotroph',            definition: 'An organism that makes its own food using energy from the sun (photosynthesis) or chemicals (chemosynthesis). Plants, algae, and some bacteria. "Self-feeders" — producers.' },
  { term: 'Heterotroph',          definition: 'An organism that gets food by consuming other organisms. Animals, fungi, most bacteria, and protozoans. "Other-feeders" — consumers and decomposers.' },
  { term: 'Enzyme',               definition: 'A protein catalyst that speeds up biochemical reactions without being consumed. Lowers the activation energy. Names usually end in "-ase" (amylase, lactase, DNA polymerase).' },
  { term: 'Substrate',            definition: 'The specific molecule that an enzyme acts upon. The enzyme\'s active site binds the substrate like a lock binds a key. Lactose is the substrate of lactase.' },

  // ── Cell Division & Reproduction ──────────────────────────────────
  { term: 'Mitosis',              definition: 'Cell division that produces two identical daughter cells, each with the same number of chromosomes as the parent. Used for growth, repair, and asexual reproduction. Phases: PMAT.' },
  { term: 'Meiosis',              definition: 'Cell division that produces four genetically unique gametes (sex cells), each with HALF the chromosomes of the parent (haploid). Includes two rounds: meiosis I and meiosis II.' },
  { term: 'Interphase',           definition: 'The longest phase of the cell cycle — the time between divisions. The cell grows, copies its DNA, and prepares for mitosis. Includes G1, S, and G2 sub-phases.' },
  { term: 'Prophase',             definition: 'First phase of mitosis. Chromatin condenses into visible chromosomes, the nuclear envelope breaks down, and the spindle fibers form.' },
  { term: 'Metaphase',            definition: 'Second phase of mitosis. Chromosomes line up at the cell’s equator (metaphase plate). The "M" in metaphase = "Middle."' },
  { term: 'Anaphase',             definition: 'Third phase of mitosis. Sister chromatids are pulled APART to opposite poles of the cell. The "A" in anaphase = "Apart."' },
  { term: 'Telophase',            definition: 'Fourth phase of mitosis. Two new nuclear envelopes form around the separated chromosomes. The cell prepares to divide.' },
  { term: 'Cytokinesis',          definition: 'The actual division of the cytoplasm and cell membrane that splits one cell into two. Happens at the end of mitosis (and meiosis). In plants, a cell plate forms; in animals, a cleavage furrow pinches in.' },
  { term: 'Chromosome',           definition: 'A tightly coiled package of DNA and proteins. Humans have 46 chromosomes (23 pairs) in each body cell. Visible under a microscope only during cell division.' },
  { term: 'Sister chromatids',    definition: 'The two identical copies of a chromosome joined at the centromere, formed during DNA replication. Separated during anaphase of mitosis (or anaphase II of meiosis).' },
  { term: 'Homologous chromosomes', definition: 'A pair of chromosomes, one from each parent, that carry the same genes in the same order (but possibly different alleles). Pair up during meiosis I.' },
  { term: 'Gamete',               definition: 'A sex cell — sperm in males, egg in females. Haploid (half the chromosome count). Produced by meiosis. In humans, gametes have 23 chromosomes.' },
  { term: 'Haploid',              definition: 'A cell containing ONE set of chromosomes (n). Gametes are haploid. In humans, n = 23.' },
  { term: 'Diploid',              definition: 'A cell containing TWO sets of chromosomes (2n) — one from each parent. Body (somatic) cells are diploid. In humans, 2n = 46.' },
  { term: 'Fertilization',        definition: 'The fusion of two gametes (sperm + egg) to form a diploid zygote. Restores the full chromosome number and combines genetic material from both parents.' },

  // ── Genetics & Heredity ───────────────────────────────────────────
  { term: 'Gene',                 definition: 'A segment of DNA that codes for a specific protein or trait. Humans have ~20,000 genes packaged into 46 chromosomes.' },
  { term: 'Allele',               definition: 'One of two or more alternative forms of a gene. For eye color, there are alleles for brown, blue, green, etc. Each parent contributes one allele per gene.' },
  { term: 'Dominant allele',      definition: 'An allele whose trait appears in the phenotype whenever it is present (homozygous OR heterozygous). Written with a capital letter (T). Masks the recessive allele.' },
  { term: 'Recessive allele',     definition: 'An allele whose trait only appears when both copies are recessive (homozygous recessive). Written with a lowercase letter (t). Hidden by any dominant allele.' },
  { term: 'Genotype',             definition: 'The actual genetic makeup — the combination of alleles. Examples: TT, Tt, tt. Two letters = the alleles inherited from each parent.' },
  { term: 'Phenotype',            definition: 'The observable trait that results from the genotype. Examples: tall, short, brown eyes, attached earlobes. What the organism looks like.' },
  { term: 'Homozygous',           definition: 'Having two IDENTICAL alleles for a gene. Either TT (homozygous dominant) or tt (homozygous recessive). Also called "purebred."' },
  { term: 'Heterozygous',         definition: 'Having two DIFFERENT alleles for a gene (Tt). Also called "hybrid." The dominant trait shows; the recessive trait is hidden but can be passed on.' },
  { term: 'Punnett square',       definition: 'A grid used to predict the genotypes and phenotypes of offspring from a genetic cross. Parent alleles go on the top and side; the cells show possible offspring combinations.' },
  { term: 'Monohybrid cross',     definition: 'A genetic cross that tracks ONE trait. Example: Tt × Tt → ratio 1 TT : 2 Tt : 1 tt (genotype), 3 dominant : 1 recessive (phenotype).' },
  { term: 'Dihybrid cross',       definition: 'A genetic cross that tracks TWO traits at once. A 4×4 Punnett square. Heterozygous parents (TtYy × TtYy) produce a 9:3:3:1 phenotype ratio in offspring.' },
  { term: 'Codominance',          definition: 'Both alleles are FULLY expressed in the heterozygote — neither is dominant over the other. Example: a red-and-white speckled flower from red × white parents.' },
  { term: 'Incomplete dominance', definition: 'The heterozygote shows a BLENDED phenotype between the two homozygotes. Example: a pink flower from red × white parents.' },
  { term: 'Sex-linked trait',     definition: 'A trait carried on the X (or Y) chromosome. Because males have only one X, recessive X-linked traits show up more often in males. Examples: color blindness, hemophilia.' },
  { term: 'Pedigree',             definition: 'A family tree diagram showing how a trait is inherited across generations. Circles are females, squares are males; filled symbols have the trait.' },

  // ── DNA & Protein Synthesis ───────────────────────────────────────
  { term: 'DNA',                  definition: 'Deoxyribonucleic acid — the molecule that stores genetic information. Double helix made of two strands of nucleotides. Bases: A, T, G, C.' },
  { term: 'Nucleotide',           definition: 'The building block of DNA and RNA. Each nucleotide has three parts: a phosphate group, a sugar (deoxyribose in DNA, ribose in RNA), and a nitrogenous base.' },
  { term: 'Base pairing rule',    definition: 'In DNA, A pairs with T and G pairs with C. In RNA, A pairs with U (uracil) instead of T. The two strands of DNA are complementary.' },
  { term: 'DNA replication',      definition: 'The process of copying DNA before cell division. The double helix unwinds; each strand serves as a template for a new complementary strand. Result: two identical DNA molecules.' },
  { term: 'Transcription',        definition: 'The process of copying a DNA gene into messenger RNA (mRNA). Happens in the nucleus. The mRNA carries the genetic instructions to the ribosome. DNA → mRNA.' },
  { term: 'Translation',          definition: 'The process of building a protein from an mRNA template. Happens at the ribosome. tRNA brings amino acids; codons (3 bases at a time) specify each amino acid. mRNA → protein.' },
  { term: 'mRNA',                 definition: 'Messenger RNA — carries the genetic code from the DNA in the nucleus to the ribosome where proteins are built. A single-stranded copy of one gene.' },
  { term: 'tRNA',                 definition: 'Transfer RNA — carries amino acids to the ribosome and matches them to mRNA codons using its anticodon. Folded into a cloverleaf shape.' },
  { term: 'Codon',                definition: 'A sequence of three mRNA bases that codes for one amino acid (or a stop signal). There are 64 possible codons coding for 20 amino acids plus start and stop.' },
  { term: 'Anticodon',            definition: 'A three-base sequence on tRNA that pairs with a complementary mRNA codon. Ensures the correct amino acid is added to the protein.' },
  { term: 'Mutation',             definition: 'A change in the DNA sequence. Can be harmful, beneficial, or neutral. Types include point mutations (single base) and frameshift mutations (insertion or deletion).' },
  { term: 'Point mutation',       definition: 'A mutation that changes a single base in the DNA. Three sub-types: silent (no change in amino acid), missense (different amino acid), nonsense (creates a stop codon).' },
  { term: 'Frameshift mutation',  definition: 'An insertion or deletion of bases that is NOT a multiple of three. Shifts the reading frame, changing every codon after the mutation. Usually devastating.' },

  // ── Evolution & Natural Selection ─────────────────────────────────
  { term: 'Evolution',            definition: 'Change in the inherited traits of a population over many generations. The unifying theory of biology, proposed by Charles Darwin and supported by overwhelming evidence.' },
  { term: 'Natural selection',    definition: 'The mechanism of evolution: individuals with favorable traits survive and reproduce more, passing those traits to the next generation. Requires variation, heritability, and differential survival.' },
  { term: 'Adaptation',           definition: 'An inherited trait that increases an organism’s fitness in its environment. Adaptations accumulate through natural selection. Examples: a thicker coat, sharper claws, camouflage coloring.' },
  { term: 'Fitness',              definition: 'In evolutionary biology, the ability to survive AND reproduce — to pass genes to the next generation. Not "fitness" in the gym sense.' },
  { term: 'Variation',            definition: 'Differences among individuals in a population. Comes from mutation, sexual reproduction (independent assortment, crossing over), and immigration. The raw material for natural selection.' },
  { term: 'Homologous structures',definition: 'Body parts with the same underlying structure but possibly different functions. Inherited from a common ancestor. Example: human arm, whale flipper, bat wing — all have the same bones.' },
  { term: 'Analogous structures', definition: 'Body parts with similar functions but DIFFERENT underlying structures. NOT inherited from a common ancestor. Example: bird wing vs. insect wing — both fly, but different evolutionary origins.' },
  { term: 'Vestigial structure',  definition: 'A body part that has lost most or all of its original function through evolution. Example: human appendix, whale pelvic bones, snake hindlimb bones. Evidence of evolutionary descent.' },
  { term: 'Fossil',               definition: 'Preserved remains or impressions of organisms that lived in the past. The fossil record documents how life has changed over billions of years. Older rock layers contain older fossils.' },
  { term: 'Speciation',           definition: 'The formation of a new species from an ancestral one, typically when populations become reproductively isolated long enough that their gene pools diverge.' },
  { term: 'Species',              definition: 'A group of organisms that can interbreed and produce fertile offspring. The basic unit of classification. A donkey and horse are different species (their offspring, mules, are sterile).' },

  // ── Ecology & Ecosystems ──────────────────────────────────────────
  { term: 'Ecosystem',            definition: 'A community of organisms (biotic factors) interacting with their physical environment (abiotic factors). Can be as small as a pond or as large as a tropical rainforest.' },
  { term: 'Biotic factor',        definition: 'A living component of an ecosystem. Animals, plants, fungi, bacteria. Anything that is or once was alive.' },
  { term: 'Abiotic factor',       definition: 'A nonliving component of an ecosystem. Water, sunlight, temperature, soil, minerals, oxygen. Shapes where organisms can live.' },
  { term: 'Population',           definition: 'A group of individuals of the SAME species living in the same area. All the largemouth bass in one lake form a population.' },
  { term: 'Community',            definition: 'All the populations of DIFFERENT species that live and interact in a given area. A forest community includes oaks, deer, squirrels, fungi, and bacteria.' },
  { term: 'Niche',                definition: 'The role and position an organism has in its environment — what it eats, where it lives, when it is active, how it reproduces. No two species can occupy exactly the same niche.' },
  { term: 'Food chain',           definition: 'A linear sequence showing who eats whom: producer → primary consumer → secondary consumer → tertiary consumer. Arrows point in the direction energy flows.' },
  { term: 'Food web',             definition: 'An interconnected network of food chains in an ecosystem. More realistic than a single food chain because most organisms eat (and are eaten by) more than one species.' },
  { term: 'Trophic level',        definition: 'A feeding position in a food chain. Producers (level 1), primary consumers (2), secondary consumers (3), tertiary consumers (4), apex predators at the top.' },
  { term: 'Energy pyramid',       definition: 'A diagram showing energy transfer between trophic levels. Only about 10% of energy passes from one level to the next; the other 90% is lost mostly as heat.' },
  { term: '10% rule',             definition: 'About 10% of the energy stored in one trophic level is transferred to the next. Explains why food chains rarely have more than 4–5 levels — there’s not enough energy at the top.' },
  { term: 'Mutualism',            definition: 'A symbiotic relationship where BOTH species benefit. Examples: clownfish and sea anemone, bees and flowers, gut bacteria and humans.' },
  { term: 'Commensalism',         definition: 'A symbiotic relationship where ONE species benefits and the other is unaffected. Examples: barnacles on a whale, birds nesting in trees.' },
  { term: 'Parasitism',           definition: 'A symbiotic relationship where ONE species benefits and the OTHER is HARMED. Examples: ticks on a deer, tapeworm in a human gut.' },
  { term: 'Carbon cycle',         definition: 'The movement of carbon between the atmosphere, organisms, soil, and oceans. Driven by photosynthesis (takes CO₂ in), respiration (releases CO₂), and combustion of fossil fuels.' },
  { term: 'Nitrogen cycle',       definition: 'The movement of nitrogen between the atmosphere, soil, and organisms. Bacteria fix atmospheric N₂ into forms plants can use; decomposers return nitrogen to the soil.' },
  { term: 'Water cycle',          definition: 'The continuous movement of water through evaporation, condensation, precipitation, and runoff. Driven by solar energy.' },
  { term: 'Biome',                definition: 'A large geographic area characterized by its climate and the communities of organisms that live there. Examples: tropical rainforest, desert, tundra, grassland, deciduous forest.' },
  { term: 'Succession',           definition: 'The gradual change in species composition of an ecosystem over time. Primary succession starts from bare rock; secondary succession follows a disturbance like fire.' },
  { term: 'Biodiversity',         definition: 'The variety of life in a particular ecosystem. More biodiversity usually means a more stable, resilient ecosystem. Threatened by habitat loss, pollution, and climate change.' },

  // ── Classification & Biodiversity ─────────────────────────────────
  { term: 'Taxonomy',             definition: 'The science of classifying and naming organisms. Developed by Carl Linnaeus in the 1700s. Organizes life into nested groups based on shared characteristics.' },
  { term: 'Domain',               definition: 'The BROADEST level of classification. There are three domains: Bacteria, Archaea, and Eukarya. Encompasses entire groups of organisms above the kingdom level.' },
  { term: 'Kingdom',              definition: 'The second-broadest level of classification. The six kingdoms are Archaebacteria, Eubacteria, Protista, Fungi, Plantae, and Animalia.' },
  { term: 'Binomial nomenclature',definition: 'The two-word naming system for species: Genus species. The first word is capitalized; the whole name is italicized or underlined. Example: Homo sapiens.' },
  { term: 'Cladogram',            definition: 'A branching diagram showing evolutionary relationships among organisms. Each branch point represents a common ancestor. Built from shared derived characteristics.' },
  { term: 'Phylogeny',            definition: 'The evolutionary history of a species or group. Shown visually with a phylogenetic tree or cladogram.' },
  { term: 'Dichotomous key',      definition: 'An identification tool with paired (di- = two) choices at each step. Follow the choices that match your specimen and you arrive at its identity.' },
  { term: 'Characteristics of life', definition: 'The seven features all living things share: made of cells, reproduce, respond to stimuli, grow and develop, use energy, maintain homeostasis, and evolve.' },

  // ── Homeostasis & Body Systems ───────────────────────────────────
  { term: 'Homeostasis',          definition: 'The maintenance of stable internal conditions despite changes in the external environment. Examples: keeping body temperature near 37°C, blood glucose around 90 mg/dL, blood pH near 7.4.' },
  { term: 'Negative feedback',    definition: 'A regulatory loop where a change triggers a response that REVERSES the change, restoring the set point. Most homeostatic mechanisms (thermoregulation, glucose control) work this way. The thermostat is the classic example.' },
  { term: 'Positive feedback',    definition: 'A regulatory loop where a change triggers a response that AMPLIFIES the change. Less common than negative feedback. Examples: childbirth contractions, blood clotting, lactation.' },
  { term: 'Levels of organization', definition: 'The hierarchy of structure in living things: atom → molecule → organelle → cell → tissue → organ → organ system → organism → population → community → ecosystem → biosphere.' },
  { term: 'Tissue',               definition: 'A group of similar cells working together to perform a specific function. Four main animal tissue types: epithelial (covering), connective (support), muscle (contraction), nervous (signaling).' },
  { term: 'Organ',                definition: 'A structure made of two or more tissue types working together to perform specific functions. Examples: heart (pumps blood), stomach (digests food), kidney (filters waste).' },
  { term: 'Organ system',         definition: 'A group of organs working together to perform a major body function. Examples: digestive system (mouth, esophagus, stomach, intestines), circulatory system (heart, blood vessels).' },
  { term: 'Stimulus',             definition: 'Any change in the environment that triggers a response in an organism. Light, temperature, sound, touch, chemicals can all be stimuli. Living things characteristically respond to stimuli.' },

  // ── Scientific Inquiry & Lab Skills ──────────────────────────────
  { term: 'Scientific method',    definition: 'A systematic process for investigating questions: observe → ask a question → form a hypothesis → design an experiment → collect data → analyze results → draw conclusions → share findings.' },
  { term: 'Hypothesis',           definition: 'A testable explanation for an observation, usually phrased as "If [I do X], then [Y will happen] because [Z]." Must be falsifiable — there must be a way to prove it wrong.' },
  { term: 'Theory',               definition: 'A well-substantiated explanation of some aspect of the natural world that integrates many confirmed observations, hypotheses, and laws. Examples: theory of evolution, cell theory, atomic theory. NOT a guess.' },
  { term: 'Scientific law',       definition: 'A statement describing a pattern observed in nature, usually expressible mathematically. Tells WHAT happens, not WHY. Example: law of gravity, law of conservation of mass.' },
  { term: 'Independent variable', definition: 'The variable the experimenter changes on purpose to see its effect. Goes on the x-axis of a graph. Sometimes called the manipulated or explanatory variable.' },
  { term: 'Dependent variable',   definition: 'The variable the experimenter MEASURES — the one that responds to (depends on) changes in the independent variable. Goes on the y-axis. Sometimes called the responding or outcome variable.' },
  { term: 'Control variable',     definition: 'A factor kept CONSTANT throughout an experiment so that it does not affect the outcome. Also called controlled variable or constant. Different from a control group.' },
  { term: 'Control group',        definition: 'The group in an experiment that does NOT receive the experimental treatment. Provides a baseline for comparison. The experimental group gets the treatment.' },
  { term: 'Observation',          definition: 'Information gathered through the senses (or instruments that extend the senses). Two types: qualitative (descriptive — "the liquid is blue") and quantitative (numerical — "the liquid is 5.2 mL").' },
  { term: 'Inference',            definition: 'A logical conclusion drawn from observations and prior knowledge. Different from observation: "There are tracks in the snow" is an observation; "A deer walked through here" is an inference.' },
  { term: 'Microscope',           definition: 'An instrument that uses lenses to magnify small objects. Compound light microscopes magnify up to about 1000× (cells visible). Electron microscopes can reach 1,000,000× (organelles, viruses).' },
];
