// Question bank for BIO1 — SC Biology 1 (9th/10th grade). Targets the SC
// End-of-Course Examination Program (EOCEP) for Biology 1.

export type QuestionType = 'single' | 'multi' | 'ordering' | 'yesno' | 'match' | 'hot-area' | 'case-study';

export interface Question {
  id: string;
  domain: 1;            // single domain — the EOCEP is one combined exam
  subdomain: string;
  type: QuestionType;
  difficulty: 'easy' | 'medium' | 'hard';
  question: string;
  options: string[];
  correctAnswers: number[];
  explanation: string;
  codeSnippet?: string;
  examTip?: string;
  match?: { leftItems: string[]; rightItems: string[]; correctPairs: [number, number][] };
  hotArea?: { svg: string; targets: { id: string; label: string }[]; correctTargetIds: string[]; selectAll?: boolean };
  caseStudy?: { scenario: string; subQuestions: { question: string; options: string[]; type: 'single' | 'multi'; correctAnswers: number[] }[] };
}

export const questions: Question[] = [
  // ══════════════════════════════════════════════════════════════════
  // Cells & Cell Processes
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'cell-01',
    domain: 1,
    subdomain: 'Cells & Cell Processes',
    type: 'single',
    difficulty: 'easy',
    question: 'Which organelle is responsible for producing most of the ATP in a eukaryotic cell?',
    options: [
      'Nucleus',
      'Ribosome',
      'Mitochondrion',
      'Golgi apparatus',
    ],
    correctAnswers: [2],
    explanation: 'The mitochondrion is the site of aerobic cellular respiration, where glucose and oxygen are converted into roughly 36–38 ATP per glucose molecule. The nucleus stores DNA, ribosomes build proteins, and the Golgi apparatus packages proteins — none of those produce significant ATP. The nickname "powerhouse of the cell" exists for exactly this reason.',
  },
  {
    id: 'cell-02',
    domain: 1,
    subdomain: 'Cells & Cell Processes',
    type: 'single',
    difficulty: 'easy',
    question: 'What is the main structural difference between a prokaryotic cell and a eukaryotic cell?',
    options: [
      'Prokaryotes have ribosomes; eukaryotes do not.',
      'Eukaryotes have a membrane-bound nucleus; prokaryotes do not.',
      'Eukaryotes have DNA; prokaryotes do not.',
      'Prokaryotes have a cell membrane; eukaryotes do not.',
    ],
    correctAnswers: [1],
    explanation: 'The defining feature is the presence of a membrane-bound nucleus (and other membrane-bound organelles) in eukaryotes. Both cell types have DNA, ribosomes, and a cell membrane — those are not the difference. Prokaryotes (bacteria, archaea) keep their DNA floating in a region called the nucleoid; eukaryotes wall it off inside a nuclear envelope.',
  },
  {
    id: 'cell-03',
    domain: 1,
    subdomain: 'Cells & Cell Processes',
    type: 'single',
    difficulty: 'easy',
    question: 'Which structure controls what enters and leaves the cell?',
    options: [
      'Nuclear envelope',
      'Cell wall',
      'Cell membrane',
      'Endoplasmic reticulum',
    ],
    correctAnswers: [2],
    explanation: 'The cell membrane (plasma membrane) is the selectively permeable phospholipid bilayer that controls movement of substances into and out of every cell. The cell wall (in plants, fungi, and bacteria) provides structural support but is not selectively permeable. The nuclear envelope controls movement into and out of the nucleus specifically, not the cell as a whole.',
  },
  {
    id: 'cell-04',
    domain: 1,
    subdomain: 'Cells & Cell Processes',
    type: 'single',
    difficulty: 'easy',
    question: 'The cell membrane is best described as which type of structure?',
    options: [
      'A single layer of carbohydrates',
      'A phospholipid bilayer with embedded proteins',
      'A solid sheet of cellulose',
      'A network of DNA strands',
    ],
    correctAnswers: [1],
    explanation: 'The cell membrane is a phospholipid bilayer — two layers of phospholipids with their hydrophilic heads facing outward (toward water) and hydrophobic tails facing inward. Embedded proteins act as channels, pumps, and receptors. Cellulose is the polysaccharide that makes up plant cell WALLS, not the membrane. The fluid-mosaic model describes this arrangement.',
  },
  {
    id: 'cell-05',
    domain: 1,
    subdomain: 'Cells & Cell Processes',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are found in PLANT cells but NOT in animal cells? Select ALL that apply.',
    options: [
      'Cell wall',
      'Mitochondria',
      'Chloroplasts',
      'Large central vacuole',
      'Nucleus',
    ],
    correctAnswers: [0, 2, 3],
    explanation: 'Plant cells uniquely have a cellulose cell wall, chloroplasts for photosynthesis, and a single large central vacuole that maintains turgor pressure. Animal cells have small scattered vacuoles instead. Mitochondria and the nucleus are present in BOTH plant and animal cells — both are eukaryotes. The trap: mitochondria might feel like a "plant thing" but plants do cellular respiration too, just in addition to photosynthesis.',
  },
  {
    id: 'cell-06',
    domain: 1,
    subdomain: 'Cells & Cell Processes',
    type: 'single',
    difficulty: 'medium',
    question: 'A red blood cell is placed in pure distilled water. What is most likely to happen?',
    options: [
      'The cell will shrink as water leaves it.',
      'The cell will remain unchanged.',
      'The cell will swell and may burst.',
      'The cell will divide by mitosis.',
    ],
    correctAnswers: [2],
    explanation: 'Distilled water has essentially zero solute concentration, making it hypotonic compared to the inside of the red blood cell. Water moves by osmosis from high water concentration (outside) to low water concentration (inside the cell), so the cell swells. Animal cells lack a cell wall, so they have nothing to resist the swelling and can lyse (burst). Plant cells in the same situation would become turgid but not burst because the cell wall holds them in.',
  },
  {
    id: 'cell-07',
    domain: 1,
    subdomain: 'Cells & Cell Processes',
    type: 'single',
    difficulty: 'medium',
    question: 'A cell is actively pumping sodium ions out against the concentration gradient. This transport requires —',
    options: [
      'Only a concentration gradient',
      'ATP (energy)',
      'Osmosis',
      'Diffusion through the lipid bilayer',
    ],
    correctAnswers: [1],
    explanation: 'Movement against the concentration gradient (low → high) defines active transport, which always requires ATP because it works "uphill" against natural diffusion. Passive transport (diffusion, osmosis, facilitated diffusion) moves substances down the gradient and requires no energy. The sodium-potassium pump is the textbook example of active transport.',
  },
  {
    id: 'cell-08',
    domain: 1,
    subdomain: 'Cells & Cell Processes',
    type: 'single',
    difficulty: 'medium',
    question: 'Which sequence correctly orders the phases of mitosis?',
    options: [
      'Metaphase, Prophase, Telophase, Anaphase',
      'Prophase, Metaphase, Anaphase, Telophase',
      'Anaphase, Telophase, Prophase, Metaphase',
      'Prophase, Anaphase, Metaphase, Telophase',
    ],
    correctAnswers: [1],
    explanation: 'The mitosis phases are Prophase (chromatin condenses, nuclear envelope breaks down), Metaphase (chromosomes line up at the middle), Anaphase (sister chromatids pull apart toward the poles), Telophase (new nuclear envelopes form). The mnemonic PMAT preserves the order. Cytokinesis (cell splitting) follows. Memory tricks: Metaphase = Middle, Anaphase = Apart.',
  },
  {
    id: 'cell-09',
    domain: 1,
    subdomain: 'Cells & Cell Processes',
    type: 'single',
    difficulty: 'medium',
    question: 'During which phase of mitosis do sister chromatids separate and move to opposite poles of the cell?',
    options: [
      'Prophase',
      'Metaphase',
      'Anaphase',
      'Telophase',
    ],
    correctAnswers: [2],
    explanation: 'Anaphase is when sister chromatids are pulled apart toward opposite poles of the cell by the spindle fibers. The "A" memory trick (Apart) helps. Prophase compacts the chromosomes; metaphase aligns them at the middle; telophase reforms the nuclear envelopes around the separated chromatids. Each pole ends up with a complete set of chromosomes, ready for cytokinesis.',
  },
  {
    id: 'cell-10',
    domain: 1,
    subdomain: 'Cells & Cell Processes',
    type: 'single',
    difficulty: 'medium',
    question: 'Cancer is best described as —',
    options: [
      'An infection caused by viruses or bacteria',
      'Uncontrolled cell division that bypasses normal cell-cycle checkpoints',
      'A failure of meiosis to produce gametes',
      'A nutritional deficiency in body cells',
    ],
    correctAnswers: [1],
    explanation: 'Cancer arises when mutations disable the cell-cycle checkpoints that normally halt division when DNA is damaged or when cells should not divide. The result is uncontrolled mitosis, forming tumors. While some cancers are linked to viruses (e.g., HPV) or environmental factors, the defining biological feature is loss of cell-cycle regulation — not infection or nutrient deficiency.',
  },
  {
    id: 'cell-11',
    domain: 1,
    subdomain: 'Cells & Cell Processes',
    type: 'single',
    difficulty: 'hard',
    question: 'A scientist observes that a cell from an unknown organism has a cell wall, ribosomes, and circular DNA in its cytoplasm but no membrane-bound organelles. The cell is most likely —',
    options: [
      'A plant cell',
      'An animal cell',
      'A bacterium (prokaryote)',
      'A fungal cell',
    ],
    correctAnswers: [2],
    explanation: 'The combination — cell wall, ribosomes, CIRCULAR DNA floating in the cytoplasm, no membrane-bound organelles — is diagnostic for a bacterium (prokaryote). Plant and fungal cells have cell walls but are EUKARYOTIC, with membrane-bound organelles and linear chromosomes inside a nucleus. Animal cells have no cell wall. Circular DNA + no nucleus is the prokaryote tell.',
  },
  {
    id: 'cell-12',
    domain: 1,
    subdomain: 'Cells & Cell Processes',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Does osmosis require energy from ATP?',
    options: ['Yes', 'No'],
    correctAnswers: [1],
    explanation: 'No — osmosis is a form of passive transport, specifically the diffusion of water across a selectively permeable membrane. It moves water from high water concentration to low water concentration (down its gradient) and requires no energy. Only active transport, which moves substances AGAINST the gradient, needs ATP.',
  },
  {
    id: 'cell-13',
    domain: 1,
    subdomain: 'Cells & Cell Processes',
    type: 'single',
    difficulty: 'hard',
    question: 'A plant cell is placed in a HYPERTONIC solution. Which best describes what happens?',
    options: [
      'The cell swells and bursts.',
      'The cell shrinks and pulls away from the cell wall (plasmolysis).',
      'The cell remains exactly the same.',
      'The cell undergoes mitosis to compensate.',
    ],
    correctAnswers: [1],
    explanation: 'In a hypertonic solution, the outside has MORE solute (less water) than inside the cell, so water moves OUT by osmosis. In a plant cell, the membrane and cytoplasm shrink while the rigid cell wall holds its shape — the membrane pulls away from the wall in a process called plasmolysis. An animal cell would shrivel (crenate) but plant cells uniquely show plasmolysis because of the wall.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Biochemistry & Energy
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'bio-01',
    domain: 1,
    subdomain: 'Biochemistry & Energy',
    type: 'single',
    difficulty: 'easy',
    question: 'Which equation correctly summarizes photosynthesis?',
    options: [
      'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + energy',
      '6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂',
      '6O₂ + 6H₂O → C₆H₁₂O₆ + light',
      'C₆H₁₂O₆ → 6CO₂ + 6H₂O',
    ],
    correctAnswers: [1],
    explanation: 'Photosynthesis takes carbon dioxide and water, plus light energy, and produces glucose (C₆H₁₂O₆) and oxygen. The first option is cellular RESPIRATION, the reverse process. Memorize the reactants (CO₂ + H₂O + light) and products (glucose + O₂) — the EOCEP loves to ask you to identify the equation or its components.',
  },
  {
    id: 'bio-02',
    domain: 1,
    subdomain: 'Biochemistry & Energy',
    type: 'single',
    difficulty: 'easy',
    question: 'Which equation correctly summarizes aerobic cellular respiration?',
    options: [
      '6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂',
      'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP',
      '6O₂ → 6CO₂',
      'ATP → ADP + light',
    ],
    correctAnswers: [1],
    explanation: 'Aerobic cellular respiration takes glucose and oxygen and produces carbon dioxide, water, and ATP. It is the reverse of photosynthesis: photosynthesis stores energy in glucose; respiration releases that energy as ATP. The first equation is photosynthesis. Cellular respiration produces about 36–38 ATP per glucose molecule under aerobic conditions.',
  },
  {
    id: 'bio-03',
    domain: 1,
    subdomain: 'Biochemistry & Energy',
    type: 'single',
    difficulty: 'easy',
    question: 'What is the primary function of ATP in a cell?',
    options: [
      'To store hereditary information',
      'To act as a structural component of membranes',
      'To serve as the immediate energy currency for cellular reactions',
      'To carry oxygen through the bloodstream',
    ],
    correctAnswers: [2],
    explanation: 'ATP (adenosine triphosphate) is the immediate energy currency of the cell. When ATP loses its third phosphate to become ADP, energy is released to power muscle contraction, active transport, protein synthesis, and nearly every cellular process. DNA stores hereditary information; phospholipids form membranes; hemoglobin carries oxygen — none of those are ATP roles.',
  },
  {
    id: 'bio-04',
    domain: 1,
    subdomain: 'Biochemistry & Energy',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are the four major classes of macromolecules in living things? Select ALL that apply.',
    options: [
      'Carbohydrates',
      'Lipids',
      'Proteins',
      'Nucleic acids',
      'Minerals',
    ],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'The four major biological macromolecules are carbohydrates (sugars, starches), lipids (fats, oils, waxes, phospholipids), proteins (made of amino acids), and nucleic acids (DNA and RNA). Minerals are inorganic ions — important for life, but not "macromolecules." Each of the four macromolecule classes has characteristic monomers: monosaccharides → carbs, fatty acids/glycerol → lipids, amino acids → proteins, nucleotides → nucleic acids.',
  },
  {
    id: 'bio-05',
    domain: 1,
    subdomain: 'Biochemistry & Energy',
    type: 'single',
    difficulty: 'medium',
    question: 'Enzymes function by —',
    options: [
      'Being permanently consumed in each chemical reaction',
      'Increasing the activation energy of a reaction',
      'Lowering the activation energy required for a reaction',
      'Producing ATP directly from sunlight',
    ],
    correctAnswers: [2],
    explanation: 'Enzymes are protein catalysts that LOWER the activation energy of a reaction without being consumed themselves. They bind a specific substrate at their active site (lock-and-key model), bring the reactants closer or destabilize bonds, and speed up the reaction. They are reusable — one enzyme can catalyze the same reaction many times. Enzyme names usually end in "-ase" (lactase digests lactose).',
  },
  {
    id: 'bio-06',
    domain: 1,
    subdomain: 'Biochemistry & Energy',
    type: 'single',
    difficulty: 'medium',
    question: 'Which property of water allows it to dissolve many ionic and polar substances, earning it the nickname "universal solvent"?',
    options: [
      'Its low density when liquid',
      'Its polarity (uneven distribution of charge)',
      'Its high boiling point',
      'Its lack of a chemical structure',
    ],
    correctAnswers: [1],
    explanation: 'Water is polar — the oxygen atom pulls electrons more strongly than the hydrogen atoms, giving the molecule a slightly negative end (O) and slightly positive end (H). This polarity lets water surround and dissolve ions and polar molecules. The other properties of water (high specific heat, ice floating, surface tension) also stem from polarity and hydrogen bonding, but the dissolving property specifically depends on polarity.',
  },
  {
    id: 'bio-07',
    domain: 1,
    subdomain: 'Biochemistry & Energy',
    type: 'single',
    difficulty: 'medium',
    question: 'Which stage of cellular respiration produces the most ATP?',
    options: [
      'Glycolysis',
      'Krebs cycle (citric acid cycle)',
      'Electron transport chain',
      'Fermentation',
    ],
    correctAnswers: [2],
    explanation: 'The electron transport chain (ETC) in the inner mitochondrial membrane produces about 34 ATP per glucose — far more than glycolysis (2 net ATP) or the Krebs cycle (2 ATP). The ETC uses electrons carried by NADH and FADH₂ from the earlier steps to pump protons and drive ATP synthase. This is why oxygen is so important: O₂ is the final electron acceptor at the end of the ETC.',
  },
  {
    id: 'bio-08',
    domain: 1,
    subdomain: 'Biochemistry & Energy',
    type: 'single',
    difficulty: 'medium',
    question: 'Where in the cell does glycolysis occur?',
    options: [
      'In the mitochondrial matrix',
      'In the cytoplasm',
      'On the inner mitochondrial membrane',
      'Inside the nucleus',
    ],
    correctAnswers: [1],
    explanation: 'Glycolysis happens in the cytoplasm — outside any organelle. It is the only stage of cellular respiration that does NOT require oxygen and is therefore common to both aerobic and anaerobic respiration. The Krebs cycle happens in the mitochondrial matrix; the electron transport chain happens on the inner mitochondrial membrane. Both of those later stages happen only if oxygen is present.',
  },
  {
    id: 'bio-09',
    domain: 1,
    subdomain: 'Biochemistry & Energy',
    type: 'single',
    difficulty: 'medium',
    question: 'During photosynthesis, the Calvin cycle (light-independent reactions) uses the products of the light-dependent reactions to —',
    options: [
      'Split water molecules to release oxygen',
      'Capture light directly to make glucose',
      'Use ATP and NADPH to fix CO₂ into glucose',
      'Pump protons across a membrane',
    ],
    correctAnswers: [2],
    explanation: 'The light-dependent reactions in the thylakoid membranes capture light energy to produce ATP and NADPH (and split water, releasing O₂). The light-INDEPENDENT (Calvin) cycle in the stroma then uses that ATP and NADPH to "fix" CO₂ (turn it from a gas into an organic molecule) and ultimately build glucose. Both stages happen in the chloroplast and depend on each other.',
  },
  {
    id: 'bio-10',
    domain: 1,
    subdomain: 'Biochemistry & Energy',
    type: 'single',
    difficulty: 'medium',
    question: 'A muscle cell during intense exercise switches to fermentation. What is the most likely reason?',
    options: [
      'It has too much oxygen.',
      'It is running out of oxygen and needs to keep making some ATP.',
      'It is undergoing photosynthesis.',
      'It has too much glucose.',
    ],
    correctAnswers: [1],
    explanation: 'During intense exercise, muscles consume oxygen faster than the blood can deliver it. Without oxygen, the electron transport chain stalls and aerobic respiration cannot continue. Muscle cells switch to lactic acid fermentation — glycolysis followed by converting pyruvate to lactic acid — to regenerate NAD⁺ and keep glycolysis (and its 2 ATP per glucose) going. The lactic acid buildup contributes to the burning sensation.',
  },
  {
    id: 'bio-11',
    domain: 1,
    subdomain: 'Biochemistry & Energy',
    type: 'single',
    difficulty: 'hard',
    question: 'A scientist measures the rate of photosynthesis in pondweed at different temperatures. The rate increases up to about 35°C and then drops sharply. What best explains the drop?',
    options: [
      'Plants stop needing light at high temperatures.',
      'Enzymes involved in photosynthesis denature at high temperatures.',
      'Water becomes too dense to enter the leaves.',
      'CO₂ becomes unavailable above 35°C.',
    ],
    correctAnswers: [1],
    explanation: 'Enzymes have an optimal temperature range. Below it, reactions are too slow; above it, enzymes DENATURE — their three-dimensional shapes unfold, destroying the active site and disabling them. Photosynthesis depends on many enzymes (especially RuBisCO and the Calvin cycle enzymes), so when they denature the rate plummets. This is true for nearly all enzyme-driven processes in biology.',
  },
  {
    id: 'bio-12',
    domain: 1,
    subdomain: 'Biochemistry & Energy',
    type: 'yesno',
    difficulty: 'medium',
    question: 'Do plants perform cellular respiration?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes — plants do BOTH photosynthesis and cellular respiration. Photosynthesis makes glucose during the day, but every plant cell needs ATP to power its work, so plants run cellular respiration in their mitochondria 24/7. A common misconception is that plants only photosynthesize and animals only respire. In fact, photosynthesis stores energy in glucose; respiration releases that energy as ATP. Plants do both.',
  },
  {
    id: 'bio-13',
    domain: 1,
    subdomain: 'Biochemistry & Energy',
    type: 'single',
    difficulty: 'hard',
    question: 'Which set correctly pairs each macromolecule with its monomer?',
    options: [
      'Carbohydrates → amino acids; proteins → monosaccharides',
      'Proteins → amino acids; nucleic acids → nucleotides',
      'Lipids → amino acids; proteins → fatty acids',
      'Nucleic acids → monosaccharides; carbohydrates → nucleotides',
    ],
    correctAnswers: [1],
    explanation: 'Proteins are polymers of amino acids; nucleic acids (DNA, RNA) are polymers of nucleotides. The full set: carbohydrates → monosaccharides (simple sugars), lipids → fatty acids + glycerol (lipids are technically not strict polymers, but fatty acids and glycerol are their building blocks), proteins → amino acids, nucleic acids → nucleotides. This is core EOCEP content — memorize all four pairs.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Genetics & Heredity
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'gen-01',
    domain: 1,
    subdomain: 'Genetics & Heredity',
    type: 'single',
    difficulty: 'easy',
    question: 'Which scientist is credited as the founder of modern genetics through experiments on pea plants?',
    options: [
      'Charles Darwin',
      'Gregor Mendel',
      'Rosalind Franklin',
      'Louis Pasteur',
    ],
    correctAnswers: [1],
    explanation: 'Gregor Mendel, a 19th-century monk, conducted carefully controlled crosses on pea plants and discovered the principles of heredity — what we now call dominant and recessive alleles, segregation, and independent assortment. Darwin proposed natural selection; Franklin did X-ray crystallography of DNA; Pasteur worked on germ theory. Mendel\'s laws were essentially ignored until the early 1900s when scientists rediscovered his work.',
  },
  {
    id: 'gen-02',
    domain: 1,
    subdomain: 'Genetics & Heredity',
    type: 'single',
    difficulty: 'easy',
    question: 'A pea plant has the genotype Tt. Which of the following best describes the plant?',
    options: [
      'Homozygous dominant',
      'Homozygous recessive',
      'Heterozygous',
      'Haploid',
    ],
    correctAnswers: [2],
    explanation: 'Tt means the plant has two DIFFERENT alleles (one dominant T, one recessive t) — that is heterozygous by definition. Homozygous dominant would be TT; homozygous recessive would be tt. Haploid refers to a cell with one set of chromosomes (a gamete) and is unrelated to the question of how the two alleles compare. A Tt plant shows the dominant phenotype.',
  },
  {
    id: 'gen-03',
    domain: 1,
    subdomain: 'Genetics & Heredity',
    type: 'single',
    difficulty: 'easy',
    question: 'In a monohybrid cross of Tt × Tt, what is the phenotype ratio of the offspring?',
    options: [
      '1 dominant : 1 recessive',
      '3 dominant : 1 recessive',
      '1 dominant : 2 mixed : 1 recessive',
      'All dominant',
    ],
    correctAnswers: [1],
    explanation: 'A Tt × Tt cross has four equally likely outcomes: TT, Tt, Tt, tt. Three of those (TT, Tt, Tt) show the dominant phenotype; one (tt) shows the recessive. So the phenotype ratio is 3 dominant : 1 recessive. The genotype ratio is different: 1 TT : 2 Tt : 1 tt. The EOCEP often asks you to distinguish phenotype ratio from genotype ratio — read carefully.',
  },
  {
    id: 'gen-04',
    domain: 1,
    subdomain: 'Genetics & Heredity',
    type: 'single',
    difficulty: 'medium',
    question: 'A pea plant heterozygous for purple flowers (Pp) is crossed with a homozygous recessive (pp) for white flowers. What percentage of the offspring are expected to have purple flowers?',
    options: [
      '0%',
      '25%',
      '50%',
      '100%',
    ],
    correctAnswers: [2],
    explanation: 'A Pp × pp cross gives offspring genotypes 1 Pp : 1 pp — half heterozygous, half homozygous recessive. The Pp offspring show the dominant purple phenotype; the pp offspring show the recessive white phenotype. So 50% of offspring have purple flowers. This is the classic "test cross" — crossing an unknown dominant phenotype to a homozygous recessive to figure out the unknown\'s genotype.',
  },
  {
    id: 'gen-05',
    domain: 1,
    subdomain: 'Genetics & Heredity',
    type: 'single',
    difficulty: 'medium',
    question: 'Which DNA bases form the correct base pairs?',
    options: [
      'A pairs with G; T pairs with C',
      'A pairs with T; G pairs with C',
      'A pairs with C; T pairs with G',
      'A pairs with A; T pairs with T',
    ],
    correctAnswers: [1],
    explanation: 'In DNA, adenine (A) always pairs with thymine (T), held together by 2 hydrogen bonds. Guanine (G) always pairs with cytosine (C), held by 3 hydrogen bonds. This complementary base pairing is what allows DNA to be copied accurately during replication. In RNA, A pairs with uracil (U) instead of T. The pyrimidine-purine pairing rule (A-T, G-C) is foundational — memorize it.',
  },
  {
    id: 'gen-06',
    domain: 1,
    subdomain: 'Genetics & Heredity',
    type: 'single',
    difficulty: 'medium',
    question: 'What is the complementary mRNA sequence to the DNA template strand 5\'-TACGGT-3\'?',
    options: [
      'AUGCCA',
      'ATGCCA',
      'UACGGU',
      'TACGGT',
    ],
    correctAnswers: [0],
    explanation: 'Transcription pairs each DNA template base with its RNA complement: T → A, A → U (RNA uses uracil instead of thymine), C → G, G → C. So TACGGT → AUGCCA. The trap answer ATGCCA uses T instead of U (that would be DNA, not RNA). The trap UACGGU just copies T to U without pairing. AUGCCA also begins with AUG — the universal start codon — which is a nice biology check.',
  },
  {
    id: 'gen-07',
    domain: 1,
    subdomain: 'Genetics & Heredity',
    type: 'single',
    difficulty: 'medium',
    question: 'In which organelle does TRANSCRIPTION take place in a eukaryotic cell?',
    options: [
      'Ribosome',
      'Mitochondrion',
      'Nucleus',
      'Golgi apparatus',
    ],
    correctAnswers: [2],
    explanation: 'Transcription (DNA → mRNA) happens in the nucleus, where the DNA is. The mRNA then exits the nucleus through nuclear pores and travels to a ribosome for translation. Translation (mRNA → protein) happens at the ribosome — either free in the cytoplasm or attached to the rough endoplasmic reticulum. Keeping the two processes separate by location is a key feature of eukaryotic gene expression.',
  },
  {
    id: 'gen-08',
    domain: 1,
    subdomain: 'Genetics & Heredity',
    type: 'single',
    difficulty: 'medium',
    question: 'A red snapdragon (RR) is crossed with a white snapdragon (WW). All the offspring have pink flowers. This pattern best illustrates —',
    options: [
      'Codominance',
      'Incomplete dominance',
      'Sex-linked inheritance',
      'A frameshift mutation',
    ],
    correctAnswers: [1],
    explanation: 'When the heterozygote shows a BLENDED phenotype between the two homozygotes (pink between red and white), that is incomplete dominance. In codominance, BOTH alleles are fully expressed in the heterozygote (you would see red-and-white speckles, not pink). Human blood type A/B is codominance (AB has both antigens); snapdragon flower color is the classic incomplete dominance example.',
  },
  {
    id: 'gen-09',
    domain: 1,
    subdomain: 'Genetics & Heredity',
    type: 'single',
    difficulty: 'medium',
    question: 'A father is XᴬYa, where a is a recessive sex-linked allele. The mother is XᴬXᴬ. What is the chance that any of their sons will show the recessive trait?',
    options: [
      '0%',
      '25%',
      '50%',
      '100%',
    ],
    correctAnswers: [0],
    explanation: 'Sons inherit their X from the mother and Y from the father. The mother is XᴬXᴬ, so every son will get XᴬY and will NOT show the recessive trait. The father\'s Y carries no copy of the gene at all in standard sex-linked inheritance (the gene is on the X chromosome). Daughters would inherit XᴬXᴬ (one X from each parent — both A), so they are also unaffected. Carrier daughters (XᴬXa) would require an Xa mother.',
  },
  {
    id: 'gen-10',
    domain: 1,
    subdomain: 'Genetics & Heredity',
    type: 'single',
    difficulty: 'medium',
    question: 'Why do males show X-linked recessive traits more often than females?',
    options: [
      'Males have stronger immune systems.',
      'Males have only one X chromosome, so a single recessive allele is enough to show the trait.',
      'Recessive alleles only appear in males.',
      'Females do not inherit X chromosomes.',
    ],
    correctAnswers: [1],
    explanation: 'Males have one X and one Y (XY). If the X carries a recessive allele, there is no second X to mask it — the trait shows. Females have two Xs (XX) and would need BOTH copies recessive to show the trait. This is why color blindness, hemophilia, and Duchenne muscular dystrophy appear far more often in males. Females with one recessive copy are called carriers — phenotypically normal but able to pass the allele on.',
  },
  {
    id: 'gen-11',
    domain: 1,
    subdomain: 'Genetics & Heredity',
    type: 'multi',
    difficulty: 'hard',
    question: 'Which of the following are examples of mutations? Select ALL that apply.',
    options: [
      'A single DNA base is changed from A to G.',
      'Three bases are inserted into the middle of a gene.',
      'A chromosome is duplicated, leading to an extra copy.',
      'A cell finishes mitosis and produces two identical daughter cells.',
      'A single base is deleted, shifting the reading frame.',
    ],
    correctAnswers: [0, 1, 2, 4],
    explanation: 'Mutations are any heritable changes to the DNA sequence. Point mutations (single-base substitutions like A→G), insertions, deletions, and chromosomal duplications all qualify. Adding three bases is an in-frame insertion; deleting one base is a frameshift mutation. Normal mitosis producing identical daughter cells is NOT a mutation — it is faithful copying. The trap answer relies on confusing "change" with "mutation."',
  },
  {
    id: 'gen-12',
    domain: 1,
    subdomain: 'Genetics & Heredity',
    type: 'single',
    difficulty: 'hard',
    question: 'A frameshift mutation occurs when —',
    options: [
      'A single base is changed but the amino acid sequence is unaffected.',
      'A multiple-of-three number of bases is inserted, preserving the reading frame.',
      'One or two bases are inserted or deleted, shifting the reading frame and changing every codon afterward.',
      'A whole chromosome is duplicated during meiosis.',
    ],
    correctAnswers: [2],
    explanation: 'A frameshift mutation involves inserting or deleting bases in a number NOT divisible by three. Because the ribosome reads codons in groups of three, a shift of one or two bases changes the reading frame, so every subsequent codon is different from the original. The result is usually a completely non-functional protein, which is why frameshift mutations are typically much more harmful than point mutations.',
  },
  {
    id: 'gen-13',
    domain: 1,
    subdomain: 'Genetics & Heredity',
    type: 'single',
    difficulty: 'hard',
    question: 'A dihybrid cross between two heterozygous parents (TtYy × TtYy) yields what phenotype ratio of offspring?',
    options: [
      '1 : 1 : 1 : 1',
      '3 : 1',
      '9 : 3 : 3 : 1',
      '1 : 2 : 1',
    ],
    correctAnswers: [2],
    explanation: 'The classic Mendelian dihybrid cross result is 9 : 3 : 3 : 1 — 9 with both dominant traits, 3 with first dominant + second recessive, 3 with first recessive + second dominant, and 1 with both recessive. This emerges because each gene independently follows the 3:1 monohybrid pattern, and (3:1) × (3:1) = 9:3:3:1. This assumes independent assortment — that the two genes are on different chromosomes or far apart.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Evolution & Natural Selection
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'evo-01',
    domain: 1,
    subdomain: 'Evolution & Natural Selection',
    type: 'single',
    difficulty: 'easy',
    question: 'Who proposed the theory of evolution by natural selection in "On the Origin of Species" (1859)?',
    options: [
      'Gregor Mendel',
      'Charles Darwin',
      'Carl Linnaeus',
      'Watson and Crick',
    ],
    correctAnswers: [1],
    explanation: 'Charles Darwin published "On the Origin of Species" in 1859 after observing variation in finches, tortoises, and other species during his voyage on HMS Beagle (especially in the Galápagos Islands). Alfred Russel Wallace arrived at similar conclusions independently, and the two presented their work jointly in 1858. Mendel did genetics; Linnaeus founded taxonomy; Watson and Crick described DNA structure.',
  },
  {
    id: 'evo-02',
    domain: 1,
    subdomain: 'Evolution & Natural Selection',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are required conditions for natural selection to occur? Select ALL that apply.',
    options: [
      'Variation among individuals',
      'Inheritance of traits from parent to offspring',
      'All individuals reproducing at the same rate',
      'Differential survival or reproduction based on traits',
      'A constant unchanging environment',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'Natural selection requires three things: (1) variation among individuals (some heritable trait differs), (2) inheritance — those traits can be passed to offspring, (3) differential survival or reproduction — individuals with certain traits leave more offspring. Equal reproduction is the OPPOSITE of natural selection. A constant environment is not required — in fact, environmental change often drives selection.',
  },
  {
    id: 'evo-03',
    domain: 1,
    subdomain: 'Evolution & Natural Selection',
    type: 'single',
    difficulty: 'medium',
    question: 'In evolutionary biology, "fitness" is best defined as —',
    options: [
      'How strong or fast an organism is',
      'How long an organism lives',
      'An organism\'s ability to survive AND reproduce, passing genes to the next generation',
      'How large an organism grows',
    ],
    correctAnswers: [2],
    explanation: 'Evolutionary fitness has nothing to do with gym fitness. It measures reproductive success — how many viable offspring an individual leaves. A small bird that produces many surviving chicks has higher fitness than a large strong bird with no chicks. Survival matters because you must live long enough to reproduce, but ultimately fitness is measured in heritable copies left in the next generation.',
  },
  {
    id: 'evo-04',
    domain: 1,
    subdomain: 'Evolution & Natural Selection',
    type: 'single',
    difficulty: 'medium',
    question: 'Which of these is NOT considered direct evidence for evolution?',
    options: [
      'The fossil record',
      'Homologous structures across species',
      'Similar DNA sequences across related species',
      'The law of gravity',
      'Vestigial structures like the human appendix',
    ],
    correctAnswers: [3],
    explanation: 'The law of gravity is a physics principle and has nothing to do with biological evolution. The other four are core evolutionary evidence: fossils document change through time, homologous structures (same bones in different functions — human arm, whale flipper, bat wing) show common ancestry, molecular similarity in DNA quantifies relatedness, and vestigial structures (appendix, whale pelvic bones) are leftovers from ancestors.',
  },
  {
    id: 'evo-05',
    domain: 1,
    subdomain: 'Evolution & Natural Selection',
    type: 'single',
    difficulty: 'medium',
    question: 'A bird\'s wing and an insect\'s wing both allow flight but have completely different internal anatomy. They are best described as —',
    options: [
      'Homologous structures',
      'Analogous structures',
      'Vestigial structures',
      'Identical structures',
    ],
    correctAnswers: [1],
    explanation: 'Analogous structures have similar FUNCTIONS but different underlying anatomy and evolutionary origins — they evolved independently because flight is useful in both lineages (convergent evolution). Bird wings are modified vertebrate forelimbs with bones; insect wings are membrane outgrowths with no bones at all. Homologous structures (like vertebrate forelimbs across mammals) share anatomy because of common ancestry — opposite kind of evidence.',
  },
  {
    id: 'evo-06',
    domain: 1,
    subdomain: 'Evolution & Natural Selection',
    type: 'single',
    difficulty: 'medium',
    question: 'The presence of nearly identical limb bone arrangements in humans, whales, bats, and horses is best explained by —',
    options: [
      'These animals all need to swim.',
      'They share a common vertebrate ancestor with that limb structure.',
      'They were all designed for the same purpose.',
      'Coincidence — there is no pattern.',
    ],
    correctAnswers: [1],
    explanation: 'These are HOMOLOGOUS structures — same underlying bones in completely different functions (grasping, swimming, flying, running). The most parsimonious explanation is descent from a common vertebrate ancestor with that limb plan. Each lineage then modified the structure for its environment. This is some of the strongest comparative-anatomy evidence for evolution. The "different functions" rules out shared selective pressure as the explanation.',
  },
  {
    id: 'evo-07',
    domain: 1,
    subdomain: 'Evolution & Natural Selection',
    type: 'single',
    difficulty: 'medium',
    question: 'A population of moths lives in a forest where tree bark has darkened due to pollution. Over several generations, the proportion of dark-colored moths in the population increases. This is an example of —',
    options: [
      'Lamarckian evolution (use and disuse)',
      'Natural selection favoring better camouflage',
      'Mitosis producing dark moths',
      'Random genetic mutation with no selection',
    ],
    correctAnswers: [1],
    explanation: 'On dark bark, dark moths are better camouflaged from bird predators, so they survive and reproduce more — passing the dark allele on. The frequency of the dark trait rises across generations. This is the famous peppered moth case. Lamarck wrongly proposed that traits acquired during life (use and disuse) could be inherited; Darwin\'s correct mechanism is selection acting on heritable variation.',
  },
  {
    id: 'evo-08',
    domain: 1,
    subdomain: 'Evolution & Natural Selection',
    type: 'single',
    difficulty: 'hard',
    question: 'Two populations of the same species become geographically isolated by a river. Over thousands of generations, they accumulate different mutations and can no longer interbreed when reunited. This process is called —',
    options: [
      'Mitosis',
      'Speciation',
      'Convergent evolution',
      'Mutation pressure',
    ],
    correctAnswers: [1],
    explanation: 'Speciation is the formation of a new species — typically when two populations are reproductively isolated long enough that their gene pools diverge until they can no longer produce fertile offspring with each other. Geographic isolation (allopatric speciation) is the most common driver. Convergent evolution is when DIFFERENT species evolve similar traits independently (analogous structures) — different mechanism, different outcome.',
  },
  {
    id: 'evo-09',
    domain: 1,
    subdomain: 'Evolution & Natural Selection',
    type: 'single',
    difficulty: 'hard',
    question: 'Whales have small, internal pelvic bones with no apparent function. These are best classified as —',
    options: [
      'Vestigial structures',
      'Homologous structures',
      'Analogous structures',
      'Newly evolved structures',
    ],
    correctAnswers: [0],
    explanation: 'Vestigial structures are remnants from an evolutionary ancestor that have lost their original function. Whale pelvic bones are leftovers from a land-living ancestor that walked on legs — evidence that whales descended from terrestrial mammals. The human appendix, blind cave fish eyes, and snake hindlimb bones are other examples. They are still technically homologous to their ancestral equivalents, but the vestigial label specifically points to the lost-function aspect.',
  },
  {
    id: 'evo-10',
    domain: 1,
    subdomain: 'Evolution & Natural Selection',
    type: 'yesno',
    difficulty: 'medium',
    question: 'Does natural selection act directly on individual organisms within their own lifetimes?',
    options: ['Yes', 'No'],
    correctAnswers: [1],
    explanation: 'No — natural selection acts on POPULATIONS over generations, not on individuals during their lifetimes. An individual cannot evolve. What happens is that within a population, individuals with favorable heritable traits leave more offspring, so the frequency of those traits rises in the NEXT generation. This is a common misconception worth correcting on the exam.',
  },
  {
    id: 'evo-11',
    domain: 1,
    subdomain: 'Evolution & Natural Selection',
    type: 'single',
    difficulty: 'hard',
    question: 'Antibiotic resistance in bacteria is an example of —',
    options: [
      'Lamarckian inheritance — bacteria learning to survive antibiotics',
      'Natural selection — resistant individuals survive and pass on resistance genes',
      'Random mutation with no consequence',
      'Convergent evolution between species',
    ],
    correctAnswers: [1],
    explanation: 'When a population of bacteria is exposed to an antibiotic, the few individuals with random mutations conferring resistance survive and reproduce, while susceptible bacteria die. Over generations, the resistant trait becomes dominant in the population. This is classical natural selection in action — the most clinically important real-world example. Bacteria do not "learn" or "choose" resistance; it is selection acting on pre-existing variation.',
  },
  {
    id: 'evo-12',
    domain: 1,
    subdomain: 'Evolution & Natural Selection',
    type: 'single',
    difficulty: 'easy',
    question: 'What is the ultimate source of new genetic variation that natural selection acts upon?',
    options: [
      'Cell division',
      'Mutation',
      'Cytokinesis',
      'Diffusion',
    ],
    correctAnswers: [1],
    explanation: 'Mutation — random changes in the DNA sequence — is the ultimate source of all new genetic variation. Mutations create new alleles; sexual reproduction (independent assortment, crossing over, random fertilization) then shuffles existing alleles into new combinations. Cell division (mitosis) makes identical copies and adds no new variation. Diffusion and cytokinesis are unrelated processes. Without mutation, there would be nothing new for selection to favor.',
  },
  {
    id: 'evo-13',
    domain: 1,
    subdomain: 'Evolution & Natural Selection',
    type: 'single',
    difficulty: 'medium',
    question: 'Why is biogeography (the geographic distribution of species) considered evidence for evolution?',
    options: [
      'Climate is the same everywhere, so species should be the same.',
      'Similar species tend to live in the same regions because of shared common ancestors, even when other regions have similar climates.',
      'Species are randomly distributed worldwide.',
      'Animals can fly anywhere, so geography is irrelevant.',
    ],
    correctAnswers: [1],
    explanation: 'Biogeographic patterns — like all marsupials being native to Australia, or finches diversifying across the Galápagos — are best explained by descent from a common ancestor within each region, modified by isolation and local selection. If species were independently created with no shared ancestry, you would expect similar climates worldwide to have similar species, but that is not what we see. Geography tracks evolutionary history.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Ecology & Ecosystems
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'eco-01',
    domain: 1,
    subdomain: 'Ecology & Ecosystems',
    type: 'single',
    difficulty: 'easy',
    question: 'In a food chain Grass → Rabbit → Fox, approximately how much energy reaches the fox if 1000 kJ enters the grass?',
    options: [
      '1000 kJ',
      '500 kJ',
      '100 kJ',
      '10 kJ',
    ],
    correctAnswers: [3],
    explanation: 'The 10% rule: about 10% of energy at one trophic level transfers to the next; the rest is lost as heat, used in metabolism, or remains in undigested material. So 1000 kJ in grass → 100 kJ in rabbits → 10 kJ in the fox. This is why food chains rarely have more than 4–5 levels — there is not enough energy left at the top to sustain another level.',
  },
  {
    id: 'eco-02',
    domain: 1,
    subdomain: 'Ecology & Ecosystems',
    type: 'single',
    difficulty: 'easy',
    question: 'Which of the following is an ABIOTIC factor in an ecosystem?',
    options: [
      'Oak tree',
      'Soil bacteria',
      'Sunlight',
      'Earthworm',
    ],
    correctAnswers: [2],
    explanation: 'Abiotic factors are the NONLIVING components of an ecosystem — sunlight, water, temperature, soil minerals, oxygen, pH. Trees, bacteria, and earthworms are alive, so they are biotic factors. Both biotic and abiotic factors shape where organisms can live. The trap "soil bacteria" works because students associate "soil" with abiotic, but bacteria themselves are living organisms.',
  },
  {
    id: 'eco-03',
    domain: 1,
    subdomain: 'Ecology & Ecosystems',
    type: 'single',
    difficulty: 'easy',
    question: 'Which of these organisms is a producer?',
    options: [
      'A wolf',
      'A mushroom',
      'A grass plant',
      'A rabbit',
    ],
    correctAnswers: [2],
    explanation: 'Producers (autotrophs) make their own food through photosynthesis — plants, algae, and some bacteria. The grass plant is the only producer here. Wolves and rabbits are consumers (heterotrophs). Mushrooms are fungi — decomposers, not producers. Producers form the base of every food chain because they are the only organisms that capture energy directly from sunlight (or, more rarely, chemical energy).',
  },
  {
    id: 'eco-04',
    domain: 1,
    subdomain: 'Ecology & Ecosystems',
    type: 'single',
    difficulty: 'medium',
    question: 'Bees pollinating flowers while collecting nectar is an example of —',
    options: [
      'Parasitism',
      'Mutualism',
      'Commensalism',
      'Competition',
    ],
    correctAnswers: [1],
    explanation: 'Mutualism is a symbiotic relationship where BOTH species benefit. Bees get food (nectar and pollen); flowers get pollinated and reproduce. Parasitism has one species benefit and the other harmed (ticks on a deer). Commensalism has one species benefit and the other unaffected (barnacles on a whale). Bees and flowers is the canonical mutualism example — both sides win.',
  },
  {
    id: 'eco-05',
    domain: 1,
    subdomain: 'Ecology & Ecosystems',
    type: 'single',
    difficulty: 'medium',
    question: 'A tapeworm lives inside the intestine of a deer, absorbing nutrients meant for the deer. This relationship is —',
    options: [
      'Mutualism',
      'Commensalism',
      'Parasitism',
      'Predation',
    ],
    correctAnswers: [2],
    explanation: 'Parasitism: one species (tapeworm) benefits while the other (deer) is harmed. The tapeworm steals nutrients and weakens the deer. Predation is different — a predator kills and eats its prey, often quickly. Parasites generally live with their host for extended periods and benefit by keeping the host alive (though sick). Mosquitoes, fleas, and tapeworms are all parasites; lions hunting zebras is predation.',
  },
  {
    id: 'eco-06',
    domain: 1,
    subdomain: 'Ecology & Ecosystems',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are biogeochemical cycles? Select ALL that apply.',
    options: [
      'Carbon cycle',
      'Nitrogen cycle',
      'Water cycle',
      'Solar cycle',
      'Mitosis cycle',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'The major biogeochemical cycles are carbon, nitrogen, phosphorus, water (hydrologic), and oxygen — the movement of essential elements between living organisms and the abiotic environment. The "solar cycle" is an astronomy term about sunspot activity (not a biogeochemical cycle). The "mitosis cycle" is not a real term — cell cycle yes, mitosis is a phase, but neither is a biogeochemical cycle.',
  },
  {
    id: 'eco-07',
    domain: 1,
    subdomain: 'Ecology & Ecosystems',
    type: 'single',
    difficulty: 'medium',
    question: 'Which group of organisms is most directly responsible for converting atmospheric nitrogen (N₂) into a form usable by plants?',
    options: [
      'Decomposing fungi',
      'Nitrogen-fixing bacteria',
      'Photosynthetic algae',
      'Earthworms',
    ],
    correctAnswers: [1],
    explanation: 'Nitrogen-fixing bacteria (often living in root nodules of legumes like clover and beans) convert atmospheric N₂ into ammonia (NH₃) or nitrates (NO₃⁻) that plants can absorb. Most organisms cannot use N₂ directly even though it makes up ~78% of the atmosphere. Decomposers recycle nitrogen from dead organisms back into the soil, and that is important, but the conversion FROM atmospheric N₂ specifically is the work of nitrogen-fixing bacteria.',
  },
  {
    id: 'eco-08',
    domain: 1,
    subdomain: 'Ecology & Ecosystems',
    type: 'single',
    difficulty: 'medium',
    question: 'A "niche" is best defined as —',
    options: [
      'The physical place where an organism lives',
      'The role and position an organism has in its environment (what it eats, when it is active, etc.)',
      'A group of the same species in one area',
      'Any group of different species in one area',
    ],
    correctAnswers: [1],
    explanation: 'Niche = role. Habitat = address. The niche includes what an organism eats, what eats it, when it is active, how it reproduces, and how it interacts with other species. The competitive exclusion principle says no two species can occupy exactly the same niche indefinitely — one will outcompete the other or they will diverge. A population is the same species in an area; a community is different species in an area.',
  },
  {
    id: 'eco-09',
    domain: 1,
    subdomain: 'Ecology & Ecosystems',
    type: 'single',
    difficulty: 'medium',
    question: 'Primary succession differs from secondary succession in that primary succession —',
    options: [
      'Happens faster',
      'Starts from bare rock with NO existing soil',
      'Always occurs in deserts',
      'Only happens in aquatic ecosystems',
    ],
    correctAnswers: [1],
    explanation: 'Primary succession starts on lifeless ground with no soil — bare rock after a volcanic eruption or retreating glacier. Pioneer species (lichens, mosses) gradually break down rock to build soil over hundreds of years. Secondary succession follows a disturbance like a fire or flood that leaves soil intact, so it proceeds much faster (decades, not centuries). The presence or absence of pre-existing soil is the key distinction.',
  },
  {
    id: 'eco-10',
    domain: 1,
    subdomain: 'Ecology & Ecosystems',
    type: 'single',
    difficulty: 'hard',
    question: 'Why is biodiversity typically higher in tropical rainforests than in tundra biomes?',
    options: [
      'Tropical rainforests have less sunlight.',
      'Tropical rainforests have warmer, wetter, more stable climates that support more producers and more niches.',
      'Tundra biomes have no living organisms.',
      'Tropical rainforests have higher elevations.',
    ],
    correctAnswers: [1],
    explanation: 'Tropical rainforests get abundant sunlight, warmth, and rainfall year-round, supporting massive productivity (many producers). High productivity supports more consumers, which creates more niches, which supports more biodiversity. Tundra biomes are cold, dark for months, and have a short growing season, limiting both producer biomass and the number of viable niches. Climate stability and resource abundance are the main drivers of biodiversity.',
  },
  {
    id: 'eco-11',
    domain: 1,
    subdomain: 'Ecology & Ecosystems',
    type: 'single',
    difficulty: 'medium',
    question: 'Which of these correctly orders levels of ecological organization from smallest to largest?',
    options: [
      'Population → Community → Ecosystem → Biome',
      'Biome → Ecosystem → Community → Population',
      'Community → Population → Biome → Ecosystem',
      'Ecosystem → Biome → Community → Population',
    ],
    correctAnswers: [0],
    explanation: 'Population (same species in one area) → Community (multiple species interacting in one area) → Ecosystem (community + abiotic factors) → Biome (large region with similar climate and communities) → Biosphere (all life on Earth). Each level is a superset of the one below. This is core ecology vocabulary — a frequent EOCEP question.',
  },
  {
    id: 'eco-12',
    domain: 1,
    subdomain: 'Ecology & Ecosystems',
    type: 'single',
    difficulty: 'medium',
    question: 'In an ecosystem, decomposers (bacteria and fungi) play the essential role of —',
    options: [
      'Making energy through photosynthesis',
      'Hunting and consuming live prey',
      'Breaking down dead organisms and returning nutrients to the soil',
      'Reproducing sexually with all other species',
    ],
    correctAnswers: [2],
    explanation: 'Decomposers break down dead organisms, fallen leaves, and waste — releasing nutrients (carbon, nitrogen, phosphorus) back into the soil so producers can reuse them. Without decomposers, nutrients would stay locked in dead material and ecosystems would grind to a halt. Decomposers are not producers (no photosynthesis) and not predators (they eat dead, not live, organisms). They are the ultimate recyclers.',
  },
  {
    id: 'eco-13',
    domain: 1,
    subdomain: 'Ecology & Ecosystems',
    type: 'yesno',
    difficulty: 'medium',
    question: 'In an energy pyramid, can the biomass of secondary consumers exceed the biomass of producers?',
    options: ['Yes', 'No'],
    correctAnswers: [1],
    explanation: 'No — because only about 10% of energy is transferred between trophic levels, the biomass of each higher level is much smaller than the level below it. Producers must vastly outnumber and outweigh secondary consumers; otherwise there is not enough energy flowing upward to sustain the higher trophic level. This is why food chains are short and apex predators are rare.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Classification & Biodiversity
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'class-01',
    domain: 1,
    subdomain: 'Classification & Biodiversity',
    type: 'single',
    difficulty: 'easy',
    question: 'Which sequence correctly lists the levels of classification from BROADEST to MOST SPECIFIC?',
    options: [
      'Species, Genus, Family, Order, Class, Phylum, Kingdom, Domain',
      'Domain, Kingdom, Phylum, Class, Order, Family, Genus, Species',
      'Kingdom, Domain, Class, Phylum, Family, Order, Species, Genus',
      'Genus, Species, Family, Order, Phylum, Class, Kingdom, Domain',
    ],
    correctAnswers: [1],
    explanation: 'The order from broadest to most specific is Domain → Kingdom → Phylum → Class → Order → Family → Genus → Species. Mnemonic: "Dear King Philip Came Over For Good Soup." Domain was added more recently (above kingdom) when scientists realized Bacteria and Archaea were biochemically very different. The first answer reverses the order (specific to broad); the third and fourth scramble levels.',
  },
  {
    id: 'class-02',
    domain: 1,
    subdomain: 'Classification & Biodiversity',
    type: 'single',
    difficulty: 'easy',
    question: 'What are the three domains of life?',
    options: [
      'Plants, Animals, Fungi',
      'Bacteria, Archaea, Eukarya',
      'Prokaryotes, Eukaryotes, Viruses',
      'Land, Water, Air',
    ],
    correctAnswers: [1],
    explanation: 'The three domains are Bacteria (typical bacteria), Archaea (extremophiles + others, structurally and biochemically distinct from bacteria), and Eukarya (all eukaryotes — protists, fungi, plants, animals). Domain is the broadest classification level. Plants, animals, and fungi are kingdoms WITHIN Eukarya. Viruses are not classified into any of the three domains because they are not considered living.',
  },
  {
    id: 'class-03',
    domain: 1,
    subdomain: 'Classification & Biodiversity',
    type: 'single',
    difficulty: 'easy',
    question: 'In the scientific name Homo sapiens, which word is the genus?',
    options: [
      'Homo',
      'sapiens',
      'Both words together',
      'Neither',
    ],
    correctAnswers: [0],
    explanation: 'In binomial nomenclature, the FIRST word (capitalized) is the genus; the second word (lowercase) is the species. So in Homo sapiens, "Homo" is the genus (which also includes extinct species like Homo erectus and Homo neanderthalensis) and "sapiens" is the species. Both words together are the scientific name; the whole thing is italicized (or underlined in handwriting).',
  },
  {
    id: 'class-04',
    domain: 1,
    subdomain: 'Classification & Biodiversity',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are kingdoms in the modern six-kingdom system? Select ALL that apply.',
    options: [
      'Animalia',
      'Plantae',
      'Fungi',
      'Protista',
      'Vertebrata',
    ],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'The six kingdoms are Archaebacteria, Eubacteria, Protista, Fungi, Plantae, and Animalia. Vertebrata is a SUBPHYLUM within the phylum Chordata (kingdom Animalia), not a kingdom itself. The split of bacteria into Archaebacteria and Eubacteria reflected the discovery that archaea are biochemically distinct. Some older textbooks use a five-kingdom system that combines them into "Monera."',
  },
  {
    id: 'class-05',
    domain: 1,
    subdomain: 'Classification & Biodiversity',
    type: 'single',
    difficulty: 'medium',
    question: 'Two organisms that share the same GENUS but different species must also share which of the following?',
    options: [
      'Only the species name',
      'Only the kingdom',
      'All higher classification levels (family, order, class, phylum, kingdom, domain)',
      'Nothing in common',
    ],
    correctAnswers: [2],
    explanation: 'Classification is hierarchical and nested — if two organisms share a genus, they must also share all broader levels (family, order, class, phylum, kingdom, domain) by definition. They simply differ at the species level. This is why classification trees are useful — sharing a recent classification level implies recent common ancestry.',
  },
  {
    id: 'class-06',
    domain: 1,
    subdomain: 'Classification & Biodiversity',
    type: 'single',
    difficulty: 'medium',
    question: 'A dichotomous key is a tool used to —',
    options: [
      'Open organisms for dissection',
      'Identify an unknown organism by making a series of paired choices',
      'Sort organisms alphabetically',
      'Determine an organism\'s age',
    ],
    correctAnswers: [1],
    explanation: 'A dichotomous key (di- = two) presents pairs of contrasting choices at each step. You compare your specimen to each pair, choose the matching option, and follow the path until you reach an identification. Example: "Does it have feathers? Yes → bird group; No → next pair." Used by field biologists to identify unknown species quickly without prior expertise.',
  },
  {
    id: 'class-07',
    domain: 1,
    subdomain: 'Classification & Biodiversity',
    type: 'single',
    difficulty: 'medium',
    question: 'Carl Linnaeus is credited with —',
    options: [
      'Discovering the structure of DNA',
      'Proposing the theory of evolution',
      'Developing the system of binomial nomenclature and modern taxonomy',
      'Inventing the microscope',
    ],
    correctAnswers: [2],
    explanation: 'Carl Linnaeus, an 18th-century Swedish botanist, established the binomial nomenclature system (Genus species) and the hierarchical classification system we still use today. Watson and Crick described DNA; Darwin and Wallace proposed evolution by natural selection; Hooke and Leeuwenhoek pioneered microscopy. Linnaeus organized biology before there was a theory to organize it under — his system later integrated nicely with evolutionary thinking.',
  },
  {
    id: 'class-08',
    domain: 1,
    subdomain: 'Classification & Biodiversity',
    type: 'single',
    difficulty: 'medium',
    question: 'A cladogram is a diagram that shows —',
    options: [
      'The age of individual organisms',
      'The hierarchical structure of cells',
      'Evolutionary relationships among species based on shared derived characteristics',
      'The chemical composition of biological molecules',
    ],
    correctAnswers: [2],
    explanation: 'A cladogram is a branching tree diagram showing the proposed evolutionary relationships among a group of species. Branch points (nodes) represent common ancestors; the order of branching shows which species share more recent common ancestors. Cladograms are built using shared derived characteristics — traits that arose in a common ancestor and were inherited by descendants. Closely related species share more recent common ancestors on the cladogram.',
  },
  {
    id: 'class-09',
    domain: 1,
    subdomain: 'Classification & Biodiversity',
    type: 'single',
    difficulty: 'hard',
    question: 'Why are viruses NOT placed in any of the three domains of life?',
    options: [
      'They are too small to classify.',
      'They lack the characteristics of life — they cannot reproduce or carry out metabolism on their own.',
      'They have not yet been discovered.',
      'They belong to a fourth secret domain.',
    ],
    correctAnswers: [1],
    explanation: 'Viruses are not considered living because they cannot reproduce, metabolize, maintain homeostasis, or grow on their own — they must hijack a host cell to do anything. They lack cells entirely (just protein coats around genetic material). Because they fail most of the seven characteristics of life, biologists do not include them in the three-domain system. Their evolutionary origin is still debated.',
  },
  {
    id: 'class-10',
    domain: 1,
    subdomain: 'Classification & Biodiversity',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are characteristics that ALL living things share? Select ALL that apply.',
    options: [
      'Made of one or more cells',
      'Reproduce',
      'Respond to stimuli',
      'Use energy (metabolism)',
      'Have a backbone',
    ],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'The characteristics of life: made of cells, reproduce, respond to stimuli, grow and develop, use energy (metabolism), maintain homeostasis, and evolve as populations. Having a backbone is specific to vertebrates — bacteria, plants, jellyfish, and insects are all alive without one. Memorize the full list — the EOCEP loves to throw in a trap option like "backbone" or "can fly" that applies only to certain groups.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Homeostasis & Body Systems
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'homeo-01',
    domain: 1,
    subdomain: 'Homeostasis & Body Systems',
    type: 'single',
    difficulty: 'easy',
    question: 'Homeostasis refers to —',
    options: [
      'The rapid evolution of populations',
      'The maintenance of stable internal conditions despite external changes',
      'The process of breaking down glucose for energy',
      'The growth of a cell before division',
    ],
    correctAnswers: [1],
    explanation: 'Homeostasis is the regulation of internal conditions — body temperature, blood pH, blood glucose, hydration — to stay within a narrow optimal range even as the external environment changes. Every living thing does this in some form. It is one of the characteristics of life. Cellular respiration breaks down glucose; the cell cycle controls growth and division — different topics.',
  },
  {
    id: 'homeo-02',
    domain: 1,
    subdomain: 'Homeostasis & Body Systems',
    type: 'single',
    difficulty: 'easy',
    question: 'When you get hot, you sweat to cool down. This is an example of —',
    options: [
      'Positive feedback',
      'Negative feedback',
      'Mutation',
      'Mitosis',
    ],
    correctAnswers: [1],
    explanation: 'Negative feedback REVERSES a change to return to the set point. Body temp rises → you sweat → sweating cools you down → temperature returns to ~37°C. The response opposes the change. Positive feedback AMPLIFIES the change (rare — childbirth contractions, blood clotting). Most homeostatic mechanisms are negative feedback because the goal is stability.',
  },
  {
    id: 'homeo-03',
    domain: 1,
    subdomain: 'Homeostasis & Body Systems',
    type: 'single',
    difficulty: 'easy',
    question: 'Which sequence correctly orders levels of organization from SMALLEST to LARGEST?',
    options: [
      'Organ → Tissue → Cell → Organ system',
      'Cell → Tissue → Organ → Organ system',
      'Organ system → Organ → Tissue → Cell',
      'Tissue → Cell → Organ system → Organ',
    ],
    correctAnswers: [1],
    explanation: 'Cells → tissues (groups of similar cells) → organs (multiple tissues working together) → organ systems (groups of organs performing a major function) → organism. Each level is built from the level below it. This is the body-level version of the broader levels of organization (atom → molecule → organelle → cell → tissue → organ → organ system → organism → population → community → ecosystem → biosphere).',
  },
  {
    id: 'homeo-04',
    domain: 1,
    subdomain: 'Homeostasis & Body Systems',
    type: 'single',
    difficulty: 'medium',
    question: 'Which body system is primarily responsible for transporting oxygen, nutrients, and wastes throughout the body?',
    options: [
      'Digestive system',
      'Respiratory system',
      'Circulatory system',
      'Nervous system',
    ],
    correctAnswers: [2],
    explanation: 'The circulatory system (heart + blood + blood vessels) transports oxygen, CO₂, nutrients, hormones, and wastes throughout the body. The respiratory system specifically handles gas exchange between blood and air. The digestive system breaks down food and absorbs nutrients into the blood. The nervous system handles electrical signaling. Transport is the circulatory system\'s defining role.',
  },
  {
    id: 'homeo-05',
    domain: 1,
    subdomain: 'Homeostasis & Body Systems',
    type: 'single',
    difficulty: 'medium',
    question: 'During childbirth, contractions of the uterus trigger more contractions, building until the baby is delivered. This is an example of —',
    options: [
      'Negative feedback',
      'Positive feedback',
      'Active transport',
      'Mitosis',
    ],
    correctAnswers: [1],
    explanation: 'Childbirth contractions are a textbook example of positive feedback. The pressure of the baby on the cervix triggers oxytocin release, which causes more contractions, which causes more pressure and more oxytocin — until birth ends the loop. Positive feedback amplifies change toward an endpoint; once birth occurs, the loop breaks. Negative feedback would be inappropriate here because the goal is to drive the process to completion, not maintain stasis.',
  },
  {
    id: 'homeo-06',
    domain: 1,
    subdomain: 'Homeostasis & Body Systems',
    type: 'single',
    difficulty: 'medium',
    question: 'Blood glucose homeostasis involves two hormones from the pancreas. Insulin LOWERS blood glucose; glucagon RAISES blood glucose. After a meal high in carbohydrates, which hormone is most likely released?',
    options: [
      'Glucagon',
      'Insulin',
      'Both equally',
      'Neither',
    ],
    correctAnswers: [1],
    explanation: 'After eating, blood glucose rises sharply as the meal is digested and absorbed. The pancreas releases insulin to LOWER blood glucose by signaling cells (especially muscle and liver) to take up glucose and store it as glycogen. Glucagon is released when blood glucose is too LOW (e.g., between meals or during exercise) to trigger glycogen breakdown back into glucose. Diabetes results when insulin signaling fails.',
  },
  {
    id: 'homeo-07',
    domain: 1,
    subdomain: 'Homeostasis & Body Systems',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are organ systems in the human body? Select ALL that apply.',
    options: [
      'Digestive system',
      'Respiratory system',
      'Skeletal system',
      'Photosynthesis system',
      'Endocrine system',
    ],
    correctAnswers: [0, 1, 2, 4],
    explanation: 'Digestive, respiratory, skeletal, muscular, circulatory, nervous, endocrine, immune (lymphatic), excretory (urinary), reproductive, and integumentary (skin) are the major human organ systems. "Photosynthesis system" is not a human system at all — humans do not photosynthesize. The endocrine system regulates the body through hormones; the skeletal system provides structure and protects organs.',
  },
  {
    id: 'homeo-08',
    domain: 1,
    subdomain: 'Homeostasis & Body Systems',
    type: 'single',
    difficulty: 'medium',
    question: 'Which type of tissue contracts to produce movement in the body?',
    options: [
      'Epithelial tissue',
      'Connective tissue',
      'Muscle tissue',
      'Nervous tissue',
    ],
    correctAnswers: [2],
    explanation: 'Muscle tissue is specialized for contraction. There are three types: skeletal (voluntary, moves bones), cardiac (heart, involuntary), and smooth (lining internal organs and blood vessels, involuntary). Epithelial tissue covers body surfaces and lines cavities; connective tissue supports and connects (bone, blood, fat); nervous tissue transmits electrical signals. Only muscle contracts.',
  },
  {
    id: 'homeo-09',
    domain: 1,
    subdomain: 'Homeostasis & Body Systems',
    type: 'yesno',
    difficulty: 'medium',
    question: 'Do plants exhibit homeostasis even though they have no nervous system or circulatory system like animals?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes — plants maintain homeostasis through different mechanisms than animals. They regulate water balance through guard cells (opening/closing stomata to control transpiration), regulate temperature through transpiration, balance ion concentrations, and respond to light, gravity, and touch. Homeostasis is a universal characteristic of life; the MECHANISMS differ across kingdoms, but every living thing does it in some way.',
  },
  {
    id: 'homeo-10',
    domain: 1,
    subdomain: 'Homeostasis & Body Systems',
    type: 'single',
    difficulty: 'hard',
    question: 'A person walking from an air-conditioned room to a hot parking lot begins to sweat within a few minutes. The hypothalamus in the brain detects rising body temperature and signals the sweat glands. This negative-feedback loop most directly involves which two body systems?',
    options: [
      'Digestive and reproductive',
      'Nervous and integumentary (skin)',
      'Skeletal and circulatory only',
      'Respiratory and excretory only',
    ],
    correctAnswers: [1],
    explanation: 'The hypothalamus (nervous system) detects the temperature change and sends signals to the sweat glands in the skin (integumentary system) to release sweat. Sweat evaporation cools the body. The circulatory system also helps by dilating skin blood vessels, but the most direct loop is nervous-system detection acting on integumentary-system effectors. Body systems work in concert — most homeostatic responses involve more than one system.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Scientific Inquiry & Lab Skills
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'inq-01',
    domain: 1,
    subdomain: 'Scientific Inquiry & Lab Skills',
    type: 'single',
    difficulty: 'easy',
    question: 'In an experiment testing whether different amounts of fertilizer affect plant growth, what is the INDEPENDENT variable?',
    options: [
      'Plant height (the measurement)',
      'Amount of fertilizer (what the experimenter changes)',
      'Sunlight (kept the same for all plants)',
      'Soil type (kept the same for all plants)',
    ],
    correctAnswers: [1],
    explanation: 'The independent variable is what the experimenter CHANGES on purpose — here, amount of fertilizer. Plant height is the dependent variable (what is measured in response). Sunlight and soil type are control variables (kept constant so they do not confound the experiment). The rule: independent goes on the x-axis, dependent goes on the y-axis.',
  },
  {
    id: 'inq-02',
    domain: 1,
    subdomain: 'Scientific Inquiry & Lab Skills',
    type: 'single',
    difficulty: 'easy',
    question: 'A "hypothesis" in science is best described as —',
    options: [
      'A guess that has no evidence behind it',
      'A proven fact about nature',
      'A testable, falsifiable proposed explanation for an observation',
      'A type of microscope used in lab',
    ],
    correctAnswers: [2],
    explanation: 'A hypothesis is a TESTABLE, FALSIFIABLE proposed explanation for something observed. It must be possible to design an experiment that could prove the hypothesis wrong. "If I water plants more, then they will grow taller because more water aids photosynthesis" is a hypothesis. It is NOT a guess (guesses have no reasoning) and NOT a proven fact (a hypothesis is what you TEST, not what you have proven).',
  },
  {
    id: 'inq-03',
    domain: 1,
    subdomain: 'Scientific Inquiry & Lab Skills',
    type: 'single',
    difficulty: 'easy',
    question: 'In science, a "theory" is —',
    options: [
      'A guess or hunch',
      'A well-supported, broad explanation that integrates many confirmed observations and hypotheses',
      'The same thing as a hypothesis',
      'An opinion held by a single scientist',
    ],
    correctAnswers: [1],
    explanation: 'Scientific theory ≠ everyday "theory." A scientific theory is the highest tier of explanation, supported by extensive evidence and integrating many confirmed hypotheses, observations, and laws. Examples: cell theory, theory of evolution, atomic theory, germ theory. Theories do not "get promoted to" laws — laws and theories serve different purposes (laws describe patterns; theories explain why).',
  },
  {
    id: 'inq-04',
    domain: 1,
    subdomain: 'Scientific Inquiry & Lab Skills',
    type: 'single',
    difficulty: 'medium',
    question: 'A scientist tests whether a new fertilizer increases plant growth. She gives one group of plants the fertilizer and another group plain water. The plain-water group is the —',
    options: [
      'Independent variable',
      'Dependent variable',
      'Control group',
      'Experimental error',
    ],
    correctAnswers: [2],
    explanation: 'The control group is the group that does NOT receive the experimental treatment — used as a baseline for comparison. Here, the plants with plain water are the control. The plants getting fertilizer are the experimental group. Without a control, you cannot tell whether observed differences come from the treatment or from random variation. A control group is different from a control variable (a constant factor kept the same across groups).',
  },
  {
    id: 'inq-05',
    domain: 1,
    subdomain: 'Scientific Inquiry & Lab Skills',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are good practices for designing a reliable experiment? Select ALL that apply.',
    options: [
      'Use a large enough sample size',
      'Repeat the experiment multiple times',
      'Test only one variable at a time',
      'Include a control group for comparison',
      'Skip recording data that doesn\'t support your hypothesis',
    ],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'A reliable experiment has a large sample size, is repeatable, isolates one variable at a time, and includes a control. Skipping data that contradicts your hypothesis is cherry-picking — a serious ethical violation that destroys the experiment\'s validity. Good scientists record ALL data and let evidence guide conclusions. The trap "skip data" sounds like efficiency but is actually the opposite of good science.',
  },
  {
    id: 'inq-06',
    domain: 1,
    subdomain: 'Scientific Inquiry & Lab Skills',
    type: 'single',
    difficulty: 'medium',
    question: 'Which is an OBSERVATION rather than an inference?',
    options: [
      'The plant is happy in the sunlight.',
      'The plant is 25 centimeters tall.',
      'The plant prefers water with minerals in it.',
      'The plant needs more nutrients to thrive.',
    ],
    correctAnswers: [1],
    explanation: 'Observations are statements about what we can directly perceive (with senses or instruments) — measurements, descriptions of color, length, etc. "25 cm tall" is a measurable observation. The others are inferences (interpretations going beyond the data) or anthropomorphic interpretations ("happy," "prefers"). Good scientific writing distinguishes carefully between what you saw and what you concluded.',
  },
  {
    id: 'inq-07',
    domain: 1,
    subdomain: 'Scientific Inquiry & Lab Skills',
    type: 'single',
    difficulty: 'medium',
    question: 'A student observes 5 plants in fertilizer growing taller than 5 plants without fertilizer over one week. Why should the student NOT immediately conclude that the fertilizer caused the growth?',
    options: [
      'The student needs to publish a paper first.',
      'A sample size of 5 is small, and one week is short — more replicates and time are needed to reduce the role of chance.',
      'Fertilizer is illegal in school experiments.',
      'Plants cannot grow taller in only one week.',
    ],
    correctAnswers: [1],
    explanation: 'Small samples and short timeframes are vulnerable to chance variation — maybe the five plants in fertilizer happened to be more vigorous to begin with. Larger samples, multiple trials, and longer time periods give clearer signals through statistical averaging. This is why real science demands replication. A single small experiment is suggestive but rarely conclusive.',
  },
  {
    id: 'inq-08',
    domain: 1,
    subdomain: 'Scientific Inquiry & Lab Skills',
    type: 'single',
    difficulty: 'medium',
    question: 'Which scientific instrument is best for viewing individual plant cells and their organelles?',
    options: [
      'A pair of binoculars',
      'A compound light microscope',
      'An ordinary magnifying glass',
      'A bare eye',
    ],
    correctAnswers: [1],
    explanation: 'A compound light microscope can magnify up to about 1000× — enough to see individual cells (typically 10–100 μm) and their larger organelles like the nucleus and chloroplasts. The unaided eye and a magnifying glass cannot see individual cells. Binoculars are for distant objects, not small ones. Electron microscopes go further (>1,000,000×) and are needed for smaller organelles like ribosomes and viruses.',
  },
  {
    id: 'inq-09',
    domain: 1,
    subdomain: 'Scientific Inquiry & Lab Skills',
    type: 'single',
    difficulty: 'hard',
    question: 'A scientist hypothesizes that caffeine increases reaction time in students. After designing and running an experiment, the data shows NO significant effect. The most scientifically appropriate next step is to —',
    options: [
      'Hide the data because it contradicts the hypothesis.',
      'Report the results honestly; the hypothesis was not supported.',
      'Change the data to match the hypothesis.',
      'Refuse to publish the results.',
    ],
    correctAnswers: [1],
    explanation: 'Reporting honest results — even when the hypothesis is not supported — is fundamental to science. "Negative" results (no effect found) are still valuable information; they help other scientists avoid wasted effort and refine theory. Hiding or fabricating data is research misconduct that can end a scientific career. A failed hypothesis is not failure — it is a normal, important part of science.',
  },
  {
    id: 'inq-10',
    domain: 1,
    subdomain: 'Scientific Inquiry & Lab Skills',
    type: 'yesno',
    difficulty: 'medium',
    question: 'Is it possible for a scientific theory to be revised or replaced if new evidence emerges?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes — every scientific theory is open to revision in light of new evidence. The geocentric theory was replaced by heliocentric; classical physics was refined by relativity and quantum mechanics. This openness to revision is a strength, not a weakness — it is what separates science from dogma. That said, well-established theories (evolution, cell theory, atomic theory) have so much evidence that any revision would refine rather than overturn the core ideas.',
  },
  {
    id: 'inq-11',
    domain: 1,
    subdomain: 'Scientific Inquiry & Lab Skills',
    type: 'single',
    difficulty: 'easy',
    question: 'A graph plots temperature (°C) on the x-axis and enzyme reaction rate on the y-axis. Which is the DEPENDENT variable?',
    options: [
      'Temperature',
      'Enzyme reaction rate',
      'Both equally',
      'Neither',
    ],
    correctAnswers: [1],
    explanation: 'The dependent variable is what is MEASURED in response to the independent variable. By convention, the dependent variable goes on the y-axis, the independent on the x-axis. Reaction rate depends on temperature; temperature is what the experimenter changed. So enzyme reaction rate is the dependent variable. This convention is universal in scientific graphing.',
  },
  {
    id: 'inq-12',
    domain: 1,
    subdomain: 'Scientific Inquiry & Lab Skills',
    type: 'single',
    difficulty: 'medium',
    question: 'Why is peer review an important part of the scientific process?',
    options: [
      'It guarantees a study is completely correct.',
      'It allows other scientists to critically evaluate methods, results, and interpretations before publication.',
      'It is a tradition with no real benefit.',
      'It increases the cost of publishing.',
    ],
    correctAnswers: [1],
    explanation: 'Peer review is the system where other experts in the field critically evaluate a study\'s methods, statistics, and interpretations before it is published. It catches errors, identifies overreach, and improves quality. It does NOT guarantee correctness — flawed papers still get through — but it raises the average quality of published science. Replication and ongoing scrutiny continue the quality control after publication.',
  },
  {
    id: 'inq-13',
    domain: 1,
    subdomain: 'Scientific Inquiry & Lab Skills',
    type: 'single',
    difficulty: 'hard',
    question: 'A researcher claims a single experiment proves that a new vitamin cures the common cold. Why should other scientists be skeptical of this claim before accepting it?',
    options: [
      'Vitamins cannot affect colds.',
      'A single, non-replicated experiment is not strong evidence — independent replication and peer review are needed before broad acceptance.',
      'Colds are not real diseases.',
      'No one should ever change their mind based on evidence.',
    ],
    correctAnswers: [1],
    explanation: 'Science is built on replication. A single positive result could be due to chance, methodology errors, small sample size, or unknown bias. Independent research groups must reproduce findings before they are accepted into the established body of knowledge. Extraordinary claims (like a sweeping cure) demand even more extraordinary evidence. This is why "one study showed X" headlines should always be treated cautiously.',
  },
  {
    id: 'class-11',
    domain: 1,
    subdomain: 'Classification & Biodiversity',
    type: 'single',
    difficulty: 'easy',
    question: 'Which of these belongs to the kingdom Fungi?',
    options: [
      'A pine tree',
      'A mushroom',
      'A goldfish',
      'A jellyfish',
    ],
    correctAnswers: [1],
    explanation: 'Mushrooms are the fruiting bodies of fungi — kingdom Fungi. Pine trees are plants (Plantae), goldfish are animals (Animalia, phylum Chordata), and jellyfish are animals (Animalia, phylum Cnidaria). Fungi differ from plants in that they are heterotrophs (cannot photosynthesize) and have cell walls made of chitin, not cellulose. Yeasts and molds are also fungi.',
  },
  {
    id: 'class-12',
    domain: 1,
    subdomain: 'Classification & Biodiversity',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are valid scientific names written using correct binomial nomenclature conventions? Select ALL that apply.',
    options: [
      'Homo sapiens',
      'homo sapiens',
      'Canis familiaris',
      'CANIS FAMILIARIS',
      'Escherichia coli',
    ],
    correctAnswers: [0, 2, 4],
    explanation: 'Correct format: Genus species — genus capitalized, species lowercase, whole name italicized (or underlined in handwriting). "Homo sapiens," "Canis familiaris," and "Escherichia coli" all follow the rule. "homo sapiens" loses the capital on genus. "CANIS FAMILIARIS" is in all caps — wrong. The conventions matter; mis-formatted names are a common source of point loss on the EOCEP.',
  },
  {
    id: 'cell-14',
    domain: 1,
    subdomain: 'Cells & Cell Processes',
    type: 'single',
    difficulty: 'medium',
    question: 'Which organelle is correctly paired with its function?',
    options: [
      'Lysosome → photosynthesis',
      'Golgi apparatus → modifying and packaging proteins for secretion',
      'Ribosome → producing ATP through respiration',
      'Cell wall → controlling movement of substances in and out of the cell',
    ],
    correctAnswers: [1],
    explanation: 'The Golgi apparatus modifies, sorts, and packages proteins received from the ER into vesicles destined for secretion or for other organelles. Lysosomes break down waste with digestive enzymes (no photosynthesis happens there). Ribosomes BUILD proteins (mitochondria produce ATP). The cell wall provides structural support and shape — the cell MEMBRANE controls what enters and exits.',
  },
  {
    id: 'bio-14',
    domain: 1,
    subdomain: 'Biochemistry & Energy',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are unique properties of water that make it essential for life? Select ALL that apply.',
    options: [
      'Polarity — uneven distribution of charge',
      'High specific heat — resists temperature change',
      'Ice is less dense than liquid water',
      'It conducts electricity better than any other substance',
      'Cohesion and surface tension',
    ],
    correctAnswers: [0, 1, 2, 4],
    explanation: 'Water\'s polarity creates hydrogen bonding, which produces its other special properties: high specific heat (stabilizes temperature in cells and lakes), high heat of vaporization (sweat cools us efficiently), ice floating (insulates lakes in winter), cohesion (water sticks to itself — surface tension), and adhesion (water sticks to other polar surfaces — capillary action in plants). Water is actually a POOR conductor of electricity in pure form — that is not a key property.',
  },
  {
    id: 'gen-14',
    domain: 1,
    subdomain: 'Genetics & Heredity',
    type: 'single',
    difficulty: 'medium',
    question: 'Two parents with genotypes Tt and Tt have children. What fraction of their offspring are expected to be HOMOZYGOUS RECESSIVE (tt)?',
    options: [
      '0',
      '1/4',
      '1/2',
      '3/4',
    ],
    correctAnswers: [1],
    explanation: 'In a Tt × Tt cross, the Punnett square gives four equally likely outcomes: TT, Tt, Tt, tt. Only 1 out of 4 offspring is tt (homozygous recessive). The 3/4 answer trap mistakes phenotype ratio (3 dominant : 1 recessive) with genotype. The 1/2 trap incorrectly assumes a simple two-outcome cross. Always set up a Punnett square when in doubt — counting cells gives the right ratio.',
  },
  {
    id: 'evo-14',
    domain: 1,
    subdomain: 'Evolution & Natural Selection',
    type: 'single',
    difficulty: 'medium',
    question: 'Why do new antibiotics often become less effective over time?',
    options: [
      'Bacteria stop reproducing.',
      'The antibiotic ingredient breaks down over time.',
      'Natural selection favors bacteria with random mutations that confer resistance, increasing their frequency over generations.',
      'Doctors stop prescribing antibiotics.',
    ],
    correctAnswers: [2],
    explanation: 'Bacteria reproduce extremely rapidly (every 20–30 minutes for many species), so even rare resistance mutations can spread fast under antibiotic selection pressure. Each new antibiotic kills susceptible bacteria; the survivors are the resistant ones, who reproduce and dominate. Within a few years, the antibiotic loses effectiveness in many populations. This is why doctors emphasize finishing prescriptions and not over-using antibiotics.',
  },
  {
    id: 'eco-14',
    domain: 1,
    subdomain: 'Ecology & Ecosystems',
    type: 'single',
    difficulty: 'hard',
    question: 'An invasive species enters an ecosystem with no natural predators. Which outcome is most likely?',
    options: [
      'The invasive species dies out immediately.',
      'The invasive species population grows rapidly, often disrupting native communities by out-competing native species or eating them.',
      'Other species adapt instantly to coexist with it.',
      'The invasive species has no measurable effect.',
    ],
    correctAnswers: [1],
    explanation: 'Without natural predators or parasites that evolved with it elsewhere, an invasive species often experiences explosive population growth in its new environment. It out-competes native species for resources or directly preys on them. Famous examples: kudzu vines in the southeastern U.S., zebra mussels in the Great Lakes, cane toads in Australia. Restoring balance often takes decades of human intervention.',
  },
  {
    id: 'cell-15',
    domain: 1,
    subdomain: 'Cells & Cell Processes',
    type: 'single',
    difficulty: 'hard',
    question: 'The "fluid mosaic model" of the cell membrane describes the membrane as —',
    options: [
      'A solid layer of rigid protein',
      'A flexible phospholipid bilayer with proteins floating throughout like a mosaic',
      'A double layer of carbohydrates only',
      'A single layer of DNA strands',
    ],
    correctAnswers: [1],
    explanation: 'The fluid mosaic model, proposed in 1972, describes the membrane as a fluid phospholipid bilayer with embedded proteins (channels, pumps, receptors) floating laterally throughout. "Fluid" because the phospholipids can move within the membrane plane; "mosaic" because the proteins form a varied pattern. Some proteins span the whole membrane (integral); others sit on the surface (peripheral). This dynamic model is essential to understanding membrane function.',
  },
  {
    id: 'homeo-11',
    domain: 1,
    subdomain: 'Homeostasis & Body Systems',
    type: 'single',
    difficulty: 'hard',
    question: 'A diabetic patient cannot produce enough insulin. Which homeostatic process is most directly disrupted?',
    options: [
      'Body temperature regulation',
      'Blood glucose regulation',
      'Blood pH regulation',
      'Calcium ion balance',
    ],
    correctAnswers: [1],
    explanation: 'Insulin is the hormone that signals body cells to take up glucose from the blood after a meal — lowering blood sugar. Without enough insulin (type 1 diabetes), blood glucose stays dangerously high. Type 2 diabetes is similar but caused by cells becoming resistant to insulin signaling. Untreated, high blood glucose damages blood vessels and nerves. This is a direct failure of negative-feedback regulation of blood glucose.',
  },
  {
    id: 'gen-15',
    domain: 1,
    subdomain: 'Genetics & Heredity',
    type: 'single',
    difficulty: 'hard',
    question: 'A point mutation changes one DNA base but does not alter the amino acid that is coded for. This type of mutation is called —',
    options: [
      'Silent mutation',
      'Missense mutation',
      'Nonsense mutation',
      'Frameshift mutation',
    ],
    correctAnswers: [0],
    explanation: 'Because the genetic code is redundant (multiple codons code for the same amino acid — e.g., both UCU and UCC code for serine), a base change can leave the amino acid unchanged. That is a silent mutation, often invisible at the protein level. A missense mutation changes the amino acid. A nonsense mutation introduces a premature stop codon. A frameshift mutation shifts the reading frame entirely.',
  },
  {
    id: 'bio-15',
    domain: 1,
    subdomain: 'Biochemistry & Energy',
    type: 'single',
    difficulty: 'hard',
    question: 'A scientist treats a culture of yeast with a chemical that destroys mitochondria. What is the most likely effect on energy production in the yeast?',
    options: [
      'The yeast will produce more ATP because mitochondria are inhibitory.',
      'The yeast will be limited to glycolysis and fermentation, producing only 2 ATP per glucose instead of ~36.',
      'The yeast will continue making ATP through photosynthesis.',
      'The yeast will become immune to all stressors.',
    ],
    correctAnswers: [1],
    explanation: 'Without mitochondria, the Krebs cycle and electron transport chain cannot run — yeast is reduced to glycolysis in the cytoplasm plus fermentation. Glycolysis nets only 2 ATP per glucose, compared with the ~36 ATP from full aerobic respiration. Yeast can survive on fermentation for some time (that is how brewing works), but it is a dramatic energy drop. Yeast does not photosynthesize — it is a fungus, not a plant.',
  },
  {
    id: 'eco-15',
    domain: 1,
    subdomain: 'Ecology & Ecosystems',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are major threats to biodiversity worldwide? Select ALL that apply.',
    options: [
      'Habitat destruction (deforestation, urbanization)',
      'Invasive species displacing natives',
      'Pollution of air, water, and soil',
      'Climate change shifting habitat ranges',
      'An over-supply of food everywhere on Earth',
    ],
    correctAnswers: [0, 1, 2, 3],
    explanation: 'The five major drivers of biodiversity loss (HIPPO): Habitat destruction, Invasive species, Pollution, Population growth (human), and Overharvesting (hunting, fishing). Climate change is increasingly recognized as a sixth major driver. "Over-supply of food" is not a real threat and is a trap option — limited resources, not unlimited ones, drive ecological stress. Knowing the HIPPO acronym helps on this kind of multi-select.',
  },
  {
    id: 'evo-15',
    domain: 1,
    subdomain: 'Evolution & Natural Selection',
    type: 'yesno',
    difficulty: 'medium',
    question: 'Does evidence from comparing DNA sequences across species support evolutionary relationships predicted by anatomy?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes — and this convergence of evidence is one of the strongest arguments for evolution. Species predicted to share recent common ancestors by anatomical and fossil evidence also share more similar DNA sequences. For example, humans and chimps share ~98% of their DNA, matching the close anatomical similarity. Molecular evidence has confirmed and refined the evolutionary tree built from morphology, with relatively few surprises.',
  },
];
