import type { SATQuestion } from './index';

export const rwConventionsQuestions: SATQuestion[] = [
  {
    id: "rw-conv-001",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "easy",
    passage: "Because the lab needed more storage space.",
    question: "Which choice most effectively revises the sentence to form a complete sentence?",
    options: [
      "Because the lab needed more storage space, the director cleared an unused closet.",
      "Because the lab needed more storage space, the director, clearing an unused closet.",
      "Because the lab needed more storage space, clearing an unused closet.",
      "Because the lab needed more storage space, an unused closet for supplies.",
    ],
    correctAnswers: [0],
    explanation: "The dependent clause Because the lab needed more storage space cannot stand alone. Choice A correctly supplies an independent clause to complete the sentence.",
    tip: "If the opening word is because, although, when, while, or since, make sure the sentence has a full main clause.",
  },
  {
    id: "rw-conv-002",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "easy",
    passage: "Although the hikers had already reached the summit.",
    question: "Which choice most effectively revises the sentence to form a complete sentence?",
    options: [
      "Although the hikers had already reached the summit, they stayed a few minutes to sketch the view.",
      "Although the hikers had already reached the summit, staying a few minutes to sketch the view.",
      "Although the hikers had already reached the summit, a sketch of the view from the summit.",
      "Although the hikers had already reached the summit, and a few minutes to sketch the view.",
    ],
    correctAnswers: [0],
    explanation: "Although begins a subordinate clause, so the sentence needs an independent clause. Choice A completes the thought clearly.",
    tip: "If the opening word is because, although, when, while, or since, make sure the sentence has a full main clause.",
  },
  {
    id: "rw-conv-003",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "easy",
    passage: "When the orchestra finished rehearsing.",
    question: "Which choice most effectively revises the sentence to form a complete sentence?",
    options: [
      "When the orchestra finished rehearsing, the conductor thanked the musicians for their focus.",
      "When the orchestra finished rehearsing, the conductor thanking the musicians for their focus.",
      "When the orchestra finished rehearsing, for their focus during rehearsal.",
      "When the orchestra finished rehearsing, and thanked the musicians for their focus.",
    ],
    correctAnswers: [0],
    explanation: "When creates a dependent clause. Choice A is the only option that turns the fragment into a complete sentence.",
    tip: "If the opening word is because, although, when, while, or since, make sure the sentence has a full main clause.",
  },
  {
    id: "rw-conv-004",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "easy",
    passage: "Because the storm arrived earlier than expected.",
    question: "Which choice most effectively revises the sentence to form a complete sentence?",
    options: [
      "Because the storm arrived earlier than expected, the game started thirty minutes ahead of schedule.",
      "Because the storm arrived earlier than expected, starting the game thirty minutes ahead of schedule.",
      "Because the storm arrived earlier than expected, an earlier start for the game.",
      "Because the storm arrived earlier than expected, with the game starting early.",
    ],
    correctAnswers: [0],
    explanation: "The opening clause needs a main clause that states what happened. Choice A provides that complete thought.",
    tip: "If the opening word is because, although, when, while, or since, make sure the sentence has a full main clause.",
  },
  {
    id: "rw-conv-005",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "easy",
    passage: "While the chef prepared the sauce.",
    question: "Which choice most effectively revises the sentence to form a complete sentence?",
    options: [
      "While the chef prepared the sauce, the assistants chopped herbs at the next counter.",
      "While the chef prepared the sauce, the assistants chopping herbs at the next counter.",
      "While the chef prepared the sauce, chopping herbs at the next counter.",
      "While the chef prepared the sauce, the next counter for chopping herbs.",
    ],
    correctAnswers: [0],
    explanation: "While introduces a subordinate clause, so the sentence must continue with a full independent clause. Choice A does that.",
    tip: "If the opening word is because, although, when, while, or since, make sure the sentence has a full main clause.",
  },
  {
    id: "rw-conv-006",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "easy",
    passage: "Since the museum extended its weekend hours.",
    question: "Which choice most effectively revises the sentence to form a complete sentence?",
    options: [
      "Since the museum extended its weekend hours, more families have been able to visit together.",
      "Since the museum extended its weekend hours, more families visiting together.",
      "Since the museum extended its weekend hours, the weekend hours extending longer.",
      "Since the museum extended its weekend hours, and more family visits.",
    ],
    correctAnswers: [0],
    explanation: "Since starts a dependent clause. Choice A supplies a complete main clause that explains the result.",
    tip: "If the opening word is because, although, when, while, or since, make sure the sentence has a full main clause.",
  },
  {
    id: "rw-conv-007",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "medium",
    passage: "Before the volunteers painted the mural.",
    question: "Which choice most effectively revises the sentence to form a complete sentence?",
    options: [
      "Before the volunteers painted the mural, they cleaned and primed the wall.",
      "Before the volunteers painted the mural, cleaning and priming the wall.",
      "Before the volunteers painted the mural, the wall, clean and primed.",
      "Before the volunteers painted the mural, and the wall was prepared.",
    ],
    correctAnswers: [0],
    explanation: "The sentence needs a complete thought after the introductory clause. Choice A provides the required subject and verb.",
    tip: "If the opening word is because, although, when, while, or since, make sure the sentence has a full main clause.",
  },
  {
    id: "rw-conv-008",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "medium",
    passage: "The research team finished the field survey, it still needed to organize the samples.",
    question: "Which choice most effectively revises the sentence?",
    options: [
      "The research team finished the field survey, it still needed to organize the samples.",
      "The research team finished the field survey, but it still needed to organize the samples.",
      "The research team finished the field survey still needing to organize the samples.",
      "The research team finished the field survey, and organizing the samples.",
    ],
    correctAnswers: [1],
    explanation: "Choice B correctly joins two independent clauses with a comma and coordinating conjunction. Choice A is a comma splice, and the other options are not complete or clear.",
    tip: "When two full sentences are joined, use a period, semicolon, or comma plus a coordinating conjunction.",
  },
  {
    id: "rw-conv-009",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "medium",
    passage: "Maya wanted to submit her article before lunch, the editor was still checking one quotation.",
    question: "Which choice most effectively revises the sentence?",
    options: [
      "Maya wanted to submit her article before lunch; the editor was still checking one quotation.",
      "Maya wanted to submit her article before lunch, the editor was still checking one quotation.",
      "Maya wanted to submit her article before lunch because the editor was still checking one quotation.",
      "Maya wanted to submit her article before lunch, still checking one quotation.",
    ],
    correctAnswers: [0],
    explanation: "Choice A correctly joins two closely related independent clauses with a semicolon. Choice B is a comma splice, and the other options distort the meaning or create awkward structure.",
    tip: "When two full sentences are joined, use a period, semicolon, or comma plus a coordinating conjunction.",
  },
  {
    id: "rw-conv-010",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "medium",
    passage: "The bus arrived on time, several passengers were already waiting at the stop.",
    question: "Which choice most effectively revises the sentence?",
    options: [
      "The bus arrived on time; and several passengers were already waiting at the stop.",
      "The bus arrived on time, and several passengers were already waiting at the stop.",
      "The bus arrived on time several passengers were already waiting at the stop.",
      "The bus arrived on time, several passengers waiting at the stop.",
    ],
    correctAnswers: [1],
    explanation: "Choice B properly links the clauses with a comma and and. Choice A misuses the semicolon, and C and D are faulty run-ons or fragments.",
    tip: "When two full sentences are joined, use a period, semicolon, or comma plus a coordinating conjunction.",
  },
  {
    id: "rw-conv-011",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "medium",
    passage: "The team liked the first design, it chose the lighter version for the final model.",
    question: "Which choice most effectively revises the sentence?",
    options: [
      "The team liked the first design; however, it chose the lighter version for the final model.",
      "The team liked the first design, however it chose the lighter version for the final model.",
      "The team liked the first design but choosing the lighter version for the final model.",
      "The team liked the first design, choosing the lighter version for the final model however.",
    ],
    correctAnswers: [0],
    explanation: "Choice A correctly uses a semicolon before the conjunctive adverb however and a comma after it. The other options contain punctuation or structure errors.",
    tip: "When two full sentences are joined, use a period, semicolon, or comma plus a coordinating conjunction.",
  },
  {
    id: "rw-conv-012",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "medium",
    passage: "The orchard looked dry after weeks without rain, new growth appeared after the irrigation system was repaired.",
    question: "Which choice most effectively revises the sentence?",
    options: [
      "The orchard looked dry after weeks without rain; new growth appeared after the irrigation system was repaired,",
      "The orchard looked dry after weeks without rain, but new growth appeared after the irrigation system was repaired.",
      "The orchard looked dry after weeks without rain new growth appeared after the irrigation system was repaired.",
      "The orchard looked dry after weeks without rain, new growth appearing after the irrigation system was repaired.",
    ],
    correctAnswers: [1],
    explanation: "Choice B correctly joins the contrasting clauses with a comma and but. The other choices contain a run-on or faulty punctuation.",
    tip: "When two full sentences are joined, use a period, semicolon, or comma plus a coordinating conjunction.",
  },
  {
    id: "rw-conv-013",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "hard",
    passage: "The audience applauded loudly, the speaker returned to the stage for one final question.",
    question: "Which choice most effectively revises the sentence?",
    options: [
      "The audience applauded loudly; the speaker returned to the stage for one final question.",
      "The audience applauded loudly, the speaker returned to the stage for one final question.",
      "The audience applauded loudly and the speaker returned to the stage for one final question,",
      "The audience applauded loudly returning to the stage for one final question.",
    ],
    correctAnswers: [0],
    explanation: "Choice A uses a semicolon correctly between two independent clauses. The others include a comma splice or incomplete structure.",
    tip: "When two full sentences are joined, use a period, semicolon, or comma plus a coordinating conjunction.",
  },
  {
    id: "rw-conv-014",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "hard",
    passage: "The weather forecast predicted clear skies, thick fog covered the harbor by dawn.",
    question: "Which choice most effectively revises the sentence?",
    options: [
      "The weather forecast predicted clear skies; nonetheless, thick fog covered the harbor by dawn.",
      "The weather forecast predicted clear skies, nonetheless thick fog covered the harbor by dawn.",
      "The weather forecast predicted clear skies thick fog covered the harbor by dawn.",
      "The weather forecast predicted clear skies, thick fog covering the harbor by dawn.",
    ],
    correctAnswers: [0],
    explanation: "Choice A correctly punctuates a conjunctive adverb joining two independent clauses. The other options create run-on or fragment problems.",
    tip: "When two full sentences are joined, use a period, semicolon, or comma plus a coordinating conjunction.",
  },
  {
    id: "rw-conv-015",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "easy",
    passage: "The internship teaches students to analyze data, write reports, and [UNDERLINED: _____]",
    question: "Which choice completes the sentence in the most logical and grammatical way?",
    options: [
      "present findings to clients.",
      "presenting findings to clients.",
      "the presentation of findings to clients.",
      "to be presenting findings to clients.",
    ],
    correctAnswers: [0],
    explanation: "The list begins with analyze and write, so the third item should match that verb form. Choice A keeps the series parallel.",
    tip: "Items in a series should match one another grammatically.",
  },
  {
    id: "rw-conv-016",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "easy",
    passage: "For the fundraiser, volunteers sorted donations, labeled boxes, and [UNDERLINED: _____]",
    question: "Which choice completes the sentence in the most logical and grammatical way?",
    options: [
      "delivered supplies to the shelter.",
      "delivering supplies to the shelter.",
      "the delivery of supplies to the shelter.",
      "to have delivered supplies to the shelter.",
    ],
    correctAnswers: [0],
    explanation: "The items in the series should all share the same grammatical form. Choice A maintains the parallel sequence of sorted, labeled, and delivered.",
    tip: "Items in a series should match one another grammatically.",
  },
  {
    id: "rw-conv-017",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "medium",
    passage: "The coach asked the players to stretch carefully, to drink water regularly, and [UNDERLINED: _____]",
    question: "Which choice completes the sentence in the most logical and grammatical way?",
    options: [
      "to get enough sleep before the game.",
      "getting enough sleep before the game.",
      "enough sleep before the game.",
      "they should get enough sleep before the game.",
    ],
    correctAnswers: [0],
    explanation: "Because the first two items use infinitives, the third should also use an infinitive. Choice A is parallel.",
    tip: "Items in a series should match one another grammatically.",
  },
  {
    id: "rw-conv-018",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "medium",
    passage: "The new software lets users organize notes quickly, search old files easily, and [UNDERLINED: _____]",
    question: "Which choice completes the sentence in the most logical and grammatical way?",
    options: [
      "share folders securely.",
      "sharing folders securely.",
      "secure folder sharing.",
      "to share folders securely.",
    ],
    correctAnswers: [0],
    explanation: "The sentence uses a series of base-form verbs after lets users. Choice A matches that structure.",
    tip: "Items in a series should match one another grammatically.",
  },
  {
    id: "rw-conv-019",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "medium",
    passage: "The director hoped the new exhibit would inform visitors, inspire curiosity, and [UNDERLINED: _____]",
    question: "Which choice completes the sentence in the most logical and grammatical way?",
    options: [
      "encourage return visits.",
      "encouraging return visits.",
      "the encouragement of return visits.",
      "to encourage return visits.",
    ],
    correctAnswers: [0],
    explanation: "Inform, inspire, and encourage are parallel verbs. The other options disrupt the pattern.",
    tip: "Items in a series should match one another grammatically.",
  },
  {
    id: "rw-conv-020",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "medium",
    passage: "The scholarship committee looked for applicants who were curious, disciplined, and [UNDERLINED: _____]",
    question: "Which choice completes the sentence in the most logical and grammatical way?",
    options: [
      "creative.",
      "creatively.",
      "with creativity.",
      "to create.",
    ],
    correctAnswers: [0],
    explanation: "The adjectives in the series should match: curious, disciplined, and creative. Choice A preserves that parallelism.",
    tip: "Items in a series should match one another grammatically.",
  },
  {
    id: "rw-conv-021",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "hard",
    passage: "[UNDERLINED: Walking through the sculpture garden], _____",
    question: "Which choice most effectively completes the sentence?",
    options: [
      "the curator explained how each piece had been restored.",
      "each piece had been restored by the curator.",
      "the restoration of each piece was explained.",
      "there was an explanation from the curator about each piece.",
    ],
    correctAnswers: [0],
    explanation: "The introductory phrase Walking through the sculpture garden must describe the curator, who is the one doing the walking. Choice A places that modifier next to the correct noun.",
    tip: "An introductory phrase should sit next to the noun it describes.",
  },
  {
    id: "rw-conv-022",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "hard",
    passage: "[UNDERLINED: After finishing the last experiment], _____",
    question: "Which choice most effectively completes the sentence?",
    options: [
      "the students cleaned the lab tables before leaving.",
      "the lab tables were cleaned by the students before leaving.",
      "cleaning the lab tables before leaving.",
      "the last experiment was followed by cleaning the lab tables.",
    ],
    correctAnswers: [0],
    explanation: "The phrase After finishing the last experiment should modify the students. Choice A places the doer immediately after the modifier.",
    tip: "An introductory phrase should sit next to the noun it describes.",
  },
  {
    id: "rw-conv-023",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "hard",
    passage: "[UNDERLINED: Using a telephoto lens], _____",
    question: "Which choice most effectively completes the sentence?",
    options: [
      "Mina captured a sharp image of the eagle from across the lake.",
      "a sharp image of the eagle was captured from across the lake.",
      "the eagle across the lake appeared sharp in the image.",
      "there was a sharp image of the eagle across the lake.",
    ],
    correctAnswers: [0],
    explanation: "The introductory phrase should describe Mina, the person using the lens. Choice A avoids a dangling modifier.",
    tip: "An introductory phrase should sit next to the noun it describes.",
  },
  {
    id: "rw-conv-024",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "hard",
    passage: "[UNDERLINED: To improve accessibility], _____",
    question: "Which choice most effectively completes the sentence?",
    options: [
      "the museum added large-print labels near the entrance.",
      "large-print labels were added near the entrance.",
      "the entrance had large-print labels added.",
      "there were large-print labels added near the entrance.",
    ],
    correctAnswers: [0],
    explanation: "The infinitive phrase To improve accessibility should clearly modify the museum, which took the action. Choice A does that most effectively.",
    tip: "An introductory phrase should sit next to the noun it describes.",
  },
  {
    id: "rw-conv-025",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "hard",
    passage: "[UNDERLINED: Covered with fresh snow], _____",
    question: "Which choice most effectively completes the sentence?",
    options: [
      "the mountain looked brighter in the morning sun.",
      "the morning sun made the mountain look brighter.",
      "the brightness of the mountain increased in the morning sun.",
      "there was a brighter look to the mountain in the morning sun.",
    ],
    correctAnswers: [0],
    explanation: "The phrase Covered with fresh snow needs to describe the mountain. Choice A places the modified noun right after the phrase.",
    tip: "An introductory phrase should sit next to the noun it describes.",
  },
  {
    id: "rw-conv-026",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Sentence Structure",
    difficulty: "hard",
    passage: "[UNDERLINED: While reviewing the draft], _____",
    question: "Which choice most effectively completes the sentence?",
    options: [
      "Jordan noticed that one paragraph repeated the same point twice.",
      "one paragraph repeated the same point twice for Jordan.",
      "the repeated point in one paragraph was noticed.",
      "there was a repeated point in one paragraph.",
    ],
    correctAnswers: [0],
    explanation: "The introductory phrase should describe Jordan, the reviewer. Choice A clearly connects the modifier to the correct subject.",
    tip: "An introductory phrase should sit next to the noun it describes.",
  },
  {
    id: "rw-conv-027",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "easy",
    passage: "Yesterday, the class [UNDERLINED: studies] maps of ocean currents before beginning the lab.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "studies",
      "studied",
      "will study",
      "has studied",
    ],
    correctAnswers: [1],
    explanation: "Because Yesterday signals a completed action in the past, the simple past verb studied is correct.",
    tip: "Use time clues and verb patterns to choose the correct form.",
  },
  {
    id: "rw-conv-028",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "easy",
    passage: "Every spring, the volunteer group [UNDERLINED: plants] wildflowers along the trail.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "plants",
      "planted",
      "had planted",
      "planting",
    ],
    correctAnswers: [0],
    explanation: "Every spring indicates a habitual action, so the simple present verb plants is correct.",
    tip: "Use time clues and verb patterns to choose the correct form.",
  },
  {
    id: "rw-conv-029",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "easy",
    passage: "By the time the guests arrived, the chef had already [UNDERLINED: begin] preparing dessert.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "begin",
      "began",
      "begun",
      "beginning",
    ],
    correctAnswers: [2],
    explanation: "After had, the sentence needs the past participle begun.",
    tip: "Use time clues and verb patterns to choose the correct form.",
  },
  {
    id: "rw-conv-030",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "easy",
    passage: "Last week, the robotics team [UNDERLINED: build] a prototype that could sort small objects.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "build",
      "built",
      "building",
      "has built",
    ],
    correctAnswers: [1],
    explanation: "Last week requires the simple past tense built.",
    tip: "Use time clues and verb patterns to choose the correct form.",
  },
  {
    id: "rw-conv-031",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "easy",
    passage: "The museum guide [UNDERLINED: explains] the painting's symbols during every tour.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "explains",
      "explained",
      "has explained",
      "will explain",
    ],
    correctAnswers: [0],
    explanation: "During every tour shows repeated present-time action, so explains is correct.",
    tip: "Use time clues and verb patterns to choose the correct form.",
  },
  {
    id: "rw-conv-032",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "easy",
    passage: "After the storm ended, the workers [UNDERLINED: repair] the damaged fence.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "repair",
      "repaired",
      "repairs",
      "have repaired",
    ],
    correctAnswers: [1],
    explanation: "After the storm ended places the action in the past, so repaired is correct.",
    tip: "Use time clues and verb patterns to choose the correct form.",
  },
  {
    id: "rw-conv-033",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "easy",
    passage: "The scientist hopes [UNDERLINED: discovering] a simpler way to test the sample.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "discovering",
      "to discover",
      "discovered",
      "discover",
    ],
    correctAnswers: [1],
    explanation: "After hopes, standard English uses the infinitive to discover.",
    tip: "Use time clues and verb patterns to choose the correct form.",
  },
  {
    id: "rw-conv-034",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "easy",
    passage: "The hikers were relieved [UNDERLINED: seeing] the cabin lights in the distance.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "seeing",
      "to see",
      "seen",
      "see",
    ],
    correctAnswers: [1],
    explanation: "Relieved to see is the correct idiomatic construction. The other options are ungrammatical here.",
    tip: "Use time clues and verb patterns to choose the correct form.",
  },
  {
    id: "rw-conv-035",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "medium",
    passage: "For months, the archive [UNDERLINED: digitized] old recordings, and it expects to finish the project in June.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "digitized",
      "has digitized",
      "had digitized",
      "will digitize",
    ],
    correctAnswers: [1],
    explanation: "Has digitized correctly shows an action that began in the past and continues into the present.",
    tip: "For medium verb questions, track the timeline between actions carefully.",
  },
  {
    id: "rw-conv-036",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "medium",
    passage: "When the curtain rose, the audience realized that the lead actor [UNDERLINED: forgets] one prop backstage.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "forgets",
      "forgot",
      "had forgotten",
      "has forgotten",
    ],
    correctAnswers: [2],
    explanation: "The forgetting happened before the audience realized it, so the past perfect had forgotten is needed.",
    tip: "For medium verb questions, track the timeline between actions carefully.",
  },
  {
    id: "rw-conv-037",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "medium",
    passage: "The editor recommended that the final paragraph [UNDERLINED: is revised] before publication.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "is revised",
      "be revised",
      "was revised",
      "revised",
    ],
    correctAnswers: [1],
    explanation: "After recommended that, the subjunctive form be revised is standard.",
    tip: "For medium verb questions, track the timeline between actions carefully.",
  },
  {
    id: "rw-conv-038",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "medium",
    passage: "The river once [UNDERLINED: supports] several mills, but today only their foundations remain.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "supports",
      "supported",
      "has supported",
      "supporting",
    ],
    correctAnswers: [1],
    explanation: "Once places the action in the past, so supported is correct.",
    tip: "For medium verb questions, track the timeline between actions carefully.",
  },
  {
    id: "rw-conv-039",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "medium",
    passage: "By next month, the team will have [UNDERLINED: complete] three rounds of testing.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "complete",
      "completed",
      "completing",
      "completes",
    ],
    correctAnswers: [1],
    explanation: "After will have, the verb must be the past participle completed.",
    tip: "For medium verb questions, track the timeline between actions carefully.",
  },
  {
    id: "rw-conv-040",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "medium",
    passage: "The professor asked the class to keep [UNDERLINED: compare] the two translations as they read.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "compare",
      "compared",
      "comparing",
      "to compare",
    ],
    correctAnswers: [2],
    explanation: "Keep comparing is the correct idiomatic pattern after keep in this context.",
    tip: "For medium verb questions, track the timeline between actions carefully.",
  },
  {
    id: "rw-conv-041",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "medium",
    passage: "Once the seedlings [UNDERLINED: were grown] tall enough, they were moved to the garden beds.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "were grown",
      "grew",
      "had grown",
      "have grown",
    ],
    correctAnswers: [2],
    explanation: "Had grown correctly shows that the seedlings reached that height before they were moved.",
    tip: "For medium verb questions, track the timeline between actions carefully.",
  },
  {
    id: "rw-conv-042",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "medium",
    passage: "The cyclists [UNDERLINED: have worn] reflective gear during yesterday's race because the course began before sunrise.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "have worn",
      "wear",
      "wore",
      "had worn",
    ],
    correctAnswers: [2],
    explanation: "Yesterday's race requires the simple past wore.",
    tip: "For medium verb questions, track the timeline between actions carefully.",
  },
  {
    id: "rw-conv-043",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "medium",
    passage: "The guide encouraged visitors [UNDERLINED: noticing] how the artist repeated certain colors.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "noticing",
      "notice",
      "to notice",
      "noticed",
    ],
    correctAnswers: [2],
    explanation: "Encouraged visitors to notice is the correct verb pattern.",
    tip: "For medium verb questions, track the timeline between actions carefully.",
  },
  {
    id: "rw-conv-044",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "medium",
    passage: "The mayor said that the city [UNDERLINED: invests] in more bike lanes the following year.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "invests",
      "will invest",
      "invested",
      "has invested",
    ],
    correctAnswers: [1],
    explanation: "Because the statement refers to a future action from the time of speaking, will invest is correct.",
    tip: "For medium verb questions, track the timeline between actions carefully.",
  },
  {
    id: "rw-conv-045",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "hard",
    passage: "If the theater [UNDERLINED: was] larger, the school could host the regional festival there.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "was",
      "were",
      "is",
      "has been",
    ],
    correctAnswers: [1],
    explanation: "In a contrary-to-fact conditional statement, standard English uses were rather than was.",
    tip: "Hard verb questions often test conditionals, subjunctive mood, and perfect forms.",
  },
  {
    id: "rw-conv-046",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "hard",
    passage: "Had the team [UNDERLINED: knew] about the road closure, it would have left earlier.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "knew",
      "known",
      "knows",
      "knowing",
    ],
    correctAnswers: [1],
    explanation: "After had in this conditional construction, the past participle known is required.",
    tip: "Hard verb questions often test conditionals, subjunctive mood, and perfect forms.",
  },
  {
    id: "rw-conv-047",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "hard",
    passage: "The scientist would rather that the samples [UNDERLINED: remain] sealed until the humidity drops.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "remains",
      "remained",
      "remain",
      "are remaining",
    ],
    correctAnswers: [2],
    explanation: "After would rather that, standard English uses the base verb remain.",
    tip: "Hard verb questions often test conditionals, subjunctive mood, and perfect forms.",
  },
  {
    id: "rw-conv-048",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "hard",
    passage: "No one expected the sculpture [UNDERLINED: to have collapse] during transport.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "to have collapse",
      "to collapse",
      "to be collapsed",
      "having collapsed",
    ],
    correctAnswers: [1],
    explanation: "Expected the sculpture to collapse is the correct infinitive construction.",
    tip: "Hard verb questions often test conditionals, subjunctive mood, and perfect forms.",
  },
  {
    id: "rw-conv-049",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "hard",
    passage: "The committee insisted that each proposal [UNDERLINED: includes] a detailed budget before review.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "includes",
      "included",
      "include",
      "will include",
    ],
    correctAnswers: [2],
    explanation: "After insisted that, the subjunctive base form include is correct.",
    tip: "Hard verb questions often test conditionals, subjunctive mood, and perfect forms.",
  },
  {
    id: "rw-conv-050",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "hard",
    passage: "Having [UNDERLINED: wrote] several drafts, Lena finally submitted the essay.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "wrote",
      "written",
      "writes",
      "to write",
    ],
    correctAnswers: [1],
    explanation: "After having, the sentence needs the past participle written.",
    tip: "Hard verb questions often test conditionals, subjunctive mood, and perfect forms.",
  },
  {
    id: "rw-conv-051",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "hard",
    passage: "The technician is believed [UNDERLINED: to repaired] the instrument before the test began.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "to repaired",
      "to have repaired",
      "repairing",
      "to be repaired",
    ],
    correctAnswers: [1],
    explanation: "To have repaired correctly expresses an action completed before another past action.",
    tip: "Hard verb questions often test conditionals, subjunctive mood, and perfect forms.",
  },
  {
    id: "rw-conv-052",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Verb Usage",
    difficulty: "hard",
    passage: "If the river cleanup [UNDERLINED: had started] earlier each year, fewer plastic bottles would reach the marsh.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "started",
      "had started",
      "would start",
      "has started",
    ],
    correctAnswers: [1],
    explanation: "The sentence is a contrary-to-fact condition about the past, so had started is correct in the if-clause.",
    tip: "Hard verb questions often test conditionals, subjunctive mood, and perfect forms.",
  },
  {
    id: "rw-conv-053",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "easy",
    passage: "When Jordan and Maya presented the project, [UNDERLINED: them] answered the judges' questions clearly.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "them",
      "they",
      "their",
      "theirs",
    ],
    correctAnswers: [1],
    explanation: "The pronoun is the subject of answered, so the subject form they is required.",
    tip: "Pronouns must match their antecedents in role, number, and possession.",
  },
  {
    id: "rw-conv-054",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "easy",
    passage: "The museum thanked every volunteer because [UNDERLINED: they] had helped prepare the exhibit.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "they",
      "he or she",
      "them",
      "their",
    ],
    correctAnswers: [1],
    explanation: "Every volunteer is singular, so the singular pronoun he or she is the most precise match in standard SAT usage.",
    tip: "Pronouns must match their antecedents in role, number, and possession.",
  },
  {
    id: "rw-conv-055",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "easy",
    passage: "The mayor praised the debate team and invited [UNDERLINED: we] to city hall.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "we",
      "us",
      "our",
      "ours",
    ],
    correctAnswers: [1],
    explanation: "Because the pronoun is the object of invited, the object form us is correct.",
    tip: "Pronouns must match their antecedents in role, number, and possession.",
  },
  {
    id: "rw-conv-056",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "easy",
    passage: "Lena forgot [UNDERLINED: their] notebook on the lab table, so she returned after class to get it.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "their",
      "her",
      "hers",
      "she",
    ],
    correctAnswers: [1],
    explanation: "The antecedent Lena is singular and female in the sentence, so her is the correct pronoun.",
    tip: "Pronouns must match their antecedents in role, number, and possession.",
  },
  {
    id: "rw-conv-057",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "easy",
    passage: "The robot malfunctioned because [UNDERLINED: it's] battery had not been charged.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "it's",
      "its",
      "it is",
      "its'",
    ],
    correctAnswers: [1],
    explanation: "Its is the possessive pronoun; it's means it is.",
    tip: "Pronouns must match their antecedents in role, number, and possession.",
  },
  {
    id: "rw-conv-058",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "easy",
    passage: "The teachers reminded Mia and [UNDERLINED: I] to submit the permission forms.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "I",
      "me",
      "my",
      "mine",
    ],
    correctAnswers: [1],
    explanation: "The pronoun is part of the object of reminded, so me is correct.",
    tip: "Pronouns must match their antecedents in role, number, and possession.",
  },
  {
    id: "rw-conv-059",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "easy",
    passage: "The artist displayed two sculptures, but [UNDERLINED: this] drew most visitors to the back gallery.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "this",
      "the taller one",
      "they",
      "these",
    ],
    correctAnswers: [1],
    explanation: "The taller one gives the sentence a clear antecedent, whereas this is too vague.",
    tip: "Pronouns must match their antecedents in role, number, and possession.",
  },
  {
    id: "rw-conv-060",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "easy",
    passage: "If a student wants to join the choir, [UNDERLINED: they] should attend the first rehearsal.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "they",
      "he or she",
      "them",
      "their",
    ],
    correctAnswers: [1],
    explanation: "On this exam-style item, the most precise singular pronoun to match a student is he or she.",
    tip: "Pronouns must match their antecedents in role, number, and possession.",
  },
  {
    id: "rw-conv-061",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "medium",
    passage: "The director spoke with Maya after [UNDERLINED: she] reviewed the script.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "she",
      "Maya",
      "her",
      "herself",
    ],
    correctAnswers: [1],
    explanation: "The original pronoun she is ambiguous because it could refer to either the director or Maya. Replacing it with Maya clarifies the sentence.",
    tip: "When a pronoun could refer to more than one noun, replace it with a clearer noun or pronoun.",
  },
  {
    id: "rw-conv-062",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "medium",
    passage: "The historian interviewed the mayor and the museum curator before [UNDERLINED: she] wrote the article.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "she",
      "the historian",
      "her",
      "they",
    ],
    correctAnswers: [1],
    explanation: "The pronoun she is unclear because several women could be implied. Repeating the historian removes the ambiguity.",
    tip: "When a pronoun could refer to more than one noun, replace it with a clearer noun or pronoun.",
  },
  {
    id: "rw-conv-063",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "medium",
    passage: "The students presented the mural design to the principal, who praised [UNDERLINED: they] for its creativity.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "they",
      "them",
      "their",
      "theirs",
    ],
    correctAnswers: [1],
    explanation: "Praised takes an object, so them is the correct pronoun form.",
    tip: "When a pronoun could refer to more than one noun, replace it with a clearer noun or pronoun.",
  },
  {
    id: "rw-conv-064",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "medium",
    passage: "Between you and [UNDERLINED: I], the earlier bus route is more reliable.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "I",
      "me",
      "myself",
      "mine",
    ],
    correctAnswers: [1],
    explanation: "After the preposition between, the object pronoun me is required.",
    tip: "When a pronoun could refer to more than one noun, replace it with a clearer noun or pronoun.",
  },
  {
    id: "rw-conv-065",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "medium",
    passage: "The ecologist, [UNDERLINED: which] had studied the marsh for years, noticed the change immediately.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "which",
      "who",
      "whom",
      "whose",
    ],
    correctAnswers: [1],
    explanation: "Who is the correct relative pronoun for a person serving as the subject of the clause.",
    tip: "When a pronoun could refer to more than one noun, replace it with a clearer noun or pronoun.",
  },
  {
    id: "rw-conv-066",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "medium",
    passage: "The novel and [UNDERLINED: it's] sequel were displayed in the front window.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "it's",
      "its",
      "their",
      "theirs",
    ],
    correctAnswers: [1],
    explanation: "Its is the correct possessive form; it's means it is.",
    tip: "When a pronoun could refer to more than one noun, replace it with a clearer noun or pronoun.",
  },
  {
    id: "rw-conv-067",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "medium",
    passage: "Neither the coach nor the captains could explain why [UNDERLINED: they] had been left in the storage room.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "they",
      "the equipment",
      "them",
      "their",
    ],
    correctAnswers: [1],
    explanation: "The sentence needs a noun with a clear antecedent. The equipment makes it clear what had been left in the storage room.",
    tip: "When a pronoun could refer to more than one noun, replace it with a clearer noun or pronoun.",
  },
  {
    id: "rw-conv-068",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "medium",
    passage: "The article compared two maps, but [UNDERLINED: this] was more accurate than the one in the textbook.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "this",
      "the newer map",
      "they",
      "these",
    ],
    correctAnswers: [1],
    explanation: "The newer map clearly identifies the antecedent; this is too vague because two maps are mentioned.",
    tip: "When a pronoun could refer to more than one noun, replace it with a clearer noun or pronoun.",
  },
  {
    id: "rw-conv-069",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "medium",
    passage: "The committee asked Elena and [UNDERLINED: he] to summarize the survey results.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "he",
      "him",
      "his",
      "himself",
    ],
    correctAnswers: [1],
    explanation: "Because the pronoun is part of the object of asked, him is correct.",
    tip: "When a pronoun could refer to more than one noun, replace it with a clearer noun or pronoun.",
  },
  {
    id: "rw-conv-070",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "medium",
    passage: "The playwright revised the ending after the actors said [UNDERLINED: them] found it confusing.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "them",
      "they",
      "their",
      "theirs",
    ],
    correctAnswers: [1],
    explanation: "The pronoun is the subject of found, so they is required.",
    tip: "When a pronoun could refer to more than one noun, replace it with a clearer noun or pronoun.",
  },
  {
    id: "rw-conv-071",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "hard",
    passage: "The article discusses astronomers [UNDERLINED: whom] use radio telescopes to study distant galaxies.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "whom",
      "who",
      "whose",
      "which",
    ],
    correctAnswers: [1],
    explanation: "The pronoun refers to astronomers and functions as the subject of use, so who is correct.",
    tip: "Hard pronoun questions often test case and clarity in complex clauses.",
  },
  {
    id: "rw-conv-072",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "hard",
    passage: "Maya is one of the volunteers [UNDERLINED: who organizes] the archive each weekend.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "who organizes",
      "who organize",
      "whom organize",
      "whose organize",
    ],
    correctAnswers: [1],
    explanation: "The relative pronoun refers to volunteers, which is plural, so the verb should be organize.",
    tip: "Hard pronoun questions often test case and clarity in complex clauses.",
  },
  {
    id: "rw-conv-073",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "hard",
    passage: "The research team gave the interns a checklist so that [UNDERLINED: they] could label the samples correctly.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "they",
      "the interns",
      "them",
      "their",
    ],
    correctAnswers: [1],
    explanation: "They could refer to either the team or the interns. Replacing the pronoun with the interns removes the ambiguity.",
    tip: "Hard pronoun questions often test case and clarity in complex clauses.",
  },
  {
    id: "rw-conv-074",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "hard",
    passage: "The playwright met with the director after [UNDERLINED: her] had revised the second act.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "her",
      "she",
      "hers",
      "herself",
    ],
    correctAnswers: [1],
    explanation: "The pronoun functions as the subject of had revised, so the subject form she is needed.",
    tip: "Hard pronoun questions often test case and clarity in complex clauses.",
  },
  {
    id: "rw-conv-075",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "hard",
    passage: "The panel chose Nadia because the organizers considered [UNDERLINED: she] the strongest candidate.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "she",
      "her",
      "hers",
      "herself",
    ],
    correctAnswers: [1],
    explanation: "The pronoun is the object of considered, so her is correct.",
    tip: "Hard pronoun questions often test case and clarity in complex clauses.",
  },
  {
    id: "rw-conv-076",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "hard",
    passage: "The city planted rows of maples beside the river, and [UNDERLINED: this] reduced summer temperatures along the path.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "this",
      "the new tree canopy",
      "they",
      "these",
    ],
    correctAnswers: [1],
    explanation: "The new tree canopy names the actual antecedent and makes the sentence clearer than the vague pronoun this.",
    tip: "Hard pronoun questions often test case and clarity in complex clauses.",
  },
  {
    id: "rw-conv-077",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "hard",
    passage: "The musicians thanked the conductor, [UNDERLINED: whom] had arranged the final piece for strings alone.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "whom",
      "who",
      "whose",
      "which",
    ],
    correctAnswers: [1],
    explanation: "The relative pronoun is the subject of had arranged, so who is correct.",
    tip: "Hard pronoun questions often test case and clarity in complex clauses.",
  },
  {
    id: "rw-conv-078",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Pronoun Usage",
    difficulty: "hard",
    passage: "The editor handed the photographers' passes to Lena and [UNDERLINED: myself].",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "myself",
      "me",
      "I",
      "mine",
    ],
    correctAnswers: [1],
    explanation: "Reflexive pronouns like myself should be used only when the subject and object are the same person. Here, the object form me is correct.",
    tip: "Hard pronoun questions often test case and clarity in complex clauses.",
  },
  {
    id: "rw-conv-079",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "easy",
    passage: "The school newspaper interviewed Ms. Alvarez [UNDERLINED: the debate coach] about the tournament season.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "the debate coach",
      "the debate coach,",
      ", the debate coach,",
      "; the debate coach",
    ],
    correctAnswers: [2],
    explanation: "The appositive the debate coach is nonessential because Ms. Alvarez already identifies the person. It should be set off with commas on both sides.",
    tip: "Check whether added information is essential before deciding to set it off with commas.",
  },
  {
    id: "rw-conv-080",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "easy",
    passage: "The hikers packed flashlights, extra batteries, [UNDERLINED: and rain jackets] before starting the trail.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "and rain jackets",
      "and, rain jackets",
      "and rain jackets,",
      "rain jackets and",
    ],
    correctAnswers: [0],
    explanation: "The sentence contains a simple series, so no extra punctuation is needed before the final item beyond the standard comma already present.",
    tip: "Check whether added information is essential before deciding to set it off with commas.",
  },
  {
    id: "rw-conv-081",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "easy",
    passage: "The artist displayed [UNDERLINED: its] sketches beside the finished mural.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "its",
      "it's",
      "its'",
      "it is",
    ],
    correctAnswers: [0],
    explanation: "Its is the correct possessive form. The other options are incorrect apostrophe uses or a contraction.",
    tip: "Check whether added information is essential before deciding to set it off with commas.",
  },
  {
    id: "rw-conv-082",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "easy",
    passage: "The committee chose three goals [UNDERLINED: improving attendance, expanding tutoring, and reducing fees] for the new program.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "improving attendance, expanding tutoring, and reducing fees",
      "improving attendance; expanding tutoring; and reducing fees",
      "improving attendance expanding tutoring and reducing fees",
      "improving attendance: expanding tutoring: and reducing fees",
    ],
    correctAnswers: [0],
    explanation: "A standard series of three items is punctuated with commas. The other choices overpunctuate or omit needed punctuation.",
    tip: "Check whether added information is essential before deciding to set it off with commas.",
  },
  {
    id: "rw-conv-083",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "easy",
    passage: "After the storm, the gardeners covered the seedlings with plastic sheets [UNDERLINED: to protect them from frost].",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "to protect them from frost",
      ", to protect them from frost",
      "; to protect them from frost",
      ": to protect them from frost",
    ],
    correctAnswers: [0],
    explanation: "The infinitive phrase to protect them from frost is essential to the sentence's meaning and does not need extra punctuation.",
    tip: "Check whether added information is essential before deciding to set it off with commas.",
  },
  {
    id: "rw-conv-084",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "easy",
    passage: "The coach praised the [UNDERLINED: players'] effort after the comeback win.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "players'",
      "player's",
      "players",
      "players's",
    ],
    correctAnswers: [0],
    explanation: "Because the effort belongs to multiple players, the plural possessive players' is correct.",
    tip: "Check whether added information is essential before deciding to set it off with commas.",
  },
  {
    id: "rw-conv-085",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "easy",
    passage: "The class read essays by Sandra Cisneros, James Baldwin, and [UNDERLINED: Amy Tan].",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "Amy Tan",
      "Amy Tan,",
      ", Amy Tan",
      "; Amy Tan",
    ],
    correctAnswers: [0],
    explanation: "This is a standard series, so Amy Tan needs no extra punctuation beyond the existing commas.",
    tip: "Check whether added information is essential before deciding to set it off with commas.",
  },
  {
    id: "rw-conv-086",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "easy",
    passage: "The museum reopened on Friday [UNDERLINED: after six months of repairs].",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "after six months of repairs",
      ", after six months of repairs",
      "; after six months of repairs",
      ": after six months of repairs",
    ],
    correctAnswers: [0],
    explanation: "The phrase after six months of repairs is essential to the sentence and should not be set off with punctuation.",
    tip: "Check whether added information is essential before deciding to set it off with commas.",
  },
  {
    id: "rw-conv-087",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "medium",
    passage: "The board approved the proposal [UNDERLINED: however] it requested a clearer budget summary.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      ", however,",
      "; however,",
      ": however,",
      " however ",
    ],
    correctAnswers: [1],
    explanation: "The sentence contains two independent clauses joined by the conjunctive adverb however, so a semicolon should come before however and a comma after it.",
    tip: "Use semicolons for closely related independent clauses and colons to introduce explanations or lists.",
  },
  {
    id: "rw-conv-088",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "medium",
    passage: "The exhibit had one major goal [UNDERLINED: to show how translators shape meaning].",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "to show how translators shape meaning",
      "; to show how translators shape meaning",
      ": to show how translators shape meaning",
      ", to show how translators shape meaning",
    ],
    correctAnswers: [2],
    explanation: "An independent clause can be followed by a colon to introduce an explanation or elaboration. Choice C is correct.",
    tip: "Use semicolons for closely related independent clauses and colons to introduce explanations or lists.",
  },
  {
    id: "rw-conv-089",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "medium",
    passage: "The bike racks reduced clutter near the bus stop [UNDERLINED: they also made boarding easier].",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      ", they also made boarding easier",
      "; they also made boarding easier",
      ": they also made boarding easier",
      "- they also made boarding easier",
    ],
    correctAnswers: [1],
    explanation: "The sentence has two independent clauses. A semicolon correctly joins them without a conjunction.",
    tip: "Use semicolons for closely related independent clauses and colons to introduce explanations or lists.",
  },
  {
    id: "rw-conv-090",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "medium",
    passage: "The poet revised the line several times [UNDERLINED: for example] she tested how each version sounded aloud.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      ", for example,",
      "; for example,",
      ": for example,",
      " for example ",
    ],
    correctAnswers: [1],
    explanation: "For example joins two independent clauses as a conjunctive adverb here, so it should follow a semicolon and be followed by a comma.",
    tip: "Use semicolons for closely related independent clauses and colons to introduce explanations or lists.",
  },
  {
    id: "rw-conv-091",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "medium",
    passage: "The astronomy club brought one essential tool [UNDERLINED: a star chart].",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "a star chart",
      ", a star chart",
      "; a star chart",
      ": a star chart",
    ],
    correctAnswers: [3],
    explanation: "The first clause is complete and introduces the specific item, so a colon is appropriate.",
    tip: "Use semicolons for closely related independent clauses and colons to introduce explanations or lists.",
  },
  {
    id: "rw-conv-092",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "medium",
    passage: "The river project benefited local wildlife [UNDERLINED: it also gave students new research opportunities].",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      ", it also gave students new research opportunities",
      "; it also gave students new research opportunities",
      ": it also gave students new research opportunities",
      " it also gave students new research opportunities",
    ],
    correctAnswers: [1],
    explanation: "Because both parts are independent clauses, a semicolon is needed.",
    tip: "Use semicolons for closely related independent clauses and colons to introduce explanations or lists.",
  },
  {
    id: "rw-conv-093",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "medium",
    passage: "The robotics team, [UNDERLINED: after weeks of testing,] finally chose the lighter frame.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "after weeks of testing,",
      "after weeks of testing",
      ", after weeks of testing,",
      "; after weeks of testing,",
    ],
    correctAnswers: [0],
    explanation: "The parenthetical phrase after weeks of testing should be set off with commas on both sides. Since the comma before the phrase is already present, only the closing comma is needed.",
    tip: "Use semicolons for closely related independent clauses and colons to introduce explanations or lists.",
  },
  {
    id: "rw-conv-094",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "medium",
    passage: "The museum restored several fragile objects [UNDERLINED: a clock, a map, and a set of letters].",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "a clock, a map, and a set of letters",
      "; a clock, a map, and a set of letters",
      ": a clock, a map, and a set of letters",
      ", a clock, a map, and a set of letters",
    ],
    correctAnswers: [2],
    explanation: "A colon properly introduces the list after the complete independent clause.",
    tip: "Use semicolons for closely related independent clauses and colons to introduce explanations or lists.",
  },
  {
    id: "rw-conv-095",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "medium",
    passage: "The final speaker arrived late [UNDERLINED: nevertheless] the audience waited quietly.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      ", nevertheless,",
      "; nevertheless,",
      ": nevertheless,",
      " nevertheless ",
    ],
    correctAnswers: [1],
    explanation: "As a conjunctive adverb joining two independent clauses, nevertheless requires a semicolon before it and a comma after it.",
    tip: "Use semicolons for closely related independent clauses and colons to introduce explanations or lists.",
  },
  {
    id: "rw-conv-096",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "medium",
    passage: "The school adopted a simple rule [UNDERLINED: phones stay silent during study hall].",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "phones stay silent during study hall",
      "; phones stay silent during study hall",
      ": phones stay silent during study hall",
      ", phones stay silent during study hall",
    ],
    correctAnswers: [2],
    explanation: "The first clause introduces the rule, and the second explains it, so a colon is correct.",
    tip: "Use semicolons for closely related independent clauses and colons to introduce explanations or lists.",
  },
  {
    id: "rw-conv-097",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "hard",
    passage: "The archive's oldest recording [UNDERLINED: a 1942 jazz performance] was digitized first.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "a 1942 jazz performance",
      ", a 1942 jazz performance,",
      "; a 1942 jazz performance;",
      ": a 1942 jazz performance",
    ],
    correctAnswers: [1],
    explanation: "The appositive a 1942 jazz performance is nonessential and must be set off with commas on both sides.",
    tip: "Hard punctuation questions often require you to combine more than one rule in the same sentence.",
  },
  {
    id: "rw-conv-098",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "hard",
    passage: "The new trail design has one major advantage [UNDERLINED: unlike the old path, it keeps visitors above the wet soil].",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "unlike the old path, it keeps visitors above the wet soil",
      "; unlike the old path, it keeps visitors above the wet soil",
      ": unlike the old path, it keeps visitors above the wet soil",
      ", unlike the old path, it keeps visitors above the wet soil",
    ],
    correctAnswers: [2],
    explanation: "The independent clause introduces a specific advantage, so a colon correctly introduces the explanation that follows.",
    tip: "Hard punctuation questions often require you to combine more than one rule in the same sentence.",
  },
  {
    id: "rw-conv-099",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "hard",
    passage: "The conductor stopped the rehearsal [UNDERLINED: not because the musicians lacked skill, but because the hall's acoustics had changed].",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "not because the musicians lacked skill, but because the hall's acoustics had changed",
      ", not because the musicians lacked skill but because the hall's acoustics had changed",
      "; not because the musicians lacked skill, but because the hall's acoustics had changed",
      ": not because the musicians lacked skill but because the hall's acoustics had changed",
    ],
    correctAnswers: [0],
    explanation: "The inserted phrase is essential to the sentence's meaning, so no extra punctuation is needed before it. The internal comma correctly separates the paired not because/but because structure.",
    tip: "Hard punctuation questions often require you to combine more than one rule in the same sentence.",
  },
  {
    id: "rw-conv-100",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "hard",
    passage: "The project had an unexpected effect [UNDERLINED: students who had joined for extra credit became some of the club's most committed members].",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "students who had joined for extra credit became some of the club's most committed members",
      "; students who had joined for extra credit became some of the club's most committed members",
      ": students who had joined for extra credit became some of the club's most committed members",
      ", students who had joined for extra credit became some of the club's most committed members",
    ],
    correctAnswers: [2],
    explanation: "A colon is correct because the first clause is complete and the second clause explains the unexpected effect.",
    tip: "Hard punctuation questions often require you to combine more than one rule in the same sentence.",
  },
  {
    id: "rw-conv-101",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "hard",
    passage: "The greenhouse now reuses rainwater [UNDERLINED: as a result,] the school has cut summer water purchases.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "as a result,",
      ", as a result,",
      "; as a result,",
      ": as a result,",
    ],
    correctAnswers: [2],
    explanation: "The sentence contains two independent clauses connected by the conjunctive phrase as a result, so a semicolon is needed before it and a comma after it.",
    tip: "Hard punctuation questions often require you to combine more than one rule in the same sentence.",
  },
  {
    id: "rw-conv-102",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "hard",
    passage: "The article praised one design feature above all others [UNDERLINED: the ramped entrance, which made the building easier to navigate for everyone].",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "the ramped entrance, which made the building easier to navigate for everyone",
      ", the ramped entrance which made the building easier to navigate for everyone",
      "; the ramped entrance, which made the building easier to navigate for everyone",
      ": the ramped entrance, which made the building easier to navigate for everyone",
    ],
    correctAnswers: [3],
    explanation: "The first clause is complete, so a colon can introduce the specific feature. The nonrestrictive clause which made... is correctly set off with a comma.",
    tip: "Hard punctuation questions often require you to combine more than one rule in the same sentence.",
  },
  {
    id: "rw-conv-103",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "hard",
    passage: "The editor cut one sentence from the article [UNDERLINED: the sentence repeated information that already appeared in the headline].",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "the sentence repeated information that already appeared in the headline",
      "; the sentence repeated information that already appeared in the headline",
      ": the sentence repeated information that already appeared in the headline",
      ", the sentence repeated information that already appeared in the headline",
    ],
    correctAnswers: [2],
    explanation: "A colon is appropriate because the second clause explains which sentence was cut and why.",
    tip: "Hard punctuation questions often require you to combine more than one rule in the same sentence.",
  },
  {
    id: "rw-conv-104",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Punctuation",
    difficulty: "hard",
    passage: "The volunteers prepared carefully [UNDERLINED: they packed gloves, maps, and first-aid supplies—and they reviewed the weather forecast twice].",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      ", they packed gloves, maps, and first-aid supplies—and they reviewed the weather forecast twice",
      "; they packed gloves, maps, and first-aid supplies—and they reviewed the weather forecast twice",
      ": they packed gloves, maps, and first-aid supplies—and they reviewed the weather forecast twice",
      " they packed gloves, maps, and first-aid supplies—and they reviewed the weather forecast twice",
    ],
    correctAnswers: [2],
    explanation: "The first clause is complete and the second elaborates on how the volunteers prepared, so a colon is correct. The dash within the second clause adds emphasis to the second action.",
    tip: "Hard punctuation questions often require you to combine more than one rule in the same sentence.",
  },
  {
    id: "rw-conv-105",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "easy",
    passage: "The basket of apples [UNDERLINED: sit] on the counter by the window.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "sit",
      "sits",
      "are sitting",
      "have sat",
    ],
    correctAnswers: [1],
    explanation: "The subject is basket, which is singular, so the singular verb sits is correct.",
    tip: "Ignore prepositional phrases and find the true subject before choosing the verb.",
  },
  {
    id: "rw-conv-106",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "easy",
    passage: "The list of ingredients [UNDERLINED: include] cinnamon, ginger, and cloves.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "include",
      "includes",
      "including",
      "have included",
    ],
    correctAnswers: [1],
    explanation: "The subject is list, a singular noun, so includes is correct.",
    tip: "Ignore prepositional phrases and find the true subject before choosing the verb.",
  },
  {
    id: "rw-conv-107",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "easy",
    passage: "One of the museum's new exhibits [UNDERLINED: focus] on local jazz history.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "focus",
      "focuses",
      "have focused",
      "are focusing",
    ],
    correctAnswers: [1],
    explanation: "The subject is one, which is singular, so the verb should be focuses.",
    tip: "Ignore prepositional phrases and find the true subject before choosing the verb.",
  },
  {
    id: "rw-conv-108",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "easy",
    passage: "The box of old photographs [UNDERLINED: were] stored in the attic for years.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "were",
      "was",
      "being",
      "have been",
    ],
    correctAnswers: [1],
    explanation: "The subject box is singular, so the singular verb was is required.",
    tip: "Ignore prepositional phrases and find the true subject before choosing the verb.",
  },
  {
    id: "rw-conv-109",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "easy",
    passage: "Each of the students [UNDERLINED: bring] a notebook to the workshop.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "bring",
      "brings",
      "bringing",
      "have brought",
    ],
    correctAnswers: [1],
    explanation: "Each is singular, so the singular verb brings is correct.",
    tip: "Ignore prepositional phrases and find the true subject before choosing the verb.",
  },
  {
    id: "rw-conv-110",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "easy",
    passage: "The bouquet of wildflowers [UNDERLINED: look] brighter in sunlight.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "look",
      "looks",
      "looking",
      "have looked",
    ],
    correctAnswers: [1],
    explanation: "The subject bouquet is singular, so looks is correct.",
    tip: "Ignore prepositional phrases and find the true subject before choosing the verb.",
  },
  {
    id: "rw-conv-111",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "easy",
    passage: "The sound of the drums [UNDERLINED: echo] across the field.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "echo",
      "echoes",
      "have echoed",
      "are echoing",
    ],
    correctAnswers: [1],
    explanation: "The singular subject sound takes the singular verb echoes.",
    tip: "Ignore prepositional phrases and find the true subject before choosing the verb.",
  },
  {
    id: "rw-conv-112",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "easy",
    passage: "A stack of library books [UNDERLINED: remain] on the front desk.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "remain",
      "remains",
      "remaining",
      "have remained",
    ],
    correctAnswers: [1],
    explanation: "The subject is stack, which is singular, so remains is correct.",
    tip: "Ignore prepositional phrases and find the true subject before choosing the verb.",
  },
  {
    id: "rw-conv-113",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "medium",
    passage: "The captain, along with two assistants, [UNDERLINED: lead] the warm-up before each game.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "lead",
      "leads",
      "leading",
      "have led",
    ],
    correctAnswers: [1],
    explanation: "The subject is captain, which is singular. The phrase along with two assistants does not change the verb to plural.",
    tip: "In tricky agreement questions, identify whether the real subject is singular or plural, then ignore interrupters.",
  },
  {
    id: "rw-conv-114",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "medium",
    passage: "Neither the mayor nor the council members [UNDERLINED: was] willing to delay the vote.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "was",
      "were",
      "is",
      "has been",
    ],
    correctAnswers: [1],
    explanation: "With neither...nor, the verb agrees with the subject closer to it. Council members is plural, so were is correct.",
    tip: "In tricky agreement questions, identify whether the real subject is singular or plural, then ignore interrupters.",
  },
  {
    id: "rw-conv-115",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "medium",
    passage: "There [UNDERLINED: is] several reasons to preserve the wetland trail.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "is",
      "are",
      "was",
      "has been",
    ],
    correctAnswers: [1],
    explanation: "In an there is/are construction, the verb agrees with the subject that follows. Several reasons is plural, so are is correct.",
    tip: "In tricky agreement questions, identify whether the real subject is singular or plural, then ignore interrupters.",
  },
  {
    id: "rw-conv-116",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "medium",
    passage: "The committee [UNDERLINED: meet] every Thursday to review applications.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "meet",
      "meets",
      "have met",
      "are meeting",
    ],
    correctAnswers: [1],
    explanation: "Committee is treated as a singular unit here, so meets is correct.",
    tip: "In tricky agreement questions, identify whether the real subject is singular or plural, then ignore interrupters.",
  },
  {
    id: "rw-conv-117",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "medium",
    passage: "Either the lab manager or the interns [UNDERLINED: checks] the samples at closing time.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "checks",
      "check",
      "is checking",
      "has checked",
    ],
    correctAnswers: [1],
    explanation: "With either...or, the verb agrees with the nearer subject. Interns is plural, so check is correct.",
    tip: "In tricky agreement questions, identify whether the real subject is singular or plural, then ignore interrupters.",
  },
  {
    id: "rw-conv-118",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "medium",
    passage: "A series of short workshops [UNDERLINED: help] new volunteers learn the process.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "help",
      "helps",
      "helping",
      "has helped",
    ],
    correctAnswers: [1],
    explanation: "The subject is series, which is singular, so helps is correct despite the plural noun workshops in the phrase.",
    tip: "In tricky agreement questions, identify whether the real subject is singular or plural, then ignore interrupters.",
  },
  {
    id: "rw-conv-119",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "medium",
    passage: "The instructions on the side of the box [UNDERLINED: explains] how to assemble the model.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "explains",
      "explain",
      "has explained",
      "is explaining",
    ],
    correctAnswers: [1],
    explanation: "The subject instructions is plural, so explain is correct.",
    tip: "In tricky agreement questions, identify whether the real subject is singular or plural, then ignore interrupters.",
  },
  {
    id: "rw-conv-120",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "medium",
    passage: "The number of visitors [UNDERLINED: have increased] since the exhibit reopened.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "have increased",
      "has increased",
      "increase",
      "are increasing",
    ],
    correctAnswers: [1],
    explanation: "The phrase the number is singular, so the correct verb is has increased.",
    tip: "In tricky agreement questions, identify whether the real subject is singular or plural, then ignore interrupters.",
  },
  {
    id: "rw-conv-121",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "medium",
    passage: "There [UNDERLINED: remains] several unanswered questions about the manuscript.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "remains",
      "remain",
      "has remained",
      "is remaining",
    ],
    correctAnswers: [1],
    explanation: "The subject questions is plural, so the plural verb remain is correct.",
    tip: "In tricky agreement questions, identify whether the real subject is singular or plural, then ignore interrupters.",
  },
  {
    id: "rw-conv-122",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "medium",
    passage: "One hundred dollars [UNDERLINED: are] too much for a student to spend on one ticket.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "are",
      "is",
      "have been",
      "being",
    ],
    correctAnswers: [1],
    explanation: "An amount of money is treated as singular when considered as one sum, so is is correct.",
    tip: "In tricky agreement questions, identify whether the real subject is singular or plural, then ignore interrupters.",
  },
  {
    id: "rw-conv-123",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "hard",
    passage: "The effects of the new insulation on the classrooms [UNDERLINED: was] immediately noticeable.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "was",
      "were",
      "is",
      "has been",
    ],
    correctAnswers: [1],
    explanation: "The subject effects is plural, so the plural verb were is required.",
    tip: "Hard agreement questions often involve clauses, measurements, or expressions that sound plural but may act singular—or vice versa.",
  },
  {
    id: "rw-conv-124",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "hard",
    passage: "More than one student [UNDERLINED: have asked] to join the research project.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "have asked",
      "has asked",
      "ask",
      "are asking",
    ],
    correctAnswers: [1],
    explanation: "Although it sounds plural, more than one takes a singular verb in standard English: has asked.",
    tip: "Hard agreement questions often involve clauses, measurements, or expressions that sound plural but may act singular—or vice versa.",
  },
  {
    id: "rw-conv-125",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "hard",
    passage: "Every map and every photograph in the archive [UNDERLINED: need] to be handled carefully.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "need",
      "needs",
      "are needing",
      "have needed",
    ],
    correctAnswers: [1],
    explanation: "When every modifies singular nouns joined by and, the subject is treated as singular, so needs is correct.",
    tip: "Hard agreement questions often involve clauses, measurements, or expressions that sound plural but may act singular—or vice versa.",
  },
  {
    id: "rw-conv-126",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "hard",
    passage: "The data from the final trial [UNDERLINED: suggests] that the new filter works better.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "suggests",
      "suggest",
      "has suggested",
      "is suggesting",
    ],
    correctAnswers: [1],
    explanation: "Data is treated as a plural noun in formal scientific usage here, so suggest is the best choice.",
    tip: "Hard agreement questions often involve clauses, measurements, or expressions that sound plural but may act singular—or vice versa.",
  },
  {
    id: "rw-conv-127",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "hard",
    passage: "What the students proposed [UNDERLINED: were] three separate solutions to the timing problem.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "were",
      "was",
      "have been",
      "are",
    ],
    correctAnswers: [1],
    explanation: "The subject of the sentence is the clause What the students proposed, which is singular; therefore, was is correct.",
    tip: "Hard agreement questions often involve clauses, measurements, or expressions that sound plural but may act singular—or vice versa.",
  },
  {
    id: "rw-conv-128",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "hard",
    passage: "The ethics of the decision [UNDERLINED: remain] under debate among the researchers.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "remain",
      "remains",
      "remaining",
      "has remained",
    ],
    correctAnswers: [1],
    explanation: "Ethics, when referring to a field or concept, is treated as singular here, so remains is correct.",
    tip: "Hard agreement questions often involve clauses, measurements, or expressions that sound plural but may act singular—or vice versa.",
  },
  {
    id: "rw-conv-129",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "hard",
    passage: "Five miles [UNDERLINED: stretch] farther than the hikers had expected in the heat.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "stretch",
      "stretches",
      "are stretching",
      "have stretched",
    ],
    correctAnswers: [1],
    explanation: "A distance treated as a single amount takes a singular verb, so stretches is correct.",
    tip: "Hard agreement questions often involve clauses, measurements, or expressions that sound plural but may act singular—or vice versa.",
  },
  {
    id: "rw-conv-130",
    section: "reading-writing",
    domain: "standard-english-conventions",
    subdomain: "Subject-Verb Agreement",
    difficulty: "hard",
    passage: "The works of the poet [UNDERLINED: includes] several pieces translated from Arabic.",
    question: "Which choice completes the sentence so that it conforms to standard English?",
    options: [
      "includes",
      "include",
      "has included",
      "is including",
    ],
    correctAnswers: [1],
    explanation: "The plural subject works takes the plural verb include.",
    tip: "Hard agreement questions often involve clauses, measurements, or expressions that sound plural but may act singular—or vice versa.",
  },
];
