import type { SATQuestion } from './index';

export const rwExpressionQuestions: SATQuestion[] = [
  {
    id: "rw-expr-001",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "easy",
    passage: "[1] The city converted an empty lot into a community garden. [UNDERLINED: At first, however, the lot was covered with weeds and broken concrete.] [2] Volunteers built raised beds and installed a water barrel. [3] By July, neighbors were trading tomatoes and herbs. [4] The garden now serves as a weekly meeting place.",
    question: "To improve the paragraph's logical flow, where should the underlined sentence be placed?",
    options: [
      "After sentence 1",
      "After sentence 2",
      "After sentence 3",
      "After sentence 4",
    ],
    correctAnswers: [0],
    explanation: "The paragraph should move from the city's decision to transform the lot to the lot's original condition and then to the volunteers' work. Placing the sentence after sentence 1 creates that cause-and-effect sequence.",
    tip: "When a question asks about organization, look for the order that makes events unfold most logically.",
  },
  {
    id: "rw-expr-002",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "easy",
    passage: "[UNDERLINED: People like to borrow books from libraries.] The Eastview Library recently opened a makerspace with sewing machines, 3D printers, and recording equipment. Staff members report that students now stay longer after school to finish creative projects. The new room has also attracted residents who had not visited the library in years.",
    question: "Which choice most effectively replaces the underlined sentence and introduces the paragraph?",
    options: [
      "Libraries have existed in many towns for hundreds of years.",
      "The Eastview Library is expanding its role by offering a makerspace for hands-on creative work.",
      "Reading quietly can be an enjoyable weekend activity for many people.",
      "Some buildings contain rooms with tables, lights, and electrical outlets.",
    ],
    correctAnswers: [1],
    explanation: "Choice B introduces the paragraph's specific focus: the library's new makerspace and its broader role in the community. The other choices are either too general or do not connect clearly to the details that follow.",
    tip: "A strong introduction previews the paragraph's main idea, not just the broad topic.",
  },
  {
    id: "rw-expr-003",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "easy",
    passage: "Students at Bayview High began recording interviews with longtime residents. They asked each resident about neighborhood businesses, local celebrations, and major storms. The audio files are now stored in the town museum's digital archive. [UNDERLINED: The interviews are very interesting to listen to.]",
    question: "Which choice most effectively replaces the underlined sentence and concludes the paragraph?",
    options: [
      "The project preserves community memories that future researchers and residents can study.",
      "The students used microphones, headphones, and laptops during the project.",
      "Many towns have museums that collect historical objects and photographs.",
      "Listening carefully is an important skill in many school assignments.",
    ],
    correctAnswers: [0],
    explanation: "Choice A strengthens the conclusion by showing why the interviews matter: they preserve local history for future use. The other choices add side details or broad statements instead of providing a purposeful conclusion.",
    tip: "The best conclusion often explains the significance of the information that came before it.",
  },
  {
    id: "rw-expr-004",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "easy",
    passage: "[1] A science teacher challenged students to design solar ovens from cardboard boxes and foil. [2] Some early prototypes leaked heat through loose seams. [UNDERLINED: After testing several designs, the class added dark paper to absorb more sunlight.] [3] The revised ovens warmed slices of apple in less than twenty minutes. [4] Students then compared which design choices produced the fastest results.",
    question: "To improve the paragraph's organization, where should the underlined sentence be placed?",
    options: [
      "Before sentence 1",
      "After sentence 1",
      "After sentence 2",
      "After sentence 4",
    ],
    correctAnswers: [2],
    explanation: "The class would first discover that the early models leaked heat and then revise the design. Placing the underlined sentence after sentence 2 keeps the problem and solution together before the results in sentence 3.",
    tip: "Put solution details after the problem they solve and before the results they produce.",
  },
  {
    id: "rw-expr-005",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "easy",
    passage: "[UNDERLINED: Traveling can help people learn new things.] Last spring, the art club visited a museum exhibition about mural restoration. Conservators demonstrated how they remove dirt, match pigments, and repair small cracks in painted walls. After the trip, club members created a hallway display explaining what they had learned about preserving public art.",
    question: "Which choice most effectively replaces the underlined sentence and introduces the paragraph?",
    options: [
      "A museum visit showed the art club how experts restore and preserve murals.",
      "Museums can be large, quiet buildings filled with many different objects.",
      "Students often enjoy taking field trips with their classmates.",
      "Paint can appear in many colors, shades, and finishes.",
    ],
    correctAnswers: [0],
    explanation: "Choice A directly introduces the specific subject of the paragraph: what the art club learned during a museum visit about mural restoration. The other choices are either too broad or too disconnected from the supporting details.",
    tip: "An effective introduction names the specific topic the paragraph develops.",
  },
  {
    id: "rw-expr-006",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "easy",
    passage: "The school newspaper launched a weekly podcast about student life. Each episode features short interviews with athletes, musicians, and club leaders. Teachers now play selected segments during advisory meetings. [UNDERLINED: The podcast is pretty cool for everyone at school.]",
    question: "Which choice most effectively replaces the underlined sentence and concludes the paragraph?",
    options: [
      "As a result, the podcast has become a practical way to share student voices across campus.",
      "The hosts record each episode with one microphone and a laptop.",
      "Podcasts can include music, sound effects, and spoken conversation.",
      "Some students also read print articles during lunch.",
    ],
    correctAnswers: [0],
    explanation: "Choice A draws a clear conclusion from the evidence in the paragraph by explaining the podcast's value to the school community. The other choices either introduce unrelated details or restate information without showing significance.",
    tip: "Conclusions should synthesize the paragraph's details into a meaningful takeaway.",
  },
  {
    id: "rw-expr-007",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "easy",
    passage: "[1] A town installed bike racks near its busiest bus stops. [UNDERLINED: Before the racks arrived, riders often locked bicycles to trees and signposts.] [2] The new racks give commuters a sturdier place to leave their bikes. [3] As a result, the sidewalks near the stops are less cluttered. [4] Transit officials say the change has also made boarding easier during rush hour.",
    question: "Where should the underlined sentence be placed to make the paragraph most logical?",
    options: [
      "Before sentence 1",
      "After sentence 1",
      "After sentence 2",
      "After sentence 4",
    ],
    correctAnswers: [1],
    explanation: "Sentence 1 presents the new racks. The underlined sentence should follow it to explain the problem the racks solved before the paragraph moves to the benefits of the new setup.",
    tip: "Background about an earlier problem usually belongs right after the sentence that introduces the solution.",
  },
  {
    id: "rw-expr-008",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "medium",
    passage: "[UNDERLINED: Trees are important in many places.] Volunteers in Pine Ridge spent a Saturday planting young shade trees along a playground that becomes hot in late afternoon. The group chose species that can handle dry summers and provide broad canopies as they mature. Town leaders expect the new trees to make the park more comfortable for families over time.",
    question: "Which choice best replaces the underlined sentence and introduces the paragraph?",
    options: [
      "A weekend tree-planting project aimed to make Pine Ridge's playground cooler and more inviting.",
      "Plants need sunlight, water, and nutrients to grow properly.",
      "Many communities have parks with swings, benches, and walking paths.",
      "Some volunteers prefer outdoor projects to indoor ones.",
    ],
    correctAnswers: [0],
    explanation: "Choice A previews the paragraph's main focus: a specific tree-planting effort and its purpose. The other choices mention related ideas but do not set up the paragraph as effectively.",
    tip: "Look for the choice that connects most directly to the paragraph's specific details and purpose.",
  },
  {
    id: "rw-expr-009",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "medium",
    passage: "Researchers restored a wetland trail by adding a raised boardwalk over muddy ground. The new path keeps visitors from trampling fragile grasses and nesting sites. Since the boardwalk opened, more classes have used the area for field observations. [UNDERLINED: Wetlands can contain water, soil, and many kinds of plants.]",
    question: "Which choice best replaces the underlined sentence and concludes the paragraph?",
    options: [
      "The project therefore protects the habitat while making it easier for students to study it responsibly.",
      "The boardwalk is made of planks, railings, and metal fasteners.",
      "Many science classes include outdoor activities during the year.",
      "Students sometimes sketch plants when they visit natural areas.",
    ],
    correctAnswers: [0],
    explanation: "Choice A ties together the two key benefits discussed in the paragraph—protecting the habitat and expanding access for classes. The other choices add side information rather than a strong concluding idea.",
    tip: "A good conclusion should pull together the paragraph's main benefits or results.",
  },
  {
    id: "rw-expr-010",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "medium",
    passage: "[1] The museum added labels in English and Spanish to several exhibits. [2] Families said the bilingual signs made the displays easier to discuss together. [UNDERLINED: Staff members had spent months translating captions and checking them with community volunteers.] [3] Attendance at weekend programs then increased. [4] Museum leaders now plan to expand the labels to more galleries.",
    question: "To improve the paragraph's flow, where should the underlined sentence be placed?",
    options: [
      "Before sentence 1",
      "After sentence 1",
      "After sentence 2",
      "After sentence 4",
    ],
    correctAnswers: [0],
    explanation: "The translation work happened before the labels were added, so the sentence should come before sentence 1. That order gives the reader the preparation first, then the change, then the results.",
    tip: "Chronological clues like had spent often signal that a sentence belongs earlier in the paragraph.",
  },
  {
    id: "rw-expr-011",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "medium",
    passage: "[UNDERLINED: Music can be saved in many different ways.] A university archive recently began digitizing fragile jazz recordings from the 1940s. Engineers clean each record, capture the audio at high resolution, and store backup copies on secure servers. The project will allow musicians and historians to study rare performances without handling the original discs.",
    question: "Which choice most effectively replaces the underlined sentence and introduces the paragraph?",
    options: [
      "A university project is preserving rare jazz recordings by converting them to digital files.",
      "Songs are often played through speakers so listeners can hear them clearly.",
      "Many archives contain shelves, cabinets, and worktables.",
      "Musicians sometimes perform pieces that were written decades earlier.",
    ],
    correctAnswers: [0],
    explanation: "Choice A directly sets up the paragraph's focus on a digitization project and its purpose. The other choices are too general and do not prepare the reader for the specific details that follow.",
    tip: "The best introductory sentence should sound like the topic sentence of the paragraph.",
  },
  {
    id: "rw-expr-012",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "medium",
    passage: "The cafeteria began collecting food scraps for compost instead of sending them to the trash. Garden club members mix the scraps with dry leaves in bins behind the greenhouse. A few months later, the finished compost is added to campus flower beds. [UNDERLINED: Composting has many steps that happen over time.]",
    question: "Which choice most effectively replaces the underlined sentence and concludes the paragraph?",
    options: [
      "By turning leftovers into a useful soil amendment, the program reduces waste and supports the campus gardens.",
      "Leaves, peels, and stems can all be included in compost piles.",
      "Some students eat lunch early, while others eat later in the day.",
      "The greenhouse also contains watering cans and seed trays.",
    ],
    correctAnswers: [0],
    explanation: "Choice A provides a clear conclusion by explaining the value of the composting program. The other options introduce disconnected details instead of emphasizing the paragraph's main point.",
    tip: "Choose the conclusion that answers the question So what?",
  },
  {
    id: "rw-expr-013",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "medium",
    passage: "[1] Engineers tested bird-safe film on the windows of a glass office building. [2] The film includes a subtle pattern that birds can see more easily than people can. [3] Fewer bird collisions were recorded during migration season. [UNDERLINED: Building managers decided to try the film after volunteers documented repeated collisions near the entrance.] [4] The owners are now considering similar updates for other buildings.",
    question: "Where should the underlined sentence be placed to improve the paragraph's organization?",
    options: [
      "Before sentence 1",
      "After sentence 2",
      "After sentence 3",
      "After sentence 4",
    ],
    correctAnswers: [0],
    explanation: "Managers would decide to test the film before engineers tested it. Placing the sentence before sentence 1 establishes the motivation for the project before describing the solution and its results.",
    tip: "If a sentence explains why a project began, it often belongs before the details of the project itself.",
  },
  {
    id: "rw-expr-014",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "medium",
    passage: "[UNDERLINED: Technology can help people share information.] The debate team created a website that posts practice schedules, tournament notes, and sample arguments. New members say the site helps them prepare more efficiently because materials are organized in one place. Coaches have also used the site to share quick feedback after competitions.",
    question: "Which choice best replaces the underlined sentence and introduces the paragraph?",
    options: [
      "The debate team uses a website to organize materials and communicate more effectively.",
      "Websites can include text, images, links, and videos.",
      "Many students join clubs to meet people with similar interests.",
      "Computers and phones both connect to the internet in different ways.",
    ],
    correctAnswers: [0],
    explanation: "Choice A introduces both the topic—the debate team's website—and the paragraph's central idea—using it to organize communication. The other choices are too broad or only loosely related.",
    tip: "An SAT topic sentence should be specific enough that every later sentence clearly supports it.",
  },
  {
    id: "rw-expr-015",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "medium",
    passage: "After a storm, volunteers gathered plastic bottles and fishing line from the banks of the Graystone River. They sorted the trash into categories so environmental scientists could track what types of waste appeared most often. The cleanup team then presented its findings to the town council. [UNDERLINED: Rivers flow through many communities and can be important natural resources.]",
    question: "Which choice best replaces the underlined sentence and concludes the paragraph?",
    options: [
      "The project not only removed litter but also supplied data that can guide future pollution-prevention efforts.",
      "The volunteers wore gloves, boots, and bright safety vests during the cleanup.",
      "Town councils often hold public meetings to discuss local issues.",
      "Scientists sometimes sort items into groups so they can count them later.",
    ],
    correctAnswers: [0],
    explanation: "Choice A provides a strong conclusion by showing the full impact of the cleanup: it improved the riverbank and produced useful evidence. The other choices add isolated details without synthesizing the paragraph.",
    tip: "The best concluding sentence usually connects the paragraph's details to a broader purpose or result.",
  },
  {
    id: "rw-expr-016",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "medium",
    passage: "[1] The astronomy club planned an evening event so families could view Jupiter through the school's telescope. [UNDERLINED: Earlier that week, members had practiced aligning the telescope and adjusting its focus.] [2] On the night of the event, the line to look through the telescope stretched across the courtyard. [3] Club officers answered questions about the planet's clouds and moons. [4] Many guests said they would attend future stargazing programs.",
    question: "Where should the underlined sentence be placed?",
    options: [
      "Before sentence 1",
      "After sentence 1",
      "After sentence 2",
      "After sentence 4",
    ],
    correctAnswers: [1],
    explanation: "The underlined sentence describes preparation for the event, so it fits best after sentence 1, which introduces the plan, and before the paragraph moves to what happened at the event itself.",
    tip: "Preparation details usually belong after the plan is introduced and before the event's outcome.",
  },
  {
    id: "rw-expr-017",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "medium",
    passage: "[UNDERLINED: Many performances happen in theaters.] To attract more families, the Riverside Playhouse began offering Saturday matinees with reduced ticket prices. Attendance among middle school students nearly doubled during the first month of the new schedule. The theater now plans to pair future matinees with short backstage tours.",
    question: "Which choice best replaces the underlined sentence and introduces the paragraph?",
    options: [
      "The Riverside Playhouse changed its schedule to make performances more accessible to families.",
      "Actors often memorize lines before opening night.",
      "Tickets can be sold online, over the phone, or at the box office.",
      "Some audiences prefer comedies, while others prefer dramas.",
    ],
    correctAnswers: [0],
    explanation: "Choice A clearly previews the paragraph's focus on a scheduling change designed to increase access. The other choices are general statements that do not set up the paragraph's main point.",
    tip: "If the paragraph is about a change, the best introduction usually names that change and its purpose.",
  },
  {
    id: "rw-expr-018",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "hard",
    passage: "Students in a coding mentorship program met weekly with local software engineers. During each session, the mentors reviewed code, suggested debugging strategies, and described their careers. Several students later said the meetings made technical jobs seem more attainable. [UNDERLINED: Many careers require workers to learn new skills over time.]",
    question: "Which choice best replaces the underlined sentence and concludes the paragraph?",
    options: [
      "By connecting students with professionals, the program turned abstract career ideas into realistic possibilities.",
      "Software engineers often use laptops, monitors, and testing tools.",
      "Weekly meetings can help groups stay organized and focused.",
      "Some students also joined the school's computer club.",
    ],
    correctAnswers: [0],
    explanation: "Choice A concludes the paragraph by explaining why the mentorship mattered. The other choices either add tangential information or restate broad ideas without linking them to the program's impact.",
    tip: "For conclusions, prefer choices that show impact rather than repeating facts.",
  },
  {
    id: "rw-expr-019",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "hard",
    passage: "[1] A transit agency tested electric buses on two downtown routes. [2] Drivers said the buses accelerated smoothly and produced less noise at stops. [UNDERLINED: The agency had selected the routes because they included frequent stops and heavy ridership.] [3] Passengers also responded positively to the quieter rides. [4] Transit officials are now reviewing whether to expand the fleet.",
    question: "To improve the paragraph's organization, where should the underlined sentence be placed?",
    options: [
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
      "After sentence 4",
    ],
    correctAnswers: [1],
    explanation: "The sentence explains how the routes were chosen for the test, so it belongs after sentence 1, which introduces the test itself, and before the paragraph shifts to drivers' and passengers' reactions.",
    tip: "Selection criteria belong near the sentence that introduces the project or experiment.",
  },
  {
    id: "rw-expr-020",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "hard",
    passage: "[UNDERLINED: Some buildings include signs and labels.] A history museum recently added tactile maps and large-print captions near its most visited exhibits. Visitors with low vision reported that the new materials made it easier to navigate the galleries independently. Museum staff now plan to adapt more exhibits using similar features.",
    question: "Which choice best replaces the underlined sentence and introduces the paragraph?",
    options: [
      "A history museum is improving accessibility by adding tactile maps and large-print captions.",
      "Museums often arrange exhibits according to time period or theme.",
      "Visitors can usually purchase tickets at a front desk or online.",
      "Different signs use different fonts, colors, and materials.",
    ],
    correctAnswers: [0],
    explanation: "Choice A introduces the paragraph's exact focus: specific accessibility improvements at a museum. The other choices are too broad and do not prepare the reader for the details that follow.",
    tip: "Choose the introduction that sounds like a summary of the whole paragraph.",
  },
  {
    id: "rw-expr-021",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "hard",
    passage: "A biology class planted a patch of milkweed and wildflowers beside the football field. Within weeks, students observed more bees and butterflies visiting the area during lunch. The class later posted signs explaining how pollinator gardens support local ecosystems. [UNDERLINED: Butterflies and bees are insects that move from flower to flower.]",
    question: "Which choice best replaces the underlined sentence and concludes the paragraph?",
    options: [
      "The garden therefore serves as both a habitat for pollinators and a living lesson for students.",
      "Wildflowers can bloom in several colors throughout the growing season.",
      "Students often create posters to share information with classmates.",
      "Football fields are usually surrounded by fences or walkways.",
    ],
    correctAnswers: [0],
    explanation: "Choice A draws together the paragraph's two ideas: the garden helps pollinators and teaches students. The other options add extra facts without providing a clear conclusion.",
    tip: "A conclusion should unite the paragraph's examples under one main takeaway.",
  },
  {
    id: "rw-expr-022",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "hard",
    passage: "[1] The student council wanted to reduce the noise in the cafeteria during study hall. [UNDERLINED: Council members first surveyed students about why they found the space distracting.] [2] Many students said constant phone alerts were a major problem. [3] In response, the council tested a phone-free study hour twice a week. [4] Teachers reported that the room became noticeably calmer.",
    question: "Where should the underlined sentence be placed to create the most logical progression?",
    options: [
      "After sentence 1",
      "After sentence 2",
      "After sentence 3",
      "After sentence 4",
    ],
    correctAnswers: [0],
    explanation: "The survey came after the council identified the problem but before the council learned the cause and tested a solution. Placing the sentence after sentence 1 preserves that sequence.",
    tip: "Ask yourself: what had to happen first for the next sentence to make sense?",
  },
  {
    id: "rw-expr-023",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "hard",
    passage: "[UNDERLINED: Communities often have events and activities.] To encourage more residents to attend, the science center started offering free monthly engineering workshops. Each workshop invites families to build a small project, such as a paper bridge or a balloon-powered car. Attendance has grown steadily because visitors leave with both new knowledge and something they created themselves.",
    question: "Which choice most effectively replaces the underlined sentence and introduces the paragraph?",
    options: [
      "Free engineering workshops have helped the science center attract more community members.",
      "Many residents look for activities on weekends and school breaks.",
      "Science centers usually contain exhibits about several different subjects.",
      "Building a project by hand can require tools, materials, and patience.",
    ],
    correctAnswers: [0],
    explanation: "Choice A introduces both the specific program and its purpose, which the rest of the paragraph develops. The other options are either too broad or not clearly connected to the paragraph's focus.",
    tip: "The strongest topic sentence previews both the subject and the main claim about it.",
  },
  {
    id: "rw-expr-024",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "hard",
    passage: "An environmental club replaced several sections of lawn with native prairie plants. The students explained that the deeper roots of those plants help rainwater soak into the soil instead of running off quickly. Over time, the new planting required less mowing than the old grass. [UNDERLINED: Grass and flowers can grow in different kinds of soil.]",
    question: "Which choice best replaces the underlined sentence and concludes the paragraph?",
    options: [
      "The prairie project thus conserves maintenance effort while improving how the site handles rainfall.",
      "Native plants often bloom at different times during the year.",
      "Students spent several afternoons removing sections of old sod.",
      "Lawns can be found near schools, parks, and office buildings.",
    ],
    correctAnswers: [0],
    explanation: "Choice A combines the two major results described in the paragraph: easier maintenance and better rain absorption. The other choices either add minor details or make broad statements that do not conclude the paragraph effectively.",
    tip: "Good conclusions often combine the main benefits mentioned in the paragraph.",
  },
  {
    id: "rw-expr-025",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Organization",
    difficulty: "hard",
    passage: "[1] The photography club created an exhibit of nighttime sky images. [2] Members printed labels explaining shutter speed, exposure time, and light pollution. [UNDERLINED: Before opening the exhibit, the club tested different layouts to decide how visitors should move through the room.] [3] Guests later said the exhibit was easy to follow. [4] The club now hopes to share the display with a nearby middle school.",
    question: "Where should the underlined sentence be placed?",
    options: [
      "Before sentence 1",
      "After sentence 2",
      "After sentence 3",
      "After sentence 4",
    ],
    correctAnswers: [1],
    explanation: "The club would test the layout after creating the exhibit and labels but before visitors attended. Placing the sentence after sentence 2 preserves that timeline and sets up sentence 3 logically.",
    tip: "Use time clues like before opening to place sentences in chronological order.",
  },
  {
    id: "rw-expr-026",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "easy",
    passage: "The volunteers [UNDERLINED: made the decision to plant] native grasses along the creek bank after the first spring storm.",
    question: "Which choice most effectively replaces the underlined text?",
    options: [
      "made the decision to plant",
      "planted",
      "were planting in a manner that was careful",
      "had done a planting of",
    ],
    correctAnswers: [1],
    explanation: "Planted is the most concise and precise choice. It expresses the action directly without the unnecessary wording found in the other options.",
    tip: "On expression questions, prefer the clearest wording that says exactly what happened.",
  },
  {
    id: "rw-expr-027",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "easy",
    passage: "Because the club met in a small room, the editor asked each writer to keep comments [UNDERLINED: very short in length].",
    question: "Which choice most effectively replaces the underlined text?",
    options: [
      "very short in length",
      "brief",
      "not especially long overall",
      "short and concise in a brief way",
    ],
    correctAnswers: [1],
    explanation: "Brief conveys the same idea with one precise word, eliminating redundancy. The other choices are wordy or repetitive.",
    tip: "If one word expresses the idea clearly, it is often better than a long phrase.",
  },
  {
    id: "rw-expr-028",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "easy",
    passage: "The museum's new audio guide helps visitors [UNDERLINED: get a better understanding of] how conservators restore paintings.",
    question: "Which choice best replaces the underlined text?",
    options: [
      "get a better understanding of",
      "understand",
      "have understanding about",
      "gain, in a helpful way, knowledge regarding",
    ],
    correctAnswers: [1],
    explanation: "Understand is the clearest and most concise revision. The other options express the same idea less efficiently or awkwardly.",
    tip: "Watch for weak verb phrases like get an understanding of; a single strong verb is often better.",
  },
  {
    id: "rw-expr-029",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "easy",
    passage: "By noon, the runners were tired, [UNDERLINED: but despite that fact], they still finished the charity race.",
    question: "Which choice most effectively replaces the underlined text?",
    options: [
      "but despite that fact",
      "yet",
      "in spite of the fact that",
      "however on the other hand",
    ],
    correctAnswers: [1],
    explanation: "Yet expresses the contrast cleanly and idiomatically. The other choices are wordy or awkward in context.",
    tip: "Choose the transition that fits the relationship while using the fewest necessary words.",
  },
  {
    id: "rw-expr-030",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "easy",
    passage: "The engineer designed a [UNDERLINED: good] filter that removes tiny plastic particles from stormwater.",
    question: "Which choice best replaces the underlined word?",
    options: [
      "good",
      "effective",
      "nice",
      "interesting",
    ],
    correctAnswers: [1],
    explanation: "Effective is more precise than good because it identifies the filter's actual quality: it works well. Nice and interesting are too vague.",
    tip: "Replace vague adjectives with specific ones that show exactly why something is notable.",
  },
  {
    id: "rw-expr-031",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "easy",
    passage: "To prepare for the interview, Maya [UNDERLINED: read over] the scientist's recent article on wetlands.",
    question: "Which choice most effectively replaces the underlined text?",
    options: [
      "read over",
      "reviewed",
      "looked over in a careful manner",
      "went ahead and read through",
    ],
    correctAnswers: [1],
    explanation: "Reviewed is more precise and appropriately formal for an academic context. The other choices are less formal or unnecessarily wordy.",
    tip: "For formal writing, prefer specific, direct verbs over conversational phrases.",
  },
  {
    id: "rw-expr-032",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "easy",
    passage: "The principal praised the robotics team for its [UNDERLINED: new innovation] at the regional competition.",
    question: "Which choice best replaces the underlined text?",
    options: [
      "new innovation",
      "innovation",
      "innovative new innovation",
      "brand-new idea innovation",
    ],
    correctAnswers: [1],
    explanation: "Innovation already refers to something new, so adding new is redundant. Choice B expresses the idea cleanly.",
    tip: "Redundancy often appears when two nearby words mean nearly the same thing.",
  },
  {
    id: "rw-expr-033",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "easy",
    passage: "The article argues that city trees can [UNDERLINED: help out with] cooling neighborhoods during summer heat waves.",
    question: "Which choice most effectively replaces the underlined text?",
    options: [
      "help out with",
      "reduce",
      "do something for",
      "be useful regarding",
    ],
    correctAnswers: [1],
    explanation: "Reduce is more precise than help out with because it specifies exactly how trees affect neighborhood temperatures. The other choices are vague.",
    tip: "The best revision usually names the exact action instead of hinting at it.",
  },
  {
    id: "rw-expr-034",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "medium",
    passage: "The debate captain summarized the judge's feedback in a [UNDERLINED: way that was clear and easy to understand].",
    question: "Which choice best replaces the underlined text?",
    options: [
      "way that was clear and easy to understand",
      "clear, accessible way",
      "way that was understandable and not confusing",
      "manner that was clear in its clarity",
    ],
    correctAnswers: [1],
    explanation: "Clear, accessible way is concise and avoids the unnecessary repetition of easy to understand. The other choices are wordy or repetitive.",
    tip: "Trim away repeated ideas while keeping the sentence's meaning intact.",
  },
  {
    id: "rw-expr-035",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "medium",
    passage: "After comparing several sources, the historian found the diary entry especially [UNDERLINED: useful in a helpful way] for dating the event.",
    question: "Which choice best replaces the underlined text?",
    options: [
      "useful in a helpful way",
      "valuable",
      "helpful and useful",
      "something she could use helpfully",
    ],
    correctAnswers: [1],
    explanation: "Valuable is concise and precise. It captures why the diary entry mattered without the redundancy of the other options.",
    tip: "SAT revisions often reward precise vocabulary that replaces repetitive phrasing.",
  },
  {
    id: "rw-expr-036",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "medium",
    passage: "The speaker used humor [UNDERLINED: in order to] keep the audience engaged during the long presentation.",
    question: "Which choice most effectively replaces the underlined text?",
    options: [
      "in order to",
      "to",
      "for the purpose of",
      "so as to be able to",
    ],
    correctAnswers: [1],
    explanation: "To is the most concise way to express purpose here. The other options are unnecessarily long.",
    tip: "When a shorter infinitive works, choose it over a longer purpose phrase.",
  },
  {
    id: "rw-expr-037",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "medium",
    passage: "The student described the fossil as [UNDERLINED: cool], a word that sounded too informal for the lab report.",
    question: "Which choice best replaces the underlined word?",
    options: [
      "cool",
      "remarkable",
      "neat",
      "awesome",
    ],
    correctAnswers: [1],
    explanation: "Remarkable is appropriately formal and specific for a lab report. The other options are conversational and not suited to the context.",
    tip: "Match your wording to the level of formality in the passage.",
  },
  {
    id: "rw-expr-038",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "medium",
    passage: "The guide pointed out that the canyon walls had been [UNDERLINED: shaped and formed] by water over thousands of years.",
    question: "Which choice most effectively replaces the underlined text?",
    options: [
      "shaped and formed",
      "shaped",
      "formed in a way that shaped them",
      "made and created",
    ],
    correctAnswers: [1],
    explanation: "Shaped alone conveys the idea completely. The original phrase is redundant because shaped and formed mean nearly the same thing in this context.",
    tip: "If two nearby verbs repeat the same idea, one usually needs to go.",
  },
  {
    id: "rw-expr-039",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "medium",
    passage: "The principal said the new schedule would [UNDERLINED: have a positive effect on] student attendance.",
    question: "Which choice best replaces the underlined text?",
    options: [
      "have a positive effect on",
      "improve",
      "be good for in a positive way",
      "make more positive for",
    ],
    correctAnswers: [1],
    explanation: "Improve expresses the idea more directly and concisely than have a positive effect on. The other options are awkward or repetitive.",
    tip: "Prefer strong verbs over long noun phrases when revising for concision.",
  },
  {
    id: "rw-expr-040",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "medium",
    passage: "The article's conclusion [UNDERLINED: says] that restoring oyster reefs can protect shorelines from erosion.",
    question: "Which choice best replaces the underlined word?",
    options: [
      "says",
      "asserts",
      "talks about",
      "puts forth the idea in words",
    ],
    correctAnswers: [1],
    explanation: "Asserts is more precise and formal than says in an academic context. The other options are vague or awkward.",
    tip: "On formal SAT passages, precise academic verbs often improve weak everyday ones.",
  },
  {
    id: "rw-expr-041",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "medium",
    passage: "The team continued testing the prototype [UNDERLINED: until the time when] the battery finally held a full charge.",
    question: "Which choice most effectively replaces the underlined text?",
    options: [
      "until the time when",
      "until",
      "up to the point in time that",
      "during the period before",
    ],
    correctAnswers: [1],
    explanation: "Until is the cleanest and most concise expression. The other options use more words without adding meaning.",
    tip: "If several words can be replaced by one without changing meaning, make the cut.",
  },
  {
    id: "rw-expr-042",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "medium",
    passage: "The editor chose a [UNDERLINED: big] headline to emphasize the article about the school election.",
    question: "Which choice best replaces the underlined word?",
    options: [
      "big",
      "bold",
      "nice",
      "loud",
    ],
    correctAnswers: [1],
    explanation: "Bold is more precise because it describes the visual style of a headline. Big is vague, and the other options do not fit the context well.",
    tip: "Ask which word gives the reader the most exact picture of what is meant.",
  },
  {
    id: "rw-expr-043",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "medium",
    passage: "The ecologist explained that lichens are [UNDERLINED: able to survive in places where conditions are harsh].",
    question: "Which choice most effectively replaces the underlined text?",
    options: [
      "able to survive in places where conditions are harsh",
      "adapted to harsh conditions",
      "the kind of organisms that can survive when it is difficult",
      "survivors in harsh kinds of places",
    ],
    correctAnswers: [1],
    explanation: "Adapted to harsh conditions is concise and scientifically precise. The other options are longer or less exact.",
    tip: "Scientific writing often favors precise terms over conversational explanations.",
  },
  {
    id: "rw-expr-044",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "hard",
    passage: "The poet's revised line was [UNDERLINED: more better] because it used fewer words and a stronger image.",
    question: "Which choice best replaces the underlined text?",
    options: [
      "more better",
      "better",
      "more improved",
      "best in a better way",
    ],
    correctAnswers: [1],
    explanation: "Better is the correct and concise comparative form. More better is grammatically incorrect and redundant.",
    tip: "Watch for double comparatives such as more better or most fastest.",
  },
  {
    id: "rw-expr-045",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "hard",
    passage: "To show how quickly the glacier was melting, the writer included a [UNDERLINED: lot of] yearly measurements.",
    question: "Which choice best replaces the underlined text?",
    options: [
      "lot of",
      "series of",
      "bunch of",
      "big amount of",
    ],
    correctAnswers: [1],
    explanation: "Series of is more precise and formal than lot of. It also better matches the idea of measurements collected over time.",
    tip: "Informal phrases like a lot of often have more precise formal replacements.",
  },
  {
    id: "rw-expr-046",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "hard",
    passage: "The volunteers repaired the trail [UNDERLINED: each and every] Saturday morning in October.",
    question: "Which choice most effectively replaces the underlined text?",
    options: [
      "each and every",
      "each",
      "every single one of the",
      "all of the different",
    ],
    correctAnswers: [1],
    explanation: "Each conveys the idea clearly by itself. The other options are repetitive or awkward.",
    tip: "Avoid doubled emphasis when one word already expresses the meaning.",
  },
  {
    id: "rw-expr-047",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "hard",
    passage: "The article describes how satellite images can [UNDERLINED: give scientists the ability to track] wildfires in near real time.",
    question: "Which choice best replaces the underlined text?",
    options: [
      "give scientists the ability to track",
      "help scientists track",
      "allow for scientists tracking",
      "make scientists able for tracking",
    ],
    correctAnswers: [1],
    explanation: "Help scientists track is concise and idiomatic. The other choices are wordier or ungrammatical.",
    tip: "Prefer direct verb structures to longer noun-heavy phrases.",
  },
  {
    id: "rw-expr-048",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "hard",
    passage: "During rehearsal, the conductor asked the brass section to play with a more [UNDERLINED: nice] tone.",
    question: "Which choice best replaces the underlined word?",
    options: [
      "nice",
      "resonant",
      "good",
      "pleasantly okay",
    ],
    correctAnswers: [1],
    explanation: "Resonant is a precise musical term that conveys the desired quality of sound. The other options are too vague or awkward.",
    tip: "Look for the option that uses domain-specific language appropriately and clearly.",
  },
  {
    id: "rw-expr-049",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "hard",
    passage: "The report notes that the river's path [UNDERLINED: changed over the course of time] after the dam was removed.",
    question: "Which choice most effectively replaces the underlined text?",
    options: [
      "changed over the course of time",
      "shifted over time",
      "underwent changes during the passage of time",
      "was changing in the fullness of time",
    ],
    correctAnswers: [1],
    explanation: "Shifted over time is concise and precise. The other options are longer without being clearer.",
    tip: "When two options mean the same thing, choose the one with the clearest and fewest words.",
  },
  {
    id: "rw-expr-050",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Effective Language",
    difficulty: "hard",
    passage: "The student newspaper printed the correction [UNDERLINED: in a place where readers could easily notice it].",
    question: "Which choice best replaces the underlined text?",
    options: [
      "in a place where readers could easily notice it",
      "prominently",
      "in an easy-to-see spot where it was noticeable",
      "where it would be likely to be seen by readers",
    ],
    correctAnswers: [1],
    explanation: "Prominently expresses the idea in one precise word. The other choices are unnecessarily wordy.",
    tip: "An adverb can often replace a bulky descriptive phrase.",
  },
  {
    id: "rw-expr-051",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "easy",
    passage: "A student is writing a paragraph arguing that community gardens can strengthen neighborhood connections. [UNDERLINED: The writer wants to add a sentence here.]",
    question: "Which choice most effectively uses evidence to support the paragraph's claim?",
    options: [
      "Residents often swap seeds and gardening advice during the garden's weekly volunteer sessions.",
      "Tomatoes, peppers, and herbs are among the crops commonly grown in community gardens.",
      "Many gardens use raised beds because they can improve drainage.",
      "Some cities require permits before a vacant lot can be converted into a garden.",
    ],
    correctAnswers: [0],
    explanation: "Choice A directly supports the claim because it shows neighbors interacting with one another. The other choices provide background information about gardens but do not specifically show stronger community connections.",
    tip: "For development questions, pick the detail that proves the exact claim, not just the general topic.",
  },
  {
    id: "rw-expr-052",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "easy",
    passage: "A writer claims that adding bilingual exhibit labels can make museums more accessible to families. [UNDERLINED: The writer wants to add a supporting sentence here.]",
    question: "Which choice best develops the writer's claim?",
    options: [
      "Parents reported that they could discuss the exhibits more easily when both they and their children could read the labels comfortably.",
      "The labels were printed on durable material that resists smudging and fading.",
      "Museum visitors often spend extra time in galleries that display popular artifacts.",
      "Curators usually decide where labels should be mounted and how large they should be.",
    ],
    correctAnswers: [0],
    explanation: "Choice A shows exactly how bilingual labels improve access for families: they make shared understanding easier. The other choices are tangential or procedural rather than supportive of the claim.",
    tip: "The best supporting detail usually shows a real effect, not a neutral fact.",
  },
  {
    id: "rw-expr-053",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "easy",
    passage: "A paragraph argues that school podcasts can broaden who gets heard on campus. [UNDERLINED: The writer wants to add evidence here.]",
    question: "Which choice best supports the paragraph's point?",
    options: [
      "Recent episodes have featured students from the robotics team, the choir, and the newcomer club, groups that rarely appear in school announcements.",
      "The podcast is recorded with a USB microphone and edited with free software.",
      "Many schools use announcements, posters, and newsletters to share information.",
      "Podcast episodes are usually shorter than most class periods.",
    ],
    correctAnswers: [0],
    explanation: "Choice A supports the claim by showing that the podcast includes voices from a wide range of groups. The other choices do not address whose perspectives are being shared.",
    tip: "If the claim is about scope or representation, look for evidence showing a wider range of people or examples.",
  },
  {
    id: "rw-expr-054",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "easy",
    passage: "A student argues that rain gardens can reduce street flooding after storms. [UNDERLINED: The writer wants to add a sentence that supports this claim.]",
    question: "Which choice most effectively develops the argument?",
    options: [
      "Because rain gardens contain deep-rooted plants and loose soil, they can absorb runoff that would otherwise rush into storm drains.",
      "Rain gardens often include flowers that bloom at different times of year.",
      "Many neighborhoods add decorative stones or signs near rain gardens.",
      "Some storms arrive with little warning during the spring and summer months.",
    ],
    correctAnswers: [0],
    explanation: "Choice A provides a clear mechanism showing how rain gardens reduce flooding. The other options mention related topics but do not explain or support the claim directly.",
    tip: "Evidence is strongest when it explains why or how the claim is true.",
  },
  {
    id: "rw-expr-055",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "easy",
    passage: "A paragraph contends that digitizing jazz records helps preserve musical history. [UNDERLINED: The writer wants to add a supporting detail here.]",
    question: "Which choice best supports the paragraph's claim?",
    options: [
      "Once a fragile recording has been digitized, researchers can study the performance without repeatedly handling the original disc.",
      "Some jazz ensembles feature trumpets, pianos, and saxophones.",
      "Record sleeves sometimes include liner notes and black-and-white photographs.",
      "Archivists typically store old records in climate-controlled rooms.",
    ],
    correctAnswers: [0],
    explanation: "Choice A directly shows how digitization preserves history: it protects the original artifact while making the music available for study. The other choices provide context but do not support the claim as effectively.",
    tip: "Ask which option most clearly answers Why does this matter?",
  },
  {
    id: "rw-expr-056",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "easy",
    passage: "A writer wants to show that Saturday matinees can make theater performances more accessible. [UNDERLINED: The writer wants to add evidence here.]",
    question: "Which choice best develops that idea?",
    options: [
      "Families said the earlier start time made it possible to attend a play without keeping younger children out late on school nights.",
      "Actors sometimes perform more than one show on the same weekend.",
      "The theater prints programs that list the cast and summarize the plot.",
      "Some audience members prefer to sit near the stage, while others prefer the balcony.",
    ],
    correctAnswers: [0],
    explanation: "Choice A explains exactly how matinees improve access. The other options do not connect clearly to the idea of accessibility.",
    tip: "Support for a claim about access should show how a barrier was removed.",
  },
  {
    id: "rw-expr-057",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "easy",
    passage: "A student claims that pollinator gardens can serve as outdoor classrooms. [UNDERLINED: The writer wants to add a sentence here.]",
    question: "Which choice best supports the student's claim?",
    options: [
      "Biology classes use the garden to observe insect behavior, sketch flower structures, and compare which plants attract the most bees.",
      "The garden includes purple coneflowers, milkweed, and black-eyed Susans.",
      "Pollinator gardens can be planted in schoolyards, parks, and backyards.",
      "Some flowers in the garden bloom earlier than others.",
    ],
    correctAnswers: [0],
    explanation: "Choice A directly shows the garden being used for instruction, which supports the claim that it functions as an outdoor classroom. The other choices merely describe the garden.",
    tip: "When a claim is about educational value, look for evidence of actual learning activities.",
  },
  {
    id: "rw-expr-058",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "medium",
    passage: "A writer argues that bird-safe window film can help protect migrating birds. [UNDERLINED: The writer wants to add a supporting detail here.]",
    question: "Which choice most effectively develops the argument?",
    options: [
      "After the patterned film was installed, volunteers counted far fewer collisions outside the building during migration season.",
      "Window film is available in several sizes, colors, and adhesives.",
      "Many office buildings are cleaned by maintenance crews after business hours.",
      "Some birds migrate in spring, and others migrate in autumn.",
    ],
    correctAnswers: [0],
    explanation: "Choice A offers concrete evidence that the film protects birds. The other options are related background details but do not show the film's effect.",
    tip: "On evidence questions, a measured result is often stronger than a general description.",
  },
  {
    id: "rw-expr-059",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "medium",
    passage: "A paragraph argues that electric buses can improve passengers' riding experience. [UNDERLINED: The writer wants to add evidence here.]",
    question: "Which choice best supports the paragraph's claim?",
    options: [
      "Passengers on the test routes reported that the buses' quieter engines made conversations and stop announcements easier to hear.",
      "Electric buses are often painted in the same colors as other buses in a city's fleet.",
      "Bus drivers must complete training before operating a new vehicle model.",
      "Transit agencies usually publish route maps and schedules online.",
    ],
    correctAnswers: [0],
    explanation: "Choice A directly supports the claim because it identifies a specific improvement passengers experienced. The other choices do not address ride quality.",
    tip: "If the claim concerns riders, the best support usually includes riders' experiences or outcomes.",
  },
  {
    id: "rw-expr-060",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "medium",
    passage: "A student wants to support the claim that coding mentorship programs can increase students' confidence. [UNDERLINED: The writer wants to add a sentence here.]",
    question: "Which choice best develops the claim?",
    options: [
      "After several meetings with professional programmers, participants said they felt more comfortable asking technical questions and presenting their own projects.",
      "The mentors worked at companies that build websites, games, and medical software.",
      "Most sessions lasted about an hour and took place after school.",
      "Students in the program used laptops provided by the computer lab.",
    ],
    correctAnswers: [0],
    explanation: "Choice A is the only option that directly shows increased confidence. The other details may be true but do not prove the claim.",
    tip: "Match the evidence to the exact quality in the claim—here, confidence.",
  },
  {
    id: "rw-expr-061",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "medium",
    passage: "A writer claims that rainwater collection systems can reduce greenhouse water use. [UNDERLINED: The writer wants to add evidence to support this claim.]",
    question: "Which choice best supports the claim?",
    options: [
      "Club members tracked irrigation for a month and found that stored rainwater supplied nearly one-third of the water the greenhouse needed.",
      "The collection barrels were painted green to match the greenhouse doors.",
      "Greenhouses often contain fans, benches, hoses, and trays.",
      "It can take several weeks for seedlings to outgrow their trays.",
    ],
    correctAnswers: [0],
    explanation: "Choice A provides numerical evidence showing that the system reduced water use. The other choices are irrelevant to the claim.",
    tip: "Statistics are useful support when they directly measure the result the claim describes.",
  },
  {
    id: "rw-expr-062",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "medium",
    passage: "A student argues that oral-history projects can benefit local museums. [UNDERLINED: The writer wants to add a supporting detail here.]",
    question: "Which choice most effectively develops the student's point?",
    options: [
      "Recorded interviews give museums first-person accounts that can be used in exhibits and digital archives.",
      "Many museums also collect tools, photographs, and household objects.",
      "Interviewers often bring notebooks, microphones, and consent forms.",
      "Some residents can recall events from many decades ago.",
    ],
    correctAnswers: [0],
    explanation: "Choice A explains how oral histories help museums by supplying material for exhibits and archives. The other options are related but less directly supportive.",
    tip: "The strongest detail often shows how something can be used, not just what it is.",
  },
  {
    id: "rw-expr-063",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "medium",
    passage: "A writer wants to support the idea that student-run websites can improve club communication. [UNDERLINED: The writer wants to add a sentence here.]",
    question: "Which choice best develops that idea?",
    options: [
      "New members can check one page for meeting times, competition deadlines, and shared notes instead of searching through multiple messages.",
      "The website uses the school's colors in its banner and navigation menu.",
      "Several students helped design the site's homepage during lunch.",
      "Different clubs choose different names for their websites and pages.",
    ],
    correctAnswers: [0],
    explanation: "Choice A shows specifically how the website improves communication by centralizing information. The other options are cosmetic or general details.",
    tip: "For claims about efficiency, look for evidence that saves time or reduces confusion.",
  },
  {
    id: "rw-expr-064",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "medium",
    passage: "A paragraph argues that science-center workshops can increase family engagement. [UNDERLINED: The writer wants to add evidence here.]",
    question: "Which choice best supports the argument?",
    options: [
      "Staff members observed that adults and children at the workshops usually built projects together and continued discussing them after the session ended.",
      "The workshops use inexpensive materials such as paper, tape, and craft sticks.",
      "Families often visit museums and science centers during weekends and holidays.",
      "Some workshops are led by volunteers, while others are led by teachers.",
    ],
    correctAnswers: [0],
    explanation: "Choice A demonstrates family engagement by describing active participation and continued discussion. The other options do not directly show engagement.",
    tip: "Support for a claim about engagement should show interaction, not just attendance.",
  },
  {
    id: "rw-expr-065",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "medium",
    passage: "A student wants to support the claim that native prairie plants can reduce maintenance needs. [UNDERLINED: The writer wants to add a detail here.]",
    question: "Which choice best develops the claim?",
    options: [
      "After the prairie section became established, groundskeepers no longer needed to mow that area every week.",
      "Prairie plants can include tall grasses and flowers with deep roots.",
      "Students researched which species once grew naturally in the region.",
      "The planting took place on a sunny side of the school grounds.",
    ],
    correctAnswers: [0],
    explanation: "Choice A directly supports the claim because it shows a reduction in maintenance. The other choices are background details rather than evidence.",
    tip: "If the claim is about reduced work, choose the option that shows less work being required.",
  },
  {
    id: "rw-expr-066",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "medium",
    passage: "A writer argues that comparing poem translations can deepen students' understanding of literature. [UNDERLINED: The writer wants to add evidence here.]",
    question: "Which choice most effectively develops the writer's point?",
    options: [
      "When students compared two versions of the same image, they noticed how one translator emphasized sound while another emphasized meaning.",
      "Poems are often arranged in lines and stanzas.",
      "Some translators work from languages that use different alphabets.",
      "Literature classes sometimes include novels, plays, and essays as well.",
    ],
    correctAnswers: [0],
    explanation: "Choice A shows students gaining a deeper understanding by analyzing how translation choices affect interpretation. The other choices do not support that claim directly.",
    tip: "Look for evidence that demonstrates the kind of understanding the claim names.",
  },
  {
    id: "rw-expr-067",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "medium",
    passage: "A paragraph claims that astronomy nights can spark community interest in science. [UNDERLINED: The writer wants to add a sentence here.]",
    question: "Which choice best supports the paragraph's claim?",
    options: [
      "After viewing Jupiter through the telescope, several families stayed to ask club members questions about planets and future observing events.",
      "Telescopes can vary in size, lens type, and magnification power.",
      "The astronomy club posted flyers around town a week before the event.",
      "Cloud cover can make it difficult to observe the sky on some nights.",
    ],
    correctAnswers: [0],
    explanation: "Choice A shows the event generating curiosity and sustained interest in science. The other options provide context but do not support the claim as directly.",
    tip: "Evidence for a claim about interest should show curiosity, follow-up, or continued participation.",
  },
  {
    id: "rw-expr-068",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "hard",
    passage: "A writer wants to support the claim that cleanup projects can produce useful environmental data. [UNDERLINED: The writer wants to add a supporting sentence here.]",
    question: "Which choice best develops the claim?",
    options: [
      "By sorting the litter they collected, volunteers identified which kinds of plastic were most common along the riverbank.",
      "The volunteers worked in teams of three and wore bright gloves.",
      "Rivers often carry water from smaller streams and creeks.",
      "The cleanup lasted about three hours on a Saturday morning.",
    ],
    correctAnswers: [0],
    explanation: "Choice A supports the claim because it shows the cleanup producing information that can be analyzed. The other options describe the event without demonstrating data collection.",
    tip: "Data-focused claims need evidence that includes measuring, sorting, counting, or recording.",
  },
  {
    id: "rw-expr-069",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "hard",
    passage: "A student argues that accessible museum design can encourage independent exploration. [UNDERLINED: The writer wants to add evidence here.]",
    question: "Which choice best supports that claim?",
    options: [
      "Visitors with low vision said the tactile maps let them plan their routes without having to wait for staff assistance.",
      "Museums sometimes offer guided tours led by trained docents.",
      "The new maps were printed in durable material and mounted near the entrance.",
      "Some exhibits include replicas that visitors can touch with permission.",
    ],
    correctAnswers: [0],
    explanation: "Choice A directly supports the idea of independent exploration by showing visitors navigating on their own. The other choices do not address independence as clearly.",
    tip: "If the claim names independence, choose the evidence that shows people acting without extra help.",
  },
  {
    id: "rw-expr-070",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "hard",
    passage: "A writer claims that student surveys can help leaders design better policies. [UNDERLINED: The writer wants to add a supporting sentence here.]",
    question: "Which choice most effectively develops the claim?",
    options: [
      "The council used survey responses about phone alerts to decide that a phone-free study hour would address the biggest source of distraction.",
      "Surveys can be distributed on paper or through online forms.",
      "Students were asked several questions about noise, lighting, and seating.",
      "Many policies are revised after schools collect feedback from different groups.",
    ],
    correctAnswers: [0],
    explanation: "Choice A shows the survey data guiding a specific policy decision, which directly supports the claim. The other options are more general or descriptive.",
    tip: "The best evidence often links a piece of information to the decision it influenced.",
  },
  {
    id: "rw-expr-071",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "hard",
    passage: "A paragraph argues that oyster reefs can protect coastlines. [UNDERLINED: The writer wants to add evidence here.]",
    question: "Which choice best supports the paragraph's argument?",
    options: [
      "Researchers found that waves lost energy after passing over restored reef sections, reducing erosion on the shore behind them.",
      "Oysters attach themselves to hard surfaces and can form clusters.",
      "Many coastal communities depend on fishing and tourism.",
      "Marine biologists often study reefs from small boats.",
    ],
    correctAnswers: [0],
    explanation: "Choice A offers direct scientific evidence that reefs protect shorelines. The other options provide background but not proof of the argument.",
    tip: "For scientific claims, the strongest support often includes an observed effect or experimental result.",
  },
  {
    id: "rw-expr-072",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "hard",
    passage: "A student wants to support the idea that makerspaces can expand what libraries offer. [UNDERLINED: The writer wants to add a detail here.]",
    question: "Which choice best develops that idea?",
    options: [
      "Because the makerspace includes tools for sewing, recording, and 3D printing, patrons can create projects there instead of only borrowing materials.",
      "Libraries often arrange books by genre, author, or subject.",
      "Several patrons signed up for the makerspace orientation on opening day.",
      "Staff members wrote safety rules for each machine in the room.",
    ],
    correctAnswers: [0],
    explanation: "Choice A explains exactly how the makerspace broadens the library's role. The other choices are related but less directly supportive of the claim.",
    tip: "When a claim is about expansion, choose the evidence that shows a new function or capability.",
  },
  {
    id: "rw-expr-073",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "hard",
    passage: "A writer argues that solar canopies can make school parking lots more useful. [UNDERLINED: The writer wants to add evidence here.]",
    question: "Which choice best supports the argument?",
    options: [
      "The canopies generate electricity while also shading parked cars, so the same space serves two purposes at once.",
      "Solar panels are usually angled to capture as much sunlight as possible.",
      "Parking lots can become especially hot during summer afternoons.",
      "Many schools look for ways to reduce their energy costs over time.",
    ],
    correctAnswers: [0],
    explanation: "Choice A most directly supports the idea that the lot becomes more useful because it provides both energy generation and shade. The other options are related but do not make that point as clearly.",
    tip: "If the claim is about usefulness, the best support shows multiple practical benefits.",
  },
  {
    id: "rw-expr-074",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "hard",
    passage: "A paragraph claims that preserving old train stations can benefit downtown areas. [UNDERLINED: The writer wants to add a supporting sentence here.]",
    question: "Which choice best develops the claim?",
    options: [
      "After the station was restored, nearby businesses reported more weekend visitors who came to see the historic building and shop in the area.",
      "Train stations were often built with brick walls, large clocks, and waiting rooms.",
      "Several workers repaired the station's roof and windows during the project.",
      "Some towns no longer use trains for passenger service.",
    ],
    correctAnswers: [0],
    explanation: "Choice A connects the restoration to a concrete downtown benefit: increased visitor activity. The other options do not support the claim as directly.",
    tip: "Choose the detail that shows a real-world impact, not just a description of the project.",
  },
  {
    id: "rw-expr-075",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Development",
    difficulty: "hard",
    passage: "A writer wants to support the idea that comparing prototype designs helps students learn engineering. [UNDERLINED: The writer wants to add evidence here.]",
    question: "Which choice most effectively develops that idea?",
    options: [
      "By timing how quickly different solar ovens heated apple slices, the class could connect each design change to a measurable result.",
      "The students built their ovens from cardboard boxes, foil, and dark paper.",
      "Engineering classes sometimes ask students to work in small groups.",
      "The apples used in the test were cut into equal slices before class.",
    ],
    correctAnswers: [0],
    explanation: "Choice A shows students learning engineering by testing designs and analyzing results. The other options provide context but do not demonstrate that learning process.",
    tip: "For claims about learning, look for evidence of comparison, analysis, or reflection.",
  },
  {
    id: "rw-expr-076",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "easy",
    passage: "The library's makerspace contains advanced tools such as 3D printers. [UNDERLINED: As a result,] staff members begin every orientation by reviewing safety rules.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "As a result,",
      "For example,",
      "Meanwhile,",
      "Instead,",
    ],
    correctAnswers: [0],
    explanation: "As a result correctly signals cause and effect: because the room contains advanced tools, staff members begin by reviewing safety rules.",
    tip: "Match the transition to the relationship between the two ideas: cause and effect, contrast, example, or continuation.",
  },
  {
    id: "rw-expr-077",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "easy",
    passage: "The first podcast episode featured only student council announcements. [UNDERLINED: However,] later episodes included interviews, music reviews, and short stories.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "For example,",
      "However,",
      "Similarly,",
      "Therefore,",
    ],
    correctAnswers: [1],
    explanation: "However signals the contrast between the podcast's limited first episode and its broader later episodes. The other transitions do not express that shift.",
    tip: "If the second sentence shifts away from the first, a contrast transition is often best.",
  },
  {
    id: "rw-expr-078",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "easy",
    passage: "The theater added Saturday matinees for families. [UNDERLINED: Consequently,] attendance among younger audience members increased within a month.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "Consequently,",
      "In contrast,",
      "For instance,",
      "Nevertheless,",
    ],
    correctAnswers: [0],
    explanation: "Consequently correctly indicates that increased attendance was the result of adding matinees. The other transitions signal the wrong relationship.",
    tip: "When sentence two is a result of sentence one, choose a cause-and-effect transition.",
  },
  {
    id: "rw-expr-079",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "easy",
    passage: "The science center's workshops are free to attend. [UNDERLINED: In addition,] families leave each session with a project they built together.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "In addition,",
      "Instead,",
      "For example,",
      "On the contrary,",
    ],
    correctAnswers: [0],
    explanation: "In addition shows that the second sentence adds another benefit of the workshops. The other choices suggest a different relationship.",
    tip: "Use additive transitions when the second sentence gives another related point, not a result or contrast.",
  },
  {
    id: "rw-expr-080",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "easy",
    passage: "Volunteers initially worried that native prairie plants would look untidy. [UNDERLINED: Yet,] once the flowers bloomed, many neighbors praised the new landscape.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "For example,",
      "Yet,",
      "Likewise,",
      "As a result,",
    ],
    correctAnswers: [1],
    explanation: "Yet signals a clear contrast between the volunteers' concern and the later positive reaction from neighbors.",
    tip: "Contrast transitions work when expectation and outcome differ.",
  },
  {
    id: "rw-expr-081",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "easy",
    passage: "The astronomy club practiced aligning the telescope several times before the event. [UNDERLINED: Therefore,] guests spent less time waiting while members adjusted the equipment.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "Meanwhile,",
      "For instance,",
      "Therefore,",
      "Similarly,",
    ],
    correctAnswers: [2],
    explanation: "Therefore shows that the short wait times were the result of the club's preparation. The other options do not express that cause-and-effect relationship.",
    tip: "If preparation leads to a benefit, choose a transition showing result.",
  },
  {
    id: "rw-expr-082",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "easy",
    passage: "A city replaced several ordinary windows with bird-safe glass. [UNDERLINED: For example,] one building recorded far fewer collisions during migration season.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "For example,",
      "Nevertheless,",
      "Otherwise,",
      "Instead,",
    ],
    correctAnswers: [0],
    explanation: "For example correctly introduces a specific instance that illustrates the broader statement in the first sentence.",
    tip: "Use example transitions when the second sentence provides one specific case of the first.",
  },
  {
    id: "rw-expr-083",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "easy",
    passage: "The greenhouse now collects rainwater from its roof. [UNDERLINED: As a result,] the gardening club buys less water for summer irrigation.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "As a result,",
      "On the other hand,",
      "For instance,",
      "Likewise,",
    ],
    correctAnswers: [0],
    explanation: "As a result is correct because the second sentence describes the outcome of installing the collection system.",
    tip: "Identify whether sentence two answers the question What happened because of sentence one?",
  },
  {
    id: "rw-expr-084",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "medium",
    passage: "The museum's tactile maps help visitors navigate independently. [UNDERLINED: In fact,] some guests said they no longer needed to wait for staff directions at the entrance.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "In fact,",
      "By contrast,",
      "Instead,",
      "Meanwhile,",
    ],
    correctAnswers: [0],
    explanation: "In fact appropriately emphasizes the supporting detail in the second sentence. The other transitions suggest contrast or a change in topic.",
    tip: "An emphasis transition works when sentence two reinforces or intensifies the first.",
  },
  {
    id: "rw-expr-085",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "medium",
    passage: "The river cleanup removed hundreds of plastic bottles from the shoreline. [UNDERLINED: More important,] volunteers also sorted the litter so scientists could study it.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "More important,",
      "For example,",
      "Still,",
      "Otherwise,",
    ],
    correctAnswers: [0],
    explanation: "More important signals that the second point adds an even more significant benefit of the cleanup. The other choices do not capture that hierarchy.",
    tip: "Choose a transition that fits not just the relationship but also the writer's emphasis.",
  },
  {
    id: "rw-expr-086",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "medium",
    passage: "The debate team website organizes deadlines in one place. [UNDERLINED: In addition,] it stores sample cases that members can review before tournaments.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "In addition,",
      "Instead,",
      "Consequently,",
      "Nevertheless,",
    ],
    correctAnswers: [0],
    explanation: "In addition correctly shows that the second sentence presents another way the website is useful. The other transitions imply contrast or causation that is not present.",
    tip: "Additive transitions link two parallel benefits or points.",
  },
  {
    id: "rw-expr-087",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "medium",
    passage: "The class expected its first solar-oven design to work well. [UNDERLINED: However,] heat escaped through several loose seams.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "Therefore,",
      "For instance,",
      "However,",
      "Similarly,",
    ],
    correctAnswers: [2],
    explanation: "However correctly marks the contrast between the class's expectation and the disappointing result.",
    tip: "A contrast transition is best when the second sentence undermines or complicates the first.",
  },
  {
    id: "rw-expr-088",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "medium",
    passage: "The oral-history project collected dozens of interviews. [UNDERLINED: Next,] students edited the recordings and uploaded them to the museum's archive.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "Next,",
      "By contrast,",
      "For example,",
      "As a result,",
    ],
    correctAnswers: [0],
    explanation: "Next is correct because the paragraph describes a sequence of steps, and editing/uploading happened after collecting the interviews.",
    tip: "Sequence transitions are especially useful when a paragraph describes a process.",
  },
  {
    id: "rw-expr-089",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "medium",
    passage: "The electric buses are quieter than the older diesel buses. [UNDERLINED: Because of this,] passengers can hear stop announcements more clearly.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "Because of this,",
      "Instead,",
      "For example,",
      "Similarly,",
    ],
    correctAnswers: [0],
    explanation: "Because of this correctly signals that clearer announcements result from quieter buses.",
    tip: "If the second sentence names an effect, pick a transition that points back to the cause.",
  },
  {
    id: "rw-expr-090",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "medium",
    passage: "A rain garden can absorb stormwater runoff. [UNDERLINED: For instance,] one school reported fewer puddles near its parking lot after installing one.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "For instance,",
      "Nevertheless,",
      "Meanwhile,",
      "In contrast,",
    ],
    correctAnswers: [0],
    explanation: "For instance introduces a specific example of the general claim in the first sentence.",
    tip: "Specific evidence often follows example transitions like for instance or for example.",
  },
  {
    id: "rw-expr-091",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "medium",
    passage: "The first translation of the poem preserved the original rhyme. [UNDERLINED: By contrast,] the second prioritized the poem's imagery.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "By contrast,",
      "As a result,",
      "For example,",
      "Next,",
    ],
    correctAnswers: [0],
    explanation: "By contrast correctly signals the difference between the two translations' priorities.",
    tip: "When two things are being compared, use a transition that highlights their difference.",
  },
  {
    id: "rw-expr-092",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "medium",
    passage: "The restored train station now houses a small local-history exhibit. [UNDERLINED: In this way,] the building serves current visitors while preserving the town's past.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "In this way,",
      "Meanwhile,",
      "For example,",
      "Instead,",
    ],
    correctAnswers: [0],
    explanation: "In this way appropriately shows that the second sentence explains the significance of the detail in the first sentence.",
    tip: "Some transitions help explain significance rather than just add or contrast details.",
  },
  {
    id: "rw-expr-093",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "medium",
    passage: "The cafeteria separated food scraps from other trash. [UNDERLINED: Eventually,] those scraps became compost for the campus gardens.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "Eventually,",
      "Otherwise,",
      "For example,",
      "Likewise,",
    ],
    correctAnswers: [0],
    explanation: "Eventually is correct because composting takes time; the second sentence describes what happened later.",
    tip: "Time-based transitions help clarify when an outcome happens.",
  },
  {
    id: "rw-expr-094",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "hard",
    passage: "Many residents worried that removing part of the lawn would look messy. [UNDERLINED: Instead,] the mature prairie plants created a colorful and orderly border.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "Instead,",
      "For example,",
      "Consequently,",
      "Likewise,",
    ],
    correctAnswers: [0],
    explanation: "Instead shows that the actual result differed from what residents expected.",
    tip: "Instead often works when the second sentence replaces an expected outcome with a different one.",
  },
  {
    id: "rw-expr-095",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "hard",
    passage: "The article describes several ways city trees improve neighborhoods. [UNDERLINED: Specifically,] it notes that shaded sidewalks can remain several degrees cooler in summer.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "Specifically,",
      "Nevertheless,",
      "Afterward,",
      "Otherwise,",
    ],
    correctAnswers: [0],
    explanation: "Specifically correctly introduces a particular detail from a broader claim about trees' benefits.",
    tip: "Use a narrowing transition when the second sentence zooms in on one detail from a general statement.",
  },
  {
    id: "rw-expr-096",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "hard",
    passage: "The robotics team wanted its design notebook to be easier for judges to follow. [UNDERLINED: To achieve this goal,] the team added headings, labels, and short summaries to each section.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "To achieve this goal,",
      "By contrast,",
      "For example,",
      "Meanwhile,",
    ],
    correctAnswers: [0],
    explanation: "To achieve this goal clearly links the revision strategy in the second sentence to the goal stated in the first.",
    tip: "Purpose transitions are useful when sentence two explains the action taken to meet a goal.",
  },
  {
    id: "rw-expr-097",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "hard",
    passage: "The museum's bilingual labels improved family conversations in the gallery. [UNDERLINED: Likewise,] they helped tour guides answer visitors' questions more efficiently.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "Likewise,",
      "However,",
      "For instance,",
      "As a result,",
    ],
    correctAnswers: [0],
    explanation: "Likewise is appropriate because the second sentence adds a similar benefit of the labels. The other choices suggest a different relationship.",
    tip: "When two sentences present parallel benefits, use a parallel transition.",
  },
  {
    id: "rw-expr-098",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "hard",
    passage: "The coding mentors did not simply explain solutions to students. [UNDERLINED: Instead,] they asked questions that led students to debug their own programs.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "Instead,",
      "For example,",
      "Consequently,",
      "Meanwhile,",
    ],
    correctAnswers: [0],
    explanation: "Instead correctly contrasts what the mentors did not do with what they actually did.",
    tip: "Use instead when the second sentence offers an alternative to the first.",
  },
  {
    id: "rw-expr-099",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "hard",
    passage: "The photography club wanted visitors to move smoothly through the exhibit. [UNDERLINED: Therefore,] members tested several layouts before opening night.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "Therefore,",
      "For example,",
      "Similarly,",
      "Otherwise,",
    ],
    correctAnswers: [0],
    explanation: "Therefore shows that testing layouts was the logical response to the club's goal. The other transitions do not fit the relationship between the ideas.",
    tip: "If the second sentence is an action taken because of the first, choose a result transition.",
  },
  {
    id: "rw-expr-100",
    section: "reading-writing",
    domain: "expression-of-ideas",
    subdomain: "Transitions",
    difficulty: "hard",
    passage: "The makerspace orientation is only thirty minutes long. [UNDERLINED: Even so,] it covers safety, scheduling, and tool basics.",
    question: "Which choice best replaces the underlined transition?",
    options: [
      "Even so,",
      "For instance,",
      "As a result,",
      "Likewise,",
    ],
    correctAnswers: [0],
    explanation: "Even so signals that although the orientation is short, it still covers a lot of material. That contrast makes sense in context.",
    tip: "Use a concession transition when the second sentence is surprising given the first.",
  },
];
