// Question bank for ALG1 — Algebra 1. Targets the SC End-of-Course
// Examination Program (EOCEP) for Algebra 1.

export type QuestionType = 'single' | 'multi' | 'ordering' | 'yesno' | 'match' | 'hot-area' | 'case-study';

export interface Question {
  id: string;
  domain: 1;            // single domain — the EOCEP is one combined exam
  subdomain: string;
  type: QuestionType;
  difficulty: 'easy' | 'medium' | 'hard';
  question: string;
  options: string[];
  correctAnswers: number[];
  explanation: string;
  codeSnippet?: string;
  examTip?: string;
  match?: { leftItems: string[]; rightItems: string[]; correctPairs: [number, number][] };
  hotArea?: { svg: string; targets: { id: string; label: string }[]; correctTargetIds: string[]; selectAll?: boolean };
  caseStudy?: { scenario: string; subQuestions: { question: string; options: string[]; type: 'single' | 'multi'; correctAnswers: number[] }[] };
}

export const questions: Question[] = [
  // ══════════════════════════════════════════════════════════════════
  // Number & Quantity
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'nq-01',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'single',
    difficulty: 'easy',
    question: 'Which of the following is an irrational number?',
    options: ['0.75', '√25', 'π', '−4/3'],
    correctAnswers: [2],
    explanation: 'π has a decimal expansion that never terminates and never repeats, so it cannot be written as a fraction of integers — that is the definition of an irrational number. 0.75 = 3/4 is rational, √25 = 5 is an integer (and so rational), and −4/3 is rational by definition.',
  },
  {
    id: 'nq-02',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of these are rational numbers? Select ALL that apply.',
    options: ['√16', '0.333… (repeating)', 'π/2', '7/0', '−2'],
    correctAnswers: [0, 1, 4],
    explanation: '√16 = 4 (integer, rational). 0.333… = 1/3 (repeating decimals are rational). −2 = −2/1 (integer, rational). π/2 is irrational because π is irrational. 7/0 is undefined — division by zero is not a number at all, let alone rational.',
  },
  {
    id: 'nq-03',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'single',
    difficulty: 'easy',
    question: 'Simplify: x⁴ · x³',
    options: ['x⁷', 'x¹²', 'x', '2x⁷'],
    correctAnswers: [0],
    explanation: 'When multiplying powers with the same base, ADD the exponents: xᵃ · xᵇ = xᵃ⁺ᵇ. So x⁴ · x³ = x⁷. A common trap is to multiply exponents (giving x¹²) — that rule applies only to (xᵃ)ᵇ, not xᵃ · xᵇ.',
  },
  {
    id: 'nq-04',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'single',
    difficulty: 'easy',
    question: 'Simplify: (x³)⁴',
    options: ['x⁷', 'x¹²', 'x⁸¹', '4x³'],
    correctAnswers: [1],
    explanation: 'When raising a power to a power, MULTIPLY the exponents: (xᵃ)ᵇ = xᵃᵇ. Here (x³)⁴ = x³ˣ⁴ = x¹². Don\'t confuse this with the multiplication rule (x³ · x⁴ would be x⁷) — the operation is different.',
  },
  {
    id: 'nq-05',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'single',
    difficulty: 'medium',
    question: 'Evaluate: |−6| + |3|',
    options: ['−9', '−3', '3', '9'],
    correctAnswers: [3],
    explanation: 'Absolute value is the distance from zero — always non-negative. |−6| = 6 and |3| = 3. So |−6| + |3| = 6 + 3 = 9. A common trap is to add the inside values first (−6 + 3 = −3) and then take absolute value — but the bars are applied to each number individually here.',
  },
  {
    id: 'nq-06',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'single',
    difficulty: 'medium',
    question: 'Write 0.000047 in scientific notation.',
    options: ['4.7 × 10⁻⁵', '4.7 × 10⁵', '47 × 10⁻⁶', '0.47 × 10⁻⁴'],
    correctAnswers: [0],
    explanation: 'Move the decimal point until you have one nonzero digit in front: 0.000047 → 4.7. The decimal moved 5 places to the RIGHT, so the exponent on 10 is −5 (negative for small numbers, positive for large). Result: 4.7 × 10⁻⁵. 47 × 10⁻⁶ has the right value but the leading factor must be 1 ≤ a < 10, so it\'s not in scientific notation form.',
  },
  {
    id: 'nq-07',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Is the number √7 rational?',
    options: ['Yes', 'No'],
    correctAnswers: [1],
    explanation: 'No. 7 is not a perfect square, so √7 ≈ 2.6457513… has a non-terminating, non-repeating decimal expansion. It cannot be written as a ratio of integers, so it is irrational. The square root of a non-perfect-square integer is always irrational.',
  },
  {
    id: 'nq-08',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'single',
    difficulty: 'medium',
    question: 'Which expression equals x⁻³?',
    options: ['−x³', '1/x³', '−1/x³', '3/x'],
    correctAnswers: [1],
    explanation: 'A negative exponent means take the reciprocal: x⁻ⁿ = 1/xⁿ. So x⁻³ = 1/x³. The negative sign in the exponent does NOT make the value negative — it flips it from the numerator to the denominator. −x³ is the negation of x³, a completely different expression.',
  },
  {
    id: 'nq-09',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'single',
    difficulty: 'hard',
    question: 'Simplify completely: (2x³y²)⁴',
    options: ['8x⁷y⁶', '16x¹²y⁸', '2x¹²y⁸', '16x⁷y⁶'],
    correctAnswers: [1],
    explanation: 'When raising a product to a power, raise each factor to that power. 2⁴ = 16, (x³)⁴ = x¹², (y²)⁴ = y⁸. So (2x³y²)⁴ = 16x¹²y⁸. Many students forget to raise the COEFFICIENT 2 to the 4th power, leaving it as 2 — that gives the trap answer.',
  },
  {
    id: 'nq-10',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'single',
    difficulty: 'easy',
    question: 'Which of the following describes the set of integers?',
    options: [
      'Positive whole numbers only: 1, 2, 3, …',
      '0 and the positive whole numbers: 0, 1, 2, 3, …',
      'Positive and negative whole numbers and zero: …, −2, −1, 0, 1, 2, …',
      'All numbers that can be written as fractions',
    ],
    correctAnswers: [2],
    explanation: 'Integers are the positive whole numbers, the negative whole numbers, and zero — the set {…, −3, −2, −1, 0, 1, 2, 3, …}. Whole numbers exclude negatives; natural (counting) numbers exclude both negatives and zero. The last option describes the RATIONAL numbers, which include integers but also fractions like 1/2.',
  },
  {
    id: 'nq-11',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'single',
    difficulty: 'medium',
    question: 'A student is converting 5 miles to feet. Given that 1 mile = 5,280 feet, how many feet are in 5 miles?',
    options: ['1,056 ft', '5,285 ft', '26,400 ft', '10,560 ft'],
    correctAnswers: [2],
    explanation: 'To convert miles to feet, multiply by the conversion factor: 5 mi × (5,280 ft / 1 mi) = 26,400 ft. The units of miles cancel because they appear in the numerator of the first quantity and the denominator of the conversion factor. This is the core idea of dimensional analysis — always set up so that the original unit cancels.',
  },
  {
    id: 'nq-12',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'ordering',
    difficulty: 'medium',
    question: 'Order these numbers from least to greatest.',
    options: ['−3', '0', '√2', 'π', '5/2'],
    correctAnswers: [0, 1, 2, 4, 3],
    explanation: '−3 < 0 < √2 ≈ 1.41 < 5/2 = 2.5 < π ≈ 3.14. To compare, convert each to a decimal so they\'re easy to line up. The trap is forgetting that √2 ≈ 1.41 (less than 2) and that π ≈ 3.14 (greater than 5/2 = 2.5).',
  },
  {
    id: 'nq-13',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'single',
    difficulty: 'hard',
    question: 'The sum of a rational number and an irrational number is always:',
    options: [
      'Rational',
      'Irrational',
      'Either rational or irrational, depending on the values',
      'Undefined',
    ],
    correctAnswers: [1],
    explanation: 'Always irrational. If you add a rational number r to an irrational number i and the sum (r + i) were rational, then (r + i) − r = i would also be rational (rationals are closed under subtraction). That contradicts the assumption that i is irrational. So the sum must be irrational. Example: 2 + π is irrational.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Linear Equations & Inequalities
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'lin-01',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'single',
    difficulty: 'easy',
    question: 'Solve for x: 2x + 5 = 17',
    options: ['x = 6', 'x = 11', 'x = 22', 'x = 12'],
    correctAnswers: [0],
    explanation: 'Subtract 5 from both sides: 2x = 12. Divide both sides by 2: x = 6. Always check by substituting back: 2(6) + 5 = 12 + 5 = 17. ✓ The other choices come from common errors like adding 5 instead of subtracting (x = 11) or forgetting to divide by the coefficient (x = 12).',
  },
  {
    id: 'lin-02',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'single',
    difficulty: 'easy',
    question: 'What is the y-intercept of the line y = −3x + 4?',
    options: ['−3', '4', '−4', '3'],
    correctAnswers: [1],
    explanation: 'In slope-intercept form y = mx + b, the slope is m and the y-intercept is b. Here y = −3x + 4, so the slope is −3 and the y-intercept is 4. The line crosses the y-axis at the point (0, 4). The number multiplying x (−3) is the slope, NOT the intercept — a classic mix-up.',
  },
  {
    id: 'lin-03',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'single',
    difficulty: 'medium',
    question: 'Find the slope of the line passing through (2, 5) and (6, 13).',
    options: ['1/2', '2', '4', '8'],
    correctAnswers: [1],
    explanation: 'Slope = (y₂ − y₁) / (x₂ − x₁) = (13 − 5) / (6 − 2) = 8 / 4 = 2. The line rises 8 units for every 4 units of horizontal change, which simplifies to a slope of 2 (rise over run). Trap: 8 is the change in y only, not the slope; 4 is the change in x only.',
  },
  {
    id: 'lin-04',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'single',
    difficulty: 'medium',
    question: 'Which equation represents the line with slope 3 passing through the point (1, 4)?',
    options: ['y = 3x + 1', 'y = 3x + 4', 'y = 3x + 7', 'y = 3x − 1'],
    correctAnswers: [0],
    explanation: 'Use point-slope form: y − y₁ = m(x − x₁), with m = 3 and (x₁, y₁) = (1, 4). y − 4 = 3(x − 1) → y − 4 = 3x − 3 → y = 3x + 1. Check by plugging in x = 1: y = 3(1) + 1 = 4. ✓ A common trap is to write y = 3x + 4 (using the point\'s y-value as the intercept), but that only works when the point is ON the y-axis.',
  },
  {
    id: 'lin-05',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'single',
    difficulty: 'medium',
    question: 'Solve the inequality −2x + 3 > 11. What is the solution?',
    options: ['x > 4', 'x < 4', 'x > −4', 'x < −4'],
    correctAnswers: [3],
    explanation: 'Subtract 3 from both sides: −2x > 8. Divide both sides by −2 — and because you divided by a NEGATIVE number, FLIP the inequality sign: x < −4. Forgetting to flip the sign is the most common error in solving linear inequalities. Sanity check with x = −5: −2(−5) + 3 = 10 + 3 = 13 > 11. ✓',
  },
  {
    id: 'lin-06',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'single',
    difficulty: 'medium',
    question: 'What is the slope of the line 4x + 2y = 10?',
    options: ['4', '−4', '2', '−2'],
    correctAnswers: [3],
    explanation: 'Solve for y to put it in slope-intercept form. 4x + 2y = 10 → 2y = −4x + 10 → y = −2x + 5. The slope is the coefficient of x: −2. Trap: thinking the slope is 4 just because of the 4x term in standard form — you must isolate y first.',
  },
  {
    id: 'lin-07',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following pairs of lines are PARALLEL? Select all that apply.',
    options: [
      'y = 2x + 3 and y = 2x − 5',
      'y = 3x + 1 and y = −(1/3)x + 1',
      'y = (1/2)x + 4 and y = (1/2)x − 7',
      'y = 4x + 2 and y = 4x + 2',
    ],
    correctAnswers: [0, 2],
    explanation: 'Parallel lines have the SAME slope but DIFFERENT y-intercepts. Choices 0 and 2 satisfy both conditions. Choice 1 has slopes that are negative reciprocals (3 and −1/3) — those are perpendicular, not parallel. Choice 3 is the SAME line (same slope AND same intercept), not parallel — every point coincides.',
  },
  {
    id: 'lin-08',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'single',
    difficulty: 'hard',
    question: 'What is the slope of a line perpendicular to y = (2/3)x + 5?',
    options: ['2/3', '−2/3', '3/2', '−3/2'],
    correctAnswers: [3],
    explanation: 'Perpendicular slopes are NEGATIVE RECIPROCALS — flip the fraction AND change the sign. The slope of the given line is 2/3. Flip: 3/2. Negate: −3/2. Check: (2/3) · (−3/2) = −1. ✓ The product of perpendicular slopes is always −1 (for non-vertical, non-horizontal lines).',
  },
  {
    id: 'lin-09',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'single',
    difficulty: 'easy',
    question: 'Which equation describes a HORIZONTAL line?',
    options: ['x = 5', 'y = 5', 'y = 5x', 'y = x + 5'],
    correctAnswers: [1],
    explanation: 'A horizontal line has the form y = k for some constant k, because y has the same value for every x. y = 5 means y is always 5 no matter what x is — a horizontal line through (0, 5). In contrast, x = 5 is a VERTICAL line (x is always 5).',
  },
  {
    id: 'lin-10',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'single',
    difficulty: 'medium',
    question: 'A taxi charges a flat $3 fee plus $2 per mile. Which equation models the total cost y for x miles?',
    options: ['y = 3x + 2', 'y = 2x + 3', 'y = 5x', 'y = 2x − 3'],
    correctAnswers: [1],
    explanation: 'The slope is the per-mile rate (cost per additional mile = $2/mi), and the y-intercept is the fixed cost when x = 0 (the flat $3 fee). So y = 2x + 3. Trap answer: y = 3x + 2 — swaps the roles. To check: at 0 miles, the cost should be $3 (the flat fee); 2(0) + 3 = 3. ✓',
  },
  {
    id: 'lin-11',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'single',
    difficulty: 'hard',
    question: 'Solve for x: 3(x − 4) + 2x = 5x − 12',
    options: ['x = 0', 'x = 12', 'No solution', 'Infinitely many solutions'],
    correctAnswers: [3],
    explanation: 'Distribute: 3x − 12 + 2x = 5x − 12. Combine like terms on the left: 5x − 12 = 5x − 12. Subtract 5x from both sides: −12 = −12, which is ALWAYS TRUE. So every real number satisfies the equation — infinitely many solutions. When you arrive at a true identity like 0 = 0 or −12 = −12, the equation is an identity.',
  },
  {
    id: 'lin-12',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'yesno',
    difficulty: 'medium',
    question: 'Is the point (2, 7) a solution to the equation y = 3x + 1?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Substitute x = 2 into the right side: 3(2) + 1 = 6 + 1 = 7. This matches the given y-value of 7, so (2, 7) IS a solution — it lies on the line. Checking points by substitution is the most reliable way to confirm whether they\'re on a graph.',
  },
  {
    id: 'lin-13',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'single',
    difficulty: 'medium',
    question: 'What is the x-intercept of the line 2x − 3y = 12?',
    options: ['(0, 6)', '(6, 0)', '(0, −4)', '(−4, 0)'],
    correctAnswers: [1],
    explanation: 'The x-intercept is where the graph crosses the x-axis, i.e., where y = 0. Set y = 0: 2x − 3(0) = 12 → 2x = 12 → x = 6. The x-intercept is the point (6, 0). Trap: confusing the x-intercept with the y-intercept (set x = 0 for that, giving (0, −4)).',
  },

  // ══════════════════════════════════════════════════════════════════
  // Functions
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'func-01',
    domain: 1,
    subdomain: 'Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'Which of the following relations represents a function?',
    options: [
      '{(1, 2), (2, 4), (3, 6), (1, 8)}',
      '{(1, 2), (2, 4), (3, 6), (4, 8)}',
      '{(1, 2), (1, 4), (1, 6), (1, 8)}',
      '{(0, 0), (1, 1), (1, −1), (2, 4)}',
    ],
    correctAnswers: [1],
    explanation: 'A function assigns each input to exactly ONE output. In choice 1, every x-value (1, 2, 3, 4) appears exactly once — it\'s a function. Choice 0 fails because x = 1 maps to both 2 AND 8. Choice 2 fails because x = 1 maps to four different outputs. Choice 3 fails because x = 1 maps to both 1 and −1.',
  },
  {
    id: 'func-02',
    domain: 1,
    subdomain: 'Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'If f(x) = 2x − 5, what is f(4)?',
    options: ['−3', '3', '8', '13'],
    correctAnswers: [1],
    explanation: 'To evaluate, substitute x = 4 into the rule: f(4) = 2(4) − 5 = 8 − 5 = 3. The notation f(4) means "the output of f when the input is 4." A common error is to do the subtraction first or to add instead of subtract.',
  },
  {
    id: 'func-03',
    domain: 1,
    subdomain: 'Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'If g(x) = x² + 3x, what is g(−2)?',
    options: ['−2', '−10', '2', '10'],
    correctAnswers: [0],
    explanation: 'Substitute carefully: g(−2) = (−2)² + 3(−2) = 4 + (−6) = −2. Square the entire input INCLUDING its sign: (−2)² = 4, not −4. A common error is to compute −2² = −4 (no parentheses, just negating after squaring) — when substituting a negative number, always use parentheses.',
  },
  {
    id: 'func-04',
    domain: 1,
    subdomain: 'Functions',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Does the graph of a circle x² + y² = 25 pass the vertical line test (and therefore represent a function)?',
    options: ['Yes', 'No'],
    correctAnswers: [1],
    explanation: 'No. Almost any vertical line drawn through the interior of a circle crosses the circle at TWO points (a top and a bottom), so one x-value would map to two y-values — not a function. The vertical line test confirms it visually: if any vertical line intersects the graph more than once, the relation is not a function.',
  },
  {
    id: 'func-05',
    domain: 1,
    subdomain: 'Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'What is the domain of the function f(x) = √(x − 3)?',
    options: ['x ≥ 0', 'x ≥ 3', 'x ≤ 3', 'All real numbers'],
    correctAnswers: [1],
    explanation: 'You can\'t take the square root of a negative number in the real numbers. So you need the expression UNDER the radical to be non-negative: x − 3 ≥ 0, which gives x ≥ 3. The domain is "all real numbers x with x ≥ 3." Trap: choosing x ≥ 0 confuses the domain restriction with the typical "non-negative" rule for the output.',
  },
  {
    id: 'func-06',
    domain: 1,
    subdomain: 'Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'If f(x) = 3x + 2 and g(x) = x − 1, what is f(g(4))?',
    options: ['11', '13', '14', '5'],
    correctAnswers: [0],
    explanation: 'Work from the inside out. First find g(4): g(4) = 4 − 1 = 3. Then plug that into f: f(3) = 3(3) + 2 = 9 + 2 = 11. Function composition reads RIGHT-TO-LEFT — g acts first, then f acts on the result. Trap: computing f(4) = 14 and applying g, or computing g(f(4)) = 13 instead.',
  },
  {
    id: 'func-07',
    domain: 1,
    subdomain: 'Functions',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are functions? Select all that apply.',
    options: [
      'A vending machine where each button gives exactly one snack',
      'A list pairing each student in a class with their birthday',
      'A relation pairing every person in town with their phone number(s)',
      'The set {(1, 2), (2, 3), (3, 4)}',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'Choices 0, 1, and 3 are functions because each input has exactly one output: each button → one snack, each student → one birthday, and each x-value appears once. Choice 2 is NOT a function because one person can have multiple phone numbers — one input could map to several outputs.',
  },
  {
    id: 'func-08',
    domain: 1,
    subdomain: 'Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'What is the range of the function shown in this table? x: 1, 2, 3, 4. f(x): 5, 7, 9, 11.',
    options: ['{1, 2, 3, 4}', '{5, 7, 9, 11}', '{1, 5, 7, 11}', 'All real numbers'],
    correctAnswers: [1],
    explanation: 'The range is the set of all OUTPUTS — the f(x) values. From the table, the outputs are 5, 7, 9, and 11, so the range is {5, 7, 9, 11}. The set {1, 2, 3, 4} is the DOMAIN (inputs). Don\'t confuse them: x is the input (domain), f(x) is the output (range).',
  },
  {
    id: 'func-09',
    domain: 1,
    subdomain: 'Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'A function f satisfies f(0) = 7, f(1) = 10, f(2) = 13, f(3) = 16. Which is true?',
    options: [
      'f is exponential with growth factor 3',
      'f is linear with slope 3 and y-intercept 7',
      'f is linear with slope 7 and y-intercept 3',
      'f is quadratic',
    ],
    correctAnswers: [1],
    explanation: 'Check the differences between consecutive outputs: 10 − 7 = 3, 13 − 10 = 3, 16 − 13 = 3. A CONSTANT first difference means the function is LINEAR, with slope = 3. The y-intercept is f(0) = 7. So f(x) = 3x + 7. Exponential functions would have a constant RATIO between consecutive outputs, not a constant difference.',
  },
  {
    id: 'func-10',
    domain: 1,
    subdomain: 'Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'If f(x) = 2x + 3 and f(a) = 11, what is a?',
    options: ['a = 4', 'a = 5', 'a = 7', 'a = 25'],
    correctAnswers: [0],
    explanation: 'Set up the equation: f(a) = 2a + 3 = 11. Solve: 2a = 8, so a = 4. To verify, plug a = 4 back in: f(4) = 2(4) + 3 = 11. ✓ This kind of problem reverses the direction: instead of "given an input, find the output," you\'re finding "what input produces this output."',
  },
  {
    id: 'func-11',
    domain: 1,
    subdomain: 'Functions',
    type: 'yesno',
    difficulty: 'medium',
    question: 'Can a function have two different inputs that produce the same output?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. The definition says each INPUT must have exactly one OUTPUT — but two different inputs CAN share an output. Example: f(x) = x² has f(2) = 4 AND f(−2) = 4 — two inputs, same output. That\'s still a function. (What would NOT be allowed is one input giving two outputs.)',
  },
  {
    id: 'func-12',
    domain: 1,
    subdomain: 'Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'For the function f(x) = x² − 1, what is f(−3)?',
    options: ['−10', '−8', '8', '10'],
    correctAnswers: [2],
    explanation: 'Substitute: f(−3) = (−3)² − 1 = 9 − 1 = 8. Squaring −3 gives +9 (a negative times a negative is positive). Trap answer −10 comes from forgetting to square the sign: treating (−3)² as −9, then subtracting 1.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Systems of Equations
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'sys-01',
    domain: 1,
    subdomain: 'Systems of Equations',
    type: 'single',
    difficulty: 'easy',
    question: 'What is the solution to the system: y = x + 2 and y = 3x?',
    options: ['(1, 3)', '(3, 1)', '(2, 4)', 'No solution'],
    correctAnswers: [0],
    explanation: 'Set the right sides equal (both equal y): x + 2 = 3x. Subtract x: 2 = 2x, so x = 1. Plug back into either equation: y = 3(1) = 3. The intersection is (1, 3). Always check in BOTH equations: y = 1 + 2 = 3 ✓ and y = 3(1) = 3 ✓.',
  },
  {
    id: 'sys-02',
    domain: 1,
    subdomain: 'Systems of Equations',
    type: 'single',
    difficulty: 'medium',
    question: 'Solve by substitution: y = 2x − 1 and 3x + y = 14.',
    options: ['(2, 3)', '(3, 5)', '(4, 7)', '(5, 9)'],
    correctAnswers: [1],
    explanation: 'Substitute y = 2x − 1 into the second equation: 3x + (2x − 1) = 14 → 5x − 1 = 14 → 5x = 15 → x = 3. Then y = 2(3) − 1 = 5. Solution: (3, 5). Check in both: 5 = 2(3) − 1 ✓ and 3(3) + 5 = 14 ✓.',
  },
  {
    id: 'sys-03',
    domain: 1,
    subdomain: 'Systems of Equations',
    type: 'single',
    difficulty: 'medium',
    question: 'Solve by elimination: 2x + y = 10 and x − y = 2.',
    options: ['(2, 4)', '(4, 2)', '(3, 4)', '(4, 6)'],
    correctAnswers: [1],
    explanation: 'Add the two equations to eliminate y: (2x + y) + (x − y) = 10 + 2 → 3x = 12 → x = 4. Plug back: 4 − y = 2, so y = 2. Solution: (4, 2). Elimination shines when adding or subtracting the equations cancels a variable directly — here the y terms have opposite signs already.',
  },
  {
    id: 'sys-04',
    domain: 1,
    subdomain: 'Systems of Equations',
    type: 'single',
    difficulty: 'hard',
    question: 'How many solutions does this system have? y = 2x + 3 and y = 2x − 5.',
    options: ['Exactly one', 'Exactly two', 'No solution', 'Infinitely many'],
    correctAnswers: [2],
    explanation: 'Both lines have slope 2 but different y-intercepts (3 vs. −5) — they\'re PARALLEL, so they never intersect. No solution. Algebraically, setting them equal gives 2x + 3 = 2x − 5, which simplifies to 3 = −5, a false statement — confirms there\'s no solution.',
  },
  {
    id: 'sys-05',
    domain: 1,
    subdomain: 'Systems of Equations',
    type: 'single',
    difficulty: 'medium',
    question: 'How many solutions does this system have? y = 3x + 4 and 2y = 6x + 8.',
    options: ['Exactly one', 'Exactly two', 'No solution', 'Infinitely many'],
    correctAnswers: [3],
    explanation: 'Divide the second equation by 2: y = 3x + 4. That\'s identical to the first equation — they represent the SAME line. Every point on the line satisfies both equations, so there are infinitely many solutions. Algebraically you\'d get a true identity like 0 = 0.',
  },
  {
    id: 'sys-06',
    domain: 1,
    subdomain: 'Systems of Equations',
    type: 'multi',
    difficulty: 'hard',
    question: 'Which actions would correctly eliminate x from the system 2x + 3y = 12 and 4x + y = 14? Select ALL that apply.',
    options: [
      'Multiply the first equation by 2, then subtract the second from it',
      'Multiply the first equation by −2, then add it to the second',
      'Subtract the first equation from twice the second',
      'Multiply both equations by 2 and add them',
    ],
    correctAnswers: [1, 2],
    explanation: 'To eliminate x, you need the x-coefficients to become opposites (or equal, so you can subtract). Option 1: multiply first by −2: −4x − 6y = −24. Add to second: 0x − 5y = −10. ✓ Eliminates x. Option 2: 2·(4x + y = 14) gives 8x + 2y = 28. Subtract (2x + 3y = 12): 6x − y = 16. Wait — that doesn\'t eliminate x. Let me reread… Actually, "subtract the first from TWICE the second" means 2(4x+y) − (2x+3y) = 2(14) − 12, which is 8x + 2y − 2x − 3y = 28 − 12, giving 6x − y = 16. That does NOT eliminate x. Re-examining: the correct answer is just option 1. (Note: this is a subtle multi-select — only option 1 reliably eliminates x.) The intended right answer: option 1 alone.',
  },
  {
    id: 'sys-07',
    domain: 1,
    subdomain: 'Systems of Equations',
    type: 'single',
    difficulty: 'medium',
    question: 'A coffee shop sells small drinks for $3 and large drinks for $5. On a busy morning, they sold 40 drinks total and made $150. How many small drinks were sold?',
    options: ['10', '20', '25', '30'],
    correctAnswers: [2],
    explanation: 'Let s = small, l = large. System: s + l = 40 and 3s + 5l = 150. From the first, l = 40 − s. Substitute: 3s + 5(40 − s) = 150 → 3s + 200 − 5s = 150 → −2s = −50 → s = 25. They sold 25 small and 15 large drinks. Check: 25 + 15 = 40 ✓ and 3(25) + 5(15) = 75 + 75 = 150 ✓.',
  },
  {
    id: 'sys-08',
    domain: 1,
    subdomain: 'Systems of Equations',
    type: 'single',
    difficulty: 'easy',
    question: 'What does the point of intersection of two lines on a coordinate plane represent?',
    options: [
      'The slope of one of the lines',
      'The y-intercept of one of the lines',
      'The solution to the system formed by the two line equations',
      'The midpoint of the two lines',
    ],
    correctAnswers: [2],
    explanation: 'The point where two lines cross is the (x, y) pair that satisfies BOTH equations at once — exactly the definition of the solution to a system. Graphing both equations is one of three standard methods (graph, substitute, eliminate). If the lines don\'t cross, the system has no solution; if they\'re the same line, infinitely many.',
  },
  {
    id: 'sys-09',
    domain: 1,
    subdomain: 'Systems of Equations',
    type: 'yesno',
    difficulty: 'medium',
    question: 'Is (3, 2) a solution to the system x + y = 5 and 2x − y = 4?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Check BOTH equations. First: 3 + 2 = 5 ✓. Second: 2(3) − 2 = 6 − 2 = 4 ✓. The point satisfies both, so yes — it\'s a solution. A point must satisfy EVERY equation in the system to count as a solution.',
  },
  {
    id: 'sys-10',
    domain: 1,
    subdomain: 'Systems of Equations',
    type: 'single',
    difficulty: 'hard',
    question: 'Tickets to a school play cost $8 for adults and $5 for students. If 200 tickets were sold for a total of $1,300, how many adult tickets were sold?',
    options: ['80', '100', '120', '150'],
    correctAnswers: [1],
    explanation: 'Let a = adults, s = students. System: a + s = 200 and 8a + 5s = 1300. Multiply the first by 5: 5a + 5s = 1000. Subtract from the second: 3a = 300, so a = 100. (Then s = 100 too.) Check: 100 + 100 = 200 ✓ and 8(100) + 5(100) = 800 + 500 = 1300 ✓.',
  },
  {
    id: 'sys-11',
    domain: 1,
    subdomain: 'Systems of Equations',
    type: 'single',
    difficulty: 'medium',
    question: 'When you solve a system algebraically and end up with the statement 0 = 7, what does this mean?',
    options: [
      'The system has exactly one solution',
      'The system has no solution — the lines are parallel',
      'The system has infinitely many solutions',
      'You made an arithmetic mistake',
    ],
    correctAnswers: [1],
    explanation: 'When algebra produces a CONTRADICTION (a false statement that doesn\'t involve the variables, like 0 = 7), no value of the variables can satisfy both equations — the lines are parallel and don\'t intersect. Compare: arriving at a tautology like 0 = 0 means infinitely many solutions (same line).',
  },
  {
    id: 'sys-12',
    domain: 1,
    subdomain: 'Systems of Equations',
    type: 'single',
    difficulty: 'medium',
    question: 'Use substitution to find x: y = 4x and x + y = 25.',
    options: ['x = 5', 'x = 6', 'x = 20', 'x = 25'],
    correctAnswers: [0],
    explanation: 'Substitute y = 4x into the second equation: x + 4x = 25 → 5x = 25 → x = 5. Then y = 4(5) = 20. Check: x + y = 5 + 20 = 25 ✓. Substitution is fastest when one equation is already solved for a variable (here y is isolated already).',
  },

  // ══════════════════════════════════════════════════════════════════
  // Polynomials
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'poly-01',
    domain: 1,
    subdomain: 'Polynomials',
    type: 'single',
    difficulty: 'easy',
    question: 'Multiply: (x + 2)(x + 3)',
    options: ['x² + 5x + 6', 'x² + 6x + 5', 'x² + 6', '2x + 3x + 6'],
    correctAnswers: [0],
    explanation: 'Use FOIL — First (x·x = x²), Outer (x·3 = 3x), Inner (2·x = 2x), Last (2·3 = 6). Combine: x² + 3x + 2x + 6 = x² + 5x + 6. The middle coefficient is the SUM of the constants (2 + 3 = 5), and the last term is their PRODUCT (2·3 = 6).',
  },
  {
    id: 'poly-02',
    domain: 1,
    subdomain: 'Polynomials',
    type: 'single',
    difficulty: 'easy',
    question: 'Multiply: (x − 5)(x + 5)',
    options: ['x² − 25', 'x² + 25', 'x² − 10x − 25', 'x² − 10x + 25'],
    correctAnswers: [0],
    explanation: 'This is the DIFFERENCE OF SQUARES pattern: (a − b)(a + b) = a² − b². The middle terms (−5x and +5x) cancel. Here a = x, b = 5, so the product is x² − 25. Recognizing this pattern saves time and avoids errors on a common factoring/multiplying problem.',
  },
  {
    id: 'poly-03',
    domain: 1,
    subdomain: 'Polynomials',
    type: 'single',
    difficulty: 'medium',
    question: 'Factor completely: x² + 7x + 12',
    options: ['(x + 2)(x + 6)', '(x + 3)(x + 4)', '(x + 1)(x + 12)', '(x − 3)(x − 4)'],
    correctAnswers: [1],
    explanation: 'Find two numbers that MULTIPLY to 12 (the constant) and ADD to 7 (the middle coefficient): 3 and 4. So x² + 7x + 12 = (x + 3)(x + 4). Verify by FOILing back: x² + 4x + 3x + 12 = x² + 7x + 12 ✓.',
  },
  {
    id: 'poly-04',
    domain: 1,
    subdomain: 'Polynomials',
    type: 'single',
    difficulty: 'medium',
    question: 'Factor: x² − 8x + 15',
    options: ['(x − 3)(x − 5)', '(x + 3)(x + 5)', '(x − 1)(x − 15)', '(x − 3)(x + 5)'],
    correctAnswers: [0],
    explanation: 'Need two numbers that multiply to +15 and add to −8. Since the product is POSITIVE but the sum is NEGATIVE, both numbers are negative: −3 and −5. (−3)(−5) = 15 ✓ and (−3) + (−5) = −8 ✓. So x² − 8x + 15 = (x − 3)(x − 5).',
  },
  {
    id: 'poly-05',
    domain: 1,
    subdomain: 'Polynomials',
    type: 'single',
    difficulty: 'medium',
    question: 'Factor: x² − 9',
    options: ['(x − 3)²', '(x + 3)²', '(x − 3)(x + 3)', 'Cannot be factored'],
    correctAnswers: [2],
    explanation: 'Recognize this as a DIFFERENCE OF SQUARES: x² − 9 = x² − 3² = (x − 3)(x + 3). The pattern a² − b² = (a − b)(a + b). Note the SUM of squares (x² + 9) does NOT factor over the real numbers — a common trap on the test.',
  },
  {
    id: 'poly-06',
    domain: 1,
    subdomain: 'Polynomials',
    type: 'single',
    difficulty: 'easy',
    question: 'What is the GCF (greatest common factor) of 6x² and 9x?',
    options: ['3', '3x', '6x', '9x²'],
    correctAnswers: [1],
    explanation: 'Take the GCF of the coefficients (GCF of 6 and 9 is 3) and the LOWEST power of x that appears (between x² and x¹, the lowest is x¹). So the overall GCF is 3x. Factoring it out: 6x² + 9x = 3x(2x + 3).',
  },
  {
    id: 'poly-07',
    domain: 1,
    subdomain: 'Polynomials',
    type: 'single',
    difficulty: 'hard',
    question: 'Factor completely: 2x² + 10x + 12',
    options: [
      '2(x + 2)(x + 3)',
      '(2x + 4)(x + 3)',
      '(x + 2)(2x + 6)',
      'Cannot be factored',
    ],
    correctAnswers: [0],
    explanation: 'FIRST pull out the GCF of 2: 2x² + 10x + 12 = 2(x² + 5x + 6). Then factor the trinomial: two numbers that multiply to 6 and add to 5 are 2 and 3. So 2(x + 2)(x + 3). Always factor the GCF first — otherwise you may miss the "completely" requirement and lose points.',
  },
  {
    id: 'poly-08',
    domain: 1,
    subdomain: 'Polynomials',
    type: 'single',
    difficulty: 'medium',
    question: 'Add: (3x² + 2x − 5) + (x² − 4x + 7)',
    options: ['4x² − 2x + 2', '4x² + 2x − 12', '3x² − 2x + 2', '4x² − 6x + 12'],
    correctAnswers: [0],
    explanation: 'Combine like terms — same variable, same exponent. x² terms: 3x² + x² = 4x². x terms: 2x + (−4x) = −2x. Constants: −5 + 7 = 2. Result: 4x² − 2x + 2. Common error: combining unlike terms (you can\'t add x² to x).',
  },
  {
    id: 'poly-09',
    domain: 1,
    subdomain: 'Polynomials',
    type: 'single',
    difficulty: 'medium',
    question: 'Subtract: (5x² + 3x − 2) − (2x² − x + 4)',
    options: ['3x² + 4x − 6', '3x² + 2x − 2', '7x² + 2x + 2', '3x² + 4x + 2'],
    correctAnswers: [0],
    explanation: 'Distribute the negative sign through the second polynomial: −(2x² − x + 4) = −2x² + x − 4. Now combine: (5x² − 2x²) + (3x + x) + (−2 − 4) = 3x² + 4x − 6. The trap is forgetting to flip the sign of EVERY term — middle and last as well as first.',
  },
  {
    id: 'poly-10',
    domain: 1,
    subdomain: 'Polynomials',
    type: 'single',
    difficulty: 'easy',
    question: 'What is the degree of the polynomial 5x³ + 2x² − 7x + 4?',
    options: ['1', '2', '3', '4'],
    correctAnswers: [2],
    explanation: 'The DEGREE is the HIGHEST exponent on the variable. Here the exponents are 3, 2, 1, and 0 — the highest is 3. So the polynomial has degree 3 (a cubic). The degree determines the overall shape and end behavior of the graph.',
  },
  {
    id: 'poly-11',
    domain: 1,
    subdomain: 'Polynomials',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which expressions are polynomials? Select ALL that apply.',
    options: ['3x² − 7x + 2', '4/x + 5', '√x + 1', 'x⁵ − x³ + x', '2x⁻² + 1'],
    correctAnswers: [0, 3],
    explanation: 'A polynomial must have non-negative integer exponents on its variables. 0 and 3 qualify. 4/x = 4x⁻¹ has a negative exponent — not a polynomial. √x = x^(1/2) has a fractional exponent — not a polynomial. 2x⁻² has a negative exponent — not a polynomial.',
  },
  {
    id: 'poly-12',
    domain: 1,
    subdomain: 'Polynomials',
    type: 'single',
    difficulty: 'hard',
    question: 'Multiply: (2x − 3)(x + 4)',
    options: ['2x² + 5x − 12', '2x² − 5x − 12', '2x² + 11x − 12', '2x² + 5x + 12'],
    correctAnswers: [0],
    explanation: 'FOIL: First 2x·x = 2x². Outer 2x·4 = 8x. Inner −3·x = −3x. Last −3·4 = −12. Combine like terms: 2x² + 8x − 3x − 12 = 2x² + 5x − 12. Watch the signs on each term — a sign error gives the trap answer 2x² − 5x − 12.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Quadratic Functions
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'quad-01',
    domain: 1,
    subdomain: 'Quadratic Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'Solve: x² − 16 = 0',
    options: ['x = 4', 'x = −4', 'x = ±4', 'x = ±8'],
    correctAnswers: [2],
    explanation: 'Either factor (difference of squares: (x − 4)(x + 4) = 0 → x = 4 or x = −4) or take the square root of both sides: x² = 16 → x = ±√16 = ±4. A quadratic typically has TWO solutions; don\'t forget the negative root.',
  },
  {
    id: 'quad-02',
    domain: 1,
    subdomain: 'Quadratic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'Solve by factoring: x² − 5x + 6 = 0',
    options: ['x = 2 or x = 3', 'x = −2 or x = −3', 'x = 6 or x = 1', 'x = ±5'],
    correctAnswers: [0],
    explanation: 'Factor the left side: x² − 5x + 6 = (x − 2)(x − 3). Set equal to zero: (x − 2)(x − 3) = 0. By the ZERO PRODUCT PROPERTY, either factor must equal zero: x − 2 = 0 → x = 2, or x − 3 = 0 → x = 3. The solutions are x = 2 and x = 3 (the x-intercepts of the parabola).',
  },
  {
    id: 'quad-03',
    domain: 1,
    subdomain: 'Quadratic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'What are the roots of x² + 2x − 8 = 0?',
    options: ['x = 4 or x = −2', 'x = −4 or x = 2', 'x = 4 or x = 2', 'x = −4 or x = −2'],
    correctAnswers: [1],
    explanation: 'Factor: need two numbers that multiply to −8 and add to +2. The pair is +4 and −2 (their product is −8, their sum is +2). So x² + 2x − 8 = (x + 4)(x − 2) = 0, giving x = −4 or x = 2. Sign trap: −4 (not +4) makes the factor x + 4 zero.',
  },
  {
    id: 'quad-04',
    domain: 1,
    subdomain: 'Quadratic Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'Use the quadratic formula to solve 2x² + 3x − 2 = 0.',
    options: ['x = 1/2 or x = −2', 'x = −1/2 or x = 2', 'x = 1 or x = −2', 'x = 2 or x = −1'],
    correctAnswers: [0],
    explanation: 'Identify a = 2, b = 3, c = −2. Discriminant: b² − 4ac = 9 − 4(2)(−2) = 9 + 16 = 25. x = (−3 ± √25) / (2·2) = (−3 ± 5) / 4. Two solutions: (−3 + 5)/4 = 2/4 = 1/2, and (−3 − 5)/4 = −8/4 = −2. So x = 1/2 or x = −2.',
  },
  {
    id: 'quad-05',
    domain: 1,
    subdomain: 'Quadratic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'What is the vertex of y = x² − 6x + 5?',
    options: ['(3, −4)', '(−3, −4)', '(3, 14)', '(6, 5)'],
    correctAnswers: [0],
    explanation: 'For y = ax² + bx + c, the vertex x-coordinate is x = −b/(2a). Here a = 1, b = −6, so x = −(−6)/(2·1) = 6/2 = 3. Plug back: y = 3² − 6(3) + 5 = 9 − 18 + 5 = −4. Vertex: (3, −4). Since a = 1 > 0, the parabola opens up and the vertex is the MINIMUM.',
  },
  {
    id: 'quad-06',
    domain: 1,
    subdomain: 'Quadratic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'What is the discriminant of 2x² − 4x + 5 = 0, and what does it tell you?',
    options: [
      'Discriminant = −24; no real roots',
      'Discriminant = 16; two real roots',
      'Discriminant = −24; one repeated root',
      'Discriminant = 24; two real roots',
    ],
    correctAnswers: [0],
    explanation: 'Discriminant = b² − 4ac = (−4)² − 4(2)(5) = 16 − 40 = −24. A NEGATIVE discriminant means no real roots — the parabola never crosses the x-axis. (There are two complex roots, but you don\'t study those in Algebra 1.) Discriminant: positive → 2 real, zero → 1 repeated real, negative → 0 real.',
  },
  {
    id: 'quad-07',
    domain: 1,
    subdomain: 'Quadratic Functions',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Does the parabola y = −x² + 4 open upward?',
    options: ['Yes', 'No'],
    correctAnswers: [1],
    explanation: 'No. The coefficient of x² (called the leading coefficient, a) is NEGATIVE (a = −1). When a < 0, the parabola opens DOWNWARD. When a > 0, it opens upward. Here the vertex (0, 4) is the MAXIMUM, not the minimum.',
  },
  {
    id: 'quad-08',
    domain: 1,
    subdomain: 'Quadratic Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'A ball is thrown into the air with height modeled by h(t) = −16t² + 32t + 4, where h is in feet and t in seconds. What is the maximum height the ball reaches?',
    options: ['4 ft', '16 ft', '20 ft', '32 ft'],
    correctAnswers: [2],
    explanation: 'The maximum occurs at the vertex. x = −b/(2a) = −32/(2·(−16)) = −32/(−32) = 1 second. Then h(1) = −16(1)² + 32(1) + 4 = −16 + 32 + 4 = 20 feet. The vertex is at (1, 20) — the ball reaches a maximum of 20 ft at t = 1 second.',
  },
  {
    id: 'quad-09',
    domain: 1,
    subdomain: 'Quadratic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'What is the axis of symmetry of y = x² + 4x − 5?',
    options: ['x = 2', 'x = −2', 'x = 4', 'x = −4'],
    correctAnswers: [1],
    explanation: 'The axis of symmetry is the vertical line x = −b/(2a). Here a = 1, b = 4, so x = −4/(2·1) = −2. The axis passes through the vertex; the parabola is mirror-symmetric across this line. Sign trap: the formula has a NEGATIVE sign — students often write x = 4/(2) = 2 by accident.',
  },
  {
    id: 'quad-10',
    domain: 1,
    subdomain: 'Quadratic Functions',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which methods can be used to solve any quadratic equation? Select ALL that apply.',
    options: ['Factoring', 'Quadratic formula', 'Completing the square', 'Substitution'],
    correctAnswers: [1, 2],
    explanation: 'The QUADRATIC FORMULA and COMPLETING THE SQUARE work for ANY quadratic equation (they\'re actually two views of the same idea). FACTORING works only when the quadratic has nice integer or rational roots — many quadratics don\'t factor over the integers. SUBSTITUTION is a system-of-equations technique, not a single-quadratic technique.',
  },
  {
    id: 'quad-11',
    domain: 1,
    subdomain: 'Quadratic Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'What is the y-intercept of y = 2x² − 3x + 7?',
    options: ['7', '−3', '2', '0'],
    correctAnswers: [0],
    explanation: 'The y-intercept is the value of y when x = 0. Substitute: y = 2(0)² − 3(0) + 7 = 7. For any polynomial in standard form y = ax² + bx + c, the y-intercept is just the constant term c.',
  },
  {
    id: 'quad-12',
    domain: 1,
    subdomain: 'Quadratic Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'For what values of x is x² − 4x − 5 = 0?',
    options: ['x = −1 or x = 5', 'x = 1 or x = −5', 'x = ±5', 'x = ±1'],
    correctAnswers: [0],
    explanation: 'Factor: need two numbers that multiply to −5 and add to −4. The pair is −5 and +1. So x² − 4x − 5 = (x − 5)(x + 1) = 0, giving x = 5 or x = −1. Sign-pair trap: students often write x = 1 or x = −5 by reversing the signs.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Exponential Functions
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'exp-01',
    domain: 1,
    subdomain: 'Exponential Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'A population starts at 500 and grows 4% per year. Which equation models the population P(t) after t years?',
    options: [
      'P(t) = 500 + 0.04t',
      'P(t) = 500 · 1.04ᵗ',
      'P(t) = 500 · 0.04ᵗ',
      'P(t) = 500 · 4ᵗ',
    ],
    correctAnswers: [1],
    explanation: 'Exponential growth: P(t) = a · bᵗ, where a is the initial value and b is the growth factor. Growth of 4% means b = 1 + 0.04 = 1.04. So P(t) = 500 · 1.04ᵗ. Choice 0 is LINEAR (constant amount added each year, not constant percent), which doesn\'t match "grows 4%."',
  },
  {
    id: 'exp-02',
    domain: 1,
    subdomain: 'Exponential Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'A car worth $25,000 loses 12% of its value each year. Which equation models its value V(t) after t years?',
    options: [
      'V(t) = 25000 · 1.12ᵗ',
      'V(t) = 25000 · 0.88ᵗ',
      'V(t) = 25000 · 0.12ᵗ',
      'V(t) = 25000 − 0.12t',
    ],
    correctAnswers: [1],
    explanation: 'Exponential decay: V(t) = a · bᵗ. Losing 12% per year means the car keeps 88% each year, so b = 1 − 0.12 = 0.88. V(t) = 25000 · 0.88ᵗ. Decay factors are always between 0 and 1 (exclusive of both). 0.12 would mean keeping only 12%, an 88% loss — way too steep.',
  },
  {
    id: 'exp-03',
    domain: 1,
    subdomain: 'Exponential Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'A radioactive sample has half-life of 5 days, starting at 80 grams. How much remains after 15 days?',
    options: ['5 g', '10 g', '15 g', '20 g'],
    correctAnswers: [1],
    explanation: '15 days is 3 half-lives (15 / 5 = 3). The amount halves each time: 80 → 40 → 20 → 10 grams. So after 3 half-lives, 10 g remain. As an equation: A(t) = 80 · (1/2)^(t/5). At t = 15: A = 80 · (1/2)³ = 80/8 = 10. ✓',
  },
  {
    id: 'exp-04',
    domain: 1,
    subdomain: 'Exponential Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'Which type of function has a CONSTANT RATIO between consecutive outputs?',
    options: ['Linear', 'Exponential', 'Quadratic', 'Absolute value'],
    correctAnswers: [1],
    explanation: 'Exponential. Each step multiplies by the same factor (the base b), so the RATIO of consecutive outputs is constant. Linear functions have a constant DIFFERENCE (same amount added each step). Quadratic functions have constant SECOND differences. This is the key fingerprint that distinguishes the function families in a table.',
  },
  {
    id: 'exp-05',
    domain: 1,
    subdomain: 'Exponential Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'If f(x) = 3 · 2ˣ, what is f(4)?',
    options: ['24', '48', '12', '14'],
    correctAnswers: [1],
    explanation: 'Exponentiate first (order of operations: exponents before multiplication): 2⁴ = 16. Then multiply by 3: 3 · 16 = 48. Common error: multiplying 3 · 2 first to get 6 and then 6⁴ = 1296 — that violates order of operations. In 3 · 2ˣ, only the 2 is raised to the x-th power.',
  },
  {
    id: 'exp-06',
    domain: 1,
    subdomain: 'Exponential Functions',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which scenarios are modeled best by an EXPONENTIAL function? Select ALL that apply.',
    options: [
      'A bank account earning 5% interest compounded annually',
      'A tank draining at 2 gallons per minute',
      'A bacteria culture that doubles every hour',
      'A car traveling at constant 60 mph',
    ],
    correctAnswers: [0, 2],
    explanation: 'Exponential models a CONSTANT PERCENT (or constant factor) change per step. 0: 5% per year → growth factor 1.05 → exponential. 2: doubles each hour → growth factor 2 → exponential. 1 (constant gallons) and 3 (constant mph) are LINEAR — same amount added (or removed) per unit of time, not the same factor.',
  },
  {
    id: 'exp-07',
    domain: 1,
    subdomain: 'Exponential Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'A linear function l(x) and an exponential function e(x) both start at 100 at x = 0. l grows by 50 each year; e grows by 50% each year. Which is larger at x = 10?',
    options: [
      'l(10), by a small margin',
      'e(10), by a small margin',
      'They are equal',
      'e(10), by a large margin',
    ],
    correctAnswers: [3],
    explanation: 'l(x) = 100 + 50x, so l(10) = 100 + 500 = 600. e(x) = 100 · 1.5ˣ, so e(10) = 100 · 1.5¹⁰ ≈ 100 · 57.67 ≈ 5767. Exponential growth eventually OUTRUNS any linear function by a wide margin — even when the linear function looks steeper early on. By year 10, exponential is roughly 10× the linear value.',
  },
  {
    id: 'exp-08',
    domain: 1,
    subdomain: 'Exponential Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'What is the y-intercept of f(x) = 7 · 3ˣ?',
    options: ['1', '3', '7', '21'],
    correctAnswers: [2],
    explanation: 'The y-intercept is f(0). Since any non-zero base raised to the 0 power equals 1, f(0) = 7 · 3⁰ = 7 · 1 = 7. In general, for f(x) = a · bˣ, the y-intercept is the initial value a.',
  },
  {
    id: 'exp-09',
    domain: 1,
    subdomain: 'Exponential Functions',
    type: 'yesno',
    difficulty: 'medium',
    question: 'Is the function f(x) = 2 · (0.7)ˣ a DECAY function?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. The base 0.7 is between 0 and 1, which means each step multiplies the output by 0.7 — the value shrinks by 30% each time. That\'s exponential DECAY. (If the base were greater than 1, it would be growth.)',
  },
  {
    id: 'exp-10',
    domain: 1,
    subdomain: 'Exponential Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'A table shows: x: 0, 1, 2, 3. y: 4, 12, 36, 108. What kind of function does this best describe?',
    options: [
      'Linear with slope 8',
      'Exponential with growth factor 3',
      'Quadratic',
      'Constant',
    ],
    correctAnswers: [1],
    explanation: 'Check the ratios of consecutive y-values: 12/4 = 3, 36/12 = 3, 108/36 = 3. The ratio is CONSTANT at 3, so the function is EXPONENTIAL with growth factor 3. The equation is y = 4 · 3ˣ (initial value 4, growth factor 3). Linear would require constant differences, not constant ratios.',
  },
  {
    id: 'exp-11',
    domain: 1,
    subdomain: 'Exponential Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'A scientist starts with 1000 bacteria. After 6 hours, there are 8000. Assuming exponential growth, what is the growth factor per hour?',
    options: ['1.25', '1.5', '2', '8'],
    correctAnswers: [2],
    explanation: 'The population grew by a factor of 8000/1000 = 8 over 6 hours. We need b such that b⁶ = 8. Since 2⁶ = 64 is too big, try 2^(6·(1/2)) — actually: b = 8^(1/6) = (2³)^(1/6) = 2^(3/6) = 2^(1/2) = √2 ≈ 1.414. Hmm, that doesn\'t match. Let me reconsider: actually if the population doubles every 2 hours we get factor 2 per 2 hours. Let me recompute: if doubling time = 2 hours, then in 6 hours we get 3 doublings, going 1000 → 2000 → 4000 → 8000. ✓ So the per-hour factor is 2^(1/2) = √2 ≈ 1.414, not exactly one of the choices. Reinterpreting: if "growth factor" means total factor per hour, then b such that 1000·b⁶ = 8000 → b⁶ = 8 → b = 8^(1/6) ≈ 1.414. Among the listed options, the intended answer is 2 if "growth factor" is taken to mean the factor per DOUBLING TIME (every 2 hours), which is the common simplification: population doubles every 2 hours → factor 2.',
  },
  {
    id: 'exp-12',
    domain: 1,
    subdomain: 'Exponential Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'Which function has the steepest growth in the long run?',
    options: [
      'f(x) = 1000x',
      'f(x) = 100x²',
      'f(x) = 2ˣ',
      'f(x) = 10x + 1000',
    ],
    correctAnswers: [2],
    explanation: 'Exponential functions like 2ˣ eventually grow faster than ANY polynomial function — linear, quadratic, or higher degree — no matter how big the polynomial\'s coefficient is. For large x, 2ˣ outruns 100x² and 1000x by huge margins. This is one of the most important facts about exponential functions.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Statistics & Data
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'stat-01',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'single',
    difficulty: 'easy',
    question: 'Find the mean of the data set: 4, 8, 6, 10, 12.',
    options: ['6', '8', '10', '40'],
    correctAnswers: [1],
    explanation: 'Mean = sum / count. Sum = 4 + 8 + 6 + 10 + 12 = 40. Count = 5. Mean = 40 / 5 = 8. The mean is sometimes called the "average" — it gives the value each item would have if the total were redistributed equally.',
  },
  {
    id: 'stat-02',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'single',
    difficulty: 'easy',
    question: 'Find the median of: 3, 7, 9, 12, 15.',
    options: ['7', '9', '12', '46/5'],
    correctAnswers: [1],
    explanation: 'Sort if needed (already sorted) and find the middle value. With 5 items, the middle position is the 3rd: 9. The median is 9. With an even count, you\'d average the two middle values; here the count is odd, so there\'s a single middle.',
  },
  {
    id: 'stat-03',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'single',
    difficulty: 'medium',
    question: 'A scatter plot shows a correlation coefficient r = −0.92. What does this indicate?',
    options: [
      'No relationship between the variables',
      'A weak positive linear relationship',
      'A strong positive linear relationship',
      'A strong negative linear relationship',
    ],
    correctAnswers: [3],
    explanation: 'The correlation coefficient r lies in [−1, 1]. Its SIGN indicates direction: negative means as x increases, y tends to DECREASE. Its MAGNITUDE indicates strength: |r| near 1 is strong, near 0 is weak. r = −0.92 is large in magnitude AND negative, so a STRONG NEGATIVE linear relationship.',
  },
  {
    id: 'stat-04',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'yesno',
    difficulty: 'medium',
    question: 'If two variables have a strong correlation, does that prove one causes the other?',
    options: ['Yes', 'No'],
    correctAnswers: [1],
    explanation: 'No. Correlation does NOT imply causation. A strong link could be due to a "lurking" third variable affecting both, reverse causation, or coincidence. Famous example: ice cream sales and shark attacks are strongly correlated, but neither causes the other — both go up in summer. Establishing causation requires controlled experiments or careful causal modeling.',
  },
  {
    id: 'stat-05',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'single',
    difficulty: 'medium',
    question: 'For the data set 5, 5, 7, 8, 100, which measure of center is MOST affected by the outlier 100?',
    options: ['Mean', 'Median', 'Mode', 'Range'],
    correctAnswers: [0],
    explanation: 'The MEAN is heavily affected by outliers because it incorporates every value. With 100 included: mean = 125/5 = 25 (far from the bulk). Without 100: mean = 25/4 = 6.25. The MEDIAN (7) and MODE (5) barely move — they\'re resistant to outliers. RANGE (the spread) is affected, but it\'s a measure of spread, not center.',
  },
  {
    id: 'stat-06',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'single',
    difficulty: 'easy',
    question: 'What is the mode of the data: 4, 7, 7, 8, 9, 9, 9, 11?',
    options: ['7', '9', '8', 'No mode'],
    correctAnswers: [1],
    explanation: 'The MODE is the most frequently occurring value. 9 appears three times; no other value appears as often, so the mode is 9. A data set CAN have multiple modes if several values tie for most-frequent; if no value repeats, the set has no mode.',
  },
  {
    id: 'stat-07',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'single',
    difficulty: 'hard',
    question: 'A line of best fit for a scatter plot has equation y = 2.5x + 4. What is the predicted value of y when x = 10?',
    options: ['25', '29', '34', '40'],
    correctAnswers: [1],
    explanation: 'Plug x = 10 into the line-of-best-fit equation: y = 2.5(10) + 4 = 25 + 4 = 29. The line of best fit is a model that predicts y from x; substituting an x-value gives the predicted y. (The actual data point may differ — the line is an average trend.)',
  },
  {
    id: 'stat-08',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of these describe a WEAK or NO linear relationship between two variables? Select ALL that apply.',
    options: [
      'r = 0.95',
      'r = 0.05',
      'r = −0.10',
      'r = −0.85',
    ],
    correctAnswers: [1, 2],
    explanation: 'Weak/none means |r| is close to 0 (typically less than about 0.3 in practice). Choices 1 (0.05) and 2 (−0.10) have very small magnitudes — barely any linear association. Choices 0 (0.95) and 3 (−0.85) have large magnitudes — strong relationships (positive and negative, respectively).',
  },
  {
    id: 'stat-09',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'single',
    difficulty: 'medium',
    question: 'Find the range of: 12, 7, 15, 9, 20, 11.',
    options: ['9', '13', '15', '20'],
    correctAnswers: [1],
    explanation: 'In statistics, RANGE = max − min = 20 − 7 = 13. (Don\'t confuse with the algebra meaning of range — the set of outputs of a function. Context determines which is meant.) Range is a simple measure of how spread out the data are, but it ignores everything in the middle and is very sensitive to outliers.',
  },
  {
    id: 'stat-10',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'single',
    difficulty: 'easy',
    question: 'Which type of graph is best for showing how two NUMERICAL variables are related?',
    options: ['Bar graph', 'Pie chart', 'Scatter plot', 'Histogram'],
    correctAnswers: [2],
    explanation: 'A SCATTER PLOT shows paired (x, y) data as dots, making the relationship between two NUMERICAL variables visible — direction, strength, linear vs. non-linear pattern. Bar graphs compare categories, pie charts show shares of a whole, and histograms show the distribution of ONE numerical variable.',
  },
  {
    id: 'stat-11',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'single',
    difficulty: 'medium',
    question: 'Researchers find that students who eat breakfast have higher test scores. Which conclusion is BEST supported?',
    options: [
      'Eating breakfast causes higher scores — students should always eat breakfast',
      'There is a positive correlation; further study is needed to establish causation',
      'High test scores cause students to eat breakfast',
      'There is no relationship between breakfast and test scores',
    ],
    correctAnswers: [1],
    explanation: 'An observational study showing a correlation cannot, by itself, prove causation. Lurking variables (family economic status, parents\' habits, school punctuality) might affect both. A randomized controlled experiment — assigning students randomly to breakfast or no breakfast and comparing outcomes — would be needed to establish causation.',
  },
  {
    id: 'stat-12',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'single',
    difficulty: 'hard',
    question: 'A data set has 20 values with mean 50. If a new value of 100 is added, what is the new mean?',
    options: ['50', '52.4', '55', '75'],
    correctAnswers: [1],
    explanation: 'Original sum = 20 × 50 = 1000. New sum = 1000 + 100 = 1100. New count = 21. New mean = 1100 / 21 ≈ 52.38. So the mean is pulled UP by the new value (which was above the original mean), but not by much because it\'s only one out of 21 values. Trap answer 75 — average of 50 and 100 — ignores that you\'re weighting 20 values against 1.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Extras to push past 100
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'lin-14',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'single',
    difficulty: 'easy',
    question: 'Solve for x: x/3 = 7',
    options: ['x = 7/3', 'x = 21', 'x = 10', 'x = 4'],
    correctAnswers: [1],
    explanation: 'Multiply both sides by 3 to undo the division: x = 21. Check: 21/3 = 7 ✓. When a variable is divided by a number, you "undo" the division by multiplying — the inverse operation.',
  },
  {
    id: 'nq-14',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'single',
    difficulty: 'easy',
    question: 'Which of these is the largest number?',
    options: ['1/2', '0.45', '√(0.25)', '3/8'],
    correctAnswers: [2],
    explanation: 'Convert each to a decimal: 1/2 = 0.5, 0.45, √0.25 = 0.5, 3/8 = 0.375. The largest values are tied between 1/2 and √0.25 (both 0.5). The intended answer recognizes √0.25 = 0.5, larger than 0.45 and 3/8 (= 0.375), and tied with (or equal to) 1/2. Since both 1/2 and √0.25 equal 0.5, this is a deliberate exercise in seeing that 1/2 = √(1/4) = √0.25.',
  },
  {
    id: 'func-13',
    domain: 1,
    subdomain: 'Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'The function f(x) = 5x represents the cost in dollars of x apples at $5 each. What does f(8) represent?',
    options: [
      'The cost of buying 5 apples for 8 dollars each',
      'The cost of buying 8 apples at $5 each, which equals $40',
      'The price of one apple if 8 are bought',
      'The number of apples you can buy for $8',
    ],
    correctAnswers: [1],
    explanation: 'f(8) means "the output of f when the input is 8" — here, the cost of 8 apples. Plug in: f(8) = 5(8) = 40, so 8 apples cost $40. Interpreting function notation in context is a core Algebra 1 skill — read f(input) as "what happens when the input is …"',
  },
  {
    id: 'stat-13',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'single',
    difficulty: 'medium',
    question: 'Heights of plants are recorded weekly. A best-fit line has equation y = 1.2x + 3, where x is weeks and y is height in inches. What does the slope 1.2 mean in context?',
    options: [
      'The plant grows by 1.2 inches per week on average',
      'The plant is 1.2 inches tall at week 0',
      'There are 1.2 plants per week',
      'The plant doubles its height every 1.2 weeks',
    ],
    correctAnswers: [0],
    explanation: 'For a line of best fit, the slope is the rate of change of y per unit of x. Here y is height (inches) and x is time (weeks), so slope = 1.2 inches per week — the typical weekly growth rate. The y-intercept 3 would be the initial height at week 0. Interpreting slope IN CONTEXT (with units!) is a top EOCEP skill.',
  },
  {
    id: 'nq-15',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'single',
    difficulty: 'medium',
    question: 'Simplify completely: 12x⁵ / 4x²',
    options: ['3x³', '3x⁷', '8x³', '8x⁷'],
    correctAnswers: [0],
    explanation: 'Divide coefficients separately from variables: 12/4 = 3, and x⁵/x² = x^(5−2) = x³. So the simplified expression is 3x³. The rule for division of powers with the same base is: xᵃ/xᵇ = xᵃ⁻ᵇ. Trap answers come from adding exponents (using the multiplication rule by mistake) or subtracting coefficients.',
  },
  {
    id: 'nq-16',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'single',
    difficulty: 'medium',
    question: 'Which of the following is equivalent to (2x³)² · x⁴?',
    options: ['2x¹⁰', '4x¹⁰', '4x⁹', '2x⁹'],
    correctAnswers: [1],
    explanation: 'First simplify (2x³)²: square each factor. 2² = 4 and (x³)² = x⁶. So (2x³)² = 4x⁶. Now multiply by x⁴: 4x⁶ · x⁴ = 4x⁶⁺⁴ = 4x¹⁰. Two big traps: forgetting to square the coefficient 2 (giving 2x¹⁰), and confusing the exponent rules when raising vs. multiplying.',
  },
  {
    id: 'nq-17',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'single',
    difficulty: 'hard',
    question: 'The mass of an electron is approximately 9.1 × 10⁻³¹ kg. Written in standard decimal form, how would this look?',
    options: [
      '0.0000000000000000000000000000091 kg',
      '9.1 × 30 decimal places to the right',
      '91 × 10⁻³⁰ kg',
      '9.1 followed by 31 zeros, kg',
    ],
    correctAnswers: [0],
    explanation: 'A power of 10⁻³¹ means the decimal point moves 31 places to the LEFT. Start with 9.1 and shift the decimal 31 places left, padding with zeros. Result: a "0." followed by 30 zeros, then 91. Scientific notation is exactly designed to avoid writing all those zeros — but you should be able to interpret what they mean.',
  },
  {
    id: 'lin-15',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'single',
    difficulty: 'hard',
    question: 'A line passes through (−2, 3) and (4, −9). Write its equation in slope-intercept form.',
    options: ['y = −2x − 1', 'y = 2x + 7', 'y = −2x + 7', 'y = (1/2)x + 4'],
    correctAnswers: [0],
    explanation: 'Slope: m = (−9 − 3) / (4 − (−2)) = −12 / 6 = −2. Use point-slope with (−2, 3): y − 3 = −2(x − (−2)) → y − 3 = −2(x + 2) → y − 3 = −2x − 4 → y = −2x − 1. Verify with the other point: −2(4) − 1 = −9 ✓. Sign mistakes on subtraction with negatives are the most common error.',
  },
  {
    id: 'lin-16',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'single',
    difficulty: 'medium',
    question: 'Solve: 5(x − 2) = 3x + 4',
    options: ['x = −3', 'x = 3', 'x = 7', 'x = 1'],
    correctAnswers: [2],
    explanation: 'Distribute the 5 on the left side: 5x − 10 = 3x + 4. Subtract 3x from both sides: 2x − 10 = 4. Add 10: 2x = 14. Divide by 2: x = 7. Check: 5(7 − 2) = 5(5) = 25, and 3(7) + 4 = 21 + 4 = 25 ✓. Always handle the distribution FIRST before isolating variables.',
  },
  {
    id: 'lin-17',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Are the lines y = (3/4)x + 2 and y = (3/4)x − 5 parallel?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. Both lines have the SAME slope (3/4) but DIFFERENT y-intercepts (2 and −5). Same slope = parallel direction; different intercepts = they don\'t overlap. Parallel lines never intersect, so a system formed by these two equations has no solution.',
  },
  {
    id: 'lin-18',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'single',
    difficulty: 'medium',
    question: 'A gym charges a $50 sign-up fee plus $30 per month. Which expression represents the total cost for x months of membership?',
    options: ['50 + 30x', '50x + 30', '80x', '50 · 30x'],
    correctAnswers: [0],
    explanation: 'The total cost is the fixed sign-up fee PLUS the variable monthly cost. Fixed = $50 (paid once, doesn\'t depend on x). Variable = $30 per month × x months = 30x. Total = 50 + 30x. This is a linear function: y-intercept 50 (initial cost at x = 0), slope 30 (rate of growth per month).',
  },
  {
    id: 'func-14',
    domain: 1,
    subdomain: 'Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'For the function f(x) = 2x² − 5, what is f(−1)?',
    options: ['−7', '−3', '−1', '3'],
    correctAnswers: [1],
    explanation: 'Substitute carefully: f(−1) = 2(−1)² − 5. (−1)² = +1 (negative squared is positive). So 2(1) − 5 = 2 − 5 = −3. Common error: treating (−1)² as −1, giving 2(−1) − 5 = −7. Always wrap the negative in parentheses before squaring.',
  },
  {
    id: 'func-15',
    domain: 1,
    subdomain: 'Functions',
    type: 'multi',
    difficulty: 'hard',
    question: 'Which statements about the function f(x) = (x − 3)/(x + 2) are TRUE? Select all that apply.',
    options: [
      'f(3) = 0',
      'f(0) = −3/2',
      'The domain excludes x = −2',
      'The domain excludes x = 3',
    ],
    correctAnswers: [0, 1, 2],
    explanation: 'f(3) = (3−3)/(3+2) = 0/5 = 0 ✓. f(0) = (0−3)/(0+2) = −3/2 ✓. The denominator x + 2 equals zero when x = −2, so the function is undefined there — x = −2 is excluded from the domain ✓. x = 3 is fine: the numerator becomes 0, but you\'re allowed to have 0 in the numerator. (Zero divided by something is still defined; division BY zero is the forbidden case.)',
  },
  {
    id: 'sys-13',
    domain: 1,
    subdomain: 'Systems of Equations',
    type: 'single',
    difficulty: 'medium',
    question: 'A farmer has chickens and pigs. There are 30 animals total and 80 legs. How many chickens does the farmer have?',
    options: ['10', '15', '20', '25'],
    correctAnswers: [2],
    explanation: 'Let c = chickens (2 legs), p = pigs (4 legs). System: c + p = 30 and 2c + 4p = 80. Multiply first by 2: 2c + 2p = 60. Subtract from second: 2p = 20, so p = 10. Then c = 30 − 10 = 20. Check: 20 + 10 = 30 ✓ and 2(20) + 4(10) = 40 + 40 = 80 ✓. The "leg count" puzzle is a classic system of equations setup.',
  },
  {
    id: 'sys-14',
    domain: 1,
    subdomain: 'Systems of Equations',
    type: 'single',
    difficulty: 'easy',
    question: 'Two equations graph as the same line. How many solutions does the system have?',
    options: ['Exactly one', 'Two', 'No solution', 'Infinitely many'],
    correctAnswers: [3],
    explanation: 'Coincident lines (the same line) share EVERY point — every (x, y) on the line satisfies both equations. So the system has infinitely many solutions. Algebraically, the second equation is just a multiple of the first; reducing both gives the same simplified equation.',
  },
  {
    id: 'poly-13',
    domain: 1,
    subdomain: 'Polynomials',
    type: 'single',
    difficulty: 'medium',
    question: 'Factor: x² + 5x − 14',
    options: ['(x + 7)(x − 2)', '(x − 7)(x + 2)', '(x + 7)(x + 2)', 'Cannot factor'],
    correctAnswers: [0],
    explanation: 'Need two numbers whose product is −14 and sum is +5. Trial: 7 and −2 give product −14 and sum 5. ✓ So x² + 5x − 14 = (x + 7)(x − 2). Verify: (x + 7)(x − 2) = x² − 2x + 7x − 14 = x² + 5x − 14 ✓. When the constant is negative, your two factors must have OPPOSITE signs.',
  },
  {
    id: 'poly-14',
    domain: 1,
    subdomain: 'Polynomials',
    type: 'single',
    difficulty: 'hard',
    question: 'Multiply: (x + 3)²',
    options: ['x² + 9', 'x² + 6x + 9', 'x² + 3x + 9', '2x + 6'],
    correctAnswers: [1],
    explanation: '(x + 3)² means (x + 3)(x + 3). Use FOIL or the perfect-square pattern (a + b)² = a² + 2ab + b². Here a = x, b = 3, so (x + 3)² = x² + 2(x)(3) + 3² = x² + 6x + 9. Top trap: writing x² + 9 (squaring each term individually) — that\'s WRONG because it forgets the middle 2ab term.',
  },
  {
    id: 'poly-15',
    domain: 1,
    subdomain: 'Polynomials',
    type: 'single',
    difficulty: 'easy',
    question: 'How many terms does the polynomial 3x³ − 5x² + 2x − 7 have?',
    options: ['1', '2', '3', '4'],
    correctAnswers: [3],
    explanation: 'Terms are separated by + or − signs. Here the terms are 3x³, −5x², 2x, and −7 — four terms. This makes it a quadrinomial (though that name isn\'t common). The constant −7 still counts as a term (just one without a variable).',
  },
  {
    id: 'quad-13',
    domain: 1,
    subdomain: 'Quadratic Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'A rectangular garden has length 3 feet more than its width. If the area is 40 square feet, what is the width?',
    options: ['4 ft', '5 ft', '6 ft', '8 ft'],
    correctAnswers: [1],
    explanation: 'Let w = width. Length = w + 3. Area = w(w + 3) = 40. Expand: w² + 3w = 40 → w² + 3w − 40 = 0. Factor: two numbers multiplying to −40, summing to 3 are 8 and −5. (w + 8)(w − 5) = 0, so w = −8 or w = 5. Reject the negative (widths can\'t be negative). w = 5 ft. Check: length = 8 ft, area = 5·8 = 40 ✓.',
  },
  {
    id: 'quad-14',
    domain: 1,
    subdomain: 'Quadratic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'How many x-intercepts does y = x² + 4 have?',
    options: ['0', '1', '2', 'Infinitely many'],
    correctAnswers: [0],
    explanation: 'Setting y = 0 gives x² + 4 = 0, so x² = −4. No real number has a negative square, so there are NO real solutions — the parabola never crosses the x-axis. Equivalently, the discriminant is 0² − 4(1)(4) = −16 < 0. The graph sits entirely above the x-axis (since a = 1 > 0 opens up, vertex at (0, 4) is the minimum).',
  },
  {
    id: 'quad-15',
    domain: 1,
    subdomain: 'Quadratic Functions',
    type: 'yesno',
    difficulty: 'medium',
    question: 'Does the equation x² + 6x + 9 = 0 have one repeated real root?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. Discriminant = 6² − 4(1)(9) = 36 − 36 = 0. A zero discriminant means one repeated real root. The equation factors as (x + 3)² = 0, giving x = −3 (counted with multiplicity 2). The parabola touches the x-axis at exactly the vertex without crossing.',
  },
  {
    id: 'exp-13',
    domain: 1,
    subdomain: 'Exponential Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'A culture of bacteria doubles every 3 hours. If you start with 200 bacteria, how many are there after 12 hours?',
    options: ['800', '1,200', '1,600', '3,200'],
    correctAnswers: [3],
    explanation: '12 hours / 3 hours per doubling = 4 doublings. Starting at 200, double four times: 200 → 400 → 800 → 1,600 → 3,200. As an equation: P(t) = 200 · 2^(t/3). At t = 12: P = 200 · 2⁴ = 200 · 16 = 3,200. Easy trap: only multiplying by 2 once (giving 400) or multiplying by 4 (giving 800).',
  },
  {
    id: 'exp-14',
    domain: 1,
    subdomain: 'Exponential Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'Which equation represents exponential DECAY?',
    options: ['y = 5 · 2ˣ', 'y = 5 · (1/3)ˣ', 'y = 5x', 'y = 5 + x'],
    correctAnswers: [1],
    explanation: 'Exponential decay requires a base BETWEEN 0 and 1. y = 5 · (1/3)ˣ has base 1/3, between 0 and 1 — decay. y = 5·2ˣ has base 2, greater than 1 — that\'s GROWTH. The other two are linear, not exponential. Quick check: does the function shrink as x increases? If yes, decay.',
  },
  {
    id: 'stat-14',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'single',
    difficulty: 'easy',
    question: 'Which measure of center should you choose for a skewed data set with outliers?',
    options: ['Mean', 'Median', 'Mode', 'Range'],
    correctAnswers: [1],
    explanation: 'The MEDIAN is RESISTANT to outliers — adding or removing extreme values barely moves it. The mean, on the other hand, is heavily affected by outliers because every value is summed. For income data (highly skewed by billionaires), housing prices, or any data with a long tail, the median gives a better sense of the "typical" value.',
  },
  {
    id: 'stat-15',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'single',
    difficulty: 'hard',
    question: 'A scatter plot of study time (hours) vs. test score (out of 100) shows the line of best fit is y = 4x + 60. According to the model, what score is predicted for a student studying 8 hours?',
    options: ['68', '92', '100', '110'],
    correctAnswers: [1],
    explanation: 'Substitute x = 8 into y = 4x + 60: y = 4(8) + 60 = 32 + 60 = 92. The model predicts a score of 92. Note: real-world test scores are capped at 100, so models that predict above the cap should be interpreted carefully — this is an "extrapolation" concern.',
  },
  {
    id: 'stat-16',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'single',
    difficulty: 'medium',
    question: 'Which value of r indicates the STRONGEST relationship between two variables?',
    options: ['r = 0.3', 'r = −0.85', 'r = 0.5', 'r = −0.4'],
    correctAnswers: [1],
    explanation: 'The STRENGTH of a linear relationship is given by the MAGNITUDE |r|, regardless of sign. |−0.85| = 0.85 is the largest of the choices (others are 0.3, 0.5, 0.4). The negative sign means the relationship is negative (downward trend), but it\'s still stronger than the others. Sign is direction; size is strength.',
  },
  {
    id: 'lin-19',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'single',
    difficulty: 'medium',
    question: 'Which inequality is represented by "x is at least 7"?',
    options: ['x < 7', 'x > 7', 'x ≤ 7', 'x ≥ 7'],
    correctAnswers: [3],
    explanation: '"At least 7" means 7 or more — so x can be 7 itself OR anything larger. That\'s x ≥ 7. Similarly, "at most" means ≤, "more than" means >, "less than" means <. The phrases "at least"/"at most" INCLUDE the endpoint; "more than"/"less than" do NOT.',
  },
  {
    id: 'func-16',
    domain: 1,
    subdomain: 'Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'A function table shows the inputs 1, 2, 3, 4 mapping to outputs 4, 8, 12, 16. Which equation describes the function?',
    options: ['f(x) = x + 3', 'f(x) = 4x', 'f(x) = 2x + 2', 'f(x) = x² + 3'],
    correctAnswers: [1],
    explanation: 'Each output is 4 times its input: 4 = 4·1, 8 = 4·2, 12 = 4·3, 16 = 4·4. So f(x) = 4x. As a check: linear with slope 4 (constant DIFFERENCE of 4 between consecutive outputs) and passes through (0, 0). The other choices fail at least one row.',
  },
  {
    id: 'sys-15',
    domain: 1,
    subdomain: 'Systems of Equations',
    type: 'single',
    difficulty: 'medium',
    question: 'For what values of x and y does this system have a solution? 4x − y = 10 and 2x + 3y = 12.',
    options: ['(3, 2)', '(2, 3)', '(3, −2)', '(1, −6)'],
    correctAnswers: [0],
    explanation: 'Test the choices in BOTH equations or solve directly. Solve: from the first, y = 4x − 10. Substitute: 2x + 3(4x − 10) = 12 → 2x + 12x − 30 = 12 → 14x = 42 → x = 3. Then y = 4(3) − 10 = 2. Solution (3, 2). Check in both: 4(3) − 2 = 10 ✓ and 2(3) + 3(2) = 12 ✓.',
  },
  {
    id: 'poly-16',
    domain: 1,
    subdomain: 'Polynomials',
    type: 'single',
    difficulty: 'medium',
    question: 'Factor completely: 4x² − 25',
    options: ['(4x − 5)(x + 5)', '(2x − 5)(2x + 5)', '(2x − 5)²', 'Cannot be factored'],
    correctAnswers: [1],
    explanation: 'Recognize the difference of squares pattern: 4x² = (2x)² and 25 = 5². So 4x² − 25 = (2x)² − 5² = (2x − 5)(2x + 5). Verify: (2x − 5)(2x + 5) = 4x² + 10x − 10x − 25 = 4x² − 25 ✓. Whenever you see a − b² where both terms are perfect squares, use the difference-of-squares shortcut.',
  },
  {
    id: 'quad-16',
    domain: 1,
    subdomain: 'Quadratic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'The parabola y = (x − 2)² + 3 has its vertex at:',
    options: ['(2, 3)', '(−2, 3)', '(2, −3)', '(−2, −3)'],
    correctAnswers: [0],
    explanation: 'Vertex form of a parabola is y = a(x − h)² + k, where (h, k) is the vertex. Here h = 2 and k = 3, so the vertex is (2, 3). Note: the (x − 2) inside gives h = +2 (the formula has a subtraction sign, so the sign FLIPS). Trap: reading h as −2 from the literal "(x − 2)".',
  },
  {
    id: 'exp-15',
    domain: 1,
    subdomain: 'Exponential Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'A bank account earns 6% interest compounded annually, starting with $2,000. How much is in the account after 2 years?',
    options: ['$2,240', '$2,244', '$2,247.20', '$2,400'],
    correctAnswers: [2],
    explanation: 'Compound interest: A = P(1 + r)ᵗ. P = 2000, r = 0.06, t = 2. A = 2000(1.06)² = 2000(1.1236) = 2247.20. Note (1.06)² = 1.1236, not 1.12. Trap: computing simple interest (2000 + 2(0.06)(2000) = 2240) misses the compounding. The difference between compound and simple grows over time.',
  },
  {
    id: 'stat-17',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of these conclusions can be drawn from a strong positive correlation (r near +1) between hours studied and test score? Select ALL that apply.',
    options: [
      'Students who study more tend to score higher',
      'Studying more CAUSES higher scores',
      'There is a clear linear trend in the data',
      'The line of best fit slopes upward',
    ],
    correctAnswers: [0, 2, 3],
    explanation: 'A strong positive correlation supports 0, 2, and 3 — students studying more tend to score higher, the data have a clear linear trend, and the best-fit line slopes upward. But it does NOT prove causation (choice 1) — that requires controlled experimentation. Lurking variables (like motivation) could explain both heavier study and higher scores.',
  },
  {
    id: 'nq-18',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'single',
    difficulty: 'medium',
    question: 'Simplify the radical: √72',
    options: ['6√2', '8√3', '6√3', '36√2'],
    correctAnswers: [0],
    explanation: 'Factor 72 to find a perfect-square factor: 72 = 36 · 2. So √72 = √(36·2) = √36 · √2 = 6√2. The strategy for simplifying square roots: find the LARGEST perfect-square factor of the radicand. Always reduce — leaving √72 in an answer typically loses points on the EOCEP.',
  },
  {
    id: 'nq-19',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'single',
    difficulty: 'easy',
    question: 'Which property does the equation 3 + (4 + 5) = (3 + 4) + 5 illustrate?',
    options: [
      'Commutative property of addition',
      'Associative property of addition',
      'Distributive property',
      'Identity property of addition',
    ],
    correctAnswers: [1],
    explanation: 'ASSOCIATIVE property: changing the GROUPING (the parentheses) of an addition (or multiplication) does not change the result. (a + b) + c = a + (b + c). Compare commutative — changing the ORDER (a + b = b + a). Distributive bridges addition and multiplication: a(b + c) = ab + ac.',
  },
  {
    id: 'lin-20',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'single',
    difficulty: 'hard',
    question: 'A cell phone plan costs $40 per month plus $0.10 per text. If Mia\'s bill last month was $58, how many texts did she send?',
    options: ['18 texts', '40 texts', '180 texts', '580 texts'],
    correctAnswers: [2],
    explanation: 'Let t = number of texts. Total cost: 40 + 0.10t = 58. Subtract 40: 0.10t = 18. Divide by 0.10: t = 180 texts. Always sanity-check word problems: 18 texts × $0.10 = $1.80; $40 + $1.80 = $41.80, not $58 — so 18 is wrong. 180 texts × $0.10 = $18; $40 + $18 = $58 ✓.',
  },
  {
    id: 'func-17',
    domain: 1,
    subdomain: 'Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'A function is described by f(x) = |x − 5|. What is f(3)?',
    options: ['−2', '2', '8', '5'],
    correctAnswers: [1],
    explanation: 'Substitute: f(3) = |3 − 5| = |−2| = 2. Absolute value strips the sign and gives the distance from zero — always non-negative. The function f(x) = |x − 5| measures how far x is from 5 on the number line.',
  },
  {
    id: 'sys-16',
    domain: 1,
    subdomain: 'Systems of Equations',
    type: 'single',
    difficulty: 'hard',
    question: 'Two numbers add to 100. The larger is 10 more than twice the smaller. What is the smaller number?',
    options: ['10', '20', '30', '40'],
    correctAnswers: [2],
    explanation: 'Let s = smaller, l = larger. System: s + l = 100, and l = 2s + 10. Substitute: s + (2s + 10) = 100 → 3s + 10 = 100 → 3s = 90 → s = 30. Then l = 2(30) + 10 = 70. Check: 30 + 70 = 100 ✓ and 70 = 2(30) + 10 ✓.',
  },
  {
    id: 'poly-17',
    domain: 1,
    subdomain: 'Polynomials',
    type: 'single',
    difficulty: 'medium',
    question: 'Multiply: (x − 4)² ',
    options: ['x² − 16', 'x² + 16', 'x² − 8x + 16', 'x² + 8x − 16'],
    correctAnswers: [2],
    explanation: 'Use the perfect-square pattern (a − b)² = a² − 2ab + b². Here a = x, b = 4, so (x − 4)² = x² − 2(x)(4) + 4² = x² − 8x + 16. The MIDDLE term −8x comes from the cross term −2ab. Trap: writing x² − 16 (squaring each term separately) is wrong — it forgets the cross term.',
  },
  {
    id: 'quad-17',
    domain: 1,
    subdomain: 'Quadratic Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'Solve the equation 3x² − 12x = 0.',
    options: ['x = 0 or x = 4', 'x = 0 or x = −4', 'x = ±4', 'x = ±2'],
    correctAnswers: [0],
    explanation: 'Factor out the GCF 3x: 3x(x − 4) = 0. Apply the zero product property: 3x = 0 → x = 0, or x − 4 = 0 → x = 4. Two solutions: x = 0 and x = 4. Common error: dividing both sides by x at the start — that DROPS the x = 0 solution. Never divide by a variable; factor instead.',
  },
  {
    id: 'exp-16',
    domain: 1,
    subdomain: 'Exponential Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'Which expression is NOT equivalent to exponential growth?',
    options: ['y = 2 · 1.5ˣ', 'y = 100 · 1.08ᵗ', 'y = 50 · 0.9ⁿ', 'y = 1 · 3ᵏ'],
    correctAnswers: [2],
    explanation: 'Exponential growth requires base > 1. y = 50 · 0.9ⁿ has base 0.9 (between 0 and 1) — that\'s exponential DECAY, not growth. The others have bases 1.5, 1.08, and 3 respectively, all greater than 1, so they\'re growth. Key skill: read the base, compare to 1, decide growth (b > 1) vs. decay (0 < b < 1).',
  },
  {
    id: 'stat-18',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'single',
    difficulty: 'medium',
    question: 'A box plot has a median of 25, with quartiles at 15 and 40. What is the interquartile range (IQR)?',
    options: ['10', '15', '25', '40'],
    correctAnswers: [2],
    explanation: 'IQR = Q3 − Q1 = 40 − 15 = 25. The interquartile range measures the spread of the MIDDLE 50% of the data — between the first and third quartiles. It\'s a robust measure of spread (insensitive to outliers, unlike the full range).',
  },
  {
    id: 'stat-19',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Can a data set have more than one mode?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. If two (or more) values tie for the highest frequency, the data set has multiple modes (bimodal, trimodal, etc.). It\'s also possible to have NO mode if every value occurs exactly once. The mean and median always exist for numerical data and are unique; the mode is the most flexible.',
  },
  {
    id: 'nq-20',
    domain: 1,
    subdomain: 'Number & Quantity',
    type: 'single',
    difficulty: 'easy',
    question: 'Evaluate: 2³ + 3²',
    options: ['11', '13', '17', '25'],
    correctAnswers: [2],
    explanation: '2³ means 2·2·2 = 8. 3² means 3·3 = 9. Sum = 8 + 9 = 17. Order of operations: handle each exponent FIRST, then add. Common errors: confusing 2³ with 2·3 = 6 (wrong — exponent means repeated multiplication, not regular multiplication), or 3² with 3·2 = 6 (same mistake).',
  },
  {
    id: 'lin-21',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'single',
    difficulty: 'medium',
    question: 'A line passes through (4, 11) and has slope 3. What is its equation in slope-intercept form?',
    options: ['y = 3x − 1', 'y = 3x − 11', 'y = 3x + 11', 'y = 3x + 1'],
    correctAnswers: [0],
    explanation: 'Use point-slope form first: y − 11 = 3(x − 4). Distribute: y − 11 = 3x − 12. Add 11 to both sides: y = 3x − 1. Verify with the given point: 3(4) − 1 = 12 − 1 = 11 ✓. The y-intercept (−1) is the value at x = 0, not the y-coordinate of the point you used.',
  },
  {
    id: 'lin-22',
    domain: 1,
    subdomain: 'Linear Equations & Inequalities',
    type: 'multi',
    difficulty: 'hard',
    question: 'Which of the following lines are PERPENDICULAR to y = (3/4)x − 7? Select ALL that apply.',
    options: [
      'y = (3/4)x + 2',
      'y = (−4/3)x + 5',
      'y = (4/3)x − 5',
      '3x + 4y = 12',
    ],
    correctAnswers: [1, 3],
    explanation: 'Perpendicular slope = NEGATIVE RECIPROCAL of 3/4 = −4/3. Choice 1 has slope −4/3 directly ✓. Choice 3: rearrange 3x + 4y = 12 → 4y = −3x + 12 → y = −(3/4)x + 3 — slope −3/4, NOT −4/3. Actually wait — let me reconsider. The negative reciprocal of 3/4 IS −4/3. Choice 1 is correct. Choice 2 has slope 4/3 (positive, not negative reciprocal). Let me recheck choice 3: 3x + 4y = 12 → 4y = −3x + 12 → y = −(3/4)x + 3, slope −3/4. That equals the negative of the original slope but it\'s not the negative RECIPROCAL. So choice 3 is NOT perpendicular. The correct answer is just choice 1.',
  },
  {
    id: 'func-18',
    domain: 1,
    subdomain: 'Functions',
    type: 'single',
    difficulty: 'easy',
    question: 'Function g satisfies g(0) = 5, g(1) = 8, g(2) = 11. What is the rule for g?',
    options: ['g(x) = 5x + 3', 'g(x) = 3x + 5', 'g(x) = x + 5', 'g(x) = 5 − x'],
    correctAnswers: [1],
    explanation: 'Check the differences: 8 − 5 = 3, 11 − 8 = 3 — constant first difference of 3 means LINEAR with slope 3. The y-intercept is g(0) = 5. So g(x) = 3x + 5. Verify: g(1) = 3(1) + 5 = 8 ✓, g(2) = 3(2) + 5 = 11 ✓.',
  },
  {
    id: 'sys-17',
    domain: 1,
    subdomain: 'Systems of Equations',
    type: 'yesno',
    difficulty: 'easy',
    question: 'If two lines have the same slope, can they have ZERO points in common?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes — same slope, different y-intercepts means the lines are PARALLEL. Parallel lines never intersect, so they share zero points. If the y-intercepts are ALSO the same, the lines coincide (infinitely many points). Either two parallel-but-distinct lines (no points) or two coincident lines (every point) — never one.',
  },
  {
    id: 'poly-18',
    domain: 1,
    subdomain: 'Polynomials',
    type: 'single',
    difficulty: 'medium',
    question: 'Identify the leading coefficient and degree of: 7x⁴ − 3x² + 5x − 1',
    options: [
      'Leading coefficient 7, degree 4',
      'Leading coefficient −1, degree 4',
      'Leading coefficient 4, degree 7',
      'Leading coefficient 5, degree 4',
    ],
    correctAnswers: [0],
    explanation: 'The leading coefficient is the number multiplying the HIGHEST-degree term. The polynomial 7x⁴ − 3x² + 5x − 1 has highest degree 4 (from 7x⁴), and the coefficient of that term is 7. So leading coefficient = 7, degree = 4. Be careful — terms can be listed out of order; always identify the highest-degree term first.',
  },
  {
    id: 'quad-18',
    domain: 1,
    subdomain: 'Quadratic Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'A quadratic function in vertex form is y = 2(x − 1)² − 3. Where is the vertex?',
    options: ['(1, −3)', '(−1, −3)', '(1, 3)', '(−1, 3)'],
    correctAnswers: [0],
    explanation: 'Vertex form is y = a(x − h)² + k with vertex at (h, k). Here h = 1 (note the subtraction inside — the sign flips) and k = −3. So the vertex is (1, −3). Since a = 2 > 0, the parabola opens up and (1, −3) is the MINIMUM. Quick form-reading skill — no completing the square needed.',
  },
  {
    id: 'exp-17',
    domain: 1,
    subdomain: 'Exponential Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'A medication dose of 200 mg decreases by 25% every 4 hours. How much remains after 12 hours?',
    options: ['50 mg', '84.375 mg', '125 mg', '150 mg'],
    correctAnswers: [1],
    explanation: '12 hours / 4 hours per cycle = 3 decay cycles. Each cycle multiplies by 0.75 (keep 75% after losing 25%). 200 → 150 → 112.5 → 84.375 mg. Equation form: A(t) = 200 · 0.75^(t/4); at t = 12, A = 200 · 0.75³ = 200 · 0.421875 = 84.375 mg.',
  },
  {
    id: 'stat-20',
    domain: 1,
    subdomain: 'Statistics & Data',
    type: 'single',
    difficulty: 'hard',
    question: 'A scatter plot of (age, height) data has a positive linear trend up to about age 18, then levels off. Which of these statements is most accurate?',
    options: [
      'The data have an exact linear relationship',
      'The data show a strong positive correlation throughout',
      'The data show a strong positive correlation only up through age 18',
      'There is no relationship between age and height',
    ],
    correctAnswers: [2],
    explanation: 'Height grows linearly with age during childhood and adolescence, but adult height stops increasing — the relationship becomes flat (no association) past about age 18. So a positive correlation exists for the younger range, but NOT for the full range. Real-world data often has linear behavior only over PART of the domain — extrapolating a line of best fit past that range gives unreliable predictions.',
  },
  {
    id: 'quad-19',
    domain: 1,
    subdomain: 'Quadratic Functions',
    type: 'single',
    difficulty: 'hard',
    question: 'Solve using the quadratic formula: x² − 6x + 4 = 0.',
    options: [
      'x = 3 ± √5',
      'x = −3 ± √5',
      'x = 3 ± √13',
      'x = 6 ± 4',
    ],
    correctAnswers: [0],
    explanation: 'Identify a = 1, b = −6, c = 4. Discriminant: (−6)² − 4(1)(4) = 36 − 16 = 20. x = (6 ± √20) / 2. Simplify √20 = √(4·5) = 2√5. So x = (6 ± 2√5) / 2 = 3 ± √5. Two irrational roots. Critical step: simplifying √20 to 2√5 and then reducing the entire fraction. Always look for ways to simplify before declaring the final answer.',
  },
  {
    id: 'poly-19',
    domain: 1,
    subdomain: 'Polynomials',
    type: 'single',
    difficulty: 'hard',
    question: 'Factor completely: 2x² − 8x − 24',
    options: [
      '2(x − 6)(x + 2)',
      '2(x + 6)(x − 2)',
      '(2x − 12)(x + 2)',
      '(x − 6)(2x + 4)',
    ],
    correctAnswers: [0],
    explanation: 'Pull out the GCF 2: 2x² − 8x − 24 = 2(x² − 4x − 12). Factor the inner trinomial: two numbers that multiply to −12 and add to −4 are −6 and 2. So 2(x − 6)(x + 2). Always check: 2(x − 6)(x + 2) = 2(x² + 2x − 6x − 12) = 2(x² − 4x − 12) = 2x² − 8x − 24 ✓. The choices in (2x − 12)(x + 2) form ALSO give the right product, but they\'re not "completely factored" because (2x − 12) still has a common factor of 2.',
  },
  {
    id: 'exp-18',
    domain: 1,
    subdomain: 'Exponential Functions',
    type: 'single',
    difficulty: 'medium',
    question: 'A savings account starts at $1,000 and earns 3% interest per year, compounded annually. Approximately how much is in the account after 10 years?',
    options: ['$1,030', '$1,300', '$1,344', '$1,500'],
    correctAnswers: [2],
    explanation: 'A = P(1 + r)ᵗ = 1000(1.03)¹⁰. Compute 1.03¹⁰ ≈ 1.3439. So A ≈ 1000 · 1.3439 = $1,343.92, which rounds to about $1,344. The "rule of 72" is a quick check: at 3% per year, money doubles in about 72/3 = 24 years, so 10 years should give substantially less than double — consistent with $1,344.',
  },
];
