// Glossary for ENG2 — SC English 2 (10th grade). Terms a sophomore is
// expected to recognize on the SC EOCEP. Shown as a Glossary section in
// the Study Guide and indexed by the unified search.

export interface GlossaryEntry {
  term: string;
  definition: string;
}

export const glossary: GlossaryEntry[] = [
  // ── Reading Literary Texts ────────────────────────────────────────
  { term: 'Theme',                 definition: 'The central idea, message, or insight about life that a literary work explores. Theme is NOT the topic ("love") but a claim about the topic ("first love changes how you see yourself"). Stated rarely; usually inferred from the whole work.' },
  { term: 'Characterization',      definition: 'How an author reveals a character\'s personality. DIRECT: the author tells you outright ("Mara was stubborn"). INDIRECT: shown through actions, dialogue, thoughts, appearance, and how other characters react ("STEAL": Speech, Thoughts, Effect on others, Actions, Looks).' },
  { term: 'Plot structure',        definition: 'The arrangement of events in a story: exposition (setup), rising action (complications), climax (turning point), falling action (consequences play out), and resolution (new normal). Sometimes called Freytag\'s pyramid.' },
  { term: 'Metaphor',              definition: 'A direct comparison that says one thing IS another, without "like" or "as." "Her voice was velvet." Metaphors fuse two things to transfer the qualities of one onto the other.' },
  { term: 'Simile',                definition: 'A comparison using "like" or "as." "Her voice was like velvet." Softer than a metaphor — it holds the two things side-by-side rather than fusing them.' },
  { term: 'Personification',       definition: 'Giving human qualities to non-human things. "The wind whispered through the trees." A specialized form of metaphor that brings inanimate or abstract things to life.' },
  { term: 'Imagery',               definition: 'Descriptive language that appeals to the five senses — sight, sound, smell, taste, touch. "The metallic tang of rain on hot pavement" engages smell and taste. Lets the reader experience the scene rather than just hear about it.' },
  { term: 'Symbolism',             definition: 'When an object, place, or action stands for something larger than itself. A flag for a country, a dove for peace, a green light at the end of a dock for a longed-for future. Symbols are recurring and tied to the work\'s themes.' },
  { term: 'Tone',                  definition: 'The author\'s attitude toward the subject, conveyed through word choice (diction) and sentence rhythm. Can be ironic, mournful, playful, urgent, detached, reverent — pick a specific adjective, not just "good" or "bad."' },
  { term: 'Mood',                  definition: 'The emotional atmosphere the work creates IN the reader. Tone is the author\'s attitude; mood is what you feel. A spooky setting + short sentences creates a tense mood even if the tone is detached.' },
  { term: 'Point of view',         definition: 'Who is narrating. FIRST PERSON ("I") = narrator is a character. THIRD PERSON LIMITED = outside narrator, but only one character\'s thoughts. THIRD PERSON OMNISCIENT = outside narrator who knows all characters\' thoughts. Second person ("you") is rare outside instructions.' },
  { term: 'Allusion',              definition: 'A brief reference to another well-known work, person, place, or event — usually expecting the reader to recognize it. "She had the patience of Job" alludes to the Bible. Compresses meaning by piggy-backing on a shared story.' },
  { term: 'Hyperbole',             definition: 'Deliberate exaggeration for effect, not meant literally. "I\'ve told you a million times." Used for humor, emphasis, or emotional intensity — never for factual accuracy.' },
  { term: 'Irony',                 definition: 'A gap between expectation and reality. VERBAL = saying the opposite of what you mean ("Nice weather" during a hurricane). SITUATIONAL = an outcome opposite to what was expected. DRAMATIC = the audience knows something the character doesn\'t.' },
  { term: 'Motif',                 definition: 'A recurring image, idea, or pattern in a literary work that reinforces a theme. Birds keep appearing in a novel about freedom; a clock keeps ticking in a story about mortality. Motifs differ from symbols in that they recur and accumulate meaning across the work.' },
  { term: 'Juxtaposition',         definition: 'Placing two contrasting things side by side to highlight their differences. A wealthy character and an impoverished one in the same scene; a peaceful image followed by a violent one. Forces the reader to notice the contrast.' },
  { term: 'Anaphora',              definition: 'A rhetorical/literary device that repeats the same word or phrase at the beginning of consecutive clauses or sentences. "We shall fight on the beaches, we shall fight on the landing grounds…" — Churchill. Builds rhythm and emphasis.' },
  { term: 'Soliloquy',             definition: 'A speech a character delivers alone on stage, voicing their inner thoughts to the audience. Common in Shakespeare ("To be or not to be…"). Unlike a monologue, no other characters are present to hear it.' },
  { term: 'Foreshadowing',         definition: 'Hints planted earlier in a work that anticipate something that will happen later. The "Chekhov\'s gun" idea: if a gun appears on the wall in Act 1, it must go off by Act 3. Re-reading rewards you when foreshadowing pays off.' },

  // ── Reading Informational Texts ───────────────────────────────────
  { term: 'Central idea',          definition: 'The main point of a nonfiction text — the single most important thing the author wants you to take away. Usually traceable through the topic sentences of each paragraph. NOT the same as the topic ("recycling"); it\'s the claim about the topic ("Curbside recycling programs save cities money").' },
  { term: 'Author\'s purpose',     definition: 'Why the author wrote the text. PIE: to Persuade, Inform, or Entertain. (Plus to Explain, Describe.) Identifying purpose helps you weigh evidence — a persuasive piece selects evidence to convince; an informative piece tries to be balanced.' },
  { term: 'Text structure',        definition: 'The organizational pattern a nonfiction writer uses: cause-and-effect, compare/contrast, chronological/sequence, problem/solution, or description. Spotting the structure helps you predict what comes next and locate key information faster.' },
  { term: 'Claim',                 definition: 'An arguable statement the author asks you to accept. Different from a fact. "Schools should start at 9 AM" is a claim; "Most US schools currently start before 8 AM" is a fact. A strong argument supports each claim with evidence.' },
  { term: 'Evidence',              definition: 'The facts, examples, statistics, expert quotations, or anecdotes a writer uses to support a claim. Strong evidence is specific, verifiable, and from credible sources; weak evidence is vague, anecdotal, or from biased sources.' },
  { term: 'Inference',             definition: 'A conclusion you draw by combining what the text says with what you already know. The text doesn\'t state it outright; you "read between the lines." Always anchor an inference to specific textual evidence — don\'t guess.' },

  // ── Argument & Rhetoric ───────────────────────────────────────────
  { term: 'Ethos',                 definition: 'A rhetorical appeal to the speaker\'s credibility, character, or authority. "As a board-certified pediatrician with 20 years of experience…" The audience trusts the message because they trust the messenger.' },
  { term: 'Pathos',                definition: 'A rhetorical appeal to the audience\'s emotions — fear, pity, anger, hope, pride. A story about a child harmed by lead paint is pathos. Powerful but easy to overuse; can manipulate rather than persuade.' },
  { term: 'Logos',                 definition: 'A rhetorical appeal to logic and reason — statistics, facts, causal reasoning, structured argument. "Studies of 12,000 children show a 30% drop in test scores when…" The strongest persuasive writing balances logos with the other two.' },
  { term: 'Counterclaim',          definition: 'A claim that opposes the writer\'s main argument. Strong argumentative writing names the counterclaim and then REBUTS it (answers it), showing the writer has considered other perspectives.' },
  { term: 'Logical fallacy',       definition: 'A flaw in reasoning that makes an argument unsound, even if it sounds persuasive. Common fallacies: ad hominem (attacking the person, not the argument), straw man, slippery slope, bandwagon, false dichotomy, hasty generalization, post hoc.' },
  { term: 'Ad hominem',            definition: 'A fallacy that attacks the person making the argument instead of the argument itself. "You can\'t trust her safety proposal — she\'s never even owned a car." The speaker\'s car-ownership is irrelevant to the proposal\'s merit.' },
  { term: 'Straw man',             definition: 'A fallacy that distorts an opponent\'s position into a weaker, easier-to-attack version, then knocks down that version instead. "You want safer streets? So you want to BAN ALL CARS?!" The original claim wasn\'t banning cars.' },
  { term: 'Bandwagon',             definition: 'A fallacy that argues something is correct because many people believe or do it. "Everyone\'s switching to brand X, so it must be the best." Popularity is not proof of correctness — millions of people once believed the earth was flat.' },
  { term: 'False dichotomy',       definition: 'A fallacy that presents only two options when more exist. "Either we cut the arts program or test scores will fall." Almost any "either/or" framing in real policy is suspicious — usually there\'s a third option being hidden.' },
  { term: 'Slippery slope',        definition: 'A fallacy that assumes one small step will inevitably lead to a chain of dramatic negative consequences. "If we allow phones in class, soon students will stop reading entirely." Each link in the chain needs evidence; otherwise it\'s just fear-mongering.' },

  // ── Language & Grammar ────────────────────────────────────────────
  { term: 'Subject-verb agreement', definition: 'The rule that a singular subject takes a singular verb, and a plural subject takes a plural verb. "The dog runs" / "The dogs run." Tricky when intervening phrases hide the real subject: "The box of cookies IS empty" (subject = box, not cookies).' },
  { term: 'Pronoun-antecedent agreement', definition: 'A pronoun must match its antecedent (the noun it replaces) in number and gender. "Every student brought HIS OR HER (or THEIR) book." Singular antecedent → singular pronoun (though singular "they" is increasingly accepted).' },
  { term: 'Comma splice',          definition: 'An ERROR that joins two independent clauses with only a comma. "I love writing, I hate editing." Fix it with a semicolon, a period, or a comma plus a conjunction: "I love writing; I hate editing" or "I love writing, but I hate editing."' },
  { term: 'Run-on sentence',       definition: 'Two or more independent clauses joined with no punctuation between them. "I love writing I hate editing." Fix with a period, a semicolon, or a comma + conjunction. Length isn\'t the issue — punctuation is.' },
  { term: 'Sentence fragment',     definition: 'A group of words punctuated as a sentence but missing a subject, a verb, or a complete thought. "Because she was late." Has a subject and verb but isn\'t a complete thought. Fix by attaching to a complete sentence or completing it.' },
  { term: 'Parallelism',           definition: 'Using the same grammatical form for items in a series. "She likes reading, writing, and editing" (all -ing forms). NOT parallel: "She likes reading, writing, and to edit." Lists, paired ideas, and comparisons all need parallel structure.' },
  { term: 'Dangling modifier',     definition: 'A descriptive phrase that doesn\'t clearly attach to anything in the sentence it modifies. "Walking to school, the rain started." (Was the rain walking?) Fix: "Walking to school, I noticed the rain start."' },
  { term: 'Independent clause',    definition: 'A group of words with a subject and a verb that expresses a complete thought and can stand alone as a sentence. "She studied." Joining two independent clauses requires punctuation: period, semicolon, or comma + conjunction.' },

  // ── Vocabulary in Context ─────────────────────────────────────────
  { term: 'Greek/Latin roots',     definition: 'The building blocks of many English words, borrowed from Greek and Latin. TELE (far): telephone, television. PHOTO (light): photograph, photosynthesis. BIO (life): biology, biography. Learning roots multiplies your vocabulary fast.' },
  { term: 'Prefix',                definition: 'A letter group added to the BEGINNING of a root word that changes meaning. UN- (not): unhappy. RE- (again): rewrite. PRE- (before): preview. DIS- (opposite): disagree. Knowing prefixes lets you decode unfamiliar words.' },
  { term: 'Suffix',                definition: 'A letter group added to the END of a word, often changing its part of speech or precise meaning. -TION (act of): creation. -ABLE (able to be): readable. -LY (in a way that is): quickly. -NESS (state of being): kindness.' },
  { term: 'Context clues',         definition: 'Hints to a word\'s meaning that are embedded in surrounding text. Types: definition ("Stoic, meaning unaffected by emotion"), example ("Carnivores like lions and wolves"), contrast ("Unlike her gregarious sister, Mara was reserved"), inference (figure it out from the situation).' },
  { term: 'Denotation',            definition: 'The literal, dictionary definition of a word — its strict meaning, stripped of emotional baggage. "Snake" denotes a long, limbless reptile.' },
  { term: 'Connotation',           definition: 'The emotional or cultural associations a word carries beyond its literal definition. "Snake" CONNOTES treachery in many cultures. "Childlike" and "childish" share a denotation but the connotations differ — childlike is innocent, childish is immature.' },

  // ── Writing — Argumentative & Informational ───────────────────────
  { term: 'Thesis statement',      definition: 'A single, focused sentence (usually at the end of the intro paragraph) that states the writer\'s central claim AND previews the supporting reasons. A strong thesis is arguable, specific, and clearly worded. Weak thesis: "Schools are important." Strong: "South Carolina schools should start no earlier than 8:30 AM because adolescent sleep cycles, academic performance, and traffic-accident rates all improve when teens get more sleep."' },
  { term: 'Topic sentence',        definition: 'The first sentence of a body paragraph that states what THAT paragraph will prove. Acts as a mini-thesis for that paragraph. The rest of the paragraph supplies evidence and analysis to support it.' },
  { term: 'MLA in-text citation',  definition: 'A brief parenthetical reference inside the writing that tells the reader the source. Format: (Author\'s last name page #). Example: "Adolescents need 8–10 hours of sleep (Smith 47)." For online sources without page numbers, omit the page number.' },
  { term: 'MLA Works Cited',       definition: 'A list of every source you cited in the essay, alphabetized by author\'s last name, on a separate page at the end. Each entry follows a specific format with author, title, container (journal, website), publisher, date, and location (URL or page range).' },

  // ── Research & Citation ───────────────────────────────────────────
  { term: 'Primary source',        definition: 'A firsthand record of an event or topic — a diary, letter, photograph, original research study, court ruling, interview, or speech transcript. Created by someone with direct involvement, not later commentary.' },
  { term: 'Secondary source',      definition: 'A work that analyzes, interprets, or summarizes primary sources — a textbook, encyclopedia article, biography, scholarly article reviewing other research, or news article about an event. Useful for context and overview.' },
  { term: 'Paraphrase',            definition: 'Restating someone else\'s ideas in your own words, keeping roughly the same length as the original. Still requires a citation — the IDEA is borrowed. Acceptable when you want the substance without the original phrasing.' },
  { term: 'Plagiarism',            definition: 'Using someone else\'s words or ideas without giving them credit. Includes copy-pasting from a source without quotes, paraphrasing without citing, or buying/turning in another person\'s work. Educational consequences are severe — always cite.' },
  { term: 'CRAAP test',            definition: 'A checklist for evaluating a source\'s credibility: Currency (recent enough?), Relevance (matches your topic?), Authority (who wrote it / what credentials?), Accuracy (verifiable claims?), Purpose (informing or persuading? bias?). Use it before you cite anything from the web.' },

  // ── Editing & Revision ────────────────────────────────────────────
  { term: 'Revising vs. editing',  definition: 'REVISING is big-picture rework — re-organizing paragraphs, sharpening the thesis, adding evidence, cutting whole sections. EDITING is fine-tuning — fixing grammar, spelling, punctuation, and word choice. Revise first; edit last. Don\'t polish a sentence you might delete.' },
  { term: 'Active vs. passive voice', definition: 'ACTIVE: the subject does the verb. "The committee approved the plan." PASSIVE: the subject receives the verb. "The plan was approved by the committee." Active is usually clearer and more direct; passive is appropriate when the doer is unknown or unimportant.' },
  { term: 'Concision',             definition: 'Saying more with fewer words. Cut redundancies ("end result" → "result"), filler ("really very" → "very"), and wordy phrases ("due to the fact that" → "because"). Concision sharpens your voice and respects the reader\'s time.' },
];
