// Question bank for ENG2 — SC English 2 (10th grade). Targets the SC End-of-Course
// Examination Program (EOCEP) for English 2.

export type QuestionType = 'single' | 'multi' | 'ordering' | 'yesno' | 'match' | 'hot-area' | 'case-study';

export interface Question {
  id: string;
  domain: 1;            // single domain — the EOCEP is one combined exam
  subdomain: string;
  type: QuestionType;
  difficulty: 'easy' | 'medium' | 'hard';
  question: string;
  options: string[];
  correctAnswers: number[];
  explanation: string;
  codeSnippet?: string;
  examTip?: string;
  match?: { leftItems: string[]; rightItems: string[]; correctPairs: [number, number][] };
  hotArea?: { svg: string; targets: { id: string; label: string }[]; correctTargetIds: string[]; selectAll?: boolean };
  caseStudy?: { scenario: string; subQuestions: { question: string; options: string[]; type: 'single' | 'multi'; correctAnswers: number[] }[] };
}

export const questions: Question[] = [
  // ══════════════════════════════════════════════════════════════════
  // Reading Literature
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'lit-01',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'easy',
    question: 'Which sentence best describes the THEME of a literary work?',
    options: [
      'A one-word topic the story is about, such as "love" or "war."',
      'The setting and time period in which the events take place.',
      'A central insight or claim about life that the work explores.',
      'A summary of the events that happen from beginning to end.',
    ],
    correctAnswers: [2],
    explanation: 'Theme is the author\'s central insight or claim about a topic — a full statement like "Loyalty can demand a heavy price." A one-word answer ("love," "war") is only the TOPIC, not the theme. Setting and plot summary are separate elements. On the EOCEP, theme answer choices that read like single words are almost always traps.',
  },
  {
    id: 'lit-02',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'easy',
    question: 'A narrator who refers to himself as "I" and is a character inside the story is using which point of view?',
    options: [
      'First person',
      'Second person',
      'Third person limited',
      'Third person omniscient',
    ],
    correctAnswers: [0],
    explanation: 'First person uses "I" and "me" — the narrator is a participant in the story. Second person uses "you" (rare outside instructions). Third person limited and omniscient both use "he/she/they" — the narrator stands outside the story. The pronoun "I" is the clearest first-person signal.',
  },
  {
    id: 'lit-03',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'easy',
    question: 'Which stage of plot is the TURNING POINT of greatest tension in a story?',
    options: [
      'Exposition',
      'Rising action',
      'Climax',
      'Resolution',
    ],
    correctAnswers: [2],
    explanation: 'The climax is the highest point of tension and the moment the central conflict turns. Exposition sets up characters and situation; rising action builds complications toward the climax; falling action plays out the consequences; resolution restores a new normal. The climax is the pivot the rest of the story rotates around.',
  },
  {
    id: 'lit-04',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'Read the excerpt: "Maya stared at the empty seat where her grandmother always sat. The chair seemed smaller now, as if it too had given up waiting." The chair functions in this passage as a —',
    options: [
      'Protagonist',
      'Symbol of loss',
      'Setting detail with no thematic weight',
      'Allusion to a previous text',
    ],
    correctAnswers: [1],
    explanation: 'The chair represents something larger than itself — the absence of the grandmother and Maya\'s grief. That is the definition of a symbol. A protagonist is a character, not an object; an allusion would point to a known outside work; and the personified phrase "as if it too had given up waiting" shows the chair carries thematic weight, so it is not just neutral setting.',
  },
  {
    id: 'lit-05',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'A short story shows a quiet, organized character secretly setting fire to her own life\'s work. Which TYPE OF CONFLICT is most clearly at the center of this story?',
    options: [
      'Character vs. nature',
      'Character vs. another character',
      'Character vs. self',
      'Character vs. society',
    ],
    correctAnswers: [2],
    explanation: 'A character acting against her own established identity and work is the textbook example of internal conflict — character vs. self. There is no antagonist character described, no force of nature, and no clash with society. Internal conflicts are common drivers of theme because they show characters in tension with their own values.',
  },
  {
    id: 'lit-06',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are characteristic of THIRD-PERSON OMNISCIENT point of view? Select ALL that apply.',
    options: [
      'The narrator is a character inside the story.',
      'The narrator stands outside the story.',
      'The narrator can access the thoughts and feelings of multiple characters.',
      'The narrator can only see one character\'s thoughts.',
      'The narrator uses pronouns like "he," "she," and "they."',
    ],
    correctAnswers: [1, 2, 4],
    explanation: 'Third-person omniscient narrators stand OUTSIDE the story (so they use "he/she/they") and can see into ANY character\'s mind. Being a character inside the story is first person. Being limited to one mind is third-person LIMITED, not omniscient. The defining feature of omniscient narration is access to multiple characters\' inner lives.',
  },
  {
    id: 'lit-07',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'easy',
    question: 'In a story, the main character who drives the action and whose journey the reader follows is called the —',
    options: [
      'Antagonist',
      'Narrator',
      'Protagonist',
      'Setting',
    ],
    correctAnswers: [2],
    explanation: 'The protagonist is the central character — the one whose goals, decisions, and growth structure the story. The antagonist opposes the protagonist. The narrator tells the story (and may or may not be the protagonist). The setting is where and when the story takes place.',
  },
  {
    id: 'lit-08',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'Read the excerpt: "He laughed, but his laugh sounded like glass cracking under heel." What does this image MOST suggest about the character\'s emotional state?',
    options: [
      'He is genuinely amused.',
      'He is breaking down inside despite the surface of laughter.',
      'He has poor dental hygiene.',
      'He is preparing to attack someone.',
    ],
    correctAnswers: [1],
    explanation: 'The simile "like glass cracking under heel" gives the laugh a sound of fragility and breakage. Even though he is laughing on the outside, the figurative comparison signals that something inside is shattering. Literal readings (dental hygiene, actual glass) miss the figurative work. Skilled readers always ask, "What does this comparison TELL me about the character?"',
  },
  {
    id: 'lit-09',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'yesno',
    difficulty: 'easy',
    question: 'In the play "Romeo and Juliet," the audience knows Juliet has only taken a sleeping potion, but Romeo believes she is truly dead. Is this an example of DRAMATIC IRONY?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. Dramatic irony occurs when the audience knows something important that a character does not. Here, the audience knows Juliet is alive while Romeo believes she is dead — the gap between audience knowledge and character knowledge is the source of the tragedy. Verbal irony would be saying the opposite of what you mean; situational irony would be an outcome opposite to what was expected.',
  },
  {
    id: 'lit-10',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'A reader is told nothing directly about a character but watches her give her only sandwich to a hungry stranger. The reader concludes she is generous. The reader has made a(n) —',
    options: [
      'Direct characterization',
      'Inference based on indirect characterization',
      'Hyperbole',
      'Allusion',
    ],
    correctAnswers: [1],
    explanation: 'When an author SHOWS character through actions and we DRAW a conclusion from that behavior, we are reading indirect characterization and making an inference. Direct characterization would be the narrator saying outright, "She was generous." Hyperbole is exaggeration; an allusion is a reference to another work — neither fits.',
  },
  {
    id: 'lit-11',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'Read the excerpt: "Spring after spring, the apple tree she planted with her daughter bloomed in the same corner of the yard, even when no one was left to notice." The recurring apple tree in this story most likely functions as —',
    options: [
      'A motif tied to memory and continuity',
      'A red herring distracting from the main plot',
      'A logical fallacy',
      'A counterclaim',
    ],
    correctAnswers: [0],
    explanation: 'A recurring image that accumulates meaning across a work is a motif. The repeated blooming of the tree, even after the daughter is gone, reinforces themes of memory and continuity. Red herring is a mystery device, not a literary technique used here. Logical fallacy and counterclaim are argument-writing terms, not literary analysis terms.',
  },
  {
    id: 'lit-12',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'hard',
    question: 'In a novel, a wealthy, careless young man rides past a starving family on the road. The narrator zooms in on his polished boots in the same paragraph that describes the family\'s bare feet. This deliberate side-by-side contrast is an example of —',
    options: [
      'Juxtaposition used to highlight social inequality',
      'Foreshadowing of the young man\'s death',
      'Personification',
      'Soliloquy',
    ],
    correctAnswers: [0],
    explanation: 'Placing two contrasting images side by side to force a comparison is juxtaposition. Here, polished boots and bare feet sharpen the reader\'s attention to wealth inequality. Foreshadowing would have to hint at a future event, not just contrast present details. Personification gives human qualities to non-human things; soliloquy is a solo speech in drama.',
  },
  {
    id: 'lit-13',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'Which of the following BEST describes the FALLING ACTION of a story?',
    options: [
      'The setup of characters and setting before the conflict begins.',
      'The turning point of greatest tension.',
      'The consequences of the climax playing out as the story moves toward an ending.',
      'The very last line of the story.',
    ],
    correctAnswers: [2],
    explanation: 'Falling action covers the events that follow the climax and lead toward the resolution — the consequences of the turning point unfolding. Exposition is setup; the climax is the turning point; the last line is part of the resolution. Distinguishing falling action from climax is a common EOCEP trap.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Reading Informational Text
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'info-01',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'easy',
    question: 'The CENTRAL IDEA of an informational text is best described as —',
    options: [
      'The topic, in one or two words.',
      'The most surprising fact mentioned.',
      'The single most important point the author wants the reader to take away.',
      'The first sentence of the article.',
    ],
    correctAnswers: [2],
    explanation: 'The central idea is the main claim or point of a nonfiction work — a full sentence the rest of the text supports. The topic ("recycling") is just the subject, not the central idea ("Curbside recycling saves cities money"). The most surprising fact is often a hook, not the main point. The first sentence is sometimes the central idea but not always.',
  },
  {
    id: 'info-02',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'easy',
    question: 'An article is organized as "Problem: rising sea levels. Solution: building seawalls and managed retreat." This is an example of which TEXT STRUCTURE?',
    options: [
      'Chronological / sequence',
      'Cause and effect',
      'Compare and contrast',
      'Problem and solution',
    ],
    correctAnswers: [3],
    explanation: 'A passage that names a problem and then proposes one or more solutions uses the problem-and-solution structure. Chronological/sequence presents events in time order; cause and effect explains why something happens; compare and contrast highlights similarities and differences. Recognizing structure helps you predict what comes next.',
  },
  {
    id: 'info-03',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'easy',
    question: 'When you draw a conclusion from a text by combining what is stated with what you already know, you are making a(n) —',
    options: [
      'Summary',
      'Inference',
      'Paraphrase',
      'Quotation',
    ],
    correctAnswers: [1],
    explanation: 'An inference is "reading between the lines" — combining the text\'s explicit information with your background knowledge to draw a conclusion the text does not state outright. A summary restates the main points; a paraphrase restates a specific passage in your own words; a quotation reproduces the exact words. Strong inferences are always anchored in textual evidence.',
  },
  {
    id: 'info-04',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are common purposes for an author of informational text? Select ALL that apply.',
    options: [
      'To persuade',
      'To inform',
      'To entertain',
      'To eliminate the audience',
      'To explain or describe',
    ],
    correctAnswers: [0, 1, 2, 4],
    explanation: 'The classic acronym is PIE: Persuade, Inform, Entertain. Many texts also Explain or Describe. "Eliminate the audience" is not a real purpose — that distractor is just nonsense. Identifying purpose tells you how skeptically to read: persuasive texts cherry-pick evidence; informative ones aim for balance.',
  },
  {
    id: 'info-05',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'medium',
    question: 'Read the excerpt: "Although electric vehicles have higher up-front prices, owners typically save $1,500 a year on fuel and maintenance." The word "Although" most strongly signals which text structure?',
    options: [
      'Chronological order',
      'Compare and contrast',
      'Description',
      'Spatial order',
    ],
    correctAnswers: [1],
    explanation: 'Transition words like "although," "however," "in contrast," and "on the other hand" signal compare-and-contrast structure — the author is setting two things against each other (here, sticker price vs. long-term cost). Chronological order would use time markers ("first," "then"); description would pile up sensory details; spatial order would describe physical arrangement.',
  },
  {
    id: 'info-06',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'medium',
    question: 'Which of the following would be the STRONGEST evidence to support the claim, "Reading aloud to children improves their later reading skills"?',
    options: [
      'A long-term study of 5,000 children that tracked reading habits and later test scores.',
      'A single parent\'s testimonial about her own child.',
      'A quote from a celebrity actor about her childhood.',
      'A blog post written by an anonymous author.',
    ],
    correctAnswers: [0],
    explanation: 'A large, long-term, controlled study is the strongest type of evidence — it shows a pattern across many people and many years. A single testimonial is anecdotal; a celebrity quote relies on a non-expert; an anonymous blog post has no clear authority. Strong evidence is verifiable, large in scale, and from credible sources.',
  },
  {
    id: 'info-07',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'easy',
    question: 'A SUPPORTING DETAIL in an informational text usually —',
    options: [
      'Restates the central idea word for word.',
      'Provides a specific example, statistic, fact, or quotation that backs up the central idea.',
      'Introduces a brand-new topic unrelated to the central idea.',
      'Lists the author\'s personal opinions without evidence.',
    ],
    correctAnswers: [1],
    explanation: 'Supporting details are the specific evidence — facts, statistics, examples, expert quotes — that prove the central idea. They EXTEND the central idea, not just repeat it. New unrelated topics belong in a different essay. Unsupported opinions are not supporting details in informational writing.',
  },
  {
    id: 'info-08',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'medium',
    question: 'An article begins, "In 1969, humans first walked on the moon. By 1972, the last Apollo mission returned. By 2025, the program had reawakened as Artemis prepared its first crewed flight." Which TEXT STRUCTURE does this paragraph use?',
    options: [
      'Cause and effect',
      'Problem and solution',
      'Chronological / sequence',
      'Compare and contrast',
    ],
    correctAnswers: [2],
    explanation: 'The passage lists events in time order — 1969, 1972, 2025 — which is chronological/sequence structure. Specific dates and time markers ("in 1969," "by 1972," "by 2025") are the clearest signal. Cause and effect would explain why events happened; problem/solution would offer a fix; compare/contrast would highlight differences between things.',
  },
  {
    id: 'info-09',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'yesno',
    difficulty: 'easy',
    question: 'A reader can usually find the CENTRAL IDEA of an article by reading carefully through the introduction, topic sentences of each paragraph, and the conclusion. Is this a sound strategy?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. Skilled writers usually preview the central idea in the introduction, develop it through topic sentences, and re-state or extend it in the conclusion. Tracing these waypoints is a reliable strategy for identifying the central idea, especially under time pressure. Skipping straight to random body sentences without context is much less reliable.',
  },
  {
    id: 'info-10',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'medium',
    question: 'An OBJECTIVE summary of an article should —',
    options: [
      'Include the reader\'s personal opinions about the topic.',
      'Restate the central idea and key supporting details without adding personal judgment.',
      'Copy long passages directly from the article.',
      'Argue with the author\'s claims point by point.',
    ],
    correctAnswers: [1],
    explanation: 'An objective summary is a neutral restatement of what the text actually says — central idea + key supporting details — without injecting the reader\'s opinions. Personal judgment goes in a critical response, not a summary. Long copy-pastes are not summaries (and risk plagiarism). Arguing with the author is a rebuttal, not a summary.',
  },
  {
    id: 'info-11',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'hard',
    question: 'Read the excerpt: "The rise in juvenile diabetes mirrors the rise in sugary-drink advertising. From 1990 to 2020, both more than doubled." What kind of reasoning is the author using?',
    options: [
      'Cause and effect, supported by parallel data trends.',
      'Compare and contrast of two unrelated phenomena.',
      'Pure narrative storytelling.',
      'A definition of "juvenile diabetes."',
    ],
    correctAnswers: [0],
    explanation: 'The author is implying that one trend (sugary-drink advertising) is causing the other (juvenile diabetes), supported by the parallel rise in both — cause-and-effect reasoning. A careful reader should also notice that mere correlation does not prove causation; this is a place where the EOCEP often tests the difference between association and causation.',
  },
  {
    id: 'info-12',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'medium',
    question: 'In an article comparing two music streaming services, the author writes, "Unlike Service A, which charges monthly, Service B uses a one-time annual fee." This sentence is an example of —',
    options: [
      'Definition',
      'Compare-and-contrast detail',
      'Anecdote',
      'Symbolism',
    ],
    correctAnswers: [1],
    explanation: 'Words like "unlike" set up a direct contrast between two things — the hallmark of compare-and-contrast detail. A definition tells you what something means; an anecdote is a short personal story; symbolism is a literary device, not a structural pattern in expository text.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Literary Devices & Figurative Language
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'dev-01',
    domain: 1,
    subdomain: 'Literary Devices & Figurative Language',
    type: 'single',
    difficulty: 'easy',
    question: 'In the sentence "The wind whispered secrets through the pine boughs," which literary device is being used?',
    options: [
      'Personification',
      'Metaphor',
      'Hyperbole',
      'Alliteration',
    ],
    correctAnswers: [0],
    explanation: 'Personification gives human qualities to non-human things — here the wind is given the human ability to whisper. A metaphor would directly equate two things ("the wind was a thief"); hyperbole is exaggeration; alliteration is repeated initial consonant sounds. Personification is one of the most-tested devices on the EOCEP because it is easy to confuse with metaphor.',
  },
  {
    id: 'dev-02',
    domain: 1,
    subdomain: 'Literary Devices & Figurative Language',
    type: 'single',
    difficulty: 'easy',
    question: 'Read the sentence: "Her voice was like silk." Which literary device is being used?',
    options: [
      'Metaphor',
      'Simile',
      'Personification',
      'Symbolism',
    ],
    correctAnswers: [1],
    explanation: 'A simile makes a comparison using the words "like" or "as." Here "like silk" makes the comparison explicit. A metaphor would have said, "Her voice WAS silk," fusing the two. Personification gives human qualities to non-human things; symbolism is when an object stands for something larger. The presence of "like" or "as" is the simile fingerprint.',
  },
  {
    id: 'dev-03',
    domain: 1,
    subdomain: 'Literary Devices & Figurative Language',
    type: 'single',
    difficulty: 'easy',
    question: '"I have told you a thousand times to clean your room." Which literary device is being used?',
    options: [
      'Personification',
      'Hyperbole',
      'Onomatopoeia',
      'Alliteration',
    ],
    correctAnswers: [1],
    explanation: 'Hyperbole is deliberate exaggeration not meant literally — the speaker has not actually told the listener a thousand times. Personification would give human qualities to non-human things; onomatopoeia uses words that sound like what they describe ("buzz," "hiss"); alliteration repeats initial consonant sounds. Hyperbole is recognizable because the statement is plainly impossible to be literally true.',
  },
  {
    id: 'dev-04',
    domain: 1,
    subdomain: 'Literary Devices & Figurative Language',
    type: 'single',
    difficulty: 'medium',
    question: 'Read the excerpt: "The classroom was a zoo when the substitute walked in." Which best identifies the device used?',
    options: [
      'Simile, because it compares two things',
      'Metaphor, because it says the classroom IS a zoo',
      'Personification, because the classroom acts human',
      'Allusion, because zoos are real places',
    ],
    correctAnswers: [1],
    explanation: 'A metaphor fuses two unlike things by saying one IS the other, without "like" or "as." "The classroom WAS a zoo" transfers the chaos of a zoo onto the classroom. If the sentence had read "The classroom was LIKE a zoo," it would be a simile. Personification would require the classroom acting in a human way; allusion would have to reference a specific outside work.',
  },
  {
    id: 'dev-05',
    domain: 1,
    subdomain: 'Literary Devices & Figurative Language',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following appeal primarily to the SENSE of HEARING in their use of imagery? Select ALL that apply.',
    options: [
      'The bell shrieked through the empty hallway.',
      'The metallic tang of blood filled her mouth.',
      'Footsteps crunched in the frozen gravel.',
      'A red ribbon fluttered in the spring breeze.',
      'The cafeteria hummed with morning chatter.',
    ],
    correctAnswers: [0, 2, 4],
    explanation: 'Imagery is sense-specific. "Shrieked," "crunched," and "hummed" all describe sounds — auditory imagery. The "metallic tang" appeals to taste; the "red ribbon" appeals to sight. Strong writers mix sense channels; strong readers track which channels are being engaged when analyzing imagery.',
  },
  {
    id: 'dev-06',
    domain: 1,
    subdomain: 'Literary Devices & Figurative Language',
    type: 'single',
    difficulty: 'medium',
    question: 'In a short story, a green light glows at the end of a distant dock every night for a longing character. Across the story, the green light most clearly functions as —',
    options: [
      'A hyperbole',
      'A symbol of an unreachable dream',
      'An onomatopoeia',
      'A pun',
    ],
    correctAnswers: [1],
    explanation: 'When an object recurs across a work and points to something larger than itself, it is functioning as a symbol. Here, the green light stands in for the character\'s longed-for, distant goal. Hyperbole is exaggeration; onomatopoeia is sound-imitating words; a pun is a play on word meanings. This question echoes the green light in "The Great Gatsby" — a frequently-tested example.',
  },
  {
    id: 'dev-07',
    domain: 1,
    subdomain: 'Literary Devices & Figurative Language',
    type: 'single',
    difficulty: 'easy',
    question: '"Peter Piper picked a peck of pickled peppers." Which device dominates this line?',
    options: [
      'Hyperbole',
      'Alliteration',
      'Personification',
      'Simile',
    ],
    correctAnswers: [1],
    explanation: 'Alliteration is the repetition of the same initial consonant sound across nearby words — here the "p" sound in Peter, Piper, picked, peck, pickled, peppers. Hyperbole would be exaggeration; personification would give human qualities to non-human things; a simile would use "like" or "as." Tongue twisters are extreme cases of alliteration.',
  },
  {
    id: 'dev-08',
    domain: 1,
    subdomain: 'Literary Devices & Figurative Language',
    type: 'single',
    difficulty: 'medium',
    question: 'A character in a novel says, sarcastically, "Oh, perfect — another flat tire." This is an example of —',
    options: [
      'Situational irony',
      'Verbal irony',
      'Dramatic irony',
      'Foreshadowing',
    ],
    correctAnswers: [1],
    explanation: 'Verbal irony is when a speaker says the opposite of what they mean — usually sarcastically. The character does not actually think a flat tire is "perfect." Situational irony would be an unexpected outcome (a tire-store owner getting a flat tire). Dramatic irony depends on the audience knowing more than the character. Foreshadowing hints at future events.',
  },
  {
    id: 'dev-09',
    domain: 1,
    subdomain: 'Literary Devices & Figurative Language',
    type: 'single',
    difficulty: 'medium',
    question: 'The lifeguard, who could not swim, drowned during a rescue attempt. This outcome is BEST described as —',
    options: [
      'Verbal irony',
      'Dramatic irony',
      'Situational irony',
      'No irony at all',
    ],
    correctAnswers: [2],
    explanation: 'Situational irony is when the outcome is the OPPOSITE of what one would reasonably expect. Lifeguards are expected to rescue swimmers — having one drown reverses that expectation. Verbal irony involves saying the opposite of what you mean; dramatic irony depends on a knowledge gap between audience and character. The outcome itself being unexpected is the giveaway for situational irony.',
  },
  {
    id: 'dev-10',
    domain: 1,
    subdomain: 'Literary Devices & Figurative Language',
    type: 'yesno',
    difficulty: 'easy',
    question: 'In the line "The buzzing bees made me sleepy," does the word "buzzing" use onomatopoeia?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. Onomatopoeia uses words that imitate the sounds they describe — "buzz," "hiss," "crash," "click," "pop." The word "buzzing" mimics the actual sound bees make. Onomatopoeia is one of the easier devices to identify because the word and the sound share the same shape.',
  },
  {
    id: 'dev-11',
    domain: 1,
    subdomain: 'Literary Devices & Figurative Language',
    type: 'single',
    difficulty: 'hard',
    question: 'Read the excerpt: "Hope is the thing with feathers / That perches in the soul." (Emily Dickinson) This passage primarily uses —',
    options: [
      'A simile comparing hope to feathers',
      'An extended metaphor casting hope as a bird',
      'Onomatopoeia',
      'A literal description of a bird',
    ],
    correctAnswers: [1],
    explanation: 'Dickinson does not use "like" or "as," so the comparison is metaphor, not simile. She extends the comparison ("thing with feathers," "perches in the soul") rather than stopping at one line — that is the definition of an extended metaphor. Onomatopoeia would require sound-imitating words; a literal description would mean Dickinson is talking about an actual bird, which the line does not support.',
  },
  {
    id: 'dev-12',
    domain: 1,
    subdomain: 'Literary Devices & Figurative Language',
    type: 'single',
    difficulty: 'medium',
    question: 'Which sentence uses an ALLUSION?',
    options: [
      'The rain hammered the roof for hours.',
      'He had the patience of Job throughout the long delay.',
      'She laughed until she cried.',
      'The wind whistled through the broken window.',
    ],
    correctAnswers: [1],
    explanation: 'An allusion is a brief reference to a well-known person, place, work, or event. "The patience of Job" alludes to the Bible — Job is famously patient. The other sentences use other devices (metaphor, hyperbole, personification) but do not point to outside texts or known figures. EOCEP allusions commonly reference Greek myth, Shakespeare, and the Bible.',
  },
  {
    id: 'dev-13',
    domain: 1,
    subdomain: 'Literary Devices & Figurative Language',
    type: 'single',
    difficulty: 'medium',
    question: 'A storm scene in a novel uses short, choppy sentences and harsh consonants ("crack," "smash," "thud"). The combined effect is most likely —',
    options: [
      'A peaceful, calming mood',
      'A tense, frightening mood',
      'A romantic, dreamy mood',
      'A neutral, informational mood',
    ],
    correctAnswers: [1],
    explanation: 'Short, choppy sentence rhythm + harsh consonant sounds create tension and unease, signaling a frightening mood. Mood is what the reader FEELS; here the sensory features push toward fear. A peaceful mood would use long, flowing sentences; a dreamy mood often uses soft consonants; informational writing avoids charged sensory language. Strong readers analyze rhythm AND word sound when discussing mood.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Author’s Craft & Structure
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'craft-01',
    domain: 1,
    subdomain: 'Author’s Craft & Structure',
    type: 'single',
    difficulty: 'easy',
    question: 'A short story is told entirely from the perspective of a child who does not understand what the adults around her are doing. This narration choice most clearly creates —',
    options: [
      'A reliable adult-perspective narrator',
      'An unreliable or limited narrator',
      'Third-person omniscient narration',
      'Second-person narration',
    ],
    correctAnswers: [1],
    explanation: 'A narrator whose understanding is incomplete or biased is unreliable or limited — the reader has to piece together what is really happening. An omniscient narrator knows all minds; second-person uses "you." The child\'s limited understanding is itself a craft choice that produces dramatic irony — the reader knows more than the narrator.',
  },
  {
    id: 'craft-02',
    domain: 1,
    subdomain: 'Author’s Craft & Structure',
    type: 'single',
    difficulty: 'easy',
    question: 'In Act I, a character casually mentions a hunting rifle hanging on the cabin wall. In Act III, that same rifle is used in the climactic scene. The mention in Act I is an example of —',
    options: [
      'Foreshadowing',
      'A logical fallacy',
      'Alliteration',
      'A counterclaim',
    ],
    correctAnswers: [0],
    explanation: 'Foreshadowing plants hints that pay off later. The early mention of the rifle prepares the reader for its later importance — the "Chekhov\'s gun" principle. A logical fallacy is a reasoning error; alliteration is a sound device; a counterclaim is an argument-writing concept. Foreshadowing is one of the most tested structural techniques on the EOCEP.',
  },
  {
    id: 'craft-03',
    domain: 1,
    subdomain: 'Author’s Craft & Structure',
    type: 'single',
    difficulty: 'medium',
    question: 'A novel opens with the protagonist looking back from old age, then jumps backward to her childhood for the rest of the story. This narrative structure is called a —',
    options: [
      'Flash-forward',
      'Flashback frame',
      'In medias res with no framing',
      'Stream of consciousness',
    ],
    correctAnswers: [1],
    explanation: 'When a story begins (and often ends) in a present-day frame and then jumps backward in time for the main narrative, the structure is called a flashback or framed narrative. A flash-forward would jump ahead, not backward. "In medias res" means starting in the middle of the action with no setup. Stream of consciousness is about HOW thoughts are presented, not narrative time order.',
  },
  {
    id: 'craft-04',
    domain: 1,
    subdomain: 'Author’s Craft & Structure',
    type: 'single',
    difficulty: 'medium',
    question: 'An author chooses to spend three pages describing a single five-minute scene of a character waiting for test results, then summarizes the next three months in a single paragraph. This deliberate variation is called —',
    options: [
      'A logical fallacy',
      'Narrative pacing',
      'Personification',
      'A counterclaim',
    ],
    correctAnswers: [1],
    explanation: 'Narrative pacing is the author\'s control of how much time the prose spends on each section of story-time. Stretching a five-minute moment over three pages while compressing three months into a paragraph signals what matters emotionally. A logical fallacy is a reasoning error; personification gives non-humans human traits; counterclaim is an argument-writing term.',
  },
  {
    id: 'craft-05',
    domain: 1,
    subdomain: 'Author’s Craft & Structure',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are valid reasons an author might choose FIRST-PERSON point of view? Select ALL that apply.',
    options: [
      'To give the reader intimate access to the narrator\'s thoughts and biases.',
      'To create an unreliable narrator whose perspective is limited.',
      'So the reader can know every character\'s thoughts simultaneously.',
      'To build a strong, distinctive narrative voice.',
    ],
    correctAnswers: [0, 1, 3],
    explanation: 'First-person POV creates intimacy with the narrator\'s mind, allows unreliable narration, and supports a distinctive voice. Access to EVERY character\'s mind, however, requires third-person omniscient — first-person is locked to one narrator\'s viewpoint. Authors choose POV deliberately; recognizing the trade-offs is a craft question on the EOCEP.',
  },
  {
    id: 'craft-06',
    domain: 1,
    subdomain: 'Author’s Craft & Structure',
    type: 'single',
    difficulty: 'medium',
    question: 'A nonfiction author opens her essay with a vivid, two-sentence story about her grandmother in a hospital waiting room. What is the most likely PURPOSE of this opening?',
    options: [
      'To document a primary source',
      'To hook the reader emotionally before presenting the main argument',
      'To provide MLA citation information',
      'To list the works cited',
    ],
    correctAnswers: [1],
    explanation: 'A short personal anecdote at the opening of an essay is a classic rhetorical "hook" — it engages the reader emotionally and sets up the main argument. Anecdotes do not function as primary-source documentation, MLA citations, or works-cited entries in expository writing. Recognizing structural choices like this is core craft analysis.',
  },
  {
    id: 'craft-07',
    domain: 1,
    subdomain: 'Author’s Craft & Structure',
    type: 'yesno',
    difficulty: 'easy',
    question: 'If an author repeats the same phrase at the beginning of three consecutive sentences for emphasis (for example, "We shall fight on the beaches, we shall fight on the landing grounds, we shall fight in the fields…"), is the author using ANAPHORA?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. Anaphora is the deliberate repetition of the same word or phrase at the beginning of successive clauses or sentences. It builds rhythm and emphasis — used famously by Churchill, MLK, and many speech writers. Anaphora is one of the rhetorical-craft techniques the EOCEP regularly asks about.',
  },
  {
    id: 'craft-08',
    domain: 1,
    subdomain: 'Author’s Craft & Structure',
    type: 'single',
    difficulty: 'medium',
    question: 'A nonfiction article includes the sentence, "Imagine waking up tomorrow with no clean water from the tap." Why does the author most likely choose this construction?',
    options: [
      'To present statistical data',
      'To invite the reader into a thought experiment that builds emotional investment',
      'To list works cited',
      'To create alliteration',
    ],
    correctAnswers: [1],
    explanation: 'Asking the reader to "imagine" a scenario is a craft choice that personalizes an abstract issue. By putting the reader in the situation, the author increases emotional investment before presenting evidence. It is not statistical writing, citation, or alliteration. Identifying WHY an author chose a particular sentence structure is a craft question.',
  },
  {
    id: 'craft-09',
    domain: 1,
    subdomain: 'Author’s Craft & Structure',
    type: 'single',
    difficulty: 'hard',
    question: 'A novel\'s narrator describes the same dinner party twice — once from the host\'s perspective and once from the guest\'s. The reader sees the same lines of dialogue but with very different interpretations of motive. This structural choice most clearly emphasizes —',
    options: [
      'The unreliability of any single perspective and the role of point of view in shaping truth',
      'That the author could not decide on one narrator',
      'A logical fallacy in the host\'s argument',
      'Onomatopoeia',
    ],
    correctAnswers: [0],
    explanation: 'Showing the same scene twice from different perspectives is a deliberate structural choice that highlights how point of view shapes interpretation. It is not authorial indecision — it is purposeful craft. There is no specific logical fallacy involved, and onomatopoeia is about sound. Multi-perspective narration is a sophisticated technique used in modern fiction to challenge single-narrator authority.',
  },
  {
    id: 'craft-10',
    domain: 1,
    subdomain: 'Author’s Craft & Structure',
    type: 'single',
    difficulty: 'medium',
    question: 'A speech ends with the line: "And so I ask you tonight: which world will we leave for our children?" The use of a question at the end is a deliberate rhetorical technique called —',
    options: [
      'A rhetorical question',
      'A simile',
      'An onomatopoeia',
      'A bandwagon appeal',
    ],
    correctAnswers: [0],
    explanation: 'A rhetorical question is asked for effect rather than to get a literal answer — it pushes the audience to supply the answer the speaker wants. It is not a simile (no comparison), not onomatopoeia (no sound-imitating word), and not a bandwagon (no appeal to "everyone is doing it"). Rhetorical questions in conclusions are common in persuasive speeches.',
  },
  {
    id: 'craft-11',
    domain: 1,
    subdomain: 'Author’s Craft & Structure',
    type: 'single',
    difficulty: 'medium',
    question: 'A poem is broken into three-line stanzas, with regular rhyme and a steady rhythm. These choices are examples of —',
    options: [
      'Poetic form and structure',
      'Logical fallacies',
      'Plagiarism',
      'Citation style',
    ],
    correctAnswers: [0],
    explanation: 'How a poem is broken into stanzas, its rhyme scheme, and its rhythm are all elements of poetic FORM and STRUCTURE — deliberate craft choices that shape meaning. Logical fallacies are reasoning errors in arguments; plagiarism is uncredited borrowing; citation style is research formatting. Poetry-form questions on the EOCEP test whether students can identify these structural features.',
  },
  {
    id: 'craft-12',
    domain: 1,
    subdomain: 'Author’s Craft & Structure',
    type: 'single',
    difficulty: 'medium',
    question: 'An author uses simple, plain language and short sentences throughout a story about a frightened child trying to find her mother. The DICTION choice most strongly supports the —',
    options: [
      'Authority of an academic argument',
      'Childlike voice and emotional immediacy of the narrator',
      'Use of MLA Works Cited',
      'Need for a counterclaim',
    ],
    correctAnswers: [1],
    explanation: 'Diction (word choice) and sentence length combine to produce voice. Plain words and short sentences support a childlike voice and emotional urgency. Academic authority would require precise, formal vocabulary and longer syntax. MLA Works Cited and counterclaims are argument-writing concepts, not narrative craft choices.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Argument & Evidence
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'arg-01',
    domain: 1,
    subdomain: 'Argument & Evidence',
    type: 'single',
    difficulty: 'easy',
    question: 'In a persuasive essay, the CLAIM is best described as —',
    options: [
      'An arguable statement that the author asks the reader to accept.',
      'A neutral fact that no one disputes.',
      'A direct quotation from an outside source.',
      'A logical fallacy.',
    ],
    correctAnswers: [0],
    explanation: 'A claim is an ARGUABLE statement — something a reasonable person could disagree with. Neutral facts are not claims (no one needs to be persuaded). Quotations are evidence, not claims themselves. A logical fallacy is a flaw in reasoning, not a claim. Strong essays make claims and then support them with evidence.',
  },
  {
    id: 'arg-02',
    domain: 1,
    subdomain: 'Argument & Evidence',
    type: 'single',
    difficulty: 'easy',
    question: 'A speaker says, "As a cardiologist with 30 years of experience, I can tell you these dietary guidelines work." This is an appeal to —',
    options: [
      'Ethos',
      'Pathos',
      'Logos',
      'Bandwagon',
    ],
    correctAnswers: [0],
    explanation: 'Ethos is an appeal based on the speaker\'s CREDIBILITY, character, or authority. Mentioning 30 years as a cardiologist asks the audience to trust the message because the messenger is qualified. Pathos appeals to emotion; logos appeals to logic and evidence; bandwagon appeals to popularity. Ethos is one of the three rhetorical appeals every EOCEP student must know.',
  },
  {
    id: 'arg-03',
    domain: 1,
    subdomain: 'Argument & Evidence',
    type: 'single',
    difficulty: 'easy',
    question: 'A speech includes the line, "Imagine your own child going to bed hungry tonight." This sentence appeals most directly to —',
    options: [
      'Ethos',
      'Pathos',
      'Logos',
      'Anaphora',
    ],
    correctAnswers: [1],
    explanation: 'Pathos is an appeal to emotion. Asking listeners to imagine their child going to bed hungry stirs empathy, fear, and protective instincts. Ethos would invoke credentials; logos would cite statistics; anaphora would repeat a phrase. Strong persuasive writing uses pathos but balances it with logos and ethos — pathos alone can feel manipulative.',
  },
  {
    id: 'arg-04',
    domain: 1,
    subdomain: 'Argument & Evidence',
    type: 'single',
    difficulty: 'medium',
    question: 'A study reports that "in 12,000 students surveyed, students who slept at least 8 hours had test scores 22% higher on average." Citing this study is primarily an appeal to —',
    options: [
      'Ethos',
      'Pathos',
      'Logos',
      'Hyperbole',
    ],
    correctAnswers: [2],
    explanation: 'Logos is an appeal to LOGIC and EVIDENCE — statistics, studies, structured reasoning. Citing a 12,000-student study with specific numerical findings is textbook logos. Ethos would emphasize the credentials of the researcher; pathos would emphasize emotional consequences; hyperbole is exaggeration. Skilled writers combine logos with the other two appeals.',
  },
  {
    id: 'arg-05',
    domain: 1,
    subdomain: 'Argument & Evidence',
    type: 'single',
    difficulty: 'medium',
    question: 'A writer claims, "Students should be allowed to bring phones to class. If we ban phones now, soon we will be told what books to read, what to wear, and what to think." This argument is an example of —',
    options: [
      'Strong logical reasoning',
      'A slippery slope fallacy',
      'A counterclaim',
      'A primary source',
    ],
    correctAnswers: [1],
    explanation: 'A slippery slope fallacy assumes one small step will inevitably lead to a chain of dramatic negative consequences without evidence linking the steps. Banning phones does not automatically lead to controlling books, clothes, and thought. The argument may FEEL convincing, but it is not logically sound. Strong reasoning requires evidence at each link of a causal chain.',
  },
  {
    id: 'arg-06',
    domain: 1,
    subdomain: 'Argument & Evidence',
    type: 'single',
    difficulty: 'medium',
    question: 'A debater says, "We should not listen to her safety proposal — she has only been driving for two years." This kind of attack is an example of which fallacy?',
    options: [
      'Ad hominem',
      'False dichotomy',
      'Bandwagon',
      'Strawman',
    ],
    correctAnswers: [0],
    explanation: 'Ad hominem ("to the person") is a fallacy that attacks the speaker instead of the argument itself. Whether or not the speaker has driven for two years has no necessary bearing on whether her safety proposal is sound. The argument has to be evaluated on its own merits. False dichotomy presents only two options; bandwagon appeals to popularity; strawman distorts an opponent\'s position.',
  },
  {
    id: 'arg-07',
    domain: 1,
    subdomain: 'Argument & Evidence',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are STRONG, well-supported pieces of evidence for the claim "Reading 20 minutes a day improves teen reading test scores"? Select ALL that apply.',
    options: [
      'A peer-reviewed study of 5,000 teens that tracked daily reading habits and test scores over four years.',
      'A blog post by an anonymous author claiming reading helped them.',
      'A statement from the National Council of Teachers of English.',
      'A meme shared 100,000 times on social media.',
      'A government Department of Education report on reading habits and test outcomes.',
    ],
    correctAnswers: [0, 2, 4],
    explanation: 'The strongest evidence comes from peer-reviewed studies, expert professional organizations, and credible government reports. Anonymous blog posts and viral memes are not credible sources — they are anecdotal or unverified. The CRAAP test (Currency, Relevance, Authority, Accuracy, Purpose) helps evaluate which sources to trust. Choose evidence with verifiable authority and methodology.',
  },
  {
    id: 'arg-08',
    domain: 1,
    subdomain: 'Argument & Evidence',
    type: 'single',
    difficulty: 'medium',
    question: 'In an argumentative essay, a COUNTERCLAIM is best described as —',
    options: [
      'A logical fallacy made by the author',
      'A position OPPOSED to the writer\'s main argument that the writer should name and rebut',
      'A quotation from a primary source',
      'A topic sentence',
    ],
    correctAnswers: [1],
    explanation: 'A counterclaim is an opposing argument that the writer DELIBERATELY names and then answers (rebuts). Strong argumentative writing acknowledges that other reasonable positions exist and explains why the writer\'s position is better. Skipping the counterclaim makes writing seem one-sided. A counterclaim is not a fallacy, a source quotation, or a topic sentence — though all of those may appear in the same essay.',
  },
  {
    id: 'arg-09',
    domain: 1,
    subdomain: 'Argument & Evidence',
    type: 'single',
    difficulty: 'easy',
    question: '"Either we cut the arts program or our test scores will fall." This argument structure is an example of —',
    options: [
      'A false dichotomy',
      'A strong logical claim',
      'A simile',
      'A primary source',
    ],
    correctAnswers: [0],
    explanation: 'A false dichotomy presents only two options when more exist. Cutting arts and falling test scores are not the only two possible outcomes — better scheduling, supplementary tutoring, or reallocating other funds could be alternatives. Recognizing "either/or" framing as a possible fallacy is an EOCEP-tested critical-reading skill.',
  },
  {
    id: 'arg-10',
    domain: 1,
    subdomain: 'Argument & Evidence',
    type: 'single',
    difficulty: 'medium',
    question: 'Read the claim: "We must invest in solar energy now because reliable expert estimates project we will reduce CO₂ output by 40% over a decade." The phrase "reliable expert estimates project" suggests the author is using —',
    options: [
      'Logos supported by expert authority',
      'Pure pathos',
      'A bandwagon appeal',
      'A strawman fallacy',
    ],
    correctAnswers: [0],
    explanation: 'The author is citing expert projections (an appeal to authority — overlapping with ethos) and using a specific numerical claim (40% reduction over a decade — logos). This combination of logical evidence and expert credibility is a hallmark of strong argumentative writing. It is not pathos (no emotional appeal), bandwagon (no "everyone is doing it"), or strawman (no distorted opposing claim).',
  },
  {
    id: 'arg-11',
    domain: 1,
    subdomain: 'Argument & Evidence',
    type: 'yesno',
    difficulty: 'easy',
    question: 'A claim that "everyone is doing it, so it must be right" is a logical fallacy known as the BANDWAGON fallacy. Is that correct?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes. The bandwagon fallacy argues that something is correct because many people believe or do it. Popularity is not the same as truth — millions of people once believed the earth was flat. On the EOCEP, watch for advertising and political language that leans on "everyone is switching" or "join the millions."',
  },
  {
    id: 'arg-12',
    domain: 1,
    subdomain: 'Argument & Evidence',
    type: 'single',
    difficulty: 'hard',
    question: 'A writer argues for later school start times. She presents one personal story about her own tired sibling and no other evidence. Which is the MOST VALID critique of her argument?',
    options: [
      'The anecdote alone is too narrow — she needs broader evidence such as studies or statistics to support a policy-level claim.',
      'Anecdotes are never allowed in argumentative writing.',
      'Her grammar must be wrong.',
      'Personal stories are stronger than studies.',
    ],
    correctAnswers: [0],
    explanation: 'Anecdotes CAN be effective opening hooks or emotional support, but a policy claim about all students needs broader evidence — controlled studies, statistics, expert reports. Saying anecdotes are NEVER allowed is too strong; they have a place. Claiming her grammar is wrong is irrelevant to the argument\'s logic. Saying anecdotes outweigh studies reverses what credible evidence looks like.',
  },
  {
    id: 'arg-13',
    domain: 1,
    subdomain: 'Argument & Evidence',
    type: 'single',
    difficulty: 'medium',
    question: 'A speaker argues, "If you really cared about our community, you would vote yes on the school bond." This is closest to which fallacy?',
    options: [
      'A bandwagon fallacy',
      'A guilt-trip appeal (a form of pathos used dishonestly)',
      'A strong logical argument',
      'A counterclaim',
    ],
    correctAnswers: [1],
    explanation: 'Equating disagreement with not caring is a manipulative emotional appeal — a guilt-trip form of pathos. It conflates one specific policy choice (voting yes) with the listener\'s entire moral standing. It is not bandwagon (no appeal to popularity), not a strong logical argument, and not a counterclaim. Recognizing emotional manipulation in arguments is a 10th-grade-level skill.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Language Conventions
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'lang-01',
    domain: 1,
    subdomain: 'Language Conventions',
    type: 'single',
    difficulty: 'easy',
    question: 'Which sentence is punctuated CORRECTLY?',
    options: [
      'My brother loves hiking, he goes every weekend.',
      'My brother loves hiking he goes every weekend.',
      'My brother loves hiking; he goes every weekend.',
      'My brother loves hiking. He goes, every weekend.',
    ],
    correctAnswers: [2],
    explanation: 'A semicolon correctly joins two independent clauses. The first option is a COMMA SPLICE (comma joining two independent clauses — wrong); the second is a RUN-ON (no punctuation at all between the clauses — wrong); the fourth has a misplaced comma after "goes." A semicolon, a period, or a comma + coordinating conjunction (FANBOYS) are the three valid ways to join two independent clauses.',
  },
  {
    id: 'lang-02',
    domain: 1,
    subdomain: 'Language Conventions',
    type: 'single',
    difficulty: 'easy',
    question: 'Which sentence shows correct SUBJECT-VERB AGREEMENT?',
    options: [
      'The box of cookies are on the table.',
      'The box of cookies is on the table.',
      'The box of cookies were on the table.',
      'The box of cookies be on the table.',
    ],
    correctAnswers: [1],
    explanation: 'The subject is "box" (singular), not "cookies" — "of cookies" is a prepositional phrase that does not change the subject. A singular subject takes a singular verb: "is." The other options use plural verbs ("are," "were") or a non-standard form ("be"). The trick on the EOCEP is to ignore intervening prepositional phrases when finding the real subject.',
  },
  {
    id: 'lang-03',
    domain: 1,
    subdomain: 'Language Conventions',
    type: 'single',
    difficulty: 'easy',
    question: 'Which sentence uses the APOSTROPHE correctly?',
    options: [
      'The student\'s book was on the desk. (one student)',
      'The students\' book was on the desk. (one student)',
      'The students book\'s was on the desk.',
      'The student\'s books\' was on the desk.',
    ],
    correctAnswers: [0],
    explanation: 'For a single owner, add \'s: the student\'s book (the book belonging to one student). For multiple owners ending in -s, add only the apostrophe: the students\' book (book belonging to several students). The other options either put the apostrophe on the wrong noun or stack apostrophes incorrectly. Apostrophes signal possession or contractions — not plurals.',
  },
  {
    id: 'lang-04',
    domain: 1,
    subdomain: 'Language Conventions',
    type: 'single',
    difficulty: 'medium',
    question: 'Which sentence has PARALLEL structure?',
    options: [
      'She likes reading, writing, and to edit.',
      'She likes reading, writing, and editing.',
      'She likes to read, writing, and editing.',
      'She likes reading, to write, and edits.',
    ],
    correctAnswers: [1],
    explanation: 'Parallelism uses the same grammatical form for items in a series. Option 2 uses three -ing forms ("reading, writing, editing") — consistent and parallel. The other options mix infinitives ("to edit," "to read," "to write") with -ing forms or shift to a present-tense verb ("edits"), breaking parallelism. Lists, pairs, and comparisons all need parallel structure.',
  },
  {
    id: 'lang-05',
    domain: 1,
    subdomain: 'Language Conventions',
    type: 'single',
    difficulty: 'medium',
    question: 'Which sentence contains a DANGLING MODIFIER?',
    options: [
      'Walking to school, I noticed the rain start.',
      'Walking to school, the rain started.',
      'While I walked to school, the rain started.',
      'The rain started while I walked to school.',
    ],
    correctAnswers: [1],
    explanation: '"Walking to school" is an introductory modifier that needs to attach to a noun that can do the walking. In option 2, the noun the phrase attaches to is "the rain" — implying the rain was walking to school. That is a dangling modifier. The other options either supply a correct subject ("I noticed") or restructure the sentence to avoid the dangling-modifier problem.',
  },
  {
    id: 'lang-06',
    domain: 1,
    subdomain: 'Language Conventions',
    type: 'single',
    difficulty: 'easy',
    question: 'Which option is a COMPLETE SENTENCE?',
    options: [
      'Because she was late to class.',
      'Running through the park.',
      'After the long, exhausting practice.',
      'She finished the assignment before the bell rang.',
    ],
    correctAnswers: [3],
    explanation: 'Option 4 contains a subject ("She"), a verb ("finished"), and expresses a complete thought. The others are sentence FRAGMENTS — option 1 is a dependent clause needing a main clause, options 2 and 3 are phrases without a complete thought. A fragment can be fixed by attaching it to a main clause or by adding missing parts.',
  },
  {
    id: 'lang-07',
    domain: 1,
    subdomain: 'Language Conventions',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following sentences are CORRECTLY constructed (no errors)? Select ALL that apply.',
    options: [
      'Neither the teacher nor the students were ready for the surprise quiz.',
      'Each of the students were nervous about the test.',
      'Either Maria or her brothers are bringing snacks.',
      'The committee have voted unanimously.',
    ],
    correctAnswers: [0, 2],
    explanation: 'With "neither/nor" or "either/or," the verb agrees with the closer subject — both option 1 ("students were") and option 3 ("brothers are") are correct. Option 2 is wrong: "Each" is singular, so it needs "was" not "were." Option 4 uses "committee" as plural ("have"), but in American English a collective noun like "committee" usually takes a singular verb ("has").',
  },
  {
    id: 'lang-08',
    domain: 1,
    subdomain: 'Language Conventions',
    type: 'single',
    difficulty: 'medium',
    question: 'Which sentence uses PRONOUN-ANTECEDENT agreement correctly?',
    options: [
      'Every player should bring their own water bottle.',
      'Every player should bring his or her own water bottle.',
      'Every player should bring its own water bottle.',
      'Every player should bring our own water bottle.',
    ],
    correctAnswers: [1],
    explanation: '"Every player" is singular, so the pronoun must be singular too — "his or her." (Singular "their" is increasingly accepted in modern English and may appear as a correct answer on some EOCEP versions, but "his or her" is unambiguously correct in formal writing.) "Its" treats the player as non-human, and "our" inappropriately shifts to first-person plural.',
  },
  {
    id: 'lang-09',
    domain: 1,
    subdomain: 'Language Conventions',
    type: 'single',
    difficulty: 'medium',
    question: 'Which option is a COMPOUND-COMPLEX sentence?',
    options: [
      'I went home.',
      'I went home, and I ate dinner.',
      'Because I was tired, I went home.',
      'Because I was tired, I went home, and I ate dinner.',
    ],
    correctAnswers: [3],
    explanation: 'A compound-complex sentence has at least TWO independent clauses AND at least one dependent clause. Option 4 has the dependent clause "Because I was tired" plus two independent clauses ("I went home" and "I ate dinner"). Option 1 is simple, option 2 is compound, and option 3 is complex. Knowing these four sentence types is essential for the EOCEP grammar section.',
  },
  {
    id: 'lang-10',
    domain: 1,
    subdomain: 'Language Conventions',
    type: 'single',
    difficulty: 'easy',
    question: 'Which sentence uses COMMAS correctly to set off a non-restrictive clause?',
    options: [
      'My oldest sister who lives in Charleston is a teacher.',
      'My oldest sister, who lives in Charleston, is a teacher.',
      'My oldest sister, who lives in Charleston is a teacher.',
      'My oldest sister who lives in Charleston, is a teacher.',
    ],
    correctAnswers: [1],
    explanation: 'A non-restrictive clause adds extra (non-essential) information and is set off by a PAIR of commas. Option 2 surrounds "who lives in Charleston" with two commas — correct. Options 3 and 4 have only one comma and create a punctuation imbalance; option 1 omits commas, treating the clause as restrictive (essential to identifying which sister). The EOCEP tests this rule frequently.',
  },
  {
    id: 'lang-11',
    domain: 1,
    subdomain: 'Language Conventions',
    type: 'single',
    difficulty: 'medium',
    question: 'Which sentence avoids a COMMA SPLICE?',
    options: [
      'I finished my essay, I went to bed.',
      'I finished my essay; I went to bed.',
      'I finished my essay I went to bed.',
      'I finished my essay then I went to bed.',
    ],
    correctAnswers: [1],
    explanation: 'A comma splice joins two independent clauses with ONLY a comma. Option 1 is a classic comma splice. Option 3 is a run-on (no punctuation). Option 4 is also a run-on — "then" is not a coordinating conjunction. Option 2 fixes the join with a semicolon, which is grammatically valid. Other valid fixes: a period, or a comma + coordinating conjunction (FANBOYS).',
  },
  {
    id: 'lang-12',
    domain: 1,
    subdomain: 'Language Conventions',
    type: 'single',
    difficulty: 'medium',
    question: 'In the sentence "Although the storm was severe, the school remained open," the dependent clause is —',
    options: [
      '"the school remained open"',
      '"Although the storm was severe"',
      '"the storm"',
      '"the school"',
    ],
    correctAnswers: [1],
    explanation: 'A dependent clause has a subject and verb but cannot stand alone as a complete sentence — it relies on the rest of the sentence. "Although the storm was severe" has a subject (storm) and verb (was) but starts with the subordinating conjunction "Although," making it dependent. "The school remained open" is the independent clause. The other options are noun phrases, not clauses.',
  },
  {
    id: 'lang-13',
    domain: 1,
    subdomain: 'Language Conventions',
    type: 'single',
    difficulty: 'easy',
    question: 'Which word in this sentence is an ADVERB? "She quickly finished the long, important essay."',
    options: [
      'finished',
      'quickly',
      'long',
      'essay',
    ],
    correctAnswers: [1],
    explanation: '"Quickly" describes HOW she finished — modifying the verb. Adverbs typically end in -ly and modify verbs, adjectives, or other adverbs. "Finished" is a verb; "long" is an adjective modifying "essay"; "essay" is a noun. Many EOCEP grammar questions ask you to identify parts of speech in a given sentence.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Vocabulary in Context
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'vocab-01',
    domain: 1,
    subdomain: 'Vocabulary in Context',
    type: 'single',
    difficulty: 'easy',
    question: 'Read the sentence: "Her TENACITY in the face of repeated failure inspired her teammates." Based on context, TENACITY most nearly means —',
    options: [
      'Laziness',
      'Persistence',
      'Arrogance',
      'Sadness',
    ],
    correctAnswers: [1],
    explanation: 'The context — "in the face of repeated failure" and "inspired her teammates" — signals a positive trait of refusing to give up. That is persistence. Laziness would not inspire anyone; arrogance is unrelated to failure-resilience; sadness is an emotion, not a character trait that inspires teammates. Always use surrounding context to triangulate meaning, not your gut on the word alone.',
  },
  {
    id: 'vocab-02',
    domain: 1,
    subdomain: 'Vocabulary in Context',
    type: 'single',
    difficulty: 'easy',
    question: 'Read the sentence: "The TRANSIENT visitors stayed only one night before driving on to the next town." Based on context, TRANSIENT most nearly means —',
    options: [
      'Permanent',
      'Loud',
      'Temporary or passing through',
      'Wealthy',
    ],
    correctAnswers: [2],
    explanation: '"Stayed only one night before driving on" signals that the visitors were temporary, not permanent. TRANSIENT shares a root with "transit" (passing through). Permanent is the opposite; loud and wealthy do not match the context cue about duration. EOCEP vocabulary questions are nearly always solvable with careful context reading.',
  },
  {
    id: 'vocab-03',
    domain: 1,
    subdomain: 'Vocabulary in Context',
    type: 'single',
    difficulty: 'easy',
    question: 'The prefix UN- in "unbelievable" means —',
    options: [
      'More',
      'Not',
      'Before',
      'Without',
    ],
    correctAnswers: [1],
    explanation: 'UN- is a common English prefix meaning "not" — unbelievable = not believable, unhappy = not happy, unsafe = not safe. "More" is a comparative (-er); "before" is PRE-; "without" is a separate word, sometimes signaled by the suffix -less or the prefix A-. Knowing prefixes lets you decode hundreds of unfamiliar words.',
  },
  {
    id: 'vocab-04',
    domain: 1,
    subdomain: 'Vocabulary in Context',
    type: 'single',
    difficulty: 'medium',
    question: 'Read the sentence: "Despite the BENEVOLENT smile she gave her younger brother, Maria still grabbed the last cookie." The contrast set up by "Despite" suggests BENEVOLENT most nearly means —',
    options: [
      'Cruel',
      'Kind or well-meaning',
      'Confused',
      'Loud',
    ],
    correctAnswers: [1],
    explanation: '"Despite" signals a contrast: a benevolent smile is the OPPOSITE of grabbing the last cookie. So benevolent must mean kind or well-meaning. The Latin root "bene-" means "good" (as in beneficial, benefit). Cruel is the opposite; confused and loud do not match the contrast structure. Use contrast cues like "despite," "however," and "although" as vocabulary tools.',
  },
  {
    id: 'vocab-05',
    domain: 1,
    subdomain: 'Vocabulary in Context',
    type: 'single',
    difficulty: 'medium',
    question: 'The Greek root BIO- means "life." Which of the following best uses BIO- with that meaning?',
    options: [
      'Biology (the study of life)',
      'Biceps (two-headed muscle)',
      'Biennial (every two years)',
      'Bicycle (two wheels)',
    ],
    correctAnswers: [0],
    explanation: 'BIO- meaning "life" appears in biology (study of life), biography (writing about a life), biopsy (examination of living tissue). "Biceps," "biennial," and "bicycle" all use BI- meaning "two" — a different root that happens to look similar. Roots are powerful but require care: BI- and BIO- are different.',
  },
  {
    id: 'vocab-06',
    domain: 1,
    subdomain: 'Vocabulary in Context',
    type: 'single',
    difficulty: 'medium',
    question: 'Read the sentence: "The witness gave an ELUSIVE answer, refusing to commit to any specific time or place." ELUSIVE most nearly means —',
    options: [
      'Direct',
      'Hard to pin down or evasive',
      'Loud',
      'Honest',
    ],
    correctAnswers: [1],
    explanation: 'The sentence explains itself: "refusing to commit to any specific time or place" defines elusive — hard to pin down, evasive. Direct and honest are antonyms in this context; loud is unrelated. Watch for sentences that gloss difficult words right inside the same sentence — they give you the meaning for free.',
  },
  {
    id: 'vocab-07',
    domain: 1,
    subdomain: 'Vocabulary in Context',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following pairs have similar DENOTATIONS (literal meanings) but very different CONNOTATIONS (associations)? Select ALL that apply.',
    options: [
      'Childlike vs. childish',
      'Confident vs. arrogant',
      'House vs. home',
      'Sprint vs. dash',
    ],
    correctAnswers: [0, 1, 2],
    explanation: '"Childlike" denotes "having qualities of a child" but connotes innocence; "childish" shares the denotation but connotes immaturity. "Confident" and "arrogant" both mean self-assured but carry opposite emotional weight. "House" denotes a building; "home" connotes warmth and belonging. "Sprint" and "dash" are nearly synonymous in both denotation and connotation — minimal difference. Sensitive readers track connotation, not just denotation.',
  },
  {
    id: 'vocab-08',
    domain: 1,
    subdomain: 'Vocabulary in Context',
    type: 'single',
    difficulty: 'medium',
    question: 'The suffix -OLOGY means "the study of." Which word best uses -OLOGY with that meaning?',
    options: [
      'Geology (the study of the earth)',
      'Diary (a daily record)',
      'Magnify (to make larger)',
      'Helpful (full of help)',
    ],
    correctAnswers: [0],
    explanation: 'GEO- (earth) + -OLOGY (study of) = the study of the earth. -OLOGY is one of the most useful English suffixes: biology, psychology, geology, sociology, anthropology. The other options use unrelated word parts (diary uses DIA-; magnify uses MAGN-/MAGNI-; helpful uses -FUL). Combining root + suffix knowledge is a fast vocabulary-builder.',
  },
  {
    id: 'vocab-09',
    domain: 1,
    subdomain: 'Vocabulary in Context',
    type: 'yesno',
    difficulty: 'easy',
    question: 'Are "house" and "home" SYNONYMS in their literal denotation?',
    options: ['Yes', 'No'],
    correctAnswers: [0],
    explanation: 'Yes, in their literal (denotative) meaning, "house" and "home" both refer to a residential building. However, their CONNOTATIONS differ — "home" suggests warmth, family, belonging, while "house" is more neutral and structural. Recognizing that two words can share a denotation but carry different emotional weight is an important EOCEP-tested skill.',
  },
  {
    id: 'vocab-10',
    domain: 1,
    subdomain: 'Vocabulary in Context',
    type: 'single',
    difficulty: 'medium',
    question: 'Read the sentence: "Her ARDUOUS climb up the mountain left her exhausted, dehydrated, and limping." Based on context, ARDUOUS most nearly means —',
    options: [
      'Effortless',
      'Difficult or strenuous',
      'Brief',
      'Joyful',
    ],
    correctAnswers: [1],
    explanation: 'The consequences described — exhausted, dehydrated, limping — signal that the climb was very hard. ARDUOUS means difficult or strenuous. Effortless is the opposite; brief refers to duration, not difficulty; joyful does not match exhaustion and limping. Match the descriptive context to the meaning rather than guessing on the word in isolation.',
  },
  {
    id: 'vocab-11',
    domain: 1,
    subdomain: 'Vocabulary in Context',
    type: 'single',
    difficulty: 'hard',
    question: 'Read the sentence: "The film\'s ostensible message of unity masked a more cynical agenda underneath." OSTENSIBLE most nearly means —',
    options: [
      'Truly honest',
      'Appearing to be true, but not necessarily so',
      'Loud and clear',
      'Forgotten',
    ],
    correctAnswers: [1],
    explanation: 'The sentence contrasts "ostensible message" with the "more cynical agenda underneath" — signaling that ostensible means appearing to be true on the surface, while something different lies underneath. "Truly honest" would not need to be masked; "loud and clear" misses the surface/underneath contrast; "forgotten" does not match. OSTENSIBLE often appears in argument analysis on the EOCEP.',
  },
  {
    id: 'vocab-12',
    domain: 1,
    subdomain: 'Vocabulary in Context',
    type: 'single',
    difficulty: 'medium',
    question: 'Read the sentence: "The diplomat was praised for her ELOQUENCE during the speech." Knowing that "loqu-" is a Latin root meaning "speak," ELOQUENCE most likely means —',
    options: [
      'Skill in speaking',
      'Fear of speaking',
      'Refusal to speak',
      'Whispering loudly',
    ],
    correctAnswers: [0],
    explanation: 'LOQU-/LOC- is a Latin root for speaking. ELOQUENT = speaking well; ELOQUENCE = the quality of speaking well. The same root appears in loquacious (talkative), soliloquy (a solo speech), and colloquial (conversational). Fear of speaking would be GLOSSOPHOBIA; refusal to speak does not match a positive context like "praised."',
  },

  // ══════════════════════════════════════════════════════════════════
  // Writing & Revision
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'write-01',
    domain: 1,
    subdomain: 'Writing & Revision',
    type: 'single',
    difficulty: 'easy',
    question: 'A strong THESIS STATEMENT in an argumentative essay should —',
    options: [
      'State the topic without making a claim.',
      'Make a single, focused, ARGUABLE claim that previews the supporting reasons.',
      'Be the very last sentence of the conclusion.',
      'Include several quotations from outside sources.',
    ],
    correctAnswers: [1],
    explanation: 'A thesis statement is a single sentence (usually at the end of the introduction) that makes one focused, arguable claim and gives a quick preview of the supporting reasons. Stating the topic without a claim is too weak; the thesis belongs in the introduction, not the conclusion; quotations belong in body paragraphs, not the thesis. Weak: "Schools are important." Strong: "South Carolina schools should start no earlier than 8:30 AM because of sleep cycles, test scores, and traffic safety."',
  },
  {
    id: 'write-02',
    domain: 1,
    subdomain: 'Writing & Revision',
    type: 'single',
    difficulty: 'easy',
    question: 'A TOPIC SENTENCE in a body paragraph functions as —',
    options: [
      'A summary of the entire essay',
      'A mini-thesis announcing what THAT paragraph will prove',
      'A quotation from a primary source',
      'The works cited entry',
    ],
    correctAnswers: [1],
    explanation: 'A topic sentence is the first sentence of a body paragraph that states the paragraph\'s point — its mini-thesis. The body of the paragraph supplies evidence and analysis to support it. A topic sentence is not an essay summary, a quotation, or a works-cited entry. Strong topic sentences also connect back to the overall thesis.',
  },
  {
    id: 'write-03',
    domain: 1,
    subdomain: 'Writing & Revision',
    type: 'single',
    difficulty: 'medium',
    question: 'Which TRANSITION word most strongly signals a CONTRASTING idea between sentences?',
    options: [
      'Furthermore',
      'However',
      'In addition',
      'For example',
    ],
    correctAnswers: [1],
    explanation: '"However" signals a contrast or opposing turn. "Furthermore" and "in addition" add another point in the same direction; "for example" introduces an illustration. Skilled writers use precise transitions to guide the reader through the logic of an argument — picking the right one matters.',
  },
  {
    id: 'write-04',
    domain: 1,
    subdomain: 'Writing & Revision',
    type: 'single',
    difficulty: 'easy',
    question: 'In MLA format, an in-text citation for a quote from page 47 of a book by an author named Smith would look like —',
    options: [
      '(Smith 47)',
      '[Smith, 47]',
      'Smith says page 47',
      '"page 47 — Smith"',
    ],
    correctAnswers: [0],
    explanation: 'MLA in-text citations use parentheses with the author\'s last name and page number: (Smith 47). No comma between name and page number. The other options use brackets, words instead of parentheses, or non-MLA formatting. Citation style errors are common EOCEP traps in revision questions.',
  },
  {
    id: 'write-05',
    domain: 1,
    subdomain: 'Writing & Revision',
    type: 'single',
    difficulty: 'medium',
    question: 'A student writes: "The end result is that schools need to start later." Which is the most CONCISE rewrite of "The end result is"?',
    options: [
      'The result is',
      'The end-result outcome is',
      'In the eventual final result, the result is',
      'Resulting, the end is',
    ],
    correctAnswers: [0],
    explanation: '"End result" is redundant — a "result" is already at the end. "The result is" cuts the redundancy without losing meaning. The other options either pile on more redundancy or are ungrammatical. Concision is one of the most common EOCEP revision skills; cut wordy phrases like "due to the fact that" → "because," "in order to" → "to," "for the purpose of" → "for."',
  },
  {
    id: 'write-06',
    domain: 1,
    subdomain: 'Writing & Revision',
    type: 'single',
    difficulty: 'medium',
    question: 'Which sentence uses ACTIVE VOICE?',
    options: [
      'The cake was eaten by the children.',
      'The children ate the cake.',
      'The cake had been eaten.',
      'It was eaten.',
    ],
    correctAnswers: [1],
    explanation: 'In active voice, the subject performs the action: "The children ate the cake" — children (subject) ate (action). In passive voice, the subject RECEIVES the action: "The cake was eaten by the children." Active voice is usually clearer, more direct, and more concise. Passive voice has legitimate uses (when the doer is unknown or unimportant), but on revision, prefer active.',
  },
  {
    id: 'write-07',
    domain: 1,
    subdomain: 'Writing & Revision',
    type: 'multi',
    difficulty: 'medium',
    question: 'Which of the following are reasonable revisions to improve a draft? Select ALL that apply.',
    options: [
      'Sharpening the thesis to make it more specific',
      'Cutting redundant phrases',
      'Replacing weak verbs with vivid, precise verbs',
      'Adding random commas in every sentence',
      'Combining short, choppy sentences for better flow',
    ],
    correctAnswers: [0, 1, 2, 4],
    explanation: 'Good revision means sharpening claims, cutting redundancy, choosing stronger verbs, and varying sentence length and structure. Randomly adding commas would create errors, not improvements. Revision = big-picture rework (structure, evidence, argument); editing = surface-level fixes (grammar, spelling, punctuation). Both stages are important, but revise first.',
  },
  {
    id: 'write-08',
    domain: 1,
    subdomain: 'Writing & Revision',
    type: 'single',
    difficulty: 'easy',
    question: 'A solid INTRODUCTION paragraph in an argumentative essay usually contains —',
    options: [
      'Only a thesis statement, with no context',
      'A hook, brief context, and a thesis statement at the end',
      'All of the supporting evidence for every body paragraph',
      'The works cited list',
    ],
    correctAnswers: [1],
    explanation: 'A strong introduction starts with a hook (something to draw the reader in — a question, anecdote, statistic, vivid image), supplies brief context to orient the reader, and ends with a thesis statement that previews the argument. Supporting evidence belongs in body paragraphs; works cited goes at the end of the essay. Skipping the hook and context loses readers immediately.',
  },
  {
    id: 'write-09',
    domain: 1,
    subdomain: 'Writing & Revision',
    type: 'single',
    difficulty: 'medium',
    question: 'When paraphrasing a source, a writer must —',
    options: [
      'Copy the exact words but skip the citation',
      'Restate the IDEA in their own words AND cite the source',
      'Make up new information not in the source',
      'Avoid mentioning the source at all',
    ],
    correctAnswers: [1],
    explanation: 'Paraphrasing means restating someone else\'s ideas in your own words — but because the IDEA is still borrowed, you must cite the source. Copying exact words requires quotation marks AND a citation; either omission is plagiarism. Making up new information is fabrication. Skipping the citation entirely is plagiarism — the academic offense paraphrasing is supposed to avoid.',
  },
  {
    id: 'write-10',
    domain: 1,
    subdomain: 'Writing & Revision',
    type: 'single',
    difficulty: 'medium',
    question: 'A student\'s draft has a paragraph that abruptly changes topics mid-paragraph. The best revision is to —',
    options: [
      'Add a comma between the two ideas.',
      'Split the paragraph into two separate paragraphs, each focused on a single idea.',
      'Underline both sections in red.',
      'Delete the entire paragraph.',
    ],
    correctAnswers: [1],
    explanation: 'One topic per paragraph is a basic structural principle of strong writing. If a paragraph contains two distinct ideas, the cleanest revision is to split it in two. Adding a comma will not fix a paragraph-level structural problem. Underlining is a marking strategy, not a revision. Deleting the entire paragraph throws away potentially good material.',
  },
  {
    id: 'write-11',
    domain: 1,
    subdomain: 'Writing & Revision',
    type: 'single',
    difficulty: 'hard',
    question: 'Which of the following revisions BEST integrates a quoted source into a sentence?',
    options: [
      '"Sleep deprivation is dangerous" (Smith 22). Sleep deprivation is dangerous, this is supported.',
      'According to Smith, "Sleep deprivation is dangerous" (Smith 22).',
      'According to Smith, "sleep deprivation is dangerous" (22).',
      'Smith said, "Sleep deprivation is dangerous", quotation page 22.',
    ],
    correctAnswers: [2],
    explanation: 'Option 3 integrates the quote with a signal phrase ("According to Smith"), uses the quoted material smoothly, and follows MLA format with just the page number in parentheses (the author is already named in the signal phrase). Option 1 is a comma splice and awkward; option 2 repeats Smith\'s name unnecessarily; option 4 misuses commas and non-standard citation style.',
  },
  {
    id: 'write-12',
    domain: 1,
    subdomain: 'Writing & Revision',
    type: 'single',
    difficulty: 'medium',
    question: 'A CONCLUSION paragraph in an argumentative essay should —',
    options: [
      'Introduce brand-new evidence not seen earlier',
      'Restate the thesis in fresh wording, summarize key reasons, and offer a final insight or call to action',
      'Apologize for the writer\'s argument',
      'List every counterclaim the writer ignored',
    ],
    correctAnswers: [1],
    explanation: 'A strong conclusion echoes the thesis with new phrasing (don\'t copy-paste), briefly synthesizes the main reasons, and ends with a memorable closing thought, broader implication, or call to action. Introducing brand-new evidence is jarring; apologies undercut the argument; listing ignored counterclaims belongs in the body, where you can rebut them.',
  },
  {
    id: 'write-13',
    domain: 1,
    subdomain: 'Writing & Revision',
    type: 'single',
    difficulty: 'easy',
    question: 'Which best describes the difference between REVISING and EDITING?',
    options: [
      'They are the same thing.',
      'Revising is big-picture changes (organization, evidence, thesis); editing is sentence-level fixes (grammar, punctuation, spelling).',
      'Revising happens after editing.',
      'Editing always happens before drafting.',
    ],
    correctAnswers: [1],
    explanation: 'Revising = big-picture rework (organization, structure, evidence, argument). Editing = sentence-level cleanup (grammar, spelling, punctuation, word choice). Revise first — don\'t polish a sentence you might delete. Editing always happens AFTER drafting and revising. They are different stages of the writing process, not interchangeable.',
  },
  {
    id: 'write-14',
    domain: 1,
    subdomain: 'Writing & Revision',
    type: 'single',
    difficulty: 'medium',
    question: 'In an MLA Works Cited entry, which piece of information comes FIRST?',
    options: [
      'The page number',
      'The title of the article',
      'The author\'s last name (followed by first name)',
      'The publisher',
    ],
    correctAnswers: [2],
    explanation: 'MLA Works Cited entries begin with the author\'s last name, then first name — that\'s how the list stays alphabetized. The general MLA order is: Author. Title. Container, other contributors, version, number, publisher, publication date, location. Putting the page number or title first would break alphabetization. Memorize the author-first rule for the EOCEP\'s research-writing questions.',
  },
  {
    id: 'write-15',
    domain: 1,
    subdomain: 'Writing & Revision',
    type: 'single',
    difficulty: 'easy',
    question: 'A student\'s draft has the sentence: "The teacher gave the assignment to the students who were ready for it." Which is the most CONCISE revision?',
    options: [
      'The teacher gave the assignment to the students who at that moment were ready for it.',
      'The teacher gave the assignment to the ready students.',
      'The teacher gave it to them.',
      'The teacher gave the assignment to the students that were prepared in their readiness.',
    ],
    correctAnswers: [1],
    explanation: 'Replacing the long relative clause "who were ready for it" with the adjective "ready" tightens the sentence without losing meaning. Option 1 adds more words; option 3 is unclear (what does "it" and "them" refer to?); option 4 piles up redundancy ("prepared in their readiness"). Strong revision often replaces a clause with a single modifier — concision without sacrificing clarity.',
  },
  {
    id: 'write-16',
    domain: 1,
    subdomain: 'Writing & Revision',
    type: 'single',
    difficulty: 'medium',
    question: 'When a student is asked to EVALUATE the credibility of a website source, which approach is most appropriate?',
    options: [
      'Trust the source automatically if it has many pictures.',
      'Use the CRAAP test: check Currency, Relevance, Authority, Accuracy, and Purpose.',
      'Only use a source if a friend recommends it.',
      'Avoid all online sources because they are unreliable.',
    ],
    correctAnswers: [1],
    explanation: 'The CRAAP test is the standard checklist for evaluating sources: Currency (is it recent enough?), Relevance (does it match the topic?), Authority (who wrote it and what are their credentials?), Accuracy (are the claims verifiable?), Purpose (is it informing or persuading? is there bias?). Pictures, friend recommendations, and blanket avoidance are all flawed approaches.',
  },

  // ══════════════════════════════════════════════════════════════════
  // Extra mixed-subdomain questions to deepen the bank
  // ══════════════════════════════════════════════════════════════════
  {
    id: 'lit-14',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'medium',
    question: 'In a story, the protagonist refuses to leave her flooding hometown despite repeated warnings, because her late husband is buried there. This SETTING is most clearly contributing to —',
    options: [
      'A purely physical obstacle with no emotional weight',
      'The development of character motivation and theme',
      'An MLA citation',
      'A rhetorical fallacy',
    ],
    correctAnswers: [1],
    explanation: 'Setting in literature is not just background — it can drive character motivation and reinforce theme. The protagonist\'s ATTACHMENT to a specific place, because of memory and grief, both motivates her choices and develops thematic ideas about loyalty, loss, and home. MLA citation is a research term, and rhetorical fallacy belongs to argument writing — neither fits literary analysis here.',
  },
  {
    id: 'lit-15',
    domain: 1,
    subdomain: 'Reading Literature',
    type: 'single',
    difficulty: 'hard',
    question: 'A short story has two parallel plots: a young man learning to forgive his father, and a wildfire approaching the town\'s old growth forest. Both reach resolution at the same moment. This narrative choice most directly suggests that —',
    options: [
      'The author was running out of pages.',
      'The two plots are intentionally linked by theme, not just by timing.',
      'There is no climax in the story.',
      'The author is using a logical fallacy.',
    ],
    correctAnswers: [1],
    explanation: 'When two separate plots resolve simultaneously, skilled authors are signaling a thematic LINK — perhaps forgiveness and renewal, destruction and rebirth, letting old things burn so new growth can come. This is craft, not page-count panic. The story still has a climax (both, simultaneously). Logical fallacy is an argument-writing term, not a literary structure term.',
  },
  {
    id: 'info-13',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'easy',
    question: 'Read the excerpt: "Honeybees pollinate roughly one-third of the food crops Americans eat. Their population, however, has been declining for two decades." Which is the central idea of this opening?',
    options: [
      'Honeybees only eat flowers.',
      'Honeybees are essential to U.S. food supply, but their population is declining — a problem worth attention.',
      'Pollination is unrelated to food production.',
      'All bees sting humans.',
    ],
    correctAnswers: [1],
    explanation: 'The two-sentence opening establishes BOTH the importance of honeybees (one-third of food crops) AND the urgency of the issue (declining population). That combined claim — "essential resource is under threat" — is the central idea. The other options either contradict the text or are unrelated. Strong central-idea answers capture the FULL claim, not a single piece of it.',
  },
  {
    id: 'info-14',
    domain: 1,
    subdomain: 'Reading Informational Text',
    type: 'single',
    difficulty: 'medium',
    question: 'In a news article, the author writes, "After years of community organizing, the city council finally voted to fund the new library." The word "finally" suggests the author\'s tone is —',
    options: [
      'Indifferent',
      'Relieved or satisfied',
      'Sarcastic',
      'Confused',
    ],
    correctAnswers: [1],
    explanation: '"Finally" implies that the decision is overdue and welcome — a tone of relief or satisfaction. Indifferent would use neutral language; sarcasm would typically be paired with unmistakable cues (quotation marks, qualifiers, or contradictory framing); confused tone would express uncertainty. Word choice (diction) is a primary clue to author tone in nonfiction writing.',
  },
  {
    id: 'dev-14',
    domain: 1,
    subdomain: 'Literary Devices & Figurative Language',
    type: 'single',
    difficulty: 'medium',
    question: 'In the poem fragment "The fog comes / on little cat feet" (Carl Sandburg), which TWO devices are at work?',
    options: [
      'Metaphor and personification',
      'Bandwagon and false dichotomy',
      'Simile only',
      'Onomatopoeia and hyperbole',
    ],
    correctAnswers: [0],
    explanation: 'Sandburg fuses fog with a cat without "like" or "as" — that is a metaphor. He also gives the fog a non-human ability (coming on cat feet) — that is personification. There is no "like"/"as" for a simile, no exaggeration for hyperbole, and no sound-imitating words for onomatopoeia. The two work together to make an abstract weather phenomenon feel quietly stealthy.',
  },
  {
    id: 'craft-13',
    domain: 1,
    subdomain: 'Author’s Craft & Structure',
    type: 'single',
    difficulty: 'medium',
    question: 'A novel begins with an unnamed narrator describing a long-ago summer using vivid, sensory imagery and present-tense verbs. The author\'s choice of TENSE most likely creates a feeling of —',
    options: [
      'Distance and abstraction',
      'Immediacy, as if the events are happening right now',
      'Confusion about when events occur',
      'Indifference',
    ],
    correctAnswers: [1],
    explanation: 'Present tense gives a sense of immediacy and presence — the reader experiences the events as if they are unfolding now, even if the framing says "long ago." Past tense would create more distance. Confusion is not the goal of skilled writers; indifference would be created by sparse, neutral language. Tense is a craft choice with emotional effects.',
  },
  {
    id: 'arg-14',
    domain: 1,
    subdomain: 'Argument & Evidence',
    type: 'single',
    difficulty: 'medium',
    question: 'A writer claims that a new school policy is bad. Her evidence consists of one anonymous online comment from a parent. The MAIN weakness of this evidence is that it is —',
    options: [
      'Anecdotal, anonymous, and unverifiable — insufficient to support a policy-level claim',
      'Too statistical',
      'Too well-sourced',
      'In MLA format',
    ],
    correctAnswers: [0],
    explanation: 'An anonymous online comment from one parent is the weakest possible category of evidence: anecdotal (one case), anonymous (cannot verify authority), and unverifiable (no way to confirm truth). A policy-level claim needs broad, credible evidence — controlled studies, surveys, expert commentary, government data. Strong critical readers recognize weak evidence even when they agree with the conclusion.',
  },
  {
    id: 'lang-14',
    domain: 1,
    subdomain: 'Language Conventions',
    type: 'single',
    difficulty: 'medium',
    question: 'Which sentence is correctly punctuated to set off a NON-RESTRICTIVE appositive?',
    options: [
      'My brother, the engineer, lives in Charleston.',
      'My brother the engineer, lives in Charleston.',
      'My brother, the engineer lives in Charleston.',
      'My brother the engineer lives in Charleston.',
    ],
    correctAnswers: [0],
    explanation: 'An appositive is a noun phrase that renames or describes another noun. A non-restrictive appositive (giving non-essential information) is set off by a pair of commas: "My brother, the engineer, lives in Charleston" (assuming you have only one brother — so "the engineer" is extra info). Half-comma punctuation creates an imbalance; no commas would suggest you have multiple brothers and "the engineer" identifies which one.',
  },
  {
    id: 'lang-15',
    domain: 1,
    subdomain: 'Language Conventions',
    type: 'single',
    difficulty: 'easy',
    question: 'Identify the PREPOSITION in this sentence: "She walked across the bridge before sunset."',
    options: [
      'walked',
      'across',
      'bridge',
      'sunset',
    ],
    correctAnswers: [1],
    explanation: 'Prepositions show relationships of time, place, or direction between nouns and other parts of the sentence. "Across" shows the relationship between "walked" and "the bridge." "Before" is also a preposition here (time relationship). "Walked" is a verb; "bridge" and "sunset" are nouns. Common prepositions: in, on, at, of, to, with, for, from, by, across, before, after, under, over.',
  },
  {
    id: 'vocab-13',
    domain: 1,
    subdomain: 'Vocabulary in Context',
    type: 'single',
    difficulty: 'medium',
    question: 'Read the sentence: "The judge\'s IMPARTIAL ruling pleased neither side, which suggested she had decided the case on the law and not on personal feelings." IMPARTIAL most nearly means —',
    options: [
      'Biased toward one side',
      'Fair and unbiased',
      'Confused',
      'Angry',
    ],
    correctAnswers: [1],
    explanation: 'The phrase "pleased neither side" and "decided on the law and not on personal feelings" both signal that the judge was even-handed and unbiased. IMPARTIAL means fair and free from favoritism. The IM- prefix means "not" and -PARTIAL means "biased toward a part/side" — so impartial literally means "not biased." Biased is the opposite; confused and angry do not fit.',
  },
  {
    id: 'vocab-14',
    domain: 1,
    subdomain: 'Vocabulary in Context',
    type: 'single',
    difficulty: 'medium',
    question: 'Read the sentence: "Despite her DILIGENT preparation, she still felt nervous before the speech." DILIGENT most nearly means —',
    options: [
      'Careless',
      'Persistent and hardworking',
      'Brief',
      'Loud',
    ],
    correctAnswers: [1],
    explanation: 'A DILIGENT preparation is one done with persistent effort and care. The context — "Despite" + "still felt nervous" — suggests her preparation was thorough but did not eliminate nerves. Careless is the opposite; brief refers to duration, not quality; loud is unrelated. Diligent often pairs with words like "study," "work," "research" — careful and sustained effort.',
  },
];
